// cities.js — Western Massachusetts city data for SEO landing pages
// median_price: approximate 2024-2025 median single-family home price
// realtor_count: estimated active agents in area (used in copy)

const cities = [
    {
        slug: 'springfield',
        name: 'Springfield',
        county: 'Hampden',
        state: 'MA',
        zip: '01101',
        population: '155,000',
        median_price: '$235,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'the largest city in western Massachusetts and the commercial hub of the Pioneer Valley',
        neighborhoods: 'Forest Park, East Forest Park, Sixteen Acres, Indian Orchard, and the South End',
        nearby: 'Longmeadow, Chicopee, West Springfield, and Agawam',
        seller_hook: 'Springfield\'s competitive market means your home can attract multiple realtor bids — driving better commission rates and faster service.',
        realtor_hook: 'Springfield has one of the highest listing volumes in western MA. Get ahead of new listings before they hit Zillow.',
    },
    {
        slug: 'northampton',
        name: 'Northampton',
        county: 'Hampshire',
        state: 'MA',
        zip: '01060',
        population: '28,000',
        median_price: '$425,000',
        price_trend: 'up 12%',
        avg_dom: 14,
        description: 'a vibrant college city and the county seat of Hampshire County, known for its arts scene, Smith College, and high quality of life',
        neighborhoods: 'Florence, Leeds, Bay State, Williamsburg Road, and downtown Northampton',
        nearby: 'Easthampton, Amherst, Hadley, and South Hadley',
        seller_hook: 'Northampton\'s low days-on-market means motivated buyers are ready — and competitive realtors will fight for your listing.',
        realtor_hook: 'Northampton\'s premium market and fast-moving inventory reward agents who move quickly. Be first to bid on new listings.',
    },
    {
        slug: 'amherst',
        name: 'Amherst',
        county: 'Hampshire',
        state: 'MA',
        zip: '01002',
        population: '39,000',
        median_price: '$395,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'a college town home to UMass Amherst, Amherst College, and Hampshire College — with a diverse, educated community and strong rental demand',
        neighborhoods: 'North Amherst, South Amherst, East Amherst, and the Amherst Center',
        nearby: 'Northampton, Hadley, Belchertown, and Pelham',
        seller_hook: 'Strong student and faculty demand keeps Amherst\'s market competitive year-round — get multiple realtors competing for your listing.',
        realtor_hook: 'Amherst\'s university-driven market generates consistent buyer demand. Secure listings before the semester rush.',
    },
    {
        slug: 'holyoke',
        name: 'Holyoke',
        county: 'Hampden',
        state: 'MA',
        zip: '01040',
        population: '40,000',
        median_price: '$215,000',
        price_trend: 'up 11%',
        avg_dom: 28,
        description: 'a historic mill city on the Connecticut River experiencing significant revitalization, with affordable home prices and a growing arts and tech scene',
        neighborhoods: 'The Highlands, Elmwood, Oakdale, Churchill, and downtown',
        nearby: 'Chicopee, Springfield, South Hadley, and Easthampton',
        seller_hook: 'Holyoke\'s rising values mean now is an ideal time to sell — let realtors compete for the right to represent your home.',
        realtor_hook: 'Holyoke\'s affordability is driving strong buyer interest. A growing inventory of listings means opportunity for active agents.',
    },
    {
        slug: 'chicopee',
        name: 'Chicopee',
        county: 'Hampden',
        state: 'MA',
        zip: '01013',
        population: '56,000',
        median_price: '$255,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'a diverse suburb of Springfield with affordable home prices, excellent highway access, and a strong working-class community',
        neighborhoods: 'Aldenville, Fairview, Willimansett, Chicopee Falls, and Chicopee Center',
        nearby: 'Springfield, Holyoke, Ludlow, and Westfield',
        seller_hook: 'Chicopee\'s affordability draws first-time buyers and investors alike — your listing will attract serious realtor attention.',
        realtor_hook: 'Chicopee\'s volume market and steady buyer pool make it one of the best areas for active agents in Hampden County.',
    },
    {
        slug: 'pittsfield',
        name: 'Pittsfield',
        county: 'Berkshire',
        state: 'MA',
        zip: '01201',
        population: '43,000',
        median_price: '$215,000',
        price_trend: 'up 15%',
        avg_dom: 19,
        description: 'the largest city in the Berkshires and the cultural capital of western Massachusetts, with world-class arts, outdoor recreation, and a booming second-home market',
        neighborhoods: 'Morningside, Westside, Lakewood, and Allendale',
        nearby: 'Lenox, Stockbridge, Lee, and Great Barrington',
        seller_hook: 'Pittsfield\'s Berkshire market is drawing buyers from Boston and NYC — get competitive realtor bids before your home is even listed.',
        realtor_hook: 'The Berkshire market is red-hot. Out-of-state buyers with flexible budgets are fueling the fastest appreciation in western MA.',
    },
    {
        slug: 'westfield',
        name: 'Westfield',
        county: 'Hampden',
        state: 'MA',
        zip: '01085',
        population: '41,000',
        median_price: '$285,000',
        price_trend: 'up 8%',
        avg_dom: 24,
        description: 'a growing city known as the "Whip City," home to Westfield State University and excellent access to the Pioneer Valley corridor',
        neighborhoods: 'Munson Hill, Southampton Road, Paper Mill, and the Westfield Center',
        nearby: 'Agawam, Springfield, Southwick, and Southampton',
        seller_hook: 'Westfield\'s combination of affordability and strong schools draws consistent buyer demand — perfect conditions for competing realtor bids.',
        realtor_hook: 'Westfield offers a strong mix of first-time buyers, move-up buyers, and investors. A growing market rewards agents who act fast.',
    },
    {
        slug: 'longmeadow',
        name: 'Longmeadow',
        county: 'Hampden',
        state: 'MA',
        zip: '01106',
        population: '15,000',
        median_price: '$430,000',
        price_trend: 'up 10%',
        avg_dom: 15,
        description: 'one of the most desirable suburbs in western Massachusetts, known for top-rated schools, tree-lined streets, and its affluent residential character',
        neighborhoods: 'Longmeadow Center, Wolf Swamp, Blueberry Hill, and Bliss Road',
        nearby: 'Springfield, East Longmeadow, Enfield CT, and Somers CT',
        seller_hook: 'Longmeadow\'s prestige commands premium prices — but only if you have the right realtor. Let agents compete to represent your home.',
        realtor_hook: 'Longmeadow\'s premium market, fast-moving inventory, and high median prices make every listing count.',
    },
    {
        slug: 'easthampton',
        name: 'Easthampton',
        county: 'Hampshire',
        state: 'MA',
        zip: '01027',
        population: '16,000',
        median_price: '$345,000',
        price_trend: 'up 13%',
        avg_dom: 16,
        description: 'a rapidly growing arts community between Northampton and Holyoke, attracting young professionals and creatives with its mill-loft culture and walkable downtown',
        neighborhoods: 'Nashawannuck Pond, the downtown arts district, Pascommuck, and White Brook',
        nearby: 'Northampton, Holyoke, Southampton, and Westhampton',
        seller_hook: 'Easthampton is one of the fastest-appreciating markets in Hampshire County — now is the time to sell with multiple realtors competing for your listing.',
        realtor_hook: 'Easthampton is the hottest growth market in Hampshire County. Buyers from Northampton and beyond are piling in — get ahead of listings here.',
    },
    {
        slug: 'south-hadley',
        name: 'South Hadley',
        county: 'Hampshire',
        state: 'MA',
        zip: '01075',
        population: '17,000',
        median_price: '$315,000',
        price_trend: 'up 9%',
        avg_dom: 21,
        description: 'a scenic town on the Connecticut River, home to Mount Holyoke College and offering a blend of suburban comfort and academic community character',
        neighborhoods: 'South Hadley Falls, The Village Commons, Granby Road, and Newton Street',
        nearby: 'Holyoke, Amherst, Granby, and Hadley',
        seller_hook: 'South Hadley\'s steady demand from faculty, families, and college-affiliated buyers makes it a strong seller\'s market year-round.',
        realtor_hook: 'South Hadley\'s mix of college-town demand and suburban families creates reliable, year-round buyer interest for active agents.',
    },
    {
        slug: 'agawam',
        name: 'Agawam',
        county: 'Hampden',
        state: 'MA',
        zip: '01001',
        population: '28,000',
        median_price: '$295,000',
        price_trend: 'up 7%',
        avg_dom: 23,
        description: 'a thriving suburb on the Connecticut border with excellent schools, low taxes, and strong community character making it one of Hampden County\'s most sought-after towns',
        neighborhoods: 'Feeding Hills, Paucatuck, Agawam Center, and South Agawam',
        nearby: 'West Springfield, Springfield, Southwick, and Granville',
        seller_hook: 'Agawam\'s reputation for great schools and low taxes draws motivated buyers — put realtors in competition to earn your business.',
        realtor_hook: 'Agawam draws consistent demand from Springfield-area buyers looking for more space and better schools. Strong territory for growth-minded agents.',
    },
    {
        slug: 'great-barrington',
        name: 'Great Barrington',
        county: 'Berkshire',
        state: 'MA',
        zip: '01230',
        population: '7,000',
        median_price: '$495,000',
        price_trend: 'up 18%',
        avg_dom: 12,
        description: 'the southern gateway to the Berkshires, beloved by NYC weekenders and second-home buyers, with a thriving Main Street and world-class cultural institutions',
        neighborhoods: 'Housatonic, Van Deusenville, downtown Great Barrington, and Alford Road',
        nearby: 'Stockbridge, Lenox, Sheffield, and Hillsdale NY',
        seller_hook: 'Great Barrington\'s second-home market draws cash buyers from New York City and Boston — and motivated realtors ready to compete for your listing.',
        realtor_hook: 'Great Barrington is the #1 second-home market in western MA. High prices, fast-moving inventory, and out-of-state buyers make every listing valuable.',
    },
];

module.exports = cities;
