module.exports = [
  ...require('./cities/ma-western'),
  ...require('./cities/ma-eastern'),
  ...require('./cities/ct'),
  ...require('./cities/ri'),
  ...require('./cities/vt'),
  ...require('./cities/nh'),
  ...require('./cities/me'),
  // National expansion
  ...require('./cities/ny'),
  ...require('./cities/nj'),
  ...require('./cities/fl'),
  ...require('./cities/tx'),
  ...require('./cities/ca'),
  ...require('./cities/ga'),
  ...require('./cities/nc'),
  ...require('./cities/il'),
  ...require('./cities/wa'),
  ...require('./cities/co'),
];
