-- migrate-existing-cities.sql
-- Moves the 12 hardcoded western MA cities into city_pages table
-- Run after migration-cities.sql

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('springfield', 'Springfield', 'MA', 'Massachusetts', 'Hampden', '01101', '155,000', '$235,000', 'up 8%', 22, 'the largest city in western Massachusetts and the commercial hub of the Pioneer Valley', 'Forest Park, East Forest Park, Sixteen Acres, Indian Orchard, South End', 'Longmeadow, Chicopee, West Springfield, Agawam', 'Springfield''s competitive market means your home can attract multiple realtor bids — driving better commission rates and faster service.', 'Springfield has one of the highest listing volumes in western MA. Get ahead of new listings before they hit Zillow.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('northampton', 'Northampton', 'MA', 'Massachusetts', 'Hampshire', '01060', '28,000', '$425,000', 'up 12%', 14, 'a vibrant college city and the county seat of Hampshire County, known for its arts scene, Smith College, and high quality of life', 'Florence, Leeds, Bay State, Williamsburg Road, downtown Northampton', 'Easthampton, Amherst, Hadley, South Hadley', 'Northampton''s low days-on-market means motivated buyers are ready — and competitive realtors will fight for your listing.', 'Northampton''s premium market and fast-moving inventory reward agents who move quickly. Be first to bid on new listings.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('amherst', 'Amherst', 'MA', 'Massachusetts', 'Hampshire', '01002', '39,000', '$395,000', 'up 9%', 18, 'a college town home to UMass Amherst, Amherst College, and Hampshire College — with a diverse, educated community and strong rental demand', 'North Amherst, South Amherst, East Amherst, Amherst Center', 'Northampton, Hadley, Belchertown, Pelham', 'Strong student and faculty demand keeps Amherst''s market competitive year-round — get multiple realtors competing for your listing.', 'Amherst''s university-driven market generates consistent buyer demand. Secure listings before the semester rush.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('holyoke', 'Holyoke', 'MA', 'Massachusetts', 'Hampden', '01040', '40,000', '$215,000', 'up 11%', 28, 'a historic mill city on the Connecticut River experiencing significant revitalization, with affordable home prices and a growing arts and tech scene', 'The Highlands, Elmwood, Oakdale, Churchill, downtown', 'Chicopee, Springfield, South Hadley, Easthampton', 'Holyoke''s rising values mean now is an ideal time to sell — let realtors compete for the right to represent your home.', 'Holyoke''s affordability is driving strong buyer interest. A growing inventory of listings means opportunity for active agents.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('chicopee', 'Chicopee', 'MA', 'Massachusetts', 'Hampden', '01013', '56,000', '$255,000', 'up 7%', 20, 'a diverse suburb of Springfield with affordable home prices, excellent highway access, and a strong working-class community', 'Aldenville, Fairview, Willimansett, Chicopee Falls, Chicopee Center', 'Springfield, Holyoke, Ludlow, Westfield', 'Chicopee''s affordability draws first-time buyers and investors alike — your listing will attract serious realtor attention.', 'Chicopee''s volume market and steady buyer pool make it one of the best areas for active agents in Hampden County.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('pittsfield', 'Pittsfield', 'MA', 'Massachusetts', 'Berkshire', '01201', '43,000', '$215,000', 'up 15%', 19, 'the largest city in the Berkshires and the cultural capital of western Massachusetts, with world-class arts, outdoor recreation, and a booming second-home market', 'Morningside, Westside, Lakewood, Allendale', 'Lenox, Stockbridge, Lee, Great Barrington', 'Pittsfield''s Berkshire market is drawing buyers from Boston and NYC — get competitive realtor bids before your home is even listed.', 'The Berkshire market is red-hot. Out-of-state buyers with flexible budgets are fueling the fastest appreciation in western MA.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('westfield', 'Westfield', 'MA', 'Massachusetts', 'Hampden', '01085', '41,000', '$285,000', 'up 8%', 24, 'a growing city known as the "Whip City," home to Westfield State University and excellent access to the Pioneer Valley corridor', 'Munson Hill, Southampton Road, Paper Mill, Westfield Center', 'Agawam, Springfield, Southwick, Southampton', 'Westfield''s combination of affordability and strong schools draws consistent buyer demand — perfect conditions for competing realtor bids.', 'Westfield offers a strong mix of first-time buyers, move-up buyers, and investors. A growing market rewards agents who act fast.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('longmeadow', 'Longmeadow', 'MA', 'Massachusetts', 'Hampden', '01106', '15,000', '$430,000', 'up 10%', 15, 'one of the most desirable suburbs in western Massachusetts, known for top-rated schools, tree-lined streets, and its affluent residential character', 'Longmeadow Center, Wolf Swamp, Blueberry Hill, Bliss Road', 'Springfield, East Longmeadow, Enfield CT, Somers CT', 'Longmeadow''s prestige commands premium prices — but only if you have the right realtor. Let agents compete to represent your home.', 'Longmeadow''s premium market, fast-moving inventory, and high median prices make every listing count.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('easthampton', 'Easthampton', 'MA', 'Massachusetts', 'Hampshire', '01027', '16,000', '$345,000', 'up 13%', 16, 'a rapidly growing arts community between Northampton and Holyoke, attracting young professionals and creatives with its mill-loft culture and walkable downtown', 'Nashawannuck Pond, downtown arts district, Pascommuck, White Brook', 'Northampton, Holyoke, Southampton, Westhampton', 'Easthampton is one of the fastest-appreciating markets in Hampshire County — now is the time to sell with multiple realtors competing for your listing.', 'Easthampton is the hottest growth market in Hampshire County. Buyers from Northampton and beyond are piling in — get ahead of listings here.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('south-hadley', 'South Hadley', 'MA', 'Massachusetts', 'Hampshire', '01075', '17,000', '$315,000', 'up 9%', 21, 'a scenic town on the Connecticut River, home to Mount Holyoke College and offering a blend of suburban comfort and academic community character', 'South Hadley Falls, The Village Commons, Granby Road, Newton Street', 'Holyoke, Amherst, Granby, Hadley', 'South Hadley''s steady demand from faculty, families, and college-affiliated buyers makes it a strong seller''s market year-round.', 'South Hadley''s mix of college-town demand and suburban families creates reliable, year-round buyer interest for active agents.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('agawam', 'Agawam', 'MA', 'Massachusetts', 'Hampden', '01001', '28,000', '$295,000', 'up 7%', 23, 'a thriving suburb on the Connecticut border with excellent schools, low taxes, and strong community character making it one of Hampden County''s most sought-after towns', 'Feeding Hills, Paucatuck, Agawam Center, South Agawam', 'West Springfield, Springfield, Southwick, Granville', 'Agawam''s reputation for great schools and low taxes draws motivated buyers — put realtors in competition to earn your business.', 'Agawam draws consistent demand from Springfield-area buyers looking for more space and better schools. Strong territory for growth-minded agents.', true)
ON CONFLICT (state_code, slug) DO NOTHING;

INSERT INTO city_pages (slug, name, state_code, state_name, county, zip, population, median_price, price_trend, avg_dom, description, neighborhoods, nearby, seller_hook, realtor_hook, is_published) VALUES
('great-barrington', 'Great Barrington', 'MA', 'Massachusetts', 'Berkshire', '01230', '7,000', '$495,000', 'up 18%', 12, 'the southern gateway to the Berkshires, beloved by NYC weekenders and second-home buyers, with a thriving Main Street and world-class cultural institutions', 'Housatonic, Van Deusenville, downtown Great Barrington, Alford Road', 'Stockbridge, Lenox, Sheffield, Hillsdale NY', 'Great Barrington''s second-home market draws cash buyers from New York City and Boston — and motivated realtors ready to compete for your listing.', 'Great Barrington is the #1 second-home market in western MA. High prices, fast-moving inventory, and out-of-state buyers make every listing valuable.', true)
ON CONFLICT (state_code, slug) DO NOTHING;
