// cities/ak.js — Alaska city data for SEO landing pages

module.exports = [
    {
        slug: 'anchorage',
        name: 'Anchorage',
        county: 'Anchorage',
        state: 'AK',
        zip: '99501',
        population: '291,000',
        median_price: '$390,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Anchorage is Alaska\'s largest city and the gateway to the Last Frontier — a mountain-ringed Pacific Rim metropolis where oil industry employment, Joint Base Elmendorf-Richardson, Providence Alaska Medical Center, and proximity to Denali and the Kenai Peninsula create housing demand from energy workers, military families, and adventurous buyers who value Chugach Mountain trail access from their backdoor.',
        neighborhoods: 'Midtown, Eagle River, Hillside, Muldoon, Sand Lake, Abbott Road',
        nearby: 'Eagle River, Wasilla, Palmer, Girdwood, Chugiak',
        seller_hook: 'Anchorage\'s oil industry and military community drive consistent buyer demand in Alaska\'s premier housing market — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Anchorage\'s energy sector and JBER military population create steady listing volume across all price ranges — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'fairbanks',
        name: 'Fairbanks',
        county: 'Fairbanks North Star',
        state: 'AK',
        zip: '99701',
        population: '32,000',
        median_price: '$310,000',
        price_trend: 'up 4%',
        avg_dom: 40,
        description: 'Fairbanks is Alaska\'s Golden Heart City and Interior Alaska\'s largest community — an arctic university city where University of Alaska Fairbanks, Fort Wainwright Army Base, Eielson Air Force Base, and aurora borealis tourism create housing demand from students, military families, and resilient Alaskans who embrace -50°F winters in exchange for midnight sun summers, gold rush history, and some of the world\'s best northern lights viewing.',
        neighborhoods: 'North Pole, College, Ester, Moose Creek, Badger Road',
        nearby: 'North Pole, Ester, College, Moose Creek, Delta Junction',
        seller_hook: 'Fairbanks\' UAF enrollment and dual military installation drive reliable Alaska Interior buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Fairbanks\' university and military market create consistent listing activity in Alaska\'s interior — find sellers through RealtorFinder.',
    },
    {
        slug: 'juneau',
        name: 'Juneau',
        county: 'Juneau',
        state: 'AK',
        zip: '99801',
        population: '32,000',
        median_price: '$430,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Juneau is Alaska\'s state capital and one of the most geographically isolated capital cities in America — accessible only by sea or air, this rainforest city at the base of the Mendenhall Glacier attracts state government workers, cruise ship industry employees, and buyers seeking a unique Southeast Alaska lifestyle where bald eagles are common backyard visitors and kayaking the Inside Passage begins at the city limits.',
        neighborhoods: 'Downtown, Douglas Island, Mendenhall Valley, Auke Bay, Lemon Creek',
        nearby: 'Douglas, Mendenhall Valley, Auke Bay, Thane, Haines',
        seller_hook: 'Juneau\'s state capital employment and island isolation create a captive buyer market — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Juneau\'s government workforce and Southeast Alaska lifestyle create unique listing opportunities in Alaska\'s capital city — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'wasilla-ak',
        name: 'Wasilla',
        county: 'Matanuska-Susitna',
        state: 'AK',
        zip: '99654',
        population: '10,000',
        median_price: '$320,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Wasilla is the commercial hub of the Matanuska-Susitna Valley and Anchorage\'s fastest-growing suburb — a sprawling frontier community where affordable rural residential lots, the Iditarod Trail Sled Dog Race\'s ceremonial start, and 45-minute Anchorage commuter access attract military families, outdoor enthusiasts, and Alaska-minded buyers seeking more land and lower prices than the Anchorage bowl can provide.',
        neighborhoods: 'Palmer, Big Lake, Houston, Meadow Lakes, Sutton',
        nearby: 'Palmer, Big Lake, Houston, Meadow Lakes, Willow',
        seller_hook: 'Wasilla\'s Mat-Su Valley growth and Anchorage commuter appeal drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Wasilla\'s Mat-Su boom and frontier lifestyle create active listing conditions for Alaska\'s fastest-growing valley — find sellers through RealtorFinder.',
    },
];
