// cities/al.js — Alabama city data for SEO landing pages

module.exports = [
    {
        slug: 'birmingham',
        name: 'Birmingham',
        county: 'Jefferson',
        state: 'AL',
        zip: '35203',
        population: '212,000',
        median_price: '$210,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Birmingham is Alabama\'s largest city and a New South medical and financial powerhouse — a once-industrial steel city reborn as a foodie destination and healthcare hub where the University of Alabama at Birmingham, Protective Life, and a nationally acclaimed Southside restaurant scene attract young professionals and investors who find some of the Southeast\'s best home values within a walkable urban grid.',
        neighborhoods: 'Southside, Highland Park, Mountain Brook, Homewood, Vestavia Hills, Cahaba Heights',
        nearby: 'Hoover, Vestavia Hills, Homewood, Trussville, Bessemer',
        seller_hook: 'Birmingham\'s UAB medical hub and foodie renaissance drive growing buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Birmingham\'s healthcare sector and Southside revival create strong listing volume across all price ranges — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'montgomery-al',
        name: 'Montgomery',
        county: 'Montgomery',
        state: 'AL',
        zip: '36104',
        population: '200,000',
        median_price: '$180,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Montgomery is Alabama\'s state capital and a city of deep Civil Rights significance — where Maxwell-Gunter Air Force Base, the National Memorial for Peace and Justice, Alabama State University, and a growing Hyundai supplier network create housing demand from government workers, military families, and history-minded buyers who find affordable brick homes in a market with excellent investment fundamentals.',
        neighborhoods: 'Cloverdale, Garden District, Old Cloverdale, Pike Road, Prattville, Millbrook',
        nearby: 'Prattville, Millbrook, Wetumpka, Tallassee, Selma',
        seller_hook: 'Montgomery\'s state capital stability and Maxwell AFB community drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Montgomery\'s government and military buyer pool create year-round listing activity at accessible price points — find sellers through RealtorFinder.',
    },
    {
        slug: 'huntsville',
        name: 'Huntsville',
        county: 'Madison',
        state: 'AL',
        zip: '35801',
        population: '215,000',
        median_price: '$320,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Huntsville is America\'s rocket city and one of the South\'s fastest-growing metros — a NASA Marshall Space Flight Center and Redstone Arsenal hub where Boeing, Lockheed Martin, and a booming defense contractor ecosystem have created one of the Southeast\'s hottest housing markets, with California and DC transplants driving bidding wars on homes that still cost a fraction of comparable markets.',
        neighborhoods: 'Hampton Cove, Monte Sano, Five Points, South Huntsville, Madison, Jones Valley',
        nearby: 'Madison, Decatur, Athens, Meridianville, Hazel Green',
        seller_hook: 'Huntsville\'s NASA and defense boom is creating one of the South\'s most competitive seller\'s markets — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Huntsville\'s explosive tech and defense growth make it Alabama\'s premier listing opportunity right now — find sellers through RealtorFinder.',
    },
    {
        slug: 'mobile-al',
        name: 'Mobile',
        county: 'Mobile',
        state: 'AL',
        zip: '36602',
        population: '187,000',
        median_price: '$185,000',
        price_trend: 'up 4%',
        avg_dom: 40,
        description: 'Mobile is Alabama\'s only deep-water port city and the birthplace of Mardi Gras in America — a Gulf Coast commercial hub where the Port of Mobile, Austal USA shipbuilding, University of South Alabama, and a revitalized downtown arts district create housing demand from maritime workers, medical professionals, and buyers seeking affordable coastal living far from Florida\'s premium price tags.',
        neighborhoods: 'Midtown, Spring Hill, Old Dauphin Way, Dauphin Island, Prichard, Saraland',
        nearby: 'Daphne, Spanish Fort, Fairhope, Saraland, Satsuma',
        seller_hook: 'Mobile\'s port economy and Mardi Gras culture attract a diverse buyer pool — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Mobile\'s shipbuilding and medical sectors create steady listing activity at Gulf Coast value prices — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'tuscaloosa',
        name: 'Tuscaloosa',
        county: 'Tuscaloosa',
        state: 'AL',
        zip: '35401',
        population: '100,000',
        median_price: '$225,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Tuscaloosa is the home of the University of Alabama and the soul of Crimson Tide football culture — a college city where national championship energy, a massive Mercedes-Benz manufacturing plant, and DCH Regional Medical Center drive housing demand from students, faculty, manufacturing workers, and investors who prize the strong rental income potential of a dominant SEC football market.',
        neighborhoods: 'Downtown, The Strip, Northport, Lake Tuscaloosa, Forest Lake, Cottondale',
        nearby: 'Northport, Cottondale, Moundville, Demopolis, Eutaw',
        seller_hook: 'Tuscaloosa\'s UA enrollment and Mercedes plant create strong and diverse buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Tuscaloosa\'s university and manufacturing market create consistent listing volume and strong investment demand — find sellers through RealtorFinder.',
    },
    {
        slug: 'hoover-al',
        name: 'Hoover',
        county: 'Jefferson / Shelby',
        state: 'AL',
        zip: '35244',
        population: '92,000',
        median_price: '$330,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Hoover is Birmingham\'s most affluent suburb and the home of the iconic Riverchase Galleria — a Jefferson and Shelby County community where top-ranked Hoover City Schools, corporate relocations, and a master-planned suburban lifestyle create one of Alabama\'s most competitive buyer markets, with multiple-offer scenarios common across nearly every price range.',
        neighborhoods: 'Riverchase, Bluff Park, Ross Bridge, Lake Cyrus, Greystone',
        nearby: 'Birmingham, Vestavia Hills, Alabaster, Pelham, Helena',
        seller_hook: 'Hoover\'s top schools and affluent buyer pool create exceptional listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Hoover\'s Galleria corridor and elite school district make it Birmingham\'s most consistent listing suburb — find sellers through RealtorFinder.',
    },
    {
        slug: 'auburn-al',
        name: 'Auburn',
        county: 'Lee',
        state: 'AL',
        zip: '36830',
        population: '80,000',
        median_price: '$285,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Auburn is home to Auburn University and the heart of War Eagle country — an SEC college city that consistently ranks among the nation\'s most livable communities, where Toomer\'s Corner celebrations, a growing research park, a top-10 engineering program, and a warm southern college-town culture create intense housing competition from students, faculty, and transplants who love the Tigers.',
        neighborhoods: 'Downtown Auburn, Samford Avenue, Chewacla, Opelika, Drake, Moores Mill',
        nearby: 'Opelika, Phenix City, Dadeville, Alexander City, Notasulga',
        seller_hook: 'Auburn\'s top university ranking and War Eagle culture drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Auburn\'s AU enrollment and research park growth create strong listing conditions with robust investment demand — find sellers through RealtorFinder.',
    },
    {
        slug: 'dothan',
        name: 'Dothan',
        county: 'Houston',
        state: 'AL',
        zip: '36301',
        population: '72,000',
        median_price: '$195,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Dothan is Alabama\'s Peanut Capital and the commercial hub of the Wiregrass region — a regional center where Fort Rucker Army Aviation Center, a large regional medical complex, and Southeast Alabama agriculture create housing demand from military aviators, healthcare workers, and agricultural families who find exceptional affordability and a quiet southern lifestyle at the intersection of Alabama, Florida, and Georgia.',
        neighborhoods: 'Northwood, Westgate, Honeysuckle Road, Columbia, Cottonwood',
        nearby: 'Enterprise, Ozark, Headland, Abbeville, Pinckard',
        seller_hook: 'Dothan\'s Fort Rucker aviation community and regional medical hub drive steady buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Dothan\'s military and healthcare markets create consistent listing activity at Wiregrass Region prices — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'decatur-al',
        name: 'Decatur',
        county: 'Morgan',
        state: 'AL',
        zip: '35601',
        population: '54,000',
        median_price: '$185,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Decatur is Morgan County\'s Tennessee River city and one of Alabama\'s key industrial hubs — home to 3M, General Electric, and a massive chemical manufacturing sector on the Tennessee River, where manufacturing wages, Calhoun Community College enrollment, and riverfront revitalization draw first-time buyers and workers seeking affordable industrial-city living with strong employment stability.',
        neighborhoods: 'Point Mallard, Old Decatur, South Decatur, Trinity, Hartselle',
        nearby: 'Hartselle, Athens, Huntsville, Cullman, Moulton',
        seller_hook: 'Decatur\'s Tennessee River manufacturing corridor creates a reliable buyer pool — let RealtorFinder agents compete for your listing.',
        realtor_hook: 'Decatur\'s industrial economy and affordable price points generate steady listing activity — find sellers through RealtorFinder.',
    },
];
