// cities/ar.js — Arkansas city data for SEO landing pages

module.exports = [
    {
        slug: 'little-rock',
        name: 'Little Rock',
        county: 'Pulaski',
        state: 'AR',
        zip: '72201',
        population: '202,000',
        median_price: '$210,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Little Rock is Arkansas\'s state capital and largest city — a River Market District revitalization success story on the Arkansas River where state government, UAMS medical campus, and a growing tech sector anchor an affordable housing market that draws young professionals, medical workers, and families seeking southern charm at prices that rank among the South\'s best values.',
        neighborhoods: 'Hillcrest, Chenal Valley, Heights, Riverdale, West Little Rock, Pleasant Valley',
        nearby: 'North Little Rock, Conway, Benton, Bryant, Maumelle',
        seller_hook: 'Little Rock\'s state capital stability and River Market revival drive consistent buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Little Rock\'s government and medical sector create steady listing volume across all price ranges — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'fayetteville-ar',
        name: 'Fayetteville',
        county: 'Washington',
        state: 'AR',
        zip: '72701',
        population: '93,000',
        median_price: '$295,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Fayetteville is home to the University of Arkansas and the heart of Northwest Arkansas\'s booming Walmart economy — a Razorback college city where Walmart, J.B. Hunt, and Tyson Foods headquarters draw corporate talent from across the country, creating one of the South\'s hottest housing markets with Bentonville tech investment and a nationally acclaimed Mountain Bike Trail network driving rapid appreciation.',
        neighborhoods: 'Dickson Street, Wilson Park, Walker Park, Johnson, Elkins, Prairie Grove',
        nearby: 'Springdale, Rogers, Bentonville, Siloam Springs, Farmington',
        seller_hook: 'Fayetteville\'s Walmart economy and UA enrollment create intense buyer competition — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Fayetteville\'s NWA corporate relocation market makes it Arkansas\'s premier listing opportunity — find sellers through RealtorFinder.',
    },
    {
        slug: 'fort-smith-ar',
        name: 'Fort Smith',
        county: 'Sebastian',
        state: 'AR',
        zip: '72901',
        population: '87,000',
        median_price: '$175,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Fort Smith is western Arkansas\'s largest city and an Arkansas River manufacturing hub — a community where ArcBest logistics, a large VA Medical Center, University of Arkansas-Fort Smith, and a revitalizing Garrison Avenue arts district create demand for some of the Mid-South\'s most affordable single-family homes among first-time buyers and industrial workers.',
        neighborhoods: 'Chaffee Crossing, Cavanaugh, Massard, Greenwood, Van Buren',
        nearby: 'Van Buren, Greenwood, Alma, Sallisaw OK, Poteau OK',
        seller_hook: 'Fort Smith\'s manufacturing economy and affordable prices attract motivated buyers year-round — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Fort Smith\'s industrial and VA market create consistent listing activity at accessible price points — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'springdale-ar',
        name: 'Springdale',
        county: 'Washington / Benton',
        state: 'AR',
        zip: '72764',
        population: '87,000',
        median_price: '$260,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Springdale is the home of Tyson Foods and the commercial backbone of Northwest Arkansas — a diverse and rapidly growing community where poultry processing, the Crystal Bridges Museum of American Art spillover, and the Walmart supply chain drive demand from a diverse workforce of corporate employees, immigrant families, and buyers seeking affordable NWA living south of Rogers and Bentonville.',
        neighborhoods: 'Har-Ber Meadows, Randall Wobbe, Tontitown, Elm Springs, Lowell',
        nearby: 'Fayetteville, Rogers, Bentonville, Lowell, Tontitown',
        seller_hook: 'Springdale\'s Tyson Foods hub and NWA growth drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Springdale\'s diverse NWA market and rapid appreciation create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'bentonville',
        name: 'Bentonville',
        county: 'Benton',
        state: 'AR',
        zip: '72712',
        population: '57,000',
        median_price: '$380,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Bentonville is Walmart\'s global headquarters city and one of America\'s fastest-transforming small cities — a once-quiet Ozark town now packed with world-class mountain bike trails, Crystal Bridges Museum of American Art, Walmart Home Office professionals, and Silicon Valley transplants, creating a premium housing market with California-like demand at prices that still shock buyers arriving from the coasts.',
        neighborhoods: 'Downtown, Bella Vista, Centerton, Cave Springs, Highfill',
        nearby: 'Rogers, Centerton, Cave Springs, Bella Vista, Pea Ridge',
        seller_hook: 'Bentonville\'s Walmart HQ and Crystal Bridges prestige drive exceptional sale prices — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Bentonville\'s corporate relocation market and rapid appreciation make it the South\'s most exciting listing opportunity — find sellers through RealtorFinder.',
    },
    {
        slug: 'jonesboro-ar',
        name: 'Jonesboro',
        county: 'Craighead',
        state: 'AR',
        zip: '72401',
        population: '77,000',
        median_price: '$195,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Jonesboro is northeast Arkansas\'s largest city and home to Arkansas State University — a Delta Region hub where A-State\'s Red Wolves athletics, St. Bernards Medical Center, and a growing manufacturing base create consistent housing demand from students, medical professionals, and agricultural workers seeking affordable homeownership in one of Arkansas\'s most dynamic regional economies.',
        neighborhoods: 'Brookland, Bono, Bay, Harrisburg, Trumann',
        nearby: 'Paragould, Blytheville, Newport, Searcy, Batesville',
        seller_hook: 'Jonesboro\'s A-State enrollment and medical hub drive steady buyer demand — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Jonesboro\'s university and healthcare market create consistent listing activity at Delta Region prices — find sellers through RealtorFinder.',
    },
    {
        slug: 'north-little-rock',
        name: 'North Little Rock',
        county: 'Pulaski',
        state: 'AR',
        zip: '72114',
        population: '66,000',
        median_price: '$185,000',
        price_trend: 'up 5%',
        avg_dom: 34,
        description: 'North Little Rock sits across the Arkansas River from the state capital and offers some of Pulaski County\'s most affordable housing — a blue-collar community of longtime neighborhoods, Argenta Arts District galleries, Dickey-Stephens Park, and Interstate 40 logistics employment that attracts first-time buyers and investors seeking Little Rock metro access at below-average price points.',
        neighborhoods: 'Argenta, Indian Hills, Levy, Park Hill, Sherwood',
        nearby: 'Little Rock, Sherwood, Maumelle, Jacksonville, Cabot',
        seller_hook: 'North Little Rock\'s affordability and Argenta revival attract a growing buyer pool — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'North Little Rock\'s accessible prices and Little Rock proximity create active listing conditions — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'rogers-ar',
        name: 'Rogers',
        county: 'Benton',
        state: 'AR',
        zip: '72756',
        population: '68,000',
        median_price: '$330,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Rogers is Northwest Arkansas\'s fastest-growing city and the retail hub of the Walmart corridor — a community where Pinnacle Hills Promenade, the Walmart-adjacent corporate campus boom, and top-rated Rogers School District attract young families and corporate transfers seeking master-planned neighborhood amenities between Bentonville and Fayetteville in one of the nation\'s hottest mid-size metro markets.',
        neighborhoods: 'Pinnacle Hills, Pleasant Grove, Beaver Lake, Avoca, Lowell',
        nearby: 'Bentonville, Lowell, Centerton, Springdale, Pea Ridge',
        seller_hook: 'Rogers\' Walmart corridor growth and top schools create competitive listing conditions — let RealtorFinder agents compete for your home.',
        realtor_hook: 'Rogers\' NWA growth and family buyer demand generate fast-moving listing conditions — find sellers through RealtorFinder.',
    },
];
