// cities/az.js — Arizona city data for SEO landing pages

module.exports = [
    {
        slug: 'phoenix',
        name: 'Phoenix',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85001',
        population: '1608139',
        median_price: '$450,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Phoenix is the Sun Belt\'s defining metropolis — the fifth-largest city in America and the engine of Maricopa County\'s relentless population growth, driven by corporate relocations from Intel, TSMC, and Microsoft anchoring a semiconductor and tech corridor alongside a booming healthcare sector and year-round sunshine that draws retirees, remote workers, and young professionals from across the country. The Roosevelt Row arts district, Arcadia\'s citrus-grove estates, and Ahwatukee\'s family-oriented master plans reflect a city of extraordinary geographic and demographic range.',
        neighborhoods: 'Roosevelt Row, Arcadia, Biltmore, Ahwatukee, Camelback East, North Mountain, Laveen, Sunnyslope',
        nearby: 'Scottsdale, Tempe, Glendale, Mesa, Chandler',
        seller_hook: 'Phoenix\'s massive buyer pool — fueled by corporate relocations and Sun Belt migration — means the right agent can generate serious competition for your listing; let them compete on RealtorFinder.',
        realtor_hook: 'Phoenix\'s size and diversity create more listing opportunities than almost any market in the Southwest — RealtorFinder connects you with motivated sellers across America\'s fastest-growing major city.',
    },
    {
        slug: 'scottsdale',
        name: 'Scottsdale',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85251',
        population: '258069',
        median_price: '$750,000',
        price_trend: 'up 5%',
        avg_dom: 40,
        description: 'Scottsdale is Arizona\'s luxury capital — a desert playground of world-class golf resorts, spa destinations like the Boulders and Four Seasons, and a dining and arts scene on Old Town\'s galleries and Fifth Avenue that rivals any western American city. North Scottsdale\'s gated estates along Pinnacle Peak and DC Ranch\'s master-planned prestige neighborhoods attract wealthy buyers from California, the Midwest, and internationally who seek 300 days of sunshine with premium amenities at prices still below comparable California markets.',
        neighborhoods: 'Old Town, McCormick Ranch, DC Ranch, Pinnacle Peak area, Gainey Ranch, Paradise Valley border, Scottsdale Ranch, South Scottsdale',
        nearby: 'Phoenix, Tempe, Mesa, Fountain Hills, Cave Creek',
        seller_hook: 'Scottsdale\'s luxury buyer pool includes affluent out-of-state buyers who pay premium prices for the right property — let top-tier Scottsdale agents on RealtorFinder compete to represent your home.',
        realtor_hook: 'Scottsdale\'s high-net-worth buyer base and luxury listing environment make each transaction exceptionally lucrative — RealtorFinder connects you with motivated sellers in Arizona\'s premier market.',
    },
    {
        slug: 'tempe',
        name: 'Tempe',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85281',
        population: '185038',
        median_price: '$490,000',
        price_trend: 'up 4%',
        avg_dom: 33,
        description: 'Tempe is Arizona State University\'s dynamic host city — a walkable, transit-rich urban core where Mill Avenue\'s entertainment corridor, Tempe Town Lake\'s waterfront parks, and Sun Devil Stadium\'s game-day energy give residents a genuine urban experience rare in the Phoenix suburb. ASU\'s 80,000-student enrollment and a growing biomedical and tech startup ecosystem centered on ASU Research Park attract young professionals and investors who appreciate Tempe\'s density and connectivity advantages over neighboring suburbs.',
        neighborhoods: 'Mill Avenue District, Tempe Town Lake area, ASU Research Park area, Maple-Ash, College Park, South Tempe, Buena Vista Ranchos',
        nearby: 'Phoenix, Scottsdale, Mesa, Chandler, Gilbert',
        seller_hook: 'Tempe\'s ASU employment and urban lifestyle attract a motivated, educated buyer base — let competing agents on RealtorFinder earn the right to market your home to this active market.',
        realtor_hook: 'Tempe\'s university-anchored demand and urban lifestyle appeal create consistent buyer activity and strong investment property interest — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'mesa',
        name: 'Mesa',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85201',
        population: '511648',
        median_price: '$430,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Mesa is the third-largest city in Arizona and one of the most underrated metros in the Southwest — a vast, diverse community anchoring the East Valley with Boeing\'s massive maintenance and training operations at Mesa Gateway Airport, Banner Health\'s regional hospital campus, and a growing downtown arts scene along Main Street that is transforming perceptions of this traditionally suburban city. Mesa\'s range from affordable starter homes in the West to luxury properties near Red Mountain to active-adult Leisure World and Las Sendas communities gives buyers an extraordinary range of options.',
        neighborhoods: 'Downtown Mesa, Red Mountain, Las Sendas, Eastmark, Leisure World, Dobson Ranch, Val Vista, Superstition Springs',
        nearby: 'Phoenix, Tempe, Chandler, Gilbert, Queen Creek',
        seller_hook: 'Mesa\'s large and diverse buyer pool creates broad market demand for homes across all price ranges — use RealtorFinder to let competing East Valley agents earn your listing.',
        realtor_hook: 'Mesa\'s enormous size and diverse demographics create one of Arizona\'s highest listing volumes — RealtorFinder connects you with motivated sellers across the full spectrum of this major market.',
    },
    {
        slug: 'chandler',
        name: 'Chandler',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85224',
        population: '275987',
        median_price: '$520,000',
        price_trend: 'up 4%',
        avg_dom: 32,
        description: 'Chandler is Arizona\'s semiconductor and fintech capital — home to Intel\'s massive Fab 42 chip-manufacturing campus, NXP Semiconductors, and PayPal\'s regional operations that make it the East Valley\'s most sophisticated technology employer. Downtown Chandler\'s vibrant restaurant and craft beer scene along Arizona Avenue, the Chandler Fashion Center retail hub, and master-planned neighborhoods from Ocotillo\'s lakeside community to Fulton Ranch\'s premium estates give residents a complete suburban package in one of Arizona\'s wealthiest cities.',
        neighborhoods: 'Downtown Chandler, Ocotillo, Fulton Ranch, Sun Lakes border, Andersen Springs, Dobson Ranch border, Perry and McQueen corridor',
        nearby: 'Gilbert, Tempe, Mesa, Ahwatukee, Queen Creek',
        seller_hook: 'Chandler\'s tech-sector employment and affluent demographics attract highly qualified buyers consistently — let competing East Valley experts on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Chandler\'s Intel-anchored tech economy and high household incomes make it one of Arizona\'s most rewarding listing environments — RealtorFinder connects you with motivated sellers in this premier suburb.',
    },
    {
        slug: 'gilbert',
        name: 'Gilbert',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85233',
        population: '267918',
        median_price: '$520,000',
        price_trend: 'up 4%',
        avg_dom: 32,
        description: 'Gilbert has transformed from an agricultural town into one of Arizona\'s most sought-after family destinations — a meticulously maintained suburb with consistently top-ranked schools, the Heritage District\'s revitalized small-town square with craft restaurants and breweries, and Riparian Preserve at Water Ranch\'s celebrated urban wildlife habitat. Gilbert\'s master-planned communities like Power Ranch, Val Vista Lakes, and Trilogy at Power Ranch attract families and active adults seeking a community-oriented lifestyle with East Valley employment access.',
        neighborhoods: 'Heritage District, Power Ranch, Val Vista Lakes, Trilogy at Power Ranch, Morrison Ranch, Rancho Sahuarita border area, Seville',
        nearby: 'Chandler, Mesa, Queen Creek, Tempe, Higley',
        seller_hook: 'Gilbert\'s family-oriented reputation and top school ratings create fierce buyer competition for quality listings — let competing agents on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Gilbert\'s award-winning livability and family demographics create one of Arizona\'s most active listing markets — RealtorFinder connects you with motivated sellers in this highly desirable suburb.',
    },
    {
        slug: 'glendale',
        name: 'Glendale',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85301',
        population: '248325',
        median_price: '$400,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Glendale is the West Valley\'s sports and entertainment capital — home to State Farm Stadium (Arizona Cardinals), Gila River Arena (Arizona Coyotes while active), and the Camelback Ranch spring training complex shared by the Dodgers and White Sox, anchoring a sports economy that drives significant hospitality and retail employment. The Historic Catlin Court antique and specialty retail district and the redeveloping Westgate Entertainment District reflect a city balancing its traditional roots with modern mixed-use development.',
        neighborhoods: 'Historic Catlin Court, Westgate area, Arrowhead Ranch, Thunderbird Park area, Foothills, Cholla area, Downtown Glendale',
        nearby: 'Phoenix, Peoria, Surprise, Avondale, Goodyear',
        seller_hook: 'Glendale\'s sports district and West Valley growth create diverse buyer demand — let competing RealtorFinder agents earn the right to market your home to this active buyer pool.',
        realtor_hook: 'Glendale\'s West Valley position and diverse housing stock create consistent listing activity across all price tiers — RealtorFinder connects you with motivated sellers in this major suburb.',
    },
    {
        slug: 'peoria',
        name: 'Peoria',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85345',
        population: '175961',
        median_price: '$460,000',
        price_trend: 'up 4%',
        avg_dom: 34,
        description: 'Peoria is a sprawling West Valley suburb that stretches from desert foothills to Lake Pleasant — one of Arizona\'s premier inland recreational destinations — offering residents a lifestyle that combines suburban convenience with boating, kayaking, and hiking access rare in the Phoenix metro. The Peoria Sports Complex hosts Padres and Mariners spring training, P83 Entertainment District provides a walkable venue for dining and events, and planned Desert Horizon communities reflect a city investing in long-term livability.',
        neighborhoods: 'Lake Pleasant area, P83 District, Terramar at Lake Pleasant, Happy Valley corridor, Vistancia, Westwing, Tierra Del Rio',
        nearby: 'Glendale, Surprise, Phoenix, El Mirage, Sun City',
        seller_hook: 'Peoria\'s Lake Pleasant recreation and strong West Valley growth draw buyers seeking outdoor lifestyle and suburban value — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Peoria\'s Lake Pleasant lifestyle and West Valley expansion create consistent buyer interest in this growing market — RealtorFinder connects you with motivated sellers across Maricopa County.',
    },
    {
        slug: 'surprise',
        name: 'Surprise',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85374',
        population: '165060',
        median_price: '$400,000',
        price_trend: 'up 4%',
        avg_dom: 36,
        description: 'Surprise is one of Arizona\'s fastest-growing cities — a northwestern Maricopa County suburb that has built a reputation around the Surprise Recreation Campus spring training complex hosting the Kansas City Royals and Texas Rangers, extensive trail systems connecting to White Tank Mountain Regional Park, and Sun City Grand\'s nationally recognized active-adult community. New master-planned neighborhoods and competitive pricing relative to Scottsdale and Gilbert attract both retirees and young families seeking value in the West Valley.',
        neighborhoods: 'Sun City Grand, Marley Park, Greer Ranch, White Tank foothills area, Corte Sierra, Palm Valley border, Surprise Farms',
        nearby: 'Glendale, Peoria, El Mirage, Buckeye, Goodyear',
        seller_hook: 'Surprise\'s retiree and family buyer bases create year-round demand for homes at accessible prices — let competing West Valley agents on RealtorFinder earn your listing.',
        realtor_hook: 'Surprise\'s active-adult communities and family subdivisions create diverse, consistent listing volume in Arizona\'s growing northwest corridor — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'avondale',
        name: 'Avondale',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85323',
        population: '89930',
        median_price: '$380,000',
        price_trend: 'up 4%',
        avg_dom: 36,
        description: 'Avondale is a Southwest Valley suburb best known as home to Phoenix International Raceway, which brings two NASCAR Cup Series events annually and anchors a sports tourism economy, while the city\'s working-class and growing Hispanic community has built a vibrant small business ecosystem along Dysart Road and the Cashman neighborhood. Its I-10 frontage and proximity to Goodyear\'s Amazon and manufacturing logistics corridor make Avondale an increasingly practical choice for buyers seeking West Valley affordability with regional employment access.',
        neighborhoods: 'Cashman area, Garden Lakes, Coldwater Springs, Rancho Santa Fe, West Phoenix border, Avondale Business Park area',
        nearby: 'Goodyear, Glendale, Surprise, Buckeye, Phoenix',
        seller_hook: 'Avondale\'s affordability and Southwest Valley employment growth create rising buyer demand — let competing local agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Avondale\'s value-driven buyer demand and logistics-corridor employment growth create active listing opportunities in the Southwest Valley — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'goodyear',
        name: 'Goodyear',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85338',
        population: '104557',
        median_price: '$440,000',
        price_trend: 'up 5%',
        avg_dom: 33,
        description: 'Goodyear is Arizona\'s most strategically positioned logistics and advanced manufacturing hub — home to Amazon\'s regional fulfillment center, Lockheed Martin\'s training operations at Goodyear Airport, and a booming industrial corridor along I-10 that has attracted billions in investment. Estrella Mountain Ranch\'s stunning desert mountain community and Palm Valley\'s established master-planned neighborhoods offer residents resort-style amenities and excellent Litchfield Elementary and Agua Fria Union school district schools at prices below the East Valley.',
        neighborhoods: 'Estrella Mountain Ranch, Palm Valley, Pebblecreek, Centerra, Verrado border, Cottonflower, Canyon Trails',
        nearby: 'Avondale, Buckeye, Surprise, Litchfield Park, Tolleson',
        seller_hook: 'Goodyear\'s booming employment growth and desirable master-planned communities create strong buyer competition — let competing West Valley agents on RealtorFinder earn your listing.',
        realtor_hook: 'Goodyear\'s industrial employment boom and premium master-planned neighborhoods create one of Arizona\'s fastest-appreciating listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'buckeye',
        name: 'Buckeye',
        county: 'Maricopa',
        state: 'AZ',
        zip: '85326',
        population: '105573',
        median_price: '$380,000',
        price_trend: 'up 5%',
        avg_dom: 37,
        description: 'Buckeye is Arizona\'s land-rich western frontier city — geographically the largest city in the Phoenix metro with enormous planned growth capacity that has made it a magnet for new-construction buyers seeking the lowest prices for brand-new homes in Maricopa County. Verrado\'s acclaimed new urbanist community with its Main Street, golf course, and walkable town center has redefined the West Valley lifestyle, and massive data center and logistics investments along I-10 are creating the employment base to support Buckeye\'s long-term growth projections.',
        neighborhoods: 'Verrado, Sun Valley, West Phoenix area, Sundance, Blue Horizons, Watson Road corridor, Southern Ave corridor',
        nearby: 'Goodyear, Avondale, Surprise, Wickenburg, Tonopah',
        seller_hook: 'Buckeye\'s explosive growth and new-construction buyer demand create strong appreciation even for existing homes — let competing agents on RealtorFinder earn the right to maximize your sale.',
        realtor_hook: 'Buckeye\'s rapid population growth and abundant new listings create one of Arizona\'s most dynamic listing pipelines — RealtorFinder connects you with motivated sellers in this high-growth market.',
    },
    {
        slug: 'tucson',
        name: 'Tucson',
        county: 'Pima',
        state: 'AZ',
        zip: '85701',
        population: '547553',
        median_price: '$320,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Tucson is the cultural and intellectual capital of Southern Arizona — a university city where the University of Arizona\'s 45,000 students, Davis-Monthan Air Force Base\'s military employment, and a nationally recognized arts scene in the Barrio Viejo and Fourth Avenue districts define a progressive, eclectic community with the Sonoran Desert\'s iconic saguaro landscape as its dramatic backdrop. Catalina Foothills\' luxury canyon estates, the Sam Hughes historic neighborhood, and the emerging Mercado District\'s walkable village give buyers an unusually diverse range of lifestyle options for a city of this size.',
        neighborhoods: 'Fourth Avenue, Sam Hughes, Barrio Viejo, Catalina Foothills, Armory Park, West University, Rincon Heights, Civano',
        nearby: 'Marana, Oro Valley, Sahuarita, Green Valley, Sierra Vista',
        seller_hook: 'Tucson\'s university and military buyer base creates consistent year-round demand — let competing Pima County agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Tucson\'s large population, diverse demographics, and UA and military employment create one of Arizona\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'marana',
        name: 'Marana',
        county: 'Pima',
        state: 'AZ',
        zip: '85653',
        population: '55806',
        median_price: '$390,000',
        price_trend: 'up 5%',
        avg_dom: 33,
        description: 'Marana is the Tucson metro\'s fastest-growing suburb — a northwestern master-planned community that has leveraged its position along I-10 between Tucson and Phoenix to attract logistics and industrial employers while building world-class amenities including the Ritz-Carlton Dove Mountain resort, Heritage Highlands golf club, and a continuous ribbon of Tortolita Mountain parks that give residents rare desert wilderness access from their neighborhoods. Dove Mountain\'s luxury custom homes and Gladden Farms\' family master plans reflect a suburb growing faster than its infrastructure.',
        neighborhoods: 'Dove Mountain, Heritage Highlands, Gladden Farms, Continental Ranch, Tortolita Vistas, Twin Peaks corridor',
        nearby: 'Tucson, Oro Valley, Sahuarita, Casa Grande, Phoenix',
        seller_hook: 'Marana\'s rapid growth and Dove Mountain prestige attract a motivated, upscale buyer base — let competing Northwest Tucson agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Marana\'s explosive growth trajectory and luxury resort community create premium listing opportunities in the Tucson metro\'s most dynamic suburb — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'oro-valley',
        name: 'Oro Valley',
        county: 'Pima',
        state: 'AZ',
        zip: '85737',
        population: '47070',
        median_price: '$490,000',
        price_trend: 'up 4%',
        avg_dom: 36,
        description: 'Oro Valley is the Tucson metro\'s premier family suburb — a carefully planned community of golf course estates and master-planned neighborhoods nestled against the Santa Catalina Mountains that has earned national recognition for public safety, top-rated Amphitheater and Flowing Wells school districts, and a thriving Steam Pump Ranch heritage park that anchors community identity. The Tucson Premium Outlets, Oro Valley Marketplace, and an active cycling community on the Oracle Road corridor reflect a suburb that has grown up without losing its small-town character.',
        neighborhoods: 'Rancho Vistoso, Honey Bee Hills, Sun City Vistoso, Steam Pump Ranch area, Catalina Shadows, Lambert Lane corridor',
        nearby: 'Tucson, Marana, Catalina, Saddlebrooke, Cortaro',
        seller_hook: 'Oro Valley\'s top-rated schools and mountain-view lifestyle attract premium buyers from across Southern Arizona — let competing agents on RealtorFinder earn your listing with their best proposal.',
        realtor_hook: 'Oro Valley\'s affluent demographics and premium school districts attract highly qualified buyers consistently — RealtorFinder connects you with motivated sellers in this sought-after Tucson suburb.',
    },
    {
        slug: 'sahuarita',
        name: 'Sahuarita',
        county: 'Pima',
        state: 'AZ',
        zip: '85629',
        population: '35279',
        median_price: '$330,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Sahuarita is a rapidly growing southern Pima County suburb positioned between Tucson and the border — a community anchored by the Freeport-McMoRan Sierrita copper mine, the expansive Rancho Sahuarita planned community with its lakeside parks and community events, and easy I-19 access to Tucson\'s employment centers and University of Arizona. Green Valley\'s enormous active-adult community borders Sahuarita to the south, creating a diverse residential corridor with both young family and retirement buyer demand.',
        neighborhoods: 'Rancho Sahuarita, Quail Creek border, Sahuarita proper, Green Valley border, Sahuarita Farms area, Continental Ranch border',
        nearby: 'Tucson, Green Valley, Nogales, Marana, Sierra Vista',
        seller_hook: 'Sahuarita\'s combination of young-family and retiree buyer markets creates year-round demand — let competing Pima County agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Sahuarita\'s dual family and active-adult buyer markets create consistent listing opportunities south of Tucson — RealtorFinder connects you with motivated sellers in this growing community.',
    },
    {
        slug: 'flagstaff',
        name: 'Flagstaff',
        county: 'Coconino',
        state: 'AZ',
        zip: '86001',
        population: '76831',
        median_price: '$650,000',
        price_trend: 'up 4%',
        avg_dom: 42,
        description: 'Flagstaff is Arizona\'s mountain city — a ponderosa pine-forested high-altitude community at 7,000 feet where Northern Arizona University\'s 28,000 students, the Arizona Snowbowl ski resort, and year-round outdoor recreation create a uniquely un-Arizona lifestyle that commands significant price premiums. Historic Downtown Flagstaff\'s brick-street dining and brewing scene, the Southside creative district, and established neighborhoods like Sunnyside and Cheshire reflect a genuine college town culture that remote workers and second-home buyers from Phoenix increasingly covet.',
        neighborhoods: 'Historic Downtown, Southside, Sunnyside, Cheshire, University Heights, Continental Country Club, Kachina Village, Ponderosa Trails',
        nearby: 'Sedona, Williams, Winslow, Prescott, Cottonwood',
        seller_hook: 'Flagstaff\'s rare mountain lifestyle and NAU buyer base create a competitive market that rewards well-presented listings — let top-rated agents on RealtorFinder earn your sale.',
        realtor_hook: 'Flagstaff\'s limited inventory, mountain lifestyle premium, and NAU-driven demand create strong appreciation and motivated buyers — RealtorFinder connects you with sellers ready to capitalize.',
    },
    {
        slug: 'prescott',
        name: 'Prescott',
        county: 'Yavapai',
        state: 'AZ',
        zip: '86301',
        population: '46606',
        median_price: '$560,000',
        price_trend: 'up 4%',
        avg_dom: 44,
        description: 'Prescott is Arizona\'s "Everybody\'s Hometown" — a mile-high former territorial capital with a Victorian courthouse plaza, the famous Whiskey Row saloon district, and a walkable historic downtown that has made it one of the Southwest\'s most desirable retirement and second-home destinations. Embry-Riddle Aeronautical University\'s campus, Yavapai Regional Medical Center\'s growing campus, and the city\'s National Forest access and mild four-season climate draw a diverse mix of retirees, outdoor enthusiasts, and remote workers unwilling to choose between mountain living and urban amenities.',
        neighborhoods: 'Downtown Courthouse Plaza area, Prescott Country Club, Granite Dells Estates, Iron Springs area, Miller Valley, Talking Rock, Williamson Valley',
        nearby: 'Prescott Valley, Chino Valley, Dewey-Humboldt, Mayer, Cottonwood',
        seller_hook: 'Prescott\'s retirement and second-home buyer market creates strong demand from well-funded buyers — let competing Yavapai County agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Prescott\'s affluent retiree and second-home buyer base creates a premium listing environment in Central Arizona\'s most charming city — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'yuma',
        name: 'Yuma',
        county: 'Yuma',
        state: 'AZ',
        zip: '85364',
        population: '99623',
        median_price: '$265,000',
        price_trend: 'up 4%',
        avg_dom: 40,
        description: 'Yuma is the agricultural capital of the Southwest and the sunniest city on Earth by recorded sunshine hours — a binational community on the Colorado River where Marine Corps Air Station Yuma\'s military employment, the Yuma Crossing National Heritage Area\'s historic river crossing, and the nation\'s lettuce and leafy green production capital create a distinctive economic identity. Foothills\' rapidly growing master-planned neighborhoods and the historic downtown\'s revitalization efforts are attracting retirees and young families seeking genuine affordability in Arizona\'s sunniest corner.',
        neighborhoods: 'Foothills, Downtown Yuma, Avenue B area, Fortuna Foothills, West Yuma, Carver Park, Pacific area',
        nearby: 'San Luis, Somerton, Wellton, El Centro CA, Mexicali Mexico',
        seller_hook: 'Yuma\'s military relocation demand and winter visitor buyers create year-round buyer activity — let competing local agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Yuma\'s military base relocation stream and winter-visitor second-home market create consistent listing activity at accessible price points — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'lake-havasu-city',
        name: 'Lake Havasu City',
        county: 'Mohave',
        state: 'AZ',
        zip: '86403',
        population: '57144',
        median_price: '$390,000',
        price_trend: 'up 4%',
        avg_dom: 45,
        description: 'Lake Havasu City is Arizona\'s premier desert water recreation destination — a planned community built around the London Bridge (relocated here in 1971) and the Colorado River\'s blue water that draws boaters, spring breakers, and retirees to a lifestyle centered on the water. The island channel below the London Bridge, Rotary Community Park\'s waterfront amenities, and Windsor Beach State Park anchor a tourism economy that supports year-round visitor traffic and a real estate market driven equally by primary residents and vacation property investors.',
        neighborhoods: 'Island area, Smoketree, Lake Havasu Estates, Northside, Southside, Havasu Heights, Horizon One',
        nearby: 'Bullhead City, Kingman, Needles CA, Parker, Laughlin NV',
        seller_hook: 'Lake Havasu\'s vacation and retirement buyer demand creates competitive bidding for waterfront-adjacent properties — let top-rated agents on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Lake Havasu\'s recreational lifestyle attracts vacation buyers and retirees from across the Southwest, creating motivated listing opportunities — RealtorFinder connects you with sellers ready to act.',
    },
    {
        slug: 'sierra-vista',
        name: 'Sierra Vista',
        county: 'Cochise',
        state: 'AZ',
        zip: '85635',
        population: '43888',
        median_price: '$270,000',
        price_trend: 'up 4%',
        avg_dom: 42,
        description: 'Sierra Vista is Southern Arizona\'s military city — a borderland community built to serve Fort Huachuca, the U.S. Army\'s intelligence and cyber warfare center and the economic engine of Cochise County, that has developed an identity around Ramsey Canyon\'s world-famous hummingbird sanctuary, the San Pedro Riparian National Conservation Area\'s premier birding trails, and the Huachuca Mountains\' hiking and camping access. The city\'s combination of military stability, outdoor recreation, and genuine affordability attracts both active-duty families and retirees seeking quality of life in a quiet corner of Arizona.',
        neighborhoods: 'Garden Canyon area, Thunderbird Hills, Canyon de Oro, Fry area, Bella Vista area, Buena area, Post Oak',
        nearby: 'Bisbee, Douglas, Tombstone, Huachuca City, Hereford',
        seller_hook: 'Sierra Vista\'s Fort Huachuca relocation demand and retiree buyers create year-round market activity — let competing agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Sierra Vista\'s military relocation stream and outdoor-lifestyle retiree buyers create consistent listing activity at affordable price points — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'sedona',
        name: 'Sedona',
        county: 'Yavapai',
        state: 'AZ',
        zip: '86336',
        population: '10338',
        median_price: '$850,000',
        price_trend: 'up 5%',
        avg_dom: 55,
        description: 'Sedona is one of America\'s most visually dramatic small cities — a spiritual and artistic community set among iconic red sandstone buttes and canyons in the Verde Valley where world-class spa resorts like Enchantment and L\'Auberge, the Tlaquepaque arts village, and some of the Southwest\'s most celebrated hiking trails on the Vultee Arch and Cathedral Rock attract a global visitor base and a residential market defined by luxury second homes and high-net-worth full-time residents. Limited geography, strict dark-sky ordinances, and strong short-term rental demand make Sedona Arizona\'s most exclusive small-city real estate market.',
        neighborhoods: 'Uptown Sedona, West Sedona, Village of Oak Creek, Chapel area, Coffee Pot area, Tlaquepaque area, Soldier Pass',
        nearby: 'Cottonwood, Camp Verde, Flagstaff, Jerome, Prescott',
        seller_hook: 'Sedona\'s global appeal and limited housing supply create premium buyer competition — let top luxury agents on RealtorFinder compete to achieve the best possible sale price for your property.',
        realtor_hook: 'Sedona\'s ultra-desirable lifestyle and constrained supply make each listing a significant opportunity — RealtorFinder connects you with motivated sellers in Arizona\'s most coveted small-city market.',
    },
];
