// cities/ca-extra.js — Additional California city data for SEO landing pages
// Base ca.js already covers: LA, San Diego, San Jose, SF, Oakland, Berkeley, Fremont, Hayward,
// Santa Clara, Sunnyvale, Cupertino, Palo Alto, Mountain View, San Mateo, Redwood City,
// Foster City, Burlingame, San Ramon, Pleasanton, Livermore, Walnut Creek, Concord, Richmond,
// Sacramento, Elk Grove, Roseville, Folsom, Rancho Cordova, Rocklin, Lincoln, Riverside,
// San Bernardino, Redlands, Fontana, Ontario, Rancho Cucamonga, Irvine, Anaheim, Santa Ana,
// Huntington Beach, Costa Mesa, Newport Beach, Long Beach, Pasadena, Glendale, Burbank,
// Santa Monica, Torrance, Thousand Oaks, Ventura, Santa Barbara, Fresno, Bakersfield,
// Stockton, Modesto

module.exports = [
    {
        slug: 'oxnard',
        name: 'Oxnard',
        county: 'Ventura',
        state: 'CA',
        zip: '93030',
        population: '202,000',
        median_price: '$690,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Oxnard is Ventura County\'s largest city and a working-class coastal community on the Pacific — a strawberry and citrus agriculture hub where Channel Islands Harbor, Naval Base Ventura County, and LA commuter demand create a market where buyers find Ventura County beach access at prices below Santa Barbara and Malibu, with Channel Islands National Park boating a major lifestyle draw.',
        neighborhoods: 'Seabridge, RiverPark, Westport, Oxnard Shores, Silver Strand',
        nearby: 'Ventura, Camarillo, Thousand Oaks, Port Hueneme, Santa Paula',
        seller_hook: 'Oxnard\'s coastal access and LA commuter appeal drive strong Ventura County buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Oxnard\'s Navy community and beach lifestyle create consistent listing activity in the Ventura County market — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'santa-rosa',
        name: 'Santa Rosa',
        county: 'Sonoma',
        state: 'CA',
        zip: '95401',
        population: '178,000',
        median_price: '$720,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Santa Rosa is Sonoma Wine Country\'s urban hub and the North Bay\'s largest city — a community rebuilt after devastating wildfires where Sonoma State University, a thriving healthcare corridor, and Bay Area remote worker influx have restored and elevated the housing market, with buyers paying a Sonoma County wine country premium for Napa-adjacent lifestyle at Bay Area-accessible prices.',
        neighborhoods: 'Fountaingrove, Bennett Valley, Rincon Valley, Railroad Square, Roseland',
        nearby: 'Petaluma, Rohnert Park, Windsor, Healdsburg, Sebastopol',
        seller_hook: 'Santa Rosa\'s Wine Country location and North Bay recovery attract motivated buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Santa Rosa\'s Sonoma County market and Bay Area remote worker demand create strong listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'moreno-valley',
        name: 'Moreno Valley',
        county: 'Riverside',
        state: 'CA',
        zip: '92553',
        population: '208,000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Moreno Valley is the Inland Empire\'s fastest-growing city and a logistics hub anchored by the World Logistics Center — a Riverside County community where March Air Reserve Base, Valley Children\'s Hospital proximity, and affordable Southern California homeownership for logistics corridor workers attract first-generation homeowners and military families seeking LA-metro access on Inland Empire budgets.',
        neighborhoods: 'Sunnymead Ranch, Towngate, Canyon Crest, Perris, Beaumont',
        nearby: 'Perris, Riverside, Beaumont, Hemet, Banning',
        seller_hook: 'Moreno Valley\'s Inland Empire growth and March ARB community drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Moreno Valley\'s logistics sector and affordable SoCal prices create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'santa-cruz-ca',
        name: 'Santa Cruz',
        county: 'Santa Cruz',
        state: 'CA',
        zip: '95060',
        population: '65,000',
        median_price: '$1,050,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Santa Cruz is California\'s surf capital and a UC Santa Cruz college town on Monterey Bay — a progressive coastal community where Boardwalk amusement park nostalgia, world-class surfing at Steamer Lane, and a proximity to Silicon Valley that makes it a beloved remote worker destination create fierce buyer competition for a limited inventory of Victorian homes, beach bungalows, and Westside cottages.',
        neighborhoods: 'Westside, Seabright, Pleasure Point, Live Oak, Capitola',
        nearby: 'Capitola, Scotts Valley, Aptos, Watsonville, Los Gatos',
        seller_hook: 'Santa Cruz\'s surf culture and Silicon Valley proximity create intense buyer competition — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Santa Cruz\'s coastal premium and remote worker demand generate fast-moving listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'chico-ca',
        name: 'Chico',
        county: 'Butte',
        state: 'CA',
        zip: '95928',
        population: '103,000',
        median_price: '$410,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Chico is California State University, Chico\'s college town and the North Valley\'s most livable city — a tree canopied community where CSU Chico\'s renowned brewing science and agriculture programs, a thriving Bidwell Park outdoor recreation culture, and some of northern California\'s most affordable home prices attract students, faculty, and Bay Area buyers seeking an authentic California lifestyle away from coastal crowds.',
        neighborhoods: 'Bidwell Park, East Avenue, Chapmantown, Nord, Durham',
        nearby: 'Durham, Orland, Paradise, Oroville, Gridley',
        seller_hook: 'Chico\'s CSU enrollment and northern California affordability create consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Chico\'s university market and North Valley lifestyle generate active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'redding-ca',
        name: 'Redding',
        county: 'Shasta',
        state: 'CA',
        zip: '96001',
        population: '93,000',
        median_price: '$365,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Redding is the Gateway to the Cascades and far northern California\'s commercial hub — a Shasta Dam and Sacramento River city where a regional healthcare complex, outdoor recreation access to Shasta Lake, Whiskeytown NRA, and Mount Shasta skiing, and some of California\'s most affordable single-family homes attract retiring Californians and remote workers seeking space, sunshine, and a genuine small-city lifestyle.',
        neighborhoods: 'Shasta Lake City, Anderson, Palo Cedro, Cottonwood, Red Bluff',
        nearby: 'Anderson, Shasta Lake City, Cottonwood, Corning, Red Bluff',
        seller_hook: 'Redding\'s northern California affordability and outdoor lifestyle attract motivated buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Redding\'s retirement and remote worker market generate consistent listing activity in the North State — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'visalia-ca',
        name: 'Visalia',
        county: 'Tulare',
        state: 'CA',
        zip: '93291',
        population: '141,000',
        median_price: '$365,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Visalia is the San Joaquin Valley\'s gateway to Sequoia and Kings Canyon National Parks and Tulare County\'s largest city — an agricultural and healthcare hub where Kaweah Delta Medical Center, College of the Sequoias, and some of inland California\'s most affordable homes attract farm families, medical workers, and buyers who want to live near two of America\'s most breathtaking national parks.',
        neighborhoods: 'Tulare, Exeter, Farmersville, Cutler-Orosi, Dinuba',
        nearby: 'Tulare, Porterville, Hanford, Fresno, Three Rivers',
        seller_hook: 'Visalia\'s national parks gateway and Central Valley affordability attract strong buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Visalia\'s agricultural and healthcare market create consistent listing activity at Central Valley prices — find sellers through RealtorFinder.',
    },
    {
        slug: 'palmdale-ca',
        name: 'Palmdale',
        county: 'Los Angeles',
        state: 'CA',
        zip: '93550',
        population: '169,000',
        median_price: '$450,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Palmdale is the Antelope Valley\'s largest city and Los Angeles County\'s most affordable metropolitan community — a high desert aerospace hub where Northrop Grumman, Lockheed Martin\'s Skunk Works, and Edwards Air Force Base employment create demand for the most affordable single-family home prices in LA County, drawing first-time buyers and aerospace workers who accept a 60-mile commute for homeownership that would cost three times as much near LAX.',
        neighborhoods: 'Quartz Hill, Littlerock, Leona Valley, Lake Los Angeles, Pearblossom',
        nearby: 'Lancaster, Quartz Hill, Leona Valley, Lake Los Angeles, Rosamond',
        seller_hook: 'Palmdale\'s Antelope Valley aerospace employment and LA County affordability create consistent buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Palmdale\'s aerospace workforce and first-time buyer market generate active listing conditions in the Antelope Valley — find sellers through RealtorFinder.',
    },
    {
        slug: 'lancaster-ca',
        name: 'Lancaster',
        county: 'Los Angeles',
        state: 'CA',
        zip: '93534',
        population: '157,000',
        median_price: '$420,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Lancaster is the Antelope Valley\'s second city and a solar energy capital built on the Mojave Desert floor — a community where California\'s most aggressive solar mandate, NASA Armstrong Flight Research Center, and LA County\'s most affordable detached home prices create a diverse market of aerospace workers, commuters, and first-time buyers who find ample square footage and desert sunshine within the nation\'s largest county.',
        neighborhoods: 'Quartz Hill, Rosamond, Antelope Acres, Del Sur, Lake Los Angeles',
        nearby: 'Palmdale, Rosamond, Quartz Hill, Mojave, Tehachapi',
        seller_hook: 'Lancaster\'s Antelope Valley solar economy and LA County affordability attract motivated buyers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Lancaster\'s aerospace and first-time buyer market create consistent listing activity in the high desert — connect with sellers through RealtorFinder.',
    },
];
