// cities/ca-extra.js — Additional California city data for SEO landing pages

module.exports = [
    {
        slug: 'stockton',
        name: 'Stockton',
        county: 'San Joaquin',
        state: 'CA',
        zip: '95202',
        population: '320,000',
        median_price: '$440,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Stockton is the San Joaquin Valley\'s largest city and the Bay Area\'s most affordable bedroom community — a Delta waterway city where University of the Pacific, a massive Amazon and logistics hub, and Bay Area spillover buyers priced out of Alameda and Contra Costa counties drive housing demand among first-generation homeowners, commuters, and investors seeking Central Valley returns on Bay Area-scale incomes.',
        neighborhoods: 'Lincoln Village, Brookside, Spanos Park, Bear Creek, Weston Ranch',
        nearby: 'Lodi, Manteca, Tracy, Modesto, Lathrop',
        seller_hook: 'Stockton\'s Bay Area spillover demand and Amazon logistics growth drive competitive buyer activity — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Stockton\'s Bay Area commuter market and strong appreciation create active listing conditions — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'bakersfield',
        name: 'Bakersfield',
        county: 'Kern',
        state: 'CA',
        zip: '93301',
        population: '407,000',
        median_price: '$390,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Bakersfield is California\'s oil capital and a Central Valley agricultural powerhouse — the birthplace of the Bakersfield Sound country music tradition, anchored by Chevron refinery operations, California State University Bakersfield, and one of California\'s most affordable major city housing markets where Los Angeles commuters and oil industry workers find single-family homes at a fraction of coastal prices.',
        neighborhoods: 'Seven Oaks, Riverlakes Ranch, Oleander, Silver Creek, Rosedale',
        nearby: 'Delano, Tehachapi, Shafter, Arvin, McFarland',
        seller_hook: 'Bakersfield\'s oil sector and LA commuter demand keep buyers active in California\'s most affordable major city — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Bakersfield\'s energy economy and Central Valley affordability generate consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'oxnard',
        name: 'Oxnard',
        county: 'Ventura',
        state: 'CA',
        zip: '93030',
        population: '202,000',
        median_price: '$690,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Oxnard is Ventura County\'s largest city and a working-class coastal community on the Pacific — a strawberry and citrus agriculture hub where Channel Islands Harbor, Naval Base Ventura County, and LA commuter demand create a market where buyers find Ventura County beach access at prices below Santa Barbara and Malibu, with Channel Islands National Park boating a major lifestyle draw.',
        neighborhoods: 'Seabridge, RiverPark, Westport, Oxnard Shores, Silver Strand',
        nearby: 'Ventura, Camarillo, Thousand Oaks, Port Hueneme, Santa Paula',
        seller_hook: 'Oxnard\'s coastal access and LA commuter appeal drive strong Ventura County buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Oxnard\'s Navy community and beach lifestyle create consistent listing activity in the Ventura County market — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'modesto',
        name: 'Modesto',
        county: 'Stanislaus',
        state: 'CA',
        zip: '95354',
        population: '218,000',
        median_price: '$400,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Modesto is the Central Valley\'s American Graffiti city and Stanislaus County\'s agricultural hub — a community where E&J Gallo Winery, Blue Diamond almonds, and Stanislaus County government create a diverse economy, and Bay Area equity buyers priced out of the East Bay find large single-family homes with yards at prices that represent genuine value compared to comparable Bay Area properties.',
        neighborhoods: 'Beyer Park, Sherwood Forest, Shackelford, Dry Creek, Salida',
        nearby: 'Turlock, Ceres, Riverbank, Oakdale, Stockton',
        seller_hook: 'Modesto\'s Bay Area spillover demand and Central Valley affordability attract motivated buyers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Modesto\'s agricultural economy and commuter market generate consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'santa-rosa',
        name: 'Santa Rosa',
        county: 'Sonoma',
        state: 'CA',
        zip: '95401',
        population: '178,000',
        median_price: '$720,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Santa Rosa is Sonoma Wine Country\'s urban hub and the North Bay\'s largest city — a community rebuilt after devastating Tubbs and Kincade wildfires, where Sonoma State University, a thriving healthcare corridor, and Bay Area remote worker influx have restored and elevated the housing market, with buyers paying a Sonoma County wine country premium for Napa-adjacent lifestyle at Bay Area-accessible prices.',
        neighborhoods: 'Fountaingrove, Bennett Valley, Rincon Valley, Railroad Square, Roseland',
        nearby: 'Petaluma, Rohnert Park, Windsor, Healdsburg, Sebastopol',
        seller_hook: 'Santa Rosa\'s Wine Country location and North Bay recovery story attract motivated buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Santa Rosa\'s Sonoma County market and Bay Area remote worker demand create strong listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'elk-grove',
        name: 'Elk Grove',
        county: 'Sacramento',
        state: 'CA',
        zip: '95624',
        population: '176,000',
        median_price: '$570,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Elk Grove is Sacramento\'s fastest-growing suburb and one of California\'s most diverse planned communities — a South Sacramento community where top-ranked Elk Grove Unified School District schools, proximity to Sacramento International Airport, and a thriving Southeast Asian and South Asian community create intense buyer demand from families seeking Sacramento metro living with superior school options.',
        neighborhoods: 'Laguna, Stonelake, Paloma, Sheldon, Calvine',
        nearby: 'Sacramento, Galt, Folsom, Rancho Cordova, Citrus Heights',
        seller_hook: 'Elk Grove\'s top schools and diverse buyer pool create competitive listing conditions — let RealtorFinder agents compete for your home.',
        realtor_hook: 'Elk Grove\'s South Sacramento growth and family buyer demand generate fast-moving listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'fontana',
        name: 'Fontana',
        county: 'San Bernardino',
        state: 'CA',
        zip: '92335',
        population: '214,000',
        median_price: '$530,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Fontana is the Inland Empire\'s industrial powerhouse and one of Southern California\'s largest cities — a logistics and NASCAR racing hub where massive warehouse and distribution operations along the I-10 and I-15 corridors create working-class buyer demand for affordable Inland Empire homeownership from families priced out of LA and Orange County but employed in SoCal\'s massive goods movement economy.',
        neighborhoods: 'Sierra Lakes, Heritage Village, North Fontana, South Fontana, Rialto',
        nearby: 'Rialto, Ontario, Rancho Cucamonga, Bloomington, San Bernardino',
        seller_hook: 'Fontana\'s Inland Empire logistics growth and SoCal commuter demand drive consistent buyer activity — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Fontana\'s working-class buyer base and Inland Empire growth generate active listing conditions — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'moreno-valley',
        name: 'Moreno Valley',
        county: 'Riverside',
        state: 'CA',
        zip: '92553',
        population: '208,000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Moreno Valley is the Inland Empire\'s fastest-growing city and a logistics hub anchored by the World Logistics Center — a Riverside County community where March Air Reserve Base, Valley Children\'s Hospital proximity, and affordable Southern California homeownership for workers in the Ontario and Riverside logistics corridor attract first-generation homeowners and military families seeking LA-metro access on Inland Empire budgets.',
        neighborhoods: 'Sunnymead Ranch, Towngate, Canyon Crest, Perris, Beaumont',
        nearby: 'Perris, Riverside, Beaumont, Hemet, Banning',
        seller_hook: 'Moreno Valley\'s Inland Empire growth and March ARB community drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Moreno Valley\'s logistics sector and affordable SoCal prices create active listing conditions — find sellers through RealtorFinder.',
    },
];
