// cities/co.js — Colorado city data for SEO landing pages

module.exports = [
    {
        slug: 'denver',
        name: 'Denver',
        county: 'Denver',
        state: 'CO',
        zip: '80202',
        population: '715,000',
        median_price: '$620,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Denver is the Mile High City and the Rocky Mountain West\'s premier metropolis — a booming tech and energy hub where walkable neighborhoods like Capitol Hill, Highland, and Wash Park, a craft brewery culture, and 300 days of sunshine attract transplants from both coasts seeking mountain lifestyle paired with a thriving urban economy.',
        neighborhoods: 'Capitol Hill, Highland, Washington Park, Cherry Creek, Five Points, Baker, RiNo, Congress Park',
        nearby: 'Aurora, Lakewood, Arvada, Englewood, Westminster',
        seller_hook: 'Denver\'s sustained in-migration and urban neighborhood demand drive strong year-round buyer competition — let top Denver agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Denver\'s tech economy and coastal transplant buyer influx create one of the Mountain West\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'aurora-co',
        name: 'Aurora',
        county: 'Arapahoe',
        state: 'CO',
        zip: '80010',
        population: '386,000',
        median_price: '$480,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Aurora is Colorado\'s third-largest city and Denver\'s most diverse suburb — a sprawling metro anchored by Aurora Medical Center, Buckley Space Force Base, and an expanding University of Colorado Health campus where affordable entry-level prices and strong I-225 light rail access attract first-time buyers and young families from across the Denver metro.',
        neighborhoods: 'Southlands, Murphy Creek, Stapleton border, Saddle Rock, Tollgate Crossing, Aurora Hills',
        nearby: 'Denver, Parker, Centennial, Englewood, Commerce City',
        seller_hook: 'Aurora\'s military and healthcare buyer base create consistent demand across price ranges — let competing Arapahoe County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Aurora\'s large military and medical workforce create reliable listing volume at accessible price points — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'lakewood-co',
        name: 'Lakewood',
        county: 'Jefferson',
        state: 'CO',
        zip: '80226',
        population: '160,000',
        median_price: '$550,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Lakewood is Jefferson County\'s largest city and Denver\'s most accessible western suburb — a light rail-connected community with the popular Belmar district, easy foothills access, and proximity to both downtown Denver and Red Rocks Amphitheatre that attracts outdoor enthusiasts and urban professionals seeking mountain proximity at metro prices.',
        neighborhoods: 'Belmar, Lakewood Estates, Green Gables, Eiber, Westgate, Union Hills, Solterra',
        nearby: 'Denver, Arvada, Golden, Englewood, Morrison',
        seller_hook: 'Lakewood\'s foothills access and Belmar district popularity attract motivated buyers — let competing Jefferson County agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Lakewood\'s light rail access and outdoor lifestyle appeal generate consistent buyer demand — RealtorFinder connects you with motivated sellers in west Denver.',
    },
    {
        slug: 'arvada',
        name: 'Arvada',
        county: 'Jefferson',
        state: 'CO',
        zip: '80002',
        population: '118,000',
        median_price: '$580,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Arvada is one of the Denver metro\'s most beloved suburbs — a city with a beautifully revitalized Olde Town district, new Gold Line light rail connections to downtown Denver, and an outdoor-oriented community that has made it a top choice for families seeking mountain access, strong schools, and a genuine small-town character within the metro.',
        neighborhoods: 'Olde Town Arvada, Ralston Valley, West Woods, Candelas, Wildgrass, Sheridan Green',
        nearby: 'Lakewood, Westminster, Golden, Broomfield, Denver',
        seller_hook: 'Arvada\'s Olde Town character and light rail access drive strong buyer demand — let competing Jefferson County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Arvada\'s Olde Town revival and Gold Line connectivity create consistent premium listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'westminster-co',
        name: 'Westminster',
        county: 'Adams',
        state: 'CO',
        zip: '80030',
        population: '116,000',
        median_price: '$540,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Westminster sits on the Adams-Jefferson county border and is one of Denver\'s most strategically located northern suburbs — an evolving city with a major transit-oriented development underway at the old Westminster Mall site, strong tech employment along the US-36 corridor, and easy access to both Denver and Boulder that draws buyers from both job markets.',
        neighborhoods: 'Bradburn Village, Anthem, Legacy Ridge, Ranch Reserve, Westfield, Hyland Hills',
        nearby: 'Broomfield, Arvada, Thornton, Louisville CO, Denver',
        seller_hook: 'Westminster\'s US-36 corridor jobs and access to both Denver and Boulder attract buyers from two major markets — let competing agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Westminster\'s dual-market access and growing tech employment create consistent listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'thornton',
        name: 'Thornton',
        county: 'Adams',
        state: 'CO',
        zip: '80229',
        population: '141,000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Thornton is Adams County\'s largest city and one of the Denver metro\'s most affordable northern suburbs — a rapidly growing community with new North Metro rail service to Union Station, strong retail corridors along I-25, and family-friendly neighborhoods that attract buyers seeking Denver metro access at prices well below the regional median.',
        neighborhoods: 'Eastlake, Todd Creek, North Creek, Thorncreek, Hunters Glen, Woodglen',
        nearby: 'Westminster, Brighton, Commerce City, Denver, Northglenn',
        seller_hook: 'Thornton\'s North Metro rail and affordable pricing attract buyers priced out of closer-in suburbs — let competing Adams County agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Thornton\'s affordability and rail connectivity generate consistent buyer demand — RealtorFinder connects you with motivated sellers in north Adams County.',
    },
    {
        slug: 'brighton-co',
        name: 'Brighton',
        county: 'Adams',
        state: 'CO',
        zip: '80601',
        population: '40,000',
        median_price: '$460,000',
        price_trend: 'up 7%',
        avg_dom: 27,
        description: 'Brighton is Adams County\'s seat and one of the Denver metro\'s fastest-growing outer suburbs — a historic agricultural town evolving into a new-construction hub along the I-76 corridor where affordability, large lots, and easy access to downtown Denver via commuter rail attract buyers seeking space and value on the metro\'s northeastern frontier.',
        neighborhoods: 'Brighton Crossing, Todd Creek Village, Bromley Park, Platte Valley, Downtown Brighton',
        nearby: 'Thornton, Commerce City, Fort Lupton, Keenesburg, Lochbuie',
        seller_hook: 'Brighton\'s new construction boom and commuter rail access attract a growing buyer pool — let competing agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Brighton\'s rapid growth and affordable price point generate strong listing volume on Denver\'s eastern frontier — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'parker-co',
        name: 'Parker',
        county: 'Douglas',
        state: 'CO',
        zip: '80134',
        population: '62,000',
        median_price: '$650,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Parker is Douglas County\'s most charming suburb — a rapidly growing community with a beloved Main Street Mainstreet district, top-ranked Douglas County schools, and a strong equestrian heritage that attracts families and professionals seeking the Colorado outdoor lifestyle, excellent schools, and a true community character within the Denver metro.',
        neighborhoods: 'Main Street Parker, The Pinery, Clarke Farms, Stroh Ranch, Anthology, Sierra Ridge',
        nearby: 'Castle Rock, Lone Tree, Aurora, Centennial, Highlands Ranch',
        seller_hook: 'Parker\'s Main Street character and top Douglas County schools attract loyal buyers — let competing agents on RealtorFinder fight to earn the right to sell your home.',
        realtor_hook: 'Parker\'s family-focused market and top-ranked schools create consistent premium listing demand — RealtorFinder connects you with motivated sellers in Douglas County.',
    },
    {
        slug: 'lone-tree',
        name: 'Lone Tree',
        county: 'Douglas',
        state: 'CO',
        zip: '80124',
        population: '14,000',
        median_price: '$750,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Lone Tree is one of the Denver metro\'s most affluent small cities — a master-planned community anchored by the Park Meadows Mall, Charles Schwab headquarters, and Sky Ridge Medical Center where executives, financial services professionals, and healthcare workers drive some of the highest home values in Douglas County.',
        neighborhoods: 'Heritage Hills, RidgeGate, Acres Green, Wildcat Ridge, Village at Castle Pines',
        nearby: 'Highlands Ranch, Parker, Castle Rock, Centennial, Aurora',
        seller_hook: 'Lone Tree\'s corporate headquarters and executive buyer pool sustain premium values — let top Douglas County agents on RealtorFinder compete to achieve your maximum sale.',
        realtor_hook: 'Lone Tree\'s Schwab and medical center employment base deliver a high-income buyer pool and premium listing commissions — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'castle-rock-co',
        name: 'Castle Rock',
        county: 'Douglas',
        state: 'CO',
        zip: '80104',
        population: '72,000',
        median_price: '$650,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Castle Rock is Douglas County\'s seat and one of Colorado\'s fastest-growing cities — a scenic community at the base of its iconic butte with a revitalized Festival Park downtown, Factory Stores at Castle Rock outlet mall, and dramatic Front Range views that make it a top destination for Denver metro families seeking space, scenery, and top schools.',
        neighborhoods: 'The Meadows, Terrain, Crystal Valley, Cobblestone Ranch, Founders Village, Plum Creek',
        nearby: 'Parker, Lone Tree, Highlands Ranch, Monument, Larkspur',
        seller_hook: 'Castle Rock\'s scenic setting and rapid growth attract buyers from across the Denver-Colorado Springs corridor — let competing agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Castle Rock\'s fast-growing population and I-25 corridor location create one of Douglas County\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'highlands-ranch',
        name: 'Highlands Ranch',
        county: 'Douglas',
        state: 'CO',
        zip: '80129',
        population: '107,000',
        median_price: '$750,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Highlands Ranch is the Denver metro\'s largest master-planned community and one of Colorado\'s most consistently desirable addresses — a meticulously maintained suburb with four massive recreation centers, top-ranked Douglas County schools, and a community identity so strong that buyers relocate specifically to its zip codes from across the country.',
        neighborhoods: 'Highlands Ranch Town Center, Firelight, BackCountry, Westridge, Eastridge, Northridge',
        nearby: 'Lone Tree, Littleton, Parker, Englewood, Centennial',
        seller_hook: 'Highlands Ranch\'s national reputation and top Douglas County schools attract buyers from across the country — let competing agents on RealtorFinder compete to maximize your sale.',
        realtor_hook: 'Highlands Ranch\'s master-planned prestige and family-driven market create consistent premium listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'littleton-co',
        name: 'Littleton',
        county: 'Arapahoe',
        state: 'CO',
        zip: '80120',
        population: '47,000',
        median_price: '$590,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Littleton is one of Denver\'s most lovable inner suburbs — a historic city with a beautifully walkable Main Street, light rail access on multiple lines, Chatfield Reservoir outdoor recreation, and top-rated Littleton Public Schools that attract families seeking an established community character with excellent commute connectivity.',
        neighborhoods: 'Downtown Littleton, Columbine Valley, Centennial border, Highlands Ranch border, South Suburban area',
        nearby: 'Englewood, Centennial, Highlands Ranch, Lakewood, Lone Tree',
        seller_hook: 'Littleton\'s walkable Main Street and top schools attract motivated buyers — let competing Arapahoe County agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Littleton\'s established character and light rail access generate consistent buyer demand — RealtorFinder connects you with motivated sellers in south metro Denver.',
    },
    {
        slug: 'centennial-co',
        name: 'Centennial',
        county: 'Arapahoe',
        state: 'CO',
        zip: '80112',
        population: '109,000',
        median_price: '$600,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'Centennial is one of Colorado\'s newest incorporated cities and Arapahoe County\'s most prosperous suburb — a tech and aerospace employment corridor along Arapahoe Road where Lockheed Martin, Raytheon, and a cluster of defense contractors create a high-income buyer base and Centennial Airport access makes it attractive to executive homebuyers.',
        neighborhoods: 'Cherry Knolls, Willow Creek, Foxridge, Homestead, Piney Creek, Heritage Greens',
        nearby: 'Englewood, Littleton, Aurora, Parker, Greenwood Village',
        seller_hook: 'Centennial\'s defense and aerospace employer base attracts high-income buyers — let competing Arapahoe County agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Centennial\'s defense corridor employment and premium school reputation create consistent listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'englewood-co',
        name: 'Englewood',
        county: 'Arapahoe',
        state: 'CO',
        zip: '80110',
        population: '34,000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 23,
        description: 'Englewood is an inner Denver suburb undergoing a remarkable transformation — a walkable light rail city with the CityCenter Englewood mixed-use redevelopment, thriving South Broadway arts and restaurant district, and easy access to Cherry Hills Village and Belleview Corridor employment that attracts buyers seeking urban density at a relative discount.',
        neighborhoods: 'Downtown Englewood, South Broadway corridor, Bates Logan Park, Romans Park, Cherry Hills Village border',
        nearby: 'Denver, Littleton, Centennial, Sheridan, Greenwood Village',
        seller_hook: 'Englewood\'s South Broadway transformation and light rail access attract buyers seeking value near Denver — let competing agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Englewood\'s urban revitalization and Denver proximity attract buyers priced out of the city — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'boulder',
        name: 'Boulder',
        county: 'Boulder',
        state: 'CO',
        zip: '80301',
        population: '105,000',
        median_price: '$950,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Boulder is one of America\'s most desirable cities and Colorado\'s crown jewel of outdoor living — a world-class university city at the foot of the Flatirons where Pearl Street\'s vibrant pedestrian mall, a globally recognized startup ecosystem, and the nation\'s most educated populace create extraordinary and persistent buyer demand against severely constrained supply.',
        neighborhoods: 'Pearl Street, Mapleton Hill, University Hill, Martin Acres, Whittier, South Boulder, Table Mesa',
        nearby: 'Louisville CO, Lafayette CO, Longmont, Westminster, Superior',
        seller_hook: 'Boulder\'s nationally constrained supply and powerful demand from CU and tech buyers mean your home will command top dollar — let the best Boulder agents on RealtorFinder compete for it.',
        realtor_hook: 'Boulder\'s extraordinary demand and permanently constrained supply create Colorado\'s most rewarding listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'louisville-co',
        name: 'Louisville',
        county: 'Boulder',
        state: 'CO',
        zip: '80027',
        population: '21,000',
        median_price: '$700,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Louisville is one of Colorado\'s most consistently top-ranked small cities — a charming Boulder County community with a beloved Historic District downtown, excellent Boulder Valley School District ratings, US 36 tech corridor employment, and a community identity that draws buyers from Boulder who want the lifestyle at a relative discount.',
        neighborhoods: 'Historic Louisville, Coal Creek, South Boulder Road corridor, Rock Creek, Harper Lake',
        nearby: 'Boulder, Lafayette CO, Broomfield, Superior, Westminster',
        seller_hook: 'Louisville\'s beloved downtown and top Boulder Valley schools attract buyers eager to pay a premium — let competing Boulder County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Louisville\'s top national livability rankings and Boulder proximity create consistent premium listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'lafayette-co',
        name: 'Lafayette',
        county: 'Boulder',
        state: 'CO',
        zip: '80026',
        population: '30,000',
        median_price: '$620,000',
        price_trend: 'up 6%',
        avg_dom: 23,
        description: 'Lafayette is Boulder County\'s most affordable and rapidly growing city — a community with a thriving Old Town arts district, top-rated Boulder Valley schools, and excellent US-36 corridor access to both Boulder and Denver that attracts tech workers and young families seeking Boulder County lifestyle at prices that make ownership achievable.',
        neighborhoods: 'Old Town Lafayette, Waneka Lake, Indian Peaks, Centaur Village, Coal Creek',
        nearby: 'Louisville CO, Boulder, Broomfield, Longmont, Erie',
        seller_hook: 'Lafayette\'s affordability relative to Boulder and top schools attract motivated buyers — let competing agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Lafayette\'s Boulder County school reputation and relative affordability attract buyers priced out of Boulder — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'longmont',
        name: 'Longmont',
        county: 'Boulder',
        state: 'CO',
        zip: '80501',
        population: '96,000',
        median_price: '$530,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Longmont is Boulder County\'s largest and most affordable city — a tech and aerospace hub with IBM, Seagate, and OtterBox operations anchoring a diverse employment base where a revitalized Main Street, the scenic St. Vrain Creek corridor, and accessible pricing attract buyers seeking Boulder County character without Boulder County prices.',
        neighborhoods: 'Downtown Longmont, Old Town, Twin Peaks, Prospect, Southwest Longmont, Renaissance',
        nearby: 'Boulder, Lafayette CO, Loveland CO, Fort Collins, Berthoud',
        seller_hook: 'Longmont\'s tech employment and Boulder County location attract motivated buyers across a wide price range — let competing agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Longmont\'s tech employment base and Boulder County address create consistent listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'fort-collins',
        name: 'Fort Collins',
        county: 'Larimer',
        state: 'CO',
        zip: '80521',
        population: '165,000',
        median_price: '$580,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Fort Collins is Colorado\'s most celebrated college city and consistently ranks as one of America\'s best places to live — a Colorado State University town with a world-famous Old Town craft beer district, Cache la Poudre River access, and a tech and clean energy economy that attracts well-educated buyers and young families from across the nation.',
        neighborhoods: 'Old Town, Midtown, Harmony Road corridor, Fort Collins South, Rigden Farm, Maple Hill',
        nearby: 'Loveland CO, Windsor CO, Greeley, Berthoud, Laporte',
        seller_hook: 'Fort Collins\' national livability rankings and CSU buyer pool drive consistent strong demand — let competing Larimer County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Fort Collins\' CSU workforce and national livability recognition create a robust and consistent listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'windsor-co',
        name: 'Windsor',
        county: 'Weld',
        state: 'CO',
        zip: '80550',
        population: '28,000',
        median_price: '$490,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Windsor is one of Colorado\'s fastest-growing Front Range towns — a Weld-Larimer border community straddling the Fort Collins and Greeley metros where scenic Windsor Lake, top-ranked Weld RE-4 schools, and aggressively priced new construction attract buyers who want Fort Collins proximity and lifestyle at significantly lower price points.',
        neighborhoods: 'Downtown Windsor, Windsor Lake, Eastridge, Jacoby Farm, Highland Meadows, Chimney Park',
        nearby: 'Fort Collins, Greeley, Loveland CO, Johnstown, Severance',
        seller_hook: 'Windsor\'s rapid growth and Fort Collins proximity attract buyers seeking value — let competing Weld County agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Windsor\'s explosive growth and affordability relative to Fort Collins generate strong listing volume — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'greeley',
        name: 'Greeley',
        county: 'Weld',
        state: 'CO',
        zip: '80631',
        population: '107,000',
        median_price: '$390,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Greeley is Weld County\'s seat and northern Colorado\'s most affordable major city — anchored by the University of Northern Colorado, Aims Community College, and a large oil and gas industry workforce where strong job growth, affordable entry-level prices, and a revitalized downtown arts district attract first-time buyers and investors in this underrated market.',
        neighborhoods: 'Downtown Greeley, UNC campus area, West Greeley, Poudre River area, Promontory',
        nearby: 'Windsor CO, Fort Collins, Loveland CO, Evans, Milliken',
        seller_hook: 'Greeley\'s affordable price point and university buyer base attract motivated buyers — let competing Weld County agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Greeley\'s UNC workforce and affordable price point create consistent listing volume — RealtorFinder connects you with motivated sellers in northern Colorado.',
    },
    {
        slug: 'loveland-co',
        name: 'Loveland',
        county: 'Larimer',
        state: 'CO',
        zip: '80537',
        population: '77,000',
        median_price: '$510,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Loveland is the Gateway to Rocky Mountain National Park and one of the Front Range\'s most livable mid-sized cities — a nationally recognized sculpture and arts community with the Benson Sculpture Garden, Lake Loveland recreation, and a manufacturing and tech employment base that makes it a top alternative to Fort Collins for buyers seeking outdoor lifestyle and affordability.',
        neighborhoods: 'Downtown Loveland, Centerra, Mariana Butte, Lake Loveland area, Alford Meadows, Lakeside',
        nearby: 'Fort Collins, Windsor CO, Berthoud, Longmont, Estes Park',
        seller_hook: 'Loveland\'s arts character and Rocky Mountain gateway status attract motivated buyers — let competing Larimer County agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Loveland\'s outdoor lifestyle appeal and affordable price relative to Fort Collins generate consistent listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'colorado-springs',
        name: 'Colorado Springs',
        county: 'El Paso',
        state: 'CO',
        zip: '80903',
        population: '478,000',
        median_price: '$420,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Colorado Springs is Colorado\'s second-largest city and the military\'s premier Rocky Mountain base complex — home to Fort Carson, Peterson, Schriever, and Cheyenne Mountain Space Force Station where Pikes Peak\'s iconic backdrop, the Garden of the Gods, and a growing tech and cybersecurity sector attract buyers seeking mountain lifestyle at half the cost of Denver.',
        neighborhoods: 'Old Colorado City, Manitou Springs, Briargate, Broadmoor, Black Forest, Rockrimmon, Ivywild',
        nearby: 'Pueblo, Monument, Woodland Park, Fountain, Security',
        seller_hook: 'Colorado Springs\' massive military buyer base and growing tech sector ensure consistent buyer demand — let competing El Paso County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Colorado Springs\' military installations and Pikes Peak lifestyle create one of Colorado\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'pueblo',
        name: 'Pueblo',
        county: 'Pueblo',
        state: 'CO',
        zip: '81001',
        population: '112,000',
        median_price: '$280,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Pueblo is Colorado\'s most affordable mid-sized city and a steel town with a rich industrial heritage — home to Colorado State University-Pueblo, Pueblo Community College, and a growing outdoor recreation economy along the Arkansas River where entry-level home prices attract investors and first-time buyers from Colorado Springs and beyond.',
        neighborhoods: 'Belmont, Eastside, Bessemer, South Side, Pueblo West, University area, Downtown Historic District',
        nearby: 'Colorado Springs, Canon City, Walsenburg, La Junta, Penrose',
        seller_hook: 'Pueblo\'s rapid appreciation and growing investor interest create stronger buyer demand than ever — let competing agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Pueblo\'s entry-level price point and investor buyer demand create consistent listing opportunities — RealtorFinder connects you with motivated sellers in southern Colorado.',
    },
    {
        slug: 'broomfield',
        name: 'Broomfield',
        county: 'Broomfield',
        state: 'CO',
        zip: '80021',
        population: '70,000',
        median_price: '$580,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Broomfield is the only Colorado city that is also its own county — a strategically positioned tech suburb equidistant between Denver and Boulder on the US-36 corridor where Oracle, Ball Aerospace, and Level 3 Communications anchor a thriving tech employment base and planned Flatiron Crossing development drives retail and residential growth.',
        neighborhoods: 'Anthem, Interlocken, Broadlands, The Ponds, Broomfield Village, Northwest Broomfield',
        nearby: 'Westminster, Louisville CO, Thornton, Arvada, Superior',
        seller_hook: 'Broomfield\'s midpoint location between Denver and Boulder and Oracle-anchored employment attract buyers from both markets — let competing agents on RealtorFinder compete.',
        realtor_hook: 'Broomfield\'s tech corridor employment and dual-market access create consistent premium listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'northglenn',
        name: 'Northglenn',
        county: 'Adams',
        state: 'CO',
        zip: '80233',
        population: '39,000',
        median_price: '$450,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Northglenn is one of Denver\'s most affordable inner-ring northern suburbs — a dense, transit-accessible city adjacent to Thornton and Westminster where solid North Metro light rail access, affordable entry-level pricing, and easy I-25 commutes attract first-time buyers and working families seeking homeownership in the Denver metro without the premium zip code price.',
        neighborhoods: 'Downtown Northglenn, MLK Park area, York Street corridor, Comanche Creek, North Washington area',
        nearby: 'Thornton, Westminster, Commerce City, Denver, Brighton',
        seller_hook: 'Northglenn\'s affordability and rail access attract motivated first-time buyers — let competing Adams County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Northglenn\'s light rail connectivity and entry-level price point create consistent buyer demand — RealtorFinder connects you with motivated sellers.',
    },
];
