// cities/co.js — Colorado city data for SEO landing pages

module.exports = [
    {
        slug: 'denver',
        name: 'Denver',
        county: 'Denver',
        state: 'CO',
        zip: '80201',
        population: '715,000',
        median_price: '$549,000',
        price_trend: 'up 4%',
        avg_dom: 29,
        description: 'Denver is the gateway to the Rocky Mountains and one of America\'s most livable large cities — a sunny, active outdoor culture city where neighborhoods from RiNo\'s art galleries to Wash Park\'s Victorian bungalows and Capitol Hill\'s diverse community attract a broad base of buyers from across the country seeking Colorado lifestyle.',
        neighborhoods: 'RiNo, Washington Park, Capitol Hill, LoHi, Highlands, Congress Park, Baker, Curtis Park',
        nearby: 'Aurora, Lakewood, Westminster, Thornton, Englewood',
        seller_hook: 'Denver\'s outdoor lifestyle and diverse buyer base drive consistent demand — let competing Denver realtors on RealtorFinder fight to earn the right to represent your home.',
        realtor_hook: 'Denver\'s national desirability and diverse neighborhoods create strong listing volume across a broad price spectrum — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'colorado-springs',
        name: 'Colorado Springs',
        county: 'El Paso',
        state: 'CO',
        zip: '80901',
        population: '478,000',
        median_price: '$419,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Colorado Springs is the Pikes Peak region\'s anchor and one of the fastest-growing cities in Colorado — a military-tech hub home to Fort Carson, Peterson Space Force Base, and NORAD that creates stable employment-driven housing demand alongside a growing civilian tech sector and outdoor recreation culture.',
        neighborhoods: 'Old Colorado City, Manitou Springs border, Briargate, Wolf Ranch, Broadmoor area, Downtown Colorado Springs',
        nearby: 'Fountain, Pueblo, Monument, Castle Rock, Woodland Park',
        seller_hook: 'Colorado Springs\' military and Space Force buyer base drive consistent year-round demand — RealtorFinder puts competitive El Paso County realtors in a race to represent your home.',
        realtor_hook: 'Colorado Springs\' military installations and growing tech sector create recession-resistant buyer demand — RealtorFinder connects you with motivated sellers in El Paso County.',
    },
    {
        slug: 'aurora-co',
        name: 'Aurora',
        county: 'Arapahoe',
        state: 'CO',
        zip: '80010',
        population: '386,000',
        median_price: '$449,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Aurora is Colorado\'s third-largest city and the Denver metro\'s most diverse community — home to Buckley Space Force Base, the University of Colorado Anschutz Medical Campus, and a broad range of neighborhoods with light rail access to downtown Denver that draws buyers seeking metro access at prices below central Denver.',
        neighborhoods: 'Stapleton border, Central Aurora, Southeast Aurora, Aurora Highlands, Saddle Rock',
        nearby: 'Denver, Centennial, Englewood, Commerce City, Parker',
        seller_hook: 'Aurora\'s medical campus and Space Force presence drive consistent buyer demand — let competing Arapahoe County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Aurora\'s UCHealth campus and light rail access to Denver create diverse buyer demand — RealtorFinder connects you with motivated sellers in Colorado\'s third-largest city.',
    },
    {
        slug: 'fort-collins',
        name: 'Fort Collins',
        county: 'Larimer',
        state: 'CO',
        zip: '80521',
        population: '169,000',
        median_price: '$519,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Fort Collins is Colorado State University\'s home and one of the Front Range\'s most beloved communities — a walkable, craft-beer culture city on the Cache la Poudre River with a vibrant Old Town, top-ranked CSU, and a buyer profile that draws graduates, tech professionals, and outdoor enthusiasts to one of Colorado\'s most consistently desirable markets.',
        neighborhoods: 'Old Town, Midtown, East Fort Collins, Spring Creek, SoFoCo, Fossil Creek, Harmony',
        nearby: 'Loveland, Windsor, Greeley, Timnath, Wellington',
        seller_hook: 'Fort Collins\' CSU community and Old Town appeal drive consistent buyer loyalty — let competing Larimer County agents on RealtorFinder earn the right to sell your home.',
        realtor_hook: 'Fort Collins\' CSU buyer base and Old Town lifestyle create consistent listing demand — RealtorFinder connects you with motivated sellers in this beloved Colorado city.',
    },
    {
        slug: 'lakewood-co',
        name: 'Lakewood',
        county: 'Jefferson',
        state: 'CO',
        zip: '80226',
        population: '159,000',
        median_price: '$499,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Lakewood is the Denver metro\'s most strategically positioned suburb — a large, light-rail-connected city in Jefferson County that offers immediate access to both downtown Denver and the Rocky Mountain foothills, with diverse neighborhoods and home prices that attract buyers seeking Denver lifestyle at slightly more accessible prices.',
        neighborhoods: 'Belmar, Eiber, Green Gables, Applewood, Glennon Heights, Morse Park, Federal Heights area',
        nearby: 'Denver, Golden, Wheat Ridge, Englewood, Morrison',
        seller_hook: 'Lakewood\'s Denver access and foothills proximity drive strong buyer interest — let competing Jefferson County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Lakewood\'s light rail access and foothills adjacency create consistent buyer demand — RealtorFinder connects you with motivated sellers in Jefferson County.',
    },
    {
        slug: 'thornton',
        name: 'Thornton',
        county: 'Adams',
        state: 'CO',
        zip: '80229',
        population: '142,000',
        median_price: '$449,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Thornton is the Denver metro\'s fastest-growing suburb in Adams County — a family-oriented community with light rail extension to downtown Denver, strong new construction activity, and home prices that offer first-time buyers and families a genuine path to homeownership in the metro area without sacrificing commute practicality.',
        neighborhoods: 'Downtown Thornton, Eastlake, Todd Creek, Hunters Glen, Eastridge, Margaret W. Carpenter Park area',
        nearby: 'Northglenn, Westminster, Brighton, Commerce City, Denver',
        seller_hook: 'Thornton\'s growth and light rail access drive strong buyer demand from families and first-time buyers — RealtorFinder puts competing Adams County agents in a race to represent your home.',
        realtor_hook: 'Thornton\'s rapid growth and Denver light rail access create consistent buyer demand — RealtorFinder connects you with motivated sellers in Adams County.',
    },
    {
        slug: 'arvada',
        name: 'Arvada',
        county: 'Jefferson',
        state: 'CO',
        zip: '80002',
        population: '118,000',
        median_price: '$519,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'Arvada is one of the Denver metro\'s most complete communities — a Jefferson County suburb with a nationally recognized Olde Town arts and dining district, light rail to downtown Denver, and established family neighborhoods with mature trees and strong school districts that keep buyer demand consistently high.',
        neighborhoods: 'Olde Town Arvada, West Woods, Ralston Estates, Sierra Vista, Crown Pointe, Stenger',
        nearby: 'Westminster, Golden, Lakewood, Wheat Ridge, Denver',
        seller_hook: 'Arvada\'s Olde Town character and light rail access drive premium buyer interest — let competing Jefferson County realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Arvada\'s Olde Town dining scene and established neighborhoods create a consistent premium buyer pool — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'westminster-co',
        name: 'Westminster',
        county: 'Jefferson',
        state: 'CO',
        zip: '80030',
        population: '113,000',
        median_price: '$489,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Westminster straddles the Adams-Jefferson county line and two of the metro\'s most important employment corridors — US 36 to Boulder and I-25 to downtown Denver — making it one of the most commuter-practical suburbs in the Front Range and a consistent target for buyers who need access to both Boulder and Denver employment centers.',
        neighborhoods: 'Bradburn Village, Legacy Ridge, Shaw Heights, Countryside, Hyland Hills, Ranch District',
        nearby: 'Broomfield, Thornton, Arvada, Northglenn, Boulder corridor',
        seller_hook: 'Westminster\'s dual-corridor access to Boulder and Denver creates a diverse buyer pool — let competing Jefferson County agents on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Westminster\'s US 36 and I-25 access creates buyer demand from both Boulder and Denver employment markets — RealtorFinder connects you with motivated sellers.',
    },
];
