// cities/ct-extra.js — Additional Connecticut city data for SEO landing pages

module.exports = [
    {
        slug: 'waterbury',
        name: 'Waterbury',
        county: 'New Haven / Litchfield',
        state: 'CT',
        zip: '06702',
        population: '114,000',
        median_price: '$245,000',
        price_trend: 'up 8%',
        avg_dom: 16,
        description: 'Waterbury is the Brass City and Connecticut\'s fifth-largest city — a historic industrial center in the Naugatuck Valley where UConn Waterbury, Sacred Heart University Graduate School, and a massive housing value gap compared to Fairfield County create intense investor and first-time buyer activity, with triple-deckers and Victorians offering cap rates rarely found in Connecticut and rapid appreciation driven by New York metro spillover.',
        neighborhoods: 'Bunker Hill, Bucks Hill, Town Plot, East End, Naugatuck',
        nearby: 'Naugatuck, Wolcott, Prospect, Cheshire, Middlebury',
        seller_hook: 'Waterbury\'s rapid appreciation and NY commuter discovery are creating exceptional seller conditions — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Waterbury\'s value-gap market and investor demand generate some of Connecticut\'s fastest-moving listings — find sellers through RealtorFinder.',
    },
    {
        slug: 'meriden',
        name: 'Meriden',
        county: 'New Haven',
        state: 'CT',
        zip: '06450',
        population: '60,000',
        median_price: '$265,000',
        price_trend: 'up 8%',
        avg_dom: 15,
        description: 'Meriden is the Silver City of Connecticut and one of the state\'s most rapidly appreciating mid-size markets — a Quinnipiac River community positioned on I-91 between Hartford and New Haven, where a Silver Peaks Park revitalization, direct Metro-North access to Grand Central, and some of the Hartford-New Haven corridor\'s most affordable multi-family homes attract investors and commuters priced out of both state capitals.',
        neighborhoods: 'West Meriden, East Meriden, Hanover, Meriden Center, Broad Street',
        nearby: 'Wallingford, Berlin, Southington, Cheshire, Middlefield',
        seller_hook: 'Meriden\'s I-91 corridor and Metro-North access create fast-moving buyer competition — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Meriden\'s Silver City revival and commuter demand generate active listing conditions between Hartford and New Haven — find sellers through RealtorFinder.',
    },
    {
        slug: 'middletown-ct',
        name: 'Middletown',
        county: 'Middlesex',
        state: 'CT',
        zip: '06457',
        population: '47,000',
        median_price: '$295,000',
        price_trend: 'up 7%',
        avg_dom: 18,
        description: 'Middletown is Connecticut\'s geographic center and home to Wesleyan University — a Connecticut River city where Wesleyan\'s liberal arts prestige, Middlesex Hospital, and a revitalized Main Street of independent restaurants and galleries create a progressive college-town market with strong rental demand and appreciation driven by Wesleyan alumni and young professionals who never want to leave.',
        neighborhoods: 'Wesleyan Hills, Newfield, South Farms, Maromas, Portland',
        nearby: 'Portland, Cromwell, East Hampton, Durham, Haddam',
        seller_hook: 'Middletown\'s Wesleyan prestige and Connecticut River location create consistent buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Middletown\'s university market and geographic Connecticut centrality generate steady listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'naugatuck',
        name: 'Naugatuck',
        county: 'New Haven',
        state: 'CT',
        zip: '06770',
        population: '32,000',
        median_price: '$270,000',
        price_trend: 'up 8%',
        avg_dom: 16,
        description: 'Naugatuck is the Naugatuck Valley\'s working-class heart — a rubber manufacturing legacy town on the Naugatuck River where affordable single-family homes, proximity to Waterbury and I-84, and some of New Haven County\'s lowest per-square-foot prices attract first-time buyers, investors, and families seeking Connecticut homeownership at a price point that still feels like a genuine bargain compared to Fairfield County.',
        neighborhoods: 'Rubber City, Hop Brook, Cross Street, Springdale, Salem Road',
        nearby: 'Waterbury, Ansonia, Derby, Beacon Falls, Seymour',
        seller_hook: 'Naugatuck\'s Naugatuck Valley affordability and I-84 access attract motivated buyers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Naugatuck\'s value-market positioning and first-time buyer demand generate consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'shelton',
        name: 'Shelton',
        county: 'Fairfield',
        state: 'CT',
        zip: '06484',
        population: '42,000',
        median_price: '$395,000',
        price_trend: 'up 7%',
        avg_dom: 17,
        description: 'Shelton is Fairfield County\'s fastest-growing city and one of western Connecticut\'s most sought-after family destinations — a Housatonic River community where Shelton\'s top-rated public schools, significant corporate presence, and home prices 30–40% below comparable Fairfield County shore towns create intense buyer demand from Greenwich and Westport workers seeking larger homes and better school budgets without sacrificing the Fairfield County lifestyle.',
        neighborhoods: 'Long Hill, Huntington, Shelton Center, White Hills, Seymour',
        nearby: 'Derby, Ansonia, Oxford, Monroe, Trumbull',
        seller_hook: 'Shelton\'s Fairfield County value and top schools create competitive listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Shelton\'s corporate corridor and family buyer demand generate fast-moving listing conditions in western Connecticut — find sellers through RealtorFinder.',
    },
    {
        slug: 'torrington',
        name: 'Torrington',
        county: 'Litchfield',
        state: 'CT',
        zip: '06790',
        population: '35,000',
        median_price: '$230,000',
        price_trend: 'up 7%',
        avg_dom: 18,
        description: 'Torrington is the Litchfield Hills gateway and northwestern Connecticut\'s largest city — a Naugatuck River mill city where Warner Theatre arts revitalization, Northwestern Connecticut Community College, and some of Connecticut\'s most affordable home prices are attracting remote workers, artists, and families who want Litchfield County\'s scenic weekend beauty — covered bridges, state forests, and ski resorts — as their backyard.',
        neighborhoods: 'Burrville, East Litchfield, Torrington Center, Goshen Road, New Hartford',
        nearby: 'New Hartford, Litchfield, Winsted, Harwinton, Burlington',
        seller_hook: 'Torrington\'s Litchfield Hills gateway and affordable prices attract remote workers and families — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Torrington\'s remote worker discovery and Northwestern CT appeal create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'ansonia',
        name: 'Ansonia',
        county: 'New Haven',
        state: 'CT',
        zip: '06401',
        population: '18,000',
        median_price: '$255,000',
        price_trend: 'up 8%',
        avg_dom: 15,
        description: 'Ansonia is the Naugatuck Valley\'s Copper City — a small Housatonic River mill town adjacent to Derby where some of Connecticut\'s most affordable historic multi-family homes, proximity to I-95 and the Milford train station, and rapid appreciation driven by New Haven area buyers create genuine investment opportunities that remind regional investors of where Waterbury was five years ago.',
        neighborhoods: 'Riverside, Hilltop, Ansonia Center, Birmingham, Derby border',
        nearby: 'Derby, Shelton, Seymour, Naugatuck, Beacon Falls',
        seller_hook: 'Ansonia\'s value-gap market and Naugatuck Valley appreciation create fast-moving listing conditions — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Ansonia\'s investment-grade pricing and New Haven spillover generate active listing conditions — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'southington',
        name: 'Southington',
        county: 'Hartford',
        state: 'CT',
        zip: '06489',
        population: '44,000',
        median_price: '$330,000',
        price_trend: 'up 7%',
        avg_dom: 17,
        description: 'Southington is Hartford County\'s most family-friendly suburb and the Apple Valley of Connecticut — a community on I-84 between Hartford and Waterbury where Southington\'s top-ranked public schools, strong Apple Harvest Festival community identity, and prices well below West Hartford and Glastonbury attract families and corporate transferees seeking the Hartford metro\'s best school-to-value ratio.',
        neighborhoods: 'Plantsville, Marion, Milldale, Wolcott border, Cheshire border',
        nearby: 'Cheshire, Wolcott, Meriden, Berlin, Bristol',
        seller_hook: 'Southington\'s Apple Valley schools and I-84 access create consistent family buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Southington\'s Hartford County school premium and suburban appeal generate active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'east-hartford',
        name: 'East Hartford',
        county: 'Hartford',
        state: 'CT',
        zip: '06108',
        population: '51,000',
        median_price: '$255,000',
        price_trend: 'up 8%',
        avg_dom: 15,
        description: 'East Hartford is Connecticut\'s aerospace capital and one of the state\'s most rapidly appreciating markets — a Pratt & Whitney heritage city across the Connecticut River from Hartford where a massive workforce of jet engine engineers, a Silver Lane retail corridor, and some of the Hartford metro\'s most affordable homes create brisk activity from first-time buyers, aerospace workers, and investors discovering the value gap.',
        neighborhoods: 'Burnside, Forbes, Mayberry Village, Charter Oak, Hockanum',
        nearby: 'Hartford, Manchester, Glastonbury, South Windsor, Bolton',
        seller_hook: 'East Hartford\'s Pratt & Whitney workforce and affordable prices create fast-moving buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'East Hartford\'s aerospace employment and value market generate consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'wallingford',
        name: 'Wallingford',
        county: 'New Haven',
        state: 'CT',
        zip: '06492',
        population: '45,000',
        median_price: '$345,000',
        price_trend: 'up 7%',
        avg_dom: 16,
        description: 'Wallingford is Choate Rosemary Hall\'s hometown and one of the New Haven-Hartford corridor\'s most well-rounded communities — a Quinnipiac River town where the prestigious prep school adds educational cachet, a strong manufacturing and service economy provides diverse employment, and direct Metro-North New Haven Line rail service to Grand Central makes it a genuine commuter alternative to pricier shoreline and Fairfield County towns.',
        neighborhoods: 'Wallingford Center, Yalesville, Northford, Hanover, Tyler Mill',
        nearby: 'Meriden, North Haven, Cheshire, Durham, Middlefield',
        seller_hook: 'Wallingford\'s Choate prestige and Metro-North access create strong buyer demand along the I-91 corridor — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Wallingford\'s prep school cachet and commuter rail appeal generate consistent listing activity — find sellers through RealtorFinder.',
    },
];
