module.exports = [
    // ── Fairfield County ──────────────────────────────────────────────────────
    {
        slug: 'greenwich',
        name: 'Greenwich',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06830',
        population: '63,000',
        median_price: '$1,450,000',
        price_trend: 'up 10%',
        avg_dom: 30,
        description: 'Greenwich is Connecticut\'s premier luxury enclave, blending Gold Coast estates with a vibrant downtown and direct Metro-North access to Midtown Manhattan in under an hour. The market consistently attracts high-net-worth buyers seeking prestigious addresses, top-ranked schools, and unmatched amenities.',
        neighborhoods: 'Backcountry, Mid-Country, Cos Cob, Old Greenwich, Riverside, Belle Haven, Greenwich Avenue',
        nearby: 'Stamford, Darien, Port Chester NY, Rye NY',
        seller_hook: 'NYC buyers are flooding the market seeking Greenwich\'s luxury estates and sub-60-minute commute — median prices are up 10% and serious buyers act fast. List now to capture peak demand from Manhattan executives ready to move.',
        realtor_hook: 'Greenwich generates some of the highest per-transaction commissions in New England, with a deep pool of relocating finance and tech professionals actively searching. Agents who specialize here build seven-figure book-of-business quickly.',
    },
    {
        slug: 'stamford',
        name: 'Stamford',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06901',
        population: '136,000',
        median_price: '$649,000',
        price_trend: 'up 9%',
        avg_dom: 22,
        description: 'Stamford is Fairfield County\'s urban hub, home to major corporate headquarters and a booming downtown condo scene alongside quiet residential neighborhoods. Its express Metro-North service and vibrant restaurant corridor make it the entry point of choice for NYC transplants.',
        neighborhoods: 'Downtown Stamford, Shippan, North Stamford, Glenbrook, Springdale, Newfield',
        nearby: 'Greenwich, Darien, Norwalk, Port Chester NY',
        seller_hook: 'Stamford\'s corporate relocation pipeline and sub-45-minute train to Grand Central keeps buyer demand fierce year-round, with homes averaging only 22 days on market. Sellers are routinely seeing multiple offers above asking price.',
        realtor_hook: 'Stamford\'s diverse price range — from starter condos to North Stamford estates — means consistent transaction volume across every market segment. The city\'s ongoing corporate expansions create a steady stream of relocation clients.',
    },
    {
        slug: 'westport',
        name: 'Westport',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06880',
        population: '28,000',
        median_price: '$1,299,000',
        price_trend: 'up 8%',
        avg_dom: 32,
        description: 'Westport pairs celebrity cachet with charming New England character, boasting award-winning schools, the Saugatuck River waterfront, and Compo Beach. Its artistic community and upscale Main Street draw discerning buyers who want luxury suburban living within commuting range of NYC.',
        neighborhoods: 'Saugatuck, Compo Beach, Downtown Westport, Greens Farms, Long Lots',
        nearby: 'Fairfield, Weston, Norwalk, Wilton',
        seller_hook: 'Westport\'s national reputation for luxury living and top schools means your home attracts buyers from across the country, not just the region — and prices are up 8% with strong momentum. Inventory remains historically tight, putting sellers firmly in control.',
        realtor_hook: 'Westport\'s blend of media personalities, finance executives, and creative professionals creates a unique, high-value clientele that relies on trusted local agents. Referral networks here are exceptionally powerful and lead to repeat luxury business.',
    },
    {
        slug: 'fairfield',
        name: 'Fairfield',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06824',
        population: '62,000',
        median_price: '$779,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Fairfield strikes the ideal balance between suburban charm and coastal access, with miles of Long Island Sound beaches and a walkable downtown anchored by top-rated schools. The town draws families priced out of Greenwich or Westport who still demand quality and Metro-North connectivity.',
        neighborhoods: 'Fairfield Beach, Southport, Greenfield Hill, Stratfield, Downtown Fairfield',
        nearby: 'Westport, Bridgeport, Trumbull, Easton',
        seller_hook: 'Fairfield\'s combination of beach access, excellent schools, and relative affordability compared to neighboring towns creates relentless buyer demand — homes sell in just 24 days on average. Sellers benefit from a large, motivated NYC-commuter buyer pool.',
        realtor_hook: 'Fairfield\'s wide price spectrum from beach cottages to Greenfield Hill estates lets agents build a diverse, high-volume portfolio. The consistent influx of NYC families creates year-round listing and buyer opportunities.',
    },
    {
        slug: 'darien',
        name: 'Darien',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06820',
        population: '21,000',
        median_price: '$1,399,000',
        price_trend: 'up 7%',
        avg_dom: 33,
        description: 'Darien is one of Connecticut\'s most coveted addresses, renowned for its excellent public schools, close-knit community, and easy access to both the beach and New York City via Metro-North. Its intimate scale and prestigious reputation keep demand persistently ahead of supply.',
        neighborhoods: 'Tokeneke, Noroton, Noroton Heights, Pear Tree Point Beach area',
        nearby: 'New Canaan, Stamford, Norwalk, Greenwich',
        seller_hook: 'Darien\'s national ranking among the best places to raise a family drives a constant stream of high-earning buyers competing for a very limited number of listings. With prices up 7% and inventory near historic lows, sellers hold exceptional negotiating leverage.',
        realtor_hook: 'Darien\'s affluent, well-connected community is built on trust and referrals — agents who establish themselves here enjoy decades of repeat and word-of-mouth business at the luxury price point.',
    },
    {
        slug: 'wilton',
        name: 'Wilton',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06897',
        population: '18,500',
        median_price: '$749,000',
        price_trend: 'up 6%',
        avg_dom: 31,
        description: 'Wilton is a wooded, upscale bedroom community that offers spacious properties, acclaimed schools, and a serene New England atmosphere at a relative value compared to its coastal neighbors. It appeals strongly to families seeking privacy and land without sacrificing quality or commuter convenience.',
        neighborhoods: 'Wilton Center, Cannondale, Georgetown, Wolfpit',
        nearby: 'Westport, Norwalk, Ridgefield, New Canaan',
        seller_hook: 'Buyers priced out of coastal Fairfield County towns are actively targeting Wilton for its value, privacy, and school quality — keeping the market competitive with steady upward price pressure. Now is the time to leverage rising demand for your spacious Wilton property.',
        realtor_hook: 'Wilton attracts move-up buyers from Norwalk and Stamford as well as NYC relocators, creating a dual market of both buyers and sellers for well-connected agents to serve. Its wooded luxury feel commands strong prices without the extreme inventory pressure of coastal towns.',
    },
    {
        slug: 'ridgefield',
        name: 'Ridgefield',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06877',
        population: '25,000',
        median_price: '$649,000',
        price_trend: 'up 7%',
        avg_dom: 29,
        description: 'Ridgefield is a picturesque New England town with a charming Main Street, thriving arts scene anchored by the Aldrich Contemporary Art Museum, and excellent schools that rival those of pricier Fairfield County towns. Its slightly inland location offers more square footage per dollar while still drawing serious NYC commuters.',
        neighborhoods: 'Ridgefield Center, Branchville, Lounsbury Road, Silver Spring',
        nearby: 'Wilton, Danbury, Norwalk, Bethel',
        seller_hook: 'Ridgefield\'s reputation for village charm and outstanding schools is attracting buyers from across Fairfield County and directly from New York, pushing prices up 7% in the last year. Sellers can expect motivated buyers who have done their research and are ready to act.',
        realtor_hook: 'Ridgefield\'s growing arts-and-culture profile is expanding its buyer demographic well beyond traditional commuters, giving savvy agents a broadening market to work. Competitive days-on-market means quick closings and healthy transaction volume.',
    },
    {
        slug: 'norwalk',
        name: 'Norwalk',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06850',
        population: '92,000',
        median_price: '$569,000',
        price_trend: 'up 8%',
        avg_dom: 21,
        description: 'Norwalk has transformed into one of Fairfield County\'s most dynamic markets, led by the revitalized SoNo arts and dining district, waterfront redevelopment, and strong Metro-North links to NYC. It offers the region\'s best value for buyers seeking urban energy with suburban roots.',
        neighborhoods: 'South Norwalk (SoNo), Rowayton, East Norwalk, West Norwalk, Cranbury, Silvermine',
        nearby: 'Westport, Darien, Stamford, Wilton',
        seller_hook: 'Norwalk\'s surging SoNo scene and waterfront development have created explosive buyer demand, with homes selling in just 21 days and prices up 8% year over year. Sellers in every neighborhood — from Rowayton waterfront to Silvermine — are seeing strong returns.',
        realtor_hook: 'Norwalk\'s rapid appreciation and high transaction velocity make it one of Fairfield County\'s most productive markets for building commission income. The mix of condos, single-families, and luxury waterfront properties supports a full-spectrum client roster.',
    },
    {
        slug: 'danbury',
        name: 'Danbury',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06810',
        population: '86,000',
        median_price: '$369,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'Danbury is Fairfield County\'s most affordable entry point, offering strong price appreciation, a diverse and growing population, and convenient I-84 access to both Hartford and New York. Its revitalized downtown and expanding amenity base are drawing first-time buyers and investors in growing numbers.',
        neighborhoods: 'Downtown Danbury, Danbury Hat City, Shelter Rock, Long Ridge, Stadley Rough',
        nearby: 'Ridgefield, Bethel, Newtown, Brookfield',
        seller_hook: 'Danbury is experiencing the strongest appreciation in Fairfield County at 10%, fueled by buyers seeking affordability without sacrificing access to the region\'s economic engine. With homes moving in 22 days, sellers are cashing out at record prices.',
        realtor_hook: 'Danbury\'s affordability drives exceptional transaction volume, making it one of the busiest markets in the county for agents focused on first-time buyers and investors. Rising prices and strong rental demand also support a growing investment-property client base.',
    },
    {
        slug: 'new-canaan',
        name: 'New Canaan',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06840',
        population: '20,500',
        median_price: '$1,549,000',
        price_trend: 'up 7%',
        avg_dom: 35,
        description: 'New Canaan is Fairfield County\'s architectural showpiece, celebrated for its mid-century modern Glass House legacy, walkable village center, and some of the state\'s finest public schools. It commands the county\'s highest median prices and attracts a discerning, design-conscious buyer pool.',
        neighborhoods: 'New Canaan Center, Silvermine, Smith Ridge, Oenoke Ridge',
        nearby: 'Darien, Stamford, Wilton, Norwalk',
        seller_hook: 'New Canaan\'s architectural prestige and unrivaled school reputation create a buyer pool that actively seeks out listings regardless of price — and with the median at $1.55M and climbing, sellers are maximizing generational equity. Limited inventory keeps your home at the center of attention.',
        realtor_hook: 'New Canaan\'s affluent, architecturally sophisticated clientele values agents with deep local knowledge and a refined marketing approach. Established agents here benefit from some of the highest average sale prices in Connecticut and a loyal referral network.',
    },
    {
        slug: 'weston',
        name: 'Weston',
        county: 'Fairfield County',
        state: 'CT',
        zip: '06883',
        population: '10,500',
        median_price: '$849,000',
        price_trend: 'up 6%',
        avg_dom: 33,
        description: 'Weston is a bucolic, low-density town prized for its expansive lots, excellent schools, and protected open spaces including the Aspetuck Land Trust. Buyers come for privacy and nature without sacrificing quality, making it one of Fairfield County\'s best-kept secrets.',
        neighborhoods: 'Weston Center, Georgetown, Devil\'s Den area, Norfield',
        nearby: 'Westport, Wilton, Redding, Easton',
        seller_hook: 'Weston\'s combination of privacy, acreage, and top-tier schools is drawing significant buyer interest from NYC professionals seeking space to spread out — prices are up 6% with limited listings to absorb demand. Weston sellers benefit from a motivated, qualified buyer pool with few alternatives.',
        realtor_hook: 'Weston\'s intimate market rewards agents who take the time to build genuine community relationships and understand the land and property nuances that drive value here. Luxury listings on private acreage create high per-transaction earnings in a low-competition environment.',
    },

    // ── Hartford County ───────────────────────────────────────────────────────
    {
        slug: 'west-hartford',
        name: 'West Hartford',
        county: 'Hartford County',
        state: 'CT',
        zip: '06107',
        population: '64,000',
        median_price: '$339,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'West Hartford is consistently ranked among Connecticut\'s best places to live, offering a vibrant town center packed with restaurants and boutiques, excellent public schools, and a diverse, walkable community. Its strong fundamentals and relative affordability make it Hartford County\'s most competitive market.',
        neighborhoods: 'West Hartford Center, Elmwood, Bishops Corner, Buena Vista, Morley',
        nearby: 'Hartford, Bloomfield, Farmington, Avon',
        seller_hook: 'West Hartford\'s nationally recognized livability scores and top schools drive intense buyer competition — homes sell in just 18 days on average, often with multiple offers above list price. Sellers routinely walk away with significantly more than asking in this supply-constrained market.',
        realtor_hook: 'West Hartford\'s consistent demand, strong school reputation, and active town center create one of Hartford County\'s highest transaction volumes, giving agents a reliable pipeline of motivated buyers and sellers year-round.',
    },
    {
        slug: 'hartford',
        name: 'Hartford',
        county: 'Hartford County',
        state: 'CT',
        zip: '06101',
        population: '121,000',
        median_price: '$175,000',
        price_trend: 'up 15%',
        avg_dom: 26,
        description: 'Hartford is Connecticut\'s capital city, undergoing a significant revitalization driven by healthcare and insurance industry anchors, a growing arts scene, and aggressive investment in historic neighborhoods. Its entry-level price point and 15% annual appreciation make it one of New England\'s most compelling investor and first-time buyer markets.',
        neighborhoods: 'Asylum Hill, Blue Hills, Clay Arsenal, Frog Hollow, Behind the Rocks, West End',
        nearby: 'West Hartford, East Hartford, Bloomfield, Windsor',
        seller_hook: 'Hartford\'s 15% year-over-year appreciation is the strongest in the state, and demand from investors, first-time buyers, and urban pioneers is accelerating. Sellers who act now are capturing gains that were unimaginable just a few years ago.',
        realtor_hook: 'Hartford\'s rapid revitalization and investment influx create exceptional lead-generation opportunities for agents who know the neighborhoods — from historic brownstones to multi-family investment properties. The city\'s price trajectory means clients who buy today will be calling you to list in five years.',
    },
    {
        slug: 'new-britain',
        name: 'New Britain',
        county: 'Hartford County',
        state: 'CT',
        zip: '06051',
        population: '73,000',
        median_price: '$195,000',
        price_trend: 'up 13%',
        avg_dom: 27,
        description: 'New Britain, once known as the Hardware City of the World, is experiencing a housing renaissance fueled by CCSU enrollment, rising Hartford-area prices pushing buyers outward, and genuine community investment. Its affordability and strong appreciation make it a standout opportunity for value-focused buyers.',
        neighborhoods: 'Downtown New Britain, Corbin Heights, East Side, West Side',
        nearby: 'Hartford, Bristol, Newington, Berlin',
        seller_hook: 'New Britain\'s 13% appreciation is among the highest in Hartford County, as buyers priced out of West Hartford look here for value and find a revitalized community with real momentum. Sellers are capitalizing on a window of strong demand and rising prices.',
        realtor_hook: 'New Britain\'s affordability and rapid appreciation create high transaction velocity and an ever-growing base of motivated first-time buyers eager to act. Agents who plant their flag here early are positioning themselves at the center of a market that is only going to get more competitive.',
    },
    {
        slug: 'bristol',
        name: 'Bristol',
        county: 'Hartford County',
        state: 'CT',
        zip: '06010',
        population: '60,000',
        median_price: '$259,000',
        price_trend: 'up 11%',
        avg_dom: 23,
        description: 'Bristol is a family-friendly community best known as the hometown of ESPN, offering affordable housing, solid schools, and a historic downtown undergoing steady improvement. Its central Connecticut location and 11% price growth signal a market gaining serious momentum.',
        neighborhoods: 'Downtown Bristol, West Bristol, Forestville, Chippens Hill',
        nearby: 'New Britain, Southington, Waterbury, Farmington',
        seller_hook: 'Bristol\'s 11% appreciation reflects growing recognition that it offers excellent value in a tight central Connecticut market — homes are moving in 23 days as buyers prioritize affordability with quality of life. Sellers are achieving prices well above what the market offered just two years ago.',
        realtor_hook: 'Bristol\'s growing appeal to value-conscious families and investors creates consistent demand across price points, giving agents a broad and active client base. Its central location and proximity to major employers support a diverse buyer demographic.',
    },
    {
        slug: 'manchester',
        name: 'Manchester',
        county: 'Hartford County',
        state: 'CT',
        zip: '06040',
        population: '59,000',
        median_price: '$279,000',
        price_trend: 'up 10%',
        avg_dom: 21,
        description: 'Manchester is a vibrant Hartford suburb offering exceptional affordability, a thriving restaurant and retail scene on Main Street, and easy access to I-84 and Route 44. Its diverse community and strong school options attract a wide range of buyers seeking value in the greater Hartford market.',
        neighborhoods: 'Manchester Center, Buckland, Eighth Utilities District, South Manchester',
        nearby: 'Hartford, Glastonbury, East Hartford, Bolton',
        seller_hook: 'Manchester\'s 10% appreciation and 21-day average days on market reflect a buyer pool that is energized and ready — homes are selling fast, often with competing offers. Sellers in Manchester are enjoying a strong market where quality listings rarely sit.',
        realtor_hook: 'Manchester\'s high transaction volume, diverse price range, and strong rental market create consistent income opportunities for agents across buyer, seller, and investor transactions. Its proximity to Hartford and I-84 keeps demand steady throughout the year.',
    },
    {
        slug: 'glastonbury',
        name: 'Glastonbury',
        county: 'Hartford County',
        state: 'CT',
        zip: '06033',
        population: '35,000',
        median_price: '$369,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Glastonbury is Hartford County\'s premier suburb for families seeking top-ranked schools, spacious properties along the Connecticut River, and a charming town center with Apple orchards and farm stands. Its consistent quality and strong school system keep buyer demand perennially ahead of supply.',
        neighborhoods: 'Glastonbury Center, South Glastonbury, Eastbury, Neipsic',
        nearby: 'Hartford, Manchester, East Hartford, Portland',
        seller_hook: 'Glastonbury\'s reputation as one of Connecticut\'s best school districts drives a relentless wave of family buyers who specifically target this town — and with only 20 days on market, sellers face no shortage of motivated offers. Now is an ideal moment to maximize your return in this consistently strong market.',
        realtor_hook: 'Glastonbury\'s stable, family-focused buyer demographic creates predictable, year-round demand that agents can count on for consistent volume. Top school rankings and scenic Connecticut River settings make listings easy to present and market effectively.',
    },
    {
        slug: 'simsbury',
        name: 'Simsbury',
        county: 'Hartford County',
        state: 'CT',
        zip: '06070',
        population: '24,000',
        median_price: '$419,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Simsbury is a quintessential Connecticut River Valley town, celebrated for its scenic Farmington River corridor, well-regarded public schools, and a community that has consistently appeared on national Best Small Towns lists. It offers a higher quality of life per dollar than many Fairfield County alternatives.',
        neighborhoods: 'Simsbury Center, Tariffville, Weatogue, Avon border area',
        nearby: 'Avon, West Hartford, Canton, Granby',
        seller_hook: 'Simsbury\'s national recognition and scarce inventory have created a market where qualified buyers are actively watching for new listings and prepared to move quickly — giving sellers both strong prices and short marketing periods. Capitalize on 7% appreciation in one of Hartford County\'s most beloved communities.',
        realtor_hook: 'Simsbury\'s affluent, civic-minded community values agents who are genuinely embedded in local life, creating referral relationships that sustain long careers. Its scenic setting and strong school profile generate consistent out-of-state relocation inquiries.',
    },
    {
        slug: 'enfield',
        name: 'Enfield',
        county: 'Hartford County',
        state: 'CT',
        zip: '06082',
        population: '44,000',
        median_price: '$279,000',
        price_trend: 'up 10%',
        avg_dom: 21,
        description: 'Enfield is a growing north Hartford suburb positioned along the Connecticut River, offering affordable homes, improving schools, and easy access to both Springfield MA and Hartford via I-91. Its 10% appreciation reflects buyers discovering genuine value in a town with solid fundamentals.',
        neighborhoods: 'Enfield Center, Thompsonville, Hazardville, Scitico',
        nearby: 'Windsor Locks, Suffield, East Windsor, Springfield MA',
        seller_hook: 'Enfield\'s 10% price growth signals rising buyer urgency as more people discover what locals have long known — great value, good neighbors, and easy Connecticut River living. Sellers are moving homes quickly and walking away with more equity than ever before.',
        realtor_hook: 'Enfield\'s affordability and proximity to the Massachusetts border create a broad buyer catchment that includes Springfield-area buyers looking south and Hartford-area buyers looking north. High transaction velocity and consistent demand make it a productive market for agents building volume.',
    },

    // ── New Haven County ──────────────────────────────────────────────────────
    {
        slug: 'new-haven',
        name: 'New Haven',
        county: 'New Haven County',
        state: 'CT',
        zip: '06510',
        population: '134,000',
        median_price: '$269,000',
        price_trend: 'up 13%',
        avg_dom: 19,
        description: 'New Haven is a world-class city anchored by Yale University, a thriving culinary scene, and nationally recognized arts institutions, offering exceptional urban living at a fraction of Boston or New York prices. Its 13% appreciation and 19-day average on market reflect a market firing on all cylinders.',
        neighborhoods: 'East Rock, Westville, Wooster Square, Fair Haven, Edgewood, Dixwell',
        nearby: 'West Haven, Hamden, Orange, Milford',
        seller_hook: 'New Haven\'s Yale-anchored economy and booming restaurant and arts scene are attracting a new generation of buyers who see tremendous long-term value — and 13% appreciation proves the market agrees. Sellers are achieving prices that reflect a city finally getting the national recognition it deserves.',
        realtor_hook: 'New Haven\'s diverse buyer pool — from Yale affiliates and hospital professionals to first-time buyers and investors — gives agents access to multiple market segments simultaneously. The city\'s ongoing renaissance means the lead pipeline here will only widen over time.',
    },
    {
        slug: 'guilford',
        name: 'Guilford',
        county: 'New Haven County',
        state: 'CT',
        zip: '06437',
        population: '22,000',
        median_price: '$449,000',
        price_trend: 'up 8%',
        avg_dom: 23,
        description: 'Guilford is a historic shoreline gem with a scenic town green, beloved beaches along Long Island Sound, and a quiet residential character that has attracted discerning buyers for generations. It offers the Connecticut Shore lifestyle at a value that is increasingly hard to find.',
        neighborhoods: 'Guilford Green, Jacob\'s Beach, Sachem Head, Mulberry Point',
        nearby: 'Madison, Branford, New Haven, Clinton',
        seller_hook: 'Guilford\'s combination of historic charm, Sound beaches, and scarce inventory is pushing buyer competition higher — prices are up 8% as demand from shore-seeking buyers far outpaces available listings. Sellers in Guilford are well-positioned to capitalize on one of Connecticut\'s most beloved coastal markets.',
        realtor_hook: 'Guilford\'s shore lifestyle appeal draws buyers from across southern New England and New York, giving local agents access to a large, geographically diverse prospect pool. Listings here market themselves to anyone who has ever dreamed of Connecticut shoreline living.',
    },
    {
        slug: 'madison',
        name: 'Madison',
        county: 'New Haven County',
        state: 'CT',
        zip: '06443',
        population: '18,500',
        median_price: '$519,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Madison is one of Connecticut\'s most picturesque shoreline towns, known for Hammonasset Beach State Park, excellent schools, and a quintessential New England Main Street that draws both full-time residents and seasonal buyers. It consistently ranks among Connecticut\'s top communities for quality of life.',
        neighborhoods: 'Madison Center, East Madison, Rockland, West Wharf Beach',
        nearby: 'Guilford, Clinton, Killingworth, North Madison',
        seller_hook: 'Madison\'s rare combination of beach access, top schools, and small-town charm creates a buyer pool that actively seeks out any new listing — homes here represent a lifestyle that is nearly impossible to replicate at any price. With inventory extremely limited and prices up 7%, now is the moment to sell.',
        realtor_hook: 'Madison\'s appeal to both primary residence buyers and second-home seekers from Hartford and New York gives agents a perpetual dual market to work. Shoreline prestige and lifestyle-driven buyers make for enthusiastic clients and memorable transactions.',
    },
    {
        slug: 'milford',
        name: 'Milford',
        county: 'New Haven County',
        state: 'CT',
        zip: '06460',
        population: '54,000',
        median_price: '$389,000',
        price_trend: 'up 9%',
        avg_dom: 21,
        description: 'Milford offers seventeen miles of Long Island Sound coastline, a charming colonial downtown green, and solid Metro-North service to New York — all at a price point that offers genuine value compared to neighboring shore towns. Its beach neighborhoods and family-friendly atmosphere are driving 9% annual appreciation.',
        neighborhoods: 'Downtown Milford, Devon, Gulf Beach, Woodmont, Walnut Beach',
        nearby: 'Stratford, Orange, Shelton, West Haven',
        seller_hook: 'Milford\'s 17 miles of coastline and Metro-North access are drawing NYC buyers in significant numbers, pushing prices up 9% and compressing days on market to just 21. Sellers with beach proximity or water views are especially well-positioned to command premium prices.',
        realtor_hook: 'Milford\'s diverse offering — from beachfront cottages to suburban family homes to downtown condos — gives agents a broad inventory base and diverse client types. The town\'s strong Metro-North connection means NYC buyer leads are always in the funnel.',
    },

    // ── New London / Shoreline ────────────────────────────────────────────────
    {
        slug: 'old-lyme',
        name: 'Old Lyme',
        county: 'New London County',
        state: 'CT',
        zip: '06371',
        population: '7,500',
        median_price: '$479,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Old Lyme is a celebrated Connecticut River and shoreline community with a deep artistic heritage — home of the Lyme Art Colony — featuring stunning Sound beaches and a historic district of exceptional character. Its intimate scale and natural beauty attract buyers seeking a genuine escape.',
        neighborhoods: 'Lyme Street Historic District, Sound View, Old Lyme Shores, Black Hall',
        nearby: 'Lyme, East Haddam, Old Saybrook, East Lyme',
        seller_hook: 'Old Lyme\'s artistic prestige, Sound beaches, and Connecticut River setting create a buyer demand that transcends the local market, drawing purchasers from Boston, Hartford, and New York seeking a true coastal retreat. With prices up 7% and inventory scarce, sellers can command premium prices from highly motivated buyers.',
        realtor_hook: 'Old Lyme\'s cultural prestige and shore lifestyle generate inquiries from a geographically broad buyer pool who are serious, pre-qualified, and motivated by a specific vision of the good life. Agents here become lifestyle curators, which builds deep client loyalty and referral business.',
    },
    {
        slug: 'mystic',
        name: 'Mystic',
        county: 'New London County',
        state: 'CT',
        zip: '06355',
        population: '4,200',
        median_price: '$449,000',
        price_trend: 'up 8%',
        avg_dom: 26,
        description: 'Mystic is Connecticut\'s most recognizable maritime village, home to the Mystic Seaport Museum, world-class seafood restaurants, and a bascule drawbridge that defines New England charm. The market attracts buyers from across the country who want both a primary residence and a piece of genuine American maritime history.',
        neighborhoods: 'Mystic Seaport area, Noank, West Mystic, Stonington Borough',
        nearby: 'Groton, Stonington, North Stonington, Westerly RI',
        seller_hook: 'Mystic\'s national brand recognition as a destination town means your listing markets itself to buyers across the country — and 8% appreciation confirms that demand is translating into real price gains. Waterfront and village-center properties especially are seeing exceptional buyer competition.',
        realtor_hook: 'Mystic\'s tourism profile and national name recognition mean agents here benefit from inbound buyer inquiries that most Connecticut markets never see. The combination of primary, vacation, and investment buyers creates a diverse and active client base year-round.',
    },
    {
        slug: 'groton',
        name: 'Groton',
        county: 'New London County',
        state: 'CT',
        zip: '06340',
        population: '39,000',
        median_price: '$279,000',
        price_trend: 'up 9%',
        avg_dom: 24,
        description: 'Groton is the home of the U.S. Submarine Base and Electric Boat, creating a stable, defense-sector economy and consistent housing demand driven by military and civilian personnel. Its affordability and waterfront access along the Thames River and Long Island Sound make it an increasingly attractive market.',
        neighborhoods: 'Groton City, Groton Long Point, Poquonnock Bridge, Mystic side',
        nearby: 'New London, Mystic, Ledyard, Waterford',
        seller_hook: 'Groton\'s defense-sector economy provides a recession-resistant buyer base, and 9% appreciation signals that private buyers are also discovering its waterfront value and proximity to Mystic. Sellers benefit from steady, year-round demand anchored by one of the region\'s most stable employment centers.',
        realtor_hook: 'Groton\'s military and defense industry base creates a reliable stream of PCS buyers — some of the most motivated and time-sensitive buyers in real estate. Agents with relocation expertise and knowledge of Groton Long Point\'s waterfront market are especially well-positioned.',
    },
    {
        slug: 'new-london',
        name: 'New London',
        county: 'New London County',
        state: 'CT',
        zip: '06320',
        population: '27,000',
        median_price: '$219,000',
        price_trend: 'up 11%',
        avg_dom: 26,
        description: 'New London is a historic port city undergoing genuine revitalization, with a ferry hub connecting to Long Island and Block Island, a vibrant arts scene, and investments in its waterfront and downtown core attracting a new wave of buyers. Its 11% appreciation makes it one of southeastern Connecticut\'s most dynamic markets.',
        neighborhoods: 'Downtown New London, Harbour, Pequot area, Ocean Beach',
        nearby: 'Groton, Waterford, East Lyme, Montville',
        seller_hook: 'New London\'s 11% appreciation reflects a city that is genuinely transforming — and sellers who act now are capturing gains as the market builds momentum toward its full potential. Waterfront and historic district properties are especially well-positioned to command premium prices.',
        realtor_hook: 'New London\'s revitalization story is generating both investor and end-user buyer interest, giving agents two distinct and highly motivated client segments to serve. The city\'s ferry connections and waterfront assets are powerful marketing hooks that resonate with buyers from across the Northeast.',
    },
    {
        slug: 'stonington',
        name: 'Stonington',
        county: 'New London County',
        state: 'CT',
        zip: '06378',
        population: '18,000',
        median_price: '$489,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Stonington is a coastal Connecticut treasure, anchored by the historic Stonington Borough — a walkable granite-and-salt-air village jutting into Fishers Island Sound — alongside the creative energy of the Velvet Mill arts complex. It draws buyers seeking authentic New England coastal character at a premium that remains below comparable Rhode Island or Hamptons alternatives.',
        neighborhoods: 'Stonington Borough, Pawcatuck, Mystic, Velvet Mill area',
        nearby: 'Westerly RI, Mystic, North Stonington, Groton',
        seller_hook: 'Stonington Borough\'s scarcity of available properties and national recognition as one of New England\'s most beautiful villages means your listing will attract buyers from New York, Boston, and beyond — all competing for an address that rarely comes to market. Prices are up 7% and show no sign of slowing.',
        realtor_hook: 'Stonington\'s appeal to affluent second-home and primary buyers from New York and Boston means agents here regularly work with clients who are decisive, well-funded, and passionate about the town. The Borough\'s absolute scarcity of inventory makes every listing a high-stakes, high-reward event.',
    },
];
