// cities/fl-extra.js — Additional Florida city data for SEO landing pages
// Base fl.js already covers: Tampa, St. Pete, Fort Lauderdale, Boca Raton, West Palm Beach,
// Clearwater, Sarasota, Fort Myers, Naples, Cape Coral, Port St. Lucie, Orlando, Jacksonville,
// Gainesville, Tallahassee, Daytona Beach, Melbourne, Palm Bay, Ocala, Pensacola, Destin,
// Delray Beach, Coral Springs, Pembroke Pines, Miramar, Plantation, Sunrise, Deerfield Beach,
// Aventura, Coral Gables, Coconut Grove, Kendall, Lakeland, Kissimmee, The Villages

module.exports = [
    {
        slug: 'key-west',
        name: 'Key West',
        county: 'Monroe',
        state: 'FL',
        zip: '33040',
        population: '25,000',
        median_price: '$950,000',
        price_trend: 'up 5%',
        avg_dom: 55,
        description: 'Key West is America\'s Southernmost City and the most unique real estate market in the continental United States — a tiny coral island at the end of the Overseas Highway where Hemingway houses, Duval Street nightlife, a thriving LGBTQ+ community, and a finite land supply create one of the nation\'s most constrained markets, with conch-style cottages commanding prices that reflect both scarcity and the irreplaceable allure of island living.',
        neighborhoods: 'Old Town, Midtown, New Town, Stock Island, Big Coppitt Key',
        nearby: 'Stock Island, Big Pine Key, Marathon, Islamorada, Homestead',
        seller_hook: 'Key West\'s island scarcity and global prestige command exceptional sale prices — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Key West\'s limited inventory and luxury second-home market create some of Florida\'s highest-commission listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'homestead-fl',
        name: 'Homestead',
        county: 'Miami-Dade',
        state: 'FL',
        zip: '33030',
        population: '75,000',
        median_price: '$390,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Homestead is Miami-Dade\'s southernmost community and the gateway to Everglades and Biscayne National Parks — a rapidly growing agricultural city where Homestead Air Reserve Base, a booming agriculture and food processing sector, and Miami\'s explosive price appreciation pushing buyers south create one of South Florida\'s fastest-appreciating markets for first-time buyers.',
        neighborhoods: 'Florida City, Leisure City, Naranja, Princeton, Goulds',
        nearby: 'Florida City, Cutler Bay, Palmetto Bay, Key Largo',
        seller_hook: 'Homestead\'s Miami spillover demand and national park gateway create strong buyer interest — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Homestead\'s rapid appreciation and Miami commuter demand generate active listing conditions at South Florida\'s most affordable price points — find sellers through RealtorFinder.',
    },
    {
        slug: 'palm-coast',
        name: 'Palm Coast',
        county: 'Flagler',
        state: 'FL',
        zip: '32164',
        population: '93,000',
        median_price: '$330,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Palm Coast is one of Florida\'s fastest-growing cities and Flagler County\'s master-planned retirement and family destination — a Hammock Dunes coastal community between Daytona Beach and St. Augustine where golf courses, Intracoastal waterway access, and some of northeast Florida\'s most affordable new construction attract Northeast retirees and remote workers seeking Atlantic Coast living.',
        neighborhoods: 'Hammock Dunes, Marineland, Flagler Beach, Bunnell, Ormond Beach',
        nearby: 'Flagler Beach, Ormond Beach, St. Augustine, Bunnell, Daytona Beach',
        seller_hook: 'Palm Coast\'s retiree demand and coastal lifestyle create consistent buyer activity — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Palm Coast\'s rapid growth and out-of-state buyer influx generate active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'deltona',
        name: 'Deltona',
        county: 'Volusia',
        state: 'FL',
        zip: '32725',
        population: '92,000',
        median_price: '$295,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Deltona is Volusia County\'s largest city and one of Central Florida\'s fastest-growing bedroom communities — a planned lake community between Orlando and Daytona Beach on I-4 where affordability, quick access to both theme park employment and Atlantic Coast beaches, and Embry-Riddle Aeronautical University proximity attract working families and first-time buyers priced out of the greater Orlando metro.',
        neighborhoods: 'Orange City, DeBary, Sanford, Lake Helen, Cassadaga',
        nearby: 'Daytona Beach, DeLand, Orange City, DeBary, Sanford',
        seller_hook: 'Deltona\'s I-4 corridor location and Orlando spillover create consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Deltona\'s first-time buyer market and Central Florida growth generate active listing conditions — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'vero-beach',
        name: 'Vero Beach',
        county: 'Indian River',
        state: 'FL',
        zip: '32960',
        population: '17,000',
        median_price: '$430,000',
        price_trend: 'up 6%',
        avg_dom: 35,
        description: 'Vero Beach is the Treasure Coast\'s most refined coastal community — an Indian River Lagoon city beloved by snowbirds, retirees, and artists for its uncrowded Atlantic beaches, Riverside Theatre cultural scene, and a gracious small-town atmosphere that feels like Florida before the theme parks, with a luxury oceanfront market and more affordable barrier island condominiums serving a wide range of buyers.',
        neighborhoods: 'Indian River Shores, Orchid Island, Sebastian, Fellsmere, Gifford',
        nearby: 'Sebastian, Fort Pierce, Stuart, Melbourne, Wabasso',
        seller_hook: 'Vero Beach\'s Treasure Coast prestige and retiree demand command premium prices — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Vero Beach\'s coastal luxury and snowbird buyer market create high-value listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'panama-city',
        name: 'Panama City',
        county: 'Bay',
        state: 'FL',
        zip: '32401',
        population: '36,000',
        median_price: '$295,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Panama City is the Florida Panhandle\'s largest city and the commercial hub behind the emerald Gulf Coast — anchored by Tyndall Air Force Base, a major regional medical complex, and Gulf Coast State College, with a rebuilt Bay County housing market that recovered stronger after Hurricane Michael and now attracts military families, retirees, and buyers seeking affordable Gulf access east of the pricier 30A corridor.',
        neighborhoods: 'Lynn Haven, Callaway, Parker, Springfield, Millville',
        nearby: 'Lynn Haven, Callaway, Parker, Panama City Beach, Springfield',
        seller_hook: 'Panama City\'s Tyndall AFB and Gulf Coast recovery drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Panama City\'s military and Gulf Coast market create steady listing activity in the Florida Panhandle — find sellers through RealtorFinder.',
    },
    {
        slug: 'pompano-beach',
        name: 'Pompano Beach',
        county: 'Broward',
        state: 'FL',
        zip: '33060',
        population: '112,000',
        median_price: '$390,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'Pompano Beach is Broward County\'s underrated Atlantic Coast community — a working waterfront city north of Fort Lauderdale where Pompano Beach Amphitheater, the Sample-McDougald House historic district, and a booming downtown redevelopment create value opportunities for buyers who want Fort Lauderdale beach access and Broward County lifestyle at prices below comparable Boca Raton and Delray Beach addresses.',
        neighborhoods: 'Lighthouse Point, Deerfield Beach, Coconut Creek, Margate, Oakland Park',
        nearby: 'Deerfield Beach, Coconut Creek, Margate, Fort Lauderdale, Boca Raton',
        seller_hook: 'Pompano Beach\'s Atlantic Coast revival and Fort Lauderdale proximity create strong buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Pompano Beach\'s Broward County value and beach access generate active listing conditions — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'boynton-beach',
        name: 'Boynton Beach',
        county: 'Palm Beach',
        state: 'FL',
        zip: '33435',
        population: '80,000',
        median_price: '$375,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Boynton Beach is Palm Beach County\'s most diverse and affordable coastal city — a growing community between Boca Raton and Delray Beach where a revitalized Town Square development, Palm Beach State College, and some of the county\'s most accessible waterfront condominiums attract retirees, young professionals, and families seeking Palm Beach County prestige at prices well below northern Palm Beach towns.',
        neighborhoods: 'Leisureville, Golf, Quantum Park, Renaissance Commons, Hypoluxo',
        nearby: 'Delray Beach, Boca Raton, Lake Worth Beach, Lantana, Hypoluxo',
        seller_hook: 'Boynton Beach\'s Palm Beach County location and affordable coastal prices create strong buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Boynton Beach\'s retiree and young professional market generate consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'hollywood-fl',
        name: 'Hollywood',
        county: 'Broward',
        state: 'FL',
        zip: '33020',
        population: '153,000',
        median_price: '$410,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Hollywood is South Florida\'s most walkable beach city — a Broward County community between Fort Lauderdale and Miami where Hollywood Beach\'s famous Broadwalk, a Latin American cultural heritage, and Hollywood-Fort Lauderdale International Airport proximity create demand from international buyers, snowbirds, and Miami commuters seeking Atlantic Coast living with a cosmopolitan character at prices below comparable Miami Beach addresses.',
        neighborhoods: 'Hollywood Beach, West Hollywood, Hallandale Beach, Dania Beach, Aventura border',
        nearby: 'Hallandale Beach, Dania Beach, Fort Lauderdale, Pembroke Pines, Miramar',
        seller_hook: 'Hollywood\'s Broadwalk beach lifestyle and international buyer demand create strong listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Hollywood\'s Latin American buyer pool and beach city appeal generate active listing conditions in South Florida — find sellers through RealtorFinder.',
    },
    {
        slug: 'titusville',
        name: 'Titusville',
        county: 'Brevard',
        state: 'FL',
        zip: '32796',
        population: '47,000',
        median_price: '$265,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Titusville is the Space Coast\'s northern gateway and the closest city to Kennedy Space Center — a Brevard County community where NASA contractor employment, Space Coast Launching complex operations, an extraordinary Indian River Lagoon wildlife refuge, and some of the Space Coast\'s most affordable single-family homes attract aerospace workers, nature enthusiasts, and buyers seeking Central Florida access at lower prices than Orlando suburbs.',
        neighborhoods: 'Mims, Scottsmoor, Oak Hill, Port St. John, Sharpes',
        nearby: 'Cocoa, Rockledge, Melbourne, New Smyrna Beach, Daytona Beach',
        seller_hook: 'Titusville\'s Kennedy Space Center employment and Space Coast growth create active buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Titusville\'s aerospace workforce and affordable Space Coast prices generate consistent listing activity — find sellers through RealtorFinder.',
    },
];
