// cities/fl-extra.js — Additional Florida city data for SEO landing pages

module.exports = [
    {
        slug: 'cape-coral',
        name: 'Cape Coral',
        county: 'Lee',
        state: 'FL',
        zip: '33990',
        population: '194,000',
        median_price: '$370,000',
        price_trend: 'up 5%',
        avg_dom: 45,
        description: 'Cape Coral is the Gulf Coast\'s canal capital and one of Florida\'s most unique waterfront markets — a master-planned city with more navigable waterways than Venice, where boating lifestyle, Gulf of Mexico access, and Cape Coral\'s explosive post-pandemic population growth attract retirees, boaters, and investors seeking waterfront properties at prices well below comparable Fort Lauderdale and Naples canal addresses.',
        neighborhoods: 'Cape Coral Yacht Club, Pelican, Entrada, Southwest Cape, Burnt Store',
        nearby: 'Fort Myers, Bonita Springs, Estero, Pine Island, North Fort Myers',
        seller_hook: 'Cape Coral\'s canal waterfront lifestyle and Gulf Coast demand create strong buyer interest — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Cape Coral\'s waterfront market and retiree buyer pool create active listing conditions on the Gulf Coast — find sellers through RealtorFinder.',
    },
    {
        slug: 'fort-myers',
        name: 'Fort Myers',
        county: 'Lee',
        state: 'FL',
        zip: '33901',
        population: '87,000',
        median_price: '$330,000',
        price_trend: 'up 5%',
        avg_dom: 40,
        description: 'Fort Myers is Lee County\'s historic downtown and the City of Palms — a Caloosahatchee River community where Edison and Ford Winter Estates, Florida Gulf Coast University, and a booming River District arts scene attract retirees, university students, and investors who rebuilt and refined after Hurricane Ian, creating a dynamic market with post-storm new construction and refurbished historic inventory.',
        neighborhoods: 'McGregor, Downtown Fort Myers, Lehigh Acres, Gateway, Bonita Springs',
        nearby: 'Cape Coral, Bonita Springs, Lehigh Acres, Estero, Sanibel',
        seller_hook: 'Fort Myers\' River District revival and FGCU enrollment drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Fort Myers\' Gulf Coast market and retiree demand create steady listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'pembroke-pines',
        name: 'Pembroke Pines',
        county: 'Broward',
        state: 'FL',
        zip: '33024',
        population: '168,000',
        median_price: '$430,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Pembroke Pines is Broward County\'s second-largest city and one of South Florida\'s most family-oriented suburbs — a planned community where consistently top-ranked Broward County Schools, Memorial Healthcare System, and Florida International University proximity attract Miami and Fort Lauderdale commuters seeking more space, better schools, and suburban stability at prices below comparable Palm Beach County addresses.',
        neighborhoods: 'Silver Lakes, Chapel Trail, Pembroke Falls, Century Village, Miramar',
        nearby: 'Miramar, Hollywood, Davie, Weston, Cooper City',
        seller_hook: 'Pembroke Pines\' top schools and South Florida commuter demand create competitive listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Pembroke Pines\' family buyer market and Broward County appeal generate active listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'port-st-lucie',
        name: 'Port St. Lucie',
        county: 'St. Lucie',
        state: 'FL',
        zip: '34984',
        population: '201,000',
        median_price: '$360,000',
        price_trend: 'up 6%',
        avg_dom: 35,
        description: 'Port St. Lucie is the Treasure Coast\'s largest city and one of Florida\'s fastest-growing communities — a master-planned suburban city between Palm Beach and Melbourne where Cleveland Clinic\'s Tradition Medical Center, Indian River State College, and affordable master-planned communities attract South Florida retirees, medical workers, and families seeking palm-lined suburban living south of the high-cost Palm Beach market.',
        neighborhoods: 'Tradition, Torino, Gatlin, Becker Road, Fort Pierce',
        nearby: 'Stuart, Fort Pierce, Palm City, Jensen Beach, Hobe Sound',
        seller_hook: 'Port St. Lucie\'s Treasure Coast growth and Cleveland Clinic drive strong buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Port St. Lucie\'s medical sector and family buyer demand create active listing conditions on Florida\'s Treasure Coast — find sellers through RealtorFinder.',
    },
    {
        slug: 'miramar-fl',
        name: 'Miramar',
        county: 'Broward',
        state: 'FL',
        zip: '33025',
        population: '136,000',
        median_price: '$455,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Miramar is one of South Florida\'s most diverse and fastest-growing cities — a planned Broward County community where Spirit Airlines headquarters, hard rock companies, and a massive Haitian and Jamaican Caribbean-American community create a vibrant market of move-up buyers and investors seeking newer construction with quick Palmetto Expressway access to both Miami International Airport and Fort Lauderdale.',
        neighborhoods: 'Miramar Isles, Sunset Lakes, Monarch Lakes, Silver Falls, Riviera Isles',
        nearby: 'Pembroke Pines, Hollywood, Davie, Hialeah, Opa-locka',
        seller_hook: 'Miramar\'s diverse buyer pool and South Florida growth create competitive listing conditions — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Miramar\'s corporate headquarters and Caribbean-American buyer market generate active listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'gainesville-fl',
        name: 'Gainesville',
        county: 'Alachua',
        state: 'FL',
        zip: '32601',
        population: '141,000',
        median_price: '$290,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Gainesville is home to the University of Florida and one of the South\'s most dynamic college towns — a Gator Nation hub where UF\'s 55,000 students, a top-10 research university, UF Health medical complex, and a nationally recognized bike culture create intense housing competition, strong rental yields, and appreciation that has significantly outperformed Florida\'s non-coastal markets.',
        neighborhoods: 'Duckpond, Millhopper, Haile Plantation, Tioga, Newberry',
        nearby: 'Newberry, Alachua, Waldo, Micanopy, Hawthorne',
        seller_hook: 'Gainesville\'s UF enrollment and Gator Nation culture drive competitive buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Gainesville\'s university market and research economy create strong listing activity with excellent investment demand — find sellers through RealtorFinder.',
    },
    {
        slug: 'tallahassee',
        name: 'Tallahassee',
        county: 'Leon',
        state: 'FL',
        zip: '32301',
        population: '196,000',
        median_price: '$255,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Tallahassee is Florida\'s state capital and home to both Florida State University and Florida A&M — a double-university government city where Seminoles and Rattlers athletics culture, state agency employment, and two major research universities create consistent housing demand from students, government workers, and professionals seeking the South\'s most affordable capital city homeownership.',
        neighborhoods: 'Midtown, Betton Hills, Killearn, SouthWood, Waverly Hills',
        nearby: 'Crawfordville, Quincy, Havana, Monticello, Madison',
        seller_hook: 'Tallahassee\'s dual university system and state capital stability create reliable buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Tallahassee\'s government and university market generate consistent listing activity at Florida\'s most accessible capital city prices — find sellers through RealtorFinder.',
    },
    {
        slug: 'lakeland-fl',
        name: 'Lakeland',
        county: 'Polk',
        state: 'FL',
        zip: '33801',
        population: '112,000',
        median_price: '$295,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Lakeland is Central Florida\'s I-4 corridor hub and the City of Swans — a Polk County commercial center between Tampa and Orlando where Publix Super Markets headquarters, Florida Southern College, Watson Clinic, and some of central Florida\'s most affordable lakefront properties attract Tampa and Orlando commuters and retirees seeking a slower-paced Florida lifestyle without the I-4 traffic.',
        neighborhoods: 'South Lakeland, North Lakeland, Dixieland, Auburndale, Winter Haven',
        nearby: 'Winter Haven, Auburndale, Plant City, Bartow, Haines City',
        seller_hook: 'Lakeland\'s I-4 corridor growth and Publix headquarters create strong buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Lakeland\'s Tampa-Orlando commuter market and affordable prices generate active listing conditions — find sellers through RealtorFinder.',
    },
];
