// cities/fl.js — Florida city data for SEO landing pages

module.exports = [
    {
        slug: 'tampa',
        name: 'Tampa',
        county: 'Hillsborough',
        state: 'FL',
        zip: '33602',
        population: '403,000',
        median_price: '$399,000',
        price_trend: 'up 5%',
        avg_dom: 31,
        description: 'Tampa has evolved from a port city into one of Florida\'s most dynamic metros — anchored by Channelside\'s waterfront scene, Hyde Park\'s bungalow-lined streets, and Ybor City\'s historic brick districts. A booming tech and finance sector, the Port of Tampa, and easy access to Gulf Coast beaches drive relentless population growth and housing demand.',
        neighborhoods: 'Hyde Park, Ybor City, Channelside, Seminole Heights, South Tampa, Palma Ceia, Davis Islands, New Tampa',
        nearby: 'St. Petersburg, Clearwater, Brandon, Wesley Chapel, Lakeland',
        seller_hook: 'Tampa\'s in-migration from high-cost Northeast and Midwest markets keeps buyer demand elevated — let competing realtors on RealtorFinder fight for the right to list your home.',
        realtor_hook: 'Tampa\'s explosive commercial and residential growth makes it one of Florida\'s most active listing markets — RealtorFinder connects you with sellers ready to move.',
    },
    {
        slug: 'st-petersburg',
        name: 'St. Petersburg',
        county: 'Pinellas',
        state: 'FL',
        zip: '33701',
        population: '265,000',
        median_price: '$389,000',
        price_trend: 'up 4%',
        avg_dom: 33,
        description: 'St. Petersburg has reinvented itself as one of Florida\'s hippest mid-size cities — a walkable downtown packed with murals, world-class museums like the Dalí and the Chihuly, and a craft brewery scene anchored by the Grand Central and Edge districts. The city\'s Pinellas peninsula location gives residents quick access to Gulf beaches and the Tampa Bay job market.',
        neighborhoods: 'Downtown St. Pete, Old Northeast, Kenwood, Snell Isle, Shore Acres, Grand Central, Crescent Lake, Jungle Prada',
        nearby: 'Tampa, Clearwater, Gulfport, Seminole, Pinellas Park',
        seller_hook: 'St. Pete\'s rising arts-driven cachet and downtown revitalization have pushed values steadily upward — RealtorFinder helps you find an agent who knows how to price this competitive market.',
        realtor_hook: 'St. Petersburg\'s gentrifying neighborhoods and waterfront properties create strong listing opportunity for agents who understand its distinct submarkets — join RealtorFinder to reach motivated sellers.',
    },
    {
        slug: 'fort-lauderdale',
        name: 'Fort Lauderdale',
        county: 'Broward',
        state: 'FL',
        zip: '33301',
        population: '187,000',
        median_price: '$579,000',
        price_trend: 'up 5%',
        avg_dom: 34,
        description: 'Fort Lauderdale is the Venice of America — over 300 miles of navigable inland waterways thread through Las Olas Boulevard\'s restaurant row, Victoria Park\'s historic estates, and the Intracoastal\'s luxury marinas. It serves as the gateway to the Bahamas and functions as Broward County\'s commercial hub, drawing yachting enthusiasts, international buyers, and remote workers who want South Florida lifestyle at a slight discount to Miami.',
        neighborhoods: 'Las Olas Isles, Victoria Park, Rio Vista, Tarpon River, Sailboat Bend, Flagler Village, Colee Hammock, Harbor Beach',
        nearby: 'Hollywood, Pompano Beach, Deerfield Beach, Boca Raton, Miami',
        seller_hook: 'Fort Lauderdale\'s waterfront premium and Bahamas proximity attract high-net-worth buyers who demand expert representation — use RealtorFinder to get top Broward agents competing for your listing.',
        realtor_hook: 'Fort Lauderdale\'s boating community and luxury waterfront inventory generate some of Broward\'s highest per-transaction commissions — RealtorFinder connects you with sellers in this premium market.',
    },
    {
        slug: 'boca-raton',
        name: 'Boca Raton',
        county: 'Palm Beach',
        state: 'FL',
        zip: '33432',
        population: '101,000',
        median_price: '$649,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'Boca Raton is Palm Beach County\'s most affluent planned community — manicured boulevards lined with pink Mediterranean architecture lead to Mizner Park\'s upscale dining, the Boca Resort\'s private beach club, and gated communities favored by corporate executives and retirees from the Northeast. Florida Atlantic University and a strong tech corridor anchor younger professional demand.',
        neighborhoods: 'Mizner Park, Royal Palm Yacht & Country Club, Boca West, Camino Gardens, Broken Sound, Boca Pointe, Riviera Beach Colony, Saturnia',
        nearby: 'Delray Beach, Deerfield Beach, Boynton Beach, West Palm Beach, Fort Lauderdale',
        seller_hook: 'Boca Raton\'s wealthy buyer pool and strong demand from Northeast transplants make this one of South Florida\'s fastest-moving luxury markets — RealtorFinder lets top agents compete to list your home.',
        realtor_hook: 'Boca Raton\'s affluent clientele and high average sale prices make every listing count — RealtorFinder gives you access to motivated sellers in this prestigious Palm Beach County market.',
    },
    {
        slug: 'west-palm-beach',
        name: 'West Palm Beach',
        county: 'Palm Beach',
        state: 'FL',
        zip: '33401',
        population: '117,000',
        median_price: '$489,000',
        price_trend: 'up 7%',
        avg_dom: 29,
        description: 'West Palm Beach sits across the Intracoastal from Palm Beach island and has developed a vibrant identity of its own — Clematis Street\'s nightlife and Rosemary Square\'s boutiques anchor a revitalized downtown, while Northwood Village\'s arts scene and El Cid\'s historic bungalows attract a younger creative class. Billionaire migration to nearby Palm Beach has lifted surrounding valuations substantially.',
        neighborhoods: 'Downtown West Palm, Northwood Village, El Cid, Grandview Heights, Flamingo Park, SoSo, Prospect Park, South End',
        nearby: 'Palm Beach, Lake Worth, Boca Raton, Boynton Beach, Riviera Beach',
        seller_hook: 'West Palm Beach\'s rising profile — fueled by billionaire migration to Palm Beach island — has pushed demand and prices to new highs; let RealtorFinder connect you with an agent who can capitalize.',
        realtor_hook: 'West Palm Beach\'s rapidly appreciating neighborhoods and overflow demand from Palm Beach island make this one of South Florida\'s most lucrative emerging markets for listing agents.',
    },
    {
        slug: 'clearwater',
        name: 'Clearwater',
        county: 'Pinellas',
        state: 'FL',
        zip: '33755',
        population: '117,000',
        median_price: '$369,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Clearwater anchors the northern end of Pinellas County\'s Gulf Coast strip, with Clearwater Beach regularly ranked among America\'s best beaches for its powdery white sand and calm emerald water. Island Estates and Harbor Oaks provide waterfront living, while Downtown Clearwater\'s ongoing Imagine Clearwater project is reshaping the bluff overlooking the bay into a premier civic destination.',
        neighborhoods: 'Clearwater Beach, Island Estates, Harbor Oaks, Morningside Estates, Del Oro Groves, East Gateway, Old Clearwater Bay, Safety Harbor border',
        nearby: 'Dunedin, St. Petersburg, Largo, Oldsmar, Palm Harbor',
        seller_hook: 'Clearwater\'s beach proximity and bayfront lifestyle command a strong premium — RealtorFinder helps you find a local agent who understands the Pinellas market\'s nuanced waterfront value.',
        realtor_hook: 'Clearwater\'s combination of beach tourism, retiree demand, and young professional growth creates steady listing opportunity for agents who know Pinellas County inside and out.',
    },
    {
        slug: 'sarasota',
        name: 'Sarasota',
        county: 'Sarasota',
        state: 'FL',
        zip: '34236',
        population: '58,000',
        median_price: '$519,000',
        price_trend: 'up 4%',
        avg_dom: 36,
        description: 'Sarasota is Florida\'s cultural capital — home to the Ringling Museum of Art, a thriving opera and ballet scene, and one of the country\'s most visited stretches of Gulf beach at Siesta Key. The Rosemary District and Burns Court neighborhoods attract arts professionals and affluent retirees, while the Sarasota School of Architecture legacy gives the city an internationally recognized design identity.',
        neighborhoods: 'Rosemary District, Burns Court, Laurel Park, Gillespie Park, Hudson Bayou, Gulf Gate, Indian Beach Sapphire Shores, Oyster Bay',
        nearby: 'Bradenton, Venice, North Port, Osprey, Englewood',
        seller_hook: 'Sarasota\'s arts-and-beach lifestyle and wealthy retiree buyer base create strong demand for well-positioned properties — RealtorFinder helps you find the agent best suited to this refined market.',
        realtor_hook: 'Sarasota\'s affluent transplant community and Siesta Key beach premium make listings here among the most rewarding on Florida\'s Gulf Coast — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'fort-myers',
        name: 'Fort Myers',
        county: 'Lee',
        state: 'FL',
        zip: '33901',
        population: '93,000',
        median_price: '$349,000',
        price_trend: 'up 3%',
        avg_dom: 40,
        description: 'Fort Myers sits at the heart of Lee County\'s booming Southwest Florida corridor — the historic River District\'s galleries and restaurants line the Caloosahatchee River waterfront, while Edison and Ford\'s winter estates anchor a cultural tourism draw. Post-Hurricane Ian recovery has accelerated redevelopment and brought a new generation of buyers into the market.',
        neighborhoods: 'River District, McGregor Boulevard, Seminole, Villas, Iona, Cape Coral border, Page Park, Palmlee Park',
        nearby: 'Cape Coral, Bonita Springs, Naples, Lehigh Acres, Estero',
        seller_hook: 'Fort Myers\'s post-Ian redevelopment momentum and continued in-migration from Northern states are driving renewed buyer competition — let RealtorFinder match you with an agent who knows this rebound market.',
        realtor_hook: 'Fort Myers\'s ongoing recovery and redevelopment cycle, combined with strong population growth, makes it one of Southwest Florida\'s most active listing markets for motivated agents.',
    },
    {
        slug: 'naples',
        name: 'Naples',
        county: 'Collier',
        state: 'FL',
        zip: '34102',
        population: '22,000',
        median_price: '$749,000',
        price_trend: 'up 5%',
        avg_dom: 45,
        description: 'Naples is Florida\'s most exclusive small city — a pristine Gulf Coast enclave where Fifth Avenue South\'s boutiques and fine dining sit minutes from white-sand beaches that consistently rank among the nation\'s cleanest. The city attracts Midwestern executives, hedge fund managers, and retirees seeking world-class golf at communities like Pelican Bay, Grey Oaks, and Port Royal.',
        neighborhoods: 'Port Royal, Aqualane Shores, Old Naples, Pelican Bay, Park Shore, Moorings, Grey Oaks, Coquina Sands',
        nearby: 'Marco Island, Bonita Springs, Fort Myers, Estero, Ave Maria',
        seller_hook: 'Naples\'s ultra-wealthy buyer pool and limited inventory make choosing the right listing agent critical — RealtorFinder lets you compare top Collier County agents competing for your property.',
        realtor_hook: 'Naples consistently produces some of Florida\'s highest per-transaction values — RealtorFinder connects you with sellers in one of the country\'s most affluent small real estate markets.',
    },
    {
        slug: 'cape-coral',
        name: 'Cape Coral',
        county: 'Lee',
        state: 'FL',
        zip: '33990',
        population: '230,000',
        median_price: '$399,000',
        price_trend: 'up 3%',
        avg_dom: 42,
        description: 'Cape Coral is a city built on canals — over 400 miles of navigable waterways, more than any city in the world, give a huge portion of its residential inventory direct Gulf access and boat dock potential. One of Florida\'s fastest-growing cities, it draws families and retirees who want waterfront lifestyle at a relative discount to Naples or Fort Lauderdale.',
        neighborhoods: 'Cape Harbour, Pelican, Entrada, Surfside, Caloosa, Pine Island Corridor, Burnt Store Marina, Sandoval',
        nearby: 'Fort Myers, Matlacha, Pine Island, Bonita Springs, Lehigh Acres',
        seller_hook: 'Cape Coral\'s canal-front homes are a unique product that savvy buyers compete for — let RealtorFinder connect you with agents who specialize in the Lee County waterfront market.',
        realtor_hook: 'Cape Coral\'s unmatched canal network and strong short-term rental market attract a steady stream of investors and lifestyle buyers — RealtorFinder helps you reach motivated sellers here.',
    },
    {
        slug: 'port-st-lucie',
        name: 'Port St. Lucie',
        county: 'St. Lucie',
        state: 'FL',
        zip: '34984',
        population: '246,000',
        median_price: '$359,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Port St. Lucie is the Treasure Coast\'s largest city and one of Florida\'s fastest-growing communities — Tradition\'s master-planned town center, the New York Mets\' spring training facility at Clover Park, and expanding healthcare and biotech sectors have transformed what was once a retirement backwater into a diverse, family-oriented metro attracting workers priced out of South Florida.',
        neighborhoods: 'Tradition, Torino, Gatlin Boulevard Corridor, River Park, Southbend, PGA Village, Lake Charles, St. James Golf Club',
        nearby: 'Stuart, Fort Pierce, Hobe Sound, Palm City, Vero Beach',
        seller_hook: 'Port St. Lucie\'s rapid growth and influx of South Florida transplants mean motivated buyers are actively competing for homes here — RealtorFinder helps you find an agent who can capture that demand.',
        realtor_hook: 'Port St. Lucie\'s population surge and expanding employer base make it one of the Treasure Coast\'s most active residential markets — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'orlando',
        name: 'Orlando',
        county: 'Orange',
        state: 'FL',
        zip: '32801',
        population: '320,000',
        median_price: '$369,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'Orlando is Florida\'s fastest-growing major metro — a tourism and tech powerhouse that has added hundreds of thousands of residents over the past decade, driven by no state income tax, job growth in healthcare and simulation/defense technology, and a lifestyle that draws families and young professionals from across the country. Beyond the theme parks, neighborhoods like Thornton Park, College Park, and Winter Park define Orlando\'s sophisticated residential identity.',
        neighborhoods: 'Thornton Park, College Park, Audubon Park, Baldwin Park, Winter Park border, Dr. Phillips, Lake Nona, Milk District',
        nearby: 'Kissimmee, Winter Park, Altamonte Springs, Sanford, Lake Mary',
        seller_hook: 'Orlando\'s booming job market and steady in-migration drive consistent buyer demand across price points — RealtorFinder helps you find an agent who can position your home to win.',
        realtor_hook: 'Orlando\'s diverse economy, theme park employment, and tech sector growth make it one of Florida\'s most active listing markets — join RealtorFinder to connect with motivated sellers.',
    },
    {
        slug: 'jacksonville',
        name: 'Jacksonville',
        county: 'Duval',
        state: 'FL',
        zip: '32202',
        population: '975,000',
        median_price: '$329,000',
        price_trend: 'up 4%',
        avg_dom: 36,
        description: 'Jacksonville is Florida\'s largest city by land area and its most affordable major metro — a consolidation city spanning from the St. Johns River\'s urban core to Atlantic Beach\'s surf scene and Ponte Vedra\'s golf resort communities. The Navy\'s largest East Coast footprint, a major financial services sector anchored by Fidelity and Berkshire Hathaway, and a growing healthcare industry underpin the job market.',
        neighborhoods: 'Riverside, Avondale, San Marco, Springfield, Ortega, Ponte Vedra border, Mandarin, Southside',
        nearby: 'Ponte Vedra Beach, Orange Park, Fleming Island, St. Augustine, Fernandina Beach',
        seller_hook: 'Jacksonville\'s affordability advantage and strong military and finance job base attract a broad buyer pool — RealtorFinder connects you with top Duval County agents competing for your listing.',
        realtor_hook: 'Jacksonville\'s massive geographic footprint and diverse submarkets from riverfront estates to oceanfront cottages offer agents exceptional breadth — reach motivated sellers through RealtorFinder.',
    },
    {
        slug: 'gainesville',
        name: 'Gainesville',
        county: 'Alachua',
        state: 'FL',
        zip: '32601',
        population: '143,000',
        median_price: '$289,000',
        price_trend: 'up 3%',
        avg_dom: 38,
        description: 'Gainesville is Florida\'s quintessential college town — the University of Florida\'s 55,000-student campus anchors a lively Midtown and University Avenue corridor, while Haile Plantation\'s planned community and Duck Pond\'s historic Craftsman bungalows serve the professional and faculty market. UF Health\'s expanding medical complex makes it one of North Florida\'s most significant healthcare employment centers.',
        neighborhoods: 'Duck Pond, Duckpond Historic District, Haile Plantation, Midtown, University Heights, Tumblin Creek, Forest Ridge, Sugarfoot Oaks',
        nearby: 'Newberry, Alachua, High Springs, Ocala, Lake City',
        seller_hook: 'Gainesville\'s stable university economy and consistent housing demand from students, faculty, and medical professionals make it a reliable seller\'s market — RealtorFinder connects you with the best local agents.',
        realtor_hook: 'Gainesville\'s university-driven rental demand and steady faculty and healthcare buyer pool make it a consistent market for listing agents — join RealtorFinder to find motivated sellers.',
    },
    {
        slug: 'tallahassee',
        name: 'Tallahassee',
        county: 'Leon',
        state: 'FL',
        zip: '32301',
        population: '198,000',
        median_price: '$269,000',
        price_trend: 'up 2%',
        avg_dom: 40,
        description: 'Tallahassee is Florida\'s capital city and home to Florida State University and FAMU — a city of canopy roads draped in Spanish moss, rolling red clay hills unlike anywhere else in Florida, and a professional class of state employees, lobbyists, attorneys, and academics. The Midtown and Betton Hills neighborhoods are perennial favorites for their mature landscaping and proximity to everything the city offers.',
        neighborhoods: 'Betton Hills, Midtown, Killearn Estates, Summerbrooke, Waverly Hills, Lafayette Park, Hartsfield, Levy Park',
        nearby: 'Thomasville GA, Quincy, Crawfordville, Monticello, Havana',
        seller_hook: 'Tallahassee\'s stable government employment base and dual university market provide consistent buyer demand — RealtorFinder helps you identify the agent best positioned to sell your home here.',
        realtor_hook: 'Tallahassee\'s government, legal, and academic communities generate steady move-up buyer demand — RealtorFinder connects you with motivated sellers in this North Florida capital market.',
    },
    {
        slug: 'daytona-beach',
        name: 'Daytona Beach',
        county: 'Volusia',
        state: 'FL',
        zip: '32114',
        population: '73,000',
        median_price: '$279,000',
        price_trend: 'up 3%',
        avg_dom: 42,
        description: 'Daytona Beach is synonymous with speed and sun — the Daytona International Speedway draws hundreds of thousands of visitors for Daytona 500 and Bike Week, while the World\'s Most Famous Beach stretches miles of hard-packed Atlantic sand. Embry-Riddle Aeronautical University and Halifax Health anchor a diversifying economy beyond tourism, and the Daytona Beach Boardwalk area is undergoing significant private investment.',
        neighborhoods: 'Daytona Beach Shores, Ormond Beach border, Port Orange border, Holly Hill, Seabreeze, Beachside, Mainland, LPGA International',
        nearby: 'Ormond Beach, Port Orange, New Smyrna Beach, DeLand, Palm Coast',
        seller_hook: 'Daytona Beach\'s growing investor appeal and tourism draw keep demand active for beachside properties — let RealtorFinder connect you with an agent who understands this unique market.',
        realtor_hook: 'Daytona Beach\'s mix of investor buyers, retirees, and Embry-Riddle families creates consistent listing demand — RealtorFinder helps you reach motivated sellers in Volusia County.',
    },
    {
        slug: 'melbourne',
        name: 'Melbourne',
        county: 'Brevard',
        state: 'FL',
        zip: '32901',
        population: '86,000',
        median_price: '$339,000',
        price_trend: 'up 5%',
        avg_dom: 33,
        description: 'Melbourne sits at the heart of Florida\'s Space Coast — a city where aerospace engineers from NASA Kennedy Space Center and Northrop Grumman fill neighborhoods like Eau Gallie\'s arts district and Suntree\'s master-planned golf communities. The ongoing New Space boom with SpaceX and Blue Origin launches from nearby Cape Canaveral has fueled strong professional in-migration and housing price appreciation.',
        neighborhoods: 'Eau Gallie Arts District, Suntree, Viera border, Indialantic border, Melbourne Beach border, Wickham Park area, Palm Bay border, Historic Downtown',
        nearby: 'Palm Bay, Titusville, Cocoa Beach, Viera, Indialantic',
        seller_hook: 'Melbourne\'s Space Coast economy is booming with New Space jobs — the resulting buyer demand means well-prepared sellers can command strong prices; RealtorFinder finds the agents to make that happen.',
        realtor_hook: 'Melbourne\'s aerospace and tech employment growth is driving some of Florida\'s strongest appreciation on the Atlantic coast — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'palm-bay',
        name: 'Palm Bay',
        county: 'Brevard',
        state: 'FL',
        zip: '32905',
        population: '125,000',
        median_price: '$299,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Palm Bay is Brevard County\'s largest city by population — a sprawling aerospace suburb where affordable single-family homes attract space industry workers, first-time buyers, and retirees seeking proximity to the Indian River Lagoon. The city\'s size and ongoing infrastructure investment have drawn distribution and manufacturing employers that supplement the dominant defense and aerospace economy.',
        neighborhoods: 'Port Malabar, Bayside Lakes, Turkey Creek, Deer Lakes, Kingsmill, Waterstone, West Melbourne border, Malabar border',
        nearby: 'Melbourne, Grant-Valkaria, Malabar, Sebastian, Micco',
        seller_hook: 'Palm Bay\'s affordability relative to other Florida markets and strong Space Coast employment draw first-time buyers and investors — RealtorFinder helps you find an agent to reach them effectively.',
        realtor_hook: 'Palm Bay\'s value positioning and growing employer base create high listing volume opportunity for active Brevard County agents — join RealtorFinder to connect with motivated sellers.',
    },
    {
        slug: 'ocala',
        name: 'Ocala',
        county: 'Marion',
        state: 'FL',
        zip: '34471',
        population: '69,000',
        median_price: '$259,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Ocala is the Horse Capital of the World — rolling limestone pastures outside the city contain over 1,200 horse farms producing more thoroughbred champions than virtually any other region in America. Downtown Ocala\'s revitalized square and the rapidly growing On Top of the World active-adult community drive residential demand that balances horse country estates with affordable suburban homes.',
        neighborhoods: 'Historic Downtown, Silver Springs Shores, On Top of the World, Heath Brook, Fore Ranch, SE Ocala, SW Ocala, Shady',
        nearby: 'Gainesville, The Villages, Leesburg, Crystal River, Dunnellon',
        seller_hook: 'Ocala\'s unique equestrian appeal and active-adult market create specialized buyer demand that rewards sellers who partner with knowledgeable local agents — find them through RealtorFinder.',
        realtor_hook: 'Ocala\'s horse farm market, retirement communities, and affordable suburban growth offer agents a diverse portfolio of listing opportunities — RealtorFinder connects you with motivated sellers here.',
    },
    {
        slug: 'pensacola',
        name: 'Pensacola',
        county: 'Escambia',
        state: 'FL',
        zip: '32501',
        population: '54,000',
        median_price: '$299,000',
        price_trend: 'up 4%',
        avg_dom: 37,
        description: 'Pensacola anchors Florida\'s western Panhandle — a city of Fort Pickens white-sand dunes, the National Naval Aviation Museum at NAS Pensacola, and a Downtown Pensacola that has revived around Palafox Street\'s restaurants and Pensacola Bay views. Military families, retirees, and remote workers from higher-cost metros have fueled a housing market that now attracts national attention for its value proposition.',
        neighborhoods: 'East Hill, North Hill, Palafox, Cordova Park, Ferry Pass, Ensley, Perdido Key border, Gulf Breeze border',
        nearby: 'Gulf Breeze, Pace, Milton, Navarre, Destin',
        seller_hook: 'Pensacola\'s military community and retiree in-migration create a reliable buyer pool — RealtorFinder helps you find an agent who knows the Escambia County market to get your home sold efficiently.',
        realtor_hook: 'Pensacola\'s mix of military PCS buyers, retirees, and Panhandle beach lifestyle seekers makes it one of Northwest Florida\'s most active listing markets — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'destin',
        name: 'Destin',
        county: 'Okaloosa',
        state: 'FL',
        zip: '32541',
        population: '16,000',
        median_price: '$649,000',
        price_trend: 'up 4%',
        avg_dom: 44,
        description: 'Destin is the Emerald Coast\'s premier resort destination — where the Gulf\'s turquoise water and sugar-white Panhandle sand meet an extraordinary concentration of vacation rentals, fishing charter fleets, and luxury condominiums along Scenic Highway 98. The Destin Harbor Boardwalk, HarborWalk Village, and Henderson Beach State Park define an experience that attracts millions of visitors and thousands of second-home investors annually.',
        neighborhoods: 'Crystal Beach, Miramar Beach, Holiday Isle, Regatta Bay, Indian Bayou, Destiny, Pelican Beach, Kelly Plantation',
        nearby: 'Miramar Beach, Fort Walton Beach, Santa Rosa Beach, Niceville, Crestview',
        seller_hook: 'Destin\'s short-term rental income potential and vacation home demand from buyers across the South make it a premium market where the right agent makes a real difference — find them on RealtorFinder.',
        realtor_hook: 'Destin\'s vacation rental economy and second-home buyer base generate high-value transactions year-round — RealtorFinder connects you with sellers in one of the Panhandle\'s most lucrative markets.',
    },
    {
        slug: 'delray-beach',
        name: 'Delray Beach',
        county: 'Palm Beach',
        state: 'FL',
        zip: '33444',
        population: '70,000',
        median_price: '$519,000',
        price_trend: 'up 5%',
        avg_dom: 31,
        description: 'Delray Beach is one of South Florida\'s most celebrated downtown destinations — Atlantic Avenue\'s two-mile stretch of restaurants, galleries, and boutiques runs from the Intracoastal to the Atlantic Ocean beach, creating a walkable energy unusual in Palm Beach County. The city has attracted a sophisticated mix of young professionals, retirees from the Northeast, and creative entrepreneurs drawn to its award-winning downtown.',
        neighborhoods: 'Osceola Park, Lake Ida, Tropic Isle, Pineapple Grove, Seagate, Del Ida Park, Tropic Palms, Lake Eden',
        nearby: 'Boca Raton, Boynton Beach, Deerfield Beach, Lantana, Greenacres',
        seller_hook: 'Delray Beach\'s nationally recognized downtown and Atlantic beach access create exceptional buyer demand — RealtorFinder helps you find an agent who can position your home at the top of this competitive market.',
        realtor_hook: 'Delray Beach\'s vibrant Atlantic Avenue lifestyle and Intracoastal properties attract motivated buyers willing to pay premium prices — join RealtorFinder to connect with sellers in this desirable market.',
    },
    {
        slug: 'coral-springs',
        name: 'Coral Springs',
        county: 'Broward',
        state: 'FL',
        zip: '33065',
        population: '135,000',
        median_price: '$499,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Coral Springs is one of Broward County\'s most family-oriented planned cities — a master-planned community from the 1960s that has matured into a sought-after suburb with nationally recognized public schools, extensive parks, and a newly revitalized downtown district. Its location between Sawgrass Mills and Boca Raton makes it a natural choice for families seeking South Florida lifestyle with strong school district performance.',
        neighborhoods: 'Eagle Trace, Wyndham Lakes, Heron Bay, Maplewood, Cypress Run, Wiles Road Corridor, Rock Island, Winston Park',
        nearby: 'Parkland, Margate, Tamarac, Coconut Creek, Boca Raton',
        seller_hook: 'Coral Springs\'s top-ranked schools and family-friendly reputation keep buyer demand consistently high — let RealtorFinder match you with an agent who can market to the families competing for homes here.',
        realtor_hook: 'Coral Springs\'s planned community design and strong school ratings generate reliable move-up buyer demand — RealtorFinder connects you with motivated sellers in this established Broward market.',
    },
    {
        slug: 'pembroke-pines',
        name: 'Pembroke Pines',
        county: 'Broward',
        state: 'FL',
        zip: '33024',
        population: '172,000',
        median_price: '$489,000',
        price_trend: 'up 5%',
        avg_dom: 31,
        description: 'Pembroke Pines is Broward County\'s second-largest city — a diverse, family-driven suburb where Charter Schools of Excellence, extensive age-55+ communities like Century Village, and well-maintained single-family neighborhoods attract a broad demographic cross-section. Its location between Miami and Fort Lauderdale along I-75 makes it a natural hub for families and retirees who want South Florida access without urban density.',
        neighborhoods: 'Pembroke Falls, Silver Lakes, Chapel Trail, Grand Palms, Walnut Creek, Century Village, Regency Lakes, Nautica',
        nearby: 'Miramar, Hollywood, Davie, Weston, Cooper City',
        seller_hook: 'Pembroke Pines\'s family appeal and active-adult communities attract a wide buyer funnel — RealtorFinder helps you find a Broward agent who can tap into that demand for your listing.',
        realtor_hook: 'Pembroke Pines\'s large population and diverse buyer demographics — families, retirees, first-timers — make it one of Broward\'s most reliable listing markets for consistent agents.',
    },
    {
        slug: 'miramar',
        name: 'Miramar',
        county: 'Broward',
        state: 'FL',
        zip: '33023',
        population: '140,000',
        median_price: '$519,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Miramar has transformed from a small Broward suburb into a major South Florida employment center — Spirit Airlines\' headquarters, extensive healthcare campuses, and a growing logistics sector have diversified the economy well beyond its residential base. Its Caribbean and Latin American diaspora community has shaped a vibrant cultural identity, and master-planned communities like Monarch Lakes attract families seeking newer construction.',
        neighborhoods: 'Monarch Lakes, Riviera Isles, Sunset Lakes, Vizcaya, Silver Shores, Miramar Isles, Royal Palm Ranch, Huntington',
        nearby: 'Pembroke Pines, Hollywood, Hallandale Beach, Davie, Hialeah',
        seller_hook: 'Miramar\'s corporate employment anchors and diverse buyer demand make it a competitive seller\'s market — RealtorFinder connects you with experienced Broward agents competing to list your home.',
        realtor_hook: 'Miramar\'s steady corporate employment growth and Caribbean community ties bring motivated buyers into the market regularly — join RealtorFinder to reach sellers across this dynamic city.',
    },
    {
        slug: 'plantation',
        name: 'Plantation',
        county: 'Broward',
        state: 'FL',
        zip: '33317',
        population: '95,000',
        median_price: '$529,000',
        price_trend: 'up 4%',
        avg_dom: 32,
        description: 'Plantation is one of Broward County\'s most established mid-century suburbs — its tree-canopied neighborhoods, Plantation Central Park, and Broward Mall anchor a community that has attracted healthcare and tech employers including DHL and American Express to its corporate campuses along Broward Boulevard. The city\'s mature landscaping and larger lot sizes command a premium over newer Broward suburbs.',
        neighborhoods: 'Jacaranda, Central Park, Plantation Acres, Plantation Isles, Lago Mar, Midtown, Plantation Gardens, Lauderdale West',
        nearby: 'Davie, Sunrise, Lauderhill, Fort Lauderdale, Weston',
        seller_hook: 'Plantation\'s mature neighborhoods and corporate employment base attract experienced buyers who appreciate established community character — let RealtorFinder find you an agent who understands this market.',
        realtor_hook: 'Plantation\'s premium lot sizes, canopied streets, and corporate employment draw make it one of Broward\'s most consistent mid-to-luxury listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'sunrise',
        name: 'Sunrise',
        county: 'Broward',
        state: 'FL',
        zip: '33351',
        population: '96,000',
        median_price: '$429,000',
        price_trend: 'up 5%',
        avg_dom: 31,
        description: 'Sunrise is a Broward County city with a profile that punches above its residential weight — it hosts the BB&T Center (home of the Florida Panthers NHL franchise), Sawgrass Mills (one of the nation\'s largest outlet malls), and the Sawgrass International Corporate Park. Its diverse population, affordable pricing relative to Coral Springs and Plantation, and strong renter-to-buyer conversion pipeline make it an active housing market.',
        neighborhoods: 'Springtree, Welleby, Sunrise Golf Village, North Springs, Sawgrass, Sunrise Lakes, Dimensions, Inverrary',
        nearby: 'Lauderhill, Plantation, Tamarac, Lauderdale Lakes, Fort Lauderdale',
        seller_hook: 'Sunrise\'s value pricing relative to surrounding Broward cities and strong renter-buyer conversion keep demand active — RealtorFinder helps you connect with an agent who knows this market\'s dynamics.',
        realtor_hook: 'Sunrise\'s large renter population converting to buyers and proximity to the Sawgrass corporate corridor create steady listing demand — join RealtorFinder to reach motivated Broward sellers.',
    },
    {
        slug: 'deerfield-beach',
        name: 'Deerfield Beach',
        county: 'Broward',
        state: 'FL',
        zip: '33441',
        population: '82,000',
        median_price: '$399,000',
        price_trend: 'up 4%',
        avg_dom: 33,
        description: 'Deerfield Beach occupies a prime coastal position at the northern edge of Broward County — its pier, blue flag beach, and Intracoastal marina create a laid-back character that attracts retirees and boaters, while proximity to Boca Raton\'s employment centers and the growing mixed-use Cove district draw younger buyers seeking affordability without sacrificing waterfront access.',
        neighborhoods: 'The Cove, Century Village, Quiet Waters, Deer Creek, West Deerfield, Greenfield Estates, Riverview, Palmaire',
        nearby: 'Boca Raton, Pompano Beach, Coconut Creek, Lighthouse Point, Hillsboro Beach',
        seller_hook: 'Deerfield Beach\'s Boca Raton adjacency and beach access attract buyers priced out of more expensive South Florida markets — RealtorFinder helps you find an agent to capture that spillover demand.',
        realtor_hook: 'Deerfield Beach\'s position between Boca Raton and Fort Lauderdale, combined with beach and Intracoastal access, makes it a reliable Broward listing market — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'aventura',
        name: 'Aventura',
        county: 'Miami-Dade',
        state: 'FL',
        zip: '33160',
        population: '40,000',
        median_price: '$579,000',
        price_trend: 'up 6%',
        avg_dom: 35,
        description: 'Aventura is one of South Florida\'s most affluent small cities — a high-rise luxury enclave built around Aventura Mall (one of the largest in the U.S.), the William Lehman Causeway Intracoastal waterway, and a concentration of upscale condominiums that attract international buyers and South American investors alongside domestic retirees. Its walkability and concierge building lifestyle set it apart from surrounding sprawl.',
        neighborhoods: 'Williams Island, Porto Vita, Mystic Pointe, Turnberry Isle, Aventura Marina, The Waterways, Thalatta, Point East',
        nearby: 'Hallandale Beach, Sunny Isles Beach, North Miami Beach, Bal Harbour, Hollywood',
        seller_hook: 'Aventura\'s international buyer appeal and luxury condo market create a unique pricing dynamic — let RealtorFinder connect you with a South Florida agent who specializes in this high-rise luxury segment.',
        realtor_hook: 'Aventura\'s concentration of luxury condos and international buyers makes it one of Miami-Dade\'s highest-value per-transaction markets — RealtorFinder connects you with motivated sellers in this elite enclave.',
    },
    {
        slug: 'coral-gables',
        name: 'Coral Gables',
        county: 'Miami-Dade',
        state: 'FL',
        zip: '33134',
        population: '50,000',
        median_price: '$1,199,000',
        price_trend: 'up 5%',
        avg_dom: 40,
        description: 'Coral Gables is Miami\'s most prestigious planned city — a Mediterranean Revival masterwork of George Merrick\'s 1920s vision, where banyan-canopied streets lead to the Venetian Pool, the Biltmore Hotel, Miracle Mile\'s boutiques, and some of the largest estate lots in Miami-Dade. The University of Miami\'s Coral Gables campus, dozens of foreign consulates, and top-tier private schools make it a perennial destination for Miami\'s executive class.',
        neighborhoods: 'Cocoplum, Gables Estates, South Gables, Ponce-Davis, Shenandoah border, Riviera, Coral Way, Old Cutler Road',
        nearby: 'Miami, Coconut Grove, South Miami, Pinecrest, Kendall',
        seller_hook: 'Coral Gables\'s estate market and international executive buyer base require agents with specialized luxury expertise — RealtorFinder lets you compare the top Gables agents competing for your listing.',
        realtor_hook: 'Coral Gables is one of Florida\'s most prestigious and highest-value residential markets — RealtorFinder connects you with motivated estate sellers in this iconic Miami-Dade enclave.',
    },
    {
        slug: 'coconut-grove',
        name: 'Coconut Grove',
        county: 'Miami-Dade',
        state: 'FL',
        zip: '33133',
        population: '22,000',
        median_price: '$899,000',
        price_trend: 'up 6%',
        avg_dom: 38,
        description: 'Coconut Grove is Miami\'s oldest neighborhood and most bohemian enclave — a lush, tree-canopied district where bayfront estates, the Vizcaya Museum gardens, and the newly reimagined CocoWalk sit alongside sailing clubs, independent galleries, and the storied history of Ralph Munroe\'s original settlers. Its limited inventory, tropical foliage, and walkable village character make it among the most coveted addresses in Miami.',
        neighborhoods: 'West Grove, Silver Bluff, North Grove, South Grove, The Roads border, Bayshore, Main Highway Corridor, DevonMiami area',
        nearby: 'Coral Gables, Brickell, South Miami, Key Biscayne, Pinecrest',
        seller_hook: 'Coconut Grove\'s constrained inventory and devoted buyer following mean well-prepared sellers consistently achieve strong outcomes — let RealtorFinder find you the Grove specialist to maximize your result.',
        realtor_hook: 'Coconut Grove\'s tight inventory and passionate buyer demand create exceptional listing opportunity for Miami agents with the right market knowledge — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'kendall',
        name: 'Kendall',
        county: 'Miami-Dade',
        state: 'FL',
        zip: '33156',
        population: '80,000',
        median_price: '$619,000',
        price_trend: 'up 5%',
        avg_dom: 33,
        description: 'Kendall is Miami-Dade\'s largest suburban district — a sprawling western corridor of master-planned communities, top-rated schools, and retail centers anchored by Dadeland Mall and the Palmetto Expressway. It serves as the primary family destination for Miami\'s Latin American middle and upper-middle class, with Pinecrest\'s luxury estate pockets to the east commanding significant premiums over Kendall\'s core.',
        neighborhoods: 'Dadeland, Sunset, The Hammocks, Kendale Lakes, Calusa, Killian, West Kendall, Three Lakes',
        nearby: 'Pinecrest, South Miami, Palmetto Bay, Doral, Sweetwater',
        seller_hook: 'Kendall\'s strong Latin American family buyer base and top-rated schools keep demand consistently elevated — RealtorFinder helps you find a Miami-Dade agent who understands this distinct suburban market.',
        realtor_hook: 'Kendall\'s large population, family orientation, and rising valuations make it one of Miami-Dade\'s most active listing corridors — join RealtorFinder to connect with motivated sellers.',
    },
    {
        slug: 'lakeland',
        name: 'Lakeland',
        county: 'Polk',
        state: 'FL',
        zip: '33801',
        population: '126,000',
        median_price: '$299,000',
        price_trend: 'up 4%',
        avg_dom: 37,
        description: 'Lakeland sits at the I-4 midpoint between Tampa and Orlando — a position that has made it Florida\'s fastest-growing inland city, as logistics giants, Amazon distribution centers, and Publix Super Markets\' global headquarters anchor a diversifying economy. Frank Lloyd Wright\'s largest collection of buildings, Florida Southern College\'s lakefront campus, and a revitalized downtown make it one of Central Florida\'s most livable mid-size cities.',
        neighborhoods: 'Lake Mirror, Cleveland Heights, Dixieland, Southgate, Beacon Hill, Lake Hollingsworth, Imperial Lakeland Estates, North Lakeland',
        nearby: 'Winter Haven, Plant City, Bartow, Haines City, Auburndale',
        seller_hook: 'Lakeland\'s I-4 corridor location and logistics boom are driving in-migration that sustains strong buyer demand across price points — RealtorFinder connects you with agents who know how to market to this growth.',
        realtor_hook: 'Lakeland\'s explosive population growth and logistics/distribution economy make it one of Central Florida\'s most active inland listing markets — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'kissimmee',
        name: 'Kissimmee',
        county: 'Osceola',
        state: 'FL',
        zip: '34741',
        population: '80,000',
        median_price: '$349,000',
        price_trend: 'up 5%',
        avg_dom: 34,
        description: 'Kissimmee is the gateway to Walt Disney World and Florida\'s most active short-term vacation rental market — Osceola County\'s proximity to four major theme park complexes has created a unique real estate ecosystem where investor-buyers compete for vacation homes in gated resort communities like ChampionsGate, Reunion Resort, and Windsor at Westside alongside traditional residential buyers seeking affordability near Orlando.',
        neighborhoods: 'ChampionsGate, Reunion Resort, Celebration border, Lake Nona border, Windsor Hills, Storey Lake, Margaritaville Resort, Neptune',
        nearby: 'Orlando, St. Cloud, Davenport, Haines City, Celebration',
        seller_hook: 'Kissimmee\'s short-term rental income potential attracts investor buyers nationwide — RealtorFinder helps you find an Osceola agent who knows how to market your property\'s full revenue story.',
        realtor_hook: 'Kissimmee\'s vacation rental economy and consistent theme park-driven buyer demand make it one of Florida\'s most unique and active listing markets — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'the-villages',
        name: 'The Villages',
        county: 'Sumter',
        state: 'FL',
        zip: '32159',
        population: '130,000',
        median_price: '$369,000',
        price_trend: 'up 3%',
        avg_dom: 38,
        description: 'The Villages is the largest retirement community in the world — a master-planned city in Sumter, Lake, and Marion counties that has grown to 130,000+ residents with 50+ golf courses, 100+ recreation centers, and three iconic town squares where golf carts outnumber cars. Its self-contained lifestyle, exceptional amenities, and active adult culture attract retirees from across the country seeking community, activity, and Florida sunshine.',
        neighborhoods: 'Spanish Springs Town Square, Lake Sumter Landing, Brownwood Paddock Square, Fenney, Chitty Farms, Southern Oaks, De La Vista, Bridgeport',
        nearby: 'Leesburg, Ocala, Wildwood, Lady Lake, Fruitland Park',
        seller_hook: 'The Villages\'s national reputation and built-in active-adult buyer pool mean well-priced homes attract serious buyers quickly — RealtorFinder connects you with agents who specialize in this unique market.',
        realtor_hook: 'The Villages is the world\'s largest retirement community and one of Florida\'s most active real estate markets by volume — join RealtorFinder to connect with motivated sellers in this exceptional destination.',
    },
];
