// cities/fl.js — Florida city data for SEO landing pages

module.exports = [
    {
        slug: 'miami',
        name: 'Miami',
        county: 'Miami-Dade',
        state: 'FL',
        zip: '33101',
        population: '454,000',
        median_price: '$649,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Miami is the financial capital of Latin America and one of the world\'s most cosmopolitan real estate markets — a city where Brickell\'s luxury towers, Coconut Grove\'s canopied estates, and Little Havana\'s vibrant streetscapes attract international buyers, domestic migrants, and investors in equal measure.',
        neighborhoods: 'Brickell, Wynwood, Coconut Grove, Coral Gables border, Little Havana, Edgewater, Design District, Overtown',
        nearby: 'Coral Gables, Hialeah, Miami Beach, Doral, Homestead',
        seller_hook: 'Miami\'s international buyer pool and luxury demand create strong competition for well-priced listings — let top South Florida agents compete on RealtorFinder to earn your business.',
        realtor_hook: 'Miami\'s global buyer pool and multi-billion-dollar development pipeline make it one of the highest-value listing markets in the country — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'orlando',
        name: 'Orlando',
        county: 'Orange',
        state: 'FL',
        zip: '32801',
        population: '320,000',
        median_price: '$369,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'Orlando is Florida\'s fastest-growing major metro — a tourism and tech powerhouse that has added hundreds of thousands of residents over the past decade, driven by no state income tax, job growth in healthcare and simulation/defense technology, and a lifestyle that draws families and young professionals from across the country.',
        neighborhoods: 'Downtown Orlando, College Park, Winter Park border, Baldwin Park, Lake Nona, Dr. Phillips, Mills 50',
        nearby: 'Kissimmee, Sanford, Altamonte Springs, Maitland, Ocoee',
        seller_hook: 'Orlando\'s explosive population growth and diverse buyer pool make it a seller\'s market — let competing Central Florida realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Orlando\'s steady population influx and diverse housing demand make it one of Florida\'s most active listing markets — RealtorFinder keeps your pipeline full.',
    },
    {
        slug: 'tampa',
        name: 'Tampa',
        county: 'Hillsborough',
        state: 'FL',
        zip: '33601',
        population: '407,000',
        median_price: '$389,000',
        price_trend: 'up 5%',
        avg_dom: 31,
        description: 'Tampa has transformed from a regional port city into one of America\'s most desirable metro areas — a city where Ybor City\'s historic brick streets, Channelside\'s waterfront development, and South Tampa\'s tree-lined bungalow neighborhoods attract buyers from across the country seeking Florida lifestyle without Miami\'s price tag.',
        neighborhoods: 'Hyde Park, Ybor City, Seminole Heights, Channelside, Palma Ceia, Davis Islands, Westchase',
        nearby: 'St. Petersburg, Clearwater, Brandon, Temple Terrace, Plant City',
        seller_hook: 'Tampa\'s surge in buyer demand from northern transplants creates real competition for your listing — RealtorFinder puts the best Tampa Bay agents in a race to represent your home.',
        realtor_hook: 'Tampa\'s population boom and diverse housing demand make it one of Florida\'s strongest listing markets — RealtorFinder connects you with motivated sellers across Hillsborough County.',
    },
    {
        slug: 'jacksonville',
        name: 'Jacksonville',
        county: 'Duval',
        state: 'FL',
        zip: '32099',
        population: '949,000',
        median_price: '$299,000',
        price_trend: 'up 6%',
        avg_dom: 32,
        description: 'Jacksonville is Florida\'s largest city by land area and one of its most affordable — a sprawling coastal city with a strong military presence, a growing financial and logistics sector, and diverse neighborhoods from San Marco\'s historic charm to Riverside\'s arts district to the rapidly developing Southside corridor.',
        neighborhoods: 'San Marco, Riverside, Avondale, Southside, Mandarin, Ortega, Springfield, Baymeadows',
        nearby: 'Orange Park, Fleming Island, Fernandina Beach, St. Augustine, Ponte Vedra Beach',
        seller_hook: 'Jacksonville\'s affordability and growing population attract a broad buyer pool — let competitive Duval County realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Jacksonville\'s large population and geographic spread create high listing volume across diverse neighborhoods — RealtorFinder gives you direct access to motivated sellers.',
    },
    {
        slug: 'st-petersburg',
        name: 'St. Petersburg',
        county: 'Pinellas',
        state: 'FL',
        zip: '33701',
        population: '265,000',
        median_price: '$419,000',
        price_trend: 'up 7%',
        avg_dom: 27,
        description: 'St. Petersburg has emerged as one of Florida\'s most culturally vibrant cities — a waterfront community on Tampa Bay with a world-class museum district anchored by the Salvador Dalí Museum, a thriving craft brewery scene, and walkable downtown neighborhoods that have attracted a wave of remote workers and young professionals.',
        neighborhoods: 'Downtown St. Pete, Old Northeast, Historic Kenwood, Crescent Lake, Roser Park, Coquina Key, Shore Acres',
        nearby: 'Clearwater, Largo, Pinellas Park, Tampa, Dunedin',
        seller_hook: 'St. Pete\'s cultural renaissance and waterfront appeal are drawing buyers from across the country — RealtorFinder puts top Pinellas County agents in competition to represent your home.',
        realtor_hook: 'St. Petersburg\'s rising profile as a lifestyle destination creates consistent buyer demand from nationwide relocators — RealtorFinder connects you with motivated sellers in this market.',
    },
    {
        slug: 'hialeah',
        name: 'Hialeah',
        county: 'Miami-Dade',
        state: 'FL',
        zip: '33010',
        population: '224,000',
        median_price: '$449,000',
        price_trend: 'up 8%',
        avg_dom: 25,
        description: 'Hialeah is Miami-Dade\'s largest suburb and the heart of South Florida\'s Cuban-American community — a densely populated, culturally rich city with strong community roots, Tri-Rail access, and home prices that represent real value compared to Miami proper, attracting both first-time buyers and investors priced out of closer-in neighborhoods.',
        neighborhoods: 'Hialeah Gardens border, East Hialeah, Country Club area, Palm Springs North, Miami Lakes border',
        nearby: 'Miami Lakes, Opa-Locka, North Miami, Doral, Miami',
        seller_hook: 'Hialeah\'s strong community ties and rising values attract committed buyers — let competitive Miami-Dade realtors on RealtorFinder fight to earn the right to sell your home.',
        realtor_hook: 'Hialeah\'s dense population and strong appreciation make it one of Miami-Dade\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'tallahassee',
        name: 'Tallahassee',
        county: 'Leon',
        state: 'FL',
        zip: '32301',
        population: '196,000',
        median_price: '$259,000',
        price_trend: 'up 6%',
        avg_dom: 34,
        description: 'Tallahassee is Florida\'s capital and university city — home to Florida State University, FAMU, and a large state government workforce that creates steady, recession-resistant housing demand in a market that remains significantly more affordable than coastal Florida despite strong long-term appreciation.',
        neighborhoods: 'Midtown, Frenchtown, Killearn Estates, SouthWood, Myers Park, Betton Hills, College Town',
        nearby: 'Thomasville GA, Quincy, Crawfordville, Monticello',
        seller_hook: 'Tallahassee\'s stable university and government buyer base ensures consistent demand — RealtorFinder puts motivated local agents in competition to represent your home.',
        realtor_hook: 'Tallahassee\'s FSU and state government workforce creates recession-resistant buyer demand — RealtorFinder connects you with sellers in Florida\'s capital city.',
    },
    {
        slug: 'fort-lauderdale',
        name: 'Fort Lauderdale',
        county: 'Broward',
        state: 'FL',
        zip: '33301',
        population: '182,000',
        median_price: '$549,000',
        price_trend: 'up 7%',
        avg_dom: 29,
        description: 'Fort Lauderdale is the crown of Broward County — a sophisticated waterfront city with more miles of navigable waterways than Venice, a revitalized Las Olas Boulevard, and a real estate market powered by both Florida migration demand and international buyers seeking a South Florida lifestyle at a slight discount to Miami.',
        neighborhoods: 'Las Olas Isles, Victoria Park, Colee Hammock, Flagler Village, Rio Vista, Wilton Manors border',
        nearby: 'Hollywood, Pompano Beach, Deerfield Beach, Boca Raton, Coral Springs',
        seller_hook: 'Fort Lauderdale\'s waterfront lifestyle draws buyers with resources and conviction — let top Broward County agents compete on RealtorFinder to bring you the best sale.',
        realtor_hook: 'Fort Lauderdale\'s waterway lifestyle and proximity to Miami create a premium listing market with strong buyer demand — RealtorFinder gives you direct access to motivated sellers.',
    },
    {
        slug: 'port-st-lucie',
        name: 'Port St. Lucie',
        county: 'St. Lucie',
        state: 'FL',
        zip: '34984',
        population: '228,000',
        median_price: '$339,000',
        price_trend: 'up 8%',
        avg_dom: 31,
        description: 'Port St. Lucie is Florida\'s Treasure Coast boomtown — one of the fastest-growing large cities in the nation, drawing families and retirees from the Northeast with affordable home prices, new master-planned communities, and a lifestyle that combines suburban comfort with proximity to the Atlantic Ocean.',
        neighborhoods: 'Tradition, PGA Village, River Park, St. Lucie West, Torino, Tesoro',
        nearby: 'Stuart, Fort Pierce, Palm Beach Gardens, Okeechobee',
        seller_hook: 'Port St. Lucie\'s explosive growth keeps buyer demand consistently strong — RealtorFinder puts competitive Treasure Coast agents in a race to represent your home.',
        realtor_hook: 'Port St. Lucie\'s rapid growth and affordable price points create high listing volume and motivated buyers — RealtorFinder connects you with sellers in this booming market.',
    },
    {
        slug: 'cape-coral',
        name: 'Cape Coral',
        county: 'Lee',
        state: 'FL',
        zip: '33990',
        population: '214,000',
        median_price: '$359,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Cape Coral is the canal capital of the world — a planned city with over 400 miles of navigable waterways, a rapidly growing population, and a real estate market popular with Midwest and Northeast buyers seeking waterfront properties and a Gulf Coast lifestyle at prices well below Fort Myers and Naples.',
        neighborhoods: 'Southwest Cape Coral, Pelican, Pine Island Corridor, NE Cape Coral, Surfside',
        nearby: 'Fort Myers, North Fort Myers, Matlacha, Lee County barrier islands',
        seller_hook: 'Cape Coral\'s waterfront lifestyle attracts motivated buyers from across the country — let competing Southwest Florida realtors on RealtorFinder earn the right to sell your home.',
        realtor_hook: 'Cape Coral\'s 400+ miles of canals create a unique buyer segment that RealtorFinder helps you reach — connect with motivated sellers in this distinctive market.',
    },
    {
        slug: 'gainesville',
        name: 'Gainesville',
        county: 'Alachua',
        state: 'FL',
        zip: '32601',
        population: '141,000',
        median_price: '$279,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Gainesville is home to the University of Florida and UF Health Shands — a college town with a vibrant arts scene, one of Florida\'s most walkable downtowns, and a real estate market driven by faculty, healthcare professionals, and a large student population that creates consistent rental and purchase demand.',
        neighborhoods: 'Duckpond, Midtown, Depot Park area, Haile Plantation, Duck Pond, University Avenue corridor',
        nearby: 'Newberry, High Springs, Micanopy, Ocala, Lake City',
        seller_hook: 'Gainesville\'s university and healthcare buyer base keeps demand steady year-round — RealtorFinder puts motivated local agents in competition to represent your home.',
        realtor_hook: 'Gainesville\'s UF-anchored economy and growing healthcare sector create reliable buyer demand — RealtorFinder connects you with sellers in this stable Florida market.',
    },
    {
        slug: 'sarasota',
        name: 'Sarasota',
        county: 'Sarasota',
        state: 'FL',
        zip: '34230',
        population: '58,000',
        median_price: '$499,000',
        price_trend: 'up 6%',
        avg_dom: 32,
        description: 'Sarasota is Florida\'s cultural capital — a sophisticated Gulf Coast city with world-class arts institutions including the Ringling Museum, Siesta Key\'s award-winning white sand beaches, and a real estate market that draws retiring professionals and arts patrons from across the nation seeking an elevated Florida lifestyle.',
        neighborhoods: 'Downtown Sarasota, Rosemary District, Laurel Park, McClellan Park, Osprey area, Lakewood Ranch border',
        nearby: 'Bradenton, Venice, Osprey, North Port, Englewood',
        seller_hook: 'Sarasota\'s cultural prestige and beach access command buyer loyalty — let top Gulf Coast agents compete on RealtorFinder to bring you the best possible sale.',
        realtor_hook: 'Sarasota\'s affluent retirement and arts community creates a high-value listing market with motivated buyers — RealtorFinder connects you with sellers in Florida\'s cultural capital.',
    },
];
