// cities/ga.js — Georgia city data for SEO landing pages

module.exports = [
    {
        slug: 'atlanta',
        name: 'Atlanta',
        county: 'Fulton',
        state: 'GA',
        zip: '30301',
        population: '498,000',
        median_price: '$450,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'Atlanta is the capital of the New South and one of America\'s fastest-growing major metros — a corporate relocation magnet home to Coca-Cola, Delta, and CNN where in-town neighborhoods like Inman Park, Old Fourth Ward, and Poncey-Highland deliver urban walkability and the BeltLine connects them all into one vibrant corridor.',
        neighborhoods: 'Inman Park, Old Fourth Ward, Midtown, Poncey-Highland, Grant Park, East Atlanta, West End, Kirkwood',
        nearby: 'Decatur, Sandy Springs, Marietta, Dunwoody, Smyrna',
        seller_hook: 'Atlanta\'s booming corporate migration and BeltLine-driven neighborhood demand drive fierce buyer competition — RealtorFinder puts top Atlanta agents in a bidding war to earn your listing.',
        realtor_hook: 'Atlanta\'s Fortune 500 economy and in-town neighborhood revival create one of the Southeast\'s strongest listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'buckhead-atlanta',
        name: 'Buckhead',
        county: 'Fulton',
        state: 'GA',
        zip: '30305',
        population: '81,000',
        median_price: '$900,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Buckhead is Atlanta\'s most prestigious address — an upscale district of gracious estates, luxury high-rises, and designer boutiques along Peachtree Road where Tuxedo Park and Chastain Park anchor some of the finest residential real estate in the Southeast and corporate executives anchor a relentlessly high-end buyer pool.',
        neighborhoods: 'Tuxedo Park, Chastain Park, Garden Hills, West Paces Ferry, Peachtree Hills, Brookwood Hills',
        nearby: 'Sandy Springs, Vinings, Brookhaven, Midtown Atlanta, Dunwoody',
        seller_hook: 'Buckhead\'s luxury buyer demand and prestige address command premium prices — let Atlanta\'s top luxury agents compete on RealtorFinder to achieve your maximum sale.',
        realtor_hook: 'Buckhead\'s estate market and high-net-worth buyer pool deliver the Southeast\'s most lucrative residential commissions — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'decatur-ga',
        name: 'Decatur',
        county: 'DeKalb',
        state: 'GA',
        zip: '30030',
        population: '24,000',
        median_price: '$530,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Decatur is one of Atlanta\'s most beloved intown suburbs — a walkable, progressive city of bungalows, craftsmen, and new construction where Agnes Scott College, a thriving square, and some of metro Atlanta\'s best restaurants and schools combine to create extraordinary buyer demand from families and young professionals alike.',
        neighborhoods: 'Downtown Decatur, Oakhurst, Winnona Park, Westchester Hills, Leafmore, Midway Woods',
        nearby: 'Atlanta, Avondale Estates, Tucker, Druid Hills, Candler Park',
        seller_hook: 'Decatur\'s walkability, top schools, and national recognition as a great place to live mean buyers compete fiercely — RealtorFinder puts top DeKalb agents in a race for your listing.',
        realtor_hook: 'Decatur\'s perennial top-ranked livability attracts buyers with strong purchase intent and deep budgets — RealtorFinder connects you with motivated sellers in this coveted market.',
    },
    {
        slug: 'sandy-springs',
        name: 'Sandy Springs',
        county: 'Fulton',
        state: 'GA',
        zip: '30328',
        population: '108,000',
        median_price: '$650,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Sandy Springs is Atlanta\'s premier northern suburb — a well-managed, affluent city with top-rated schools, UPS and Intercontinental Exchange headquarters, and a Perimeter Center office district that fuels strong corporate relocation buyer demand from executives and professionals choosing the Atlanta metro.',
        neighborhoods: 'Perimeter Center, Heards Ferry, Hammond Park, Glenridge, Dunwoody border, Abernathy Road corridor',
        nearby: 'Dunwoody, Roswell, Brookhaven, Atlanta, Marietta',
        seller_hook: 'Sandy Springs\' corporate headquarters cluster and top-ranked schools drive premium buyer demand — let top North Fulton realtors compete on RealtorFinder to maximize your sale.',
        realtor_hook: 'Sandy Springs\' Fortune 500 employer base and school reputation create a consistent premium listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'alpharetta',
        name: 'Alpharetta',
        county: 'Fulton',
        state: 'GA',
        zip: '30009',
        population: '67,000',
        median_price: '$650,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Alpharetta is metro Atlanta\'s technology hub — the "Technology City of the South" hosting over 700 tech companies along the Georgia 400 corridor, with the revitalized Alpharetta City Center, Avalon mixed-use district, and top-ranked Fulton County schools drawing families and tech professionals from across the country.',
        neighborhoods: 'Alpharetta City Center, Avalon, Milton border, Windward, Crabapple, Downtown Alpharetta',
        nearby: 'Milton, Roswell, Johns Creek, Cumming, Sandy Springs',
        seller_hook: 'Alpharetta\'s tech economy and Avalon-driven lifestyle premium attract buyers with strong purchasing power — let competing North Fulton agents fight on RealtorFinder to earn your listing.',
        realtor_hook: 'Alpharetta\'s technology corridor and top school ratings create one of North Atlanta\'s most active premium listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'roswell-ga',
        name: 'Roswell',
        county: 'Fulton',
        state: 'GA',
        zip: '30075',
        population: '94,000',
        median_price: '$580,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Roswell is one of metro Atlanta\'s most desirable suburbs — a historic city on the Chattahoochee River with a charming Canton Street restaurant district, top-ranked public schools, and neighborhoods that attract Atlanta professionals and corporate relocatees seeking Southern small-town character within a highly rated school district.',
        neighborhoods: 'Historic Roswell, Canton Street corridor, Horseshoe Bend, Willow Springs, Martins Landing, Vickery',
        nearby: 'Alpharetta, Sandy Springs, Marietta, Milton, Woodstock',
        seller_hook: 'Roswell\'s Canton Street charm and top schools generate strong buyer loyalty — let competing North Fulton realtors on RealtorFinder fight to earn the right to sell your home.',
        realtor_hook: 'Roswell\'s school ratings and historic character create a consistent premium buyer pool — RealtorFinder connects you with motivated sellers in this sought-after North Fulton market.',
    },
    {
        slug: 'milton-ga',
        name: 'Milton',
        county: 'Fulton',
        state: 'GA',
        zip: '30004',
        population: '40,000',
        median_price: '$900,000',
        price_trend: 'up 6%',
        avg_dom: 35,
        description: 'Milton is one of Georgia\'s wealthiest cities and a pastoral escape within metro Atlanta — an equestrian community of estate homes on large wooded lots where the Crabapple village district, top-ranked schools, and proximity to Alpharetta\'s tech corridor attract executives and families seeking luxury and land within 30 miles of downtown.',
        neighborhoods: 'Crabapple, Birmingham, Deerfield, Providence, White Columns, Batesville',
        nearby: 'Alpharetta, Roswell, Woodstock, Canton, Cumming',
        seller_hook: 'Milton\'s estate market and scarcity of luxury inventory attract high-net-worth buyers — let top North Atlanta agents compete on RealtorFinder to achieve your maximum sale price.',
        realtor_hook: 'Milton\'s estate market and affluent buyer pool deliver North Atlanta\'s most rewarding residential commissions — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'marietta-ga',
        name: 'Marietta',
        county: 'Cobb',
        state: 'GA',
        zip: '30060',
        population: '60,000',
        median_price: '$420,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Marietta is the heart of Cobb County — a historic city anchored by a beautiful antebellum square, Kennesaw State University, and Dobbins Air Reserve Base where walkable neighborhoods, strong school districts, and easy access to Atlanta via I-75 make it a top choice for families seeking metro living at accessible prices.',
        neighborhoods: 'Historic Marietta Square, Whitlock, East Marietta, Sandtown, Kennesaw border, Murdock',
        nearby: 'Kennesaw, Smyrna, Roswell, Acworth, Atlanta',
        seller_hook: 'Marietta\'s historic character and accessible pricing attract a broad buyer pool — let competing Cobb County agents on RealtorFinder drive your sale to the best possible outcome.',
        realtor_hook: 'Marietta\'s diverse price range and strong school reputation generate consistent listing activity — RealtorFinder connects you with motivated sellers in Cobb County.',
    },
    {
        slug: 'smyrna-ga',
        name: 'Smyrna',
        county: 'Cobb',
        state: 'GA',
        zip: '30080',
        population: '57,000',
        median_price: '$420,000',
        price_trend: 'up 8%',
        avg_dom: 24,
        description: 'Smyrna is one of metro Atlanta\'s hottest in-town suburbs — a rapidly transforming city where the Village Green pedestrian district, SunTrust Park\'s Battery Atlanta development, and I-285 access have made it a magnet for young professionals and families priced out of Buckhead and Sandy Springs seeking walkability at accessible prices.',
        neighborhoods: 'Village Green, Vinings, Cooper Lake, Belmont Hills, Spring Road corridor, Jonquil neighborhood',
        nearby: 'Marietta, Vinings, Atlanta, Sandy Springs, Mableton',
        seller_hook: 'Smyrna\'s Battery Atlanta energy and rapid transformation drive fierce buyer competition — let top Cobb County agents on RealtorFinder compete for the right to sell your home.',
        realtor_hook: 'Smyrna\'s fast-appreciating market and young professional buyer influx create one of metro Atlanta\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'kennesaw',
        name: 'Kennesaw',
        county: 'Cobb',
        state: 'GA',
        zip: '30144',
        population: '34,000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Kennesaw is a fast-growing Cobb County suburb best known for Kennesaw State University, the historic Civil War battlefield, and a pro-business environment that has attracted distribution and manufacturing employers — delivering affordable family housing with strong schools, easy I-75 access, and a consistently appreciating market.',
        neighborhoods: 'Downtown Kennesaw, Legacy Park, Brookstone, Kennesaw Mountain area, Stilesboro, Shiloh Hills',
        nearby: 'Marietta, Acworth, Woodstock, Canton, Roswell',
        seller_hook: 'Kennesaw\'s university workforce and accessible pricing attract a strong buyer pool — let competing Cobb County realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Kennesaw\'s KSU employment base and family-friendly market create consistent listing activity — RealtorFinder connects you with motivated sellers in north Cobb County.',
    },
    {
        slug: 'acworth',
        name: 'Acworth',
        county: 'Cherokee',
        state: 'GA',
        zip: '30101',
        population: '22,000',
        median_price: '$360,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Acworth is a charming lakeside community on Lake Acworth and Lake Allatoona — a historic Cobb-Cherokee border city with a walkable antebellum downtown, excellent recreation, and a steadily appreciating market that attracts Atlanta commuters and lake lifestyle buyers seeking affordability paired with outdoor amenity.',
        neighborhoods: 'Downtown Acworth, Lake Acworth Shores, Governors Towne Club, Baker Road corridor, McEver Road area',
        nearby: 'Kennesaw, Woodstock, Canton, Marietta, Dallas',
        seller_hook: 'Acworth\'s lakeside lifestyle and historic downtown draw buyers from across the metro — let competing north metro agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Acworth\'s lake amenity and commuter-friendly location generate steady buyer traffic — RealtorFinder connects you with motivated sellers in this growing market.',
    },
    {
        slug: 'peachtree-city',
        name: 'Peachtree City',
        county: 'Fayette',
        state: 'GA',
        zip: '30269',
        population: '38,000',
        median_price: '$520,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'Peachtree City is metro Atlanta\'s most distinctive planned community — a master-planned city with 100 miles of golf cart paths connecting neighborhoods, parks, and shopping where Fayette County\'s top-ranked schools, the Trilith Studios film campus, and a strong sense of community make it uniquely desirable for families.',
        neighborhoods: 'Wilksmoor, Kedron, Braelinn, Glenloch, Huddleston Pond, Kelly Drive corridor',
        nearby: 'Newnan, Fayetteville, Tyrone, Sharpsburg, Senoia',
        seller_hook: 'Peachtree City\'s golf cart lifestyle and top Fayette schools create a fiercely loyal buyer pool — let competing south metro agents on RealtorFinder earn the right to sell your home.',
        realtor_hook: 'Peachtree City\'s unique planned community appeal and family-driven market create consistent premium listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'newnan-ga',
        name: 'Newnan',
        county: 'Coweta',
        state: 'GA',
        zip: '30263',
        population: '43,000',
        median_price: '$360,000',
        price_trend: 'up 8%',
        avg_dom: 27,
        description: 'Newnan is one of Georgia\'s fastest-growing cities and a beautifully preserved antebellum town — a Coweta County seat with a stunning courthouse square, rapid development driven by I-85 corridor growth and Trilith Studios proximity, and home prices that attract buyers priced out of Peachtree City and Fayette County.',
        neighborhoods: 'Historic Newnan, Summergrove, Botanical Garden area, White Oak, Shenandoah, Arbor Springs',
        nearby: 'Peachtree City, Fayetteville, Sharpsburg, Senoia, LaGrange',
        seller_hook: 'Newnan\'s historic charm and rapid growth drive strong appreciation and buyer demand — let competing Coweta County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Newnan\'s I-85 growth corridor and historic appeal attract buyers from Atlanta and beyond — RealtorFinder connects you with motivated sellers in this fast-appreciating market.',
    },
    {
        slug: 'fayetteville-ga',
        name: 'Fayetteville',
        county: 'Fayette',
        state: 'GA',
        zip: '30214',
        population: '17,000',
        median_price: '$400,000',
        price_trend: 'up 7%',
        avg_dom: 29,
        description: 'Fayetteville is the seat of Fayette County and a beneficiary of the Trilith Studios film campus boom — a small city with top-ranked schools, a charming historic courthouse square, and a rapidly expanding residential market driven by production professionals and families relocating from Atlanta for Fayette County\'s exceptional school system.',
        neighborhoods: 'Trilith, Bennett\'s Mill, Whitewater area, Banks Road corridor, Beauregard, East Fayetteville',
        nearby: 'Peachtree City, Newnan, Tyrone, Senoia, McDonough',
        seller_hook: 'Fayetteville\'s Trilith-driven boom and top Fayette schools make it one of Georgia\'s hottest markets — let competing agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Fayetteville\'s Trilith Studios growth and school reputation drive premium buyer demand — RealtorFinder connects you with motivated sellers in Fayette County.',
    },
    {
        slug: 'savannah',
        name: 'Savannah',
        county: 'Chatham',
        state: 'GA',
        zip: '31401',
        population: '147,000',
        median_price: '$420,000',
        price_trend: 'up 9%',
        avg_dom: 27,
        description: 'Savannah is one of America\'s most beautiful cities — a moss-draped coastal destination where 22 landmark squares, antebellum mansions, and the thriving Starland District arts scene draw buyers seeking Southern charm, strong tourism economics, and short-term rental investment backed by one of the nation\'s most visited historic districts.',
        neighborhoods: 'Historic District, Victorian District, Ardsley Park, Midtown Savannah, Starland District, Isle of Hope, Sandfly',
        nearby: 'Pooler, Rincon, Port Wentworth, Tybee Island, Hilton Head SC',
        seller_hook: 'Savannah\'s national profile and tourism economy attract buyers with strong purchase intent — let top Coastal Georgia agents compete on RealtorFinder to maximize your sale.',
        realtor_hook: 'Savannah\'s historic prestige and short-term rental potential attract buyers with significant budgets — RealtorFinder connects you with motivated sellers in this iconic market.',
    },
    {
        slug: 'pooler-ga',
        name: 'Pooler',
        county: 'Chatham',
        state: 'GA',
        zip: '31322',
        population: '28,000',
        median_price: '$350,000',
        price_trend: 'up 9%',
        avg_dom: 25,
        description: 'Pooler is Savannah\'s fastest-growing suburb — a rapidly expanding city near Savannah/Hilton Head International Airport where new master-planned communities, strong retail corridors along Pooler Parkway, and the overflow demand from Savannah\'s expensive historic district combine to create one of coastal Georgia\'s most active new-construction markets.',
        neighborhoods: 'Godley Station, West Chatham, Rice Hope, Quacco Road corridor, Pooler Parkway district',
        nearby: 'Savannah, Rincon, Port Wentworth, Guyton, Richmond Hill',
        seller_hook: 'Pooler\'s explosive growth and Savannah overflow demand drive strong appreciation — let competing Chatham County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Pooler\'s rapid expansion and new-construction pipeline create a high-volume listing market — RealtorFinder connects you with motivated sellers in coastal Georgia\'s growth corridor.',
    },
    {
        slug: 'augusta-ga',
        name: 'Augusta',
        county: 'Richmond',
        state: 'GA',
        zip: '30901',
        population: '202,000',
        median_price: '$280,000',
        price_trend: 'up 8%',
        avg_dom: 30,
        description: 'Augusta is home to the Masters Tournament, Fort Eisenhower, and the Medical College of Georgia — a mid-sized city with a strong military and healthcare employment base, highly affordable home prices, and a real estate market that outperforms its size thanks to consistent institutional buyer demand and growing cybersecurity industry investment.',
        neighborhoods: 'Summerville, Harrisburg, Olde Town Augusta, Barton Village, West Augusta, National Hills, Grovetown border',
        nearby: 'Martinez, Evans, Grovetown, Aiken SC, North Augusta SC',
        seller_hook: 'Augusta\'s military and medical buyer base ensures consistent demand — let competing local realtors on RealtorFinder fight for the right to represent your home.',
        realtor_hook: 'Augusta\'s Fort Eisenhower and MCG workforce create steady buyer demand — RealtorFinder connects you with motivated sellers in this stable Georgia market.',
    },
    {
        slug: 'athens-ga',
        name: 'Athens',
        county: 'Clarke',
        state: 'GA',
        zip: '30601',
        population: '127,000',
        median_price: '$320,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Athens is home to the University of Georgia and one of the South\'s most celebrated music and food scenes — a college city with a vibrant downtown, strong creative economy, and a real estate market driven by UGA faculty, St. Mary\'s healthcare professionals, and Athens\' growing appeal as a lifestyle destination for buyers relocating from Atlanta.',
        neighborhoods: 'Five Points, Normaltown, Boulevard Historic District, East Athens, Cobbham, Waverly Hills',
        nearby: 'Commerce, Winder, Bogart, Jefferson, Madison',
        seller_hook: 'Athens\' UGA-driven buyer base and growing lifestyle profile drive consistent demand — RealtorFinder puts motivated local agents in competition to represent your home.',
        realtor_hook: 'Athens\' university workforce and growing Atlanta-overflow appeal create steady listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'gainesville-ga',
        name: 'Gainesville',
        county: 'Hall',
        state: 'GA',
        zip: '30501',
        population: '44,000',
        median_price: '$340,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Gainesville is the "Poultry Capital of the World" and Hall County\'s economic hub on the shores of Lake Lanier — a fast-growing city with a strong manufacturing and healthcare employment base, a vibrant downtown revitalization, and a real estate market driven by lake lifestyle buyers and Atlanta commuters seeking affordability.',
        neighborhoods: 'Downtown Gainesville, Longstreet Hills, Brenau area, Riverside Drive corridor, Holiday Hills',
        nearby: 'Cumming, Buford, Flowery Branch, Oakwood, Clermont',
        seller_hook: 'Gainesville\'s Lake Lanier access and rapid growth attract buyers from across the metro — let competing Hall County agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Gainesville\'s Lake Lanier lifestyle and fast-growing population create consistent listing demand — RealtorFinder connects you with motivated sellers in northeast Georgia.',
    },
    {
        slug: 'duluth-ga',
        name: 'Duluth',
        county: 'Gwinnett',
        state: 'GA',
        zip: '30096',
        population: '31,000',
        median_price: '$430,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Duluth is one of Gwinnett County\'s most desirable cities — a diverse, upscale suburb with a thriving downtown along Sugarloaf Parkway, home to Gas South Arena and top-rated schools where a large Korean-American business community and strong international flavor have created a uniquely cosmopolitan suburb with outstanding dining and commerce.',
        neighborhoods: 'Downtown Duluth, Sugarloaf, Peachtree Corners border, Chattahoochee River area, Berkeley Lake',
        nearby: 'Johns Creek, Peachtree Corners, Suwanee, Lawrenceville, Alpharetta',
        seller_hook: 'Duluth\'s diverse buyer pool and Sugarloaf corridor desirability drive consistent strong demand — let competing Gwinnett agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Duluth\'s cosmopolitan character and premium Gwinnett schools attract buyers with strong purchasing power — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'cumming-ga',
        name: 'Cumming',
        county: 'Forsyth',
        state: 'GA',
        zip: '30040',
        population: '8,000',
        median_price: '$460,000',
        price_trend: 'up 8%',
        avg_dom: 25,
        description: 'Cumming is the seat of Forsyth County — one of the fastest-growing and highest-income counties in the nation — where top-ranked schools, Lake Lanier access, and a booming mixed-use development scene along GA-400 have made it a top destination for Atlanta families seeking excellent schools, outdoor recreation, and new-construction options.',
        neighborhoods: 'Polo Golf and Country Club, Windermere, The Polo Fields, Coal Mountain, Sharon Road corridor',
        nearby: 'Alpharetta, Milton, Gainesville, Dawsonville, Suwanee',
        seller_hook: 'Cumming\'s top-ranked Forsyth County schools and Lake Lanier access drive fierce buyer competition — let top north metro agents on RealtorFinder compete to earn your listing.',
        realtor_hook: 'Cumming\'s one of the nation\'s fastest-growing counties and delivers consistent premium listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'woodstock-ga',
        name: 'Woodstock',
        county: 'Cherokee',
        state: 'GA',
        zip: '30188',
        population: '36,000',
        median_price: '$400,000',
        price_trend: 'up 8%',
        avg_dom: 26,
        description: 'Woodstock is Cherokee County\'s crown jewel — a rapidly growing city with one of metro Atlanta\'s most celebrated downtown revitalizations featuring award-winning restaurants, live music, and festivals, paired with top-rated schools and accessible pricing that has made it a consistent top-ten list pick for best places to live in Georgia.',
        neighborhoods: 'Downtown Woodstock, Eagle Watch, Towne Lake, River Green, Woodstock Commons',
        nearby: 'Canton, Kennesaw, Roswell, Acworth, Milton',
        seller_hook: 'Woodstock\'s celebrated downtown and top Cherokee schools drive strong buyer demand — let competing north metro agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Woodstock\'s award-winning downtown revival and family-friendly market create one of north Atlanta\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'canton-ga',
        name: 'Canton',
        county: 'Cherokee',
        state: 'GA',
        zip: '30114',
        population: '32,000',
        median_price: '$370,000',
        price_trend: 'up 8%',
        avg_dom: 27,
        description: 'Canton is the Cherokee County seat and one of metro Atlanta\'s most affordable access points into a top-ranked school district — a growing city with a revitalized historic downtown, strong new construction activity, and a real estate market that attracts families and first-time buyers seeking the Cherokee County school system without the Woodstock premium.',
        neighborhoods: 'Downtown Canton, Bridgemill, Prominence, Hickory Flat, Holly Springs, Great Sky',
        nearby: 'Woodstock, Alpharetta, Acworth, Jasper, Ball Ground',
        seller_hook: 'Canton\'s Cherokee County schools and accessible pricing attract a strong and growing buyer pool — let competing agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Canton\'s fast-growing population and affordable entry point generate high listing volume — RealtorFinder connects you with motivated sellers in north Cherokee County.',
    },
    {
        slug: 'johns-creek',
        name: 'Johns Creek',
        county: 'Fulton',
        state: 'GA',
        zip: '30097',
        population: '82,000',
        median_price: '$580,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Johns Creek is one of Georgia\'s wealthiest cities and consistently ranks among the best places to live in the United States — an affluent Fulton County suburb with nationally recognized schools, a large and vibrant Asian-American community, and a technology and healthcare professional workforce that sustains one of metro Atlanta\'s strongest premium housing markets.',
        neighborhoods: 'Technology Park, State Bridge corridor, Medlock Bridge, Country Club of the South, St. Ives',
        nearby: 'Alpharetta, Duluth, Suwanee, Cumming, Roswell',
        seller_hook: 'Johns Creek\'s top national rankings and premier school system drive exceptional buyer demand — let competing North Fulton agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Johns Creek\'s wealth concentration and nationally ranked schools create one of metro Atlanta\'s most valuable listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'dunwoody',
        name: 'Dunwoody',
        county: 'DeKalb',
        state: 'GA',
        zip: '30338',
        population: '51,000',
        median_price: '$530,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Dunwoody is a prestigious DeKalb County suburb anchored by Perimeter Center — one of the Southeast\'s largest office and retail corridors — where State Farm\'s regional headquarters, top-rated schools, and a charming village district combine to create strong corporate relocation buyer demand and one of metro Atlanta\'s most stable premium markets.',
        neighborhoods: 'Dunwoody Village, Hammond, Perimeter Center, Vermack, Mount Vernon, Wynterhall',
        nearby: 'Sandy Springs, Brookhaven, Atlanta, Chamblee, Tucker',
        seller_hook: 'Dunwoody\'s Perimeter Center employment base and village character drive consistent premium buyer demand — let competing DeKalb agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Dunwoody\'s corporate headquarters cluster and top school reputation sustain a reliable premium listing market — RealtorFinder connects you with motivated sellers.',
    },
];
