// cities/ga.js — Georgia city data for SEO landing pages

module.exports = [
    {
        slug: 'atlanta',
        name: 'Atlanta',
        county: 'Fulton',
        state: 'GA',
        zip: '30301',
        population: '498,000',
        median_price: '$399,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'Atlanta is the capital of the New South and one of America\'s fastest-growing major metros — a corporate relocation magnet home to Coca-Cola, Delta, and CNN where in-town neighborhoods like Inman Park, Old Fourth Ward, and Buckhead deliver urban lifestyle and the Beltline connects them all with remarkable walkability.',
        neighborhoods: 'Inman Park, Old Fourth Ward, Midtown, Buckhead, Grant Park, East Atlanta, West End, Kirkwood',
        nearby: 'Decatur, Sandy Springs, Marietta, Dunwoody, Smyrna',
        seller_hook: 'Atlanta\'s booming corporate migration and in-town neighborhood demand drive fierce buyer competition — RealtorFinder puts top Atlanta agents in a bidding war to earn your listing.',
        realtor_hook: 'Atlanta\'s Fortune 500 economy and Beltline-driven neighborhood revival create one of the Southeast\'s strongest listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'augusta-ga',
        name: 'Augusta',
        county: 'Richmond',
        state: 'GA',
        zip: '30901',
        population: '202,000',
        median_price: '$189,000',
        price_trend: 'up 8%',
        avg_dom: 30,
        description: 'Augusta is home to the Masters Tournament, Fort Eisenhower, and the Medical College of Georgia — a mid-sized city with a strong military and healthcare employment base, remarkably affordable home prices, and a real estate market that outperforms its size thanks to consistent institutional buyer demand.',
        neighborhoods: 'Summerville, Harrisburg, Olde Town, Barton Village, West Augusta, National Hills',
        nearby: 'Martinez, Evans, Grovetown, Aiken SC, North Augusta SC',
        seller_hook: 'Augusta\'s military and medical buyer base ensures consistent demand — let competing local realtors on RealtorFinder fight for the right to represent your home.',
        realtor_hook: 'Augusta\'s Fort Eisenhower and MCG workforce creates steady buyer demand — RealtorFinder connects you with motivated sellers in this stable Georgia market.',
    },
    {
        slug: 'columbus-ga',
        name: 'Columbus',
        county: 'Muscogee',
        state: 'GA',
        zip: '31901',
        population: '206,000',
        median_price: '$169,000',
        price_trend: 'up 7%',
        avg_dom: 32,
        description: 'Columbus is western Georgia\'s largest city, anchored by Fort Moore (formerly Fort Benning) — the largest infantry training base in the world — which creates a large, consistent military buyer and seller population and a remarkably stable housing market with affordability that draws buyers across economic cycles.',
        neighborhoods: 'Midland, Wynnton, North Columbus, Green Island Hills, Downtown Columbus',
        nearby: 'Phenix City AL, Fort Moore, Manchester, Warm Springs',
        seller_hook: 'Columbus\'s Fort Moore military community creates consistent buyer demand and reliable market timing — let competitive local agents on RealtorFinder earn your listing.',
        realtor_hook: 'Columbus\'s large military base ensures a steady pipeline of buyers and sellers — RealtorFinder connects you with motivated sellers in this consistent Georgia market.',
    },
    {
        slug: 'macon',
        name: 'Macon',
        county: 'Bibb',
        state: 'GA',
        zip: '31201',
        population: '157,000',
        median_price: '$149,000',
        price_trend: 'up 8%',
        avg_dom: 34,
        description: 'Macon is Georgia\'s most affordable mid-sized city and a rising market — a music heritage hub with the Allman Brothers legacy, Mercer University, and one of the Southeast\'s finest collections of antebellum architecture, drawing buyers and investors who recognize a market delivering strong returns at entry-level prices.',
        neighborhoods: 'Intown Macon, Ingleside, Shirley Hills, Unionville, East Macon, Pleasant Hill',
        nearby: 'Warner Robins, Byron, Forsyth, Gray, Milledgeville',
        seller_hook: 'Macon\'s 8% appreciation and rising buyer interest make now a strong time to sell — RealtorFinder puts competitive Middle Georgia agents in a race to represent your home.',
        realtor_hook: 'Macon\'s sub-$150K entry point and consistent appreciation attract investors and first-time buyers — RealtorFinder connects you with motivated sellers in this improving market.',
    },
    {
        slug: 'savannah',
        name: 'Savannah',
        county: 'Chatham',
        state: 'GA',
        zip: '31401',
        population: '147,000',
        median_price: '$329,000',
        price_trend: 'up 9%',
        avg_dom: 27,
        description: 'Savannah is one of America\'s most beautiful cities and its most photographed historic district — a moss-draped coastal city where 22 landmark squares, antebellum mansions, and the booming Starland District arts scene have made it a top destination for buyers seeking Southern charm, strong tourism economics, and short-term rental investment.',
        neighborhoods: 'Historic District, Victorian District, Ardsley Park, Midtown, Starland District, Isle of Hope, Sandfly',
        nearby: 'Pooler, Rincon, Port Wentworth, Tybee Island, Hilton Head SC',
        seller_hook: 'Savannah\'s national profile and tourism economy draw buyers with strong purchase intent — let top Coastal Georgia agents compete on RealtorFinder to maximize your sale.',
        realtor_hook: 'Savannah\'s historic prestige and short-term rental potential attract buyers with significant budgets — RealtorFinder connects you with motivated sellers in this iconic market.',
    },
    {
        slug: 'athens-ga',
        name: 'Athens',
        county: 'Clarke',
        state: 'GA',
        zip: '30601',
        population: '127,000',
        median_price: '$299,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Athens is home to the University of Georgia and one of the best live music scenes in the South — a college town with a vibrant downtown, strong creative economy, and a real estate market driven by UGA faculty, healthcare professionals, and Athens\' growing appeal as a lifestyle destination for buyers relocating from Atlanta.',
        neighborhoods: 'Five Points, Normaltown, Boulevard Historic District, East Athens, Cobbham, Watkinsville border',
        nearby: 'Commerce, Winder, Bogart, Jefferson, Madison',
        seller_hook: 'Athens\' UGA-driven buyer base and growing lifestyle profile drive consistent demand — RealtorFinder puts motivated local agents in competition to represent your home.',
        realtor_hook: 'Athens\' University of Georgia workforce and growing Atlanta-overflow appeal create steady listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'sandy-springs',
        name: 'Sandy Springs',
        county: 'Fulton',
        state: 'GA',
        zip: '30328',
        population: '108,000',
        median_price: '$499,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Sandy Springs is Atlanta\'s premier northern suburb — a well-managed, affluent city with top-rated schools, UPS and Intercontinental Exchange headquarters, and a Perimeter Center office district that creates strong corporate relocation buyer demand from companies moving to the Atlanta metro.',
        neighborhoods: 'Perimeter Center, Dunwoody border, Abernathy Road area, Heards Ferry, Hammond Park',
        nearby: 'Dunwoody, Roswell, Brookhaven, Atlanta, Marietta',
        seller_hook: 'Sandy Springs\' corporate headquarters and top schools drive premium buyer demand — let top Atlanta-area realtors compete on RealtorFinder to earn your listing.',
        realtor_hook: 'Sandy Springs\' corporate headquarters cluster and school reputation create a consistent premium listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'roswell-ga',
        name: 'Roswell',
        county: 'Fulton',
        state: 'GA',
        zip: '30075',
        population: '94,000',
        median_price: '$519,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Roswell is one of metro Atlanta\'s most desirable suburbs — a historic city on the Chattahoochee River with a charming Canton Street restaurant district, top-ranked public schools, and neighborhoods that attract Atlanta professionals and corporate relocatees seeking a Southern small-town feel within a premium school district.',
        neighborhoods: 'Historic District, Canton Street corridor, Horseshoe Bend, Willow Springs, Martins Landing',
        nearby: 'Alpharetta, Sandy Springs, Marietta, Milton, Woodstock',
        seller_hook: 'Roswell\'s Canton Street charm and top schools drive strong buyer loyalty — let competing North Fulton realtors on RealtorFinder fight to earn the right to sell your home.',
        realtor_hook: 'Roswell\'s school ratings and historic character create a consistent premium buyer pool — RealtorFinder connects you with motivated sellers in North Fulton County.',
    },
];
