// cities/hi.js — Hawaii city data for SEO landing pages

module.exports = [
    {
        slug: 'honolulu',
        name: 'Honolulu',
        county: 'Honolulu',
        state: 'HI',
        zip: '96813',
        population: '350,000',
        median_price: '$820,000',
        price_trend: 'up 4%',
        avg_dom: 40,
        description: 'Honolulu is Hawaii\'s capital and the Pacific\'s premier urban destination — a city of Waikiki surf, Diamond Head hiking, Pearl Harbor history, and a military-government economy anchored by Joint Base Pearl Harbor-Hickam and the state bureaucracy that creates consistent housing demand from military families, government workers, and mainland buyers willing to pay a Pacific premium for the world\'s most iconic island address.',
        neighborhoods: 'Waikiki, Manoa, Kaimuki, Nuuanu, Makiki, East Honolulu, Aiea',
        nearby: 'Pearl City, Ewa Beach, Kailua, Kaneohe, Mililani',
        seller_hook: 'Honolulu\'s global recognition and island scarcity drive strong buyer demand year-round — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Honolulu\'s military buyer pool and island premium create high-value listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'pearl-city-hi',
        name: 'Pearl City',
        county: 'Honolulu',
        state: 'HI',
        zip: '96782',
        population: '48,000',
        median_price: '$750,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Pearl City is Oahu\'s central suburban hub adjacent to Pearl Harbor Naval Complex — a community of post-war tract homes and newer condominiums where military families, state workers, and Honolulu commuters find slightly more affordable Oahu living with Pearlridge Center shopping and convenient H-1 freeway access to both Honolulu and the Ewa corridor.',
        neighborhoods: 'Waimalu, Newtown, Manana, Pacific Palisades, Aiea',
        nearby: 'Aiea, Ewa Beach, Mililani, Kapolei, Waikele',
        seller_hook: 'Pearl City\'s Pearl Harbor proximity and suburban appeal drive consistent military and civilian buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Pearl City\'s central Oahu location and military community create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'kailua-hi',
        name: 'Kailua',
        county: 'Honolulu',
        state: 'HI',
        zip: '96734',
        population: '40,000',
        median_price: '$1,100,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Kailua is Oahu\'s Windward Coast jewel and the island\'s most coveted residential address — a beach town of turquoise Kailua Bay and Lanikai\'s world-famous shores where Obama family vacation stays cemented its global prestige, attracting wealthy mainland buyers, military officers from Kaneohe Bay, and equity-rich locals who compete intensely for the island\'s most beautiful residential neighborhoods.',
        neighborhoods: 'Lanikai, Enchanted Lake, Maunawili, Kaimalino, Coconut Grove',
        nearby: 'Kaneohe, Waimanalo, Hawaii Kai, Aiea, Pearl City',
        seller_hook: 'Kailua\'s world-famous beaches and prestige address command exceptional sale prices — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Kailua\'s luxury beach market and wealthy buyer demand create Hawaii\'s most valuable listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'hilo-hi',
        name: 'Hilo',
        county: 'Hawaii',
        state: 'HI',
        zip: '96720',
        population: '45,000',
        median_price: '$420,000',
        price_trend: 'up 5%',
        avg_dom: 45,
        description: 'Hilo is the Big Island\'s county seat and Hawaii\'s most affordable major city — a lush rainforest city on Hilo Bay where University of Hawaii at Hilo, Hilo Medical Center, and the volcanic energy of nearby Hawaii Volcanoes National Park create housing demand from UH students, medical workers, and mainland buyers seeking genuine Hawaiian living at prices that are a fraction of Oahu\'s real estate market.',
        neighborhoods: 'Keaukaha, Waiakea, Panaewa, Kurtistown, Mountain View',
        nearby: 'Keaau, Pahoa, Kurtistown, Mountain View, Volcano',
        seller_hook: 'Hilo\'s Big Island affordability and UH enrollment attract motivated buyers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Hilo\'s university market and island lifestyle create consistent listing activity at Hawaii\'s most accessible prices — find sellers through RealtorFinder.',
    },
    {
        slug: 'kailua-kona',
        name: 'Kailua-Kona',
        county: 'Hawaii',
        state: 'HI',
        zip: '96740',
        population: '22,000',
        median_price: '$680,000',
        price_trend: 'up 6%',
        avg_dom: 40,
        description: 'Kailua-Kona is the Big Island\'s sunny west coast resort hub — a world-famous Ironman Triathlon destination where lava field oceanfront living, deep-sea fishing, manta ray snorkeling, and Kona coffee country create a luxury resort market driven by wealthy mainland retirees, remote workers, and vacation property investors seeking year-round sunshine on the Pacific\'s most geologically dynamic island.',
        neighborhoods: 'Keauhou, Holualoa, Captain Cook, Kealakekua, Waikoloa Village',
        nearby: 'Captain Cook, Holualoa, Waikoloa, Kohala Coast, Waimea',
        seller_hook: 'Kailua-Kona\'s resort lifestyle and Ironman prestige command premium sale prices — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Kailua-Kona\'s luxury resort market and mainland buyer demand create high-value listing opportunities on Hawaii\'s Kona Coast — find sellers through RealtorFinder.',
    },
    {
        slug: 'lahaina-hi',
        name: 'Lahaina',
        county: 'Maui',
        state: 'HI',
        zip: '96761',
        population: '13,000',
        median_price: '$850,000',
        price_trend: 'up 5%',
        avg_dom: 45,
        description: 'Lahaina is Maui\'s historic whaling capital and West Maui\'s most storied community — a town currently rebuilding after the devastating 2023 wildfire, where Front Street\'s heritage, Ka\'anapali Resort proximity, and Maui\'s extraordinary luxury market create significant demand from vacation home buyers, resort workers, and equity-rich sellers navigating a complex post-fire recovery real estate environment.',
        neighborhoods: 'Ka\'anapali, Napili, Kapalua, Honokowai, Launiupoko',
        nearby: 'Ka\'anapali, Kahului, Wailuku, Kihei, Wailea',
        seller_hook: 'Lahaina\'s historic Front Street and Ka\'anapali resort proximity command strong sale prices despite recent challenges — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Lahaina\'s post-fire market recovery and Maui resort demand create unique and high-value listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'kapolei-hi',
        name: 'Kapolei',
        county: 'Honolulu',
        state: 'HI',
        zip: '96707',
        population: '25,000',
        median_price: '$720,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Kapolei is Oahu\'s Second City and the fastest-growing community on Hawaii\'s most populous island — a master-planned west Oahu hub where Ko Olina Resort, a new rail transit connection to Honolulu, and some of the island\'s only affordable new construction attract military families from nearby Barbers Point and young families priced out of Honolulu who want modern homes with newer schools.',
        neighborhoods: 'Ewa Beach, Ko Olina, Makakilo, Hoakalei, Ocean Pointe',
        nearby: 'Ewa Beach, Pearl City, Waipahu, Mililani, Barbers Point',
        seller_hook: 'Kapolei\'s rail connection and Ko Olina resort growth drive strong buyer demand in Oahu\'s fastest-growing corridor — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Kapolei\'s new construction market and Second City growth create active listing conditions for Oahu\'s newest major community — find sellers through RealtorFinder.',
    },
];
