// cities/ia.js — Iowa city data for SEO landing pages

module.exports = [
    {
        slug: 'des-moines',
        name: 'Des Moines',
        county: 'Polk',
        state: 'IA',
        zip: '50309',
        population: '214,000',
        median_price: '$225,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Des Moines is Iowa\'s state capital and one of the Midwest\'s most underrated housing markets — an insurance and financial services capital where Principal Financial, Wells Fargo, and a booming startup scene anchor affordable neighborhoods, a nationally acclaimed restaurant row on Court Avenue, and housing values that consistently rank among the top cost-adjusted markets in the nation for young professionals.',
        neighborhoods: 'East Village, Beaverdale, Ingersoll, Sherman Hill, West Des Moines, Ankeny',
        nearby: 'West Des Moines, Ankeny, Urbandale, Waukee, Johnston',
        seller_hook: 'Des Moines\' insurance industry and startup scene attract a growing professional buyer pool — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Des Moines\' consistent appreciation and corporate relocation market create high-volume listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'cedar-rapids',
        name: 'Cedar Rapids',
        county: 'Linn',
        state: 'IA',
        zip: '52401',
        population: '137,000',
        median_price: '$195,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Cedar Rapids is Iowa\'s second-largest city and a food processing and technology hub — home to Quaker Oats, Rockwell Collins (now Collins Aerospace), and a Czech heritage so strong it still flavors the local culture, offering excellent factory and tech employment alongside some of the Midwest\'s most affordable single-family homes on the Cedar River.',
        neighborhoods: 'NewBo, Czech Village, Time Check, Kenwood Park, Marion, Hiawatha',
        nearby: 'Marion, Hiawatha, Iowa City, North Liberty, Robins',
        seller_hook: 'Cedar Rapids\' aerospace and food processing economy drive reliable buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Cedar Rapids\' diverse employer base and affordable prices create consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'iowa-city',
        name: 'Iowa City',
        county: 'Johnson',
        state: 'IA',
        zip: '52240',
        population: '74,000',
        median_price: '$275,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Iowa City is home to the University of Iowa and a UNESCO City of Literature — a Big Ten college town where Hawkeye athletics, one of the nation\'s premier hospital systems in UI Hospitals, and a vibrant Ped Mall cultural district create intense housing competition, strong rental demand, and consistent appreciation driven by a deep pool of students, faculty, and medical professionals.',
        neighborhoods: 'Northside, Longfellow, South District, Coralville, North Liberty, Tiffin',
        nearby: 'Coralville, North Liberty, Tiffin, Kalona, Hills',
        seller_hook: 'Iowa City\'s UI enrollment and hospital system drive competitive buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Iowa City\'s university and medical market generate strong listing activity with consistent investment demand — find sellers through RealtorFinder.',
    },
    {
        slug: 'davenport-ia',
        name: 'Davenport',
        county: 'Scott',
        state: 'IA',
        zip: '52801',
        population: '101,000',
        median_price: '$185,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Davenport is the largest of the Quad Cities and Iowa\'s anchor on the Mississippi River — a manufacturing and healthcare hub where John Deere, Genesis Health System, and a revitalized RiverCenter entertainment district create demand for affordable brick bungalows and family homes at prices that make it one of the Midwest\'s best markets for first-time buyers and value investors.',
        neighborhoods: 'Bettendorf, Moline IL, Rock Island IL, East Moline IL, Milan IL',
        nearby: 'Bettendorf, Moline IL, Rock Island IL, Le Claire, Princeton',
        seller_hook: 'Davenport\'s Quad Cities economy and Mississippi riverfront draw steady buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Davenport\'s manufacturing and healthcare market create consistent listing volume at accessible prices — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'sioux-city-ia',
        name: 'Sioux City',
        county: 'Woodbury',
        state: 'IA',
        zip: '51101',
        population: '82,000',
        median_price: '$170,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Sioux City is western Iowa\'s largest city and a Missouri River agricultural processing hub — home to Tyson Foods beef processing, MercyOne Medical Center, and Briar Cliff University, offering some of Iowa\'s most affordable home prices to first-time buyers, agricultural workers, and medical professionals in a tri-state metro anchored by the Historic 4th Street entertainment district.',
        neighborhoods: 'Morningside, North Sioux City SD, South Sioux City NE, Leeds, Sergeant Bluff',
        nearby: 'South Sioux City NE, North Sioux City SD, Sergeant Bluff, Dakota City NE',
        seller_hook: 'Sioux City\'s agricultural economy and affordable prices attract a steady buyer pool — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Sioux City\'s tri-state market and processing industry create consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'waterloo-ia',
        name: 'Waterloo',
        county: 'Black Hawk',
        state: 'IA',
        zip: '50701',
        population: '68,000',
        median_price: '$155,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Waterloo is northeast Iowa\'s industrial hub and the birthplace of John Deere\'s tractor legacy — a manufacturing city on the Cedar River where Tyson\'s pork processing plant, Allen Hospital, and Hawkeye Community College create demand for affordable housing among a diverse immigrant workforce and first-time buyers who find some of Iowa\'s lowest per-square-foot home prices.',
        neighborhoods: 'Cedar Falls, Hudson, Raymond, Evansdale, Elk Run Heights',
        nearby: 'Cedar Falls, Evansdale, Hudson, Raymond, Elk Run Heights',
        seller_hook: 'Waterloo\'s manufacturing economy and affordable prices attract first-time buyers year-round — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Waterloo\'s industrial market and low price points create consistent listing volume — find sellers through RealtorFinder.',
    },
    {
        slug: 'west-des-moines',
        name: 'West Des Moines',
        county: 'Dallas / Polk',
        state: 'IA',
        zip: '50265',
        population: '67,000',
        median_price: '$310,000',
        price_trend: 'up 6%',
        avg_dom: 20,
        description: 'West Des Moines is the Des Moines metro\'s most affluent suburb — a master-planned community where Principal Financial and Wells Fargo offices, Jordan Creek Town Center, and consistently top-ranked West Des Moines Community Schools attract Iowa\'s highest-earning professional class to neighborhoods of new construction colonials and ranch homes with the metro\'s fastest days-on-market velocity.',
        neighborhoods: 'Valley Junction, Clive, Waukee, Urbandale, Booneville',
        nearby: 'Clive, Urbandale, Waukee, Johnston, Ankeny',
        seller_hook: 'West Des Moines\' financial sector and top schools create exceptional seller conditions — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'West Des Moines\' affluent buyer pool and fast-moving market make it Iowa\'s most lucrative listing suburb — find sellers through RealtorFinder.',
    },
    {
        slug: 'ankeny',
        name: 'Ankeny',
        county: 'Polk',
        state: 'IA',
        zip: '50021',
        population: '72,000',
        median_price: '$285,000',
        price_trend: 'up 7%',
        avg_dom: 21,
        description: 'Ankeny is one of the fastest-growing cities in the Midwest and Des Moines\'s most popular suburb — a community where DMACC\'s largest campus, a booming retail corridor on Delaware Avenue, and top-ranked Ankeny and Ankeny Centennial school districts attract young families and corporate transfers who find new construction neighborhoods, low crime, and fast appreciation north of downtown.',
        neighborhoods: 'Prairie Trail, Northview, Midwest Commerce, Delaware Avenue, Rock Creek',
        nearby: 'Des Moines, Alleman, Bondurant, Polk City, Elkhart',
        seller_hook: 'Ankeny\'s explosive growth and top schools create fast-moving listing conditions — let RealtorFinder agents compete for your home.',
        realtor_hook: 'Ankeny\'s Midwest-leading growth rate and family buyer demand make it Iowa\'s hottest listing suburb — find sellers through RealtorFinder.',
    },
];
