// cities/id.js — Idaho city data for SEO landing pages

module.exports = [
    {
        slug: 'boise',
        name: 'Boise',
        county: 'Ada',
        state: 'ID',
        zip: '83702',
        population: '240,000',
        median_price: '$480,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Boise is one of America\'s fastest-growing cities and the undisputed star of the Mountain West\'s real estate market — a tech-forward capital where Micron Technology, Hewlett-Packard, and a surging startup scene have drawn a flood of California and Pacific Northwest transplants seeking affordable homeownership, outdoor recreation along the Boise River Greenbelt, and a walkable downtown with a nationally recognized food scene.',
        neighborhoods: 'North End, Hyde Park, East End, Bench, Downtown, Warm Springs, West Boise, Vista',
        nearby: 'Meridian, Nampa, Eagle, Kuna, Garden City',
        seller_hook: 'Boise\'s status as one of the nation\'s hottest relocation destinations drives intense buyer competition — let top agents on RealtorFinder compete to list your home.',
        realtor_hook: 'Boise\'s explosive population growth and out-of-state buyer demand make it one of the Mountain West\'s premier listing markets — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'meridian',
        name: 'Meridian',
        county: 'Ada',
        state: 'ID',
        zip: '83642',
        population: '130,000',
        median_price: '$460,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Meridian is Idaho\'s second-largest city and one of the fastest-growing suburbs in the United States — a master-planned community west of Boise where top-ranked schools, new commercial development along Eagle Road, and the massive Meridian Town Square retail hub attract young families from across the country seeking new construction at prices far below comparable West Coast markets.',
        neighborhoods: 'Tuscany, Paramount, Lochsa Falls, Bridgetower, Spurwing, Bear Creek',
        nearby: 'Boise, Nampa, Eagle, Star, Kuna',
        seller_hook: 'Meridian\'s relentless family buyer demand and top-rated schools drive multiple-offer scenarios — let RealtorFinder agents compete for your listing.',
        realtor_hook: 'Meridian\'s status as one of the nation\'s fastest-growing cities creates exceptional listing volume — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'nampa',
        name: 'Nampa',
        county: 'Canyon',
        state: 'ID',
        zip: '83651',
        population: '105,000',
        median_price: '$360,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Nampa is Canyon County\'s largest city and the most affordable entry point into the Treasure Valley metro — a working-class community transformed by Micron\'s nearby expansion and Idaho\'s broader economic boom, drawing first-time buyers, agricultural workers, and budget-conscious families who want Idaho lifestyle without Ada County price tags.',
        neighborhoods: 'South Nampa, Karcher, Midland, Northwest Nampa, Lake Lowell Estates',
        nearby: 'Caldwell, Boise, Meridian, Kuna, Middleton',
        seller_hook: 'Nampa\'s affordability and Treasure Valley growth keep buyer demand strong — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Nampa\'s first-time buyer market and affordable price points create high listing volume — find sellers through RealtorFinder.',
    },
    {
        slug: 'caldwell',
        name: 'Caldwell',
        county: 'Canyon',
        state: 'ID',
        zip: '83605',
        population: '65,000',
        median_price: '$330,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Caldwell is the seat of Canyon County and the western anchor of the Treasure Valley — a rapidly growing agricultural and manufacturing hub where affordable new construction, College of Idaho enrollment, and proximity to the Boise metro draw first-time buyers and young families seeking the most value in southwestern Idaho.',
        neighborhoods: 'Indian Creek, Middleton, Notus, Wilder, Ranch Club',
        nearby: 'Nampa, Middleton, Notus, Wilder, Parma',
        seller_hook: 'Caldwell\'s Treasure Valley growth and first-time buyer demand drive steady interest — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Caldwell\'s affordable market and Canyon County growth create consistent listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'idaho-falls',
        name: 'Idaho Falls',
        county: 'Bonneville',
        state: 'ID',
        zip: '83401',
        population: '65,000',
        median_price: '$310,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Idaho Falls is eastern Idaho\'s commercial and medical hub — a clean, family-oriented city anchored by Idaho National Laboratory, a sprawling healthcare complex, and the Snake River greenbelt that offers Grand Teton and Yellowstone day-trip access, attracting scientists, engineers, and outdoor enthusiasts seeking affordable Rocky Mountain living.',
        neighborhoods: 'Ammon, Iona, Ucon, Shelley, Lincoln Road',
        nearby: 'Ammon, Chubbuck, Pocatello, Rexburg, Blackfoot',
        seller_hook: 'Idaho Falls\' INL employment and medical hub drive steady buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Idaho Falls\' stable government and medical employer base creates a consistent listing market — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'coeur-dalene',
        name: 'Coeur d\'Alene',
        county: 'Kootenai',
        state: 'ID',
        zip: '83814',
        population: '55,000',
        median_price: '$520,000',
        price_trend: 'up 8%',
        avg_dom: 30,
        description: 'Coeur d\'Alene is northern Idaho\'s crown jewel — a lakeside resort city on pristine Lake Coeur d\'Alene that has become a top relocation destination for retirees, remote workers, and families fleeing Pacific Northwest and California prices, drawn by an extraordinary lake lifestyle, ski access at Schweitzer Mountain, and a charming downtown marina district.',
        neighborhoods: 'Riverstone, Fernan, Dalton Gardens, Hayden, Post Falls, Rathdrum',
        nearby: 'Post Falls, Hayden, Spokane Valley WA, Liberty Lake WA, Rathdrum',
        seller_hook: 'Coeur d\'Alene\'s lakeside luxury market and relocation demand drive exceptional sale prices — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Coeur d\'Alene\'s out-of-state buyer influx and resort market create high-value listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'pocatello',
        name: 'Pocatello',
        county: 'Bannock',
        state: 'ID',
        zip: '83201',
        population: '56,000',
        median_price: '$260,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Pocatello is southeastern Idaho\'s university city and rail hub — home to Idaho State University and anchored by Portneuf Medical Center, offering some of Idaho\'s most affordable home prices to students, healthcare workers, and young families who value small-city living with access to Mink Creek Recreation Area and Caribou-Targhee National Forest.',
        neighborhoods: 'North Pocatello, Chubbuck, Old Town, University District, Alameda',
        nearby: 'Chubbuck, Blackfoot, American Falls, Burley',
        seller_hook: 'Pocatello\'s ISU enrollment and medical employer base generate consistent buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Pocatello\'s affordable market and university anchors create steady listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'twin-falls',
        name: 'Twin Falls',
        county: 'Twin Falls',
        state: 'ID',
        zip: '83301',
        population: '50,000',
        median_price: '$310,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Twin Falls is the agricultural heart of the Magic Valley and home to the iconic Perrine Bridge over the Snake River Canyon — a growing regional center where College of Southern Idaho, a booming food manufacturing sector anchored by Chobani and Clif Bar, and access to world-class fishing on the Snake River attract working families and outdoor-minded buyers.',
        neighborhoods: 'Canyon Ridge, Rock Creek, Kimberly, Filer, Buhl',
        nearby: 'Kimberly, Hansen, Jerome, Filer, Buhl',
        seller_hook: 'Twin Falls\' Magic Valley growth and diverse employer base drive steady housing demand — let RealtorFinder agents compete for your listing.',
        realtor_hook: 'Twin Falls\' agricultural and manufacturing economy creates a stable listing market — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'eagle-id',
        name: 'Eagle',
        county: 'Ada',
        state: 'ID',
        zip: '83616',
        population: '30,000',
        median_price: '$590,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Eagle is Ada County\'s most affluent suburb — a small-town feel destination along the Boise River where horse properties, high-end new construction, top-rated West Ada School District schools, and a charming downtown draw Boise\'s highest-earning residents, California equity transplants, and executives seeking prestige Treasure Valley addresses.',
        neighborhoods: 'Banbury Meadows, Lexington Hills, Dry Creek Ranch, Brookwood, The Avenues',
        nearby: 'Boise, Meridian, Star, Middleton, Garden City',
        seller_hook: 'Eagle\'s luxury market and affluent buyer pool create exceptional sale conditions — let premium agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Eagle\'s high price points and discerning buyer demographic offer the Treasure Valley\'s most lucrative listing commissions — find sellers through RealtorFinder.',
    },
    {
        slug: 'post-falls',
        name: 'Post Falls',
        county: 'Kootenai',
        state: 'ID',
        zip: '83854',
        population: '40,000',
        median_price: '$390,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Post Falls is the Spokane-Coeur d\'Alene metro\'s fastest-growing hub — an Idaho border city where Washington state commuters, Inland Northwest employers, and families priced out of Coeur d\'Alene find affordable housing with quick access to both the Coeur d\'Alene lakefront and Spokane\'s urban amenities.',
        neighborhoods: 'Seltice Way, Greensferry, Prairie, Riverview, Idaho Road',
        nearby: 'Coeur d\'Alene, Rathdrum, Spokane Valley WA, Hauser Lake',
        seller_hook: 'Post Falls\' cross-border buyer pool and rapid growth create competitive listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Post Falls\' Spokane-CDA corridor growth and affordability attract motivated buyers — find listing clients through RealtorFinder.',
    },
    {
        slug: 'rexburg',
        name: 'Rexburg',
        county: 'Madison',
        state: 'ID',
        zip: '83440',
        population: '30,000',
        median_price: '$280,000',
        price_trend: 'up 4%',
        avg_dom: 36,
        description: 'Rexburg is home to BYU-Idaho and one of the fastest-growing small cities in the Mountain West — a family-focused university town where student rental demand, young LDS families, and proximity to Yellowstone and the Tetons create a unique housing market with strong investment property and starter home demand.',
        neighborhoods: 'South Rexburg, East Rexburg, University District, Hibbard, Teton',
        nearby: 'Idaho Falls, St. Anthony, Sugar City, Rigby',
        seller_hook: 'Rexburg\'s BYU-Idaho enrollment and young family demographics drive consistent buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Rexburg\'s university market and investment property demand create active listing conditions — find sellers through RealtorFinder.',
    },
];
