// cities/il.js — Illinois city data for SEO landing pages

module.exports = [
    {
        slug: 'chicago',
        name: 'Chicago',
        county: 'Cook',
        state: 'IL',
        zip: '60601',
        population: '2700000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Chicago is America\'s most undervalued world-class city — a stunning architectural landmark with a vibrant dining scene, diverse neighborhoods from Lincoln Park\'s rowhouses to Pilsen\'s murals to Hyde Park\'s academic community, and home prices that offer real estate value unmatched by any comparable global city.',
        neighborhoods: 'Lincoln Park, Wicker Park, Logan Square, Hyde Park, Pilsen, Bucktown, Andersonville, Ravenswood',
        nearby: 'Evanston, Oak Park, Cicero, Berwyn, Skokie',
        seller_hook: 'Chicago\'s world-class neighborhoods and enormous buyer pool reward sellers who choose the right agent — let competing Chicago realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Chicago\'s neighborhood diversity and volume create unmatched listing opportunities — RealtorFinder connects you with motivated sellers across Cook County.',
    },
    {
        slug: 'naperville',
        name: 'Naperville',
        county: 'DuPage',
        state: 'IL',
        zip: '60540',
        population: '149000',
        median_price: '$620,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Naperville is consistently ranked among America\'s best cities — a planned, affluent suburb with nationally top-ranked schools, a vibrant Riverwalk downtown, Metra rail service to Chicago, and a real estate market that draws corporate relocatees and growing families who pay a premium for one of the best-managed communities in Illinois.',
        neighborhoods: 'Downtown Naperville, Naper Settlement area, South Naperville, Hobson area, West Naperville',
        nearby: 'Aurora, Bolingbrook, Lisle, Plainfield, Downers Grove',
        seller_hook: 'Naperville\'s top-school reputation and Riverwalk appeal drive premium buyer demand — let competing DuPage County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Naperville\'s consistent national rankings and corporate relocation demand create a premium listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'evanston',
        name: 'Evanston',
        county: 'Cook',
        state: 'IL',
        zip: '60201',
        population: '78000',
        median_price: '$580,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Evanston is the home of Northwestern University — a walkable, architecturally rich lakefront city with a thriving arts scene, diverse dining in its downtown, and a housing market that blends academic-community character with serious appreciation driven by proximity to Chicago and Lake Michigan.',
        neighborhoods: 'Downtown Evanston, South Evanston, West Evanston, Noyes Street Arts District, Central Street corridor',
        nearby: 'Chicago, Skokie, Wilmette, Rogers Park, Morton Grove',
        seller_hook: 'Evanston\'s Northwestern University profile and lakefront setting attract educated, high-income buyers — let competing local realtors on RealtorFinder compete for your listing.',
        realtor_hook: 'Evanston\'s consistent demand from Northwestern affiliates and Chicago commuters makes it a high-value listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'oak-park',
        name: 'Oak Park',
        county: 'Cook',
        state: 'IL',
        zip: '60301',
        population: '52000',
        median_price: '$430,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Oak Park is a celebrated historic village famous for its Frank Lloyd Wright architecture and Ernest Hemingway birthplace — a walkable, socially progressive community with excellent schools, two CTA Green Line stops connecting directly to Chicago\'s Loop, and a distinctive housing stock that consistently attracts buyers seeking character over cookie-cutter suburbs.',
        neighborhoods: 'Downtown Oak Park, Historic District, South Boulevard corridor, Austin Boulevard area, Ridgeland Avenue',
        nearby: 'River Forest, Berwyn, Cicero, Forest Park, Elmwood Park',
        seller_hook: 'Oak Park\'s unique architectural heritage and CTA access command premium prices — let competing local agents on RealtorFinder earn the right to market your home.',
        realtor_hook: 'Oak Park\'s Frank Lloyd Wright tourism and Chicago CTA access create consistent out-of-town buyer interest — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'river-forest',
        name: 'River Forest',
        county: 'Cook',
        state: 'IL',
        zip: '60305',
        population: '11500',
        median_price: '$620,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'River Forest is one of Chicago\'s most prestigious western suburbs — a quiet, tree-lined community with large Victorian and Prairie-style homes, Metra and CTA access to the Loop, Dominican University, and a neighborhood character defined by deep-rooted families who value stability, excellent schools, and proximity to Oak Park\'s amenities.',
        neighborhoods: 'Central River Forest, Keystone area, Thomas Jefferson historic area, Thatcher Woods edge',
        nearby: 'Oak Park, Forest Park, Elmwood Park, Maywood, Melrose Park',
        seller_hook: 'River Forest\'s prestige and transit access to Chicago make it consistently attractive to serious buyers — let competing realtors on RealtorFinder compete to represent your home.',
        realtor_hook: 'River Forest\'s small size and high price points mean each listing matters — RealtorFinder connects you with motivated sellers in this prestigious western suburb.',
    },
    {
        slug: 'wilmette',
        name: 'Wilmette',
        county: 'Cook',
        state: 'IL',
        zip: '60091',
        population: '27000',
        median_price: '$680,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Wilmette is a sought-after North Shore village anchored by the landmark Bahá\'í House of Worship — a lakefront community with top-rated New Trier Township schools, Metra Union Pacific North service to Chicago, and a housing market that attracts buyers seeking lakefront living with the prestige and school quality of the North Shore corridor.',
        neighborhoods: 'East Wilmette, West Wilmette, Kenilworth border, Central Business District, Linden Avenue corridor',
        nearby: 'Kenilworth, Evanston, Winnetka, Skokie, Glenview',
        seller_hook: 'Wilmette\'s Bahá\'í temple landmark, New Trier schools, and lakefront reputation attract motivated, pre-qualified buyers — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Wilmette\'s consistent North Shore demand and New Trier school district profile drive premium buyer activity — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'winnetka',
        name: 'Winnetka',
        county: 'Cook',
        state: 'IL',
        zip: '60093',
        population: '12500',
        median_price: '$1,300,000',
        price_trend: 'up 4%',
        avg_dom: 45,
        description: 'Winnetka is the crown jewel of Chicago\'s North Shore — an exclusive lakefront village with historic estates, private beaches, top-tier New Trier High School, and a dining and shopping district along Elm Street that defines understated suburban luxury for some of the Chicago area\'s most affluent families.',
        neighborhoods: 'East Winnetka lakefront estates, Indian Hill, Hubbard Woods, Westfield, Crow Island area',
        nearby: 'Wilmette, Glencoe, Kenilworth, Northfield, Northbrook',
        seller_hook: 'Winnetka\'s North Shore prestige and private lake access attract national-level buyers — let competing luxury realtors on RealtorFinder earn the right to represent your estate.',
        realtor_hook: 'Winnetka\'s $1.3M median and exclusive North Shore profile make every listing a high-value opportunity — RealtorFinder connects you with motivated sellers in this premier market.',
    },
    {
        slug: 'glencoe',
        name: 'Glencoe',
        county: 'Cook',
        state: 'IL',
        zip: '60022',
        population: '9000',
        median_price: '$1,200,000',
        price_trend: 'up 4%',
        avg_dom: 48,
        description: 'Glencoe is a refined North Shore village defined by its bluff-top Lake Michigan setting, Chicago Botanic Garden at its doorstep, and a tight-knit community of accomplished professionals who choose it for its wooded ravines, outstanding New Trier-feeder schools, and an intimate village character found nowhere else in the Chicago metro.',
        neighborhoods: 'Ravine area, Lakefront bluffs, Downtown Glencoe, Green Bay Road corridor, Chicago Botanic Garden edge',
        nearby: 'Winnetka, Highland Park, Northbrook, Wilmette, Deerfield',
        seller_hook: 'Glencoe\'s Chicago Botanic Garden proximity and North Shore bluff setting command premium prices from buyers who know exactly what they want — let competing agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Glencoe\'s exclusive profile and botanical garden prestige make it a trophy listing market — RealtorFinder connects you with motivated sellers in this North Shore gem.',
    },
    {
        slug: 'highland-park',
        name: 'Highland Park',
        county: 'Lake',
        state: 'IL',
        zip: '60035',
        population: '29000',
        median_price: '$780,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Highland Park is a vibrant North Shore city with a renowned arts culture anchored by the Ravinia Festival — a lakefront community featuring a charming downtown with acclaimed restaurants, excellent schools, Metra service to Chicago, and an eclectic housing stock ranging from walkable bungalows to grand lakefront estates.',
        neighborhoods: 'Downtown Highland Park, Ravinia, Fort Sheridan, Moraine, West Highland Park',
        nearby: 'Deerfield, Glencoe, Lake Forest, Highwood, Northbrook',
        seller_hook: 'Highland Park\'s Ravinia Festival fame and lakefront lifestyle draw affluent buyers from across the Midwest — let competing North Shore realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Highland Park\'s arts-and-lakefront positioning drives consistent premium buyer demand — RealtorFinder connects you with motivated sellers in this celebrated North Shore city.',
    },
    {
        slug: 'lake-forest',
        name: 'Lake Forest',
        county: 'Lake',
        state: 'IL',
        zip: '60045',
        population: '19000',
        median_price: '$1,100,000',
        price_trend: 'up 4%',
        avg_dom: 50,
        description: 'Lake Forest is one of Illinois\'s most prestigious addresses — a wooded, estate-filled lakefront city with Lake Forest College, a beloved Market Square shopping district designed by Howard Van Doren Shaw, and a community tradition of old-money sophistication that has made it the Gold Coast of Chicago\'s northern suburbs for over a century.',
        neighborhoods: 'East Lake Forest lakefront, Market Square area, West Lake Forest, Conway Farms, Onwentsia area',
        nearby: 'Lake Bluff, Highland Park, Libertyville, Deerfield, Lincolnshire',
        seller_hook: 'Lake Forest\'s national prestige and estate-caliber properties attract the most qualified buyers in Illinois — let competing luxury agents on RealtorFinder compete to represent your home.',
        realtor_hook: 'Lake Forest\'s $1.1M median and century-long prestige create the highest-value listing opportunities in northern Illinois — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'northbrook',
        name: 'Northbrook',
        county: 'Cook',
        state: 'IL',
        zip: '60062',
        population: '34000',
        median_price: '$530,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Northbrook is a prosperous North Shore suburb known for Northbrook Court mall, outstanding Glenbrook North High School, and a tight-knit business community anchored by corporate headquarters including Allstate — a family-oriented village where manicured neighborhoods, excellent park districts, and easy Edens Expressway access create consistent housing demand.',
        neighborhoods: 'Central Northbrook, Techny area, Northbrook Court corridor, Prairie Road area, Cherry Lane',
        nearby: 'Glenview, Deerfield, Wilmette, Buffalo Grove, Wheeling',
        seller_hook: 'Northbrook\'s top schools and corporate-headquarters employers drive strong buyer demand — let competing local agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Northbrook\'s Allstate and corporate HQ base create consistent executive relocation demand — RealtorFinder connects you with motivated sellers in this affluent Cook County suburb.',
    },
    {
        slug: 'glenview',
        name: 'Glenview',
        county: 'Cook',
        state: 'IL',
        zip: '60025',
        population: '46000',
        median_price: '$510,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Glenview is a thriving North Shore suburb built around The Glen Town Center — a lifestyle development on the former Glenview Naval Air Station that created a walkable urban village within a traditional suburban setting, offering residents top-rated schools, Metra access to Chicago, and a diverse housing market from condos to custom estates.',
        neighborhoods: 'The Glen Town Center, East Glenview, Henley area, Flick Park, West Glenview',
        nearby: 'Northbrook, Wilmette, Morton Grove, Northfield, Prospect Heights',
        seller_hook: 'Glenview\'s Glen Town Center lifestyle and top schools draw buyers from across the North Shore — let competing agents on RealtorFinder compete to earn your listing.',
        realtor_hook: 'Glenview\'s unique town-center lifestyle and North Shore school reputation drive above-average buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'deerfield-il',
        name: 'Deerfield',
        county: 'Lake',
        state: 'IL',
        zip: '60015',
        population: '18500',
        median_price: '$760,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Deerfield is a polished North Shore village home to Baxter International and Walgreens corporate campuses — a community prized for its top-rated Deerfield High School, charming downtown, and proximity to both Lake Forest\'s luxury corridor and Chicago via the Metra Union Pacific North line, making it a natural draw for corporate executives.',
        neighborhoods: 'Central Deerfield, Briergate, Coromandel, Kates Road area, Bannockburn border',
        nearby: 'Highland Park, Northbrook, Lake Forest, Buffalo Grove, Lincolnshire',
        seller_hook: 'Deerfield\'s corporate-campus neighbors at Baxter and Walgreens keep executive buyer demand high — let competing Lake County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Deerfield\'s Fortune 500 corporate campus presence creates consistent executive relocation buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'buffalo-grove',
        name: 'Buffalo Grove',
        county: 'Lake',
        state: 'IL',
        zip: '60089',
        population: '41000',
        median_price: '$380,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Buffalo Grove is a family-friendly Lake County suburb known for its outstanding Stevenson and Adlai Stevenson High School district, a thriving Town Center retail hub, and affordable homes that attract buyers who want North Shore school quality at a substantially lower price than nearby Deerfield or Highland Park.',
        neighborhoods: 'Town Center area, Prairie Road corridor, Aptakisic area, Checker Road, Port Clinton area',
        nearby: 'Deerfield, Vernon Hills, Wheeling, Lincolnshire, Northbrook',
        seller_hook: 'Buffalo Grove\'s Stevenson High School reputation draws school-motivated buyers who compete aggressively for listings — let top local agents on RealtorFinder earn your sale.',
        realtor_hook: 'Buffalo Grove\'s value positioning and Stevenson district reputation drive consistent family buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'vernon-hills',
        name: 'Vernon Hills',
        county: 'Lake',
        state: 'IL',
        zip: '60061',
        population: '26000',
        median_price: '$390,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Vernon Hills is a planned Lake County suburb centered on the Hawthorn Mall and the corporate campuses of CDW and Rust-Oleum — a well-organized community with excellent Stevenson-area schools, abundant retail and restaurant options along Milwaukee Avenue, and a growing housing market that continues to attract buyers priced out of nearby North Shore communities.',
        neighborhoods: 'Gregg\'s Landing, Century Park, Cuneo area, Hawthorn Crossings, East Vernon Hills',
        nearby: 'Buffalo Grove, Libertyville, Mundelein, Lincolnshire, Waukegan',
        seller_hook: 'Vernon Hills\' CDW and corporate campus employment drives executive buyer demand — let competing local realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Vernon Hills\' corporate HQ cluster and planned community appeal create consistent demand from corporate relocatees — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'libertyville-il',
        name: 'Libertyville',
        county: 'Lake',
        state: 'IL',
        zip: '60048',
        population: '20500',
        median_price: '$480,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Libertyville is Lake County\'s most charming downtown village — a community with a beloved Milwaukee Avenue restaurant and retail strip, outstanding Libertyville High School, an active arts scene, and a housing market that rewards buyers who want distinctive character, mature trees, and a true small-town feel within commuting distance of Chicago.',
        neighborhoods: 'Downtown Libertyville, Adler Park area, Rockland Road corridor, Greenbelt area, Cook Memorial Park vicinity',
        nearby: 'Vernon Hills, Mundelein, Lake Forest, Gurnee, Waukegan',
        seller_hook: 'Libertyville\'s beloved downtown and top high school draw lifestyle-driven buyers who pay a premium — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Libertyville\'s downtown character and Libertyville High School reputation create loyal buyer demand — RealtorFinder connects you with motivated sellers in this Lake County gem.',
    },
    {
        slug: 'waukegan',
        name: 'Waukegan',
        county: 'Lake',
        state: 'IL',
        zip: '60085',
        population: '87000',
        median_price: '$230,000',
        price_trend: 'up 8%',
        avg_dom: 32,
        description: 'Waukegan is Lake County\'s largest city and seat of county government — a diverse, lakefront community with a working harbor, a revitalizing downtown, AbbVie\'s global pharmaceutical campus as a major employer, and some of the most affordable home prices in Lake County, making it a compelling entry point for buyers in a historically high-cost market.',
        neighborhoods: 'Downtown Waukegan, North Side, South Waukegan, Harbor area, Washington Street corridor',
        nearby: 'North Chicago, Zion, Gurnee, Winthrop Harbor, Kenosha WI',
        seller_hook: 'Waukegan\'s AbbVie employment and harbor revitalization are drawing new buyers — let competitive local agents on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Waukegan\'s affordability and AbbVie pharmaceutical campus drive buyer demand across price points — RealtorFinder connects you with motivated sellers in Lake County\'s largest city.',
    },
    {
        slug: 'schaumburg',
        name: 'Schaumburg',
        county: 'Cook',
        state: 'IL',
        zip: '60193',
        population: '74000',
        median_price: '$340,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Schaumburg is the retail and corporate heart of Chicago\'s northwest suburbs — home to Woodfield Mall, Motorola Solutions headquarters, and a thriving convention district that makes it one of Cook County\'s most self-sufficient suburbs, with affordable housing that attracts buyers who want suburban amenities and walkable commercial districts without a lengthy Chicago commute.',
        neighborhoods: 'Woodfield area, Schaumburg Town Square, Weathersfield, Plum Grove, Higgins Road corridor',
        nearby: 'Hoffman Estates, Palatine, Elk Grove Village, Roselle, Streamwood',
        seller_hook: 'Schaumburg\'s Woodfield Mall and corporate campus employment create broad buyer demand — let competing northwest suburban agents on RealtorFinder earn your listing.',
        realtor_hook: 'Schaumburg\'s retail dominance and Motorola HQ drive consistent corporate buyer demand — RealtorFinder connects you with motivated sellers in this commercial hub.',
    },
    {
        slug: 'hoffman-estates',
        name: 'Hoffman Estates',
        county: 'Cook',
        state: 'IL',
        zip: '60169',
        population: '51000',
        median_price: '$330,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Hoffman Estates is a well-planned northwest suburban village known for the Sears Centre arena, the former Sears corporate campus now being redeveloped, and affordable single-family homes that attract families who value Cook County amenities at a price point well below the North Shore and closer suburbs.',
        neighborhoods: 'Prairie Stone Business Park, Serenity Falls, Bode Road area, Canterbury area, Poplar Creek',
        nearby: 'Schaumburg, Palatine, Barrington, Elgin, Streamwood',
        seller_hook: 'Hoffman Estates\' northwest location and affordable price point draw first-time and move-up buyers — let competing Cook County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Hoffman Estates\' affordability and Prairie Stone corporate campus create diverse buyer demand — RealtorFinder connects you with motivated sellers in Cook County\'s northwest corridor.',
    },
    {
        slug: 'arlington-heights',
        name: 'Arlington Heights',
        county: 'Cook',
        state: 'IL',
        zip: '60004',
        population: '76000',
        median_price: '$420,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Arlington Heights is one of Chicago\'s premier northwest suburbs — a walkable, town-center community with a celebrated Metra-served downtown, excellent schools in Township High School District 214, and a balanced housing market of bungalows, ranches, and new construction that consistently ranks among Cook County\'s most livable communities.',
        neighborhoods: 'Downtown Arlington Heights, Scarsdale, Westgate, Dunton Park area, Heritage Park',
        nearby: 'Palatine, Buffalo Grove, Wheeling, Mount Prospect, Prospect Heights',
        seller_hook: 'Arlington Heights\' walkable Metra downtown and District 214 schools drive strong demand across buyer demographics — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Arlington Heights\' Metra access and beloved downtown create consistent demand from Chicago commuters — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'palatine-il',
        name: 'Palatine',
        county: 'Cook',
        state: 'IL',
        zip: '60067',
        population: '68000',
        median_price: '$340,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Palatine is a northwest suburban Cook County village with a revitalized downtown anchored by the Metra Milwaukee District Northwest line — a family-friendly community with Fremd and Palatine high schools, a growing restaurant scene along Slade Street, and a housing market that offers legitimate value compared to neighboring Arlington Heights.',
        neighborhoods: 'Downtown Palatine, Inverness border, Plum Grove area, Sandalwood, Rand Road corridor',
        nearby: 'Arlington Heights, Schaumburg, Hoffman Estates, Rolling Meadows, Barrington',
        seller_hook: 'Palatine\'s Metra access and value-priced homes attract motivated buyers from across the northwest suburbs — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Palatine\'s affordability relative to Arlington Heights drives consistent move-up and commuter buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'rolling-meadows',
        name: 'Rolling Meadows',
        county: 'Cook',
        state: 'IL',
        zip: '60008',
        population: '24000',
        median_price: '$320,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Rolling Meadows is a compact, affordable northwest suburban city conveniently positioned at the intersection of I-90 and Kirchhoff Road — a community with solid Fremd High School attendance, the Meadows Club golf course, and a starter-home and move-up housing market that consistently attracts buyers seeking Cook County value near major expressway corridors.',
        neighborhoods: 'Salt Creek area, Kirchhoff corridor, Meadow Drive area, Wilke Road corridor, Rolling Meadows High School district',
        nearby: 'Arlington Heights, Palatine, Schaumburg, Elk Grove Village, Buffalo Grove',
        seller_hook: 'Rolling Meadows\' I-90 expressway access and affordable pricing attract motivated first-time and move-up buyers — let competitive agents on RealtorFinder earn your listing.',
        realtor_hook: 'Rolling Meadows\' affordable price point and expressway access create consistent volume buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'wheaton-il',
        name: 'Wheaton',
        county: 'DuPage',
        state: 'IL',
        zip: '60187',
        population: '53000',
        median_price: '$450,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Wheaton is DuPage County\'s seat of government and home to Wheaton College — a gracious, tree-lined community with a charming downtown, award-winning District 200 schools, two Metra stops, and a consistent housing market that draws buyers who value the combination of top academics, historic character, and commuter convenience.',
        neighborhoods: 'Downtown Wheaton, Danada area, College Avenue corridor, Arrowhead, Northgate',
        nearby: 'Glen Ellyn, Winfield, Carol Stream, Naperville, Lombard',
        seller_hook: 'Wheaton\'s District 200 schools and Wheaton College profile attract quality buyers who act decisively — let competing DuPage County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Wheaton\'s county seat status and top-school reputation drive steady, reliable buyer demand — RealtorFinder connects you with motivated sellers in DuPage County.',
    },
    {
        slug: 'downers-grove',
        name: 'Downers Grove',
        county: 'DuPage',
        state: 'IL',
        zip: '60515',
        population: '49000',
        median_price: '$450,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Downers Grove is a beloved DuPage County village with a charming, walk-to-Metra downtown, two BNSF Metra stations, Downers Grove South and North high schools, and an eclectic housing stock of vintage Craftsmans, mid-century ranches, and new infill construction that draws buyers who want authentic suburban character at a fair price.',
        neighborhoods: 'Downtown Downers Grove, Belmont area, Fairview Avenue, Lacey Road corridor, Ogden Avenue',
        nearby: 'Lisle, Westmont, Woodridge, Darien, Naperville',
        seller_hook: 'Downers Grove\'s dual Metra stations and beloved downtown drive strong demand from Chicago commuters — let competing DuPage agents on RealtorFinder earn your listing.',
        realtor_hook: 'Downers Grove\'s two Metra lines and walkable downtown make it one of DuPage County\'s most consistently active markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'lisle',
        name: 'Lisle',
        county: 'DuPage',
        state: 'IL',
        zip: '60532',
        population: '23000',
        median_price: '$360,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Lisle is a well-positioned DuPage County suburb adjacent to the Morton Arboretum — a community known for Benedictine University, quick I-88 and I-355 expressway access, Metra BNSF service to Chicago, and a housing market that offers genuine DuPage County value in a setting shaped by the arboretum\'s natural beauty and community pride.',
        neighborhoods: 'Arboretum area, Downtown Lisle, Green Trails, Four Lakes area, Lisle Station Park',
        nearby: 'Naperville, Downers Grove, Woodridge, Warrenville, Wheaton',
        seller_hook: 'Lisle\'s Morton Arboretum setting and DuPage County value attract buyers seeking nature-adjacent suburban living — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Lisle\'s arboretum prestige and I-88 access create a consistent commuter and lifestyle buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'bolingbrook',
        name: 'Bolingbrook',
        county: 'Will',
        state: 'IL',
        zip: '60440',
        population: '73000',
        median_price: '$330,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Bolingbrook is Will County\'s fastest-growing suburb — a diverse, well-planned community with the Promenade Bolingbrook lifestyle center, easy I-55 expressway access to Chicago, and a consistently affordable housing market that draws buyers from across the southwest Chicago suburbs who want new-construction quality at prices below neighboring Naperville.',
        neighborhoods: 'Boughton Road corridor, Promenade area, Fountaindale, Naperville border area, Indian Boundary Park',
        nearby: 'Naperville, Romeoville, Woodridge, Darien, Plainfield',
        seller_hook: 'Bolingbrook\'s diverse buyer pool and I-55 access attract motivated buyers seeking Naperville adjacency at lower prices — let competing agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Bolingbrook\'s growth trajectory and Naperville-adjacent positioning create strong, consistent buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'orland-park',
        name: 'Orland Park',
        county: 'Cook',
        state: 'IL',
        zip: '60462',
        population: '59000',
        median_price: '$370,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Orland Park is Chicago\'s premier southwest suburban destination — a thriving community with Orland Square Mall, a vibrant restaurant corridor on LaGrange Road, Metra SWS service to Chicago, and a housing market ranging from affordable starter homes to custom estates that consistently draws buyers from Chicago\'s South Side seeking top-tier suburban living.',
        neighborhoods: 'Orland Square area, Ravinia subdivision, Centennial Park area, Wolf Road Prairie, Tinley Park border',
        nearby: 'Tinley Park, Mokena, Frankfort, Palos Heights, Matteson',
        seller_hook: 'Orland Park\'s southwest suburban appeal and LaGrange Road amenities attract motivated buyers from Chicago and neighboring towns — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Orland Park\'s strong South Side buyer migration and diverse housing stock create consistent listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'tinley-park',
        name: 'Tinley Park',
        county: 'Cook',
        state: 'IL',
        zip: '60477',
        population: '56000',
        median_price: '$330,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Tinley Park is a thriving southwest Cook County village best known for the Hollywood Casino Amphitheatre, a revitalized Metra-anchored downtown, and affordable family homes that regularly top "best suburbs" lists for buyers relocating from Chicago\'s South Side who want schools, safety, and community investment without paying North Shore prices.',
        neighborhoods: 'Downtown Tinley Park, Brementowne, Blackberry Ridge, Oak Park Avenue corridor, Harlem Avenue',
        nearby: 'Orland Park, Mokena, Oak Forest, Matteson, Frankfort',
        seller_hook: 'Tinley Park\'s Metra downtown and South Side buyer migration make it one of Cook County\'s most active markets — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Tinley Park\'s consistent South Side buyer pipeline and affordable price point create high listing volume opportunities — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'oak-lawn',
        name: 'Oak Lawn',
        county: 'Cook',
        state: 'IL',
        zip: '60453',
        population: '57000',
        median_price: '$280,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Oak Lawn is a dense, affordable southwest Cook County suburb anchored by the Advocate Christ Medical Center — a community with quick CTA Orange Line and Metra Rock Island access to Chicago\'s Loop, a busy 95th Street commercial corridor, and a housing market that offers some of the best value in Cook County for buyers seeking Chicago proximity.',
        neighborhoods: '95th Street corridor, Sleepy Hollow, Central Avenue area, Pulaski Road corridor, Ford City area',
        nearby: 'Chicago, Evergreen Park, Burbank, Chicago Ridge, Hometown',
        seller_hook: 'Oak Lawn\'s Advocate Christ Medical Center employment and CTA access drive consistent buyer demand — let competing Cook County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Oak Lawn\'s medical center employment and Chicago transit access create strong, diverse buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'cicero',
        name: 'Cicero',
        county: 'Cook',
        state: 'IL',
        zip: '60804',
        population: '83000',
        median_price: '$240,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Cicero is a densely populated, majority-Hispanic Cook County suburb directly adjacent to Chicago\'s Lawndale neighborhood — a working-class community with CTA Pink Line access to the Loop, major commercial corridors on Cermak Road, and some of the most affordable bungalows and two-flats in the Chicago metro for buyers seeking genuine urban value.',
        neighborhoods: 'Central Cicero, Southwest Cicero, Cermak Road corridor, Austin Boulevard border, 55th Court area',
        nearby: 'Chicago, Berwyn, Oak Park, Stickney, Forest Park',
        seller_hook: 'Cicero\'s Chicago adjacency and CTA access attract urban buyers seeking affordability — let competing local agents on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Cicero\'s strong Hispanic community ties and Chicago border location drive consistent neighborhood buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'berwyn',
        name: 'Berwyn',
        county: 'Cook',
        state: 'IL',
        zip: '60402',
        population: '56000',
        median_price: '$280,000',
        price_trend: 'up 8%',
        avg_dom: 26,
        description: 'Berwyn is a historic bungalow-belt suburb directly west of Chicago\'s Austin neighborhood — a diverse, walkable community with CTA Pink and Blue line access, a vibrant Cermak Road arts district, and some of the best-maintained classic Chicago bungalow stock anywhere in the metro, drawing urban buyers who value architecture, diversity, and Chicago proximity.',
        neighborhoods: 'Proksa Park area, Cermak Arts District, Roosevelt Road corridor, Harlem Avenue, Depot District',
        nearby: 'Oak Park, Cicero, Riverside, Lyons, Forest Park',
        seller_hook: 'Berwyn\'s classic bungalow stock and CTA access attract Chicago urban buyers seeking character and value — let competing Cook County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Berwyn\'s bungalow appeal and Chicago transit access create consistent demand from urban-to-suburban buyers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'elmhurst-il',
        name: 'Elmhurst',
        county: 'DuPage',
        state: 'IL',
        zip: '60126',
        population: '46000',
        median_price: '$520,000',
        price_trend: 'up 6%',
        avg_dom: 23,
        description: 'Elmhurst is DuPage County\'s most charming eastern suburb — a community with a tree-lined Metra BNSF downtown, Elmhurst University, York Community High School, and a beautifully maintained housing stock of Craftsman bungalows, Colonials, and new construction that draws discerning buyers from Chicago who want the full suburban package within 30 minutes of the Loop.',
        neighborhoods: 'Downtown Elmhurst, Wilder Park area, Elmhurst University campus, Salt Creek corridor, Spring Road',
        nearby: 'Villa Park, Oak Brook, Lombard, Addison, Downers Grove',
        seller_hook: 'Elmhurst\'s York High School and Metra downtown command some of DuPage County\'s best price-per-square-foot — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Elmhurst\'s eastern DuPage location and Metra BNSF access make it one of the region\'s highest-demand markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'lombard',
        name: 'Lombard',
        county: 'DuPage',
        state: 'IL',
        zip: '60148',
        population: '43000',
        median_price: '$360,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Lombard is DuPage County\'s "Lilac Village" — a well-established community known for the annual Lilac Time festival, Metra Union Pacific West service to Chicago, Glenbard East High School, and a diverse housing stock of ranch homes, split-levels, and new townhomes that consistently attracts buyers seeking DuPage County quality at a value price point.',
        neighborhoods: 'Downtown Lombard, Lilacia Park area, Yorktown Center corridor, Westmore, Roosevelt Road',
        nearby: 'Villa Park, Elmhurst, Glen Ellyn, Addison, Wheaton',
        seller_hook: 'Lombard\'s Lilac Village charm and Metra access attract buyers who want DuPage character at below-Elmhurst pricing — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Lombard\'s value positioning within DuPage County creates consistent buyer demand from budget-conscious suburban shoppers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'aurora-il',
        name: 'Aurora',
        county: 'Kane',
        state: 'IL',
        zip: '60505',
        population: '180000',
        median_price: '$320,000',
        price_trend: 'up 8%',
        avg_dom: 27,
        description: 'Aurora is the second-largest city in Illinois and the westernmost stop on Metra\'s BNSF line — a diverse, affordable community with a revitalized riverfront RiverEdge Park entertainment venue, Waubonsee Community College, and home prices that offer entry-level buyers a genuine path to homeownership within the broader Chicago metro market.',
        neighborhoods: 'Downtown Aurora, RiverEdge Park area, West Aurora, East Aurora, Orchard Road corridor',
        nearby: 'Naperville, Oswego, Elgin, Batavia, Montgomery',
        seller_hook: 'Aurora\'s Metra access and Chicago metro position drive strong buyer demand — let competing Kane County realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Aurora\'s affordability and Metra BNSF access create consistent commuter buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'elgin',
        name: 'Elgin',
        county: 'Kane',
        state: 'IL',
        zip: '60120',
        population: '114000',
        median_price: '$320,000',
        price_trend: 'up 8%',
        avg_dom: 26,
        description: 'Elgin is the Fox River Valley\'s anchor city — a diverse, historic community with Metra rail access to Chicago, a revitalized downtown anchored by the Hemmens Cultural Center and the Grand Victoria Casino, and home prices that offer families genuine Chicago metro value without sacrificing community character.',
        neighborhoods: 'Downtown Elgin, South Elgin border, Northwest Elgin, Fox River waterfront, Gifford Park',
        nearby: 'South Elgin, St. Charles, Bartlett, Streamwood, Carpentersville',
        seller_hook: 'Elgin\'s Metra access and diverse community attract buyers from across the Fox Valley — let competing Kane County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Elgin\'s affordability and Chicago Metra access create consistent commuter buyer demand — RealtorFinder connects you with motivated sellers in the Fox River Valley.',
    },
    {
        slug: 'joliet',
        name: 'Joliet',
        county: 'Will',
        state: 'IL',
        zip: '60432',
        population: '150000',
        median_price: '$280,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Joliet is Will County\'s largest city and a major logistics and manufacturing hub — a community undergoing downtown revitalization with Metra access to Chicago, a bustling Hollywood Casino, and home prices that offer first-time buyers an affordable entry into the Chicago metro market, anchored by employment at the massive Joliet Arsenal logistics park.',
        neighborhoods: 'Downtown Joliet, East Side, West Side, Crest Hill border, Shorewood border',
        nearby: 'Crest Hill, Lockport, Plainfield, Romeoville, Bolingbrook',
        seller_hook: 'Joliet\'s logistics growth and affordability draw buyers from across Will County — let competitive local realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Joliet\'s large population and logistics-driven job growth create consistent buyer activity — RealtorFinder connects you with motivated sellers in Will County.',
    },
    {
        slug: 'rockford',
        name: 'Rockford',
        county: 'Winnebago',
        state: 'IL',
        zip: '61101',
        population: '148000',
        median_price: '$180,000',
        price_trend: 'up 9%',
        avg_dom: 30,
        description: 'Rockford is northern Illinois\'s largest city and one of the Midwest\'s most compelling value markets — an industrial and medical hub with affordable home prices, a revitalized downtown along the Rock River, and a growing healthcare sector anchored by OSF Saint Anthony Medical Center and Mercyhealth that creates stable employment-driven housing demand.',
        neighborhoods: 'Edgewater, Kishwaukee Street corridor, Southwest Rockford, North Rockford, Loves Park border',
        nearby: 'Loves Park, Machesney Park, Belvidere, Roscoe, Cherry Valley',
        seller_hook: 'Rockford\'s 9% appreciation and strong medical sector demand make now a great time to sell — RealtorFinder puts competitive local agents in a race to represent your home.',
        realtor_hook: 'Rockford\'s sub-$180K entry point and consistent appreciation make it a high-volume opportunity market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'champaign',
        name: 'Champaign',
        county: 'Champaign',
        state: 'IL',
        zip: '61820',
        population: '89000',
        median_price: '$250,000',
        price_trend: 'up 7%',
        avg_dom: 29,
        description: 'Champaign is the home of the University of Illinois Urbana-Champaign — a dynamic college city with a thriving tech startup ecosystem in the Research Park, a vibrant Downtown Champaign arts and restaurant scene, and a housing market that blends stable academic-community demand with growing tech-sector buyer activity from UIUC spinout companies.',
        neighborhoods: 'Downtown Champaign, Campustown, Countryside, Devonshire, Savoy border',
        nearby: 'Urbana, Savoy, Mahomet, Rantoul, Tolono',
        seller_hook: 'Champaign\'s UIUC Research Park and academic community create a consistent, educated buyer pool — let competing local agents on RealtorFinder earn your listing.',
        realtor_hook: 'Champaign\'s university-anchored economy and tech startup scene create consistent, diverse buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'springfield-il',
        name: 'Springfield',
        county: 'Sangamon',
        state: 'IL',
        zip: '62701',
        population: '114000',
        median_price: '$200,000',
        price_trend: 'up 7%',
        avg_dom: 32,
        description: 'Springfield is Illinois\'s capital and Abraham Lincoln\'s hometown — a government and healthcare hub with the Abraham Lincoln Presidential Library and Museum, a revitalized downtown entertainment district along Washington Street, and home prices that offer buyers one of the most affordable entry points in any state capital in the Midwest.',
        neighborhoods: 'Old Aristocracy Hill, South Side, West Side, Enos Park, Laurel Hill, Bruns Lane area',
        nearby: 'Rochester, Sherman, Chatham, Riverton, Taylorville',
        seller_hook: 'Springfield\'s state government stability and affordable prices keep buyer demand consistent — RealtorFinder puts competing Sangamon County agents in a race to earn your listing.',
        realtor_hook: 'Springfield\'s state capital stability creates recession-resistant buyer demand — RealtorFinder connects you with motivated sellers in Illinois\'s capital city.',
    },
    {
        slug: 'peoria-il',
        name: 'Peoria',
        county: 'Peoria',
        state: 'IL',
        zip: '61602',
        population: '113000',
        median_price: '$190,000',
        price_trend: 'up 8%',
        avg_dom: 33,
        description: 'Peoria is central Illinois\'s largest city and home to Caterpillar\'s global headquarters — an industrial and healthcare hub where home prices remain among the most affordable in the state and a revitalized riverfront is drawing investment and buyers who see real value in a market where Caterpillar and OSF HealthCare employment provide economic stability.',
        neighborhoods: 'Junction City, North Peoria, West Bluff, South Side, Bartonville border, Dunlap border',
        nearby: 'East Peoria, Pekin, Morton, Washington, Chillicothe',
        seller_hook: 'Peoria\'s Caterpillar-anchored economy provides stability for sellers — RealtorFinder puts competitive local agents in a race to earn the right to represent your home.',
        realtor_hook: 'Peoria\'s Caterpillar headquarters and affordable prices attract buyers seeking Midwest value — RealtorFinder connects you with motivated sellers in central Illinois.',
    },
];
