// cities/il.js — Illinois city data for SEO landing pages

module.exports = [
    {
        slug: 'chicago',
        name: 'Chicago',
        county: 'Cook',
        state: 'IL',
        zip: '60601',
        population: '2700000',
        median_price: '$329,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Chicago is America\'s most undervalued world-class city — a stunning architectural landmark with a vibrant dining scene, diverse neighborhoods from Lincoln Park\'s rowhouses to Pilsen\'s murals to Hyde Park\'s academic community, and home prices that offer real estate value unmatched by any comparable global city.',
        neighborhoods: 'Lincoln Park, Wicker Park, Logan Square, Hyde Park, Pilsen, Bucktown, Andersonville, Ravenswood',
        nearby: 'Evanston, Oak Park, Cicero, Berwyn, Skokie',
        seller_hook: 'Chicago\'s world-class neighborhoods and diverse buyer pool reward sellers who choose the right agent — let competing Chicago realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Chicago\'s enormous size and neighborhood diversity create unmatched listing opportunities in a world-class market — RealtorFinder connects you with motivated sellers across Cook County.',
    },
    {
        slug: 'aurora-il',
        name: 'Aurora',
        county: 'Kane',
        state: 'IL',
        zip: '60505',
        population: '180,000',
        median_price: '$279,000',
        price_trend: 'up 8%',
        avg_dom: 27,
        description: 'Aurora is the second-largest city in Illinois and the westernmost stop on Metra\'s BNSF line — a diverse, affordable community with access to Chicago in under an hour and home prices that offer entry-level buyers a genuine path to homeownership within the broader Chicago metro market.',
        neighborhoods: 'Downtown Aurora, West Aurora, East Aurora, North Aurora border, Naperville border',
        nearby: 'Naperville, Oswego, Elgin, Batavia, Montgomery',
        seller_hook: 'Aurora\'s Metra access and Chicago metro position drive strong buyer demand — let competing Kane County realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Aurora\'s affordability and Metra access create consistent buyer demand from Chicago-bound commuters — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'joliet',
        name: 'Joliet',
        county: 'Will',
        state: 'IL',
        zip: '60432',
        population: '150,000',
        median_price: '$239,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Joliet is Will County\'s largest city and a major logistics and manufacturing hub — a community undergoing downtown revitalization with Metra access to Chicago, an Amazon fulfillment center driving local employment, and home prices that offer first-time buyers an affordable entry into the Chicago metro market.',
        neighborhoods: 'Downtown Joliet, East Side, West Side, Crest Hill border, Shorewood border',
        nearby: 'Crest Hill, Lockport, Plainfield, Romeoville, Bolingbrook',
        seller_hook: 'Joliet\'s growth and affordability draw buyers from across Will County — let competitive local realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Joliet\'s large population and logistics-driven job growth create consistent buyer activity — RealtorFinder connects you with motivated sellers in Will County.',
    },
    {
        slug: 'rockford',
        name: 'Rockford',
        county: 'Winnebago',
        state: 'IL',
        zip: '61101',
        population: '148,000',
        median_price: '$149,000',
        price_trend: 'up 9%',
        avg_dom: 30,
        description: 'Rockford is northern Illinois\'s largest city and one of the Midwest\'s most compelling value markets — an industrial and medical hub with affordable home prices, a revitalized downtown, and a growing healthcare sector anchored by OSF Saint Anthony Medical Center that creates stable employment-driven housing demand.',
        neighborhoods: 'Edgewater, Kishwaukee Street corridor, Southwest Rockford, North Rockford, Loves Park border',
        nearby: 'Loves Park, Machesney Park, Belvidere, Roscoe, Cherry Valley',
        seller_hook: 'Rockford\'s 9% appreciation and strong medical sector demand make now a great time to sell — RealtorFinder puts competitive local agents in a race to represent your home.',
        realtor_hook: 'Rockford\'s sub-$150K entry point and consistent appreciation make it a high-volume opportunity market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'springfield-il',
        name: 'Springfield',
        county: 'Sangamon',
        state: 'IL',
        zip: '62701',
        population: '114,000',
        median_price: '$149,000',
        price_trend: 'up 7%',
        avg_dom: 32,
        description: 'Springfield is Illinois\'s capital and Abraham Lincoln\'s hometown — a government and healthcare hub with Abraham Lincoln Presidential Library, a revitalized downtown, and home prices that offer buyers one of the most affordable entry points in any state capital in the Midwest.',
        neighborhoods: 'Old Aristocracy Hill, South Side, West Side, Enos Park, Laurel Hill, Bruns Lane area',
        nearby: 'Rochester, Sherman, Chatham, Riverton, Taylorville',
        seller_hook: 'Springfield\'s state government stability and affordable prices keep buyer demand consistent — RealtorFinder puts competing Sangamon County agents in a race to earn your listing.',
        realtor_hook: 'Springfield\'s state capital stability creates recession-resistant buyer demand — RealtorFinder connects you with motivated sellers in Illinois\'s capital city.',
    },
    {
        slug: 'elgin',
        name: 'Elgin',
        county: 'Kane',
        state: 'IL',
        zip: '60120',
        population: '114,000',
        median_price: '$259,000',
        price_trend: 'up 8%',
        avg_dom: 26,
        description: 'Elgin is the Fox River Valley\'s anchor city — a diverse, historic community with Metra rail access to Chicago, a revitalized downtown anchored by the Hemmens Cultural Center, and home prices that offer families a genuine value within the broader Chicago metro without sacrificing community character.',
        neighborhoods: 'Downtown Elgin, South Elgin border, Northwest Elgin, Fox River waterfront, Gifford Park',
        nearby: 'South Elgin, St. Charles, Bartlett, Streamwood, Carpentersville',
        seller_hook: 'Elgin\'s Metra access and diverse community attract buyers from across the Fox Valley — let competing Kane County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Elgin\'s affordability and Chicago Metra access create consistent commuter buyer demand — RealtorFinder connects you with motivated sellers in the Fox River Valley.',
    },
    {
        slug: 'naperville',
        name: 'Naperville',
        county: 'DuPage',
        state: 'IL',
        zip: '60540',
        population: '149,000',
        median_price: '$479,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Naperville is consistently ranked among America\'s best cities — a planned, affluent suburb with nationally top-ranked schools, a vibrant Riverwalk downtown, Metra rail service to Chicago, and a real estate market that draws corporate relocatees and growing families who are willing to pay a premium for one of the best-managed communities in Illinois.',
        neighborhoods: 'Downtown Naperville, Naper Settlement area, South Naperville, Hobson area, West Naperville',
        nearby: 'Aurora, Bolingbrook, Lisle, Plainfield, Downers Grove',
        seller_hook: 'Naperville\'s top-school reputation and Riverwalk appeal drive premium buyer demand — let competing DuPage County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Naperville\'s consistent national rankings and corporate relocation demand create a premium listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'peoria',
        name: 'Peoria',
        county: 'Peoria',
        state: 'IL',
        zip: '61602',
        population: '113,000',
        median_price: '$129,000',
        price_trend: 'up 8%',
        avg_dom: 33,
        description: 'Peoria is central Illinois\'s largest city and home to Caterpillar\'s global headquarters — an industrial and healthcare hub where home prices remain among the most affordable in the state and a revitalized riverfront is drawing investment and buyers who see real value in a market where Caterpillar employment provides economic stability.',
        neighborhoods: 'Junction City, North Peoria, West Bluff, South Side, Bartonville border, Dunlap border',
        nearby: 'East Peoria, Pekin, Morton, Washington, Chillicothe',
        seller_hook: 'Peoria\'s Caterpillar-anchored economy provides stability for sellers — RealtorFinder puts competitive local agents in a race to earn the right to represent your home.',
        realtor_hook: 'Peoria\'s Caterpillar headquarters and affordable prices attract buyers seeking Midwest value — RealtorFinder connects you with motivated sellers in central Illinois.',
    },
];
