// cities/in.js — Indiana city data for SEO landing pages

module.exports = [
    {
        slug: 'indianapolis',
        name: 'Indianapolis',
        county: 'Marion',
        state: 'IN',
        zip: '46204',
        population: '887000',
        median_price: '$245,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'Indianapolis is one of America\'s most undervalued major cities — a genuine sports and convention capital with a revitalized downtown anchored by Lucas Oil Stadium, Bankers Life Fieldhouse, and a thriving Mass Avenue and Fountain Square arts district, alongside Eli Lilly\'s global pharmaceutical headquarters, a growing tech sector, and neighborhoods like Meridian-Kessler and Irvington offering architectural character at accessible prices.',
        neighborhoods: 'Meridian-Kessler, Irvington, Fountain Square, Broad Ripple, Mass Ave, Butler-Tarkington',
        nearby: 'Carmel, Fishers, Zionsville, Lawrence, Southport',
        seller_hook: 'Indianapolis\'s surging prices and major city amenities create a competitive buyer market — let competing Marion County realtors on RealtorFinder fight to earn the right to list your home.',
        realtor_hook: 'Indianapolis\'s large population and diverse neighborhoods create abundant listing opportunities for agents who know this market — RealtorFinder connects you with motivated sellers across Marion County.',
    },
    {
        slug: 'carmel-in',
        name: 'Carmel',
        county: 'Hamilton',
        state: 'IN',
        zip: '46032',
        population: '105000',
        median_price: '$550,000',
        price_trend: 'up 7%',
        avg_dom: 19,
        description: 'Carmel is Indiana\'s premier affluent suburb and one of the Midwest\'s most celebrated planned communities — the Arts and Design District anchors a walkable downtown of upscale restaurants, galleries, and shops, Carmel Clay Schools consistently rank among Indiana\'s very best, and the city\'s renowned roundabout network and master-planned neighborhoods attract corporate executives, pharmaceutical professionals, and Midwest transplants seeking the full suburban package.',
        neighborhoods: 'Arts and Design District, Westfield border, Clay Township, Keystone Corridor, Guilford Park',
        nearby: 'Westfield, Zionsville, Fishers, Noblesville, Indianapolis',
        seller_hook: 'Carmel\'s Arts District prestige and elite schools attract buyers willing to pay a premium for the right home — let competing Hamilton County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Carmel\'s high price points and consistent affluent buyer demand create outstanding listing opportunities for qualified agents — RealtorFinder connects you with motivated sellers in Indiana\'s premier suburb.',
    },
    {
        slug: 'fishers',
        name: 'Fishers',
        county: 'Hamilton',
        state: 'IN',
        zip: '46037',
        population: '105000',
        median_price: '$420,000',
        price_trend: 'up 8%',
        avg_dom: 17,
        description: 'Fishers is one of America\'s fastest-growing cities and Hamilton County\'s tech hub — a transformed former bedroom community now home to Salesforce, Angie, and hundreds of tech and life sciences firms in the Fishers District innovation corridor, with Hamilton Southeastern Schools among Indiana\'s most respected districts and newer master-planned neighborhoods that attract young tech professionals and growing families.',
        neighborhoods: 'Fishers District, 116th Street corridor, Fall Creek Road area, Geist Reservoir, Noblesville border',
        nearby: 'Noblesville, Carmel, Indianapolis, Lawrence, Fortville',
        seller_hook: 'Fishers\' tech economy and top schools create a consistent pool of qualified buyers competing for limited inventory — let realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Fishers\' rapid growth and tech relocation market make it one of Indiana\'s most active listing markets for motivated agents — RealtorFinder connects you with sellers ready to capitalize on current demand.',
    },
    {
        slug: 'zionsville',
        name: 'Zionsville',
        county: 'Boone',
        state: 'IN',
        zip: '46077',
        population: '30000',
        median_price: '$560,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Zionsville is one of Indiana\'s most charming and prestigious small towns — a brick Main Street of independent boutiques, wine bars, and farm-to-table restaurants anchors a community of executive estates and golf course neighborhoods, with Zionsville Community Schools consistently among Indiana\'s highest-ranked districts and a coveted address that attracts Indianapolis\'s top executives seeking small-town authenticity without sacrificing suburban luxury.',
        neighborhoods: 'Historic Village, Boone County, Holliday Farms, Eagle Creek border, Whitestown border',
        nearby: 'Carmel, Indianapolis, Lebanon, Whitestown, Westfield',
        seller_hook: 'Zionsville\'s brick Main Street and elite school district command premium prices for sellers positioned in the right neighborhoods — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Zionsville\'s high price points and limited Village inventory create strong per-listing earnings for qualified agents — RealtorFinder connects you with motivated sellers in this premier Boone County community.',
    },
    {
        slug: 'noblesville-in',
        name: 'Noblesville',
        county: 'Hamilton',
        state: 'IN',
        zip: '46060',
        population: '75000',
        median_price: '$390,000',
        price_trend: 'up 8%',
        avg_dom: 19,
        description: 'Noblesville is Hamilton County\'s county seat and one of Indiana\'s fastest-growing cities — a beautifully preserved historic courthouse square anchors a community undergoing significant residential development, with Noblesville Schools performing well above state averages, Morse Reservoir recreational access, and the Ruoff Music Center amphitheater driving summer economic activity that makes this one of the Indianapolis metro\'s most dynamic communities.',
        neighborhoods: 'Historic Downtown, Morse Reservoir area, SR 37 corridor, Hazel Dell area, Westfield border',
        nearby: 'Fishers, Westfield, Carmel, Indianapolis, Cicero',
        seller_hook: 'Noblesville\'s historic charm and Hamilton County growth create buyers ready to compete for well-positioned listings — let competing realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Noblesville\'s rapid growth and strong school reputation create consistent listing opportunities for motivated agents — RealtorFinder connects you with sellers across Hamilton County.',
    },
    {
        slug: 'westfield-in',
        name: 'Westfield',
        county: 'Hamilton',
        state: 'IN',
        zip: '46074',
        population: '55000',
        median_price: '$420,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'Westfield is Hamilton County\'s northern growth frontier and home to Grand Park Sports Campus — one of America\'s largest youth sports complexes drives year-round economic activity and national family recognition for a community that also boasts Westfield Washington Schools above state academic averages, master-planned neighborhoods of craftsman and colonial homes, and a small-town character that is rapidly maturing into a genuine destination suburb.',
        neighborhoods: 'Grand Park area, Union Street corridor, SR 32 corridor, Carey Road area, Carmel border',
        nearby: 'Carmel, Zionsville, Noblesville, Lebanon, Sheridan',
        seller_hook: 'Westfield\'s Grand Park recognition and rapid growth attract buyers from across the Midwest relocating to the Indianapolis area — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Westfield\'s explosive population growth and sports campus visibility create one of Hamilton County\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'greenwood-in',
        name: 'Greenwood',
        county: 'Johnson',
        state: 'IN',
        zip: '46143',
        population: '65000',
        median_price: '$310,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'Greenwood is Johnson County\'s largest city and Indianapolis\'s most affordable viable southern suburb — a rapidly growing community anchored by Greenwood Park Mall and a dense US-31 retail corridor, with Center Grove Community School Corporation consistently among Indiana\'s most recognized districts for academic achievement, and accessible prices that make it the first choice for Indianapolis families seeking top schools without Hamilton County price premiums.',
        neighborhoods: 'Greenwood Park Mall area, Center Grove area, Smith Valley Road corridor, Main Street Historic District, Bargersville border',
        nearby: 'Indianapolis, Bargersville, Franklin, Whiteland, Trafalgar',
        seller_hook: 'Greenwood\'s Center Grove school reputation and affordable prices create buyers who compete aggressively for listings — let realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Greenwood\'s large population and Center Grove school demand create consistent listing activity for agents — RealtorFinder connects you with motivated sellers across Johnson County.',
    },
    {
        slug: 'plainfield-in',
        name: 'Plainfield',
        county: 'Hendricks',
        state: 'IN',
        zip: '46168',
        population: '38000',
        median_price: '$330,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Plainfield is Hendricks County\'s largest city and one of the Indianapolis metro\'s most significant logistics hubs — the Plainfield Distribution Center corridor along I-70 hosts Amazon, FedEx, and dozens of major warehousing operations that anchor a growing blue-collar and management workforce, while Plainfield Community School Corporation\'s solid reputation and new residential development make this a genuine growth story.',
        neighborhoods: 'Dan Jones Road corridor, CR 100 East area, US-40 corridor, Avon border, Mooresville border',
        nearby: 'Avon, Indianapolis, Mooresville, Brownsburg, Camby',
        seller_hook: 'Plainfield\'s logistics employment and Indianapolis access create steady buyer demand for well-priced homes — let competing Hendricks County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Plainfield\'s growing population and logistics industry employment create reliable listing activity for agents — RealtorFinder connects you with motivated sellers in this Hendricks County growth market.',
    },
    {
        slug: 'avon-in',
        name: 'Avon',
        county: 'Hendricks',
        state: 'IN',
        zip: '46123',
        population: '20000',
        median_price: '$360,000',
        price_trend: 'up 8%',
        avg_dom: 19,
        description: 'Avon is Hendricks County\'s premier family community and one of the Indianapolis metro\'s fastest-growing western suburbs — a community anchored by Avon Community School Corporation, which consistently earns Indiana\'s highest A-F accountability grades, with newer subdivisions of craftsman and colonial homes along US-36 and SR-267 that attract families seeking top schools and a suburban lifestyle at prices below the Hamilton County premium.',
        neighborhoods: 'Avon Center, US-36 corridor, SR-267 area, Plainfield border, Brownsburg border',
        nearby: 'Brownsburg, Plainfield, Indianapolis, Danville, Pittsboro',
        seller_hook: 'Avon\'s top-graded schools and Indianapolis access create motivated buyers ready to compete for good listings — let competing realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Avon\'s school reputation and growing western suburb demand create consistent listing opportunities for agents — RealtorFinder connects you with motivated sellers in Hendricks County.',
    },
    {
        slug: 'brownsburg-in',
        name: 'Brownsburg',
        county: 'Hendricks',
        state: 'IN',
        zip: '46112',
        population: '30000',
        median_price: '$330,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Brownsburg is known as Indiana\'s Racing Capital — Lucas Oil Indianapolis Raceway Park anchors a motorsports culture that gives this Hendricks County community a unique identity, while Brownsburg Community School Corporation\'s consistently strong performance drives family demand for the newer subdivisions and established neighborhoods that have made this one of the Indianapolis metro\'s most reliably growing western communities.',
        neighborhoods: 'Downtown Brownsburg, Jefferson Street corridor, SR-267 area, Pittsboro border, Avon border',
        nearby: 'Avon, Plainfield, Zionsville, Indianapolis, Lebanon',
        seller_hook: 'Brownsburg\'s racing identity and strong schools create a passionate buyer community ready to act on well-priced listings — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Brownsburg\'s consistent growth and Hendricks County school demand create reliable listing activity for motivated agents — RealtorFinder connects you with sellers ready to move.',
    },
    {
        slug: 'fort-wayne',
        name: 'Fort Wayne',
        county: 'Allen',
        state: 'IN',
        zip: '46802',
        population: '270000',
        median_price: '$215,000',
        price_trend: 'up 9%',
        avg_dom: 19,
        description: 'Fort Wayne is Indiana\'s second-largest city and one of the Midwest\'s most undervalued metros for quality of life — a diverse economy anchored by Lincoln Financial Group, Parkview Health, Sweetwater Sound\'s massive music retail campus, and a significant manufacturing base supports affordable neighborhoods from the historical Swinney Park area to the growing southwest suburban corridor of Aboite and St. Joe Center.',
        neighborhoods: 'Swinney Park, West Central, Aboite Township, St. Joe Center Road area, Dupont Road corridor',
        nearby: 'New Haven, Leo-Cedarville, Huntertown, Grabill, Waynedale',
        seller_hook: 'Fort Wayne\'s rising prices and growing national recognition create buyer demand that rewards sellers who choose the right agent — let competing Allen County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Fort Wayne\'s large population and diversified economy create consistent listing opportunities for agents — RealtorFinder connects you with motivated sellers across Allen County.',
    },
    {
        slug: 'south-bend-in',
        name: 'South Bend',
        county: 'St. Joseph',
        state: 'IN',
        zip: '46601',
        population: '103000',
        median_price: '$155,000',
        price_trend: 'up 10%',
        avg_dom: 21,
        description: 'South Bend is undergoing a remarkable renaissance — Mayor Pete Buttigieg\'s administration launched a revitalization that has continued under successive leadership, University of Notre Dame\'s global prestige anchors academic and tech investment, AM General\'s Humvee plant and Beacon Health System provide employment stability, and historic neighborhoods like Rum Village and Chapin Park offer architectural character at some of Indiana\'s most compelling entry-level prices.',
        neighborhoods: 'Chapin Park, Rum Village, Notre Dame border, Edgewater, Near Northwest, LaSalle Park',
        nearby: 'Mishawaka, Granger, Osceola, New Carlisle, Elkhart',
        seller_hook: 'South Bend\'s Notre Dame connection and revival momentum create buyers willing to act quickly on well-priced listings — let competing St. Joseph County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'South Bend\'s rising prices and Notre Dame relocation market create strong listing activity for agents who understand this evolving market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'granger-in',
        name: 'Granger',
        county: 'St. Joseph',
        state: 'IN',
        zip: '46530',
        population: '30000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 21,
        description: 'Granger is South Bend metro\'s most affluent community — an unincorporated St. Joseph County township of executive neighborhoods and wooded estates along the St. Joseph River, serving Notre Dame faculty, university administrators, and regional corporate executives who prize Penn-Harris-Madison School Corporation\'s strong academic reputation and the community\'s proximity to Notre Dame without the density of Mishawaka proper.',
        neighborhoods: 'Granger Road corridor, Cleveland Road area, Brick Road area, Osceola border, Mishawaka border',
        nearby: 'Mishawaka, South Bend, Osceola, Elkhart, New Carlisle',
        seller_hook: 'Granger\'s Notre Dame connection and executive housing market attract buyers willing to pay a premium for the right address — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Granger\'s executive housing and Notre Dame relocation demand create strong listing opportunities for qualified agents — RealtorFinder connects you with motivated sellers in St. Joseph County\'s premier community.',
    },
    {
        slug: 'mishawaka',
        name: 'Mishawaka',
        county: 'St. Joseph',
        state: 'IN',
        zip: '46544',
        population: '50000',
        median_price: '$210,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Mishawaka is the Princess City of the Midwest — a complete small city with its own downtown, Battell Park along the St. Joseph River, the University Park Mall retail hub, Bethel University, and Penn-Harris-Madison School Corporation delivering strong academic results, all at price points that offer South Bend metro buyers quality neighborhoods and genuine community character at a fraction of the cost of comparable Chicago suburbs.',
        neighborhoods: 'Downtown Mishawaka, Battell Park area, Day Road corridor, Main Street corridor, Granger border',
        nearby: 'South Bend, Granger, Osceola, Elkhart, Bremen',
        seller_hook: 'Mishawaka\'s Princess City character and affordable prices draw buyers motivated to find value in the South Bend metro — let competing St. Joseph County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Mishawaka\'s combination of affordable prices and genuine community character creates consistent buyer demand for motivated agents — RealtorFinder connects you with sellers ready to move.',
    },
    {
        slug: 'evansville',
        name: 'Evansville',
        county: 'Vanderburgh',
        state: 'IN',
        zip: '47708',
        population: '117000',
        median_price: '$165,000',
        price_trend: 'up 9%',
        avg_dom: 23,
        description: 'Evansville is Indiana\'s third-largest city and the economic capital of the tri-state region — a diverse economy anchored by Toyota\'s Indiana manufacturing plant, Berry Global, Old National Bank, and Deaconess and St. Vincent hospital systems supports some of Indiana\'s most affordable housing in distinctive neighborhoods like the Historic Haynie\'s Corner arts district, McCurdy Flats, and the established Far West Side suburban corridor.',
        neighborhoods: 'Haynie\'s Corner, McCurdy Flats, Far West Side, East Side, USI campus area, Jacobsville',
        nearby: 'Newburgh, Boonville, Henderson KY, Owensboro KY, Princeton',
        seller_hook: 'Evansville\'s stable multi-sector economy and rising prices create buyers motivated to act on well-positioned listings — let competing Vanderburgh County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Evansville\'s large population and tri-state economic significance create consistent listing opportunities for agents who know this market — RealtorFinder connects you with motivated sellers across Vanderburgh County.',
    },
];
