// cities/ks.js — Kansas city data for SEO landing pages

module.exports = [
    {
        slug: 'wichita',
        name: 'Wichita',
        county: 'Sedgwick',
        state: 'KS',
        zip: '67202',
        population: '397,000',
        median_price: '$210,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Wichita is the Air Capital of the World and Kansas\'s largest city — a Boeing, Cessna, and Textron Aviation hub where aerospace manufacturing employment, Wichita State University, and a revitalizing Old Town entertainment district create strong housing demand from engineers, aviation workers, and young professionals who find one of the Midwest\'s best value-to-lifestyle ratios.',
        neighborhoods: 'College Hill, Riverside, East Wichita, Delano, Crown Heights, Eastborough',
        nearby: 'Derby, Andover, Haysville, Bel Aire, Park City',
        seller_hook: 'Wichita\'s aerospace industry and Midwest affordability attract strong buyer demand year-round — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Wichita\'s aviation employer base and consistent appreciation create high-volume listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'overland-park',
        name: 'Overland Park',
        county: 'Johnson',
        state: 'KS',
        zip: '66210',
        population: '197,000',
        median_price: '$380,000',
        price_trend: 'up 6%',
        avg_dom: 20,
        description: 'Overland Park is Johnson County\'s largest city and consistently ranked among the nation\'s best places to live — a Kansas City suburb with nationally top-ranked schools, a thriving corporate corridor anchored by Sprint/T-Mobile and Black & Veatch, and master-planned neighborhoods that attract the region\'s highest-earning professionals seeking excellent schools and suburban luxury.',
        neighborhoods: 'Leawood, Blue Valley, Lenexa, Olathe, Prairie Village, Stilwell',
        nearby: 'Lenexa, Olathe, Leawood, Shawnee, Prairie Village',
        seller_hook: 'Overland Park\'s elite school district and corporate job base create intense buyer competition — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Overland Park\'s affluent buyer pool and fast-moving market make it Kansas\'s most lucrative listing suburb — find sellers through RealtorFinder.',
    },
    {
        slug: 'kansas-city-ks',
        name: 'Kansas City',
        county: 'Wyandotte',
        state: 'KS',
        zip: '66101',
        population: '156,000',
        median_price: '$195,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Kansas City, Kansas is experiencing a renaissance driven by Wyandotte County\'s major investments — the massive Village West entertainment district, the new Kansas City Current NWSL stadium, Hollywood Casino, and IKEA create visitor and economic traffic that drives housing demand in an urban market where prices remain dramatically below the Missouri side for comparable square footage.',
        neighborhoods: 'Rosedale, Argentine, Armourdale, Edwardsville, Turner, Bonner Springs',
        nearby: 'Bonner Springs, Edwardsville, Shawnee, Overland Park, Kansas City MO',
        seller_hook: 'Kansas City KS\'s Wyandotte County revitalization and affordability advantage attract strong buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'KCK\'s affordability and Village West investment create active listing conditions for value-savvy buyers — find sellers through RealtorFinder.',
    },
    {
        slug: 'olathe',
        name: 'Olathe',
        county: 'Johnson',
        state: 'KS',
        zip: '66061',
        population: '144,000',
        median_price: '$345,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Olathe is Johnson County\'s second-largest city and one of the fastest-growing suburbs in the Kansas City metro — a community where consistently top-ranked Olathe Unified School District schools, headquarters of Garmin International, and a booming logistics corridor along I-35 attract corporate employees, young families, and new construction buyers from across the region.',
        neighborhoods: 'Cedar Creek, Cobblestone, Heritage, Summerfield, Prairie Trace',
        nearby: 'Overland Park, Lenexa, Gardner, Spring Hill, Shawnee',
        seller_hook: 'Olathe\'s Garmin HQ and top schools drive multiple-offer conditions across all price ranges — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Olathe\'s Johnson County growth and family buyer demand create consistently fast-moving listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'topeka',
        name: 'Topeka',
        county: 'Shawnee',
        state: 'KS',
        zip: '66603',
        population: '127,000',
        median_price: '$175,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Topeka is Kansas\'s state capital and a government and healthcare hub — a community of historic Brown v. Board of Education significance where state government employment, Stormont Vail Health, and Washburn University anchor an affordable housing market drawing civil servants, medical professionals, and young families seeking some of the Midwest\'s lowest home prices.',
        neighborhoods: 'Potwin Place, College Hill, Westboro, Oakland, Curran Hills',
        nearby: 'Auburn, Silver Lake, Rossville, Wakarusa, Lawrence',
        seller_hook: 'Topeka\'s state capital stability and affordable prices attract a reliable buyer pool — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Topeka\'s government employment and healthcare economy create steady listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'shawnee-ks',
        name: 'Shawnee',
        county: 'Johnson',
        state: 'KS',
        zip: '66203',
        population: '68,000',
        median_price: '$310,000',
        price_trend: 'up 6%',
        avg_dom: 23,
        description: 'Shawnee is Johnson County\'s western suburb and one of the Kansas City metro\'s most desirable family destinations — a community where Mission Trail Park, Prairie Center, and top-rated Shawnee Mission School District schools attract professional families seeking newer construction, cul-de-sac neighborhoods, and quick I-435 access to downtown Kansas City.',
        neighborhoods: 'Clear Creek, Monticello, Woodland Hills, Stonebridge, Gleason Glen',
        nearby: 'Lenexa, Overland Park, Olathe, Merriam, Lenexa',
        seller_hook: 'Shawnee\'s Shawnee Mission schools and family buyer demand keep listings moving fast — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Shawnee\'s Johnson County location and consistent appreciation make it one of the KC metro\'s top listing markets — find sellers through RealtorFinder.',
    },
    {
        slug: 'manhattan-ks',
        name: 'Manhattan',
        county: 'Riley',
        state: 'KS',
        zip: '66502',
        population: '55,000',
        median_price: '$215,000',
        price_trend: 'up 4%',
        avg_dom: 32,
        description: 'Manhattan is the Little Apple and home to Kansas State University — a Flint Hills college city where K-State Wildcats football culture, Fort Riley military housing demand, and a robust agricultural research sector create a diverse housing market serving students, military families, and university professionals who value affordable living on the beautiful Kansas prairie.',
        neighborhoods: 'Aggieville, Bluemont, Candlewood, Sunningdale, Northeast Manhattan',
        nearby: 'Junction City, Salina, Abilene, Wamego, Ogden',
        seller_hook: 'Manhattan\'s K-State enrollment and Fort Riley community create reliable year-round buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Manhattan\'s university and military buyer mix create steady listing activity at accessible price points — find sellers through RealtorFinder.',
    },
    {
        slug: 'lawrence-ks',
        name: 'Lawrence',
        county: 'Douglas',
        state: 'KS',
        zip: '66044',
        population: '97,000',
        median_price: '$260,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Lawrence is home to the University of Kansas and one of the Midwest\'s most culturally vibrant college towns — a community where Massachusetts Street\'s independent shops and music venues, a historic Civil War heritage, and KU Jayhawks basketball create a tight housing market with strong rental demand, consistent appreciation, and a diverse buyer pool of students, faculty, and young creatives.',
        neighborhoods: 'Old West Lawrence, Oread, University Heights, Pinckney, East Lawrence',
        nearby: 'Topeka, Overland Park, Lecompton, Baldwin City, Ottawa',
        seller_hook: 'Lawrence\'s KU enrollment and cultural cachet drive consistent buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Lawrence\'s university market and rental demand create strong investment and owner-occupant listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'lenexa',
        name: 'Lenexa',
        county: 'Johnson',
        state: 'KS',
        zip: '66215',
        population: '57,000',
        median_price: '$330,000',
        price_trend: 'up 6%',
        avg_dom: 21,
        description: 'Lenexa is Johnson County\'s fastest-growing city — a Kansas City suburb where a thriving new City Center development, Shawnee Mission Medical Center proximity, and a booming warehouse and logistics corridor attract young professionals and families to master-planned communities with top-rated schools and quick access to both downtown Kansas City and suburban amenities.',
        neighborhoods: 'City Center, Falcon Valley, Prairie Highlands, Wilderness, Southgate',
        nearby: 'Overland Park, Olathe, Shawnee, Merriam, Clear Creek',
        seller_hook: 'Lenexa\'s City Center development and Johnson County demand drive fast-moving listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Lenexa\'s rapid growth and family buyer volume make it one of the KC metro\'s most active listing markets — find sellers through RealtorFinder.',
    },
];
