// cities/ky.js — Kentucky city data for SEO landing pages

module.exports = [
    {
        slug: 'louisville',
        name: 'Louisville',
        county: 'Jefferson',
        state: 'KY',
        zip: '40202',
        population: '633,000',
        median_price: '$240,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Louisville is Kentucky\'s largest city and one of the South\'s most underrated housing markets — a bourbon capital on the Ohio River where Churchill Downs, a thriving NuLu arts district, UPS\'s global hub, and a booming healthcare sector anchor an affordable and fast-appreciating market that attracts young professionals, families, and investors priced out of Nashville and Columbus.',
        neighborhoods: 'NuLu, Highlands, Crescent Hill, St. Matthews, Cherokee Triangle, Norton Commons, Prospect',
        nearby: 'Jeffersontown, Middletown, Shively, St. Matthews, Anchorage',
        seller_hook: 'Louisville\'s bourbon industry growth and young professional influx drive competitive buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Louisville\'s affordable prices and explosive appreciation attract buyers from across the Midwest — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'lexington',
        name: 'Lexington',
        county: 'Fayette',
        state: 'KY',
        zip: '40502',
        population: '322,000',
        median_price: '$285,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Lexington is the heart of Bluegrass Country and home to the University of Kentucky — a horse capital where bourbon tourism, a growing biomedical research sector, and one of the South\'s most walkable downtowns create a competitive housing market with strong appreciation, multiple-offer scenarios, and sustained demand from UK faculty, healthcare workers, and horse country transplants.',
        neighborhoods: 'Chevy Chase, Ashland Park, Beaumont, Hamburg, Lansdowne, Andover',
        nearby: 'Georgetown, Nicholasville, Winchester, Richmond, Paris',
        seller_hook: 'Lexington\'s UK enrollment and horse country prestige create a deep buyer pool — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Lexington\'s university market and Bluegrass premium drive consistent listing activity across all price ranges — find sellers through RealtorFinder.',
    },
    {
        slug: 'bowling-green-ky',
        name: 'Bowling Green',
        county: 'Warren',
        state: 'KY',
        zip: '42101',
        population: '74,000',
        median_price: '$225,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Bowling Green is Kentucky\'s third-largest city and a booming manufacturing hub — home of the Corvette and Western Kentucky University, anchored by GM\'s Bowling Green Assembly Plant and a growing Korean automotive supply chain that draws industrial workers, university students, and families seeking affordable homeownership in one of the state\'s most dynamic regional economies.',
        neighborhoods: 'Plano, Oakland, Smiths Grove, Franklin, Rich Pond',
        nearby: 'Franklin, Elizabethtown, Glasgow, Auburn, Scottsville',
        seller_hook: 'Bowling Green\'s manufacturing growth and WKU enrollment create strong and steady buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Bowling Green\'s automotive sector expansion and university market generate active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'owensboro',
        name: 'Owensboro',
        county: 'Daviess',
        state: 'KY',
        zip: '42301',
        population: '60,000',
        median_price: '$185,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Owensboro is western Kentucky\'s largest city and the self-proclaimed BBQ capital of the world — an Ohio River community where Owensboro Health Regional Hospital, Kentucky Wesleyan College, and a revitalized downtown riverfront park system make it one of the state\'s most livable small cities with some of Kentucky\'s most affordable single-family homes.',
        neighborhoods: 'Eastwood, Whitesville, Philpot, Maceo, Curdsville',
        nearby: 'Elizabethtown, Bowling Green, Henderson, Madisonville',
        seller_hook: 'Owensboro\'s riverfront revival and affordable prices attract a growing buyer pool — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Owensboro\'s affordable market and Ohio River appeal create steady listing opportunities — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'covington-ky',
        name: 'Covington',
        county: 'Kenton',
        state: 'KY',
        zip: '41011',
        population: '43,000',
        median_price: '$195,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Covington is northern Kentucky\'s most dynamic city — a Cincinnati suburb across the Ohio River where MainStrasse Village boutiques, a revitalized Roebling Bridge district, and some of the tri-state area\'s best home value attract Cincinnati commuters, urban buyers, and investors who get big-city access at a fraction of Ohio price tags.',
        neighborhoods: 'MainStrasse, Licking Riverside, Westside, Latonia, West Covington',
        nearby: 'Newport, Florence, Erlanger, Cincinnati OH, Edgewood',
        seller_hook: 'Covington\'s Cincinnati proximity and revitalized urban core drive strong buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Covington\'s cross-river buyer pool and rapid appreciation make it northern Kentucky\'s hottest listing market — find sellers through RealtorFinder.',
    },
    {
        slug: 'richmond-ky',
        name: 'Richmond',
        county: 'Madison',
        state: 'KY',
        zip: '40475',
        population: '35,000',
        median_price: '$210,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Richmond is home to Eastern Kentucky University and a fast-growing Lexington suburb — a college town 26 miles from downtown Lexington where EKU\'s 16,000 students, proximity to Toyota\'s Georgetown plant, and some of Kentucky\'s most affordable starter homes attract first-time buyers and investors seeking Bluegrass Region returns without Fayette County prices.',
        neighborhoods: 'EKU, Berea Road, Silver Creek, Lake Reba, Irvine Road',
        nearby: 'Berea, Lexington, Nicholasville, Winchester, Berea',
        seller_hook: 'Richmond\'s EKU enrollment and Lexington proximity drive consistent buyer activity — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Richmond\'s university market and affordable price points create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'florence-ky',
        name: 'Florence',
        county: 'Boone',
        state: 'KY',
        zip: '41042',
        population: '34,000',
        median_price: '$240,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Florence is Boone County\'s commercial hub and one of northern Kentucky\'s fastest-growing communities — a Cincinnati Airport suburb where Amazon, DHL, and UPS logistics operations, a booming retail corridor along US 42, and highly rated Boone County Schools attract commuters and families seeking Cincinnati metropolitan access at lower Kentucky tax rates.',
        neighborhoods: 'Union, Richwood, Verona, Tanner Station, Oakbrook',
        nearby: 'Erlanger, Covington, Union, Burlington, Hebron',
        seller_hook: 'Florence\'s Boone County schools and logistics employment attract families and investors alike — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Florence\'s northern Kentucky growth corridor and Cincinnati buyer demand create competitive listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'elizabethtown-ky',
        name: 'Elizabethtown',
        county: 'Hardin',
        state: 'KY',
        zip: '42701',
        population: '32,000',
        median_price: '$200,000',
        price_trend: 'up 5%',
        avg_dom: 34,
        description: 'Elizabethtown is the hub of Hardin County and the gateway to Fort Knox — a midpoint between Louisville and Bowling Green on I-65 where military families, Toyota plant workers, and retirees find affordable brick homes, top-ranked Hardin County schools, and a close-knit community spirit in one of Kentucky\'s most strategically located regional cities.',
        neighborhoods: 'Rineyville, Radcliff, Vine Grove, Cecilia, White Mills',
        nearby: 'Radcliff, Bardstown, Hodgenville, Leitchfield, Munfordville',
        seller_hook: 'Elizabethtown\'s Fort Knox community and I-65 corridor drive reliable buyer demand — let RealtorFinder agents compete for your listing.',
        realtor_hook: 'Elizabethtown\'s military families and central Kentucky location create consistent listing activity — connect with sellers through RealtorFinder.',
    },
];
