// cities/la.js — Louisiana city data for SEO landing pages

module.exports = [
    {
        slug: 'new-orleans',
        name: 'New Orleans',
        county: 'Orleans',
        state: 'LA',
        zip: '70112',
        population: '383,000',
        median_price: '$245,000',
        price_trend: 'up 4%',
        avg_dom: 45,
        description: 'New Orleans is America\'s most culturally distinctive city — a French Quarter jewel on the Mississippi River where Creole architecture, world-famous cuisine, a thriving music scene, and the nation\'s most exuberant festival calendar create a real estate market unlike any other, drawing buyers who prize historic charm, shotgun cottages, and Garden District grandeur at prices well below comparable cultural capitals.',
        neighborhoods: 'French Quarter, Garden District, Uptown, Mid-City, Marigny, Bywater, Lakeview, Algiers',
        nearby: 'Metairie, Kenner, Gretna, Harvey, Chalmette',
        seller_hook: 'New Orleans\' unique culture and tourism-driven demand attract buyers from across the country — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'New Orleans\' diverse price range and cultural cachet create year-round buyer interest — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'baton-rouge',
        name: 'Baton Rouge',
        county: 'East Baton Rouge',
        state: 'LA',
        zip: '70801',
        population: '228,000',
        median_price: '$220,000',
        price_trend: 'up 4%',
        avg_dom: 40,
        description: 'Baton Rouge is Louisiana\'s state capital and home to LSU — a petrochemical and government hub on the Mississippi River where Tiger Stadium football culture, a growing healthcare corridor, and affordable Acadian-style neighborhoods draw state workers, university faculty, and young professionals seeking southern living at accessible price points.',
        neighborhoods: 'Garden District, Perkins Road, Mid City, Broadmoor, Old South, Shenandoah, Sherwood Forest',
        nearby: 'Zachary, Prairieville, Gonzales, Denham Springs, Port Allen',
        seller_hook: 'Baton Rouge\'s government and university employer base drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Baton Rouge\'s state capital economy and LSU enrollment create steady listing activity across a broad price range — find sellers through RealtorFinder.',
    },
    {
        slug: 'shreveport',
        name: 'Shreveport',
        county: 'Caddo',
        state: 'LA',
        zip: '71101',
        population: '187,000',
        median_price: '$155,000',
        price_trend: 'up 3%',
        avg_dom: 50,
        description: 'Shreveport is northwest Louisiana\'s commercial hub and a growing film production center — anchored by Barksdale Air Force Base, LSU Health Sciences Center, and a riverboat casino industry along the Red River, offering some of the South\'s most affordable home prices with a revitalizing arts district and Sci-Port Discovery Center driving urban renewal.',
        neighborhoods: 'Broadmoor, Pierremont, Queensborough, South Highlands, Bossier City, Blanchard',
        nearby: 'Bossier City, Haughton, Benton, Minden, Natchitoches',
        seller_hook: 'Shreveport\'s military and medical employer base provide a steady buyer pool — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Shreveport\'s affordable price points and Barksdale AFB activity create consistent listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'metairie',
        name: 'Metairie',
        county: 'Jefferson',
        state: 'LA',
        zip: '70001',
        population: '143,000',
        median_price: '$270,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Metairie is New Orleans\' most established suburb in Jefferson Parish — a community of classic ranch homes, Lakeside Shopping Center, excellent schools, and lower flood risk than Orleans Parish that draws New Orleans professionals and families seeking suburban comfort with immediate access to the city\'s culture, cuisine, and employment.',
        neighborhoods: 'Old Metairie, Fat City, West Metairie, Bucktown, Lakeside, Lake Vista',
        nearby: 'New Orleans, Kenner, Harahan, River Ridge, Elmwood',
        seller_hook: 'Metairie\'s Jefferson Parish schools and New Orleans proximity drive strong buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Metairie\'s suburban appeal and New Orleans spillover buyers create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'lafayette-la',
        name: 'Lafayette',
        county: 'Lafayette',
        state: 'LA',
        zip: '70501',
        population: '131,000',
        median_price: '$230,000',
        price_trend: 'up 4%',
        avg_dom: 42,
        description: 'Lafayette is the capital of Cajun Country and Louisiana\'s fastest-growing metro — an oil and gas hub on the Vermilion River where University of Louisiana enrollment, world-renowned cuisine, and a tight-knit Acadian cultural identity draw energy industry workers, young professionals, and families who prize affordable homeownership in one of the South\'s most distinctive communities.',
        neighborhoods: 'Freetown, River Ranch, Oil Center, Youngsville, Broussard, Carencro',
        nearby: 'Broussard, Youngsville, Carencro, Breaux Bridge, Opelousas',
        seller_hook: 'Lafayette\'s Cajun culture and energy industry growth attract buyers from across the Gulf Coast — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Lafayette\'s energy economy and university market create consistent listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'lake-charles',
        name: 'Lake Charles',
        county: 'Calcasieu',
        state: 'LA',
        zip: '70601',
        population: '77,000',
        median_price: '$180,000',
        price_trend: 'up 3%',
        avg_dom: 48,
        description: 'Lake Charles is southwest Louisiana\'s petrochemical powerhouse and casino resort destination — an industrial city on the Calcasieu River with a booming LNG export sector and McNeese State University driving demand for affordable working-class housing and investment properties from energy workers earning above-average wages in a low cost-of-living market.',
        neighborhoods: 'Prien Lake, Downtown, Moss Bluff, Sulphur, Westlake',
        nearby: 'Sulphur, Westlake, Moss Bluff, Iowa, Jennings',
        seller_hook: 'Lake Charles\' energy industry wages and affordable prices attract motivated buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Lake Charles\' petrochemical sector and casino resort growth create consistent housing demand — find listing clients through RealtorFinder.',
    },
    {
        slug: 'kenner',
        name: 'Kenner',
        county: 'Jefferson',
        state: 'LA',
        zip: '70062',
        population: '67,000',
        median_price: '$200,000',
        price_trend: 'up 3%',
        avg_dom: 42,
        description: 'Kenner is Jefferson Parish\'s largest city and the home of Louis Armstrong New Orleans International Airport — an affordable lakefront community between New Orleans and Metairie where working families, airport employees, and transit-oriented buyers find ranches and newer construction at some of the metro\'s most accessible price points.',
        neighborhoods: 'Rivertown, Chateau Estates, Willowdale, Lake Kenner, Villa Lagoon',
        nearby: 'Metairie, New Orleans, Harahan, River Ridge, Destrehan',
        seller_hook: 'Kenner\'s affordability and airport proximity attract a wide buyer pool — let RealtorFinder agents compete for your listing.',
        realtor_hook: 'Kenner\'s affordable entry price and Jefferson Parish demand create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'bossier-city',
        name: 'Bossier City',
        county: 'Bossier',
        state: 'LA',
        zip: '71111',
        population: '68,000',
        median_price: '$175,000',
        price_trend: 'up 3%',
        avg_dom: 45,
        description: 'Bossier City sits across the Red River from Shreveport and is home to Barksdale Air Force Base — a military community and casino resort hub where VA loans dominate purchase activity, affordable brick ranches and new construction attract active-duty families and veterans, and prices among Louisiana\'s lowest give first-time buyers an exceptional entry point.',
        neighborhoods: 'Plantation Estates, Airline Drive, Old Bossier, North Bossier, Elm Grove',
        nearby: 'Shreveport, Haughton, Benton, Plain Dealing, Minden',
        seller_hook: 'Bossier City\'s Barksdale AFB community and VA buyers create reliable year-round demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Bossier City\'s military buyer pool and affordable market generate consistent listing and purchase activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'monroe-la',
        name: 'Monroe',
        county: 'Ouachita',
        state: 'LA',
        zip: '71201',
        population: '47,000',
        median_price: '$155,000',
        price_trend: 'up 2%',
        avg_dom: 55,
        description: 'Monroe is northeast Louisiana\'s commercial center and home to the University of Louisiana Monroe — a regional hub on the Ouachita River where healthcare, education, and a growing regional airport serve a wide catchment area, offering some of Louisiana\'s most affordable home prices to first-time buyers, medical professionals, and ULM students and faculty.',
        neighborhoods: 'Garden District, Forsythe Park, Richwood, West Monroe, Sterlington',
        nearby: 'West Monroe, Ruston, Bastrop, Farmerville, Natchitoches',
        seller_hook: 'Monroe\'s regional hub status and medical employer base generate steady buyer demand — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Monroe\'s university market and healthcare economy create consistent listing activity at accessible price points — find sellers through RealtorFinder.',
    },
    {
        slug: 'alexandria-la',
        name: 'Alexandria',
        county: 'Rapides',
        state: 'LA',
        zip: '71301',
        population: '47,000',
        median_price: '$160,000',
        price_trend: 'up 2%',
        avg_dom: 52,
        description: 'Alexandria is central Louisiana\'s largest city and the seat of Rapides Parish — a military and healthcare hub near England Airpark Business and Industrial District where Louisiana State University Alexandria, Cenla\'s growing medical corridor, and proximity to Fort Polk create demand for affordable housing among government workers, medical professionals, and military families.',
        neighborhoods: 'Pineville, Tioga, Ball, Boyce, Glenmora',
        nearby: 'Pineville, Boyce, Ball, Tioga, Natchitoches',
        seller_hook: 'Alexandria\'s military and medical employer base create a reliable buyer pool — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Alexandria\'s central Louisiana market and government employment drive steady listing activity — connect with sellers through RealtorFinder.',
    },
];
