// cities/ma-eastern.js — Eastern Massachusetts city data for SEO landing pages
// median_price: approximate 2024-2025 median single-family home price
// realtor_count: estimated active agents in area (used in copy)

module.exports = [
    // ── Boston Metro ──────────────────────────────────────────────────────────
    {
        slug: 'boston',
        name: 'Boston',
        county: 'Suffolk',
        state: 'MA',
        zip: '02101',
        population: '675,000',
        median_price: '$799,000',
        price_trend: 'up 8%',
        avg_dom: 18,
        description: 'The capital of Massachusetts and the economic and cultural engine of New England, Boston blends centuries of history with a dynamic innovation economy. From the stately brownstones of Beacon Hill to the vibrant restaurant scene of the South End and the waterfront revival of East Boston, every neighborhood offers a distinct flavor in one of the nation\'s most competitive housing markets.',
        neighborhoods: 'Back Bay, South End, Beacon Hill, Jamaica Plain, Dorchester, Roxbury, East Boston, Charlestown, South Boston, Fenway, Allston, Brighton',
        nearby: 'Cambridge, Brookline, Somerville, Quincy, Newton, Medford',
        seller_hook: 'Boston\'s relentless buyer demand and 18-day average market time mean your home deserves a realtor who will compete hard for your listing — RealtorFinder puts top Boston agents in a bidding war to earn your business.',
        realtor_hook: 'Boston generates more high-value listings per square mile than anywhere in New England — RealtorFinder connects you directly with motivated sellers across all 23 neighborhoods before they sign with someone else.',
    },
    {
        slug: 'cambridge',
        name: 'Cambridge',
        county: 'Middlesex',
        state: 'MA',
        zip: '02139',
        population: '118,000',
        median_price: '$899,000',
        price_trend: 'up 7%',
        avg_dom: 14,
        description: 'Home to Harvard University and MIT, Cambridge is a world-class intellectual hub with a fiercely competitive real estate market driven by academic professionals, biotech executives, and long-term residents who almost never leave. With a 14-day average on market, well-priced properties routinely draw a dozen or more offers within the first weekend.',
        neighborhoods: 'Harvard Square, Inman Square, Porter Square, Central Square, Kendall Square, East Cambridge, Cambridgeport, Agassiz',
        nearby: 'Boston, Somerville, Belmont, Watertown, Arlington',
        seller_hook: 'In Cambridge, the right realtor can mean the difference between one offer and ten — let agents compete on RealtorFinder to bring their best strategy to your home.',
        realtor_hook: 'Cambridge listings move in under two weeks and rarely sit — RealtorFinder gives you first access to sellers in one of the most sought-after ZIP codes in the country.',
    },
    {
        slug: 'brookline',
        name: 'Brookline',
        county: 'Norfolk',
        state: 'MA',
        zip: '02445',
        population: '63,000',
        median_price: '$1,250,000',
        price_trend: 'up 6%',
        avg_dom: 21,
        description: 'Brookline is Boston\'s premier inner suburb — a walkable, affluent town surrounded on three sides by the city, prized for its top-ranked public schools, the Green Line trolley, and a diverse mix of Victorian estates, Tudor revivals, and modern condominiums. Buyers here tend to be well-informed and decisive, making strong representation essential.',
        neighborhoods: 'Coolidge Corner, Washington Square, Brookline Village, Chestnut Hill, South Brookline, Pill Hill, Longwood',
        nearby: 'Boston, Newton, Cambridge, Chestnut Hill, Jamaica Plain',
        seller_hook: 'Brookline\'s $1.25M median price rewards sellers who choose their agent carefully — RealtorFinder lets multiple top-producing realtors compete for the right to sell your home.',
        realtor_hook: 'Brookline\'s affluent, educated buyer pool and premium price points make each listing an opportunity — get matched with motivated sellers on RealtorFinder before they call another agent.',
    },
    {
        slug: 'newton',
        name: 'Newton',
        county: 'Middlesex',
        state: 'MA',
        zip: '02458',
        population: '88,000',
        median_price: '$1,150,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'Newton is a city of thirteen distinct villages — each with its own center, character, and charm — anchored by some of the best public schools in Massachusetts. A perennial destination for Boston-area families upgrading from condos, Newton\'s broad tree-canopied streets and access to the Green Line D branch make it perennially in demand.',
        neighborhoods: 'Newton Centre, Newton Highlands, Newtonville, Chestnut Hill, Waban, West Newton, Auburndale, Newton Corner, Oak Hill',
        nearby: 'Brookline, Waltham, Wellesley, Needham, Watertown',
        seller_hook: 'Newton\'s desirability is perennial, but the right realtor makes the difference in a nuanced market — let agents compete on RealtorFinder to earn your listing with their best offer.',
        realtor_hook: 'Newton\'s thirteen villages and $1.15M median price create consistent high-value listing opportunities — RealtorFinder connects you with sellers who are ready to move.',
    },
    {
        slug: 'somerville',
        name: 'Somerville',
        county: 'Middlesex',
        state: 'MA',
        zip: '02143',
        population: '81,000',
        median_price: '$749,000',
        price_trend: 'up 9%',
        avg_dom: 15,
        description: 'Once known as "Slummerville," Somerville has transformed into one of Greater Boston\'s most vibrant and quickly appreciating cities. The Green Line Extension has turbocharged values near Union Square and Assembly Row, while Davis Square and Ball Square remain beloved destinations packed with restaurants, live music, and walkable neighborhood life.',
        neighborhoods: 'Davis Square, Union Square, Ball Square, Magoun Square, Assembly Row, Teele Square, East Somerville, Spring Hill',
        nearby: 'Cambridge, Medford, Malden, Arlington, Boston',
        seller_hook: 'Somerville\'s 9% annual appreciation and 15-day average market time mean buyer demand is fierce — RealtorFinder puts competitive realtors in a race to win your listing.',
        realtor_hook: 'Somerville is one of the fastest-appreciating markets in the Greater Boston metro — RealtorFinder gives you direct access to sellers in a city where every listing moves fast.',
    },
    {
        slug: 'quincy',
        name: 'Quincy',
        county: 'Norfolk',
        state: 'MA',
        zip: '02169',
        population: '101,000',
        median_price: '$529,000',
        price_trend: 'up 10%',
        avg_dom: 19,
        description: 'The "City of Presidents" and the birthplace of John Adams and John Quincy Adams, Quincy is a densely populated South Shore city with direct Red Line access to downtown Boston. Its broad range of housing stock — from triple-deckers in Quincy Center to waterfront homes in Squantum — draws first-time buyers, families, and Boston commuters alike.',
        neighborhoods: 'Quincy Center, Wollaston, Merrymount, North Quincy, Squantum, West Quincy, Germantown',
        nearby: 'Braintree, Weymouth, Milton, Boston, Randolph',
        seller_hook: 'Quincy\'s Red Line access and rising prices are drawing a new wave of Boston buyers — put realtors in competition on RealtorFinder to get the best representation for your home.',
        realtor_hook: 'Quincy\'s combination of Red Line commuter appeal, diverse housing stock, and 10% annual appreciation makes it a high-volume opportunity for focused agents.',
    },
    {
        slug: 'waltham',
        name: 'Waltham',
        county: 'Middlesex',
        state: 'MA',
        zip: '02451',
        population: '62,000',
        median_price: '$619,000',
        price_trend: 'up 8%',
        avg_dom: 17,
        description: 'Waltham punches well above its weight as a life sciences and tech hub, home to Brandeis University and a thriving Route 128 biotech corridor. Its working-class roots and genuine neighborhood identity — centered on Moody Street\'s restaurant strip — give Waltham a gritty authenticity that increasingly appeals to buyers priced out of Cambridge and Somerville.',
        neighborhoods: 'Waltham Center, South Side, Warrendale, Piety Corner, Prospect Hill, Northeast Waltham',
        nearby: 'Newton, Belmont, Lexington, Watertown, Cambridge',
        seller_hook: 'Waltham\'s biotech boom is driving professional buyer demand at every price point — let competing realtors on RealtorFinder fight for the right to represent your home.',
        realtor_hook: 'Waltham\'s Route 128 corridor generates a steady stream of high-earning buyers relocating for work — RealtorFinder connects you with sellers in this fast-moving market.',
    },
    {
        slug: 'medford',
        name: 'Medford',
        county: 'Middlesex',
        state: 'MA',
        zip: '02155',
        population: '57,000',
        median_price: '$669,000',
        price_trend: 'up 11%',
        avg_dom: 15,
        description: 'Medford is having a moment. Anchored by Tufts University and newly connected to the MBTA Green Line extension at Medford/Tufts and Ball Square stations, the city has seen explosive buyer interest from Boston and Cambridge spillover. Solid triple-deckers, converted condos, and single-family homes on tree-lined streets are moving in two weeks or less.',
        neighborhoods: 'Medford Square, West Medford, Wellington, Tufts University area, South Medford, Lawrence Estates',
        nearby: 'Somerville, Malden, Arlington, Cambridge, Woburn',
        seller_hook: 'Medford\'s new Green Line stations are fueling 11% annual appreciation — right now is the best time to sell, and RealtorFinder lets agents compete to earn your listing.',
        realtor_hook: 'Medford\'s Green Line connection has made it one of the hottest listings markets in the metro — RealtorFinder gets you in front of motivated sellers before someone else does.',
    },
    {
        slug: 'malden',
        name: 'Malden',
        county: 'Middlesex',
        state: 'MA',
        zip: '02148',
        population: '60,000',
        median_price: '$559,000',
        price_trend: 'up 13%',
        avg_dom: 16,
        description: 'Malden is Greater Boston\'s most underrated market, a diverse, transit-rich city on the Orange Line with the fastest home appreciation of any inner-ring suburb. A thriving downtown, rich immigrant community, and a wave of young buyers priced out of Somerville and Medford are fueling a boom that shows no signs of slowing.',
        neighborhoods: 'Malden Center, Edgeworth, Faulkner, Belmont Hill, Maplewood, Forestdale, Linden',
        nearby: 'Medford, Somerville, Everett, Melrose, Revere',
        seller_hook: 'At 13% annual appreciation, Malden sellers are capturing serious equity — RealtorFinder puts motivated realtors in competition to give your home the best possible outcome.',
        realtor_hook: 'Malden\'s 13% appreciation rate and 16-day market time signal one of the hottest opportunity zones in Greater Boston — secure your next listing through RealtorFinder.',
    },

    // ── North Shore ───────────────────────────────────────────────────────────
    {
        slug: 'salem',
        name: 'Salem',
        county: 'Essex',
        state: 'MA',
        zip: '01970',
        population: '44,000',
        median_price: '$479,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Salem is far more than its witch trial history — it\'s a thriving coastal city with a genuine arts scene, a year-round culinary culture, and a deeply walkable downtown anchored by the Peabody Essex Museum. The commuter rail to North Station makes it a legitimate Boston alternative, and buyers are discovering it fast.',
        neighborhoods: 'Derby Square, McIntire Historic District, Pickering Wharf, North Salem, South Salem, Witch Hill, Point neighborhood',
        nearby: 'Beverly, Peabody, Marblehead, Danvers, Lynn',
        seller_hook: 'Salem\'s combination of history, culture, and commuter rail access is attracting buyers from Boston and beyond — RealtorFinder lets top North Shore agents compete to sell your home.',
        realtor_hook: 'Salem\'s rising profile as a lifestyle destination is drawing a new class of buyers with serious budgets — RealtorFinder connects you with sellers in this fast-evolving market.',
    },
    {
        slug: 'lynn',
        name: 'Lynn',
        county: 'Essex',
        state: 'MA',
        zip: '01901',
        population: '102,000',
        median_price: '$389,000',
        price_trend: 'up 14%',
        avg_dom: 22,
        description: 'Lynn is the North Shore\'s biggest turnaround story. Once dismissed, this diverse coastal city is now one of the fastest-appreciating markets in Massachusetts, driven by affordability, direct commuter rail access to Boston, and a wave of buyers and investors recognizing its untapped potential along the Lynn Shore Reservation.',
        neighborhoods: 'Downtown Lynn, Wyoma Square, Lynn Woods, Brickyard, West Lynn, Diamond District, Lynn Shore',
        nearby: 'Salem, Saugus, Swampscott, Nahant, Revere',
        seller_hook: 'Lynn\'s 14% appreciation rate means your home may be worth significantly more than you realize — RealtorFinder puts knowledgeable realtors in competition to maximize your sale price.',
        realtor_hook: 'Lynn is the fastest-appreciating market on the North Shore and an entry-point for first-time buyers citywide — RealtorFinder gives you first access to a growing listing pipeline.',
    },
    {
        slug: 'beverly',
        name: 'Beverly',
        county: 'Essex',
        state: 'MA',
        zip: '01915',
        population: '43,000',
        median_price: '$509,000',
        price_trend: 'up 8%',
        avg_dom: 18,
        description: 'Beverly balances North Shore coastal charm with genuine residential substance, offering everything from oceanfront estates in Beverly Farms to starter colonials near the commuter rail. Endicott College, a vibrant downtown, and easy access to Route 128 make Beverly one of the most balanced communities on the North Shore.',
        neighborhoods: 'Beverly Farms, Prides Crossing, Montserrat, Ryal Side, Bass River, Beverly Cove, North Beverly',
        nearby: 'Salem, Danvers, Manchester-by-the-Sea, Gloucester, Wenham',
        seller_hook: 'Beverly\'s broad buyer appeal — from commuters to coastal lifestyle seekers — means strong competition for your listing. Let agents on RealtorFinder bid to represent your home.',
        realtor_hook: 'Beverly\'s diverse housing stock and steady 8% appreciation attract buyers at every price point — RealtorFinder connects you with sellers across all of Beverly\'s distinct neighborhoods.',
    },
    {
        slug: 'gloucester',
        name: 'Gloucester',
        county: 'Essex',
        state: 'MA',
        zip: '01930',
        population: '31,000',
        median_price: '$485,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'America\'s oldest seaport wears its working-harbor identity proudly — Gloucester smells like salt air and feels like a town that built itself around the ocean, not around a commute. Artists have gathered here since the 1800s, and today Rocky Neck\'s galleries and Gloucester\'s raw maritime character attract buyers seeking authenticity over polish.',
        neighborhoods: 'Rocky Neck, East Gloucester, Annisquam, West Gloucester, Magnolia, Stage Fort Park, Lanesville',
        nearby: 'Beverly, Rockport, Essex, Manchester-by-the-Sea, Ipswich',
        seller_hook: 'Gloucester\'s one-of-a-kind coastal character commands buyer loyalty you won\'t find elsewhere — RealtorFinder puts North Shore\'s best agents in competition to represent your home.',
        realtor_hook: 'Gloucester\'s artistic heritage and authentic maritime culture draw buyers who fall in love and move fast — RealtorFinder connects you with sellers in this irreplaceable market.',
    },
    {
        slug: 'newburyport',
        name: 'Newburyport',
        county: 'Essex',
        state: 'MA',
        zip: '01950',
        population: '18,000',
        median_price: '$679,000',
        price_trend: 'up 9%',
        avg_dom: 17,
        description: 'Newburyport is the North Shore\'s crown jewel — a beautifully preserved Federal-era brick downtown on the Merrimack River, with a restaurant scene that punches far above its size and a waterfront that draws buyers from Boston and beyond. Low inventory and strong demand from move-up buyers and Boston escapees keep competition fierce.',
        neighborhoods: 'Downtown waterfront, Joppa Flats, Plum Island area, South End, Newburyport Common, Moseley Woods',
        nearby: 'Amesbury, Salisbury, Rowley, West Newbury, Newbury',
        seller_hook: 'Newburyport\'s scarcity and desirability drive fierce competition among buyers — and among realtors. Let top agents compete on RealtorFinder to win your listing.',
        realtor_hook: 'Newburyport\'s limited inventory and premium prices make every listing a high-stakes opportunity — RealtorFinder connects you with sellers in the most coveted town on the North Shore.',
    },
    {
        slug: 'marblehead',
        name: 'Marblehead',
        county: 'Essex',
        state: 'MA',
        zip: '01945',
        population: '20,000',
        median_price: '$779,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Marblehead is a storied sailing town with one of the most picturesque harbors in New England and a compact historic core of 17th-century homes that have barely changed in three centuries. Its affluent year-round community and seasonal boating culture attract discerning buyers who plan their moves carefully and expect premium representation.',
        neighborhoods: 'Old Town, The Neck, Clifton, Marblehead Neck, Village, Devereux Beach area, Tedesco',
        nearby: 'Salem, Swampscott, Beverly, Lynn, Nahant',
        seller_hook: 'Marblehead\'s prestige market rewards careful preparation and expert representation — RealtorFinder lets elite North Shore agents compete to bring their best marketing to your home.',
        realtor_hook: 'Marblehead\'s waterfront estates and historic properties command the highest per-square-foot prices on the North Shore — RealtorFinder gives you access to sellers in this exclusive market.',
    },
    {
        slug: 'peabody',
        name: 'Peabody',
        county: 'Essex',
        state: 'MA',
        zip: '01960',
        population: '53,000',
        median_price: '$469,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Peabody is the North Shore\'s most practical suburb — centrally located between Salem and Route 128, with a broad mix of capes, ranches, and colonials that attract first-time buyers and families looking for value close to the coast. Its tanners\' legacy is long gone; in its place is a solid middle-class community with strong school enrollment.',
        neighborhoods: 'Peabody Square, South Peabody, West Peabody, North Peabody, Brooksby Farm area',
        nearby: 'Salem, Danvers, Beverly, Lynnfield, Saugus',
        seller_hook: 'Peabody\'s central North Shore location draws buyers from Salem, Beverly, and beyond — put experienced local realtors in competition on RealtorFinder to sell your home faster.',
        realtor_hook: 'Peabody\'s volume market and strong first-time buyer pool make it one of the most consistent listing territories on the North Shore — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'danvers',
        name: 'Danvers',
        county: 'Essex',
        state: 'MA',
        zip: '01923',
        population: '27,000',
        median_price: '$489,000',
        price_trend: 'up 8%',
        avg_dom: 19,
        description: 'Danvers is a well-kept secret on the North Shore — a suburban town with excellent schools, a manageable commute on Route 128, and a character shaped as much by its role as an early American farming community as by its proximity to Salem. Solid housing stock and steady appreciation make it a reliable choice for families and move-up buyers.',
        neighborhoods: 'Danvers Square, Putnamville, Tapleyville, Pine Street, Burley, Hathorne, Danversport',
        nearby: 'Salem, Beverly, Peabody, Middleton, Topsfield',
        seller_hook: 'Danvers\' excellent schools and Route 128 access bring qualified buyers consistently — RealtorFinder lets top local agents compete to represent your home with maximum exposure.',
        realtor_hook: 'Danvers\' combination of quality schools, steady appreciation, and strong family demand creates a predictable, profitable listing market for focused agents.',
    },
    {
        slug: 'ipswich',
        name: 'Ipswich',
        county: 'Essex',
        state: 'MA',
        zip: '01938',
        population: '14,000',
        median_price: '$549,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Ipswich is a North Shore gem where 17th-century saltbox homes share space with broad marshes, Crane Beach — one of the finest in New England — and a historic downtown with some of the oldest standing houses in America. Its small population and natural boundaries create a natural constraint on supply that keeps values steadily climbing.',
        neighborhoods: 'Ipswich Common, Linebrook, Castle Hill area, Great Neck, Heartbreak Road, Jeffreys Neck',
        nearby: 'Gloucester, Essex, Rowley, Newburyport, Topsfield',
        seller_hook: 'Ipswich\'s natural scarcity and coastal charm create real pricing power for sellers — let RealtorFinder\'s competing agents bring the best buyers and best terms to your sale.',
        realtor_hook: 'Ipswich\'s constrained supply and Crane Beach prestige attract buyers willing to wait for the right home — RealtorFinder connects you with motivated sellers in this distinctive market.',
    },

    // ── South Shore ───────────────────────────────────────────────────────────
    {
        slug: 'braintree',
        name: 'Braintree',
        county: 'Norfolk',
        state: 'MA',
        zip: '02184',
        population: '37,000',
        median_price: '$569,000',
        price_trend: 'up 8%',
        avg_dom: 18,
        description: 'Braintree sits at the junction of Routes 3 and 93, making it the most commuter-accessible town on the South Shore — with both Red Line and commuter rail service into Boston. Its solid ranches and split-levels draw steady buyer interest from families and Boston commuters who want space without sacrificing transit access.',
        neighborhoods: 'Braintree Highlands, East Braintree, South Braintree, Hollis Park, Weymouth Landing border',
        nearby: 'Quincy, Weymouth, Milton, Randolph, Holbrook',
        seller_hook: 'Braintree\'s transit access and steady buyer demand create ideal conditions for a competitive sale — let experienced realtors bid on RealtorFinder to represent your home.',
        realtor_hook: 'Braintree\'s dual transit access and strong family appeal generate consistent buyer demand throughout the year — RealtorFinder connects you with South Shore sellers ready to move.',
    },
    {
        slug: 'weymouth',
        name: 'Weymouth',
        county: 'Norfolk',
        state: 'MA',
        zip: '02188',
        population: '56,000',
        median_price: '$479,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Weymouth is the South Shore\'s largest town, a broad coastal community with varied neighborhoods stretching from the harborside bustle of Weymouth Landing to the quiet residential streets of South Weymouth near the former naval air station. Its affordability and commuter rail access keep buyer demand strong year-round.',
        neighborhoods: 'South Weymouth, East Weymouth, Weymouth Landing, North Weymouth, Jackson Square, Weymouth Back River',
        nearby: 'Braintree, Quincy, Hingham, Abington, Rockland',
        seller_hook: 'Weymouth\'s combination of affordability and commuter rail access drives real buyer competition — put top South Shore realtors in a bidding war on RealtorFinder to represent your home.',
        realtor_hook: 'Weymouth\'s large population and diverse housing stock generate more listing activity than almost any other South Shore town — RealtorFinder helps you get there first.',
    },
    {
        slug: 'plymouth',
        name: 'Plymouth',
        county: 'Plymouth',
        state: 'MA',
        zip: '02360',
        population: '61,000',
        median_price: '$429,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'America\'s hometown has evolved far beyond Plymouth Rock and the Mayflower. Today\'s Plymouth is a sprawling coastal community where oceanfront neighborhoods, pine-forest subdivisions, and a revitalized downtown waterfront all compete for buyer attention. Growing year-round population, expanding Route 44 commercial corridors, and ferry service to Provincetown add to its appeal.',
        neighborhoods: 'Plymouth Center, Cedarville, Manomet, Ellisville, South Plymouth, West Plymouth, Chiltonville',
        nearby: 'Carver, Kingston, Duxbury, Marshfield, Bourne',
        seller_hook: 'Plymouth\'s expanding buyer pool and waterfront appeal are driving 10% annual appreciation — RealtorFinder lets motivated agents compete to bring the best sale strategy to your home.',
        realtor_hook: 'Plymouth is one of the largest and fastest-growing markets on the South Shore, with diverse buyer demand from commuters to retirees — RealtorFinder keeps your pipeline full.',
    },
    {
        slug: 'hingham',
        name: 'Hingham',
        county: 'Plymouth',
        state: 'MA',
        zip: '02043',
        population: '24,000',
        median_price: '$849,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'Hingham is the South Shore\'s prestige address — a beautiful harbor town with a meticulously preserved historic square, top-tier schools, and direct ferry service to downtown Boston from Rowes Wharf. Its blend of seaside elegance and genuine small-town character attracts Boston executives, growing families, and move-up buyers from across the South Shore.',
        neighborhoods: 'Hingham Center, South Hingham, Crow Point, East Hingham, World\'s End, North Hingham, Wompatuck',
        nearby: 'Cohasset, Scituate, Weymouth, Norwell, Marshfield',
        seller_hook: 'Hingham\'s ferry service and prestige pricing attract buyers with means and motivation — let elite South Shore realtors compete on RealtorFinder to represent your home at full value.',
        realtor_hook: 'Hingham\'s $849K median price and Boston ferry access make it one of the most valuable listing markets on the South Shore — RealtorFinder gives you direct access to sellers here.',
    },
    {
        slug: 'scituate',
        name: 'Scituate',
        county: 'Plymouth',
        state: 'MA',
        zip: '02066',
        population: '19,000',
        median_price: '$679,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Scituate is a quintessential South Shore coastal town, with a working harbor, extensive beachfront, and a deeply connected year-round community. Known for its lighthouse, its independent local businesses along Front Street, and its distinctive sea-captain heritage, Scituate draws buyers who prioritize authentic coastal living over suburban convenience.',
        neighborhoods: 'Scituate Harbor, Greenbush, Humarock, Egypt Beach, North Scituate, Minot, Sand Hills',
        nearby: 'Marshfield, Hingham, Norwell, Cohasset, Duxbury',
        seller_hook: 'Scituate\'s coastal character and year-round community make it a top destination for motivated buyers — put competing realtors on RealtorFinder to work securing your best sale.',
        realtor_hook: 'Scituate\'s genuine harbor culture and beach access draw buyers who research deeply and commit fully — RealtorFinder connects you with sellers in this devoted community.',
    },
    {
        slug: 'marshfield',
        name: 'Marshfield',
        county: 'Plymouth',
        state: 'MA',
        zip: '02050',
        population: '25,000',
        median_price: '$549,000',
        price_trend: 'up 9%',
        avg_dom: 23,
        description: 'Marshfield stretches from Route 139\'s commercial corridor to some of the longest barrier beach on the South Shore, with barrier beach communities at Green Harbor, Brant Rock, and Ocean Bluff that feel a world away from Boston. Its combination of beach access, good schools, and relative affordability draw buyers from across the metro.',
        neighborhoods: 'Marshfield Hills, Humarock, Green Harbor, Brant Rock, Ocean Bluff, Marshfield Center, Two Mile',
        nearby: 'Scituate, Duxbury, Plymouth, Pembroke, Norwell',
        seller_hook: 'Marshfield\'s beach access and steady appreciation are drawing Boston buyers in numbers — RealtorFinder puts the best South Shore agents in competition to sell your home.',
        realtor_hook: 'Marshfield\'s diverse beach communities and strong family appeal generate consistent year-round buyer traffic — RealtorFinder gets you in front of sellers before they list elsewhere.',
    },
    {
        slug: 'duxbury',
        name: 'Duxbury',
        county: 'Plymouth',
        state: 'MA',
        zip: '02332',
        population: '15,000',
        median_price: '$749,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Duxbury is the South Shore\'s most coveted small town — a sailing community with one of the longest sandy beaches in New England, exceptional public schools, and a historic character rooted in Pilgrim heritage. Its limited inventory, strict zoning, and devoted year-round residents create a market where prepared buyers act quickly and sellers hold significant leverage.',
        neighborhoods: 'Duxbury Beach, Standish Shore, Island Creek, Powder Point, Millbrook, South Duxbury',
        nearby: 'Marshfield, Plymouth, Kingston, Pembroke, Scituate',
        seller_hook: 'Duxbury\'s constrained supply and strong buyer demand mean well-priced homes move fast — let top South Shore agents compete on RealtorFinder to bring you the best offer.',
        realtor_hook: 'Duxbury\'s prestige, scarcity, and $749K median price make every listing an event — RealtorFinder connects you with serious sellers in one of the South Shore\'s most desirable communities.',
    },
    {
        slug: 'cohasset',
        name: 'Cohasset',
        county: 'Norfolk',
        state: 'MA',
        zip: '02025',
        population: '8,500',
        median_price: '$949,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Cohasset is the South Shore\'s most exclusive enclave — a small harbor town of rocky coves, elegant sea captains\' homes, and one of the most storied yacht club communities in New England. Its nearly closed social character and extremely limited housing supply create a market where patient buyers wait years for the right property to come available.',
        neighborhoods: 'Cohasset Harbor, Jerusalem Road, Sandy Beach area, King Street, Beechwood, Border Street waterfront',
        nearby: 'Hingham, Scituate, Marshfield, Hull, Norwell',
        seller_hook: 'Cohasset\'s rarity and $949K median price mean the stakes of choosing the right realtor couldn\'t be higher — RealtorFinder lets only the best agents compete for your listing.',
        realtor_hook: 'Cohasset listings are rare, coveted, and command the highest prices on the South Shore — RealtorFinder gives you early access to sellers in this nearly closed market.',
    },

    // ── MetroWest & Central ───────────────────────────────────────────────────
    {
        slug: 'framingham',
        name: 'Framingham',
        county: 'Middlesex',
        state: 'MA',
        zip: '01701',
        population: '72,000',
        median_price: '$519,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'Framingham is MetroWest\'s largest city and its economic backbone — a diverse, dynamic community anchored by a strong Brazilian-American community, two commuter rail lines, and the Framingham State University campus. From the walkable revived downtown to the quiet cul-de-sacs of Nobscot and Edgell Road, Framingham offers remarkable range for buyers of every profile.',
        neighborhoods: 'Downtown Framingham, Saxonville, Nobscot, South Framingham, Edgell Road, Nevins area, Potter Road',
        nearby: 'Natick, Ashland, Holliston, Marlborough, Sudbury',
        seller_hook: 'Framingham\'s diverse buyer pool and dual rail access create consistent, competitive demand — RealtorFinder puts motivated MetroWest agents in a bidding war to represent your home.',
        realtor_hook: 'Framingham\'s large, diverse population and strong appreciation generate more annual listings than any other MetroWest community — RealtorFinder keeps your pipeline full.',
    },
    {
        slug: 'natick',
        name: 'Natick',
        county: 'Middlesex',
        state: 'MA',
        zip: '01760',
        population: '36,000',
        median_price: '$619,000',
        price_trend: 'up 7%',
        avg_dom: 17,
        description: 'Natick is MetroWest\'s most well-rounded community — home to top-ranked schools, the sprawling Natick Mall corridor, and a charming South Natick village on the Charles River that feels closer to a Connecticut estate town than a suburb. Commuter rail access and strong school rankings make Natick a perennial target for Boston-area families.',
        neighborhoods: 'Natick Center, South Natick, Felchville, East Natick, West Natick, Cochituate',
        nearby: 'Framingham, Wayland, Wellesley, Ashland, Sherborn',
        seller_hook: 'Natick\'s top schools and commuter rail access drive serious buyer demand — let competing realtors on RealtorFinder bring their best strategies to your home sale.',
        realtor_hook: 'Natick\'s school reputation creates predictable, recurring buyer demand from growing Boston-area families — RealtorFinder connects you with motivated sellers in this reliable market.',
    },
    {
        slug: 'marlborough',
        name: 'Marlborough',
        county: 'Middlesex',
        state: 'MA',
        zip: '01752',
        population: '39,000',
        median_price: '$409,000',
        price_trend: 'up 10%',
        avg_dom: 19,
        description: 'Marlborough is MetroWest\'s most affordable entry point — a Route 495-corridor city with a genuine downtown, strong manufacturing and tech employment base, and housing prices that still allow first-time buyers to get into Middlesex County. Its rapid appreciation signals that the market is discovering what insiders have known for years.',
        neighborhoods: 'Downtown Marlborough, Marlborough Hills, Northborough Road, East Marlborough, Briarwood',
        nearby: 'Hudson, Northborough, Southborough, Framingham, Hudson',
        seller_hook: 'Marlborough\'s 10% appreciation is accelerating and buyers are arriving fast — RealtorFinder puts competitive local agents in a race to represent your home while the market is hot.',
        realtor_hook: 'Marlborough\'s Route 495 location and affordability are pulling buyers from across MetroWest — RealtorFinder gives you early access to sellers in one of the region\'s fastest-rising markets.',
    },
    {
        slug: 'worcester',
        name: 'Worcester',
        county: 'Worcester',
        state: 'MA',
        zip: '01601',
        population: '185,000',
        median_price: '$309,000',
        price_trend: 'up 12%',
        avg_dom: 21,
        description: 'Worcester is Massachusetts\' second-largest city and its most undervalued major market — a gritty, resilient city undergoing genuine revival around a biomedical corridor anchored by UMass Medical School and a revitalized downtown fueled by the Worcester Red Sox\'s Polar Park development. Investors and first-time buyers are arriving in numbers.',
        neighborhoods: 'Main South, Tatnuck Square, Great Brook Valley, Indian Lake, Shrewsbury Street, Grafton Hill, Burncoat, Lincoln Square',
        nearby: 'Shrewsbury, Auburn, Millbury, Holden, Leicester',
        seller_hook: 'Worcester\'s 12% appreciation and surging buyer demand from Boston spillover create real pricing power for sellers — let competitive realtors on RealtorFinder fight for your listing.',
        realtor_hook: 'Worcester is the fastest-appreciating major city in Massachusetts — a high-volume, high-growth market where RealtorFinder gives you direct access to motivated sellers.',
    },
    {
        slug: 'shrewsbury',
        name: 'Shrewsbury',
        county: 'Worcester',
        state: 'MA',
        zip: '01545',
        population: '37,000',
        median_price: '$489,000',
        price_trend: 'up 9%',
        avg_dom: 19,
        description: 'Shrewsbury is Worcester County\'s most desirable suburb — a wealthy, lakeside town with routinely top-ranked schools, Lake Quinsigamond waterfront, and a broad base of biomedical and tech professionals from nearby UMass Medical and Route 9 employers. Its combination of suburban polish and relative affordability to eastern MA suburbs fuels consistent demand.',
        neighborhoods: 'Shrewsbury Center, Lake Quinsigamond, White City, Edgemere, Grafton Street area, North Shrewsbury',
        nearby: 'Worcester, Westborough, Northborough, Boylston, Grafton',
        seller_hook: 'Shrewsbury\'s top schools and lake access attract well-qualified buyers year-round — RealtorFinder puts motivated Worcester County agents in competition to represent your home.',
        realtor_hook: 'Shrewsbury\'s school rankings and lake access create steady demand from Boston-area move-in buyers — RealtorFinder connects you with sellers in Worcester\'s most coveted suburb.',
    },
    {
        slug: 'milford',
        name: 'Milford',
        county: 'Worcester',
        state: 'MA',
        zip: '01757',
        population: '28,000',
        median_price: '$389,000',
        price_trend: 'up 10%',
        avg_dom: 20,
        description: 'Milford is a Route 495 corridor town with a strong Italian-American heritage, genuine civic pride, and a housing market that has outperformed its price point for years. The town\'s well-maintained neighborhoods, strong local economy, and proximity to both MetroWest and the Massachusetts Turnpike make it a smart choice for buyers who do their homework.',
        neighborhoods: 'Milford Center, Cedar Street, Fino Field area, East Milford, Walnut Hills',
        nearby: 'Hopkinton, Holliston, Hopedale, Medway, Upton',
        seller_hook: 'Milford\'s rising profile and 10% appreciation are bringing buyers from MetroWest and beyond — RealtorFinder puts the best local agents in competition to get you top dollar.',
        realtor_hook: 'Milford\'s affordability and Route 495 access are drawing buyers priced out of MetroWest — RealtorFinder connects you with sellers in a market delivering strong returns.',
    },
    {
        slug: 'lowell',
        name: 'Lowell',
        county: 'Middlesex',
        state: 'MA',
        zip: '01850',
        population: '115,000',
        median_price: '$349,000',
        price_trend: 'up 13%',
        avg_dom: 20,
        description: 'Lowell is Massachusetts\' most dramatically improving market — a large, diverse former mill city that has transformed itself around UMass Lowell, a growing arts scene in the nationally recognized Lowell National Historical Park, and commuter rail access that is making it one of the Boston metro\'s most attractive affordable options for buyers.',
        neighborhoods: 'Centralville, Acre, Pawtucketville, Belvidere, Back Central, South Lowell, Highlands',
        nearby: 'Chelmsford, Dracut, Tewksbury, Billerica, Tyngsborough',
        seller_hook: 'Lowell\'s 13% appreciation and growing buyer demand mean the window for maximizing your sale price is open now — let competing realtors on RealtorFinder fight for your listing.',
        realtor_hook: 'Lowell is the fastest-appreciating large city in Middlesex County — a high-volume, high-growth market where early-mover agents capture the most listings through RealtorFinder.',
    },
    {
        slug: 'chelmsford',
        name: 'Chelmsford',
        county: 'Middlesex',
        state: 'MA',
        zip: '01824',
        population: '36,000',
        median_price: '$479,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'Chelmsford is a well-balanced suburban town in the Merrimack Valley, offering excellent schools, good highway access on Routes 3 and 495, and a variety of housing styles that appeal to families and commuters from the Lowell-Boston corridor. Its quiet, well-managed neighborhoods have earned a reputation for strong school performance and community cohesion.',
        neighborhoods: 'Chelmsford Center, South Chelmsford, North Chelmsford, West Chelmsford, Vinal Square',
        nearby: 'Lowell, Billerica, Westford, Tewksbury, Littleton',
        seller_hook: 'Chelmsford\'s school reputation and route access bring steady, qualified buyer traffic — RealtorFinder puts competitive local realtors in a bidding war to represent your home.',
        realtor_hook: 'Chelmsford\'s reliable demand from Lowell and Boston corridor buyers creates a consistent listing market — RealtorFinder helps you connect with motivated sellers ahead of the competition.',
    },
    {
        slug: 'fitchburg',
        name: 'Fitchburg',
        county: 'Worcester',
        state: 'MA',
        zip: '01420',
        population: '40,000',
        median_price: '$279,000',
        price_trend: 'up 14%',
        avg_dom: 24,
        description: 'Fitchburg is one of Massachusetts\' most affordable cities and one of its fastest-improving, anchored by Fitchburg State University and positioned along the MBTA Fitchburg/South Acton commuter rail line that has suddenly made it a viable Boston commuter option for budget-conscious buyers. Investors and first-time buyers are arriving from across the state.',
        neighborhoods: 'Downtown Fitchburg, Cleghorn, Westminster Hill, South Fitchburg, Rollstone Hill',
        nearby: 'Leominster, Gardner, Lunenburg, Westminster, Ashby',
        seller_hook: 'Fitchburg\'s commuter rail access and 14% appreciation are bringing Boston-area buyers to your doorstep — RealtorFinder puts motivated agents in competition to maximize your sale price.',
        realtor_hook: 'Fitchburg is the fastest-appreciating affordable market in north-central Massachusetts — RealtorFinder connects you with sellers in a city where buyer demand is finally catching up.',
    },
    {
        slug: 'gardner',
        name: 'Gardner',
        county: 'Worcester',
        state: 'MA',
        zip: '01440',
        population: '21,000',
        median_price: '$249,000',
        price_trend: 'up 13%',
        avg_dom: 26,
        description: 'Gardner — once the "Chair City" of America for its 19th-century furniture manufacturing — is now one of Massachusetts\' most surprising emerging markets, with the state\'s most affordable home prices outside of Springfield and a strong outdoor recreation culture centered on Dunn Pond and the Otter River State Forest.',
        neighborhoods: 'Gardner Center, Myrtle Street, South Gardner, West Gardner, Timpany Boulevard area',
        nearby: 'Leominster, Fitchburg, Templeton, Winchendon, Westminster',
        seller_hook: 'Gardner\'s affordability is drawing buyers from across the state in a way that hasn\'t been seen in decades — RealtorFinder puts motivated agents in competition to get the most for your home.',
        realtor_hook: 'Gardner\'s sub-$250K entry point is drawing investor and first-time buyer demand from far beyond Worcester County — RealtorFinder keeps you ahead of a rapidly growing listing market.',
    },

    // ── Cape Cod ──────────────────────────────────────────────────────────────
    {
        slug: 'barnstable',
        name: 'Barnstable',
        county: 'Barnstable',
        state: 'MA',
        zip: '02601',
        population: '45,000',
        median_price: '$529,000',
        price_trend: 'up 12%',
        avg_dom: 25,
        description: 'Barnstable is the county seat and largest town on Cape Cod, encompassing seven distinct villages — from the tourist bustle of Hyannis to the tucked-away estates of Osterville, the quiet sophistication of Cotuit, and the historic lanes of Barnstable Village. Its diversity of character within a single town gives buyers an unusual range of options at every price point.',
        neighborhoods: 'Hyannis, Osterville, Centerville, Cotuit, Marstons Mills, Barnstable Village, West Barnstable',
        nearby: 'Sandwich, Yarmouth, Mashpee, Falmouth, Dennis',
        seller_hook: 'Barnstable\'s seven-village diversity means buyers from every income level are competing for homes here — RealtorFinder puts the Cape\'s best agents in a bidding war to represent yours.',
        realtor_hook: 'Barnstable is the Cape\'s largest listing market — seven villages, multiple price points, and 12% annual appreciation make it the highest-opportunity territory on Cape Cod.',
    },
    {
        slug: 'falmouth',
        name: 'Falmouth',
        county: 'Barnstable',
        state: 'MA',
        zip: '02540',
        population: '32,000',
        median_price: '$549,000',
        price_trend: 'up 11%',
        avg_dom: 24,
        description: 'Falmouth anchors the Upper Cape with eleven distinct villages, twelve miles of sandy beaches, the renowned Woods Hole Oceanographic Institution, and a vibrant Main Street that is home to the best year-round dining and culture on this end of the Cape. Ferry service to Martha\'s Vineyard adds to its year-round appeal and investment value.',
        neighborhoods: 'Falmouth Village, Woods Hole, East Falmouth, North Falmouth, Teaticket, Waquoit, West Falmouth, Sippewissett',
        nearby: 'Sandwich, Mashpee, Bourne, Woods Hole, Martha\'s Vineyard ferry',
        seller_hook: 'Falmouth\'s eleven villages and Vineyard ferry access attract buyers with reach and resources — RealtorFinder puts top Cape agents in competition to bring you the best possible sale.',
        realtor_hook: 'Falmouth\'s diverse villages and year-round buyer demand from Boston and Providence make it one of the Cape\'s most consistent listing markets — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'sandwich',
        name: 'Sandwich',
        county: 'Barnstable',
        state: 'MA',
        zip: '02563',
        population: '20,000',
        median_price: '$489,000',
        price_trend: 'up 9%',
        avg_dom: 25,
        description: 'Sandwich is the Cape\'s oldest town, settled in 1637, and its historic character is evident in every detail — from the 19th-century glassworks heritage preserved at the Sandwich Glass Museum to the shingle-style cottages along Route 6A. Its position at the Canal makes it the first and last town on the Cape, giving it easy mainland access and genuine small-town charm.',
        neighborhoods: 'Sandwich Village, Forestdale, East Sandwich, Springhill, South Sandwich, Sagamore Beach',
        nearby: 'Falmouth, Bourne, Barnstable, Mashpee, Sagamore',
        seller_hook: 'Sandwich\'s history and canal access bring buyers who move with intention and conviction — RealtorFinder puts experienced Cape agents in competition to represent your home.',
        realtor_hook: 'Sandwich\'s gateway position and historic character attract a loyal buyer base — RealtorFinder connects you with sellers in the Cape\'s oldest and most characterful town.',
    },
    {
        slug: 'yarmouth',
        name: 'Yarmouth',
        county: 'Barnstable',
        state: 'MA',
        zip: '02664',
        population: '24,000',
        median_price: '$419,000',
        price_trend: 'up 10%',
        avg_dom: 28,
        description: 'Yarmouth spans the full width of the Cape, from the boutique antique shops and historic captains\' houses along the Old King\'s Highway (Route 6A) in Yarmouth Port to the family beach and miniature golf culture of West and South Yarmouth. This contrast — genteel north side meets lively south side — makes it one of the Cape\'s most varied towns.',
        neighborhoods: 'South Yarmouth, West Yarmouth, Yarmouth Port, Bass River, Hyannis border area',
        nearby: 'Barnstable, Dennis, Harwich, Dennis Port, Hyannis',
        seller_hook: 'Yarmouth\'s dual character draws buyers from both ends of the Cape spectrum — RealtorFinder puts competitive local agents in a bidding war to represent your home with maximum reach.',
        realtor_hook: 'Yarmouth\'s broad geographic span and varied housing stock create strong listing volume on both sides of the Cape — RealtorFinder gets you in front of motivated sellers year-round.',
    },
    {
        slug: 'dennis',
        name: 'Dennis',
        county: 'Barnstable',
        state: 'MA',
        zip: '02638',
        population: '14,000',
        median_price: '$449,000',
        price_trend: 'up 10%',
        avg_dom: 27,
        description: 'Dennis is a mid-Cape gem — five distinct villages stretching from the bayside bluffs of Dennis Village to the surf-side energy of Dennis Port on Nantucket Sound. The Cape Playhouse, the oldest professional summer theater in the nation, gives Dennis a cultural identity that sets it apart from its neighbors, attracting arts-oriented buyers who plan their moves carefully.',
        neighborhoods: 'Dennis Village, East Dennis, South Dennis, West Dennis, Dennis Port',
        nearby: 'Yarmouth, Harwich, Brewster, Barnstable, Chatham',
        seller_hook: 'Dennis\'s distinctive villages and arts culture attract buyers who value character over convenience — RealtorFinder puts the Cape\'s most knowledgeable agents in competition to sell your home.',
        realtor_hook: 'Dennis\'s five-village layout and arts-community character create a loyal buyer base that returns year after year — RealtorFinder connects you with motivated sellers across all of them.',
    },
    {
        slug: 'harwich',
        name: 'Harwich',
        county: 'Barnstable',
        state: 'MA',
        zip: '02645',
        population: '13,000',
        median_price: '$479,000',
        price_trend: 'up 9%',
        avg_dom: 28,
        description: 'Harwich is a classic mid-Cape town where cranberry bogs still dot the interior landscape and Harwich Port\'s nautical character gives the south side a genuine working-harbor feel. Popular with buyers seeking a quieter Cape experience away from the Barnstable commercial corridor, Harwich offers solid value and a committed year-round community.',
        neighborhoods: 'Harwich Port, East Harwich, West Harwich, Harwich Center, Pleasant Lake',
        nearby: 'Dennis, Chatham, Brewster, Orleans, Dennis Port',
        seller_hook: 'Harwich\'s authentic Cape character and steady appreciation attract buyers who know what they want — RealtorFinder puts experienced mid-Cape agents in competition to represent your home.',
        realtor_hook: 'Harwich\'s cranberry-and-harbor character draws a devoted buyer base with strong purchasing intent — RealtorFinder connects you with sellers in this genuine Cape community.',
    },
    {
        slug: 'chatham',
        name: 'Chatham',
        county: 'Barnstable',
        state: 'MA',
        zip: '02633',
        population: '7,000',
        median_price: '$749,000',
        price_trend: 'up 8%',
        avg_dom: 30,
        description: 'Chatham occupies the Cape\'s elbow — a town of dramatic barrier beaches, seal colonies, a beloved working lighthouse, and a Main Street of shingle-style shops that has been drawing discerning buyers for generations. It is the Cape\'s prestige address for those who prefer restraint over excess, and its market reflects that — careful, deliberate, and commanding premium prices.',
        neighborhoods: 'Chatham Village, North Chatham, South Chatham, West Chatham, Stage Harbor, Chatham Bars',
        nearby: 'Harwich, Orleans, Brewster, Monomoy, Eastham',
        seller_hook: 'Chatham\'s prestige and barrier-beach scarcity create real pricing power — RealtorFinder connects you with elite Cape agents who compete to bring the Cape\'s most motivated buyers to your door.',
        realtor_hook: 'Chatham\'s $749K median and scarcity-driven market mean every listing is an event — RealtorFinder gives you first access to sellers in the Cape\'s most coveted address.',
    },
    {
        slug: 'orleans',
        name: 'Orleans',
        county: 'Barnstable',
        state: 'MA',
        zip: '02653',
        population: '6,000',
        median_price: '$649,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Orleans sits at the crossroads of the Cape — the last town before the National Seashore begins in earnest and the gateway to the Outer Cape\'s wild landscapes. Its compact Main Street, Rock Harbor sunset views, and proximity to both Nauset Beach and Pleasant Bay give Orleans a geographic drama that buyers seek out specifically, making it a highly intentional market.',
        neighborhoods: 'Orleans Center, East Orleans, South Orleans, Rock Harbor, Skaket Beach area',
        nearby: 'Chatham, Brewster, Eastham, Harwich, Provincetown corridor',
        seller_hook: 'Orleans\'s unique position at the gateway to the National Seashore draws buyers who have been dreaming of this location for years — let competing agents on RealtorFinder bring them to your door.',
        realtor_hook: 'Orleans buyers are the Cape\'s most intentional — they come prepared and move fast when the right property appears. RealtorFinder connects you with sellers in this high-conviction market.',
    },
    {
        slug: 'brewster',
        name: 'Brewster',
        county: 'Barnstable',
        state: 'MA',
        zip: '02631',
        population: '10,000',
        median_price: '$529,000',
        price_trend: 'up 8%',
        avg_dom: 29,
        description: 'Brewster is the Cape\'s most naturally beautiful town — a community of kettle ponds, tidal flats that stretch a mile at low tide, and a historic Route 6A lined with sea captains\' mansions turned bed and breakfasts. Its Cape Cod Museum of Natural History and Nickerson State Park give Brewster a character that appeals strongly to buyers seeking nature, quiet, and authentic Cape living.',
        neighborhoods: 'Brewster Center, East Brewster, West Brewster, Brewster By The Sea, Punkhorn Parklands area',
        nearby: 'Orleans, Dennis, Harwich, Eastham, Chatham',
        seller_hook: 'Brewster\'s kettle ponds and Route 6A architecture attract buyers with genuine Cape passion — RealtorFinder puts motivated agents in competition to bring them to your home.',
        realtor_hook: 'Brewster\'s natural beauty and Route 6A heritage make it a market where buyers return year after year until they find the right home — RealtorFinder keeps you ahead of them.',
    },
];
