// cities/ma-metro.js — Greater Boston Metro / Merrimack Valley / MetroWest city data

module.exports = [
    {
        slug: 'lexington-ma',
        name: 'Lexington',
        county: 'Middlesex',
        state: 'MA',
        zip: '02420',
        population: '34,000',
        median_price: '$1,100,000',
        price_trend: 'up 6%',
        avg_dom: 14,
        description: 'Lexington is one of America\'s most historically significant towns and consistently ranks among Greater Boston\'s top school districts — a Route 2 community where the shot heard \'round the world was fired, where Lexington Public Schools\' national academic reputation commands a significant price premium, and where biotech corridor proximity creates intense buyer competition from MIT and Harvard-affiliated researchers and executives.',
        neighborhoods: 'Lexington Center, Peacock Farm, East Lexington, Munroe, Turning Mill',
        nearby: 'Bedford, Lincoln, Concord MA, Burlington, Woburn',
        seller_hook: 'Lexington\'s top-ranked schools and historic prestige create some of Greater Boston\'s most competitive listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Lexington\'s academic premium and biotech buyer pool generate fast-moving high-value listings — find sellers through RealtorFinder.',
    },
    {
        slug: 'concord-ma',
        name: 'Concord',
        county: 'Middlesex',
        state: 'MA',
        zip: '01742',
        population: '19,000',
        median_price: '$1,050,000',
        price_trend: 'up 6%',
        avg_dom: 16,
        description: 'Concord is the literary heart of America — a Walden Pond and North Bridge community where Thoreau, Emerson, Hawthorne, and Alcott shaped American thought, and where today\'s biotech executives and Boston commuters pay a premium for Concord-Carlisle Regional School District\'s excellence and the town\'s extraordinary natural and cultural landscape, creating one of MetroWest\'s tightest and most prestigious markets.',
        neighborhoods: 'West Concord, Concord Center, Nine Acre Corner, Acton, Carlisle',
        nearby: 'Carlisle, Lincoln, Acton, Bedford, Maynard',
        seller_hook: 'Concord\'s literary heritage and top schools create exceptional demand from high-income Boston buyers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Concord\'s prestige market and limited inventory make every listing a premium opportunity — find sellers through RealtorFinder.',
    },
    {
        slug: 'needham',
        name: 'Needham',
        county: 'Norfolk',
        state: 'MA',
        zip: '02492',
        population: '32,000',
        median_price: '$1,025,000',
        price_trend: 'up 7%',
        avg_dom: 14,
        description: 'Needham is one of Greater Boston\'s most coveted inner suburbs — a Route 128 tech corridor community where top-ranked Needham Public Schools, a charming New England town center, Green Line extension proximity, and MBTA commuter rail access create one of the most competitive buyer markets in Massachusetts, with bidding wars common across nearly every price point.',
        neighborhoods: 'Needham Heights, Needham Center, Highlands, Highrock, Broadmeadow',
        nearby: 'Newton, Wellesley, Dedham, Westwood, Dover',
        seller_hook: 'Needham\'s top schools and Route 128 proximity create some of eastern Massachusetts\'s most competitive listing conditions — let agents compete on RealtorFinder.',
        realtor_hook: 'Needham\'s suburban premium and corporate buyer demand generate fast-moving listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'wellesley',
        name: 'Wellesley',
        county: 'Norfolk',
        state: 'MA',
        zip: '02482',
        population: '30,000',
        median_price: '$1,350,000',
        price_trend: 'up 6%',
        avg_dom: 14,
        description: 'Wellesley is Greater Boston\'s gold standard suburb — a Wellesley College town on the Green Line where Massachusetts\'s most consistently top-ranked public schools, a charming Linden Street retail village, and proximity to Boston\'s financial district create fierce buyer competition among the region\'s highest-income professionals and families, with the median sale price ranking among the highest of any Massachusetts municipality.',
        neighborhoods: 'Wellesley Hills, Wellesley Farms, Wellesley Fells, Wellesley Center, Babson Park',
        nearby: 'Weston, Newton, Natick, Needham, Dover',
        seller_hook: 'Wellesley\'s #1 school district and Wellesley College prestige command Massachusetts\'s highest suburban prices — let top agents compete on RealtorFinder.',
        realtor_hook: 'Wellesley\'s elite buyer pool and limited inventory create the region\'s most valuable listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'andover-ma',
        name: 'Andover',
        county: 'Essex',
        state: 'MA',
        zip: '01810',
        population: '36,000',
        median_price: '$780,000',
        price_trend: 'up 7%',
        avg_dom: 16,
        description: 'Andover is the home of Phillips Academy, one of America\'s most prestigious prep schools — a Merrimack Valley town with an MBTA commuter rail connection to Boston\'s North Station, a strong pharmaceutical and biotech corridor along Route 93, top-ranked Andover Public Schools, and a quintessential New England town green that make it one of northern Massachusetts\'s most sought-after addresses.',
        neighborhoods: 'Ballardvale, Shawsheen Village, South Church, West Parish, North Andover',
        nearby: 'North Andover, Lawrence, Methuen, Tewksbury, Wilmington',
        seller_hook: 'Andover\'s Phillips Academy prestige and biotech corridor create premium listing conditions — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Andover\'s prep school cache and Route 93 corporate demand generate fast-moving listings in the Merrimack Valley — find sellers through RealtorFinder.',
    },
    {
        slug: 'north-andover',
        name: 'North Andover',
        county: 'Essex',
        state: 'MA',
        zip: '01845',
        population: '31,000',
        median_price: '$680,000',
        price_trend: 'up 7%',
        avg_dom: 16,
        description: 'North Andover is Essex County\'s quintessential New England town — a community centered on a classic town common, Great Pond, and a strong industrial heritage that today hosts a thriving tech and pharmaceutical corridor, where top-rated North Andover Public Schools and MBTA Haverhill Line access to Boston North Station create consistent demand from corporate transferees and growing families.',
        neighborhoods: 'North Andover Center, Bradford, Osgood, Foster Farm, Lake Cochichewick',
        nearby: 'Andover, Lawrence, Methuen, Haverhill, Boxford',
        seller_hook: 'North Andover\'s town common charm and top schools create strong buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'North Andover\'s pharmaceutical corridor and family buyer market generate consistent listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'haverhill',
        name: 'Haverhill',
        county: 'Essex',
        state: 'MA',
        zip: '01830',
        population: '65,000',
        median_price: '$430,000',
        price_trend: 'up 8%',
        avg_dom: 16,
        description: 'Haverhill is the Queen City of the Merrimack Valley — a shoe manufacturing legacy city on the New Hampshire border where Bradford College site redevelopment, direct MBTA commuter rail to Boston North Station, and some of northeastern Massachusetts\'s most affordable home prices within commuting distance of both Boston and New Hampshire\'s tax advantages create intense first-time buyer and investor competition.',
        neighborhoods: 'Bradford, Silver City, Mount Washington, Rosemont, Ward Hill',
        nearby: 'Methuen, Lawrence, Plaistow NH, Salem NH, Groveland',
        seller_hook: 'Haverhill\'s MBTA rail access and affordable prices create fast-moving buyer competition — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Haverhill\'s first-time buyer surge and commuter rail appeal generate one of northeastern MA\'s most active listing markets — find sellers through RealtorFinder.',
    },
    {
        slug: 'lawrence-ma',
        name: 'Lawrence',
        county: 'Essex',
        state: 'MA',
        zip: '01840',
        population: '80,000',
        median_price: '$365,000',
        price_trend: 'up 9%',
        avg_dom: 14,
        description: 'Lawrence is Massachusetts\'s most undervalued urban real estate market — a Merrimack River mill city with one of New England\'s most vibrant Latino communities, direct MBTA commuter rail to Boston North Station, and multi-family triple-deckers and mill buildings that offer investors cap rates rarely seen this close to Boston, with appreciation running near the state\'s highest as buyers discover this rapidly transforming immigrant city.',
        neighborhoods: 'North Lawrence, South Lawrence, Tower Hill, Methuen, Andover border',
        nearby: 'Methuen, Andover, North Andover, Haverhill, Salem NH',
        seller_hook: 'Lawrence\'s Boston rail access and rapid appreciation create exceptional seller conditions — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Lawrence\'s investment-grade multi-family market and first-time buyer surge generate some of northeastern MA\'s fastest-moving listings — find sellers through RealtorFinder.',
    },
    {
        slug: 'methuen',
        name: 'Methuen',
        county: 'Essex',
        state: 'MA',
        zip: '01844',
        population: '52,000',
        median_price: '$485,000',
        price_trend: 'up 8%',
        avg_dom: 15,
        description: 'Methuen is Essex County\'s fastest-appreciating suburb and a New Hampshire border community — a town where Methuen Mall corridor retail, a direct connection to I-93 and Route 213, and home prices significantly below comparable southern New Hampshire towns attract first-time buyers and families who want Massachusetts amenities with proximity to tax-free New Hampshire shopping.',
        neighborhoods: 'Nevins Memorial Library, Prospect Street, Tenney Street, Meadowbrook, Hampshire Road',
        nearby: 'Lawrence, Andover, Salem NH, Windham NH, Plaistow NH',
        seller_hook: 'Methuen\'s NH border value and Route 93 access create strong buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Methuen\'s rapid appreciation and NH proximity generate one of the Merrimack Valley\'s most active listing markets — find sellers through RealtorFinder.',
    },
    {
        slug: 'leominster',
        name: 'Leominster',
        county: 'Worcester',
        state: 'MA',
        zip: '01453',
        population: '43,000',
        median_price: '$375,000',
        price_trend: 'up 7%',
        avg_dom: 18,
        description: 'Leominster is north-central Massachusetts\'s Plastic City and the birthplace of Johnny Appleseed — a Route 2 and I-190 hub where a strong manufacturing and healthcare base, MBTA Fitchburg Line commuter rail service, and some of central Massachusetts\'s most affordable single-family homes attract Boston commuters and growing families who want Worcester County prices with solid employment in a city that\'s steadily been discovered.',
        neighborhoods: 'South Leominster, North Leominster, Orchard Hills, Priest Street, Lunenburg',
        nearby: 'Fitchburg, Lancaster, Lunenburg, Sterling, Clinton',
        seller_hook: 'Leominster\'s commuter rail access and affordable prices create competitive buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Leominster\'s central MA value and MBTA connection generate consistent listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'weston-ma',
        name: 'Weston',
        county: 'Middlesex',
        state: 'MA',
        zip: '02493',
        population: '12,000',
        median_price: '$1,600,000',
        price_trend: 'up 6%',
        avg_dom: 20,
        description: 'Weston is Massachusetts\'s wealthiest per-capita town and Greater Boston\'s most exclusive residential community — a heavily wooded Route 128 enclave where Weston Public Schools\'s extraordinary academic performance, Regis College, 2-acre minimum lot zoning, and proximity to Boston\'s financial district attract hedge fund managers, biotech executives, and old-money New England families seeking complete privacy and luxury in a blue-chip address.',
        neighborhoods: 'Weston Center, Kendal Green, South Side, Cat Rock, Doublet Hill',
        nearby: 'Wellesley, Lincoln, Wayland, Natick, Newton',
        seller_hook: 'Weston\'s exclusivity and Massachusetts\'s #1 school district create exceptional sale conditions — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Weston\'s ultra-luxury market and discerning buyer pool offer the region\'s highest listing commissions — find sellers through RealtorFinder.',
    },
    {
        slug: 'stoughton',
        name: 'Stoughton',
        county: 'Norfolk',
        state: 'MA',
        zip: '02072',
        population: '29,000',
        median_price: '$490,000',
        price_trend: 'up 7%',
        avg_dom: 17,
        description: 'Stoughton is Norfolk County\'s commuter-friendly hub — a town on both Route 138 and the MBTA Providence/Stoughton commuter rail line where a diverse working-class community, strong manufacturing employment at Randolph and Avon border industrial parks, and prices well below neighboring Canton and Sharon attract first-time buyers and move-up families seeking good schools and direct Boston South Station access.',
        neighborhoods: 'Stoughton Center, South Stoughton, Stoughton North, Avon, Canton border',
        nearby: 'Canton, Sharon, Easton, Brockton, Randolph',
        seller_hook: 'Stoughton\'s MBTA commuter rail and affordable Norfolk County prices create active buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Stoughton\'s first-time buyer market and Boston rail access generate consistent listing activity — find sellers through RealtorFinder.',
    },
];
