// cities/md.js — Maryland city data for SEO landing pages

module.exports = [
    {
        slug: 'bethesda',
        name: 'Bethesda',
        county: 'Montgomery',
        state: 'MD',
        zip: '20814',
        population: '62000',
        median_price: '$1,200,000',
        price_trend: 'up 4%',
        avg_dom: 22,
        description: 'Bethesda is Montgomery County\'s premier urban destination, combining the upscale Bethesda Row and Woodmont Triangle dining and retail corridors with the National Institutes of Health campus and Walter Reed National Military Medical Center that anchor the area\'s high-income professional workforce. Red Line Metro access, top-ranked MCPS schools, and a dense inventory of luxury condos and single-family estates make Bethesda one of the most competitive real estate markets on the entire East Coast.',
        neighborhoods: 'Bethesda Row, Woodmont Triangle, Chevy Chase Section 5, Edgemoor, Drummond, Battery Park, Old Georgetown',
        nearby: 'Chevy Chase, Potomac MD, Rockville, Friendship Heights DC, Silver Spring',
        seller_hook: 'Bethesda\'s NIH and federal contractor workforce creates year-round luxury buyer demand — let top Bethesda agents compete on RealtorFinder to achieve your home\'s maximum value.',
        realtor_hook: 'Bethesda\'s high median price and professional buyer pool produce premium commissions — RealtorFinder connects you with motivated sellers in one of Maryland\'s most prestigious markets.',
    },
    {
        slug: 'chevy-chase',
        name: 'Chevy Chase',
        county: 'Montgomery',
        state: 'MD',
        zip: '20815',
        population: '10000',
        median_price: '$1,500,000',
        price_trend: 'up 4%',
        avg_dom: 25,
        description: 'Chevy Chase is one of the DC metro area\'s most exclusive residential communities, straddling the Maryland-DC line with gracious Craftsman and Colonial Revival homes on tree-canopied streets adjacent to the Chevy Chase Club and Columbia Country Club. The community\'s Metro-accessible location on the Red Line at Friendship Heights, walkability to the Collection at Chevy Chase retail district, and highly coveted Chevy Chase Elementary School boundaries create some of the fiercest buyer competition in the entire region.',
        neighborhoods: 'Chevy Chase Village, Chevy Chase Section 3, Chevy Chase Section 4, Somerset, Martin\'s Additions',
        nearby: 'Bethesda, Washington DC, Kensington, Silver Spring',
        seller_hook: 'Chevy Chase\'s elite address and extreme scarcity of inventory make every listing a competitive event — let top Chevy Chase agents compete on RealtorFinder to achieve the highest possible price.',
        realtor_hook: 'Chevy Chase\'s $1.5M median and perpetual inventory shortage create the most competitive buyer market in Maryland — RealtorFinder connects you with motivated sellers in this exclusive community.',
    },
    {
        slug: 'potomac-md',
        name: 'Potomac',
        county: 'Montgomery',
        state: 'MD',
        zip: '20854',
        population: '45000',
        median_price: '$1,200,000',
        price_trend: 'up 4%',
        avg_dom: 28,
        description: 'Potomac is Montgomery County\'s most prestigious estate community, with wooded five-acre parcels, the Congressional Country Club, and a Beltway location that draws diplomats, federal executives, and finance professionals seeking privacy and space. The Potomac Village commercial district, C&O Canal towpath access, and highly regarded Churchill and Potomac High School pyramids reinforce the area\'s reputation as the gold standard for Maryland suburban luxury.',
        neighborhoods: 'Avenel, Potomac Village, Inverness Forest, River Road Corridor, Falconhurst, Kenwood Forest',
        nearby: 'Bethesda, Rockville, Great Falls VA, North Potomac',
        seller_hook: 'Potomac\'s exclusivity and estate-scale properties attract the DC area\'s most affluent buyers — let top Potomac agents compete on RealtorFinder to find the right buyer for your home.',
        realtor_hook: 'Potomac\'s luxury estate market offers some of the region\'s highest-value commissions — RealtorFinder connects you with motivated sellers in Montgomery County\'s most prestigious community.',
    },
    {
        slug: 'rockville',
        name: 'Rockville',
        county: 'Montgomery',
        state: 'MD',
        zip: '20850',
        population: '68000',
        median_price: '$700,000',
        price_trend: 'up 5%',
        avg_dom: 20,
        description: 'Rockville serves as Montgomery County\'s seat and a major employment hub for biotech and pharmaceutical companies including AstraZeneca, MedImmune, and Human Genome Sciences clustered along I-270\'s technology corridor. The revitalized Rockville Town Square provides a walkable urban core with Red Line Metro access, while surrounding neighborhoods from Twinbrook to King Farm offer housing options at every price point.',
        neighborhoods: 'Rockville Town Square, King Farm, Twinbrook, Fallsmead, Lakewood Estates, Watts Branch',
        nearby: 'Gaithersburg, Bethesda, North Potomac, Germantown, Kensington',
        seller_hook: 'Rockville\'s biotech corridor and Red Line Metro access drive strong professional buyer demand — let top Rockville agents compete on RealtorFinder to maximize your home\'s sale price.',
        realtor_hook: 'Rockville\'s I-270 tech corridor creates a steady stream of relocating biotech and pharma professionals — RealtorFinder connects you with motivated sellers across Montgomery County\'s largest city.',
    },
    {
        slug: 'gaithersburg',
        name: 'Gaithersburg',
        county: 'Montgomery',
        state: 'VA',
        zip: '20877',
        population: '71000',
        median_price: '$550,000',
        price_trend: 'up 5%',
        avg_dom: 21,
        description: 'Gaithersburg offers exceptional value in the Montgomery County market, with the National Institute of Standards and Technology campus and a dense cluster of biotech firms along the I-270 corridor providing stable employment. The Kentlands new-urbanist community and Lakelands developments offer walkable neighborhood design, while Rio and the Crown Farm district bring modern mixed-use retail that has revitalized the city\'s commercial landscape.',
        neighborhoods: 'Kentlands, Lakelands, Crown Farm, Rio, Montgomery Village, Quince Orchard',
        nearby: 'Rockville, Germantown, North Potomac, Damascus, Clarksburg',
        seller_hook: 'Gaithersburg\'s biotech employment base and diverse housing stock attract buyers from across the price spectrum — let top Gaithersburg agents compete on RealtorFinder for your best outcome.',
        realtor_hook: 'Gaithersburg\'s NIST and biotech employer base creates consistent buyer demand across all price ranges — RealtorFinder connects you with motivated sellers in this active Montgomery County market.',
    },
    {
        slug: 'germantown',
        name: 'Germantown',
        county: 'Montgomery',
        state: 'MD',
        zip: '20874',
        population: '90000',
        median_price: '$460,000',
        price_trend: 'up 5%',
        avg_dom: 22,
        description: 'Germantown is Montgomery County\'s most populous community and one of the most affordable entry points to the I-270 biotech and pharma corridor, with a dense mix of townhouses, condominiums, and single-family homes built across planned neighborhoods in the 1970s and 1980s. Its lower prices relative to Rockville and Gaithersburg attract first-time buyers and commuters who benefit from MARC commuter rail at Germantown station and frequent Ride On bus service.',
        neighborhoods: 'Churchill Village, Kingsview Village, Germantown Village, Waters Landing, Clopper Mill',
        nearby: 'Gaithersburg, Clarksburg, Damascus, Boyds, Rockville',
        seller_hook: 'Germantown\'s affordability and proximity to major biotech employers attract a large pool of first-time and move-up buyers — let top Germantown agents compete on RealtorFinder for your best offer.',
        realtor_hook: 'Germantown\'s high transaction volume and first-time buyer activity make it one of Montgomery County\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'silver-spring',
        name: 'Silver Spring',
        county: 'Montgomery',
        state: 'MD',
        zip: '20901',
        population: '81000',
        median_price: '$560,000',
        price_trend: 'up 5%',
        avg_dom: 19,
        description: 'Silver Spring has reinvented itself as one of the DC metro area\'s most vibrant inner-ring suburbs, with a downtown anchored by the AFI Silver Theatre, Discovery Channel headquarters, and a thriving international dining scene that reflects the community\'s extraordinary diversity. Red Line Metro access at three stations, proximity to Washington DC, and relatively affordable prices compared to Bethesda or Chevy Chase make it exceptionally attractive to young professionals and federal workers.',
        neighborhoods: 'Downtown Silver Spring, Woodside Park, Long Branch, Takoma Park adjacent, Sligo Creek, Kemp Mill, Colesville',
        nearby: 'Takoma Park, Wheaton, Bethesda, Chevy Chase, Washington DC',
        seller_hook: 'Silver Spring\'s Metro access and proximity to DC attract a large, motivated buyer pool — let top Silver Spring agents compete on RealtorFinder to sell your home quickly at maximum value.',
        realtor_hook: 'Silver Spring\'s urban amenities and Metro connectivity drive strong demand for a wide range of property types — RealtorFinder connects you with motivated sellers in this diverse, fast-moving market.',
    },
    {
        slug: 'takoma-park',
        name: 'Takoma Park',
        county: 'Montgomery',
        state: 'MD',
        zip: '20912',
        population: '17000',
        median_price: '$620,000',
        price_trend: 'up 4%',
        avg_dom: 21,
        description: 'Takoma Park is one of the DC area\'s most distinctive communities, an independent-minded small city straddling the Maryland-DC border with a bohemian character rooted in its Victorian-era homes, the nationally recognized Takoma Park Farmers Market, and a long history of progressive civic activism. Its Red Line Metro station, walkable Old Town corridor, and tight inventory of historic bungalows and Craftsman homes generate fierce buyer competition for every listing.',
        neighborhoods: 'Old Town Takoma Park, Takoma, East Silver Spring, Carroll Avenue Corridor, Columbia Hills',
        nearby: 'Silver Spring, Hyattsville, Washington DC, Wheaton',
        seller_hook: 'Takoma Park\'s unique character and DC proximity create intense demand for its limited historic home supply — let top Takoma Park agents compete on RealtorFinder to achieve premium results.',
        realtor_hook: 'Takoma Park\'s tight inventory and passionate buyer pool create a highly competitive listing environment — RealtorFinder connects you with motivated sellers in this beloved historic community.',
    },
    {
        slug: 'college-park',
        name: 'College Park',
        county: 'Prince George\'s',
        state: 'MD',
        zip: '20740',
        population: '32000',
        median_price: '$420,000',
        price_trend: 'up 5%',
        avg_dom: 23,
        description: 'College Park is home to the University of Maryland\'s flagship campus and has emerged as a significant innovation hub through the Discovery District tech corridor and the University Research Park. Green Line Metro access at two stations, ongoing downtown College Park revitalization, and proximity to DC make it increasingly attractive to professionals and investors alongside the traditional university community of faculty and staff.',
        neighborhoods: 'Old Town College Park, Berwyn, Hollywood, Berwyn Heights, Calvert Hills, North College Park',
        nearby: 'Hyattsville, Greenbelt, Beltsville, Laurel, New Carrollton',
        seller_hook: 'College Park\'s UMD research corridor and Metro access are driving rapid price appreciation — let top College Park agents compete on RealtorFinder to capture current market momentum.',
        realtor_hook: 'College Park\'s UMD Discovery District is attracting tech-sector buyers alongside traditional university demand — RealtorFinder connects you with motivated sellers in this evolving market.',
    },
    {
        slug: 'bowie',
        name: 'Bowie',
        county: 'Prince George\'s',
        state: 'MD',
        zip: '20715',
        population: '60000',
        median_price: '$430,000',
        price_trend: 'up 5%',
        avg_dom: 22,
        description: 'Bowie is the largest municipality in Prince George\'s County and one of the most affluent majority-Black communities in the United States, with well-maintained neighborhoods, Bowie State University, and easy access to both the DC metro area and Annapolis via Route 50. The Bowie Town Center retail hub and ongoing development along Central Avenue make it a popular choice for federal workers seeking affordable suburban living between DC and the Chesapeake Bay.',
        neighborhoods: 'Belair, Pointer Ridge, Northgate, Kenilworth, Whitehall, South Bowie',
        nearby: 'Laurel, Upper Marlboro, Annapolis, Greenbelt, Crofton',
        seller_hook: 'Bowie\'s strong community character and Route 50 corridor draw motivated buyers from the DC and Annapolis markets — let top Bowie agents compete on RealtorFinder for your best sale.',
        realtor_hook: 'Bowie\'s affluent buyer base and steady federal-worker demand create consistent listing activity — RealtorFinder connects you with motivated sellers in Prince George\'s County\'s largest city.',
    },
    {
        slug: 'laurel',
        name: 'Laurel',
        county: 'Prince George\'s',
        state: 'MD',
        zip: '20707',
        population: '26000',
        median_price: '$400,000',
        price_trend: 'up 5%',
        avg_dom: 23,
        description: 'Laurel occupies a strategic position at the crossroads of I-95 and the Baltimore-Washington Parkway, serving commuters to both cities and hosting major employers including Comcast and various federal agencies in the Route 1 corridor. MARC commuter rail at Laurel and BWI stations, a revitalizing Main Street downtown, and some of the most affordable single-family home prices in the close-in suburbs make Laurel increasingly attractive to value-conscious DC and Baltimore area buyers.',
        neighborhoods: 'Historic Laurel, Montpelier, Russett, Laurel Lakes, Laurel Pines, Sandy Spring',
        nearby: 'Bowie, College Park, Jessup, Savage, Elkridge',
        seller_hook: 'Laurel\'s commuter-friendly location between DC and Baltimore creates a broad buyer pool — let top Laurel agents compete on RealtorFinder to sell your home quickly and at the right price.',
        realtor_hook: 'Laurel\'s affordability and dual-metro commuter appeal create strong demand from buyers priced out of closer-in markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'annapolis',
        name: 'Annapolis',
        county: 'Anne Arundel',
        state: 'MD',
        zip: '21401',
        population: '40000',
        median_price: '$650,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Annapolis is Maryland\'s capital city and the sailing capital of the United States, with a stunning colonial downtown along the Severn River, the United States Naval Academy, and one of the most active recreational boating communities on the East Coast. Its equidistant location between Washington DC and Baltimore, combined with waterfront lifestyle appeal, makes it a perennial destination for remote workers and retirees seeking a premium quality of life.',
        neighborhoods: 'Historic Annapolis, Eastport, West Annapolis, Murray Hill, Parole, Riva, Bay Ridge',
        nearby: 'Bowie, Crofton, Severna Park, Arnold, Edgewater',
        seller_hook: 'Annapolis\'s Naval Academy prestige and waterfront lifestyle attract buyers from across the country — let top Annapolis agents compete on RealtorFinder to capture maximum value for your home.',
        realtor_hook: 'Annapolis\'s USNA presence and boating lifestyle appeal create premium buyer demand — RealtorFinder connects you with motivated sellers in Maryland\'s most distinctive waterfront capital.',
    },
    {
        slug: 'columbia',
        name: 'Columbia',
        county: 'Howard',
        state: 'MD',
        zip: '21044',
        population: '103000',
        median_price: '$560,000',
        price_trend: 'up 5%',
        avg_dom: 19,
        description: 'Columbia is James Rouse\'s landmark planned community and one of America\'s great experiments in suburban design, built around a series of lake-centered villages with extensive trail systems, public pools, and community centers that have aged beautifully over fifty years. Howard County\'s top-rated school system, one of the state\'s lowest crime rates, and a central location between Baltimore and DC with major employers like MedStar Health and Sysco Corporation make Columbia one of Maryland\'s most consistently desirable addresses.',
        neighborhoods: 'Wilde Lake, Harper\'s Choice, Oakland Mills, Longfellow, River Hill, Hickory Ridge, Owen Brown',
        nearby: 'Ellicott City, Laurel, Jessup, Elkridge, Clarksville',
        seller_hook: 'Columbia\'s planned community appeal and Howard County schools generate fierce competition among buyers — let top Columbia agents compete on RealtorFinder to get maximum value for your home.',
        realtor_hook: 'Columbia\'s consistently strong demand and Howard County\'s top-tier school reputation create one of Maryland\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'ellicott-city',
        name: 'Ellicott City',
        county: 'Howard',
        state: 'MD',
        zip: '21043',
        population: '72000',
        median_price: '$600,000',
        price_trend: 'up 5%',
        avg_dom: 20,
        description: 'Ellicott City combines the charm of a historic mill-town main street along the Patapsco River with the amenities of one of Maryland\'s wealthiest and best-educated communities. Howard County\'s consistently top-ranked school system, major tech and healthcare employers along US-29, and a mix of established golf course communities and new construction along Rt. 108 attract buyers willing to pay premium prices for Howard County\'s quality of life.',
        neighborhoods: 'Historic Ellicott City, Long Gate, Turf Valley, Waverly Woods, Dunloggin, Ilchester',
        nearby: 'Columbia, Catonsville, Towson, Baltimore, Clarksville',
        seller_hook: 'Ellicott City\'s top-ranked Howard County schools and historic charm create exceptional buyer demand — let top Ellicott City agents compete on RealtorFinder to maximize your home\'s value.',
        realtor_hook: 'Ellicott City\'s high-income buyer pool and Howard County school prestige drive premium listing prices — RealtorFinder connects you with motivated sellers in one of Maryland\'s top submarkets.',
    },
    {
        slug: 'towson',
        name: 'Towson',
        county: 'Baltimore',
        state: 'MD',
        zip: '21204',
        population: '55000',
        median_price: '$430,000',
        price_trend: 'up 4%',
        avg_dom: 24,
        description: 'Towson is Baltimore County\'s seat and a major suburban hub anchored by Towson University, the Towson Town Center mall, and a dense cluster of law firms, financial services, and healthcare providers that make it one of Maryland\'s most significant employment centers outside of Baltimore City. Its walkable downtown, established neighborhoods like Rodgers Forge and Anneslie, and strong public schools attract young professionals and families seeking Baltimore metro\'s best suburbs.',
        neighborhoods: 'Rodgers Forge, Anneslie, Loch Raven, Goucher, Hampton, West Towson, Stoneleigh',
        nearby: 'Lutherville, Timonium, Catonsville, Pikesville, Baltimore City',
        seller_hook: 'Towson\'s Towson University and county seat employment base drive consistent buyer demand in a competitive market — let top Towson agents compete on RealtorFinder to achieve top results.',
        realtor_hook: 'Towson\'s suburban amenities and proximity to Baltimore create strong listing demand across all price points — RealtorFinder connects you with motivated sellers in Baltimore County\'s hub.',
    },
    {
        slug: 'catonsville',
        name: 'Catonsville',
        county: 'Baltimore',
        state: 'MD',
        zip: '21228',
        population: '42000',
        median_price: '$380,000',
        price_trend: 'up 5%',
        avg_dom: 22,
        description: 'Catonsville is one of the Baltimore metro\'s most beloved inner-ring suburbs, known for its vibrant Frederick Road commercial strip, UMBC\'s dynamic research university campus, and a mix of Arts & Crafts bungalows and colonial homes on leafy streets. Its affordable prices relative to Howard County neighbors, easy MARC and I-695 access, and a strong community identity centered on the Catonsville Farmers\' Market and community events make it perpetually popular with buyers.',
        neighborhoods: 'Downtown Catonsville, Westchester, Hilton, Academy Heights, Rolling Road, Canford',
        nearby: 'Ellicott City, Towson, Arbutus, Halethorpe, Baltimore City',
        seller_hook: 'Catonsville\'s UMBC proximity and charming Frederick Road commercial district attract motivated buyers seeking value — let top Catonsville agents compete on RealtorFinder for your best sale.',
        realtor_hook: 'Catonsville\'s affordability relative to Howard County and active community make it a strong seller\'s market — RealtorFinder connects you with motivated sellers in this beloved Baltimore suburb.',
    },
    {
        slug: 'owings-mills',
        name: 'Owings Mills',
        county: 'Baltimore',
        state: 'MD',
        zip: '21117',
        population: '34000',
        median_price: '$390,000',
        price_trend: 'up 5%',
        avg_dom: 23,
        description: 'Owings Mills has transformed from a rural outpost to one of Baltimore County\'s most active residential markets, driven by Metro SubwayLink access, the redeveloped Foundry Row lifestyle center on Reisterstown Road, and a mix of new construction and established communities. The area\'s proximity to both Baltimore City and the Lutherville-Timonium corridor, combined with competitive pricing, makes it attractive to commuters and families seeking move-in ready suburban living.',
        neighborhoods: 'Owings Mills New Town, Garrison, Greenspring Valley, Caves Valley, Lyonswood',
        nearby: 'Pikesville, Reisterstown, Timonium, Lutherville, Randallstown',
        seller_hook: 'Owings Mills\' Metro access and Foundry Row development are drawing a growing buyer base — let top Owings Mills agents compete on RealtorFinder to maximize your home\'s sale price.',
        realtor_hook: 'Owings Mills\' rapid growth and Metro connectivity create consistent buyer demand — RealtorFinder connects you with motivated sellers in this expanding Baltimore County community.',
    },
    {
        slug: 'pikesville',
        name: 'Pikesville',
        county: 'Baltimore',
        state: 'MD',
        zip: '21208',
        population: '31000',
        median_price: '$420,000',
        price_trend: 'up 4%',
        avg_dom: 24,
        description: 'Pikesville is a well-established Baltimore County suburb known for its significant Jewish community, highly regarded schools, and a mix of brick colonials and ranchers on the Beltway\'s northwest corridor. The Quarry Lake at Greenspring development brings urban-style amenities to the community, while proximity to Sinai Hospital, Levindale Hebrew Geriatric Center, and suburban Baltimore employment hubs keeps buyer demand consistently strong.',
        neighborhoods: 'Quarry Lake, Seven Mile Lane, Greenspring, Sudbrook Park, Old Court, Gwynnbrook',
        nearby: 'Owings Mills, Reisterstown, Towson, Lutherville, Baltimore City',
        seller_hook: 'Pikesville\'s established community character and strong school ratings attract a loyal buyer base — let top Pikesville agents compete on RealtorFinder to achieve the best price for your home.',
        realtor_hook: 'Pikesville\'s stable, high-income buyer demographics and strong community identity create dependable listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'timonium',
        name: 'Timonium',
        county: 'Baltimore',
        state: 'MD',
        zip: '21093',
        population: '11000',
        median_price: '$440,000',
        price_trend: 'up 4%',
        avg_dom: 23,
        description: 'Timonium is a polished Baltimore County suburb centered on the Maryland State Fairgrounds and the Timonium Business Campus, with close proximity to the Light Rail Green Spring station providing car-free access to Baltimore\'s Inner Harbor. Its highly regarded Dulaney High School pyramid, established neighborhoods, and a dense concentration of healthcare, financial, and technology employers in the I-83 corridor make Timonium one of the metro\'s most consistent performers.',
        neighborhoods: 'Timonium Manor, Dulaney Valley, Padonia, Overlea, Ridgeleigh, Yorkshire',
        nearby: 'Lutherville, Towson, Cockeysville, Hunt Valley, Lutherville',
        seller_hook: 'Timonium\'s Dulaney school pyramid and I-83 employment corridor drive strong demand for well-maintained homes — let top Timonium agents compete on RealtorFinder to get you the best offer.',
        realtor_hook: 'Timonium\'s stable suburban character and desirable school district create reliable listing demand — RealtorFinder connects you with motivated sellers in Baltimore County\'s north corridor.',
    },
    {
        slug: 'lutherville',
        name: 'Lutherville',
        county: 'Baltimore',
        state: 'MD',
        zip: '21093',
        population: '7000',
        median_price: '$550,000',
        price_trend: 'up 4%',
        avg_dom: 22,
        description: 'Lutherville is one of Baltimore County\'s most coveted addresses, with gracious established homes, access to the Light Rail at Lutherville station, and a location that anchors the prestigious Dulaney High School corridor. The community\'s proximity to the I-83 business park district, Sheppard Pratt Health System\'s campus, and the charming Lutherville station historic district give it a distinctive character that commands a premium in the Baltimore metro market.',
        neighborhoods: 'Lutherville Station, Bare Hills, Paper Mill Road, Seminary Avenue, Lake Falls Village',
        nearby: 'Timonium, Towson, Cockeysville, Ruxton, Pikesville',
        seller_hook: 'Lutherville\'s prestigious address and Light Rail access attract motivated buyers willing to pay a premium — let top Lutherville agents compete on RealtorFinder to maximize your home\'s value.',
        realtor_hook: 'Lutherville\'s premium pricing and sought-after Dulaney High School boundaries create a loyal buyer following — RealtorFinder connects you with motivated sellers in this desirable community.',
    },
    {
        slug: 'frederick-md',
        name: 'Frederick',
        county: 'Frederick',
        state: 'MD',
        zip: '21701',
        population: '78000',
        median_price: '$420,000',
        price_trend: 'up 6%',
        avg_dom: 20,
        description: 'Frederick is one of Maryland\'s fastest-growing cities and the anchor of a county that offers some of the best housing value within commuting distance of both Washington DC and Baltimore via I-270 and I-70. The beautifully preserved Carroll Creek Linear Park and a thriving Market Street restaurant and arts district give Frederick a downtown that rivals much larger cities, while Fort Detrick\'s federal biodefense campus and a growing manufacturing base provide economic stability.',
        neighborhoods: 'Downtown Frederick, Shookstown, Worman\'s Mill, Rosemont, Clover Hill, The Overlook',
        nearby: 'Germantown, Hagerstown, Gaithersburg, Westminster, New Market',
        seller_hook: 'Frederick\'s rapid appreciation and proximity to both DC and Baltimore attract buyers from two major metro areas — let top Frederick agents compete on RealtorFinder to capitalize on strong demand.',
        realtor_hook: 'Frederick\'s dual DC-Baltimore commuter appeal and fast-appreciating market create outstanding listing opportunities — RealtorFinder connects you with motivated sellers in this growing city.',
    },
    {
        slug: 'hagerstown',
        name: 'Hagerstown',
        county: 'Washington',
        state: 'MD',
        zip: '21740',
        population: '44000',
        median_price: '$280,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Hagerstown is Western Maryland\'s largest city and a crossroads community at the intersection of I-70 and I-81 that is attracting significant distribution and logistics investment from Amazon and other major operators. The revitalized downtown anchored by the Maryland Theatre and the Hagerstown Premium Outlets, combined with some of the most affordable home prices in the mid-Atlantic region, are drawing buyers displaced from higher-cost markets along the I-70 corridor.',
        neighborhoods: 'Downtown Hagerstown, North End, South End, Fountainhead, Potomac Heights, Pangborn',
        nearby: 'Martinsburg WV, Frederick, Greencastle PA, Chambersburg PA',
        seller_hook: 'Hagerstown\'s logistics boom and affordable prices are attracting a new wave of buyers from across the mid-Atlantic — let top Hagerstown agents compete on RealtorFinder for your best offer.',
        realtor_hook: 'Hagerstown\'s affordable price point and growing logistics economy are drawing buyers priced out of Frederick and DC markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'waldorf',
        name: 'Waldorf',
        county: 'Charles',
        state: 'MD',
        zip: '20601',
        population: '90000',
        median_price: '$380,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Waldorf is Charles County\'s unincorporated commercial and residential hub, one of the largest such communities in the United States, offering affordable home prices for federal workers and military families at Patuxent River Naval Air Station and Indian Head Naval Surface Warfare Center. The Route 301 commercial corridor, planned Waldorf Blue Line Metro extension, and ongoing downtown redevelopment are accelerating buyer interest from DC commuters seeking more space at lower prices.',
        neighborhoods: 'St. Charles, Westlake, White Plains, Bryans Road, Acton, Waldorf Woods',
        nearby: 'La Plata, White Plains, Fort Washington, Clinton, Indian Head',
        seller_hook: 'Waldorf\'s planned Metro extension and federal worker buyer base are driving appreciation — let top Waldorf agents compete on RealtorFinder to maximize the value of your home sale.',
        realtor_hook: 'Waldorf\'s Metro expansion prospects and large federal workforce create strong buyer demand — RealtorFinder connects you with motivated sellers in Charles County\'s largest community.',
    },
    {
        slug: 'bel-air-md',
        name: 'Bel Air',
        county: 'Harford',
        state: 'MD',
        zip: '21014',
        population: '11000',
        median_price: '$380,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Bel Air is the seat of Harford County and the anchor of one of the Baltimore metro\'s most family-friendly suburban markets, with a charming Main Street district, highly regarded public schools, and a price point that offers considerable value compared to Baltimore County neighbors. The APG Federal Credit Union campus and Aberdeen Proving Ground\'s federal military and civilian workforce provide economic stability, while Bel Air\'s community events and parks system give it a quality of life that consistently attracts buyers from across the Baltimore region.',
        neighborhoods: 'Downtown Bel Air, Forest Hill, Fallston, Emmorton, Riverside, Bradley Manor',
        nearby: 'Aberdeen, Havre de Grace, Fallston, Jarrettsville, White Marsh',
        seller_hook: 'Bel Air\'s top Harford County schools and APG workforce create consistent family buyer demand — let top Bel Air agents compete on RealtorFinder to achieve the best possible result for your home.',
        realtor_hook: 'Bel Air\'s Aberdeen Proving Ground workforce and active family buyer market create dependable listing demand — RealtorFinder connects you with motivated sellers in Harford County\'s hub.',
    },
];
