// cities/me-extra.js — Additional Maine city data for SEO landing pages

module.exports = [
    {
        slug: 'presque-isle',
        name: 'Presque Isle',
        county: 'Aroostook',
        state: 'ME',
        zip: '04769',
        population: '9,000',
        median_price: '$155,000',
        price_trend: 'up 4%',
        avg_dom: 42,
        description: 'Presque Isle is the heart of Aroostook County and Maine\'s potato country capital — a northern Maine city near the Canadian border where University of Maine at Presque Isle, Northern Maine Medical Center, and a deep agricultural heritage create housing demand for some of New England\'s most affordable homes, with large lots and farmhouses available at prices that draw buyers seeking genuine rural Maine homeownership.',
        neighborhoods: 'Mapleton, Chapman, Castle Hill, Washburn, Caribou',
        nearby: 'Caribou, Fort Fairfield, Limestone, Houlton, Mars Hill',
        seller_hook: 'Presque Isle\'s UMPI enrollment and Aroostook County stability create consistent buyer demand — let top agents compete on RealtorFinder.',
        realtor_hook: 'Presque Isle\'s agricultural market and affordable prices create listing opportunities at New England\'s most accessible price points — find sellers through RealtorFinder.',
    },
    {
        slug: 'caribou-me',
        name: 'Caribou',
        county: 'Aroostook',
        state: 'ME',
        zip: '04736',
        population: '7,000',
        median_price: '$145,000',
        price_trend: 'up 3%',
        avg_dom: 45,
        description: 'Caribou is Aroostook County\'s second-largest city and the geographic heart of Maine\'s potato and broccoli belt — a border city where Cary Medical Center, agricultural employment, and Caribou High School\'s renowned athletic program create a tight-knit community of farmhouses and ranches at prices that make it one of the least expensive places to own a home in all of New England.',
        neighborhoods: 'Connor Township, Limestone, Fort Fairfield, Caswell, Stockholm',
        nearby: 'Presque Isle, Limestone, Fort Fairfield, Van Buren, Madawaska',
        seller_hook: 'Caribou\'s agricultural community and affordable prices attract buyers seeking Maine homeownership — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Caribou\'s Aroostook County market creates listing opportunities at Maine\'s most accessible price points — find sellers through RealtorFinder.',
    },
    {
        slug: 'houlton',
        name: 'Houlton',
        county: 'Aroostook',
        state: 'ME',
        zip: '04730',
        population: '6,000',
        median_price: '$170,000',
        price_trend: 'up 4%',
        avg_dom: 40,
        description: 'Houlton is Aroostook County\'s southern gateway and an international border crossing town connecting I-95 Maine to New Brunswick, Canada — where Aroostook Medical Center, a charming Market Square downtown, and some of Maine\'s most affordable Victorian and colonial homes create a quiet market for buyers seeking the rural Maine lifestyle with the security of a regional medical and commercial hub.',
        neighborhoods: 'Hodgdon, Linneus, New Limerick, Littleton, Hammond',
        nearby: 'Presque Isle, Woodstock NB Canada, Bridgewater, Mars Hill, Smyrna',
        seller_hook: 'Houlton\'s I-95 gateway location and affordable prices attract buyers seeking rural Maine value — let agents compete on RealtorFinder.',
        realtor_hook: 'Houlton\'s border crossing economy and southern Aroostook market create listing activity at Maine\'s most rural prices — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'belfast-me',
        name: 'Belfast',
        county: 'Waldo',
        state: 'ME',
        zip: '04915',
        population: '7,000',
        median_price: '$345,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Belfast is one of Mid-Coast Maine\'s most beloved small cities — a Penobscot Bay city of preserved Victorian architecture, a thriving arts scene anchored by Left Bank Books and the Belfast Center for the Arts, Penobscot Poultry heritage reimagined as a creative economy hub, and waterfront access that draws Boston and Portland buyers seeking authentic mid-coast Maine living at prices far below Camden and Rockport.',
        neighborhoods: 'Belfast Center, East Belfast, Northport, Searsport, Swanville',
        nearby: 'Searsport, Northport, Lincolnville, Stockton Springs, Knox',
        seller_hook: 'Belfast\'s Penobscot Bay artisan culture and coastal charm attract buyers from across New England — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Belfast\'s mid-coast arts market and rapid appreciation create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'rockport-me',
        name: 'Rockport',
        county: 'Knox',
        state: 'ME',
        zip: '04856',
        population: '3,400',
        median_price: '$650,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Rockport is arguably Maine\'s most photographed village — a Knox County harbor community adjacent to Camden where Maine Media Workshops, a historic Marine Park with lime kilns, and one of the most picturesque working boat harbors on the East Coast create intense second-home demand from Boston and New York buyers paying premium prices for the complete Downeast coastal lifestyle.',
        neighborhoods: 'Rockport Harbor, Camden border, Hope, Appleton, West Rockport',
        nearby: 'Camden, Rockland, Thomaston, Warren, Union',
        seller_hook: 'Rockport\'s iconic harbor and media arts prestige command premium Maine coastal prices — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Rockport\'s out-of-state buyer demand and Knox County coastal market create high-value listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'farmington-me',
        name: 'Farmington',
        county: 'Franklin',
        state: 'ME',
        zip: '04938',
        population: '8,000',
        median_price: '$255,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Farmington is the University of Maine at Farmington\'s college town and Franklin County\'s cultural capital — a Sandy River valley community near Sugarloaf Mountain and Saddleback ski resorts where UMF\'s teacher education program, Franklin Memorial Hospital, and proximity to some of western Maine\'s finest outdoor recreation attract faculty, skiers, and outdoor enthusiasts seeking affordable rural college-town living.',
        neighborhoods: 'Farmington Falls, Wilton, Jay, Livermore Falls, Strong',
        nearby: 'Wilton, Jay, Livermore Falls, Rangeley, Strong',
        seller_hook: 'Farmington\'s UMF enrollment and ski resort proximity create consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Farmington\'s western Maine outdoor market and university anchors generate steady listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'boothbay-harbor',
        name: 'Boothbay Harbor',
        county: 'Lincoln',
        state: 'ME',
        zip: '04538',
        population: '3,000',
        median_price: '$495,000',
        price_trend: 'up 7%',
        avg_dom: 35,
        description: 'Boothbay Harbor is mid-coast Maine\'s most picturesque fishing village — a Lincoln County harbor town where whale-watching boats, lobster pounds, a thriving summer arts community, and Coastal Maine Botanical Gardens create intense second-home demand from Massachusetts and Connecticut buyers seeking the definitive Downeast Maine experience, with waterfront cottages and antique colonials commanding premium prices for authentic New England coastal living.',
        neighborhoods: 'East Boothbay, Southport Island, Boothbay, Edgecomb, Wiscasset',
        nearby: 'Wiscasset, Damariscotta, Bath, Newcastle, Edgecomb',
        seller_hook: 'Boothbay Harbor\'s iconic Maine harbor and botanical gardens draw out-of-state buyers year-round — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Boothbay Harbor\'s second-home market and New England coastal prestige create high-value listing opportunities on mid-coast Maine — find sellers through RealtorFinder.',
    },
    {
        slug: 'norway-me',
        name: 'Norway',
        county: 'Oxford',
        state: 'ME',
        zip: '04268',
        population: '5,000',
        median_price: '$245,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Norway is Oxford County\'s commercial hub and western Maine\'s gateway to lake and mountain recreation — a compact Main Street community where Pennesseewassee Lake, Sunday River and Shawnee Peak ski resort proximity, and strong Oxford County industrial employment create demand for affordable year-round homes and camp conversions from remote workers and recreational buyers discovering Oxford Hills real estate values.',
        neighborhoods: 'South Paris, Oxford, Paris Hill, Otisfield, Harrison',
        nearby: 'South Paris, Oxford, Paris, Otisfield, Harrison',
        seller_hook: 'Norway\'s Oxford Hills value and ski resort proximity attract recreational and remote buyers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Norway\'s western Maine outdoor market and affordable prices create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'calais-me',
        name: 'Calais',
        county: 'Washington',
        state: 'ME',
        zip: '04619',
        population: '3,000',
        median_price: '$140,000',
        price_trend: 'up 4%',
        avg_dom: 45,
        description: 'Calais is Washington County\'s border city across the St. Croix River from St. Stephen, New Brunswick — a Downeast Maine community where cross-border commerce, the St. Croix River recreation corridor, and some of New England\'s most affordable home prices create an accessible market for buyers seeking the quietest and most authentic edge of coastal Maine at prices that seem almost impossible for the region.',
        neighborhoods: 'Milltown, Red Beach, Baileyville, Robbinston, Perry',
        nearby: 'Baileyville, Princeton, Eastport, Perry, Pembroke',
        seller_hook: 'Calais\'s Downeast Maine authenticity and affordable prices attract buyers seeking remote Maine value — let agents compete on RealtorFinder.',
        realtor_hook: 'Calais\'s Washington County market creates listing opportunities at some of New England\'s most accessible price points — find sellers through RealtorFinder.',
    },
];
