module.exports = [
    // ── Greater Portland (Cumberland County) ─────────────────────────────
    {
        slug: 'portland',
        name: 'Portland',
        county: 'Cumberland',
        state: 'ME',
        zip: '04101',
        population: '68,000',
        median_price: '$479,000',
        price_trend: 'up 13%',
        avg_dom: 17,
        description: 'Portland is Maine\'s largest city and one of the most celebrated small cities in America, with a nationally ranked food scene, a walkable Old Port district, a thriving arts community, and Casco Bay waterfront access that draws buyers from Boston, New York, and beyond who want urban sophistication with a Maine pace of life. At 13% appreciation and a 17-day average market time, it is the engine of Maine\'s residential real estate market.',
        neighborhoods: 'Arts District, Munjoy Hill, Bayside, East Bayside, West End, Deering, East Deering, Woodfords',
        nearby: 'South Portland, Westbrook, Falmouth-me, Scarborough',
        seller_hook: 'Portland\'s national reputation as America\'s best small food city draws motivated buyers from across the country — sellers in every neighborhood are seeing multiple offers and closing at prices that continue to set new records.',
        realtor_hook: 'Portland\'s national media profile and status as New England\'s most celebrated small city creates a constant pipeline of out-of-state buyers, making it Maine\'s most rewarding market for agents who can serve relocating clients.',
    },
    {
        slug: 'south-portland',
        name: 'South Portland',
        county: 'Cumberland',
        state: 'ME',
        zip: '04106',
        population: '26,000',
        median_price: '$419,000',
        price_trend: 'up 12%',
        avg_dom: 19,
        description: 'South Portland offers Portland-adjacent value with its own distinct neighborhoods, a working waterfront, Cash Corner commercial district, and direct access to Portland International Jetport that makes it the practical choice for buyers priced out of Portland proper. The scenic Eastern Trail coastal path, Mill Creek Park, and Willard Beach give it a coastal lifestyle appeal that commands a meaningful premium above inland Cumberland County towns.',
        neighborhoods: 'Knightville, Thornton Heights, Mill Creek, Pleasantdale, Cash Corner',
        nearby: 'Portland, Cape Elizabeth, Scarborough, Westbrook',
        seller_hook: 'South Portland\'s position as Portland\'s most accessible neighbor means your home benefits from overflow demand from the city\'s nationally recognized market — buyers who missed out in Portland are ready to act quickly here.',
        realtor_hook: 'South Portland\'s airport proximity, waterfront access, and Portland overflow demand create a fast-moving market where well-prepared agents can serve multiple transactions simultaneously throughout the year.',
    },
    {
        slug: 'westbrook',
        name: 'Westbrook',
        county: 'Cumberland',
        state: 'ME',
        zip: '04092',
        population: '19,000',
        median_price: '$349,000',
        price_trend: 'up 12%',
        avg_dom: 20,
        description: 'Westbrook has transformed from a traditional mill city into one of Greater Portland\'s most dynamic suburban communities, with the IDEXX Laboratories corporate campus anchoring major employment, new residential development along the Presumpscot River, and prices that offer significant value relative to Portland and South Portland. Its Stroudwater neighborhood, vibrant arts scene, and improving downtown are drawing buyers who want Portland proximity without Portland prices.',
        neighborhoods: 'Westbrook Center, Stroudwater, Cumberland Mills, Riverton',
        nearby: 'Portland, Gorham, Windham, Falmouth-me',
        seller_hook: 'Westbrook\'s IDEXX employment anchor and Portland overflow demand are driving 12% appreciation — sellers are benefiting from a buyer pool of corporate employees and Portland-priced-out families ready to compete.',
        realtor_hook: 'Westbrook\'s IDEXX campus and improving neighborhood story give agents a compelling value pitch for Greater Portland buyers seeking more home for their money without sacrificing employment proximity.',
    },
    {
        slug: 'scarborough',
        name: 'Scarborough',
        county: 'Cumberland',
        state: 'ME',
        zip: '04074',
        population: '21,000',
        median_price: '$489,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Scarborough offers one of Maine\'s most complete residential packages — ocean beaches at Scarborough Beach and Pine Point, the Prouts Neck headland, extensive salt marshes protected as wildlife habitat, top-ranked schools, and a strategic location between Portland and Old Orchard Beach that gives buyers both natural beauty and practical convenience. Its diverse geography of coastal estates, suburban neighborhoods, and agricultural land sustains demand across price segments.',
        neighborhoods: 'Scarborough Beach area, Pine Point, Prouts Neck, Oak Hill, West Scarborough',
        nearby: 'Portland, South Portland, Cape Elizabeth, Old Orchard Beach',
        seller_hook: 'Scarborough\'s combination of ocean beaches, top schools, and Portland proximity creates a multi-demographic buyer pool that keeps demand high and days-on-market consistently low.',
        realtor_hook: 'Scarborough\'s geographic diversity — from oceanfront estates to suburban family homes — gives agents the ability to serve buyers at every price point in one of Cumberland County\'s most consistently in-demand markets.',
    },
    {
        slug: 'gorham',
        name: 'Gorham',
        county: 'Cumberland',
        state: 'ME',
        zip: '04038',
        population: '17,500',
        median_price: '$379,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'Gorham combines rural Maine character with University of Southern Maine\'s Gorham campus and growing suburban development that positions it as Greater Portland\'s most affordable family-friendly option with genuine small-town charm. Its village center, active agricultural community, and Sebago Lake proximity add lifestyle dimensions that purely suburban communities cannot offer at comparable prices.',
        neighborhoods: 'Gorham Village, Gorham Corner, South Gorham, USM campus area',
        nearby: 'Westbrook, Windham, Standish, Buxton',
        seller_hook: 'Gorham\'s rural character and Portland commuter appeal are attracting families who want more land and community than the inner suburbs can provide — sellers are meeting a motivated buyer pool ready to act.',
        realtor_hook: 'Gorham\'s USM anchor and Portland overflow demand give agents a reliable client base of young families and academics seeking Greater Portland affordability with genuine Maine character.',
    },
    {
        slug: 'falmouth-me',
        name: 'Falmouth',
        county: 'Cumberland',
        state: 'ME',
        zip: '04105',
        population: '12,000',
        median_price: '$579,000',
        price_trend: 'up 8%',
        avg_dom: 21,
        description: 'Falmouth is one of Greater Portland\'s most prestigious addresses, offering Casco Bay waterfront access at Falmouth Foreside, exceptional public schools, and a spacious residential character that has long attracted Maine\'s business and professional leadership. Its Mackworth Island State Park, yacht club culture, and direct Route 1 corridor to Portland\'s Munjoy Hill give it an irreplaceable blend of natural beauty and urban accessibility.',
        neighborhoods: 'Falmouth Foreside, West Falmouth, Falmouth Center, Mackworth Island area',
        nearby: 'Portland, Cumberland-me, Yarmouth-me, Cumberland Foreside',
        seller_hook: 'Falmouth Foreside\'s Casco Bay waterfront and the town\'s enduring prestige command premiums that even Portland\'s hottest neighborhoods cannot match — sellers benefit from Maine\'s most discerning and financially capable buyer pool.',
        realtor_hook: 'Falmouth\'s prestige waterfront and executive buyer demographic reward agents who specialize in premium properties and can navigate sophisticated transactions with high-net-worth clients.',
    },
    {
        slug: 'cape-elizabeth',
        name: 'Cape Elizabeth',
        county: 'Cumberland',
        state: 'ME',
        zip: '04107',
        population: '9,500',
        median_price: '$679,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Cape Elizabeth is Maine\'s most sought-after oceanfront community, anchored by the iconic Two Lights State Park and Cape Elizabeth Light, Crescent Beach, and a school system that consistently ranks among the state\'s finest — all within 20 minutes of Portland. Its combination of dramatic ocean headlands, historic New England estates, and limited new development sustains a premier market where well-positioned properties attract national buyer attention.',
        neighborhoods: 'Cape Elizabeth Center, Pond Cove, Two Lights area, Crescent Beach',
        nearby: 'Portland, South Portland, Scarborough',
        seller_hook: 'Cape Elizabeth\'s ocean setting, national lighthouse recognition, and top-ranked schools make it Maine\'s most coveted address — sellers are competing for the attention of buyers from Boston, New York, and beyond willing to pay a premium for iconic Maine waterfront.',
        realtor_hook: 'Cape Elizabeth\'s premier oceanfront status and limited inventory create a high-stakes, high-reward environment for agents who can command buyer confidence and navigate luxury transactions with precision.',
    },
    {
        slug: 'cumberland-me',
        name: 'Cumberland',
        county: 'Cumberland',
        state: 'ME',
        zip: '04021',
        population: '7,500',
        median_price: '$519,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Cumberland stretches from the mainland to Chebeague Island in Casco Bay, offering buyers a rare combination of executive-suburb land-use character, top-tier schools, Cumberland Foreside waterfront access, and island community charm that makes it uniquely appealing to families seeking both Portland proximity and genuine Maine coastal atmosphere. Its large-lot zoning preserves the open, pastoral character that distinguishes it from more densely developed Cumberland County neighbors.',
        neighborhoods: 'Cumberland Center, Cumberland Foreside, Chebeague Island, Wildwood',
        nearby: 'Falmouth-me, Yarmouth-me, North Yarmouth, Gray',
        seller_hook: 'Cumberland\'s Casco Bay access, top schools, and large-lot character attract buyers who have researched the entire Greater Portland market and decided that nothing else compares — sellers face motivated, financially prepared buyers.',
        realtor_hook: 'Cumberland\'s island community on Chebeague and mainland Foreside waterfront give agents unique property types that attract dedicated buyers unlikely to be easily diverted to competing listings.',
    },
    {
        slug: 'yarmouth-me',
        name: 'Yarmouth',
        county: 'Cumberland',
        state: 'ME',
        zip: '04096',
        population: '8,900',
        median_price: '$489,000',
        price_trend: 'up 8%',
        avg_dom: 21,
        description: 'Yarmouth is a quintessential Maine coastal village with a beautifully preserved Main Street, Royal River waterfront, Cousins Island access, and one of Cumberland County\'s finest school systems — positioned between Portland and Freeport on Route 1 for buyers who want both cultural amenities and a true village lifestyle. Its active community identity, summer clam festival, and network of walking trails make it one of the region\'s most desirable year-round communities.',
        neighborhoods: 'Yarmouth Village, Royal River area, Cousins Island, East Elm Street',
        nearby: 'Cumberland-me, Freeport, Falmouth-me, North Yarmouth',
        seller_hook: 'Yarmouth\'s village character and Royal River waterfront access attract buyers who won\'t settle for ordinary suburban living — well-presented homes here sell quickly to buyers who know exactly what they\'re looking for.',
        realtor_hook: 'Yarmouth\'s village identity and loyal community following create a referral-rich environment for agents who invest in the community and build lasting relationships with repeat and referral clients.',
    },
    {
        slug: 'freeport',
        name: 'Freeport',
        county: 'Cumberland',
        state: 'ME',
        zip: '04032',
        population: '8,500',
        median_price: '$419,000',
        price_trend: 'up 9%',
        avg_dom: 22,
        description: 'Freeport is globally recognized as the home of L.L.Bean and one of New England\'s premier outlet shopping destinations, but its residential market is defined by a strong school system, Harraseeket River harbor access, South Freeport\'s working waterfront, and an outdoor recreation culture that aligns with Maine\'s most sought-after lifestyle values. Its growing population of remote workers and outdoor enthusiasts has pushed appreciation above the county median.',
        neighborhoods: 'Freeport Village (L.L.Bean area), South Freeport, Flying Point Road, Durham Road',
        nearby: 'Yarmouth-me, Brunswick-me, North Yarmouth, Pownal',
        seller_hook: 'Freeport\'s global brand recognition and L.L.Bean-driven visitor traffic introduce thousands of potential buyers to the town every year — sellers benefit from a level of community awareness that most Maine towns simply cannot match.',
        realtor_hook: 'Freeport\'s global retail brand and growing outdoor-lifestyle appeal attract buyers from across the country who arrive pre-sold on the community, giving agents an unusually motivated and well-informed buyer pool.',
    },

    // ── Mid-Coast ──────────────────────────────────────────────────────────
    {
        slug: 'brunswick-me',
        name: 'Brunswick',
        county: 'Cumberland',
        state: 'ME',
        zip: '04011',
        population: '21,000',
        median_price: '$379,000',
        price_trend: 'up 10%',
        avg_dom: 21,
        description: 'Brunswick anchors the Mid-Coast as the home of Bowdoin College, one of America\'s finest liberal arts institutions, and the redeveloped Brunswick Landing — a former naval air station transforming into a mixed-use innovation district that is drawing tech companies, startups, and a new generation of young professional residents. Its vibrant Maine Street, Merrymeeting Bay paddling, and Amtrak Downeaster service to Portland and Boston make it a uniquely connected Maine community.',
        neighborhoods: 'Downtown Brunswick, Bowdoin College area, Topsham border, Cook\'s Corner, Mere Point',
        nearby: 'Topsham, Freeport, Bath, Harpswell',
        seller_hook: 'Brunswick Landing\'s tech-sector growth and Bowdoin College\'s faculty housing demand are adding new buyer demographics to an already strong market — sellers benefit from a community actively drawing investment and talent.',
        realtor_hook: 'Brunswick\'s Bowdoin College anchor, Brunswick Landing tech development, and Amtrak access give agents a multi-dimensional buyer story that resonates with academics, tech workers, and Boston-area commuters alike.',
    },
    {
        slug: 'bath',
        name: 'Bath',
        county: 'Sagadahoc',
        state: 'ME',
        zip: '04530',
        population: '8,000',
        median_price: '$319,000',
        price_trend: 'up 9%',
        avg_dom: 24,
        description: 'Bath is Maine\'s City of Ships — home to Bath Iron Works, one of the Navy\'s most important shipbuilding facilities, and a beautifully preserved downtown Kennebec River waterfront that has made it one of the state\'s most architecturally significant small cities. BIW\'s stable defense-contract employment, combined with a growing arts scene and accessible prices, creates steady housing demand that insulates the market from broader economic swings.',
        neighborhoods: 'Downtown Bath, Shipyard District, West Bath, Front Street waterfront',
        nearby: 'Topsham, Brunswick-me, Woolwich, Phippsburg',
        seller_hook: 'Bath Iron Works\' defense employment provides stable, recession-resistant buyer demand that few Maine cities can match — sellers benefit from a market anchored by workforce housing need that persists regardless of broader conditions.',
        realtor_hook: 'BIW\'s steady defense employment and Bath\'s growing appeal to Mid-Coast lifestyle buyers give agents a reliable, year-round transaction base that combines workforce and lifestyle buyer segments.',
    },
    {
        slug: 'topsham',
        name: 'Topsham',
        county: 'Sagadahoc',
        state: 'ME',
        zip: '04086',
        population: '9,600',
        median_price: '$349,000',
        price_trend: 'up 9%',
        avg_dom: 22,
        description: 'Topsham sits directly across the Androscoggin River from Brunswick, offering buyers close proximity to Bowdoin College, Bath Iron Works, and the Cook\'s Corner retail hub in a more affordable suburban package that has made it one of Sagadahoc County\'s fastest-growing communities. Its Topsham Fair Mall commercial corridor and newer residential subdivisions attract buyers seeking Mid-Coast accessibility with practical modern amenities.',
        neighborhoods: 'Topsham Village, Cook\'s Corner, Topsham Fair Mall area, Meadowbrook',
        nearby: 'Brunswick-me, Bath, Lisbon, Bowdoin',
        seller_hook: 'Topsham\'s Cook\'s Corner proximity and Brunswick adjacency give sellers access to both the BIW workforce and Bowdoin College buyer markets — a combined demand base that keeps competition for listings robust.',
        realtor_hook: 'Topsham\'s dual proximity to Brunswick and Bath\'s employment centers gives agents an efficient market where the same listing appeals to multiple buyer segments simultaneously.',
    },
    {
        slug: 'rockland',
        name: 'Rockland',
        county: 'Knox',
        state: 'ME',
        zip: '04841',
        population: '7,300',
        median_price: '$309,000',
        price_trend: 'up 11%',
        avg_dom: 24,
        description: 'Rockland has emerged as one of the Mid-Coast\'s most compelling arts and cultural destinations, with the Farnsworth Art Museum, a thriving Main Street gallery district, the annual Maine Lobster Festival, and a working waterfront that give it an authentic character increasingly rare in coastal New England. Its relative affordability versus Camden and the Boothbay area attracts buyers seeking genuine Maine waterfront character without the resort-town premium.',
        neighborhoods: 'Downtown Rockland, Farnsworth Art Museum area, South End, North End waterfront',
        nearby: 'Thomaston, Owls Head, Rockport, Camden',
        seller_hook: 'Rockland\'s art scene, Farnsworth Museum prestige, and working waterfront are attracting buyers who want authentic Maine coastal character — sellers are seeing growing competition from buyers priced out of Camden and the Boothbay area.',
        realtor_hook: 'Rockland\'s arts community and growing national profile as Maine\'s cultural coast hub attract buyers from major metro areas who value authenticity, giving agents a compelling story that drives premium offers.',
    },
    {
        slug: 'camden',
        name: 'Camden',
        county: 'Knox',
        state: 'ME',
        zip: '04843',
        population: '5,000',
        median_price: '$519,000',
        price_trend: 'up 10%',
        avg_dom: 26,
        description: 'Camden is iconic Maine — a stunning harbor lined with windjammers, Mount Battie rising directly behind Main Street, and a village character so quintessentially New England that it has appeared on innumerable magazine covers and bucket lists. Its combination of harbor waterfront, mountain hiking, Camden Snow Bowl skiing, and a sophisticated arts and dining scene creates a four-season luxury market that draws high-net-worth buyers from across the country.',
        neighborhoods: 'Camden Harbor, Chestnut Street, Mount Battie area, West Camden, Rockport nearby',
        nearby: 'Rockport, Rockland, Lincolnville, Hope',
        seller_hook: 'Camden\'s status as one of America\'s most photographed villages ensures your property reaches a national buyer audience — harborfront and mountain-view properties here command premiums that reflect a market with no true equivalent in New England.',
        realtor_hook: 'Camden\'s national iconic status and high-net-worth buyer profile reward agents who can execute sophisticated luxury transactions and serve buyers who are often purchasing from out of state or internationally.',
    },

    // ── York County (Southern Seacoast) ───────────────────────────────────
    {
        slug: 'biddeford',
        name: 'Biddeford',
        county: 'York',
        state: 'ME',
        zip: '04005',
        population: '22,000',
        median_price: '$319,000',
        price_trend: 'up 14%',
        avg_dom: 20,
        description: 'Biddeford is Maine\'s most talked-about real estate story — a former mill city in the midst of a remarkable renaissance driven by chef-driven restaurants, craft breweries, converted mill loft residences in the Saco Island district, and an influx of young creative professionals who have recognized the value hiding in southern Maine\'s most affordable coastal city. At 14% annual appreciation, it leads York County and attracts investor and first-time buyer attention from across the region.',
        neighborhoods: 'Downtown Biddeford, Saco Island Mill District, Hill District, Biddeford Pool',
        nearby: 'Saco, Old Orchard Beach, Kennebunk, Portland',
        seller_hook: 'Biddeford\'s 14% appreciation — the fastest in York County — and national press coverage as Maine\'s hottest revitalizing city means sellers are capturing gains that would have seemed impossible just five years ago.',
        realtor_hook: 'Biddeford\'s renaissance story and 14% appreciation trajectory make it the most compelling pitch in southern Maine for buyers seeking upside — agents who know this market well can turn every showing into a motivated offer.',
    },
    {
        slug: 'saco',
        name: 'Saco',
        county: 'York',
        state: 'ME',
        zip: '04072',
        population: '20,000',
        median_price: '$349,000',
        price_trend: 'up 12%',
        avg_dom: 21,
        description: 'Saco sits across the Saco River from Biddeford, offering buyers a community with its own mill district character, ferry road beach access to Old Orchard Beach, and a more established residential feel that complements its neighbor\'s edgier renaissance. Saco Island\'s mixed-use redevelopment, the Mill Brook water feature, and strong York County school systems give it an independent appeal that is driving consistent 12% annual appreciation.',
        neighborhoods: 'Saco Island, Ferry Road, Old Orchard Beach nearby, Camp Ellis area',
        nearby: 'Biddeford, Old Orchard Beach, Scarborough, Kennebunk',
        seller_hook: 'Saco\'s proximity to Biddeford\'s renaissance and direct Old Orchard Beach access create dual market appeal — sellers benefit from both urban-revitalization buyers and beach-lifestyle seekers simultaneously.',
        realtor_hook: 'Saco\'s position between the Biddeford renaissance and the Old Orchard Beach vacation market gives agents the ability to pitch the same listing to multiple buyer profiles, increasing the likelihood of competitive offers.',
    },
    {
        slug: 'kennebunk',
        name: 'Kennebunk',
        county: 'York',
        state: 'ME',
        zip: '04043',
        population: '11,000',
        median_price: '$519,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'Kennebunk is southern Maine\'s most complete coastal community — a walkable historic downtown, Mousam River park system, acclaimed Kennebunk Beach, and Dock Square access to Kennebunkport\'s world-class dining all within a community that balances year-round residential character with resort-town sophistication. Its Amtrak Downeaster stop makes it one of the most Boston-accessible Maine coastal towns, attracting buyers seeking genuine coastal living without sacrificing urban connectivity.',
        neighborhoods: 'Kennebunk Center, Kennebunk Beach, Lower Village, Mousam River area',
        nearby: 'Kennebunkport, Arundel, Biddeford, Wells',
        seller_hook: 'Kennebunk\'s Amtrak access, beach lifestyle, and year-round community character attract Boston-area buyers willing to pay a premium for true Maine coastal living without seasonal isolation.',
        realtor_hook: 'Kennebunk\'s Downeaster rail service and premium coastal positioning attract sophisticated Boston and Portland buyers who know what they want and are prepared to act decisively — a rewarding profile for agents who execute well.',
    },
    {
        slug: 'kennebunkport',
        name: 'Kennebunkport',
        county: 'York',
        state: 'ME',
        zip: '04046',
        population: '3,800',
        median_price: '$729,000',
        price_trend: 'up 9%',
        avg_dom: 26,
        description: 'Kennebunkport is one of New England\'s most prestigious coastal resort destinations, home to the Bush family compound at Walker\'s Point, the iconic Dock Square luxury shopping and dining district, and a collection of oceanfront estates and captain\'s houses that represent Maine\'s finest traditional coastal architecture. Vacation-home demand from Boston, New York, and Washington D.C. sustains a premium market that has appreciated steadily through multiple economic cycles.',
        neighborhoods: 'Dock Square, Cape Porpoise, Goose Rocks Beach, Beachwood area',
        nearby: 'Kennebunk, Arundel, Wells, Old Orchard Beach',
        seller_hook: 'Kennebunkport\'s national prestige and vacation-home demand from Boston, New York, and Washington ensure that well-presented properties here reach the most financially capable coastal buyers in the Northeast.',
        realtor_hook: 'Kennebunkport\'s high-end vacation-home market and national prestige attract buyers who research thoroughly and invest significantly, rewarding agents who can provide expert-level local knowledge and premium service.',
    },
    {
        slug: 'york',
        name: 'York',
        county: 'York',
        state: 'ME',
        zip: '03909',
        population: '14,000',
        median_price: '$579,000',
        price_trend: 'up 9%',
        avg_dom: 24,
        description: 'York is Maine\'s southernmost coastal town and the first taste of the state\'s legendary shoreline for buyers coming north from Massachusetts, offering five distinct villages — York Village, York Harbor, York Beach, Cape Neddick, and Short Sands — each with its own distinct oceanfront character ranging from working fishing harbors to summer resort beaches. Its proximity to the New Hampshire border and I-95 makes it one of the most accessible Maine coastal markets for Boston-area buyers.',
        neighborhoods: 'York Village, York Harbor, York Beach, Cape Neddick, Short Sands Beach',
        nearby: 'Kittery, Ogunquit, Wells, Portsmouth NH',
        seller_hook: 'York\'s five oceanfront villages give buyers options that no other Maine coastal town can match, ensuring your property reaches the broadest possible audience of motivated coastal buyers from Boston and beyond.',
        realtor_hook: 'York\'s diversity of oceanfront village characters — from working harbor to resort beach — gives agents the ability to match buyers to exactly the right property type, creating highly satisfied clients and a strong referral base.',
    },
    {
        slug: 'kittery',
        name: 'Kittery',
        county: 'York',
        state: 'ME',
        zip: '03904',
        population: '9,800',
        median_price: '$449,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'Kittery is Maine\'s southern gateway — a community defined by its outlet shopping district, Portsmouth Naval Shipyard employment, the Kittery Foreside neighborhood\'s burgeoning restaurant scene, and a Piscataqua River waterfront setting that delivers genuine coastal character at prices below southern York County neighbors. Its border position adjacent to Portsmouth, NH gives buyers two strong communities in one address.',
        neighborhoods: 'Kittery Village, Kittery Point, Kittery Foreside, Eliot nearby',
        nearby: 'York, Portsmouth NH, Eliot, South Berwick',
        seller_hook: 'Kittery\'s Portsmouth Naval Shipyard employment and booming Foreside restaurant scene are attracting buyers from both the Maine coast and the Portsmouth NH market — sellers benefit from a genuinely cross-border buyer pool.',
        realtor_hook: 'Kittery\'s dual appeal to Maine coastal lifestyle buyers and Portsmouth NH commuters creates a unique cross-market opportunity for agents who can navigate the ME-NH border effectively.',
    },
    {
        slug: 'sanford',
        name: 'Sanford',
        county: 'York',
        state: 'ME',
        zip: '04073',
        population: '21,000',
        median_price: '$239,000',
        price_trend: 'up 14%',
        avg_dom: 25,
        description: 'Sanford is York County\'s most affordable market and one of Maine\'s fastest-appreciating communities, with a traditional mill-city character, the distinctive Springvale village, and prices that allow first-time buyers and investors to enter Maine\'s coastal real estate market at a fraction of beach-town costs while remaining within 30 minutes of Kennebunk, Biddeford, and the coast. Its 14% appreciation reflects growing recognition of its structural value relative to the surrounding region.',
        neighborhoods: 'Sanford Center, Springvale, Alfred Road area, Lebanon line',
        nearby: 'Kennebunk, Biddeford, Wells, Alfred',
        seller_hook: 'Sanford\'s 14% appreciation and York County coastal proximity are drawing buyers who want a foothold in Maine real estate before prices climb further — sellers are meeting buyers with genuine urgency and competitive offers.',
        realtor_hook: 'Sanford\'s affordability and 14% appreciation create one of York County\'s most active first-time buyer and investor markets, giving agents high transaction volume and a client base that will generate referrals as values rise.',
    },

    // ── Greater Bangor & Central Maine ────────────────────────────────────
    {
        slug: 'bangor',
        name: 'Bangor',
        county: 'Penobscot',
        state: 'ME',
        zip: '04401',
        population: '31,000',
        median_price: '$219,000',
        price_trend: 'up 11%',
        avg_dom: 23,
        description: 'Bangor is the commercial and cultural hub of northern Maine, offering a Stephen King-famous Broadway streetscape, a revitalized waterfront entertainment district, Eastern Maine Medical Center healthcare employment, and some of the most accessible prices of any Maine city — all with the outdoor recreation of Acadia National Park and Baxter State Park within easy reach. Its growing remote-work appeal and affordability relative to southern Maine coastal markets are driving above-average appreciation.',
        neighborhoods: 'Downtown Bangor, Broadway, West Side, Fairmount, Stillwater Avenue, UMaine area',
        nearby: 'Brewer, Orono, Old Town, Veazie',
        seller_hook: 'Bangor\'s affordable prices, remote-work appeal, and gateway location to Maine\'s wild north are drawing buyers from southern Maine and beyond — sellers are capturing appreciation gains that reflect a market catching up to its true value.',
        realtor_hook: 'Bangor\'s diverse employment base across healthcare, education, and retail, combined with growing remote-work migration, gives agents a multidimensional buyer market that supports strong transaction volume throughout the year.',
    },
    {
        slug: 'brewer',
        name: 'Brewer',
        county: 'Penobscot',
        state: 'ME',
        zip: '04412',
        population: '9,300',
        median_price: '$229,000',
        price_trend: 'up 11%',
        avg_dom: 24,
        description: 'Brewer sits directly across the Penobscot River from Bangor, offering buyers Bangor\'s full employment and amenity access with slightly more suburban character and marginally lower prices that make it attractive to families and first-time buyers seeking maximum value in the Penobscot Valley. Its Orrington Road corridor, Wilson Street commercial area, and Penobscot River waterfront access give it a distinct identity within the greater Bangor metropolitan area.',
        neighborhoods: 'Brewer Center, South Brewer, Orrington Road, Wilson Street',
        nearby: 'Bangor, Orrington, Holden, Eddington',
        seller_hook: 'Brewer\'s Bangor adjacency and river views give sellers access to the full Greater Bangor buyer market at prices that create urgency — well-priced homes here move quickly to buyers who know the value proposition.',
        realtor_hook: 'Brewer\'s affordability relative to Bangor proper and direct bridge access to the city\'s employment base make it a high-efficiency market for agents who want strong first-time buyer volume.',
    },
    {
        slug: 'orono',
        name: 'Orono',
        county: 'Penobscot',
        state: 'ME',
        zip: '04473',
        population: '10,500',
        median_price: '$289,000',
        price_trend: 'up 10%',
        avg_dom: 24,
        description: 'Orono is anchored by the University of Maine\'s flagship campus, making it a perennial university-town market with strong rental demand, faculty and staff buyers, and a walkable downtown along the Stillwater Avenue corridor that serves both the academic community and the broader Penobscot County region. Its proximity to Old Town and Bangor, combined with UMaine\'s enrollment stability, creates a housing market that has held value through economic cycles that affected less-anchored Maine communities.',
        neighborhoods: 'UMaine campus area, Downtown Orono, Stillwater Avenue, Kelley Road',
        nearby: 'Old Town, Bangor, Veazie, Bradley',
        seller_hook: 'Orono\'s UMaine employment anchor ensures your home is visible to a steady pipeline of faculty, researchers, and staff buyers with stable incomes and strong purchase motivation.',
        realtor_hook: 'UMaine\'s faculty and staff housing demand creates a reliable, year-round buyer pipeline for Orono agents, with consistent transaction volume that is insulated from broader economic volatility.',
    },
    {
        slug: 'old-town',
        name: 'Old Town',
        county: 'Penobscot',
        state: 'ME',
        zip: '04468',
        population: '7,500',
        median_price: '$189,000',
        price_trend: 'up 12%',
        avg_dom: 28,
        description: 'Old Town straddles the Penobscot River and is home to the Penobscot Nation\'s Indian Island, the Old Town Canoe legacy, and some of Penobscot County\'s most affordable single-family housing — attracting first-time buyers and investors who recognize the value available within UMaine\'s broader orbit. Its canoe manufacturing heritage, river access, and growing recognition as a value alternative to Orono and Bangor are driving above-average appreciation.',
        neighborhoods: 'Old Town City Center, Indian Island area, Milford, Greenfield',
        nearby: 'Orono, Bangor, Milford, Alton',
        seller_hook: 'Old Town\'s 12% appreciation and affordability relative to Orono and Bangor are drawing first-time buyers and investors who see genuine upside in a market that has historically been overlooked.',
        realtor_hook: 'Old Town\'s entry-level pricing and proximity to UMaine and Bangor\'s employment base create strong first-time buyer demand that gives agents reliable transaction volume and repeat client opportunities.',
    },
    {
        slug: 'augusta',
        name: 'Augusta',
        county: 'Kennebec',
        state: 'ME',
        zip: '04330',
        population: '19,000',
        median_price: '$189,000',
        price_trend: 'up 12%',
        avg_dom: 27,
        description: 'Augusta is Maine\'s state capital and the Kennebec Valley\'s administrative hub, with MaineGeneral Medical Center, state government employment, and a Kennebec River waterfront that supports consistent residential demand across income levels. Its affordability — among Maine\'s lowest for a county seat — combined with improving downtown investment and easy I-95 access to Portland has made it an increasingly attractive destination for buyers priced out of the coast.',
        neighborhoods: 'Downtown Augusta, Cony, Western Avenue, Whitefield Street',
        nearby: 'Hallowell, Gardiner, Winslow, Sidney',
        seller_hook: 'Augusta\'s state capital stability and 12% appreciation make this an ideal moment for sellers — buyers priced out of coastal Maine are discovering that the Kennebec Valley delivers genuine value and improving quality of life.',
        realtor_hook: 'Augusta\'s state government employment base and MaineGeneral hospital create steady workforce housing demand that gives agents year-round transaction volume less dependent on seasonal market swings.',
    },
    {
        slug: 'waterville',
        name: 'Waterville',
        county: 'Kennebec',
        state: 'ME',
        zip: '04901',
        population: '16,000',
        median_price: '$195,000',
        price_trend: 'up 11%',
        avg_dom: 28,
        description: 'Waterville is home to Colby College — one of New England\'s finest liberal arts institutions — whose recent $300 million downtown investment in the Paul J. Schupf Art Center and new hotel has transformed the city\'s center into an unexpected arts destination that is reshaping the residential market. Colby\'s faculty housing demand, healthcare employment at MaineGeneral, and a growing community of arts-motivated buyers are driving appreciation rates not seen in the Kennebec Valley in decades.',
        neighborhoods: 'Downtown Waterville, Colby College area, North Street, Front Street',
        nearby: 'Winslow, Oakland, Fairfield, Augusta',
        seller_hook: 'Colby College\'s downtown investment and the new arts district are attracting buyers who recognize Waterville\'s transformation — sellers are benefiting from a market in transition toward significantly higher valuations.',
        realtor_hook: 'Colby\'s downtown revitalization and faculty housing demand create a compelling upside story for buyers that agents can use to drive urgency and premium offers in a market that is actively repricing.',
    },
    {
        slug: 'lewiston',
        name: 'Lewiston',
        county: 'Androscoggin',
        state: 'ME',
        zip: '04240',
        population: '36,000',
        median_price: '$189,000',
        price_trend: 'up 13%',
        avg_dom: 25,
        description: 'Lewiston is Maine\'s second-largest city and the most dynamic urban revitalization story in central Maine, with Bates College\'s anchor, a diverse immigrant-enriched community, major hospital employment at Central Maine Medical Center, and housing prices that represent the best per-square-foot value of any city in the state. Its Lisbon Street arts scene, Franco-American heritage, and Montello neighborhood character are attracting buyers from Portland who want genuine urban energy at half the price.',
        neighborhoods: 'Downtown Lewiston, Bates College area, Little Canada, Montello, Auburn-Lewiston Metro',
        nearby: 'Auburn, Lisbon, Sabattus, Greene',
        seller_hook: 'Lewiston\'s 13% appreciation and Bates College-driven revitalization are drawing buyers from Portland who want urban energy and upside appreciation — sellers are seeing demand and prices that reflect a market finally getting its due.',
        realtor_hook: 'Lewiston\'s 13% appreciation, Bates College anchor, and Portland-overflow buyers create one of Maine\'s highest-velocity affordable markets, giving agents the transaction volume to build a thriving practice.',
    },
    {
        slug: 'auburn',
        name: 'Auburn',
        county: 'Androscoggin',
        state: 'ME',
        zip: '04210',
        population: '24,000',
        median_price: '$209,000',
        price_trend: 'up 12%',
        avg_dom: 25,
        description: 'Auburn sits across the Androscoggin River from Lewiston as the Lewiston-Auburn Metro\'s commercial counterpart, with a Court Street business corridor, the Auburn Mall, Lake Auburn\'s waterfront recreation, and residential neighborhoods that offer slightly more suburban character than Lewiston while sharing the same affordability and appreciation trajectory. Minot Avenue\'s newer development and the Lewiston-Auburn Airport give it practical amenities that support growing buyer demand.',
        neighborhoods: 'Downtown Auburn, Court Street, Minot Avenue, Lake Auburn, Lewiston-Auburn Metro',
        nearby: 'Lewiston, Turner, Poland, Mechanic Falls',
        seller_hook: 'Auburn\'s Lake Auburn recreation and commercial amenities are attracting buyers who want Lewiston-Auburn affordability with slightly more suburban comfort — sellers are meeting a motivated pool of first-time and move-up buyers.',
        realtor_hook: 'Auburn\'s commercial anchor role in the Lewiston-Auburn Metro and Lake Auburn recreation appeal give agents a well-rounded market narrative that serves buyers from multiple demographic profiles.',
    },

    // ── Downeast & Midcoast ───────────────────────────────────────────────
    {
        slug: 'bar-harbor',
        name: 'Bar Harbor',
        county: 'Hancock',
        state: 'ME',
        zip: '04609',
        population: '5,500',
        median_price: '$649,000',
        price_trend: 'up 9%',
        avg_dom: 28,
        description: 'Bar Harbor is the gateway to Acadia National Park and one of Maine\'s most internationally recognized destinations, with a Village Green, Frenchman Bay waterfront, and summer tourism infrastructure that sustains a vacation-home and luxury residential market drawing buyers from across the country and abroad. The combination of unparalleled natural beauty, world-class hiking, and a sophisticated seasonal dining and arts scene creates a premium market with virtually no comparable alternative in northern New England.',
        neighborhoods: 'Downtown Bar Harbor, Acadia area, Northeast Harbor nearby, Southwest Harbor nearby, Mount Desert Island',
        nearby: 'Northeast Harbor, Southwest Harbor, Trenton, Ellsworth',
        seller_hook: 'Bar Harbor\'s Acadia National Park setting and international recognition as a premier Maine destination ensure your property reaches the most motivated and financially capable vacation-home buyers in the country.',
        realtor_hook: 'Bar Harbor\'s national and international buyer profile and Acadia premium create a luxury vacation-home market that rewards agents who can serve affluent out-of-state buyers seeking iconic Maine coastal properties.',
    },
    {
        slug: 'ellsworth',
        name: 'Ellsworth',
        county: 'Hancock',
        state: 'ME',
        zip: '04605',
        population: '7,900',
        median_price: '$279,000',
        price_trend: 'up 11%',
        avg_dom: 26,
        description: 'Ellsworth is the commercial hub of Downeast Maine and the practical gateway to Acadia National Park, offering buyers the service amenities of a small city — major grocery, healthcare at Maine Coast Memorial Hospital, and a Union River waterfront — at prices that remain well below the coastal resort towns it serves. Its position at the junction of Routes 1, 1A, and 3 makes it the most connected community in Hancock County, supporting year-round residential demand from workers throughout the region.',
        neighborhoods: 'Downtown Ellsworth, Ellsworth Falls, High Street, Union Street, Surry Road',
        nearby: 'Bar Harbor, Trenton, Surry, Orland',
        seller_hook: 'Ellsworth\'s role as Downeast Maine\'s commercial hub and Acadia\'s service center means sellers benefit from a buyer pool that includes both local residents and buyers priced out of the resort communities to the south.',
        realtor_hook: 'Ellsworth\'s position as Hancock County\'s commercial center and its affordability relative to Bar Harbor give agents access to a diverse buyer market that combines year-round workforce buyers with Acadia-adjacent lifestyle seekers.',
    },
];
