// cities/mi.js — Michigan city data for SEO landing pages

module.exports = [
    {
        slug: 'detroit',
        name: 'Detroit',
        county: 'Wayne',
        state: 'MI',
        zip: '48201',
        population: '620000',
        median_price: '$185,000',
        price_trend: 'up 9%',
        avg_dom: 32,
        description: 'Detroit is a city in the midst of a genuine renaissance — Midtown\'s museum corridor and Corktown\'s restaurant row anchor a creative economy alongside Ford\'s iconic Michigan Central Station redevelopment, while neighborhoods like Indian Village and Boston-Edison offer grand historic homes at prices unmatched in any comparable American city.',
        neighborhoods: 'Midtown, Corktown, Indian Village, Boston-Edison, New Center, Rivertown, Mexicantown',
        nearby: 'Hamtramck, Highland Park, Dearborn, Grosse Pointe, Warren',
        seller_hook: 'Detroit\'s rising prices and national attention from the city\'s comeback story are drawing serious buyers — let competing Detroit realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Detroit\'s renaissance neighborhoods and surging investor interest create exceptional listing opportunities — RealtorFinder connects you with motivated sellers across Wayne County.',
    },
    {
        slug: 'grosse-pointe',
        name: 'Grosse Pointe',
        county: 'Wayne',
        state: 'MI',
        zip: '48230',
        population: '42000',
        median_price: '$550,000',
        price_trend: 'up 5%',
        avg_dom: 22,
        description: 'Grosse Pointe is actually five distinct communities — Grosse Pointe City, Park, Farms, Woods, and Shores — lining Lake St. Clair east of Detroit with tree-lined streets, nationally ranked schools, and some of Michigan\'s finest early-20th-century architecture ranging from Tudor Revival estates to Colonial Revival colonials.',
        neighborhoods: 'Grosse Pointe Farms, Grosse Pointe Park, Grosse Pointe Shores, Grosse Pointe Woods, Grosse Pointe City',
        nearby: 'Harper Woods, St. Clair Shores, Detroit, East English Village',
        seller_hook: 'Grosse Pointe\'s lakeside prestige and top-ranked schools command premium prices — let competing Grosse Pointe realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Grosse Pointe\'s five distinct communities and consistent affluent buyer pool create steady listing opportunities for agents ready to compete — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'birmingham-mi',
        name: 'Birmingham',
        county: 'Oakland',
        state: 'MI',
        zip: '48009',
        population: '21000',
        median_price: '$650,000',
        price_trend: 'up 6%',
        avg_dom: 18,
        description: 'Birmingham is Oakland County\'s premier walkable city — a vibrant downtown of boutique shops, acclaimed restaurants, and a thriving arts scene surrounds leafy residential streets lined with custom-built Colonials, Tudors, and contemporaries that attract Detroit\'s top executives and professionals seeking both luxury and an exceptional school district.',
        neighborhoods: 'Downtown Birmingham, Quarton Lake, Poppleton Park, Cranbrook border, Southfield Road corridor',
        nearby: 'Bloomfield Hills, Troy, Beverly Hills MI, Bingham Farms, Royal Oak',
        seller_hook: 'Birmingham\'s walkable downtown and prestige address attract premium buyers willing to pay top dollar — let competing Oakland County realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Birmingham\'s high price points and consistent luxury buyer demand make every listing count — RealtorFinder connects you with motivated sellers ready to move.',
    },
    {
        slug: 'bloomfield-hills',
        name: 'Bloomfield Hills',
        county: 'Oakland',
        state: 'MI',
        zip: '48301',
        population: '4000',
        median_price: '$650,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Bloomfield Hills is one of Michigan\'s wealthiest cities — a low-density enclave of wooded estates, sweeping lawns, and architecturally significant homes including works influenced by Cranbrook Academy of Art, attracting corporate executives, automotive industry leaders, and families who prize absolute privacy alongside top-tier Bloomfield Hills Schools.',
        neighborhoods: 'Cranbrook, Long Lake Estates, Wabeek, Wing Lake, Franklin border',
        nearby: 'Birmingham, Troy, Bloomfield Township, West Bloomfield, Pontiac',
        seller_hook: 'Bloomfield Hills\' estate properties attract a narrow but highly qualified buyer pool — let competing luxury realtors on RealtorFinder compete to deliver the best outcome for your home.',
        realtor_hook: 'Bloomfield Hills\' prestigious addresses and large estate lots command significant commissions — RealtorFinder connects you with motivated sellers in one of Michigan\'s most exclusive markets.',
    },
    {
        slug: 'troy-mi',
        name: 'Troy',
        county: 'Oakland',
        state: 'MI',
        zip: '48084',
        population: '87000',
        median_price: '$420,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'Troy is Oakland County\'s largest city and one of Michigan\'s premier corporate addresses — home to Altair Engineering, Kmart\'s former headquarters corridor, and a dense concentration of automotive suppliers and tech firms, with well-established subdivisions, excellent Troy School District schools, and convenient access to I-75 and M-59.',
        neighborhoods: 'Wattles Road corridor, Big Beaver corridor, Sylvan Lake border, Somerset area, Livernois corridor',
        nearby: 'Birmingham, Rochester Hills, Sterling Heights, Madison Heights, Clawson',
        seller_hook: 'Troy\'s corporate employment base and top-rated schools create year-round buyer demand — let competing Oakland County realtors on RealtorFinder earn the right to represent your listing.',
        realtor_hook: 'Troy\'s large population and consistent corporate relocation market produce steady listing inventory — RealtorFinder connects you with motivated sellers across Oakland County.',
    },
    {
        slug: 'rochester-hills',
        name: 'Rochester Hills',
        county: 'Oakland',
        state: 'MI',
        zip: '48307',
        population: '73000',
        median_price: '$420,000',
        price_trend: 'up 7%',
        avg_dom: 21,
        description: 'Rochester Hills combines Oakland University\'s academic energy with upscale master-planned neighborhoods along Paint Creek — a community known for its Paint Creek Trail, Meadow Brook Hall estate on the OU campus, thriving downtown Rochester adjacent to its borders, and school districts that consistently rank among Michigan\'s finest.',
        neighborhoods: 'Stony Creek Village, Tienken Road corridor, Auburn Hills border, Orion border, Avon Township',
        nearby: 'Rochester, Auburn Hills, Troy, Shelby Township, Pontiac',
        seller_hook: 'Rochester Hills\' trail access, OU employment, and top schools draw a deep buyer pool — let competing realtors on RealtorFinder fight for the chance to list your home.',
        realtor_hook: 'Rochester Hills\' growing population and upscale subdivisions create consistent listing opportunities for motivated agents — RealtorFinder connects you with sellers ready to move.',
    },
    {
        slug: 'auburn-hills',
        name: 'Auburn Hills',
        county: 'Oakland',
        state: 'MI',
        zip: '48326',
        population: '25000',
        median_price: '$320,000',
        price_trend: 'up 8%',
        avg_dom: 23,
        description: 'Auburn Hills is home to Stellantis\'s North American headquarters and the Palace of Auburn Hills corridor — a dynamic mix of automotive and tech employment anchors a growing residential market with newer condo and townhome communities, Oakland University nearby, and Great Lakes Crossing Outlets driving significant economic activity.',
        neighborhoods: 'Stellantis HQ corridor, Oakland University border, Great Lakes Crossing area, Squirrel Road corridor',
        nearby: 'Rochester Hills, Pontiac, Waterford, Troy, Lake Orion',
        seller_hook: 'Auburn Hills\' corporate employment and proximity to Oakland University draw a steady stream of buyers — let competing realtors on RealtorFinder earn the right to list your property.',
        realtor_hook: 'Auburn Hills\' Stellantis employment base and newer housing stock create strong relocation demand — RealtorFinder connects you with motivated sellers in this dynamic Oakland County city.',
    },
    {
        slug: 'clarkston',
        name: 'Clarkston',
        county: 'Oakland',
        state: 'MI',
        zip: '48346',
        population: '9800',
        median_price: '$360,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Clarkston is a charming historic village surrounded by Independence Township\'s rolling hills and glacial lakes — its quaint downtown on the National Register of Historic Places, proximity to Orion Lakes recreational trails, Pine Knob Music Theatre, and top-rated Clarkston Community Schools make it one of Oakland County\'s most sought-after addresses.',
        neighborhoods: 'Historic Village, Independence Township, Waterford border, Lake Orion border, Pine Knob area',
        nearby: 'Lake Orion, Waterford, Auburn Hills, Holly, Pontiac',
        seller_hook: 'Clarkston\'s historic village charm and top-rated schools attract buyers willing to pay a premium — let competing Oakland County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Clarkston\'s strong school reputation and lakefront properties create motivated buyers year-round — RealtorFinder connects you with sellers in one of Oakland County\'s most desirable communities.',
    },
    {
        slug: 'novi',
        name: 'Novi',
        county: 'Oakland',
        state: 'MI',
        zip: '48375',
        population: '67000',
        median_price: '$380,000',
        price_trend: 'up 8%',
        avg_dom: 21,
        description: 'Novi is one of Metro Detroit\'s fastest-growing cities — Twelve Oaks Mall anchors a thriving retail and restaurant corridor alongside a booming tech and automotive supplier campus environment, while master-planned communities like Stonebrook and Lakeview offer newer construction homes, excellent Novi Community School District ratings, and convenient I-96 access.',
        neighborhoods: 'Twelve Oaks corridor, Stonebrook, Lakeview, Meadowbrook Road area, Beck Road corridor',
        nearby: 'Northville, Wixom, Walled Lake, South Lyon, Milford',
        seller_hook: 'Novi\'s rapid growth and retail amenities draw a consistent pool of buyers from across Metro Detroit — let competing realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Novi\'s population growth and newer housing stock create a steady pipeline of listing opportunities — RealtorFinder connects you with motivated sellers in this high-demand Oakland County market.',
    },
    {
        slug: 'northville',
        name: 'Northville',
        county: 'Wayne/Oakland',
        state: 'MI',
        zip: '48167',
        population: '6000',
        median_price: '$450,000',
        price_trend: 'up 6%',
        avg_dom: 19,
        description: 'Northville is one of Metro Detroit\'s most beloved small cities — a walkable downtown of independent boutiques, wine bars, and farmers\' markets anchored by the Victorian-era Town Square, surrounded by master-planned communities and golf course estates in Northville Township that attract families prizing both charm and exceptional schools.',
        neighborhoods: 'Historic Downtown, Northville Township, Mill Race Village, Seven Mile corridor, Sheldon Road area',
        nearby: 'Plymouth, Novi, South Lyon, Livonia, Canton',
        seller_hook: 'Northville\'s walkable downtown and prestige address command prices that reward sellers who choose the right agent — let competing realtors on RealtorFinder earn that opportunity.',
        realtor_hook: 'Northville\'s high desirability and limited inventory create strong demand for every listing — RealtorFinder connects you with motivated sellers in this Metro Detroit gem.',
    },
    {
        slug: 'plymouth-mi',
        name: 'Plymouth',
        county: 'Wayne',
        state: 'MI',
        zip: '48170',
        population: '9000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'Plymouth is a gem of Wayne County — its walkable Kellogg Park downtown draws families and young professionals to a vibrant mix of restaurants, art galleries, and seasonal festivals, while surrounding Plymouth Township offers newer subdivisions, Plymouth-Canton Community Schools, and convenient access to US-23 and I-275.',
        neighborhoods: 'Historic Downtown, Plymouth Township, Five Mile corridor, Canton border, Northville border',
        nearby: 'Northville, Canton, Livonia, Westland, Ann Arbor',
        seller_hook: 'Plymouth\'s beloved downtown and top-rated schools attract motivated buyers from across Metro Detroit — let competing Wayne County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Plymouth\'s strong community identity and consistent buyer demand make it a reliable listing market — RealtorFinder connects you with motivated sellers ready to capitalize on current prices.',
    },
    {
        slug: 'canton-mi',
        name: 'Canton',
        county: 'Wayne',
        state: 'MI',
        zip: '48187',
        population: '98000',
        median_price: '$340,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Canton Township is Wayne County\'s most populous township and one of Metro Detroit\'s premier family communities — a sprawling master-planned environment of newer subdivisions, extensive parks, the Summit on the Park recreation complex, and top-performing Plymouth-Canton Community Schools that draw families seeking suburban space at attainable prices.',
        neighborhoods: 'Canton Center, Cherry Hill corridor, Ford Road corridor, Beck Road area, Denton Road corridor',
        nearby: 'Plymouth, Northville, Westland, Ypsilanti, Ann Arbor',
        seller_hook: 'Canton\'s family-friendly reputation and large buyer pool mean strong competition for your listing — let realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Canton\'s large population and steady turnover in family subdivisions create abundant listing opportunities — RealtorFinder connects you with motivated sellers across this Wayne County powerhouse.',
    },
    {
        slug: 'livonia',
        name: 'Livonia',
        county: 'Wayne',
        state: 'MI',
        zip: '48150',
        population: '93000',
        median_price: '$260,000',
        price_trend: 'up 8%',
        avg_dom: 18,
        description: 'Livonia is one of Metro Detroit\'s most established suburban communities — a well-maintained city of postwar brick ranches and Colonial homes with Livonia Public Schools consistently ranked among Wayne County\'s finest, abundant retail along Five Mile and Plymouth Roads, and a stable blue-collar and professional workforce that has kept vacancy rates exceptionally low.',
        neighborhoods: 'Rosedale Gardens, Kingsbury Heights, McNamara area, Newburgh Road corridor, Seven Mile corridor',
        nearby: 'Westland, Plymouth, Dearborn Heights, Farmington Hills, Redford',
        seller_hook: 'Livonia\'s low vacancy rates and strong school reputation create competitive buyers willing to move fast — let competing realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Livonia\'s large established housing stock and consistent buyer demand produce reliable listing volume for agents — RealtorFinder connects you with motivated sellers throughout Wayne County.',
    },
    {
        slug: 'dearborn',
        name: 'Dearborn',
        county: 'Wayne',
        state: 'MI',
        zip: '48124',
        population: '109000',
        median_price: '$215,000',
        price_trend: 'up 9%',
        avg_dom: 21,
        description: 'Dearborn is home to Ford Motor Company\'s global headquarters and the Henry Ford Museum complex — a culturally rich community with the largest Arab American population in the United States, a thriving restaurant scene along Michigan Avenue, and well-kept neighborhoods of brick bungalows and Tudor cottages that offer Metro Detroit\'s best entry-level value.',
        neighborhoods: 'East Dearborn, West Dearborn, Springwells Village, Michigan Avenue corridor, Ford Road corridor',
        nearby: 'Dearborn Heights, Detroit, Allen Park, Melvindale, Lincoln Park',
        seller_hook: 'Dearborn\'s cultural vitality and Ford employment base attract buyers from across Metro Detroit — let competing Wayne County realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Dearborn\'s large population and rising prices create excellent listing opportunities for agents ready to serve this dynamic market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'westland',
        name: 'Westland',
        county: 'Wayne',
        state: 'MI',
        zip: '48185',
        population: '82000',
        median_price: '$210,000',
        price_trend: 'up 9%',
        avg_dom: 22,
        description: 'Westland is a dense, affordable Wayne County suburb built around Westland Center mall — a working-class community of brick ranches and Cape Cods with Wayne-Westland Community Schools, strong I-96 freeway access connecting residents to both Detroit and Ann Arbor job markets, and home prices that offer Metro Detroit\'s most accessible path to homeownership.',
        neighborhoods: 'Central Westland, Norwayne, Wildwood, Wayne border, Garden City border',
        nearby: 'Wayne, Livonia, Garden City, Canton, Inkster',
        seller_hook: 'Westland\'s affordability draws a deep pool of first-time buyers competing for limited inventory — let realtors on RealtorFinder earn the right to represent your listing.',
        realtor_hook: 'Westland\'s affordable price points and large population create high transaction volume for agents — RealtorFinder connects you with motivated sellers in this active Wayne County market.',
    },
    {
        slug: 'warren-mi',
        name: 'Warren',
        county: 'Macomb',
        state: 'MI',
        zip: '48088',
        population: '139000',
        median_price: '$210,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Warren is Michigan\'s third-largest city and Macomb County\'s seat of automotive industry employment — home to GM\'s Technical Center, Stellantis and Ford supplier campuses, and the largest concentration of defense contractors outside of the Beltway, with neighborhoods of well-maintained brick bungalows offering entry-level buyers exceptional value in Metro Detroit.',
        neighborhoods: 'Warren Center, Centerline border, East Warren, West Warren, Van Dyke corridor',
        nearby: 'Sterling Heights, Centerline, Roseville, Eastpointe, Clinton Township',
        seller_hook: 'Warren\'s automotive and defense employment drives consistent buyer demand from transferred workers — let competing Macomb County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Warren\'s large population and corporate relocation market produce steady listing inventory for agents — RealtorFinder connects you with motivated sellers in Michigan\'s third-largest city.',
    },
    {
        slug: 'sterling-heights',
        name: 'Sterling Heights',
        county: 'Macomb',
        state: 'MI',
        zip: '48310',
        population: '134000',
        median_price: '$260,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Sterling Heights is Macomb County\'s largest city and one of Metro Detroit\'s most ethnically diverse suburbs — a first-ring community of well-maintained ranch and colonial subdivisions home to a large Chaldean and Arab American community, major automotive supplier campuses along Van Dyke, and Utica Community Schools among the region\'s most respected districts.',
        neighborhoods: 'Dodge Park area, Van Dyke corridor, Mound Road corridor, Lakeside area, 18 Mile corridor',
        nearby: 'Warren, Utica, Clinton Township, Troy, Shelby Township',
        seller_hook: 'Sterling Heights\' diverse buyer pool and strong school reputation mean your listing will attract serious competition — let realtors on RealtorFinder fight for the opportunity.',
        realtor_hook: 'Sterling Heights\' large population and growing diversity create consistent listing activity for motivated agents — RealtorFinder connects you with sellers across Macomb County.',
    },
    {
        slug: 'macomb-mi',
        name: 'Macomb',
        county: 'Macomb',
        state: 'MI',
        zip: '48042',
        population: '86000',
        median_price: '$340,000',
        price_trend: 'up 7%',
        avg_dom: 23,
        description: 'Macomb Township is Macomb County\'s fastest-growing community — a newer development frontier of upscale subdivisions, sprawling ranch and colonial homes on generous lots, excellent Utica Community and Chippewa Valley school districts, and a quiet exurban character that appeals to Metro Detroit families seeking more space without leaving the county.',
        neighborhoods: 'North Macomb, Romeo Plank corridor, 23 Mile Road area, Card Road corridor, Washington Township border',
        nearby: 'Shelby Township, Romeo, Washington Township, Clinton Township, Ray Township',
        seller_hook: 'Macomb Township\'s rapid growth and newer housing stock attract buyers willing to pay premium prices — let competing realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Macomb Township\'s booming new construction and growing population create strong listing demand — RealtorFinder connects you with motivated sellers in Macomb County\'s growth corridor.',
    },
    {
        slug: 'ann-arbor',
        name: 'Ann Arbor',
        county: 'Washtenaw',
        state: 'MI',
        zip: '48104',
        population: '123000',
        median_price: '$520,000',
        price_trend: 'up 6%',
        avg_dom: 14,
        description: 'Ann Arbor is one of America\'s premier college towns elevated to a full innovation economy — the University of Michigan anchors a world-class research and biotech ecosystem alongside Google, Duo Security, and hundreds of startups, while neighborhoods like Burns Park, Kerrytown, and the Old West Side offer architectural character and walkability rarely found outside major coastal cities.',
        neighborhoods: 'Burns Park, Kerrytown, Old West Side, UM Central Campus, Eberwhite, Westside',
        nearby: 'Ypsilanti, Saline, Chelsea, Dexter, Plymouth',
        seller_hook: 'Ann Arbor\'s university economy and tech sector create year-round buyer demand at prices that reward patient sellers — let competing Washtenaw County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Ann Arbor\'s high price points, fast DOM, and steady university relocation market make it one of Michigan\'s most rewarding listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'saline',
        name: 'Saline',
        county: 'Washtenaw',
        state: 'MI',
        zip: '48176',
        population: '9500',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 21,
        description: 'Saline is Washtenaw County\'s most beloved small town — a charming downtown of locally owned shops and restaurants anchors a community known for its nationally recognized Saline Area Schools, proximity to Ann Arbor\'s employment base, and newer subdivisions that attract UM faculty and tech professionals seeking a quieter alternative to Ann Arbor\'s urban density.',
        neighborhoods: 'Historic Downtown Saline, North Saline, Saline Township, York Township border, Lodi Township border',
        nearby: 'Ann Arbor, Milan, Chelsea, Ypsilanti, Manchester',
        seller_hook: 'Saline\'s top-ranked schools and Ann Arbor proximity attract educated buyers ready to pay a premium — let competing Washtenaw County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Saline\'s school reputation and Ann Arbor spillover demand create motivated buyers for every listing — RealtorFinder connects you with sellers in this sought-after Washtenaw County market.',
    },
    {
        slug: 'chelsea-mi',
        name: 'Chelsea',
        county: 'Washtenaw',
        state: 'MI',
        zip: '48118',
        population: '5000',
        median_price: '$330,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Chelsea is a quintessential Michigan small town with outsized cultural cachet — the Purple Rose Theatre founded by Jeff Daniels, a thriving downtown of antique shops and farm-to-table restaurants, Chelsea Community Hospital, and a surrounding landscape of preserved farmland and lakes attract Ann Arbor professionals seeking a genuine small-town lifestyle within commuting distance.',
        neighborhoods: 'Historic Downtown Chelsea, North Chelsea, Sylvan Township, Lima Township border, Dexter border',
        nearby: 'Dexter, Ann Arbor, Jackson, Saline, Manchester',
        seller_hook: 'Chelsea\'s cultural identity and Ann Arbor commuter appeal create buyers who truly value what this community offers — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Chelsea\'s unique character and steady Ann Arbor overflow demand make listings here highly rewarding for the right agent — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'grand-rapids',
        name: 'Grand Rapids',
        county: 'Kent',
        state: 'MI',
        zip: '49503',
        population: '198000',
        median_price: '$295,000',
        price_trend: 'up 10%',
        avg_dom: 12,
        description: 'Grand Rapids is Michigan\'s second-largest city and one of the Midwest\'s most dynamic mid-size metros — a thriving furniture and healthcare industry anchored by Steelcase, Herman Miller, and Spectrum Health supports vibrant neighborhoods like Eastown, Heartside, and Heritage Hill with nationally recognized craft breweries, ArtPrize, and one of the country\'s best urban turnaround stories.',
        neighborhoods: 'Eastown, Heartside, Heritage Hill, East Hills, West Grand, Creston',
        nearby: 'Kentwood, Wyoming MI, East Grand Rapids, Grandville, Walker',
        seller_hook: 'Grand Rapids\' surging prices and tight inventory mean sellers are in an exceptional position — let competing Kent County realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Grand Rapids\' rapid appreciation and fast DOM make it one of Michigan\'s most rewarding listing markets — RealtorFinder connects you with motivated sellers across Kent County.',
    },
    {
        slug: 'kentwood',
        name: 'Kentwood',
        county: 'Kent',
        state: 'MI',
        zip: '49508',
        population: '55000',
        median_price: '$310,000',
        price_trend: 'up 9%',
        avg_dom: 16,
        description: 'Kentwood is the largest suburb directly south of Grand Rapids — a diverse, fast-growing community of newer subdivisions and commercial corridors along 28th Street and Breton Road, anchored by Woodland Mall, a strong manufacturing and distribution employment base, and Kentwood Public Schools that serve one of West Michigan\'s most ethnically diverse student populations.',
        neighborhoods: 'Woodland Mall area, Breton Downs, 28th Street corridor, East Paris corridor, Kentwood Center',
        nearby: 'Grand Rapids, Wyoming MI, Caledonia, Gaines Township, Byron Center',
        seller_hook: 'Kentwood\'s diverse buyer pool and proximity to Grand Rapids create fast-moving inventory — let competing realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Kentwood\'s growing population and diverse housing stock create consistent listing volume for agents — RealtorFinder connects you with motivated sellers in this Kent County growth community.',
    },
    {
        slug: 'wyoming-mi',
        name: 'Wyoming',
        county: 'Kent',
        state: 'MI',
        zip: '49509',
        population: '78000',
        median_price: '$280,000',
        price_trend: 'up 10%',
        avg_dom: 14,
        description: 'Wyoming is Kent County\'s second-largest city and Grand Rapids\' most affordable first-ring suburb — a densely populated working-class community with strong manufacturing employment, established neighborhoods of brick bungalows and Cape Cods along Chicago Drive and Division Avenue, and a growing immigrant community that has fueled remarkable neighborhood revitalization.',
        neighborhoods: 'Rogers Heights, Clyde Park corridor, Chicago Drive corridor, Division Avenue corridor, Burton Heights border',
        nearby: 'Grand Rapids, Kentwood, Grandville, Byron Center, Hudsonville',
        seller_hook: 'Wyoming\'s tight inventory and strong buyer demand from Grand Rapids overflow create excellent selling conditions — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Wyoming\'s fast-moving market and affordable price points generate high transaction volume for motivated agents — RealtorFinder connects you with sellers across this Kent County market.',
    },
    {
        slug: 'east-grand-rapids',
        name: 'East Grand Rapids',
        county: 'Kent',
        state: 'MI',
        zip: '49506',
        population: '11000',
        median_price: '$580,000',
        price_trend: 'up 7%',
        avg_dom: 16,
        description: 'East Grand Rapids is one of West Michigan\'s most desirable communities — a lakeside city wrapped around Reeds Lake with a beloved walkable downtown on Wealthy Street, East Grand Rapids Schools consistently ranked among Michigan\'s best, and a concentrated inventory of Craftsman, Colonial, and mid-century modern homes that attract Grand Rapids\' most discerning buyers.',
        neighborhoods: 'Reeds Lake, Breton Downs, Lake Drive corridor, Gaslight Village, Robinson Road area',
        nearby: 'Grand Rapids, Kentwood, Ada, Forest Hills, Cascade',
        seller_hook: 'East Grand Rapids\' Reeds Lake setting and top-ranked schools command premium prices that reward sellers who choose the right agent — let competing realtors on RealtorFinder earn that chance.',
        realtor_hook: 'East Grand Rapids\' prestige and limited inventory create strong demand for every listing that comes to market — RealtorFinder connects you with motivated sellers in this premier Kent County community.',
    },
    {
        slug: 'cascade-mi',
        name: 'Cascade',
        county: 'Kent',
        state: 'MI',
        zip: '49546',
        population: '17000',
        median_price: '$480,000',
        price_trend: 'up 7%',
        avg_dom: 19,
        description: 'Cascade Township is one of Grand Rapids\' most affluent eastern suburbs — a wooded community of executive homes and golf course estates along the Thornapple River corridor, served by the highly regarded Forest Hills Public Schools, and anchored by the Cascade Road commercial corridor connecting residents to both Grand Rapids\' urban amenities and Ada\'s charming township character.',
        neighborhoods: 'Cascade Road corridor, Thornapple River area, Forest Hills, Ada border, Caledonia border',
        nearby: 'East Grand Rapids, Ada, Caledonia, Kentwood, Lowell',
        seller_hook: 'Cascade\'s wooded estates and Forest Hills Schools create buyers willing to pay a premium for the right listing — let competing Kent County realtors on RealtorFinder earn your business.',
        realtor_hook: 'Cascade\'s executive home market and consistent affluent buyer pool make listings here highly rewarding for qualified agents — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'caledonia-mi',
        name: 'Caledonia',
        county: 'Kent',
        state: 'MI',
        zip: '49316',
        population: '13000',
        median_price: '$380,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Caledonia Township is Kent County\'s fastest-growing exurban community — a rapidly developing area of newer single-family subdivisions and rural acreage properties southeast of Grand Rapids, served by Caledonia Community Schools with a growing reputation for academics, and offering the space and affordability that Grand Rapids families increasingly seek as the city\'s core prices rise.',
        neighborhoods: 'Caledonia Village, Duncan Lake area, Kraft Avenue corridor, 84th Street corridor, Gaines Township border',
        nearby: 'Kentwood, Cascade, Byron Center, Dorr, Lowell',
        seller_hook: 'Caledonia\'s rapid growth and new construction demand mean sellers benefit from exceptional buyer competition — let realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Caledonia\'s booming development and Grand Rapids overflow demand create abundant listing opportunities for agents — RealtorFinder connects you with motivated sellers in this growth community.',
    },
];
