// cities/mn.js — Minnesota city data for SEO landing pages

module.exports = [
    {
        slug: 'minneapolis',
        name: 'Minneapolis',
        county: 'Hennepin',
        state: 'MN',
        zip: '55401',
        population: '429954',
        median_price: '$380,000',
        price_trend: 'up 4%',
        avg_dom: 22,
        description: 'Minneapolis is Minnesota\'s largest city and a thriving economic hub anchored by Target, US Bancorp, and a dense concentration of Fortune 500 headquarters, with neighborhoods from the Mill District\'s converted riverfront warehouses to Uptown\'s walkable lakeside corridors and Northeast\'s thriving arts scene. The Chain of Lakes parkway system and extensive bike infrastructure make Minneapolis one of the most livable major cities in the Midwest. Linden Hills, Longfellow, and Whittier draw buyers seeking urban character with strong neighborhood identity.',
        neighborhoods: 'Mill District, Uptown, Northeast, Linden Hills, Longfellow, Whittier, North Loop',
        nearby: 'Saint Paul, Edina, Bloomington',
        seller_hook: 'Minneapolis\'s dense buyer pool and diverse neighborhood appeal attract buyers from across the Twin Cities and beyond, and competing realtors deploy aggressive marketing strategies that consistently push final sale prices above list.',
        realtor_hook: 'Minneapolis\'s high transaction volume, diverse price points, and consistent relocation demand from Fortune 500 employers make it one of the Midwest\'s most productive listing markets.',
    },
    {
        slug: 'saint-paul',
        name: 'Saint Paul',
        county: 'Ramsey',
        state: 'MN',
        zip: '55101',
        population: '311527',
        median_price: '$320,000',
        price_trend: 'up 3%',
        avg_dom: 24,
        description: 'Saint Paul is Minnesota\'s state capital and a city of distinct character, with Summit Avenue\'s grand Victorian mansions, the vibrant Hmong Village and Frogtown neighborhoods, and a revitalized Lowertown arts district anchored by CHS Field and the Farmers Market along the Mississippi riverfront. State government, HealthPartners, and a growing tech presence through companies like Ecolab provide economic stability and a diverse professional buyer base. The Cathedral Hill and Mac-Groveland neighborhoods consistently attract buyers seeking architectural character at accessible prices.',
        neighborhoods: 'Summit Avenue, Lowertown, Cathedral Hill, Mac-Groveland, Frogtown, Highland Park',
        nearby: 'Minneapolis, Maplewood, Roseville',
        seller_hook: 'Saint Paul\'s affordability relative to Minneapolis attracts buyers priced out of the west metro, and competing realtors bring cross-market buyer networks that generate strong multi-offer situations.',
        realtor_hook: 'Saint Paul\'s growing buyer demand from the Minneapolis overflow market and state government employment base create consistent listing opportunities across a wide range of price points.',
    },
    {
        slug: 'edina',
        name: 'Edina',
        county: 'Hennepin',
        state: 'MN',
        zip: '55435',
        population: '53494',
        median_price: '$750,000',
        price_trend: 'up 5%',
        avg_dom: 18,
        description: 'Edina is the Twin Cities\' most prestigious inner-ring suburb, anchored by the Southdale Center — America\'s first enclosed shopping mall — and the Fifty-Second and France Avenue luxury retail corridor known locally as "50th & France." The city\'s top-ranked Edina Public Schools, manicured Country Club neighborhood, and strong executive buyer demand from Minneapolis corporate headquarters keep prices consistently at the metro\'s upper tier. Morningside and Parkwood Knolls offer a range of luxury options from mid-century moderns to new construction.',
        neighborhoods: 'Country Club, Morningside, Parkwood Knolls, Highlands, Cahill',
        nearby: 'Minneapolis, Bloomington, Eden Prairie',
        seller_hook: 'Edina\'s prestige address and top-ranked schools command premium valuations, and competing realtors bring high-net-worth buyer networks that regularly produce strong over-list offers.',
        realtor_hook: 'With median prices near $750K and a deep executive buyer pool, Edina delivers some of the Twin Cities\' highest per-transaction commissions for listing agents.',
    },
    {
        slug: 'eden-prairie',
        name: 'Eden Prairie',
        county: 'Hennepin',
        state: 'MN',
        zip: '55344',
        population: '64198',
        median_price: '$620,000',
        price_trend: 'up 4%',
        avg_dom: 20,
        description: 'Eden Prairie is a master-planned southwest metro city that consistently ranks among the best places to live in America, with a thriving business park corridor hosting General Mills, Supervalu, and CH Robinson alongside outstanding Eden Prairie Schools and the Purgatory Creek Recreation Area. The Eden Prairie Center mall and Town Center development provide retail and dining amenities, while neighborhoods like Bearpath and Settlers Ridge offer luxury living with golf course and nature preserve access. Strong corporate relocation demand from the southwest employment corridor keeps buyer activity high year-round.',
        neighborhoods: 'Bearpath, Settlers Ridge, Preserve, Duck Lake, Round Lake',
        nearby: 'Edina, Minnetonka, Bloomington',
        seller_hook: 'Eden Prairie\'s corporate park employers and top-ranked schools create a steady stream of relocating buyers, and competitive realtors leverage corporate relocation programs to generate offers quickly.',
        realtor_hook: 'Eden Prairie\'s combination of corporate relocation demand, strong school ratings, and premium price point makes it one of Hennepin County\'s most rewarding listing markets.',
    },
    {
        slug: 'minnetonka',
        name: 'Minnetonka',
        county: 'Hennepin',
        state: 'MN',
        zip: '55305',
        population: '54064',
        median_price: '$580,000',
        price_trend: 'up 4%',
        avg_dom: 21,
        description: 'Minnetonka is a sprawling western suburb defined by the shores of Lake Minnetonka and a business corridor along I-394 and Opus Business Park that houses UnitedHealth Group, Cargill, and dozens of medical device companies. The city\'s top-rated Minnetonka School District and proximity to Lake Minnetonka\'s 14,000 acres of boating and recreation make it a perennial top choice for executives and healthcare professionals. Neighborhoods like Woodland and Minnetonka Mills offer lakeside living with strong appreciation histories.',
        neighborhoods: 'Minnetonka Mills, Woodland, Ridgedale, Opus, Glen Lake',
        nearby: 'Eden Prairie, Plymouth, Edina',
        seller_hook: 'Minnetonka\'s lake lifestyle and corporate corridor employers attract well-qualified buyers from across the metro, and competing realtors tap healthcare and tech employer networks to bring motivated offers.',
        realtor_hook: 'Minnetonka\'s UnitedHealth Group and medical device sector employer base delivers a consistent pipeline of financially strong buyers seeking well-priced listings in top school districts.',
    },
    {
        slug: 'plymouth-mn',
        name: 'Plymouth',
        county: 'Hennepin',
        state: 'MN',
        zip: '55441',
        population: '79828',
        median_price: '$580,000',
        price_trend: 'up 4%',
        avg_dom: 21,
        description: 'Plymouth is Hennepin County\'s third-largest city and a premier northwest metro suburb anchored by Medtronic\'s global headquarters and a dense medical device and technology employer cluster along I-494. The city\'s extensive trail system connecting Medicine Lake, Parkers Lake, and Bass Lake recreation areas draws active families, while Wayzata School District\'s top ratings make Plymouth among the metro\'s most sought-after addresses. East Medicine Lake and Nanterre offer a range of executive housing options.',
        neighborhoods: 'East Medicine Lake, Nanterre, Bass Lake, Parkers Lake, Zachary Lane',
        nearby: 'Minnetonka, Maple Grove, Brooklyn Park',
        seller_hook: 'Plymouth\'s Medtronic and medical device workforce creates steady corporate relocation demand, and realtors competing for Plymouth listings bring pre-qualified buyers from nationwide employer programs.',
        realtor_hook: 'Plymouth\'s Medtronic-driven relocation traffic and top Wayzata school ratings give listing agents a reliable pipeline of well-funded buyers in a fast-moving market.',
    },
    {
        slug: 'maple-grove',
        name: 'Maple Grove',
        county: 'Hennepin',
        state: 'MN',
        zip: '55369',
        population: '70253',
        median_price: '$460,000',
        price_trend: 'up 4%',
        avg_dom: 20,
        description: 'Maple Grove is the Twin Cities\' fastest-growing suburb over the past two decades, with the Arbor Lakes retail and dining district serving as a regional destination alongside the Rush Creek Golf Club and Elm Creek Park Reserve\'s 5,000 acres of recreation. The city\'s top-rated Osseo School District, planned community design, and strong healthcare employer presence through North Memorial Health draw families seeking suburban amenities at relative value versus the south metro. New construction remains active in neighborhoods like Arbor Glen and The Reserve.',
        neighborhoods: 'Arbor Lakes, Arbor Glen, The Reserve, Rush Creek, Elm Creek',
        nearby: 'Plymouth, Champlin, Brooklyn Park',
        seller_hook: 'Maple Grove\'s regional retail destination status and top school ratings attract buyers from throughout the northwest metro, and competing realtors leverage the city\'s family-friendly reputation to generate strong buyer turnout.',
        realtor_hook: 'Maple Grove\'s steady population growth, new construction activity, and family buyer demand create high listing volume and motivated buyer traffic for efficient closings.',
    },
    {
        slug: 'champlin-mn',
        name: 'Champlin',
        county: 'Hennepin',
        state: 'MN',
        zip: '55316',
        population: '25185',
        median_price: '$460,000',
        price_trend: 'up 3%',
        avg_dom: 22,
        description: 'Champlin sits on the Mississippi River\'s western bank just north of Maple Grove, offering riverfront parks, the Champlin Mill Pond, and a quiet suburban character with Anoka-Hennepin School District\'s strong ratings at prices accessible to first-move-up buyers. The city\'s proximity to the Northwest Business Campus employment corridor and Anoka-Ramsey Community College provides economic stability, while Mississippi River Boulevard and East River Road offer scenic neighborhoods with mature trees and established lot sizes.',
        neighborhoods: 'Mill Pond, Mississippi River Boulevard, East River Road, Elm Creek adjacent, Northgate',
        nearby: 'Maple Grove, Brooklyn Park, Anoka',
        seller_hook: 'Champlin\'s riverfront character and relative affordability versus Maple Grove attract buyers ready to stretch their budget for lifestyle, and competing realtors bring cross-market buyers from throughout the northwest metro.',
        realtor_hook: 'Champlin\'s value positioning between Maple Grove and Anoka creates a motivated buyer pool of move-up purchasers, delivering efficient transactions for realtors building northwest metro volume.',
    },
    {
        slug: 'bloomington-mn',
        name: 'Bloomington',
        county: 'Hennepin',
        state: 'MN',
        zip: '55420',
        population: '89987',
        median_price: '$420,000',
        price_trend: 'up 3%',
        avg_dom: 23,
        description: 'Bloomington is home to Mall of America and the Minnesota Valley National Wildlife Refuge, a unique combination of the nation\'s largest retail destination and pristine river bottomland that defines the city\'s dual character. The city\'s proximity to Minneapolis-Saint Paul International Airport and major employers like Toro Company and the convention hospitality industry draws a diverse buyer base of airline workers, hospitality professionals, and corporate travelers turned residents. South Bloomington\'s older ranch homes and East Bloomington\'s newer neighborhoods offer distinct options.',
        neighborhoods: 'South Bloomington, East Bloomington, West Bloomington, Oxboro, Penn-American',
        nearby: 'Edina, Eden Prairie, Burnsville',
        seller_hook: 'Bloomington\'s airport proximity and Mall of America employment base generate consistent buyer demand from a wide geographic radius, and competing realtors bring buyers who prioritize commute access above all else.',
        realtor_hook: 'Bloomington\'s diverse employer base, airport access, and broad price range give realtors consistent pipeline opportunities across multiple buyer demographics throughout the year.',
    },
    {
        slug: 'burnsville',
        name: 'Burnsville',
        county: 'Dakota',
        state: 'MN',
        zip: '55337',
        population: '61434',
        median_price: '$390,000',
        price_trend: 'up 3%',
        avg_dom: 24,
        description: 'Burnsville is the south metro\'s commercial hub, anchored by the Burnsville Center mall, Heart of the City development, and a strong industrial and distribution employment corridor along I-35W that provides economic stability. Buck Hill ski area and the Crystal Lake Recreation Area give the city an outdoor recreation identity that appeals to active families, while neighborhoods like Woodhaven and Lac Lavon Drive offer lakeside living at accessible prices. Burnsville-Eagan-Savage School District\'s strong ratings support consistent family buyer demand.',
        neighborhoods: 'Woodhaven, Lac Lavon, Heart of the City, Buck Hill area, Diamond Path',
        nearby: 'Eagan, Apple Valley, Bloomington',
        seller_hook: 'Burnsville\'s position at a major south metro interchange and broad employer base attract buyers from a wide area, and competing realtors leverage family-focused marketing to generate strong open house turnout.',
        realtor_hook: 'Burnsville\'s high household density, accessible price point, and proximity to major south metro employment centers make it a reliable high-volume listing market for Dakota County realtors.',
    },
    {
        slug: 'eagan-mn',
        name: 'Eagan',
        county: 'Dakota',
        state: 'MN',
        zip: '55122',
        population: '68855',
        median_price: '$390,000',
        price_trend: 'up 3%',
        avg_dom: 23,
        description: 'Eagan is one of Dakota County\'s largest and most employment-dense cities, with Blue Cross Blue Shield of Minnesota, Thomson Reuters, and Delta Air Lines\' pilot training campus anchoring a corporate park corridor along Yankee Doodle Road. The city\'s Central Park and Cascade Bay water park provide community gathering infrastructure, while Lebanon Hills Regional Park\'s 2,000 acres of trails and lakes give residents exceptional outdoor recreation. Neighborhoods like Lexington Pointe and Woodhaven offer move-in-ready homes at prices that attract buyers from both Minneapolis and Saint Paul.',
        neighborhoods: 'Lexington Pointe, Woodhaven, Parkcliff, Pilot Knob, Thomas Lake',
        nearby: 'Burnsville, Apple Valley, Saint Paul',
        seller_hook: 'Eagan\'s dense corporate employment base creates consistent relocation demand, and competing realtors deploy Blue Cross and Thomson Reuters employee network marketing that brings pre-qualified buyers to your listing.',
        realtor_hook: 'Eagan\'s major employer concentration and central south metro location deliver a steady buyer pipeline for listing agents looking to build efficient Dakota County volume.',
    },
    {
        slug: 'apple-valley-mn',
        name: 'Apple Valley',
        county: 'Dakota',
        state: 'MN',
        zip: '55124',
        population: '55135',
        median_price: '$410,000',
        price_trend: 'up 3%',
        avg_dom: 23,
        description: 'Apple Valley is a family-oriented south metro suburb best known for the Minnesota Zoo — one of the nation\'s most acclaimed zoological parks — and a community character defined by strong schools, well-maintained neighborhoods, and the Valleywood Golf Course along the Minnesota River bluff. The city\'s Rosemount-Apple Valley-Eagan School District delivers consistently top-tier ratings, and Cedar Avenue\'s bus rapid transit provides direct connections to downtown Minneapolis for commuting buyers. Longridge and Palomino Hills offer established neighborhoods with mature landscaping.',
        neighborhoods: 'Longridge, Palomino Hills, Whitney Drive, Diamond Path, Cobblestone Lake',
        nearby: 'Eagan, Burnsville, Rosemount',
        seller_hook: 'Apple Valley\'s Minnesota Zoo identity and top school district bring buyers from throughout the south metro who prioritize community character, and competing realtors generate strong interest through family-focused marketing.',
        realtor_hook: 'Apple Valley\'s strong school reputation and steady family buyer demand create a consistent and efficient listing market for Dakota County realtors seeking high-repeat-referral opportunities.',
    },
    {
        slug: 'woodbury-mn',
        name: 'Woodbury',
        county: 'Washington',
        state: 'MN',
        zip: '55125',
        population: '75102',
        median_price: '$520,000',
        price_trend: 'up 5%',
        avg_dom: 19,
        description: 'Woodbury is the Twin Cities\' premier east metro suburb, consistently ranking among America\'s safest and most livable cities with top-rated South Washington County Schools, the Bielenberg Sports Center, and a master-planned development pattern that seamlessly integrates parks, retail, and residential neighborhoods. The city\'s proximity to 3M\'s global headquarters and strong healthcare employer presence through Regions Hospital\'s administrative functions attract a highly educated professional buyer base. Neighborhoods like Stonemill Farms and Bailey\'s Arbor represent the best of planned east metro living.',
        neighborhoods: 'Stonemill Farms, Bailey\'s Arbor, Settlers Ridge, Woodbury Lakes, Bielenberg',
        nearby: 'Stillwater, Saint Paul, Maplewood',
        seller_hook: 'Woodbury\'s national livability rankings and 3M employer proximity draw buyers from across the Twin Cities who compete aggressively for well-presented listings, giving competitive realtors exceptional leverage.',
        realtor_hook: 'Woodbury\'s premium price point, top school district, and fast-moving market make it one of Washington County\'s most rewarding listing environments for realtors building east metro business.',
    },
    {
        slug: 'stillwater-mn',
        name: 'Stillwater',
        county: 'Washington',
        state: 'MN',
        zip: '55082',
        population: '20113',
        median_price: '$520,000',
        price_trend: 'up 4%',
        avg_dom: 22,
        description: 'Stillwater is Minnesota\'s birthplace city and a beautifully preserved historic river town on the St. Croix River, with a charming Main Street of antique shops, restaurants, and bookstores that has made it one of the state\'s top tourism and lifestyle destinations. The iconic Lift Bridge, scenic bluffs, and boutique lodging draw buyers from the Twin Cities metro who want historic character and outdoor recreation access to the St. Croix National Scenic Riverway. Neighborhoods along Third Street and the north side bluffs command premium prices for their Victorian architecture and river views.',
        neighborhoods: 'Main Street district, Third Street, North Hill, South Hill, Croixwood',
        nearby: 'Woodbury, White Bear Lake, Hudson WI',
        seller_hook: 'Stillwater\'s statewide reputation as a lifestyle destination draws buyers from throughout the Twin Cities who are emotionally motivated to purchase, making well-positioned listings attract strong offers with minimal days on market.',
        realtor_hook: 'Stillwater\'s limited historic inventory and lifestyle-buyer demand create high-urgency purchase decisions that reward realtors with efficient, low-concession closings at premium price points.',
    },
    {
        slug: 'white-bear-lake',
        name: 'White Bear Lake',
        county: 'Ramsey',
        state: 'MN',
        zip: '55110',
        population: '24443',
        median_price: '$390,000',
        price_trend: 'up 3%',
        avg_dom: 24,
        description: 'White Bear Lake is the north metro\'s premier lakeside community, built around Minnesota\'s most iconic suburban lake and a charming downtown of locally owned restaurants, galleries, and the Tamarack Nature Center. The city\'s White Bear Lake School District and proximity to 3M\'s headquarters along I-694 attract families and professionals seeking lakeside lifestyle at prices well below the south metro\'s lake communities. The historic downtown and lakeshore neighborhoods along the east and west bays offer distinct architectural character from Victorian cottages to contemporary lakeshore homes.',
        neighborhoods: 'East Bay, West Bay, Downtown White Bear Lake, Birch Lake, Bellaire',
        nearby: 'Shoreview, Maplewood, Stillwater',
        seller_hook: 'White Bear Lake\'s namesake lake and community character attract buyers from throughout the north metro who place a premium on lifestyle, and competing realtors bring motivated buyers from Saint Paul and the northeast suburbs.',
        realtor_hook: 'White Bear Lake\'s lake lifestyle demand and accessible price point relative to south metro lake properties give realtors a motivated buyer pool with strong emotional purchase drivers.',
    },
    {
        slug: 'roseville-mn',
        name: 'Roseville',
        county: 'Ramsey',
        state: 'MN',
        zip: '55113',
        population: '36539',
        median_price: '$370,000',
        price_trend: 'up 3%',
        avg_dom: 25,
        description: 'Roseville is the Twin Cities\' most centrally located inner-ring suburb, positioned between Minneapolis and Saint Paul along the I-35W and I-694 interchange with Rosedale Center as its retail anchor and the Skating Center of Minnesota as a community institution. The city\'s affordability relative to its proximity to both downtowns, strong Roseville Area Schools, and diverse housing stock from post-war ramblers to newer townhomes attract first-time and move-up buyers equally. Central Park and Langton Lake neighborhood provide accessible outdoor recreation within a dense residential setting.',
        neighborhoods: 'Central Park, Langton Lake, Hamline-Midway border, Twin Lakes, Josephine',
        nearby: 'Saint Paul, Maplewood, Shoreview',
        seller_hook: 'Roseville\'s central location between two major cities creates a buyer pool drawn from the entire metro, and competing realtors leverage the city\'s commute convenience to drive fast, competitive offers.',
        realtor_hook: 'Roseville\'s central metro location and broad buyer appeal across multiple demographics give realtors consistent listing volume and efficient deal flow throughout the year.',
    },
    {
        slug: 'maplewood-mn',
        name: 'Maplewood',
        county: 'Ramsey',
        state: 'MN',
        zip: '55109',
        population: '41361',
        median_price: '$370,000',
        price_trend: 'up 3%',
        avg_dom: 25,
        description: 'Maplewood is a diverse and growing east metro suburb anchored by 3M\'s global headquarters campus along McKnight Road, which provides a large, stable professional employer base alongside healthcare through Regions and HealthEast facilities. The Maplewood Mall and Maplewood Community Center serve a community that has diversified rapidly over the past decade, with growing Somali and Asian-American communities enriching the city\'s cultural fabric. Neighborhoods along Larpenteur Avenue and near Battle Creek Regional Park offer affordable access to the east metro with quick Saint Paul connections.',
        neighborhoods: 'Battle Creek, Larpenteur Avenue, McKnight Road corridor, Hillside, Kohlman Lake',
        nearby: 'Saint Paul, Roseville, White Bear Lake',
        seller_hook: 'Maplewood\'s 3M campus and healthcare employer concentration bring steady relocation buyers, and competing realtors tap corporate relocation programs that generate pre-qualified offers efficiently.',
        realtor_hook: 'Maplewood\'s 3M-driven corporate buyer pipeline and accessible price point make it a reliable high-volume listing market for Ramsey County realtors building consistent east metro business.',
    },
    {
        slug: 'shoreview',
        name: 'Shoreview',
        county: 'Ramsey',
        state: 'MN',
        zip: '55126',
        population: '27696',
        median_price: '$430,000',
        price_trend: 'up 4%',
        avg_dom: 21,
        description: 'Shoreview is one of Ramsey County\'s most desirable suburban addresses, built around a remarkable network of lakes, wetlands, and the Shoreview Community Center with its nationally recognized aquatic facility and sports programming. The Mounds View School District\'s excellent ratings and the city\'s location along I-694 between 3M, Land O\'Lakes, and north metro employers make it a prime destination for professional families seeking quality-of-life at prices below the south metro\'s premium suburbs. Lake Owasso and Snail Lake neighborhoods provide scenic water-access living.',
        neighborhoods: 'Lake Owasso, Snail Lake, Rice Creek, Norwood Square, Lexington-Victoria',
        nearby: 'Roseville, White Bear Lake, Maplewood',
        seller_hook: 'Shoreview\'s top-rated school district and exceptional community center infrastructure draw families from throughout the north metro who compete actively for well-priced listings.',
        realtor_hook: 'Shoreview\'s Mounds View School District reputation and strong community amenities create motivated family buyers with long-term ownership intentions, generating reliable referral-based business for realtors.',
    },
];
