// cities/mo.js — Missouri city data for SEO landing pages

module.exports = [
    {
        slug: 'kansas-city',
        name: 'Kansas City',
        county: 'Jackson',
        state: 'MO',
        zip: '64101',
        population: '508090',
        median_price: '$280,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Kansas City is Missouri\'s largest city and a cultural powerhouse anchored by the Country Club Plaza, the Nelson-Atkins Museum of Art, and one of the nation\'s most celebrated barbecue traditions extending from Westport\'s nightlife district to the Jazz District\'s historic 18th & Vine corridor. The city\'s economy is driven by healthcare through HCA Midwest and Saint Luke\'s, financial services, and a growing tech scene centered on the Crossroads Arts District and Midtown. Neighborhoods like Waldo, Brookside, and Hyde Park attract buyers seeking architectural character and urban walkability at Midwest-accessible prices.',
        neighborhoods: 'Waldo, Brookside, Hyde Park, Crossroads, Westport, Midtown',
        nearby: 'Lee\'s Summit, Independence, Liberty',
        seller_hook: 'Kansas City\'s broad buyer pool spanning healthcare, finance, and tech sectors means competing realtors bring diverse buyer networks that generate multi-offer situations even at entry-level price points.',
        realtor_hook: 'Kansas City\'s high transaction volume, diverse neighborhood mix, and consistent in-migration from both coasts make it one of Missouri\'s most productive listing environments for building a high-volume real estate business.',
    },
    {
        slug: 'lees-summit',
        name: 'Lee\'s Summit',
        county: 'Jackson',
        state: 'MO',
        zip: '64063',
        population: '102650',
        median_price: '$380,000',
        price_trend: 'up 5%',
        avg_dom: 21,
        description: 'Lee\'s Summit is the Kansas City metro\'s most desirable southeastern suburb, with a beautifully preserved Victorian downtown along Third Street, the Summit Woods Crossing shopping district, and a strong corporate presence from Cerner Corporation and several healthcare employers. The city\'s Lee\'s Summit R-7 School District earns consistently high state rankings, and master-planned communities like Summit Trace and Stoney Creek attract families seeking new construction with strong resale trajectories. The downtown arts scene and community events along Douglas Street reinforce Lee\'s Summit\'s identity as a place people stay for decades.',
        neighborhoods: 'Downtown Lee\'s Summit, Summit Trace, Stoney Creek, Chapel Ridge, Legacy Park',
        nearby: 'Kansas City, Blue Springs, Raymore',
        seller_hook: 'Lee\'s Summit\'s top school ratings and downtown character create emotional buyer attachment that drives competitive offers, and realtors competing for your listing bring the metro\'s most motivated family buyers.',
        realtor_hook: 'Lee\'s Summit\'s combination of top schools, corporate employers, and premium price point for the southeast metro creates consistent high-value listing opportunities with strong repeat and referral potential.',
    },
    {
        slug: 'independence',
        name: 'Independence',
        county: 'Jackson',
        state: 'MO',
        zip: '64050',
        population: '116830',
        median_price: '$230,000',
        price_trend: 'up 4%',
        avg_dom: 28,
        description: 'Independence is Harry Truman\'s hometown and a historic city with a deeply rooted community identity centered on the Truman Historic District, the Community of Christ Temple, and the Little Blue Trace Trail system along the Little Blue River. The city\'s affordability makes it a primary destination for first-time buyers throughout the Kansas City metro, while healthcare employment through Centerpoint Medical Center and manufacturing along 40 Highway provide economic stability. The Square district\'s revitalization and new retail along Noland Road attract buyers seeking established neighborhoods at accessible entry points.',
        neighborhoods: 'Truman Historic District, Englewood, Sugar Creek border, Fairmount, Sterling Park',
        nearby: 'Kansas City, Blue Springs, Lee\'s Summit',
        seller_hook: 'Independence\'s status as the metro\'s most accessible major city creates the largest pool of pre-approved first-time buyers in the east metro, and competing realtors bring buyers who have been outbid elsewhere and are highly motivated to close.',
        realtor_hook: 'Independence\'s high first-time buyer volume and broad price accessibility make it a strong market for realtors building transaction count and referral networks across a large, motivated buyer demographic.',
    },
    {
        slug: 'blue-springs',
        name: 'Blue Springs',
        county: 'Jackson',
        state: 'MO',
        zip: '64014',
        population: '58369',
        median_price: '$280,000',
        price_trend: 'up 4%',
        avg_dom: 25,
        description: 'Blue Springs is an east-metro suburb known for Lake Jacomo and Fleming Park\'s 7,800-acre recreation complex — one of the largest urban parks in the country — alongside a family-oriented community identity anchored by the Blue Springs R-IV School District. The city\'s position along I-70 and Adams Dairy Parkway provides direct access to downtown Kansas City, and neighborhoods like Ravenwood and Deerfield offer established family housing at prices that attract move-up buyers from both Independence and Lee\'s Summit. The Grain Valley Road commercial corridor provides growing retail and dining options.',
        neighborhoods: 'Ravenwood, Deerfield, Woods Chapel, Lake Jacomo area, Adams Dairy',
        nearby: 'Independence, Lee\'s Summit, Grain Valley',
        seller_hook: 'Blue Springs\'s lake and park amenities create lifestyle-driven buyer demand that keeps homes moving even in slower markets, and competing realtors leverage Fleming Park\'s recreational appeal to attract buyers from across the east metro.',
        realtor_hook: 'Blue Springs\'s position between Independence and Lee\'s Summit and its recreational amenity premium give listing agents access to a motivated move-up buyer pool seeking lifestyle value in a strong school district.',
    },
    {
        slug: 'liberty',
        name: 'Liberty',
        county: 'Clay',
        state: 'MO',
        zip: '64068',
        population: '32276',
        median_price: '$320,000',
        price_trend: 'up 4%',
        avg_dom: 23,
        description: 'Liberty is the north metro\'s most charming suburb, with a National Register-listed historic downtown square anchored by William Jewell College and a growing collection of locally owned restaurants and boutiques along Kansas Street. The city\'s Liberty Public Schools rank among the top districts in Missouri, and proximity to the Amazon fulfillment center and North Kansas City Hospital employment corridor provides economic depth beyond its historic character. Neighborhoods like Liberty Estates and Spring Creek offer newer construction with top school access at north-metro value pricing.',
        neighborhoods: 'Downtown Liberty, Liberty Estates, Spring Creek, Clay County border, Ward Road',
        nearby: 'Kansas City, Gladstone, Kearney',
        seller_hook: 'Liberty\'s historic downtown character and top school district create a buyer pool that acts with urgency on well-priced listings, and competing realtors bring north metro buyers specifically seeking Liberty\'s unique combination of charm and school access.',
        realtor_hook: 'Liberty\'s William Jewell College and hospital employer base, combined with top school district ratings, deliver a steady stream of highly motivated buyers for listing agents building north-metro Clay County volume.',
    },
    {
        slug: 'raymore',
        name: 'Raymore',
        county: 'Cass',
        state: 'MO',
        zip: '64083',
        population: '23707',
        median_price: '$320,000',
        price_trend: 'up 5%',
        avg_dom: 22,
        description: 'Raymore is a rapidly growing south metro suburb in Cass County where new residential development along Raymore-Peculiar Road and the Scott Avenue corridor has made it one of the Kansas City metro\'s fastest-expanding communities. The Raymore-Peculiar School District\'s strong ratings and the city\'s quick I-49 access to both Kansas City and Belton attract first-move-up families seeking new construction and suburban space at prices well below the Lee\'s Summit market. The Creekmoor master-planned development with its own lake and golf course has been particularly successful at drawing buyers seeking amenity-rich living.',
        neighborhoods: 'Creekmoor, Scott Avenue corridor, Raymore-Peculiar area, Eagle Glen, Canyon Creek',
        nearby: 'Belton, Lee\'s Summit, Grandview',
        seller_hook: 'Raymore\'s new construction boom and strong school district ratings attract move-up buyers from throughout the south metro who are specifically seeking suburban value and space, generating motivated offers for well-priced listings.',
        realtor_hook: 'Raymore\'s rapid growth trajectory and new construction activity create consistent listing opportunities for Cass County realtors, with a motivated move-up buyer pool driving efficient closings.',
    },
    {
        slug: 'belton',
        name: 'Belton',
        county: 'Cass',
        state: 'MO',
        zip: '64012',
        population: '23709',
        median_price: '$260,000',
        price_trend: 'up 4%',
        avg_dom: 27,
        description: 'Belton is a south metro community with Longview Lake\'s 930-acre recreational reservoir as its defining amenity, alongside a historic downtown along Main Street and a workforce closely tied to Cerner Corporation, Richards-Gebaur Memorial Airport area employers, and the Cass County healthcare corridor. The city\'s affordability positions it as a primary option for buyers seeking lake-adjacent lifestyle at accessible prices, and new commercial development along 58 Highway has improved retail access considerably. Neighborhoods near Longview Lake\'s eastern shore and south Belton subdivisions offer the best combination of price and outdoor access.',
        neighborhoods: 'Longview Lake area, Historic Downtown Belton, East Belton, South Belton, 58 Highway corridor',
        nearby: 'Raymore, Grandview, Kansas City',
        seller_hook: 'Belton\'s Longview Lake access and south metro affordability attract buyers who have been priced out of Lee\'s Summit and are highly motivated to act on well-positioned listings.',
        realtor_hook: 'Belton\'s lake lifestyle positioning and entry-level price point create a high first-time and move-up buyer volume that gives realtors consistent deal flow in a market with low competition pressure.',
    },
    {
        slug: 'grain-valley',
        name: 'Grain Valley',
        county: 'Jackson',
        state: 'MO',
        zip: '64029',
        population: '16845',
        median_price: '$280,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Grain Valley is one of the Kansas City metro\'s fastest-growing small cities, with significant new residential development driven by its I-70 access, the Grain Valley R-V School District\'s strong performance, and land prices that support new construction at rates no longer possible closer to the urban core. The Bass Pro Shops distribution center and growing commercial corridor along Buckner-Tarsney Road provide local employment, while the nearby Lake Tapawingo neighborhood and Legacy Park development offer recreational amenity. Buyers priced out of Blue Springs and Lee\'s Summit increasingly look to Grain Valley for new construction value.',
        neighborhoods: 'Legacy Park, Lake Tapawingo area, Buckner-Tarsney corridor, Sni-A-Bar Farms, Manchester',
        nearby: 'Blue Springs, Independence, Oak Grove',
        seller_hook: 'Grain Valley\'s new construction demand and strong school district attract east-metro buyers specifically seeking value, and competing realtors bring motivated buyers who have done the school district research and are ready to act.',
        realtor_hook: 'Grain Valley\'s rapid growth, new construction activity, and east metro value positioning give listing agents consistent pipeline opportunities in one of Jackson County\'s most active emerging markets.',
    },
    {
        slug: 'saint-louis',
        name: 'Saint Louis',
        county: 'Saint Louis City',
        state: 'MO',
        zip: '63101',
        population: '286578',
        median_price: '$230,000',
        price_trend: 'up 4%',
        avg_dom: 26,
        description: 'Saint Louis is a city of extraordinary architectural legacy and neighborhood character, from the restored Victorian brick row houses of Lafayette Square and the historic homes of Tower Grove South to the revitalized Midtown arts corridor anchored by Cortex Innovation Community and Washington University\'s medical campus. The Gateway Arch National Park, Forest Park — larger than New York\'s Central Park — and a thriving craft beer and food scene along Cherokee Street and South Grand give Saint Louis an urban richness that consistently surprises visitors. Washington University, BJC HealthCare, and Edward Jones provide a strong professional employer base that supports consistent buyer demand.',
        neighborhoods: 'Lafayette Square, Tower Grove South, The Hill, Soulard, Benton Park, Midtown',
        nearby: 'Chesterfield, Clayton, Kirkwood',
        seller_hook: 'Saint Louis\'s architectural character and neighborhood diversity attract buyers from across the country, and competing realtors bring networks of Washington University affiliates and BJC professionals who are actively seeking quality city homes.',
        realtor_hook: 'Saint Louis\'s diverse neighborhood mix, broad price range, and strong institutional employer base give realtors consistent listing volume and access to buyer segments from first-time purchasers to luxury investors.',
    },
    {
        slug: 'chesterfield',
        name: 'Chesterfield',
        county: 'Saint Louis',
        state: 'MO',
        zip: '63017',
        population: '47981',
        median_price: '$580,000',
        price_trend: 'up 4%',
        avg_dom: 21,
        description: 'Chesterfield is the Saint Louis metro\'s premier western suburb, with the Chesterfield Valley retail corridor anchored by Chesterfield Mall, Taubman\'s Premium Outlets, and a concentration of healthcare employers including Mercy Hospital and Des Peres Hospital driving a high-income professional buyer base. The city\'s top-rated Rockwood and Parkway School Districts, Chesterfield Central Park, and the Baue performing arts scene create a community infrastructure that justifies the premium prices buyers willingly pay. Neighborhoods like Kehrs Mill and Long Meadow offer established luxury homes on wooded lots in highly sought school attendance zones.',
        neighborhoods: 'Kehrs Mill, Long Meadow, Wildhorse Village, Baue area, Clarkson Valley border',
        nearby: 'Saint Louis, Creve Coeur, Wildwood',
        seller_hook: 'Chesterfield\'s Rockwood and Parkway school district access and Mercy Hospital employer proximity drive consistently high buyer demand, and competing realtors bring healthcare professional networks that generate pre-qualified offers on premium listings.',
        realtor_hook: 'Chesterfield\'s dual school district appeal, premium price point, and professional buyer base make it one of St. Louis County\'s most rewarding listing markets for agents seeking high per-transaction value.',
    },
    {
        slug: 'clayton',
        name: 'Clayton',
        county: 'Saint Louis',
        state: 'MO',
        zip: '63105',
        population: '16899',
        median_price: '$650,000',
        price_trend: 'up 5%',
        avg_dom: 19,
        description: 'Clayton is the Saint Louis metro\'s most prestigious inner-ring suburb and Saint Louis County\'s seat, with a compact and walkable central business district of major law firms, financial institutions, and Centene Corporation\'s headquarters surrounded by the nation\'s most densely concentrated collection of high-value residential blocks. The Clayton School District consistently ranks as one of Missouri\'s top public school systems, and Shaw Park\'s 60-acre greenspace anchors a neighborhood fabric of Tudor, Colonial, and Georgian homes on tree-lined streets that buyers across the metro aspire to join. Maryland Avenue\'s dining and boutique district adds daily walkable amenities.',
        neighborhoods: 'Central Clayton, Wydown-Forsyth, Concordia, DeMun, Hanley Hills border',
        nearby: 'Saint Louis, Kirkwood, Creve Coeur',
        seller_hook: 'Clayton\'s top-ranked school district and county seat prestige make every listing a high-demand event, and realtors competing for Clayton listings bring affluent buyer networks that regularly produce above-list results.',
        realtor_hook: 'Clayton\'s status as St. Louis County\'s most prestigious address, with a top school district and Centene-anchored corporate employer base, delivers some of the metro\'s highest per-transaction commissions.',
    },
    {
        slug: 'kirkwood',
        name: 'Kirkwood',
        county: 'Saint Louis',
        state: 'MO',
        zip: '63122',
        population: '28168',
        median_price: '$580,000',
        price_trend: 'up 4%',
        avg_dom: 20,
        description: 'Kirkwood is one of Missouri\'s most beloved historic suburbs, with an authentically charming downtown Farmers Market and Main Street that has operated continuously since 1976 alongside the Kirkwood Train Station\'s Amtrak service and a community character that blends old-money established families with younger professional buyers. The Kirkwood R-7 School District\'s consistent top-ten Missouri rankings and the Greentree Festival neighborhood identity attract buyers from throughout the metro who place tremendous value on community and school quality. The Magic House and Powder Valley Conservation Nature Center add family-friendly amenity to an already deeply appealing urban village.',
        neighborhoods: 'Greentree Festival, Downtown Kirkwood, Dougherty Ferry, Woodbine, Old Orchard',
        nearby: 'Webster Groves, Saint Louis, Chesterfield',
        seller_hook: 'Kirkwood\'s downtown charm and top school district create one of the strongest emotional buyer attachments in the metro, producing competitive offers and fast closings for sellers who price accurately.',
        realtor_hook: 'Kirkwood\'s community identity and top school district consistently attract buyers who have done extensive research and are highly motivated to purchase, creating efficient high-value transactions for listing agents.',
    },
    {
        slug: 'webster-groves',
        name: 'Webster Groves',
        county: 'Saint Louis',
        state: 'MO',
        zip: '63119',
        population: '23145',
        median_price: '$480,000',
        price_trend: 'up 4%',
        avg_dom: 22,
        description: 'Webster Groves is a historic inner-ring suburb with one of the most distinctive community identities in the Saint Louis metro, anchored by Webster University and an Old Webster business district of independent bookstores, restaurants, and galleries along Lockwood Avenue that earned it a devoted following among artists, academics, and young professionals. The city\'s Victorian and Arts & Crafts residential streetscapes along Elm, Oak, and Maple avenues offer buyers genuine architectural character at prices below Clayton and Kirkwood. Webster Groves School District\'s strong ratings and the community\'s progressive character attract buyers seeking urban village living within easy MetroLink reach of downtown.',
        neighborhoods: 'Old Webster, Tuxedo Park, Elm Avenue, Newport, Rock Hill border',
        nearby: 'Kirkwood, Saint Louis, Glendale',
        seller_hook: 'Webster Groves\'s community character and Webster University employer base attract buyers who are passionate about the neighborhood, driving strong emotional purchase decisions and competitive offers on well-maintained homes.',
        realtor_hook: 'Webster Groves\'s loyal buyer community, university employer base, and strong architectural character create a market where well-positioned listings generate immediate and genuine buyer interest.',
    },
    {
        slug: 'creve-coeur',
        name: 'Creve Coeur',
        county: 'Saint Louis',
        state: 'MO',
        zip: '63141',
        population: '18872',
        median_price: '$550,000',
        price_trend: 'up 4%',
        avg_dom: 21,
        description: 'Creve Coeur is a premier inner-west suburb anchored by the Creve Coeur Lake Memorial Park — a 320-acre park on a stunning oxbow lake — and a concentration of Fortune 500 corporate campuses including Monsanto/Bayer\'s headquarters complex and several pharmaceutical and biotech employers that create a dense, well-compensated professional buyer base. The Parkway School District\'s elite rankings and proximity to the Olive Boulevard corporate corridor place Creve Coeur among the metro\'s top five most sought-after addresses. Neighborhoods along the lake\'s southern shore and the Ladue border command consistent premiums.',
        neighborhoods: 'Creve Coeur Lake area, Ladue border, Spoede Road, Kehrs Mill approach, Conway Road',
        nearby: 'Chesterfield, Clayton, Ladue',
        seller_hook: 'Creve Coeur\'s biotech and pharma employer cluster and Parkway School District access create a highly qualified buyer pool, and competing realtors bring Bayer and corporate relocation networks that generate pre-approved offers quickly.',
        realtor_hook: 'Creve Coeur\'s Monsanto/Bayer and pharmaceutical employer base delivers consistent corporate relocation demand, making it one of the most efficient premium listing markets in Saint Louis County.',
    },
    {
        slug: 'ladue',
        name: 'Ladue',
        county: 'Saint Louis',
        state: 'MO',
        zip: '63124',
        population: '8684',
        median_price: '$1,100,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Ladue is the Saint Louis metro\'s most exclusive municipality, a small enclave of exceptional estate properties on large wooded lots where minimum lot sizes are among the largest of any incorporated city in Missouri and homes range from historic French Country estates to contemporary architectural commissions for the region\'s most prominent families. The Ladue School District is widely considered Missouri\'s finest public school system, drawing buyers from across the country who make location decisions specifically around school access. Frontenac Plaza and the proximity to Clayton\'s professional district complete the picture for executives, physicians, and attorneys who comprise Ladue\'s buyer pool.',
        neighborhoods: 'Ladue Road estates, Log Cabin Road, Price Road, Lindbergh corridor, Frontenac border',
        nearby: 'Clayton, Creve Coeur, Town and Country',
        seller_hook: 'Ladue\'s status as Missouri\'s most prestigious address and its top-ranked school district attract high-net-worth buyers from nationwide, and realtors competing for Ladue listings bring affluent buyer networks with serious purchase intent.',
        realtor_hook: 'Ladue\'s elite market position and Missouri\'s top school district deliver the Saint Louis metro\'s most exceptional residential commissions, with a buyer pool of physicians, executives, and attorneys who transact deliberately and pay full value.',
    },
    {
        slug: 'town-and-country',
        name: 'Town and Country',
        county: 'Saint Louis',
        state: 'MO',
        zip: '63131',
        population: '10941',
        median_price: '$1,200,000',
        price_trend: 'up 5%',
        avg_dom: 38,
        description: 'Town and Country is the Saint Louis metro\'s highest-priced municipality, an incorporated city of sweeping estate properties along Ladue Road and Clayton Road where minimum lot sizes of one acre preserve the rural character of the Chesterfield Valley\'s eastern edge despite the city\'s proximity to Clayton and I-270. The city\'s location within the Parkway School District, adjacency to Ladue, and access to Kehrs Mill Road\'s biotech employer corridor create a demand structure driven by the region\'s most financially capable buyers. World-class equestrian properties, tennis estates, and architecturally significant contemporary homes define the Town and Country market.',
        neighborhoods: 'Ladue Road corridor, Clayton Road estates, Mason Road, Kehrs Mill approach, Ballwin border',
        nearby: 'Ladue, Chesterfield, Creve Coeur',
        seller_hook: 'Town and Country\'s position as the metro\'s most expensive market means every listing attracts serious high-net-worth buyers, and realtors competing for your property bring national luxury networks with motivated cash buyers.',
        realtor_hook: 'Town and Country\'s status as Missouri\'s highest-priced residential market delivers the region\'s most significant per-transaction commissions, with an estate buyer pool that is well-researched and capable of decisive action.',
    },
    {
        slug: 'ofallen',
        name: 'O\'Fallon',
        county: 'Saint Charles',
        state: 'MO',
        zip: '63366',
        population: '91316',
        median_price: '$320,000',
        price_trend: 'up 5%',
        avg_dom: 22,
        description: 'O\'Fallon is Missouri\'s fourth-largest city and the Saint Charles County growth engine, with sustained residential and commercial expansion along Bryan Road and Highway 40 driven by MasterCard\'s technology campus, Midland States Bank, and a healthcare corridor that has made the city one of the fastest-growing in the state for over two decades. The city\'s Central Park and Family Arena proximity, Winghaven neighborhood\'s master-planned amenities, and top-rated Fort Zumwalt and Francis Howell School Districts attract buyers seeking suburban value with quick I-64 access to both Saint Louis and Lambert Airport. New construction continues at a strong pace in neighborhoods like Heritage Point.',
        neighborhoods: 'Winghaven, Heritage Point, Central Park area, Bryan Road corridor, Dardenne Prairie border',
        nearby: 'Saint Charles, Saint Peters, Lake Saint Louis',
        seller_hook: 'O\'Fallon\'s rapid population growth and MasterCard employer campus create a large pool of relocating buyers, and competing realtors leverage corporate relocation programs to bring pre-qualified offers to well-positioned listings.',
        realtor_hook: 'O\'Fallon\'s sustained growth trajectory, dual school district appeal, and corporate employer base make it one of Saint Charles County\'s most consistently active listing markets for high-volume realtors.',
    },
    {
        slug: 'saint-charles',
        name: 'Saint Charles',
        county: 'Saint Charles',
        state: 'MO',
        zip: '63301',
        population: '72473',
        median_price: '$320,000',
        price_trend: 'up 4%',
        avg_dom: 23,
        description: 'Saint Charles is Missouri\'s first state capital and a city with an extraordinarily well-preserved historic DNA along Main Street\'s eight-block National Register district of 19th-century brick storefronts, taverns, and the Lewis and Clark Boathouse on the Missouri River. Lindenwood University\'s 9,000-student campus provides an economic anchor alongside the Highway 94 commercial corridor\'s retail and healthcare employment, and neighborhoods like New Town\'s neo-traditional development on the Missouri River attract buyers seeking walkable community character at value pricing versus Clayton and Kirkwood. The Spirit of St. Louis Airport employment cluster adds logistics and corporate employer diversity.',
        neighborhoods: 'Historic Main Street, New Town, Frenchtown, Elmwood, South Saint Charles',
        nearby: 'O\'Fallon, Saint Peters, Wentzville',
        seller_hook: 'Saint Charles\'s historic character and Lindenwood University activity create consistent buyer interest from both the university community and buyers drawn to the Missouri River lifestyle, giving realtors diverse buyer marketing angles.',
        realtor_hook: 'Saint Charles\'s historic tourism profile and Lindenwood employer base create a buyer pool that spans student housing investors, young professionals, and historic preservation enthusiasts — providing realtors with a uniquely varied listing opportunity.',
    },
];
