// cities/ms.js — Mississippi city data for SEO landing pages

module.exports = [
    {
        slug: 'jackson-ms',
        name: 'Jackson',
        county: 'Hinds',
        state: 'MS',
        zip: '39201',
        population: '153,000',
        median_price: '$140,000',
        price_trend: 'up 3%',
        avg_dom: 50,
        description: 'Jackson is Mississippi\'s state capital and largest city — a Deep South government and medical hub on the Pearl River where University of Mississippi Medical Center, state agencies, and Belhaven University create housing demand among government workers and medical professionals who find some of the nation\'s most affordable single-family homes and investment properties in Fondren District-adjacent neighborhoods.',
        neighborhoods: 'Fondren, Belhaven, Eastover, Ridgeland, Madison, Flowood',
        nearby: 'Ridgeland, Madison, Brandon, Flowood, Pearl',
        seller_hook: 'Jackson\'s state capital stability and affordable prices attract investors and first-time buyers — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Jackson\'s government and medical market create consistent listing activity at some of the nation\'s lowest price points — find sellers through RealtorFinder.',
    },
    {
        slug: 'gulfport',
        name: 'Gulfport',
        county: 'Harrison',
        state: 'MS',
        zip: '39501',
        population: '72,000',
        median_price: '$195,000',
        price_trend: 'up 5%',
        avg_dom: 38,
        description: 'Gulfport is Mississippi\'s second-largest city and the Gulf Coast\'s commercial backbone — a deep-water port and casino resort hub where Keesler Air Force Base spillover, a growing healthcare sector, and post-Katrina rebuilt housing stock create demand from military families, casino workers, and buyers seeking Gulf Coast lifestyle at a fraction of Florida\'s price tags.',
        neighborhoods: 'Pass Christian, Long Beach, D\'Iberville, Biloxi, Ocean Springs',
        nearby: 'Biloxi, D\'Iberville, Long Beach, Pass Christian, Ocean Springs',
        seller_hook: 'Gulfport\'s Gulf Coast lifestyle and rebuilt housing stock attract buyers from across the region — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Gulfport\'s military and casino economy create steady listing activity along the Mississippi Gulf Coast — find sellers through RealtorFinder.',
    },
    {
        slug: 'biloxi',
        name: 'Biloxi',
        county: 'Harrison',
        state: 'MS',
        zip: '39530',
        population: '47,000',
        median_price: '$185,000',
        price_trend: 'up 5%',
        avg_dom: 38,
        description: 'Biloxi is Mississippi\'s casino resort capital and home to Keesler Air Force Base — a Gulf Coast city rebuilt stronger after Hurricane Katrina, where beachfront casinos, Air Force training command housing demand, and a booming tourism economy create a unique housing market serving military families, hospitality workers, and retirees seeking affordable coastal living east of New Orleans.',
        neighborhoods: 'Ocean Springs, D\'Iberville, Woolmarket, East Biloxi, North Biloxi',
        nearby: 'Gulfport, Ocean Springs, D\'Iberville, Pascagoula, Moss Point',
        seller_hook: 'Biloxi\'s Keesler AFB community and beachfront appeal create strong buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Biloxi\'s military and resort economy drive consistent listing activity on Mississippi\'s Gulf Coast — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'hattiesburg',
        name: 'Hattiesburg',
        county: 'Forrest / Lamar',
        state: 'MS',
        zip: '39401',
        population: '48,000',
        median_price: '$175,000',
        price_trend: 'up 4%',
        avg_dom: 40,
        description: 'Hattiesburg is the Hub City of Mississippi and home to the University of Southern Mississippi — a medical and educational hub in the Longleaf Pine region where Camp Shelby military training, Forrest General Hospital, and USM\'s Golden Eagles athletics create housing demand from students, soldiers, and medical workers seeking affordable southern homeownership in one of Mississippi\'s most livable cities.',
        neighborhoods: 'Oak Grove, Petal, Sumrall, Purvis, Moselle',
        nearby: 'Petal, Oak Grove, Laurel, Purvis, Columbia',
        seller_hook: 'Hattiesburg\'s USM enrollment and medical hub create reliable buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Hattiesburg\'s university and Camp Shelby market generate steady listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'southaven',
        name: 'Southaven',
        county: 'DeSoto',
        state: 'MS',
        zip: '38671',
        population: '55,000',
        median_price: '$235,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Southaven is Mississippi\'s fastest-growing city and Memphis\'s most affordable suburb — a DeSoto County community where Tennessee income tax savings, top-ranked DeSoto County Schools, and immediate I-55 access to downtown Memphis attract Tennessee and Arkansas commuters who find significantly lower home prices while keeping their Memphis jobs, creating one of the Mid-South\'s most active buyer markets.',
        neighborhoods: 'Goodman Road, Airways, Nail Road, Horn Lake, Olive Branch',
        nearby: 'Olive Branch, Horn Lake, Hernando, Memphis TN, Germantown TN',
        seller_hook: 'Southaven\'s Memphis commuter market and DeSoto County schools create competitive listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Southaven\'s cross-state buyer pool and tax advantage make it the Mid-South\'s most active listing suburb — find sellers through RealtorFinder.',
    },
    {
        slug: 'meridian-ms',
        name: 'Meridian',
        county: 'Lauderdale',
        state: 'MS',
        zip: '39301',
        population: '36,000',
        median_price: '$130,000',
        price_trend: 'up 3%',
        avg_dom: 52,
        description: 'Meridian is east-central Mississippi\'s largest city and home to Naval Air Station Meridian — a railroad crossroads city where NAS Meridian aviation training, Meridian Community College, and Rush Foundation Hospital create demand for some of the Deep South\'s most affordable housing among military families, medical workers, and buyers seeking low-cost homeownership in a historically significant rail city.',
        neighborhoods: 'North Hills, Bonita Lakes, West Meridian, Marion, Chunky',
        nearby: 'Lauderdale, Marion, Quitman, Newton, Philadelphia',
        seller_hook: 'Meridian\'s NAS aviation training and medical community drive steady buyer demand — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Meridian\'s military and medical market create consistent listing activity at Deep South value prices — find sellers through RealtorFinder.',
    },
    {
        slug: 'olive-branch-ms',
        name: 'Olive Branch',
        county: 'DeSoto',
        state: 'MS',
        zip: '38654',
        population: '42,000',
        median_price: '$295,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Olive Branch is DeSoto County\'s fastest-growing community and one of the fastest-growing cities in the entire South — a Memphis suburb where Amazon and FedEx distribution center employment, top-rated DeSoto County Schools, and new construction master-planned neighborhoods attract Tennessee families seeking more space, lower taxes, and better schools than Memphis suburbs can provide at comparable prices.',
        neighborhoods: 'Wedgewood, Oak Grove, Sycamore, Bridgewater, Pigeon Roost',
        nearby: 'Southaven, Horn Lake, Hernando, Memphis TN, Collierville TN',
        seller_hook: 'Olive Branch\'s explosive growth and Memphis spillover create exceptional seller conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Olive Branch\'s rapid appreciation and Memphis commuter demand make it the South\'s most active listing suburb — find sellers through RealtorFinder.',
    },
];
