// cities/mt.js — Montana city data for SEO landing pages

module.exports = [
    {
        slug: 'billings',
        name: 'Billings',
        county: 'Yellowstone',
        state: 'MT',
        zip: '59101',
        population: '120,000',
        median_price: '$335,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Billings is Montana\'s largest city and the commercial capital of the Northern Rockies — an oil refining and healthcare hub on the Yellowstone River where St. Vincent Healthcare, ExxonMobil refinery employment, and proximity to Beartooth Highway and Yellowstone\'s east entrance attract energy workers, medical professionals, and remote workers seeking Montana lifestyle at the region\'s most diverse urban economy.',
        neighborhoods: 'Heights, West End, South Side, Lockwood, Laurel',
        nearby: 'Laurel, Lockwood, Hardin, Columbus, Red Lodge',
        seller_hook: 'Billings\' energy industry and Montana\'s largest healthcare system drive consistent buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Billings\' oil and medical economy create steady listing volume as Montana\'s largest city — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'missoula',
        name: 'Missoula',
        county: 'Missoula',
        state: 'MT',
        zip: '59801',
        population: '77,000',
        median_price: '$420,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Missoula is home to the University of Montana and Montana\'s most progressive city — a Clark Fork River college town where UM Grizzlies culture, a booming outdoor recreation economy, a nationally recognized food and music scene, and remote worker influx from California and the Pacific Northwest have created one of the Mountain West\'s tightest housing markets with intense competition for limited inventory.',
        neighborhoods: 'University District, South Hills, Rattlesnake, Northside, Lolo',
        nearby: 'Lolo, Frenchtown, Stevensville, Florence, Hamilton',
        seller_hook: 'Missoula\'s remote worker influx and UM enrollment create exceptional seller conditions — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Missoula\'s out-of-state buyer demand and limited inventory make every listing a competitive opportunity — find sellers through RealtorFinder.',
    },
    {
        slug: 'great-falls-mt',
        name: 'Great Falls',
        county: 'Cascade',
        state: 'MT',
        zip: '59401',
        population: '60,000',
        median_price: '$255,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Great Falls is central Montana\'s largest city and home to Malmstrom Air Force Base — a Missouri River city where ICBM wing military employment, an agricultural services economy, and Montana\'s lowest home prices among major cities attract Air Force families, agricultural workers, and buyers seeking affordable Montana homeownership with access to the Rocky Mountain Front and Glacier National Park.',
        neighborhoods: 'Black Eagle, Malmstrom AFB, Giant Springs, Cascade, Belt',
        nearby: 'Cascade, Belt, Vaughn, Ulm, Raynesford',
        seller_hook: 'Great Falls\' Malmstrom AFB community and affordable prices create consistent buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Great Falls\' military buyer pool and Montana affordability create active listing conditions — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'bozeman',
        name: 'Bozeman',
        county: 'Gallatin',
        state: 'MT',
        zip: '59715',
        population: '56,000',
        median_price: '$650,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Bozeman is Montana\'s fastest-growing city and one of the Mountain West\'s most coveted real estate markets — a Montana State University hub where Big Sky Resort access, a booming tech startup scene, and a flood of wealthy out-of-state buyers have driven prices to levels that shock longtime locals, creating Montana\'s most competitive and highest-commission listing market.',
        neighborhoods: 'Downtown, South Bozeman, Bridger Canyon, Four Corners, Belgrade',
        nearby: 'Belgrade, Manhattan MT, Three Forks, Livingston, Big Sky',
        seller_hook: 'Bozeman\'s explosive growth and wealthy buyer demand create exceptional sale prices — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Bozeman\'s high price points and out-of-state buyer influx make it Montana\'s most lucrative listing market — find sellers through RealtorFinder.',
    },
    {
        slug: 'helena-mt',
        name: 'Helena',
        county: 'Lewis and Clark',
        state: 'MT',
        zip: '59601',
        population: '34,000',
        median_price: '$345,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Helena is Montana\'s state capital and a historic gold rush city in the Rocky Mountain foothills — where state government employment, Carroll College, and proximity to Canyon Ferry Lake and the Continental Divide attract government workers, educators, and outdoor enthusiasts seeking the quiet capital-city lifestyle that Helena\'s Last Chance Gulch downtown and Victorian architecture provide.',
        neighborhoods: 'South Hills, East Side, Forestvale, East Helena, Jefferson City',
        nearby: 'East Helena, Townsend, Boulder, Jefferson City, Three Forks',
        seller_hook: 'Helena\'s state capital stability and historic charm attract consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Helena\'s government employment and Montana lifestyle appeal create steady listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'kalispell',
        name: 'Kalispell',
        county: 'Flathead',
        state: 'MT',
        zip: '59901',
        population: '26,000',
        median_price: '$430,000',
        price_trend: 'up 8%',
        avg_dom: 24,
        description: 'Kalispell is the Flathead Valley\'s commercial hub and gateway to Glacier National Park — a mountain city where Whitefish Mountain Resort, Flathead Lake, and one of Montana\'s fastest-growing regions attract California and Pacific Northwest transplants, remote workers, and retirees who create fierce competition for limited inventory in a market defined by stunning scenery and a rapidly rising price floor.',
        neighborhoods: 'Whitefish, Columbia Falls, Bigfork, Evergreen, Lakeside',
        nearby: 'Whitefish, Columbia Falls, Bigfork, Polson, Ronan',
        seller_hook: 'Kalispell\'s Glacier Park gateway and Flathead Valley lifestyle command premium prices — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Kalispell\'s resort market and out-of-state buyer demand create high-value listing opportunities in Montana\'s most scenic corridor — find sellers through RealtorFinder.',
    },
];
