// cities/nc.js — North Carolina city data for SEO landing pages

module.exports = [
    {
        slug: 'charlotte',
        name: 'Charlotte',
        county: 'Mecklenburg',
        state: 'NC',
        zip: '28201',
        population: '874000',
        median_price: '$450,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Charlotte is the financial capital of the Southeast and one of America\'s fastest-growing large cities — home to Bank of America and a major Wells Fargo hub, with neighborhoods from NoDa\'s arts district to Myers Park\'s historic estates and the emerging South End corridor drawing buyers from across the country.',
        neighborhoods: 'NoDa, South End, Plaza Midwood, Myers Park, Dilworth, Elizabeth, Ballantyne, SouthPark',
        nearby: 'Huntersville, Concord, Gastonia, Rock Hill SC, Belmont',
        seller_hook: 'Charlotte\'s banking industry migration and population growth drive fierce buyer competition — let top Mecklenburg County realtors compete on RealtorFinder to earn your listing.',
        realtor_hook: 'Charlotte\'s Fortune 500 economy and rapid growth make it one of the Southeast\'s strongest listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'huntersville',
        name: 'Huntersville',
        county: 'Mecklenburg',
        state: 'NC',
        zip: '28078',
        population: '64000',
        median_price: '$480,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Huntersville is Charlotte\'s fastest-growing northern suburb — a master-planned Mecklenburg County town on Lake Norman where the Birkdale Village lifestyle center, Northcross and Macaulay communities, and direct access to I-77 attract Charlotte banking and tech professionals seeking top schools and lakeside amenities just 15 miles from Uptown.',
        neighborhoods: 'Birkdale Village, Northcross, Macaulay, Skybrook, Vermillion, Wynfield Creek',
        nearby: 'Cornelius, Davidson, Mooresville, Charlotte, Concord',
        seller_hook: 'Huntersville\'s Birkdale Village and Lake Norman proximity drive strong buyer competition — let top Mecklenburg County realtors on RealtorFinder fight for your listing.',
        realtor_hook: 'Huntersville\'s Charlotte commuter demand and Lake Norman access create a highly motivated buyer pool — RealtorFinder connects you with sellers in this thriving suburb.',
    },
    {
        slug: 'cornelius',
        name: 'Cornelius',
        county: 'Mecklenburg',
        state: 'NC',
        zip: '28031',
        population: '32000',
        median_price: '$540,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Cornelius is Lake Norman\'s most vibrant lakefront community — a Mecklenburg County town where Peninsula Club, Antiquity, and Bailey\'s Glen neighborhoods offer direct Lake Norman water access, a thriving downtown with Jetton Park, and close proximity to Charlotte financial centers, attracting executives and families seeking a lake lifestyle without sacrificing urban amenities.',
        neighborhoods: 'The Peninsula, Antiquity, Bailey\'s Glen, Jetton Village, Pinnacle at McDowell, Davidson Landing',
        nearby: 'Davidson, Huntersville, Mooresville, Charlotte, Denver NC',
        seller_hook: 'Cornelius\'s Lake Norman waterfront appeal and Peninsula Club prestige command Mecklenburg premiums — let competing realtors on RealtorFinder maximize your sale.',
        realtor_hook: 'Cornelius\'s lakefront lifestyle and Charlotte executive buyer base create premium listing opportunities — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'davidson-nc',
        name: 'Davidson',
        county: 'Mecklenburg',
        state: 'NC',
        zip: '28036',
        population: '16000',
        median_price: '$680,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Davidson is one of the Carolinas\' most beloved small college towns — an exceptionally walkable Mecklenburg County village where Davidson College\'s liberal arts legacy anchors a community of historic homes, thriving Main Street shops, and new neo-traditional neighborhoods like River Run and The Trails that attract buyers willing to pay a premium for small-town authenticity near Charlotte.',
        neighborhoods: 'Historic Davidson, River Run, The Trails, Jetton Cove, Peninsula Point, Westmoreland',
        nearby: 'Cornelius, Huntersville, Mooresville, Charlotte, Denver NC',
        seller_hook: 'Davidson\'s beloved college-town character and Lake Norman proximity keep supply tight and prices elevated — let top Mecklenburg realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Davidson\'s unique small-town prestige and walkable character attract buyers willing to pay premium prices — RealtorFinder connects you with motivated sellers in this coveted market.',
    },
    {
        slug: 'ballantyne',
        name: 'Ballantyne',
        county: 'Mecklenburg',
        state: 'NC',
        zip: '28277',
        population: '38000',
        median_price: '$530,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Ballantyne is Charlotte\'s southern corporate and residential crown — a master-planned Mecklenburg community anchored by Ballantyne Corporate Park, host to Brighthouse Financial and dozens of major firms, where Providence Country Club, Palisades, and Ballantyne Country Club neighborhoods offer top-ranked schools and upscale suburban living for Charlotte\'s corporate class.',
        neighborhoods: 'Ballantyne Country Club, Providence Country Club, Palisades, Ballantyne West, Ardrey, Blakeney',
        nearby: 'Charlotte, Matthews, Fort Mill SC, Pineville, Lake Wylie',
        seller_hook: 'Ballantyne\'s corporate park and country club communities command some of Charlotte\'s strongest south-side prices — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Ballantyne\'s Fortune 500 corporate campus and premium neighborhoods create a well-qualified buyer pool — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'matthews-nc',
        name: 'Matthews',
        county: 'Mecklenburg',
        state: 'NC',
        zip: '28104',
        population: '32000',
        median_price: '$480,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Matthews is Mecklenburg County\'s most livable southeastern suburb — a thoughtfully managed town with a charming historic Courthouse Square, award-winning greenways and the McMullen Creek Greenway, and communities like Sardis Forest and Crown Point where Charlotte commuters prize consistent school quality, neighborhood cohesion, and competitive pricing relative to SouthPark.',
        neighborhoods: 'Sardis Forest, Crown Point, Weddington Chase, Matthews Township Plantation, Crossroads, Brightmoor',
        nearby: 'Charlotte, Concord, Indian Trail, Stallings, Monroe',
        seller_hook: 'Matthews\' beloved Courthouse Square and greenway system keep buyer competition strong — let top Mecklenburg County realtors on RealtorFinder fight to represent your home.',
        realtor_hook: 'Matthews\' Charlotte proximity and award-winning community planning attract motivated, well-qualified buyers — RealtorFinder connects you with sellers in this Mecklenburg gem.',
    },
    {
        slug: 'concord-nc',
        name: 'Concord',
        county: 'Cabarrus',
        state: 'NC',
        zip: '28025',
        population: '108000',
        median_price: '$390,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Concord is Cabarrus County\'s booming NASCAR-heritage city — home to Charlotte Motor Speedway and a massive Concord Mills outlet mall complex that has helped anchor a residential boom where Afton Village, Christenbury, and Moss Creek communities attract Charlotte commuters seeking more square footage at prices still well below Mecklenburg County.',
        neighborhoods: 'Afton Village, Christenbury, Moss Creek, McCullough, Cabarrus Crossing, Poplar Tent',
        nearby: 'Kannapolis, Charlotte, Harrisburg, Huntersville, Mooresville',
        seller_hook: 'Concord\'s Charlotte Motor Speedway economy and Mecklenburg overflow demand drive appreciation — let competitive Cabarrus County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Concord\'s NASCAR economy and affordability relative to Charlotte attract buyers from across the metro — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'kannapolis',
        name: 'Kannapolis',
        county: 'Cabarrus',
        state: 'NC',
        zip: '28081',
        population: '52000',
        median_price: '$320,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Kannapolis is one of North Carolina\'s most compelling turnaround stories — a former Cannon textile mill town now home to the NC Research Campus biotech center and NC State\'s plant science hub, where downtown revitalization and major stadium investments alongside Atrium Health\'s expansion are creating new appreciation momentum for buyers entering ahead of the curve.',
        neighborhoods: 'Downtown Kannapolis, NinetyOne District, West Avenue corridor, Forest Hills, Village of Kannapolis',
        nearby: 'Concord, Salisbury, Mooresville, Harrisburg, China Grove',
        seller_hook: 'Kannapolis\'s biotech campus and downtown revival are driving rapid appreciation — let competing Cabarrus County realtors on RealtorFinder earn the right to sell your home.',
        realtor_hook: 'Kannapolis\'s NC Research Campus and downtown redevelopment attract buyers getting ahead of major appreciation — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'mooresville-nc',
        name: 'Mooresville',
        county: 'Iredell',
        state: 'NC',
        zip: '28115',
        population: '50000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Mooresville is NASCAR\'s hometown — Race City USA where more than 80 racing teams and suppliers anchor an industrial base, while Lake Norman\'s Iredell County shoreline, Trump National Golf Club, and the upscale Langtree at the Lake mixed-use development attract Charlotte executives and second-home buyers seeking premium lake living at lower prices than Mecklenburg County.',
        neighborhoods: 'Langtree, Trump National, The Point, Lake Shore Estates, Morrison Plantation, Pinnacle at Morrison',
        nearby: 'Davidson, Cornelius, Charlotte, Huntersville, Denver NC',
        seller_hook: 'Mooresville\'s Lake Norman waterfront and NASCAR-economy demand command strong Iredell County prices — let top local realtors on RealtorFinder compete for your listing.',
        realtor_hook: 'Mooresville\'s Lake Norman access and Race City industrial economy attract buyers across all price points — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'raleigh',
        name: 'Raleigh',
        county: 'Wake',
        state: 'NC',
        zip: '27601',
        population: '467000',
        median_price: '$550,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Raleigh is the capital of North Carolina and the center of the Research Triangle — a booming tech and pharmaceutical hub where Apple, Google, and Wolfspeed have announced major operations, creating a buyer pool of well-compensated professionals driving some of the Southeast\'s strongest home appreciation.',
        neighborhoods: 'Five Points, Oakwood, North Hills, Brier Creek, Cameron Village, Mordecai, Glenwood South',
        nearby: 'Durham, Cary, Chapel Hill, Garner, Wake Forest',
        seller_hook: 'Raleigh\'s tech sector expansion is driving premium buyer demand — let competing Wake County realtors on RealtorFinder fight to earn the right to represent your home.',
        realtor_hook: 'Raleigh\'s Research Triangle tech economy creates high-earning buyer demand that keeps listing prices strong — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'cary',
        name: 'Cary',
        county: 'Wake',
        state: 'NC',
        zip: '27511',
        population: '174000',
        median_price: '$620,000',
        price_trend: 'up 6%',
        avg_dom: 23,
        description: 'Cary is the premier suburb of the Research Triangle — a master-planned, exceptionally well-managed town with top-ranked schools, SAS Institute headquarters, and a reputation for safety and livability that has earned it perennial recognition on national best-places-to-live lists and strong demand from tech-industry relocatees.',
        neighborhoods: 'West Cary, MacGregor Downs, Preston, Lochmere, Cary Park, Regency, Oaks',
        nearby: 'Raleigh, Apex, Morrisville, Durham, Research Triangle Park',
        seller_hook: 'Cary\'s top-school reputation and SAS corporate presence drive premium buyer demand — let competing Wake County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Cary\'s elite school ratings and tech-company proximity create a premium listing market with highly qualified buyers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'apex',
        name: 'Apex',
        county: 'Wake',
        state: 'NC',
        zip: '27502',
        population: '67000',
        median_price: '$620,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Apex is consistently ranked one of America\'s best places to live — a vibrant Wake County town where a beautifully preserved Historic Downtown anchors master-planned communities like Bella Casa and Sweetwater, and where Research Triangle Park proximity and Wake County schools drive fierce competition from tech professionals seeking suburban character just minutes from the region\'s largest employment corridors.',
        neighborhoods: 'Historic Downtown Apex, Bella Casa, Sweetwater, Haddon Hall, Salem Village, Lake Pine',
        nearby: 'Cary, Morrisville, Holly Springs, Raleigh, Fuquay-Varina',
        seller_hook: 'Apex\'s national best-places recognition and top Wake County schools drive consistently strong buyer competition — let top realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Apex\'s national rankings and RTP proximity attract the Research Triangle\'s most motivated buyers — RealtorFinder connects you with sellers in this highly sought-after market.',
    },
    {
        slug: 'morrisville-nc',
        name: 'Morrisville',
        county: 'Wake',
        state: 'NC',
        zip: '27560',
        population: '32000',
        median_price: '$530,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Morrisville is the Research Triangle\'s most strategically positioned suburb — a diverse, rapidly growing Wake County town literally adjacent to Research Triangle Park and RDU International Airport where Morrisville Parkway and Church Street corridors and communities like Morrisville Parkway draw tech workers from Cisco, NetApp, and IBM who prize proximity to their campuses above all else.',
        neighborhoods: 'Morrisville Parkway corridor, Church Street area, Morrisville Commons, Breckenridge, Perimeter Woods',
        nearby: 'Cary, Durham, Raleigh, Apex, Research Triangle Park',
        seller_hook: 'Morrisville\'s RTP adjacency creates relentless tech-worker buyer demand — let competing Wake County realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Morrisville\'s Research Triangle Park location ensures a consistent stream of well-paid tech buyers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'wake-forest',
        name: 'Wake Forest',
        county: 'Wake',
        state: 'NC',
        zip: '27587',
        population: '47000',
        median_price: '$490,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Wake Forest is one of the Research Triangle\'s fastest-growing northern suburbs — a charming town that has tripled in size over the past decade where Heritage and Holding Village master-planned communities attract Raleigh commuters seeking newer construction and Wake County schools at prices still below the Cary and Apex corridor, supported by easy US-1 access to downtown Raleigh.',
        neighborhoods: 'Heritage, Holding Village, Traditions, Hasentree, Olde Mill Stream, Franklin Place',
        nearby: 'Raleigh, Youngsville, Rolesville, Louisburg, Franklinton',
        seller_hook: 'Wake Forest\'s explosive growth and Heritage community demand drive strong appreciation — let competing Wake County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Wake Forest\'s Raleigh commuter demand and affordable entry points relative to Cary attract motivated buyers — RealtorFinder connects you with sellers in this booming suburb.',
    },
    {
        slug: 'holly-springs',
        name: 'Holly Springs',
        county: 'Wake',
        state: 'NC',
        zip: '27540',
        population: '46000',
        median_price: '$540,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Holly Springs is Wake County\'s high-achieving southwestern suburb — a rapidly growing town where Bass Lake Park, Ting Park minor-league stadium, and new master-planned communities like Woodrun and Sunset Ridge attract families seeking top-ranked schools, a walkable downtown, and biotech employment from the growing drug manufacturing and pharmaceutical corridor along NC-55.',
        neighborhoods: 'Woodrun, Sunset Ridge, 12 Oaks, Braxton Village, Holly Glen, Bass Lake area',
        nearby: 'Fuquay-Varina, Apex, Cary, Raleigh, Garner',
        seller_hook: 'Holly Springs\' top-rated schools and pharma-corridor employment drive fierce buyer competition — let top Wake County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Holly Springs\' bio-manufacturing corridor and new-community development attract well-qualified buyers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'fuquay-varina',
        name: 'Fuquay-Varina',
        county: 'Wake',
        state: 'NC',
        zip: '27526',
        population: '38000',
        median_price: '$460,000',
        price_trend: 'up 7%',
        avg_dom: 27,
        description: 'Fuquay-Varina is Wake County\'s most affordable growth destination — a rapidly expanding southern suburb where a walkable Twin Towns historic district, active brewery and dining scene on Main Street, and communities like Bella Square and Braxton Village attract buyers priced out of Holly Springs and Apex who want Wake County schools without Cary price tags.',
        neighborhoods: 'Bella Square, Braxton Village, Fuquay Village, Varina, Sunset Lake Road corridor, Harnett County border communities',
        nearby: 'Holly Springs, Apex, Garner, Angier, Lillington',
        seller_hook: 'Fuquay-Varina\'s Twin Towns charm and Wake County schools at lower price points attract motivated buyers — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Fuquay-Varina\'s affordability within Wake County attracts buyers priced out of Cary and Holly Springs — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'durham',
        name: 'Durham',
        county: 'Durham',
        state: 'NC',
        zip: '27701',
        population: '283000',
        median_price: '$430,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Durham is the Bull City — a vibrant, progressive Research Triangle city where Duke University and Duke Health anchor an intellectual and medical economy that draws buyers from across the country, and where neighborhoods like Walltown, Trinity Park, and East Durham are experiencing rapid appreciation driven by a growing national profile.',
        neighborhoods: 'Trinity Park, Watts-Hillandale, East Durham, Northgate Park, Walltown, Old West Durham, Forest Hills',
        nearby: 'Chapel Hill, Raleigh, Cary, Hillsborough, Mebane',
        seller_hook: 'Durham\'s Duke-driven economy and rising national profile drive strong buyer demand — let competing Triangle realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Durham\'s Duke University economy and growing Bull City identity attract motivated buyers — RealtorFinder connects you with sellers in one of the Triangle\'s hottest markets.',
    },
    {
        slug: 'chapel-hill',
        name: 'Chapel Hill',
        county: 'Orange',
        state: 'NC',
        zip: '27514',
        population: '61000',
        median_price: '$600,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Chapel Hill is the intellectual heart of the Research Triangle — home to the University of North Carolina\'s flagship campus and UNC Health Care, a nationally recognized medical system, where Franklin Street\'s iconic corridor, Meadowmont\'s walkable neighborhood, and Southern Village\'s village center anchor a market of academics, physicians, and tech professionals who prize UNC\'s liberal arts legacy and Tar Heel identity.',
        neighborhoods: 'Meadowmont, Southern Village, Northside, Glen Lennox, Morgan Creek, Battle Forest',
        nearby: 'Carrboro, Durham, Hillsborough, Pittsboro, Apex',
        seller_hook: 'Chapel Hill\'s UNC flagship and UNC Health demand keep supply tight and prices elevated — let top Orange County realtors on RealtorFinder maximize your sale.',
        realtor_hook: 'Chapel Hill\'s UNC faculty and health system create a steady premium buyer pipeline — RealtorFinder connects you with motivated sellers in this coveted Triangle market.',
    },
    {
        slug: 'carrboro',
        name: 'Carrboro',
        county: 'Orange',
        state: 'NC',
        zip: '27510',
        population: '22000',
        median_price: '$510,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Carrboro is the Triangle\'s most progressive and culturally vibrant small town — a walkable community directly adjacent to UNC-Chapel Hill where the ArtsCenter, Cat\'s Cradle music venue, and Saturday farmers\' market anchor a community of academics, artists, and tech workers who prize Carrboro\'s urban-village character and deep commitment to local businesses and sustainability.',
        neighborhoods: 'Downtown Carrboro, Carrboro Village, Northwood, Bolin Creek corridor, Craig-Gomains, Lloyd Street area',
        nearby: 'Chapel Hill, Durham, Hillsborough, Mebane, Pittsboro',
        seller_hook: 'Carrboro\'s walkable village identity and UNC-adjacent demand keep inventory scarce and prices strong — let competing Orange County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Carrboro\'s UNC proximity and beloved local culture attract buyers seeking Triangle living with walkable character — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'wilmington-nc',
        name: 'Wilmington',
        county: 'New Hanover',
        state: 'NC',
        zip: '28401',
        population: '119000',
        median_price: '$420,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Wilmington is North Carolina\'s premier coastal city — a historic port town with a charming riverfront district, direct access to Wrightsville Beach and Carolina Beach, a booming film industry, and a real estate market that draws retirees, remote workers, and beach-lifestyle buyers from across the East Coast.',
        neighborhoods: 'Historic District, Midtown, Oleander Drive corridor, Landfall, Carolina Beach access, Wrightsville Beach access',
        nearby: 'Leland, Hampstead, Carolina Beach, Wrightsville Beach, Surf City',
        seller_hook: 'Wilmington\'s beach access and coastal lifestyle draw buyers from across the East Coast — let top Cape Fear realtors compete on RealtorFinder to maximize your sale.',
        realtor_hook: 'Wilmington\'s coastal appeal and growing film economy attract buyers from across the region — RealtorFinder connects you with motivated sellers in this Cape Fear market.',
    },
    {
        slug: 'leland-nc',
        name: 'Leland',
        county: 'Brunswick',
        state: 'NC',
        zip: '28451',
        population: '27000',
        median_price: '$360,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Leland is Wilmington\'s fastest-growing bedroom community — a Brunswick County boom town just across the Cape Fear River where Waterford, Belville, and Brunswick Forest master-planned communities offer new-construction single-family homes at prices well below New Hanover County, attracting Wilmington professionals and retirees seeking larger homes, lower taxes, and easy beach access.',
        neighborhoods: 'Waterford, Brunswick Forest, Magnolia Greens, Westbay Estates, Belville, Mallory Creek Plantation',
        nearby: 'Wilmington, Bolivia, Navassa, Shallotte, Oak Island',
        seller_hook: 'Leland\'s Wilmington-overflow demand and Brunswick Forest community drive rapid appreciation — let top Brunswick County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Leland\'s new-construction pipeline and Wilmington commuter demand create one of coastal NC\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'surf-city',
        name: 'Surf City',
        county: 'Pender',
        state: 'NC',
        zip: '28445',
        population: '3000',
        median_price: '$520,000',
        price_trend: 'up 7%',
        avg_dom: 38,
        description: 'Surf City is the crown jewel of Topsail Island — a beloved barrier island community between Wilmington and Jacksonville where Topsail Sound, uncrowded Atlantic beaches, and a classic North Carolina beach town character attract second-home buyers, retirees, and vacation rental investors seeking coastal North Carolina at a more accessible price point than the Outer Banks.',
        neighborhoods: 'North Topsail Beach vicinity, Topsail Beach vicinity, Sloop Point, Hampstead shoreline, Hunt Club',
        nearby: 'Topsail Beach, North Topsail Beach, Jacksonville NC, Wilmington, Hampstead',
        seller_hook: 'Surf City\'s Topsail Island scarcity and coastal lifestyle consistently attract second-home premium buyers — let top Pender County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Surf City\'s vacation rental income potential and coastal scarcity attract investment-minded buyers — RealtorFinder connects you with motivated sellers on Topsail Island.',
    },
    {
        slug: 'high-point',
        name: 'High Point',
        county: 'Guilford',
        state: 'NC',
        zip: '27260',
        population: '112000',
        median_price: '$280,000',
        price_trend: 'up 6%',
        avg_dom: 32,
        description: 'High Point is the Furniture Capital of the World — a Guilford County city that hosts the biannual High Point Market, the world\'s largest home furnishings trade show, and maintains a diverse economy anchored by Truist Financial services, manufacturing, and healthcare, offering buyers Triad access with price points well below Greensboro and Winston-Salem.',
        neighborhoods: 'Emerywood, Country Club, North Elm corridor, Deep River area, Oak Hollow, Westchester',
        nearby: 'Greensboro, Winston-Salem, Thomasville, Archdale, Kernersville',
        seller_hook: 'High Point\'s Furniture Market international profile and Triad affordability attract buyers from across the region — let competing Guilford County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'High Point\'s Furniture Market economy and affordability create a steady buyer pipeline — RealtorFinder connects you with motivated sellers in this Triad hub.',
    },
    {
        slug: 'greensboro',
        name: 'Greensboro',
        county: 'Guilford',
        state: 'NC',
        zip: '27401',
        population: '299000',
        median_price: '$320,000',
        price_trend: 'up 7%',
        avg_dom: 29,
        description: 'Greensboro is the Triad\'s largest city and an emerging technology hub — home to Honda Aircraft Company\'s world headquarters and a growing advanced manufacturing sector that is attracting a new generation of buyers who see Greensboro\'s affordability and improving job market as an opportunity ahead of the broader real estate market.',
        neighborhoods: 'Fisher Park, Westerwood, Sunset Hills, Hamilton Lakes, Guilford Hills, Lindley Park',
        nearby: 'High Point, Winston-Salem, Burlington, Kernersville, Gibsonville',
        seller_hook: 'Greensboro\'s tech and manufacturing growth drives consistent buyer demand — RealtorFinder puts competitive Guilford County agents in a race to represent your home.',
        realtor_hook: 'Greensboro\'s affordable prices and growing Honda/tech economy create a compelling buyer profile — RealtorFinder connects you with motivated sellers in the Triad.',
    },
    {
        slug: 'winston-salem',
        name: 'Winston-Salem',
        county: 'Forsyth',
        state: 'NC',
        zip: '27101',
        population: '249000',
        median_price: '$295,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Winston-Salem is the Triad\'s arts and innovation city — a former tobacco hub that has reinvented itself around Wake Forest Innovation Quarter, Forsyth Medical Center, and a thriving arts scene that has put it on national best-places lists while keeping home prices well below comparable Southeast markets.',
        neighborhoods: 'West End Historic District, Ardmore, Buena Vista, Reynolda Village, Robinhood Road, University Parkway',
        nearby: 'Kernersville, Clemmons, High Point, Greensboro, Lewisville',
        seller_hook: 'Winston-Salem\'s arts and innovation appeal is driving appreciation — let competing Forsyth County realtors on RealtorFinder earn the right to sell your home.',
        realtor_hook: 'Winston-Salem\'s Wake Forest Innovation Quarter and affordable prices attract buyers priced out of Raleigh and Charlotte — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'kernersville',
        name: 'Kernersville',
        county: 'Forsyth',
        state: 'NC',
        zip: '27284',
        population: '25000',
        median_price: '$320,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'Kernersville is the geographic heart of the Triad — a strategically positioned Forsyth County town equidistant between Greensboro, Winston-Salem, and High Point where Brookberry Farm and Kemersville Manor communities attract buyers seeking affordability, a beloved small-town character with festivals and a walkable Main Street, and three-city access from a single convenient location.',
        neighborhoods: 'Brookberry Farm, Kernersville Manor, Dobson Branch, Harmon Cove, Salem Glen',
        nearby: 'Winston-Salem, Greensboro, High Point, Walkertown, Summerfield',
        seller_hook: 'Kernersville\'s Triad crossroads position and small-town appeal attract buyers from all three major metros — let competing Forsyth County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Kernersville\'s central Triad location and affordability attract practical buyers seeking all three cities\' employment — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'asheville',
        name: 'Asheville',
        county: 'Buncombe',
        state: 'NC',
        zip: '28801',
        population: '93000',
        median_price: '$550,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Asheville is Western North Carolina\'s cultural capital and one of America\'s most celebrated destinations — a vibrant mountain city where the River Arts District\'s working studios, Biltmore Estate, a nationally recognized craft brewery scene, and Blue Ridge Parkway access attract remote workers, retirees, and in-migrants from major metros willing to pay North Carolina\'s highest mountain-market premiums.',
        neighborhoods: 'River Arts District, West Asheville, Montford Historic District, North Asheville, Kenilworth, Grove Park',
        nearby: 'Hendersonville, Weaverville, Black Mountain, Brevard, Waynesville',
        seller_hook: 'Asheville\'s national cultural profile and Biltmore cachet drive buyer demand from coastal metros — let top Buncombe County realtors on RealtorFinder compete for your listing.',
        realtor_hook: 'Asheville\'s River Arts District and Biltmore Estate attract motivated buyers willing to pay mountain premiums — RealtorFinder connects you with sellers in this highly competitive market.',
    },
    {
        slug: 'hendersonville-nc',
        name: 'Hendersonville',
        county: 'Henderson',
        state: 'NC',
        zip: '28792',
        population: '14000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 32,
        description: 'Hendersonville is Western North Carolina\'s most livable small city — an exceptionally charming Henderson County seat with one of the Southeast\'s most walkable historic Main Streets, apple orchard farmlands on the urban edge, and a climate cooled by its 2,100-foot elevation that draws Asheville-overflow buyers and retirees seeking mountain character at more accessible prices.',
        neighborhoods: 'Historic Downtown Hendersonville, Laurel Park, Etowah, Fletcher, Clear Creek, Dana Road area',
        nearby: 'Asheville, Brevard, Flat Rock, Fletcher, Mills River',
        seller_hook: 'Hendersonville\'s beloved Main Street and Asheville-overflow demand drive strong Henderson County appreciation — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Hendersonville\'s mountain charm and affordability relative to Asheville attract buyers seeking WNC living at value — RealtorFinder connects you with motivated sellers.',
    },
];
