// cities/nc.js — North Carolina city data for SEO landing pages

module.exports = [
    {
        slug: 'charlotte',
        name: 'Charlotte',
        county: 'Mecklenburg',
        state: 'NC',
        zip: '28201',
        population: '874,000',
        median_price: '$379,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Charlotte is the financial capital of the Southeast and one of America\'s fastest-growing large cities — home to Bank of America and a major Wells Fargo hub, with neighborhoods from NoDa\'s arts district to Myers Park\'s historic estates and the emerging South End corridor drawing buyers from across the country.',
        neighborhoods: 'NoDa, South End, Plaza Midwood, Myers Park, Dilworth, Elizabeth, Ballantyne, SouthPark',
        nearby: 'Huntersville, Concord, Gastonia, Rock Hill SC, Belmont',
        seller_hook: 'Charlotte\'s banking industry migration and population growth drive fierce buyer competition — let top Mecklenburg County realtors compete on RealtorFinder to earn your listing.',
        realtor_hook: 'Charlotte\'s Fortune 500 economy and rapid growth make it one of the Southeast\'s strongest listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'raleigh',
        name: 'Raleigh',
        county: 'Wake',
        state: 'NC',
        zip: '27601',
        population: '467,000',
        median_price: '$419,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Raleigh is the capital of North Carolina and the center of the Research Triangle — a booming tech and pharmaceutical hub where Apple, Google, and Wolfspeed have announced major operations, creating a buyer pool of well-compensated professionals driving some of the Southeast\'s strongest home appreciation.',
        neighborhoods: 'Five Points, Oakwood, North Hills, Brier Creek, Cameron Village, Mordecai, Glenwood South',
        nearby: 'Durham, Cary, Chapel Hill, Garner, Wake Forest',
        seller_hook: 'Raleigh\'s tech sector expansion is driving premium buyer demand — let competing Wake County realtors on RealtorFinder fight to earn the right to represent your home.',
        realtor_hook: 'Raleigh\'s Research Triangle tech economy creates high-earning buyer demand that keeps listing prices strong — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'greensboro',
        name: 'Greensboro',
        county: 'Guilford',
        state: 'NC',
        zip: '27401',
        population: '299,000',
        median_price: '$279,000',
        price_trend: 'up 7%',
        avg_dom: 29,
        description: 'Greensboro is the Triad\'s largest city and an emerging technology hub — home to Honda Aircraft Company\'s world headquarters and a growing advanced manufacturing sector that is attracting a new generation of buyers who see Greensboro\'s affordability and improving job market as an opportunity ahead of the broader real estate market.',
        neighborhoods: 'Fisher Park, Westerwood, Sunset Hills, Hamilton Lakes, Guilford Hills, Lindley Park',
        nearby: 'High Point, Winston-Salem, Burlington, Kernersville, Gibsonville',
        seller_hook: 'Greensboro\'s tech and manufacturing growth drives consistent buyer demand — RealtorFinder puts competitive Guilford County agents in a race to represent your home.',
        realtor_hook: 'Greensboro\'s affordable prices and growing Honda/tech economy create a compelling buyer profile — RealtorFinder connects you with motivated sellers in the Triad.',
    },
    {
        slug: 'durham',
        name: 'Durham',
        county: 'Durham',
        state: 'NC',
        zip: '27701',
        population: '283,000',
        median_price: '$399,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Durham is the Bull City — a vibrant, progressive Research Triangle city where Duke University and Duke Health anchor an intellectual and medical economy that draws buyers from across the country, and where neighborhoods like Walltown, Trinity Park, and East Durham are experiencing rapid appreciation driven by a growing national profile.',
        neighborhoods: 'Trinity Park, Watts-Hillandale, East Durham, Northgate Park, Walltown, Old West Durham, Forest Hills',
        nearby: 'Chapel Hill, Raleigh, Cary, Hillsborough, Mebane',
        seller_hook: 'Durham\'s Duke-driven economy and rising national profile drive strong buyer demand — let competing Triangle realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Durham\'s Duke University economy and growing Bull City identity attract motivated buyers — RealtorFinder connects you with sellers in one of the Triangle\'s hottest markets.',
    },
    {
        slug: 'winston-salem',
        name: 'Winston-Salem',
        county: 'Forsyth',
        state: 'NC',
        zip: '27101',
        population: '249,000',
        median_price: '$259,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Winston-Salem is the Triad\'s arts and innovation city — a former tobacco hub that has reinvented itself around Wake Forest Innovation Quarter, Forsyth Medical Center, and a thriving arts scene that has put it on national best-places lists while keeping home prices well below comparable Southeast markets.',
        neighborhoods: 'West End Historic District, Ardmore, Buena Vista, Reynolda Village, Robinhood Road, University Parkway',
        nearby: 'Kernersville, Clemmons, High Point, Greensboro, Lewisville',
        seller_hook: 'Winston-Salem\'s arts and innovation appeal is driving appreciation — let competing Forsyth County realtors on RealtorFinder earn the right to sell your home.',
        realtor_hook: 'Winston-Salem\'s Wake Forest Innovation Quarter and affordable prices attract buyers priced out of Raleigh and Charlotte — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'fayetteville-nc',
        name: 'Fayetteville',
        county: 'Cumberland',
        state: 'NC',
        zip: '28301',
        population: '208,000',
        median_price: '$199,000',
        price_trend: 'up 7%',
        avg_dom: 31,
        description: 'Fayetteville is home to Fort Liberty (formerly Fort Bragg) — the largest military installation in the world by population — creating a massive, rotating pool of military buyers and sellers that keeps the housing market active throughout the year and provides affordability that draws first-time buyers from across the region.',
        neighborhoods: 'Haymount, Cross Creek Mall area, Vanstory Hills, Arlington, Hope Mills border',
        nearby: 'Hope Mills, Spring Lake, Lumberton, Sanford, Dunn',
        seller_hook: 'Fayetteville\'s Fort Liberty military community creates consistent year-round demand — let competitive Cumberland County realtors on RealtorFinder represent your home.',
        realtor_hook: 'Fayetteville\'s large military base ensures a steady pipeline of motivated buyers and sellers — RealtorFinder keeps you connected to this consistent market.',
    },
    {
        slug: 'cary',
        name: 'Cary',
        county: 'Wake',
        state: 'NC',
        zip: '27511',
        population: '174,000',
        median_price: '$529,000',
        price_trend: 'up 6%',
        avg_dom: 23,
        description: 'Cary is the premier suburb of the Research Triangle — a master-planned, exceptionally well-managed town with top-ranked schools, SAS Institute headquarters, and a reputation for safety and livability that has earned it perennial recognition on national best-places-to-live lists and strong demand from tech-industry relocatees.',
        neighborhoods: 'West Cary, MacGregor Downs, Preston, Lochmere, Cary Park, Regency, Oaks',
        nearby: 'Raleigh, Apex, Morrisville, Durham, Research Triangle Park',
        seller_hook: 'Cary\'s top-school reputation and SAS corporate presence drive premium buyer demand — let competing Wake County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Cary\'s elite school ratings and tech-company proximity create a premium listing market with highly qualified buyers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'wilmington-nc',
        name: 'Wilmington',
        county: 'New Hanover',
        state: 'NC',
        zip: '28401',
        population: '119,000',
        median_price: '$389,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Wilmington is North Carolina\'s premier coastal city — a historic port town with a charming riverfront district, direct access to Wrightsville Beach and Carolina Beach, a booming film industry, and a real estate market that draws retirees, remote workers, and beach-lifestyle buyers from across the East Coast.',
        neighborhoods: 'Historic District, Midtown, Oleander Drive corridor, Landfall, Carolina Beach access, Wrightsville Beach access',
        nearby: 'Leland, Hampstead, Carolina Beach, Wrightsville Beach, Surf City',
        seller_hook: 'Wilmington\'s beach access and coastal lifestyle draw buyers from across the East Coast — let top Cape Fear realtors compete on RealtorFinder to maximize your sale.',
        realtor_hook: 'Wilmington\'s coastal appeal and growing film economy attract buyers from across the region — RealtorFinder connects you with motivated sellers in this Cape Fear market.',
    },
];
