// cities/nd.js — North Dakota city data for SEO landing pages

module.exports = [
    {
        slug: 'fargo',
        name: 'Fargo',
        county: 'Cass',
        state: 'ND',
        zip: '58102',
        population: '126,000',
        median_price: '$285,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Fargo is North Dakota\'s largest city and a Midwestern tech and healthcare hub on the Red River — home to North Dakota State University, Microsoft and Amazon operations, and a surprisingly vibrant downtown Broadway arts scene that has made it one of the Great Plains\' most livable metros, attracting young professionals and families seeking Big Ten college-town energy with some of the upper Midwest\'s most affordable home prices.',
        neighborhoods: 'Island Park, Hawthorne, South Fargo, West Fargo, Moorhead MN',
        nearby: 'West Fargo, Moorhead MN, Dilworth MN, Casselton, Horace',
        seller_hook: 'Fargo\'s tech sector and NDSU enrollment create strong buyer demand in a tight market — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Fargo\'s growing tech economy and university market generate active listing conditions — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'bismarck-nd',
        name: 'Bismarck',
        county: 'Burleigh',
        state: 'ND',
        zip: '58501',
        population: '74,000',
        median_price: '$295,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Bismarck is North Dakota\'s state capital and Missouri River city — a government and energy hub where state agencies, Sanford Health, and the Bakken Oil Boom\'s administrative center create housing demand from government workers, medical professionals, and energy industry management who find some of the upper Midwest\'s most affordable new construction and ranch-style homes on the northern Great Plains.',
        neighborhoods: 'South Bismarck, North Bismarck, Mandan, Lincoln, Wilton',
        nearby: 'Mandan, Lincoln, Washburn, Beulah, Hazen',
        seller_hook: 'Bismarck\'s state capital stability and energy sector drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Bismarck\'s government and oil industry create steady listing activity as North Dakota\'s capital city — find sellers through RealtorFinder.',
    },
    {
        slug: 'grand-forks-nd',
        name: 'Grand Forks',
        county: 'Grand Forks',
        state: 'ND',
        zip: '58201',
        population: '57,000',
        median_price: '$245,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Grand Forks is home to the University of North Dakota and the northern gateway of the Red River Valley — a Fighting Hawks college city where UND\'s aviation and medical programs, Grand Forks Air Force Base, and an agricultural services economy create housing demand from students, airmen, and farm families seeking affordable college-town living with reliable employment from the university and military installations.',
        neighborhoods: 'University Park, Near Southside, Reeves Drive, East Grand Forks MN, Emerado',
        nearby: 'East Grand Forks MN, Larimore, Thompson, Manvel, Emerado',
        seller_hook: 'Grand Forks\' UND enrollment and Air Force Base drive reliable buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Grand Forks\' university and military market create steady listing activity in the Red River Valley — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'minot-nd',
        name: 'Minot',
        county: 'Ward',
        state: 'ND',
        zip: '58701',
        population: '48,000',
        median_price: '$255,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Minot is the Magic City of North Dakota and home to Minot Air Force Base — a northern plains city where the ICBM wing and B-52 operations, Minot State University, and a booming agricultural services sector create consistent military housing demand, with VA loans funding a significant share of home purchases among active-duty and veteran families who value the quiet Great Plains lifestyle and low North Dakota taxes.',
        neighborhoods: 'North Hill, South Hill, Souris Valley, Burlington, Velva',
        nearby: 'Burlington, Velva, Surrey, Carpio, Stanley',
        seller_hook: 'Minot\'s Air Force Base community drives year-round military buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Minot\'s military VA buyer pool and Bakken proximity create consistent listing activity — find sellers through RealtorFinder.',
    },
];
