// cities/ne.js — Nebraska city data for SEO landing pages

module.exports = [
    {
        slug: 'omaha',
        name: 'Omaha',
        county: 'Douglas',
        state: 'NE',
        zip: '68102',
        population: '486,000',
        median_price: '$270,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Omaha is Nebraska\'s largest city and a Midwest economic powerhouse — the headquarters of Warren Buffett\'s Berkshire Hathaway, Mutual of Omaha, and Union Pacific Railroad, with a thriving Old Market entertainment district, a nationally acclaimed zoo, and housing values that consistently rank among the nation\'s best for cost-adjusted quality of life, drawing remote workers and corporate transferees from both coasts.',
        neighborhoods: 'Old Market, Dundee, Benson, Aksarben, Midtown, West Omaha, Millard, Papillion',
        nearby: 'Bellevue, Papillion, La Vista, Ralston, Council Bluffs IA',
        seller_hook: 'Omaha\'s Fortune 500 employer base and Midwest value reputation drive strong buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Omaha\'s corporate headquarters market and consistent appreciation create high-volume listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'lincoln-ne',
        name: 'Lincoln',
        county: 'Lancaster',
        state: 'NE',
        zip: '68501',
        population: '295,000',
        median_price: '$255,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Lincoln is Nebraska\'s state capital and home to the University of Nebraska — a Big Ten college city where Husker football passion, a booming tech and insurance sector, and one of the Midwest\'s most walkable downtowns create strong housing demand from students, government workers, and young professionals seeking college-town energy with big-city amenities at affordable prices.',
        neighborhoods: 'Near South, University Place, Haymarket, Highlands, Williamsburg, Southeast Lincoln',
        nearby: 'Waverly, Hickman, Seward, Milford, Beatrice',
        seller_hook: 'Lincoln\'s university enrollment and state capital stability create a reliable buyer pool — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Lincoln\'s UNL market and government employment drive consistent listing activity across all price ranges — find sellers through RealtorFinder.',
    },
    {
        slug: 'bellevue-ne',
        name: 'Bellevue',
        county: 'Sarpy',
        state: 'NE',
        zip: '68005',
        population: '65,000',
        median_price: '$245,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Bellevue is Omaha\'s largest suburb and home to Offutt Air Force Base — Nebraska\'s most populous Sarpy County community where Bellevue University, STRATCOM military housing demand, and a growing Omaha spillover market attract active-duty families, veterans, and commuters seeking top-rated Papillion-La Vista and Bellevue school districts south of the metro.',
        neighborhoods: 'Old Towne, Bellevue Heights, Lied Activity Center, Haworth Park, Fontenelle Hills',
        nearby: 'Papillion, La Vista, Omaha, Springfield, Plattsmouth',
        seller_hook: 'Bellevue\'s Offutt AFB community and Omaha proximity drive strong, consistent buyer activity — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Bellevue\'s military buyer pool and Sarpy County growth create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'grand-island-ne',
        name: 'Grand Island',
        county: 'Hall',
        state: 'NE',
        zip: '68801',
        population: '53,000',
        median_price: '$185,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Grand Island is central Nebraska\'s largest city and a beef processing powerhouse — a diverse immigrant community on the Platte River where JBS and Tyson food processing plants, Central Community College, and a growing manufacturing base create demand for affordable housing among first-generation buyers, young families, and agricultural workers seeking homeownership at Nebraska\'s lowest price points.',
        neighborhoods: 'North End, Pier Park, Fonner Park, Stuhr Road, Wood River',
        nearby: 'Hastings, Kearney, Aurora, Giltner, Central City',
        seller_hook: 'Grand Island\'s food processing economy and diverse buyer pool drive year-round housing demand — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Grand Island\'s affordable market and diverse workforce create consistent listing volume — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'kearney-ne',
        name: 'Kearney',
        county: 'Buffalo',
        state: 'NE',
        zip: '68845',
        population: '34,000',
        median_price: '$210,000',
        price_trend: 'up 4%',
        avg_dom: 32,
        description: 'Kearney is Nebraska\'s fifth-largest city and home to the University of Nebraska at Kearney — a Great Plains regional hub on I-80 where UNK\'s 6,500 students, a growing healthcare corridor, and proximity to the Sandhills sandhill crane migration attract students, medical workers, and outdoor-minded buyers seeking affordable central Nebraska living.',
        neighborhoods: 'University Heights, South Kearney, Kearney Estates, Sunrise, Meadowbrook',
        nearby: 'Lexington, Hastings, Grand Island, Holdrege, Minden',
        seller_hook: 'Kearney\'s university market and I-80 corridor create steady buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Kearney\'s UNK enrollment and regional healthcare economy drive consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'fremont-ne',
        name: 'Fremont',
        county: 'Dodge',
        state: 'NE',
        zip: '68025',
        population: '27,000',
        median_price: '$195,000',
        price_trend: 'up 4%',
        avg_dom: 34,
        description: 'Fremont is Dodge County\'s seat and a growing Omaha suburb 35 miles northwest of the metro — a manufacturing and agricultural hub where Hormel Foods processing, Midland University, and affordable housing in a tight-knit community attract first-time buyers and young families seeking Omaha metro access at prices well below Douglas County averages.',
        neighborhoods: 'Downtown Fremont, North Fremont, Valley, Ames, North Bend',
        nearby: 'Omaha, Blair, Wahoo, West Point, Schuyler',
        seller_hook: 'Fremont\'s Omaha proximity and affordable market attract buyers seeking metro access without metro prices — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Fremont\'s Omaha suburb appeal and manufacturing base create reliable listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'north-platte',
        name: 'North Platte',
        county: 'Lincoln',
        state: 'NE',
        zip: '69101',
        population: '24,000',
        median_price: '$160,000',
        price_trend: 'up 3%',
        avg_dom: 45,
        description: 'North Platte is western Nebraska\'s largest city and the railroad hub of the Great Plains — home to Union Pacific\'s massive Bailey Yard, the world\'s largest railroad classification yard, where railroad workers, medical professionals, and agricultural families find some of the region\'s most affordable single-family homes with strong rental yield potential.',
        neighborhoods: 'East Platte, Westfield, Cody Park, Maloney Lake, Sutherland',
        nearby: 'Ogallala, Kearney, McCook, Imperial, Lexington',
        seller_hook: 'North Platte\'s Union Pacific railroad workforce and healthcare economy drive steady housing demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'North Platte\'s affordable prices and railroad employer base create consistent listing opportunities — connect with sellers through RealtorFinder.',
    },
];
