// cities/nh-extra.js — Additional New Hampshire city data for SEO landing pages

module.exports = [
    {
        slug: 'hanover-nh',
        name: 'Hanover',
        county: 'Grafton',
        state: 'NH',
        zip: '03755',
        population: '12,000',
        median_price: '$670,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Hanover is home to Dartmouth College and the Upper Connecticut River Valley\'s crown jewel — an Ivy League college town on the New Hampshire-Vermont border where Dartmouth\'s faculty, medical professionals at Dartmouth Health, and a deeply intellectual community create fierce competition for limited inventory in a market that commands some of northern New England\'s highest prices per square foot.',
        neighborhoods: 'Hanover Center, Lebanon, Norwich VT, Lyme, Etna',
        nearby: 'Lebanon, Norwich VT, Lyme, Enfield, Canaan',
        seller_hook: 'Hanover\'s Dartmouth Ivy League prestige and Upper Valley scarcity create exceptional seller conditions — let top agents compete on RealtorFinder.',
        realtor_hook: 'Hanover\'s Dartmouth buyer pool and limited inventory make every listing a premium opportunity — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'lebanon-nh',
        name: 'Lebanon',
        county: 'Grafton',
        state: 'NH',
        zip: '03766',
        population: '14,000',
        median_price: '$430,000',
        price_trend: 'up 6%',
        avg_dom: 20,
        description: 'Lebanon is the Upper Valley\'s commercial hub and New Hampshire\'s western gateway — a Dartmouth-Hitchcock Medical Center community where the region\'s largest employer, a thriving Colburn Park downtown, and I-89 access to both Concord and Burlington create housing demand from medical workers, Dartmouth affiliates, and Vermont border buyers who want New Hampshire\'s tax advantages with Upper Valley amenities.',
        neighborhoods: 'West Lebanon, North Lebanon, Wilder VT, White River Junction VT, Enfield',
        nearby: 'Hanover, Enfield, Hartland VT, White River Junction VT, Claremont',
        seller_hook: 'Lebanon\'s Dartmouth-Hitchcock and Upper Valley location create consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Lebanon\'s medical center and NH tax advantage generate active listing conditions in the Upper Valley — find sellers through RealtorFinder.',
    },
    {
        slug: 'wolfeboro',
        name: 'Wolfeboro',
        county: 'Carroll',
        state: 'NH',
        zip: '03894',
        population: '7,000',
        median_price: '$520,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Wolfeboro is the Oldest Summer Resort in America on the eastern shore of Lake Winnipesaukee — a Carroll County village where waterfront estates, a pristine Main Street, and one of New England\'s most spectacular lake settings create a seasonal and second-home market dominated by Massachusetts and Connecticut buyers seeking New Hampshire\'s tax-free lakefront living in a community that has attracted summer residents since the 1760s.',
        neighborhoods: 'Lake Winnipesaukee, Crescent Lake, Back Bay, Pine Hill, Mirror Lake',
        nearby: 'Alton, Ossipee, Wakefield, Moultonborough, Tuftonboro',
        seller_hook: 'Wolfeboro\'s Lake Winnipesaukee waterfront and resort heritage command premium prices — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Wolfeboro\'s second-home market and out-of-state buyer demand create high-value listing opportunities — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'meredith-nh',
        name: 'Meredith',
        county: 'Belknap',
        state: 'NH',
        zip: '03253',
        population: '7,000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Meredith is the Lakes Region\'s year-round hub on Lake Winnipesaukee\'s western shore — a community where Mills Falls Marketplace, Meredith Neck peninsula waterfront, and snowmobile and boat access to New Hampshire\'s largest lake attract buyers from Greater Boston and southern NH seeking lake lifestyle properties at prices that still undercut comparable waterfront real estate in Massachusetts.',
        neighborhoods: 'Center Harbor, Meredith Neck, Waukewan, Lake Waukewan, Plymouth Road',
        nearby: 'Laconia, Center Harbor, New Hampton, Gilford, Belmont',
        seller_hook: 'Meredith\'s Lake Winnipesaukee access and year-round amenities attract strong vacation and primary home buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Meredith\'s Lakes Region appeal and Boston spillover market create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'claremont-nh',
        name: 'Claremont',
        county: 'Sullivan',
        state: 'NH',
        zip: '03743',
        population: '13,000',
        median_price: '$235,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Claremont is Sullivan County\'s largest city and one of New Hampshire\'s most affordable urban communities — a Connecticut River mill city opposite Springfield, Vermont, where manufacturing, cold-water fly fishing on the Sugar River, and some of the state\'s lowest home prices attract first-time buyers, investors, and remote workers who want genuine New Hampshire affordability with upper valley access.',
        neighborhoods: 'Newport, Sunapee, Charlestown, Cornish, Unity',
        nearby: 'Newport, Charlestown, Cornish, Windsor VT, Springfield VT',
        seller_hook: 'Claremont\'s Connecticut River Valley affordability and remote worker appeal create consistent buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Claremont\'s value pricing and Sullivan County growth create active listing conditions in western New Hampshire — find sellers through RealtorFinder.',
    },
    {
        slug: 'jaffrey',
        name: 'Jaffrey',
        county: 'Cheshire',
        state: 'NH',
        zip: '03452',
        population: '5,500',
        median_price: '$285,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Jaffrey is the Monadnock Region\'s most charming village and the base camp for Mount Monadnock, the world\'s second most climbed mountain — a southern New Hampshire community where Thorndike Pond, Crotched Mountain ski area, and one of New England\'s most beloved hiking mountains create year-round demand from remote workers, Boston weekenders, and families seeking authentic small-town New Hampshire life at prices well below the seacoast.',
        neighborhoods: 'East Jaffrey, Peterborough, New Ipswich, Rindge, Fitzwilliam',
        nearby: 'Peterborough, Keene, Greenfield, Temple, New Ipswich',
        seller_hook: 'Jaffrey\'s Mount Monadnock access and village charm attract remote workers and weekend buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Jaffrey\'s Monadnock Region appeal and Boston proximity generate active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'north-hampton',
        name: 'North Hampton',
        county: 'Rockingham',
        state: 'NH',
        zip: '03862',
        population: '4,500',
        median_price: '$720,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'North Hampton is New Hampshire\'s most exclusive seacoast town — a small Rockingham County community where Atlantic Ocean frontage, a pristine Hampton Falls watershed, and top-tier Winnacunnet High School access create one of northern New England\'s highest-priced residential markets, with oceanfront estates and sea-view colonials attracting Massachusetts equity buyers and Boston executives seeking New Hampshire\'s zero income tax with genuine coastal lifestyle.',
        neighborhoods: 'Little Boar\'s Head, Plaice Cove, Hampton Falls, Rye border',
        nearby: 'Rye, Hampton, Exeter, Greenland, Seabrook',
        seller_hook: 'North Hampton\'s oceanfront scarcity and NH tax advantages create exceptional seller conditions — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'North Hampton\'s luxury seacoast market and Massachusetts buyer demand create high-value listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'franklin-nh',
        name: 'Franklin',
        county: 'Merrimack',
        state: 'NH',
        zip: '03235',
        population: '9,000',
        median_price: '$270,000',
        price_trend: 'up 7%',
        avg_dom: 19,
        description: 'Franklin is New Hampshire\'s most affordable city and an emerging value market on the Winnipesaukee River — a central New Hampshire community at the confluence of the Pemigewasset and Winnipesaukee rivers where manufacturing heritage, affordable colonial and ranch homes, and proximity to both Concord and the Lakes Region attract first-time buyers and remote workers discovering genuine New Hampshire homeownership at some of the state\'s lowest price points.',
        neighborhoods: 'Sanbornton, Hill, Tilton, Northfield, Webster',
        nearby: 'Tilton, Northfield, Sanbornton, Concord, Laconia',
        seller_hook: 'Franklin\'s affordable prices and central NH location attract first-time buyers and remote workers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Franklin\'s value market and Lakes Region proximity generate active listing conditions — find sellers through RealtorFinder.',
    },
];
