module.exports = [
    // ── Southern NH (Boston commuter belt) ───────────────────────────────
    {
        slug: 'manchester',
        name: 'Manchester',
        county: 'Hillsborough',
        state: 'NH',
        zip: '03101',
        population: '115,000',
        median_price: '$319,000',
        price_trend: 'up 13%',
        avg_dom: 17,
        description: 'Manchester is New Hampshire\'s largest city and the economic engine of the Merrimack Valley, offering urban amenities, a revitalized Millyard arts and tech district, and prices that look extraordinary to buyers fleeing Boston\'s metro costs — all without a state income tax. At 13% annual appreciation and a 17-day average market time, it is one of the most dynamic housing markets in all of New England.',
        neighborhoods: 'Beech Hill, West Side, Rimmon Heights, North End, Millyard Arts District, Elm Street',
        nearby: 'Bedford, Goffstown, Hooksett, Londonderry',
        seller_hook: 'Manchester\'s 13% appreciation and status as New Hampshire\'s largest city mean sellers are seeing Boston-caliber demand without Boston-caliber inventory — act now before competition increases.',
        realtor_hook: 'Manchester\'s combination of New Hampshire\'s no-income-tax advantage, fast appreciation, and Boston-commuter demand makes it one of New England\'s highest-velocity markets for agents who move quickly.',
    },
    {
        slug: 'nashua',
        name: 'Nashua',
        county: 'Hillsborough',
        state: 'NH',
        zip: '03060',
        population: '92,000',
        median_price: '$379,000',
        price_trend: 'up 11%',
        avg_dom: 17,
        description: 'Nashua sits at New Hampshire\'s southern border, just 45 miles from Boston, making it the ultimate no-income-tax alternative for Massachusetts commuters who want to stretch their housing dollar without sacrificing urban amenities. Its Mine Falls Park, thriving downtown, and diverse employment base anchored by BAE Systems and Nashua Corporation have made it one of the most consistently ranked livable cities in the country.',
        neighborhoods: 'Downtown Nashua, Crown Hill, Mine Falls, Millpond, Birchwood',
        nearby: 'Hudson, Merrimack, Hollis, Milford-nh',
        seller_hook: 'Nashua\'s status as New Hampshire\'s premier Boston alternative means your home is visible to tens of thousands of Massachusetts buyers actively seeking the no-income-tax advantage — demand is structural, not cyclical.',
        realtor_hook: 'Nashua\'s location on the Massachusetts border and no-income-tax draw create a perpetual pipeline of motivated Boston-area buyers, making it one of southern NH\'s most reliable markets for high transaction volume.',
    },
    {
        slug: 'bedford',
        name: 'Bedford',
        county: 'Hillsborough',
        state: 'NH',
        zip: '03110',
        population: '23,500',
        median_price: '$519,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Bedford is consistently ranked among New Hampshire\'s most desirable communities, offering top-tier public schools, upscale suburban neighborhoods, and Manchester-Boston Airport accessibility in a package that has made it the preferred address for the state\'s business and professional class. Its relatively restrained appreciation reflects a market that never gets too hot — just steady, reliable value growth.',
        neighborhoods: 'Bedford Center, Ministerial Road area, New Boston Road, Ridgewood',
        nearby: 'Manchester, Goffstown, Amherst-nh, New Boston',
        seller_hook: 'Bedford\'s top-ranked schools and executive-suburb reputation command a consistent price premium — sellers benefit from a buyer pool dominated by well-qualified professionals who know exactly what Bedford addresses are worth.',
        realtor_hook: 'Bedford\'s affluent, well-qualified buyer base and stable appreciation make it a low-stress, high-reward market for agents who specialize in move-up and executive relocation transactions.',
    },
    {
        slug: 'derry',
        name: 'Derry',
        county: 'Rockingham',
        state: 'NH',
        zip: '03038',
        population: '33,000',
        median_price: '$369,000',
        price_trend: 'up 11%',
        avg_dom: 18,
        description: 'Derry offers southern New Hampshire\'s combination of suburban affordability and Boston commuter convenience, with an 18-day average market time reflecting intense demand from Massachusetts buyers drawn by the no-income-tax advantage and access to both I-93 and the Everett Turnpike. Its colonial heritage, Pinkerton Academy, and growing commercial corridor give buyers both community character and practical amenities.',
        neighborhoods: 'Derry Village, East Derry, Pinkerton, Hood Road area',
        nearby: 'Londonderry, Salem-nh, Windham, Manchester',
        seller_hook: 'Derry\'s I-93 access and New Hampshire\'s no-income-tax advantage make your home visible to thousands of Massachusetts commuters ready to cross the border — sellers consistently see multiple offers here.',
        realtor_hook: 'Derry\'s position on the I-93 corridor makes it a magnet for Massachusetts buyers, giving agents a steady stream of motivated out-of-state clients eager to capture the no-income-tax benefit.',
    },
    {
        slug: 'londonderry',
        name: 'Londonderry',
        county: 'Rockingham',
        state: 'NH',
        zip: '03053',
        population: '26,000',
        median_price: '$419,000',
        price_trend: 'up 9%',
        avg_dom: 19,
        description: 'Londonderry combines Manchester-Boston Airport adjacency with highly regarded public schools and newer residential development that appeals to corporate relocators and Boston commuters seeking New Hampshire\'s tax advantages in a polished suburban package. Its apple orchard heritage and spacious lots differentiate it from more densely developed neighbors while keeping it firmly within the southern NH growth corridor.',
        neighborhoods: 'Londonderry Town Center, Harvey Road, Pillsbury Road area',
        nearby: 'Derry, Manchester, Bedford, Salem-nh',
        seller_hook: 'Londonderry\'s airport proximity and top schools create a dual-market advantage — sellers attract both corporate relocation buyers and Boston commuters seeking New Hampshire\'s no-income-tax benefit.',
        realtor_hook: 'Corporate relocations to the Manchester-Boston Airport corridor and steady Boston-commuter demand give Londonderry agents a reliable pipeline of well-qualified buyers throughout the year.',
    },
    {
        slug: 'salem-nh',
        name: 'Salem',
        county: 'Rockingham',
        state: 'NH',
        zip: '03079',
        population: '30,000',
        median_price: '$389,000',
        price_trend: 'up 10%',
        avg_dom: 18,
        description: 'Salem sits directly on the Massachusetts border, making it the shortest possible commute for buyers seeking New Hampshire\'s no-income-tax advantage — a positioning that drives extraordinary demand from Lawrence, Haverhill, and Methuen buyers who can save thousands annually simply by crossing the state line. The Rockingham Park development corridor and proximity to I-93 and I-495 give Salem strong commercial and residential fundamentals.',
        neighborhoods: 'Salem Center, Pelham Road area, Brookside, Policy Street',
        nearby: 'Derry, Windham, Pelham, Methuen MA',
        seller_hook: 'Salem\'s position literally on the Massachusetts border means your home is the first option for tens of thousands of Bay State buyers ready to capture New Hampshire\'s no-income-tax savings — demand here is unmatched.',
        realtor_hook: 'Salem\'s border location creates a constant cross-state buyer flow that is unlike anywhere else in New Hampshire, giving agents access to the full depth of the Massachusetts buyer market.',
    },
    {
        slug: 'windham',
        name: 'Windham',
        county: 'Rockingham',
        state: 'NH',
        zip: '03087',
        population: '15,000',
        median_price: '$479,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Windham is one of southern New Hampshire\'s most sought-after bedroom communities, with consistently high-ranking schools, spacious wooded lots, Cobbetts Pond recreation, and a peaceful residential character that attracts high-earning Boston-area professionals seeking to maximize New Hampshire\'s no-income-tax savings. Its limited commercial development preserves the quiet suburban quality that keeps buyer demand reliably elevated.',
        neighborhoods: 'Windham Center, Cobbetts Pond, Windham Depot, Range Road',
        nearby: 'Salem-nh, Derry, Pelham, Londonderry',
        seller_hook: 'Windham\'s top-tier schools and no-income-tax advantage attract Boston professionals who have done the math — they\'re motivated, pre-qualified, and ready to pay a premium for what Windham delivers.',
        realtor_hook: 'Windham\'s premium positioning within the southern NH market attracts high-earning buyers who close quickly and rarely need hand-holding, making it an efficient and rewarding market for experienced agents.',
    },
    {
        slug: 'merrimack',
        name: 'Merrimack',
        county: 'Hillsborough',
        state: 'NH',
        zip: '03054',
        population: '26,000',
        median_price: '$389,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Merrimack straddles the F.E. Everett Turnpike between Manchester and Nashua, offering buyers a strategic location with excellent schools, the Budweiser brewery landmark, and new residential development that has made it one of the Hillsborough County corridor\'s fastest-growing communities. Baboosic Lake recreation and strong municipal services add lifestyle value that has consistently outperformed broader market appreciation.',
        neighborhoods: 'Merrimack Center, Thorntons Ferry, Baboosic Lake, Continental Boulevard',
        nearby: 'Nashua, Bedford, Amherst-nh, Milford-nh',
        seller_hook: 'Merrimack\'s turnpike-corridor location between Manchester and Nashua gives your home maximum buyer exposure — sellers benefit from a dual-market reach that smaller NH towns simply cannot offer.',
        realtor_hook: 'Merrimack\'s central position in the Hillsborough corridor and consistent buyer demand from both Manchester and Nashua commuters give agents a reliable, year-round transaction base.',
    },
    {
        slug: 'goffstown',
        name: 'Goffstown',
        county: 'Hillsborough',
        state: 'NH',
        zip: '03045',
        population: '18,000',
        median_price: '$339,000',
        price_trend: 'up 10%',
        avg_dom: 21,
        description: 'Goffstown offers Manchester-adjacent affordability with a distinct small-town character, anchored by Saint Anselm College and the scenic Piscataquog River corridor, attracting buyers who want New Hampshire\'s tax advantages, quick Manchester access, and more breathing room than the city proper provides. Glen Lake and the Pinardville neighborhood add recreational variety to a community undergoing genuine residential demand growth.',
        neighborhoods: 'Goffstown Village, Pinardville, Glen Lake, Grasmere',
        nearby: 'Manchester, Bedford, New Boston, Weare',
        seller_hook: 'Goffstown\'s value proposition versus Bedford and Manchester is resonating with first-time buyers and growing families — sellers are seeing demand that is outpacing the broader county.',
        realtor_hook: 'Goffstown\'s affordability relative to neighboring Bedford and its Manchester adjacency give agents a strong value narrative for first-time buyers and young families entering the southern NH market.',
    },
    {
        slug: 'amherst-nh',
        name: 'Amherst',
        county: 'Hillsborough',
        state: 'NH',
        zip: '03031',
        population: '12,000',
        median_price: '$519,000',
        price_trend: 'up 8%',
        avg_dom: 21,
        description: 'Amherst is one of southern New Hampshire\'s most prestigious rural-suburban communities, with a beautifully preserved Village Green, exceptional public schools, and estates set along scenic roads that appeal to buyers seeking a refined New England character alongside significant Boston-commuter tax savings. Its limited commercial development and strong sense of community identity sustain a premium that has held through multiple market cycles.',
        neighborhoods: 'Amherst Village, Ponemah, Baboosic Lake area, Mack Hill Road',
        nearby: 'Milford-nh, Merrimack, Bedford, Nashua',
        seller_hook: 'Amherst\'s prestigious Village Green address and top-ranked schools command the kind of premium that even Boston suburbs struggle to match — especially once buyers factor in New Hampshire\'s no-income-tax advantage.',
        realtor_hook: 'Amherst\'s discerning buyer base of senior executives and affluent professionals rewards agents who understand luxury positioning and can articulate the long-term financial case for NH homeownership.',
    },
    {
        slug: 'milford-nh',
        name: 'Milford',
        county: 'Hillsborough',
        state: 'NH',
        zip: '03055',
        population: '16,000',
        median_price: '$369,000',
        price_trend: 'up 10%',
        avg_dom: 21,
        description: 'Milford anchors the Souhegan Valley with a historic Oval town center, a vibrant community character, and prices that undercut larger neighboring communities while providing excellent schools and Souhegan River outdoor recreation. Buyers from Nashua and Manchester are increasingly discovering Milford as a value alternative with genuine character, driving consistent above-market appreciation.',
        neighborhoods: 'Milford Oval, Cabinet Street, Briar Hill, Union Street',
        nearby: 'Amherst-nh, Nashua, Merrimack, Wilton',
        seller_hook: 'Milford\'s Oval and community character are drawing buyers from pricier nearby towns who can\'t find this combination of value and charm anywhere else in Hillsborough County.',
        realtor_hook: 'Milford\'s reputation as a value alternative to Amherst and Bedford creates an active buyer market of informed purchasers who are ready to act — ideal for agents who appreciate an efficient close.',
    },
    {
        slug: 'hooksett',
        name: 'Hooksett',
        county: 'Merrimack',
        state: 'NH',
        zip: '03106',
        population: '14,500',
        median_price: '$349,000',
        price_trend: 'up 10%',
        avg_dom: 20,
        description: 'Hooksett sits strategically between Manchester and Concord on the Merrimack River, offering buyers one of southern New Hampshire\'s best-connected locations at prices that remain below the Hillsborough County average, supported by major retail at the Hooksett outlet corridor and a growing residential base. Bear Brook State Park provides significant green space that gives Hooksett a recreational appeal uncommon in this section of the I-93 corridor.',
        neighborhoods: 'Hooksett Village, Hackett Hill, Pinecrest, Bear Brook area',
        nearby: 'Manchester, Auburn, Candia, Bow',
        seller_hook: 'Hooksett\'s positioning between Manchester and Concord means your home appeals to two of New Hampshire\'s largest employment centers simultaneously — a geographic advantage that translates directly into more competing offers.',
        realtor_hook: 'Hooksett\'s dual-market access between Manchester and Concord gives agents a broad buyer funnel, while its price point below Manchester attracts active first-time buyers seeking NH\'s tax benefits.',
    },
    {
        slug: 'hudson',
        name: 'Hudson',
        county: 'Hillsborough',
        state: 'NH',
        zip: '03051',
        population: '25,000',
        median_price: '$389,000',
        price_trend: 'up 10%',
        avg_dom: 19,
        description: 'Hudson hugs the Massachusetts border across the Merrimack River from Nashua, offering no-income-tax homeownership within minutes of I-93 and the Everett Turnpike for buyers who work in Lowell, Haverhill, or Lawrence and want to maximize their take-home pay. Strong schools, Alvirne High School\'s reputation, and accessible land have made Hudson one of the Hillsborough County corridor\'s most consistent performers.',
        neighborhoods: 'Hudson Center, Alvirne area, Library Hill, Burns Hill Road',
        nearby: 'Nashua, Litchfield, Pelham, Chelmsford MA',
        seller_hook: 'Hudson\'s border location and no-income-tax advantage draw a constant stream of Massachusetts buyers — your home will be seen by commuters from Lowell and Lawrence who are motivated to cross the state line.',
        realtor_hook: 'Hudson\'s Massachusetts border access and NH tax advantage create a unique cross-state buyer dynamic that rewards agents who can serve both NH-based and MA-relocating clients equally well.',
    },

    // ── Seacoast ──────────────────────────────────────────────────────────
    {
        slug: 'portsmouth',
        name: 'Portsmouth',
        county: 'Rockingham',
        state: 'NH',
        zip: '03801',
        population: '22,000',
        median_price: '$479,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Portsmouth is New Hampshire\'s crown jewel — a compact, walkable seacoast city with a nationally celebrated restaurant scene, historic Strawbery Banke district, and a Market Square that anchors one of New England\'s most vibrant small-city downtowns. Its no-income-tax advantage combined with easy Boston and Portland commutes and a waterfront lifestyle create demand that far exceeds available supply.',
        neighborhoods: 'Downtown Portsmouth, Strawbery Banke, South End, New Castle nearby, Kittery ME nearby',
        nearby: 'Newington, Greenland, Rye, Kittery ME',
        seller_hook: 'Portsmouth\'s national reputation as New England\'s most livable small city draws buyers from Boston, Portland, and New York who are ready to pay a premium — and NH\'s no-income-tax advantage seals the deal.',
        realtor_hook: 'Portsmouth\'s combination of coastal lifestyle, no-income-tax advantage, and national recognition as a top small city draws sophisticated buyers from major metros, creating a premium market that rewards agents with deep local knowledge.',
    },
    {
        slug: 'hampton',
        name: 'Hampton',
        county: 'Rockingham',
        state: 'NH',
        zip: '03842',
        population: '15,000',
        median_price: '$519,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'Hampton offers New Hampshire\'s only major ocean beach, combining seasonal resort energy with year-round residential neighborhoods that attract buyers seeking a true seacoast lifestyle without the Massachusetts price tag. The Hampton Beach State Park, surf culture, and growing off-season dining scene make it increasingly appealing as a primary residence for Boston-area remote workers who want sand, surf, and NH tax savings.',
        neighborhoods: 'Hampton Beach, Hampton Center, North Hampton side, Winnacunnet Road',
        nearby: 'North Hampton, Seabrook, Kensington, Exeter',
        seller_hook: 'Hampton\'s ocean beach access and New Hampshire\'s no-income-tax advantage create a powerful combination for Boston-area buyers — beachfront and beach-adjacent properties here are attracting multiple offers routinely.',
        realtor_hook: 'Hampton\'s ocean beach lifestyle paired with NH\'s tax advantage makes it one of the most compelling pitches on the entire New England coast — agents who know the beach property market here are in high demand.',
    },
    {
        slug: 'exeter',
        name: 'Exeter',
        county: 'Rockingham',
        state: 'NH',
        zip: '03833',
        population: '15,000',
        median_price: '$489,000',
        price_trend: 'up 9%',
        avg_dom: 19,
        description: 'Exeter anchors the Seacoast\'s inland communities with a stunning historic downtown, Phillips Exeter Academy\'s institutional prestige, and a Squamscott River setting that creates a walkable, architecturally rich environment unlike anything else in the region. The academy draws faculty and staff buyers from across the country, while its broader community appeal to Boston commuters and seacoast residents sustains above-average demand year-round.',
        neighborhoods: 'Exeter Town Center, Swasey Parkway, Front Street, Lincoln Street',
        nearby: 'Newmarket, Hampton, Stratham-nh, Kingston',
        seller_hook: 'Exeter\'s Phillips Exeter Academy prestige and stunning historic downtown command a lasting premium — sellers benefit from a nationally aware buyer pool that includes educators, professionals, and seacoast enthusiasts.',
        realtor_hook: 'Exeter\'s academy-driven prestige and Boston-commuter appeal attract highly educated buyers who research thoroughly and then move decisively, rewarding agents who can build trust quickly.',
    },
    {
        slug: 'newmarket',
        name: 'Newmarket',
        county: 'Rockingham',
        state: 'NH',
        zip: '03857',
        population: '9,000',
        median_price: '$449,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Newmarket is a beautifully preserved mill town on the Lamprey River that has become one of the Seacoast\'s most sought-after residential communities, with a converted mill district, independent arts scene, and University of New Hampshire proximity that attracts buyers who want Portsmouth-caliber character at a more accessible price. Its rapid appreciation reflects growing recognition of its undervalued status relative to neighboring Exeter and Portsmouth.',
        neighborhoods: 'Newmarket Mill District, Main Street, Packer Falls, Bay Road',
        nearby: 'Exeter, Durham, Stratham-nh, Portsmouth',
        seller_hook: 'Newmarket\'s mill-town character and UNH proximity are converting Exeter and Portsmouth buyers who want authentic New England at a more achievable price — sellers are meeting serious, motivated buyers.',
        realtor_hook: 'Newmarket\'s rapidly evolving identity from sleeper town to Seacoast discovery gives agents a compelling story that resonates with buyers who want both character and upside appreciation.',
    },
    {
        slug: 'stratham',
        name: 'Stratham',
        county: 'Rockingham',
        state: 'NH',
        zip: '03885',
        population: '7,500',
        median_price: '$549,000',
        price_trend: 'up 8%',
        avg_dom: 21,
        description: 'Stratham is a quiet, semi-rural Seacoast community with a large-lot residential character, top-ranked schools, and a Stratham Hill Park that gives it an open, spacious quality that larger neighboring towns cannot replicate at comparable prices. Its position at the crossroads of I-95 and Routes 101 and 33 makes it one of the Seacoast\'s most commuter-convenient addresses while preserving a distinctly small-town feel.',
        neighborhoods: 'Stratham Hill Park area, Portsmouth Avenue, Winnicut Road, Stratham Center',
        nearby: 'Exeter, Greenland, Portsmouth, Newfields',
        seller_hook: 'Stratham\'s top schools, large lots, and Seacoast convenience command a premium that Boston-area buyers readily understand — sellers consistently see strong, clean offers from well-qualified relocators.',
        realtor_hook: 'Stratham\'s premium positioning and low inventory create a seller\'s market dynamic that rewards agents who price accurately and market aggressively to the broader NH and Boston buyer pool.',
    },
    {
        slug: 'dover',
        name: 'Dover',
        county: 'Strafford',
        state: 'NH',
        zip: '03820',
        population: '32,000',
        median_price: '$339,000',
        price_trend: 'up 11%',
        avg_dom: 18,
        description: 'Dover is New Hampshire\'s fastest-growing city, with a revitalized downtown anchored by the Cochecho Millworks, a burgeoning restaurant and arts scene, and Amtrak Downeaster service to Boston that makes it the Seacoast\'s most transit-accessible community. Its combination of urban energy, UNH proximity, and prices well below Portsmouth have made it the go-to destination for young professionals seeking the NH tax advantage.',
        neighborhoods: 'Downtown Dover, Cochecho Millworks, Henry Law Park area, Rollinsford nearby',
        nearby: 'Somersworth, Rochester, Rollinsford, Portsmouth',
        seller_hook: 'Dover\'s Amtrak service to Boston and downtown renaissance are attracting a new generation of Boston-area buyers — sellers are seeing demand and price growth that rival any city in the state.',
        realtor_hook: 'Dover\'s Downeaster train access and downtown revival create a compelling pitch for Boston-area buyers seeking maximum NH tax savings with genuine urban amenities — a combination that closes deals.',
    },
    {
        slug: 'rochester',
        name: 'Rochester',
        county: 'Strafford',
        state: 'NH',
        zip: '03867',
        population: '31,000',
        median_price: '$279,000',
        price_trend: 'up 12%',
        avg_dom: 22,
        description: 'Rochester is the Strafford County seat and one of New Hampshire\'s most affordable cities, undergoing a meaningful downtown revitalization that is attracting first-time buyers, investors, and small-business owners who recognize the upside potential of a well-located market trading at a significant discount to coastal neighbors. Its Spaulding Turnpike access and growing commercial corridor signal a market in active transition.',
        neighborhoods: 'Rochester City Center, Gonic, East Rochester, Spaulding Turnpike area',
        nearby: 'Dover, Farmington, Barrington, Somersworth',
        seller_hook: 'Rochester\'s affordability and proximity to the booming Dover and Portsmouth markets are drawing buyers who want to get in early on New Hampshire\'s next rising city — sellers are seeing appreciation not seen in years.',
        realtor_hook: 'Rochester\'s value positioning relative to coastal Strafford County and 12% appreciation trajectory create excellent opportunity for agents willing to build a client base in a market on the cusp of broader recognition.',
    },

    // ── Central & Lakes Region ────────────────────────────────────────────
    {
        slug: 'concord',
        name: 'Concord',
        county: 'Merrimack',
        state: 'NH',
        zip: '03301',
        population: '43,000',
        median_price: '$309,000',
        price_trend: 'up 10%',
        avg_dom: 20,
        description: 'Concord is New Hampshire\'s capital city and the Merrimack Valley\'s civic and commercial anchor, offering state-government employment stability, a revitalized Main Street, and major hospital anchors that create consistent year-round housing demand. Its central location with easy I-93 and I-89 access gives buyers connectivity to Boston, Manchester, and the Lakes Region that few NH cities can match.',
        neighborhoods: 'Downtown Concord, West Concord, East Concord, Penacook, Intervale',
        nearby: 'Hooksett, Bow, Pembroke, Canterbury',
        seller_hook: 'Concord\'s state capital stability and improving downtown have made it one of the Merrimack Valley\'s most reliable markets — sellers benefit from a diverse buyer pool that includes state employees, healthcare workers, and Boston commuters.',
        realtor_hook: 'Concord\'s employment diversity across government, healthcare, and education creates a steady transaction base that insulates agents from the volatility affecting more single-sector NH markets.',
    },
    {
        slug: 'laconia',
        name: 'Laconia',
        county: 'Belknap',
        state: 'NH',
        zip: '03246',
        population: '16,000',
        median_price: '$309,000',
        price_trend: 'up 12%',
        avg_dom: 22,
        description: 'Laconia is the commercial hub of the Lakes Region, surrounded by Lake Winnipesaukee, Paugus Bay, and Opechee Lake in a setting that drives both primary-residence and vacation-home demand from buyers throughout New England. Weirs Beach\'s seasonal energy, a revitalizing downtown, and growing year-round residential appeal are pushing appreciation to some of the fastest rates in Belknap County.',
        neighborhoods: 'Lakeport, Weirs Beach, Laconia City Center, Meredith Neck, Paugus Bay',
        nearby: 'Gilford, Meredith, Belmont, Tilton',
        seller_hook: 'Laconia\'s lakefront and near-lake properties are competing with coastal markets for the same second-home and relocating buyers — sellers are commanding prices that reflect the Lakes Region\'s national appeal.',
        realtor_hook: 'Laconia\'s mix of primary-residence and vacation-home buyers creates a diverse, year-round client base that rewards agents comfortable working the full spectrum from starter homes to lakefront estates.',
    },
    {
        slug: 'keene',
        name: 'Keene',
        county: 'Cheshire',
        state: 'NH',
        zip: '03431',
        population: '23,000',
        median_price: '$259,000',
        price_trend: 'up 9%',
        avg_dom: 24,
        description: 'Keene is the Monadnock Region\'s largest city, anchored by Keene State College, a stunning Central Square recognized as one of New England\'s finest, and a cultural amenity base that sustains demand well above what its size might suggest. Its position at the intersection of Routes 9, 10, and 101 makes it the service center for southwestern New Hampshire, providing durable employment and retail anchors that support year-round residential demand.',
        neighborhoods: 'Keene Central Square, West Keene, East Keene, Marlborough Street',
        nearby: 'Swanzey, Marlborough, Chesterfield, Brattleboro VT',
        seller_hook: 'Keene\'s college-town stability and stunning Central Square give sellers a story that resonates with buyers from across the Monadnock Region and beyond — well-priced homes here sell with confidence.',
        realtor_hook: 'Keene\'s position as the Monadnock Region\'s service hub and its Keene State College anchor create a reliable transaction base for agents who want long-term market stability.',
    },

    // ── White Mountains ───────────────────────────────────────────────────
    {
        slug: 'conway',
        name: 'Conway',
        county: 'Carroll',
        state: 'NH',
        zip: '03818',
        population: '10,000',
        median_price: '$379,000',
        price_trend: 'up 15%',
        avg_dom: 20,
        description: 'Conway anchors the Mount Washington Valley and the gateway to New Hampshire\'s White Mountains, encompassing North Conway\'s famous outlet shopping district and ski-country amenities that draw buyers from Boston, Portland, and beyond seeking vacation homes and year-round mountain lifestyles. At 15% annual appreciation, it leads Carroll County by a wide margin as remote work migration and vacation-home demand continue to outstrip available inventory.',
        neighborhoods: 'Conway Village, North Conway, Redstone, Intervale, Bartlett nearby',
        nearby: 'Bartlett, Jackson, North Conway, Madison',
        seller_hook: 'Conway\'s 15% appreciation — among the highest in New Hampshire — and booming vacation-home market mean sellers are capturing prices that reflect the national surge in mountain-lifestyle demand.',
        realtor_hook: 'Conway\'s White Mountain appeal draws buyers from Boston, Portland, and beyond who are motivated, well-funded, and eager to close — one of New Hampshire\'s most dynamic opportunity markets for agents who specialize in resort and vacation properties.',
    },
];
