// cities/nj.js — New Jersey city data for SEO landing pages

module.exports = [
    {
        slug: 'newark',
        name: 'Newark',
        county: 'Essex',
        state: 'NJ',
        zip: '07101',
        population: '311,000',
        median_price: '$349,000',
        price_trend: 'up 11%',
        avg_dom: 21,
        description: 'Newark is New Jersey\'s largest city and a real estate market experiencing dramatic appreciation, driven by NJ Transit and PATH train access to Midtown Manhattan, a massive downtown development boom, and buyers priced out of New York City\'s boroughs discovering Newark\'s authentic culture and walkable neighborhoods.',
        neighborhoods: 'Ironbound, Forest Hill, University Heights, Weequahic, Down Neck, North Ward, Central Ward',
        nearby: 'East Orange, Elizabeth, Bloomfield, Belleville, Irvington',
        seller_hook: 'Newark\'s PATH access and Manhattan proximity are driving 11% appreciation — let competitive Essex County realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Newark is New Jersey\'s fastest-appreciating urban market — RealtorFinder connects you with sellers in a city where buyer demand has never been stronger.',
    },
    {
        slug: 'jersey-city',
        name: 'Jersey City',
        county: 'Hudson',
        state: 'NJ',
        zip: '07302',
        population: '292,000',
        median_price: '$679,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'Jersey City is the most Manhattan-adjacent real estate market in New Jersey — a densely developed waterfront city where PATH train service delivers residents to the World Trade Center in under 10 minutes, and neighborhoods like the Heights and Journal Square offer entry points well below comparable Brooklyn and Queens addresses.',
        neighborhoods: 'Journal Square, The Heights, Downtown Jersey City, Greenville, Bergen-Lafayette, West Side, Paulus Hook',
        nearby: 'Hoboken, Bayonne, Secaucus, Union City, North Bergen',
        seller_hook: 'Jersey City\'s PATH access and NYC proximity drive fierce buyer competition — RealtorFinder puts top Hudson County agents in a bidding war to represent your home.',
        realtor_hook: 'Jersey City\'s position as Manhattan\'s most accessible suburb creates consistent, high-value buyer demand — RealtorFinder gives you early access to motivated sellers in this premium market.',
    },
    {
        slug: 'paterson',
        name: 'Paterson',
        county: 'Passaic',
        state: 'NJ',
        zip: '07501',
        population: '159,000',
        median_price: '$279,000',
        price_trend: 'up 10%',
        avg_dom: 24,
        description: 'Paterson is New Jersey\'s third-largest city and one of its most affordable — a historically rich manufacturing city built around the Great Falls National Historical Park with direct NJ Transit rail access to New York Penn Station, drawing buyers seeking urban character at significantly lower price points than the Hudson County waterfront.',
        neighborhoods: 'Great Falls Historic District, Eastside, Northside, Sandy Hill, Bunker Hill, Totowa border',
        nearby: 'Clifton, Passaic, Haledon, Hawthorne, Wayne',
        seller_hook: 'Paterson\'s affordability and train access are drawing NYC-area buyers in growing numbers — let competitive realtors on RealtorFinder bring you the best possible sale.',
        realtor_hook: 'Paterson\'s sub-$280K median and strong appreciation make it one of New Jersey\'s highest-volume entry-level markets — RealtorFinder connects you with motivated sellers here.',
    },
    {
        slug: 'elizabeth',
        name: 'Elizabeth',
        county: 'Union',
        state: 'NJ',
        zip: '07201',
        population: '137,000',
        median_price: '$389,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'Elizabeth is Union County\'s largest city and a transit nexus — served by both NJ Transit rail and Newark Liberty International Airport — with a vibrant Latino commercial district, a broad stock of Victorian-era housing, and appreciation rates that reflect spillover demand from buyers priced out of Newark and Jersey City.',
        neighborhoods: 'Elizabethport, Midtown, Elmora, North Elizabeth, Peterstown, Kesbrough',
        nearby: 'Newark, Linden, Hillside, Roselle, Union Township',
        seller_hook: 'Elizabeth\'s transit access and strong buyer demand from NYC commuters create ideal conditions for a competitive sale — RealtorFinder puts top local agents in competition for your listing.',
        realtor_hook: 'Elizabeth\'s combination of affordability, transit access, and 10% appreciation makes it a consistent high-opportunity market for focused agents — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'edison',
        name: 'Edison',
        county: 'Middlesex',
        state: 'NJ',
        zip: '08817',
        population: '107,000',
        median_price: '$529,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Edison is one of New Jersey\'s most sought-after suburban communities — a diverse, well-managed township with top-ranked schools, a large Indian-American community anchored by Oak Tree Road, and NJ Transit rail access to New York Penn Station that keeps commuter demand reliably strong.',
        neighborhoods: 'Oak Tree Road corridor, Metuchen border, Clara Barton, Pumptown, North Edison, Stelton',
        nearby: 'Woodbridge, Metuchen, Piscataway, South Plainfield, New Brunswick',
        seller_hook: 'Edison\'s top schools and train access drive strong buyer competition year-round — let competitive Middlesex County realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Edison\'s diverse, highly educated buyer pool and strong school ratings create consistent listing demand — RealtorFinder connects you with motivated sellers in this reliable market.',
    },
    {
        slug: 'woodbridge',
        name: 'Woodbridge',
        county: 'Middlesex',
        state: 'NJ',
        zip: '07095',
        population: '100,000',
        median_price: '$469,000',
        price_trend: 'up 8%',
        avg_dom: 21,
        description: 'Woodbridge is Middlesex County\'s largest township — a sprawling community where established neighborhoods, NJ Transit rail service, and access to the Garden State Parkway and Turnpike make it one of the most practical choices for commuters and families in central New Jersey.',
        neighborhoods: 'Woodbridge Center, Fords, Colonia, Avenel, Port Reading, Iselin, Sewaren',
        nearby: 'Edison, Perth Amboy, Metuchen, South Amboy, Carteret',
        seller_hook: 'Woodbridge\'s highway access and family-friendly neighborhoods keep buyer demand strong — RealtorFinder puts motivated local agents in competition to maximize your sale.',
        realtor_hook: 'Woodbridge\'s large population and central location generate consistent listing volume across six distinct communities — RealtorFinder gets you in front of motivated sellers.',
    },
    {
        slug: 'lakewood',
        name: 'Lakewood',
        county: 'Ocean',
        state: 'NJ',
        zip: '08701',
        population: '135,000',
        median_price: '$389,000',
        price_trend: 'up 12%',
        avg_dom: 19,
        description: 'Lakewood is one of New Jersey\'s fastest-growing townships — a remarkably diverse community with a large Orthodox Jewish population, rapid residential development, and proximity to both the Jersey Shore and the New York metro that keeps it in strong demand across multiple buyer demographics.',
        neighborhoods: 'Lakewood Center, New Central, Pine Park, Ocean County Park area, Cedarbridge',
        nearby: 'Toms River, Jackson, Brick, Howell, Manchester',
        seller_hook: 'Lakewood\'s 12% appreciation and fast-growing population create fierce buyer competition — let RealtorFinder\'s competing agents bring you the strongest possible offer.',
        realtor_hook: 'Lakewood is one of New Jersey\'s fastest-appreciating townships with a rapidly expanding buyer base — RealtorFinder connects you with sellers in this high-velocity market.',
    },
    {
        slug: 'toms-river',
        name: 'Toms River',
        county: 'Ocean',
        state: 'NJ',
        zip: '08753',
        population: '92,000',
        median_price: '$379,000',
        price_trend: 'up 9%',
        avg_dom: 23,
        description: 'Toms River is Ocean County\'s commercial hub and the gateway to the Barnegat Bay shore towns — a large township that draws families, retirees, and Jersey Shore buyers seeking year-round residential stability with beach access on weekends and seasons.',
        neighborhoods: 'Downtown Toms River, Pine Beach border, Silverton, Brookside, North Dover, Pleasant Plains',
        nearby: 'Brick, Lakewood, Beachwood, Berkeley Township, Seaside Heights',
        seller_hook: 'Toms River\'s shore access and family demand drive consistent year-round buyer interest — RealtorFinder puts competitive Ocean County agents in a bidding war to represent your home.',
        realtor_hook: 'Toms River\'s combination of shore access, family appeal, and steady appreciation makes it Ocean County\'s most active listing market — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'hamilton-nj',
        name: 'Hamilton',
        county: 'Mercer',
        state: 'NJ',
        zip: '08609',
        population: '92,000',
        median_price: '$339,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Hamilton is Mercer County\'s largest township — a sprawling suburban community adjacent to Trenton with NJ Transit rail to both New York and Philadelphia, top-rated public schools, and a diverse housing stock that appeals to first-time buyers and commuters seeking value between the two major metro areas.',
        neighborhoods: 'Hamilton Square, Groveville, White Horse, Mercerville, Yardville, Hamilton area',
        nearby: 'Trenton, Lawrenceville, Ewing, Princeton, Robbinsville',
        seller_hook: 'Hamilton\'s dual commuter access to NYC and Philly creates a broad buyer pool — let competitive Mercer County realtors on RealtorFinder fight for the right to represent your home.',
        realtor_hook: 'Hamilton\'s position between New York and Philadelphia commuter markets makes it a consistently active listing territory — RealtorFinder connects you with sellers in Mercer County.',
    },
    {
        slug: 'trenton',
        name: 'Trenton',
        county: 'Mercer',
        state: 'NJ',
        zip: '08601',
        population: '92,000',
        median_price: '$219,000',
        price_trend: 'up 10%',
        avg_dom: 26,
        description: 'Trenton is New Jersey\'s capital and its most affordable major city — a state government hub with NJ Transit rail service to both New York Penn Station and Philadelphia 30th Street, drawing buyers seeking maximum value in a market that is finally beginning to reflect its strategic location between two of the most expensive metros in the country.',
        neighborhoods: 'Chambersburg, Mill Hill Historic District, South Ward, North Ward, East Trenton, West Ward',
        nearby: 'Hamilton, Ewing, Lawrence, Morrisville PA, Levittown PA',
        seller_hook: 'Trenton\'s 10% appreciation and dual-metro rail access are drawing buyers from both NYC and Philadelphia — RealtorFinder puts motivated agents in competition to maximize your sale.',
        realtor_hook: 'Trenton\'s sub-$220K entry point and state capital stability make it a compelling market for buyers and investors — RealtorFinder connects you with sellers in New Jersey\'s capital.',
    },
];
