// cities/nm.js — New Mexico city data for SEO landing pages

module.exports = [
    {
        slug: 'albuquerque',
        name: 'Albuquerque',
        county: 'Bernalillo',
        state: 'NM',
        zip: '87102',
        population: '564,000',
        median_price: '$310,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'Albuquerque is New Mexico\'s largest city and a sun-drenched high desert metropolis along the Rio Grande — a Breaking Bad backdrop where Sandia Mountain views, Kirtland Air Force Base, University of New Mexico, and a growing tech and film production sector attract remote workers, military families, and adventurous buyers seeking affordable desert living with 310+ days of sunshine per year.',
        neighborhoods: 'Nob Hill, North Valley, Corrales, Rio Rancho, Heights, Downtown, Four Hills',
        nearby: 'Rio Rancho, Bernalillo, Corrales, Tijeras, Los Lunas',
        seller_hook: 'Albuquerque\'s remote worker influx and Kirtland AFB community drive strong buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Albuquerque\'s growing tech and film economy attract buyers from across the country — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'las-cruces',
        name: 'Las Cruces',
        county: 'Doña Ana',
        state: 'NM',
        zip: '88001',
        population: '114,000',
        median_price: '$240,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Las Cruces is New Mexico\'s second-largest city and home to New Mexico State University — a Mesilla Valley community near El Paso with Organ Mountains views, White Sands Missile Range proximity, and a booming Spaceport America sector that draws Aggie students, defense workers, and retirees seeking affordable desert homeownership with one of the Southwest\'s longest growing seasons.',
        neighborhoods: 'Mesilla, East Mesa, Sonoma Ranch, Rinconada Hills, Picacho Hills',
        nearby: 'Anthony, Chaparral, Sunland Park, El Paso TX, Mesilla',
        seller_hook: 'Las Cruces\' NMSU enrollment and defense sector create reliable buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Las Cruces\' university market and Spaceport sector growth create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'rio-rancho',
        name: 'Rio Rancho',
        county: 'Sandoval',
        state: 'NM',
        zip: '87124',
        population: '105,000',
        median_price: '$295,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Rio Rancho is New Mexico\'s third-largest city and Albuquerque\'s most populous suburb — a Sandoval County community where Intel\'s large semiconductor fabrication plant, top-rated Rio Rancho Unified School District schools, and affordable new construction on the high desert mesa attract tech workers, young families, and buyers priced out of Bernalillo County.',
        neighborhoods: 'Loma Colorado, Cabezon, High Resort, Northern Meadows, Enchanted Hills',
        nearby: 'Albuquerque, Corrales, Bernalillo, Cuba, Placitas',
        seller_hook: 'Rio Rancho\'s Intel workforce and top schools drive competitive listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Rio Rancho\'s tech employer base and rapid growth make it Albuquerque\'s fastest-appreciating suburb — find sellers through RealtorFinder.',
    },
    {
        slug: 'santa-fe',
        name: 'Santa Fe',
        county: 'Santa Fe',
        state: 'NM',
        zip: '87501',
        population: '84,000',
        median_price: '$580,000',
        price_trend: 'up 7%',
        avg_dom: 40,
        description: 'Santa Fe is America\'s oldest state capital and the world\'s third-largest art market — a 7,000-foot adobe city where Canyon Road galleries, the Santa Fe Opera, a James Beard Award-winning food scene, and New Mexico\'s state government draw wealthy retirees, artists, and remote workers willing to pay a significant premium for the spiritual beauty and cultural density of the City Different.',
        neighborhoods: 'Canyon Road, Historic District, Museum Hill, Monte Sereno, Tesuque',
        nearby: 'Pojoaque, Espanola, Lamy, Galisteo, Pecos',
        seller_hook: 'Santa Fe\'s art market prestige and global buyer demand command premium prices — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Santa Fe\'s luxury art market and wealthy out-of-state buyer base create high-value listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'roswell-nm',
        name: 'Roswell',
        county: 'Chaves',
        state: 'NM',
        zip: '88201',
        population: '48,000',
        median_price: '$175,000',
        price_trend: 'up 3%',
        avg_dom: 48,
        description: 'Roswell is southeastern New Mexico\'s commercial hub and the world\'s most famous UFO destination — an agricultural and oil production city on the Pecos River where the International UFO Museum, Eastern New Mexico University-Roswell, and petrochemical employment create demand for affordable ranch-style homes at prices that make it one of the Southwest\'s best markets for first-time buyers and investors.',
        neighborhoods: 'Downtown, South Roswell, North Town, Orchard Park, Sunset',
        nearby: 'Artesia, Dexter, Hagerman, Lake Arthur, Lovington',
        seller_hook: 'Roswell\'s agricultural economy and oil sector create steady buyer demand at accessible prices — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Roswell\'s affordable market and diverse employer base create consistent listing volume — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'farmington-nm',
        name: 'Farmington',
        county: 'San Juan',
        state: 'NM',
        zip: '87401',
        population: '45,000',
        median_price: '$220,000',
        price_trend: 'up 3%',
        avg_dom: 45,
        description: 'Farmington is the Four Corners region\'s largest city and New Mexico\'s oil and natural gas capital — a high desert community at the confluence of the San Juan, Animas, and La Plata rivers where energy industry wages, San Juan College enrollment, and proximity to Navajo Nation, Mesa Verde, and world-class fly fishing create a unique housing market for outdoor-minded energy workers.',
        neighborhoods: 'Pinon Hills, Riverview, Animas Valley, Tinajas, La Plata',
        nearby: 'Aztec, Bloomfield, Aztec Ruins, Durango CO, Shiprock',
        seller_hook: 'Farmington\'s energy sector wages and Four Corners lifestyle attract motivated buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Farmington\'s oil and gas economy and college enrollment create steady listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'clovis-nm',
        name: 'Clovis',
        county: 'Curry',
        state: 'NM',
        zip: '88101',
        population: '40,000',
        median_price: '$175,000',
        price_trend: 'up 3%',
        avg_dom: 45,
        description: 'Clovis is eastern New Mexico\'s agricultural hub and home to Cannon Air Force Base — a high plains community near the Texas border where USAF special operations employment, Eastern New Mexico University, and agricultural services create demand for affordable single-family homes, with VA loans driving a significant share of purchase activity among military families.',
        neighborhoods: 'North Clovis, East Grand Plains, South Clovis, Portales, Texico',
        nearby: 'Portales, Melrose, Grady, Texico, Friona TX',
        seller_hook: 'Clovis\' Cannon AFB military community provides year-round buyer activity — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Clovis\' military buyer pool and agricultural economy create consistent listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'hobbs-nm',
        name: 'Hobbs',
        county: 'Lea',
        state: 'NM',
        zip: '88240',
        population: '43,000',
        median_price: '$185,000',
        price_trend: 'up 4%',
        avg_dom: 42,
        description: 'Hobbs is the heart of New Mexico\'s Permian Basin oil patch and Lea County\'s largest city — an energy boomtown where oil royalties, Lea County jobs, and New Mexico Junior College create demand for affordable housing in a market that swings with crude prices, offering opportunistic buyers and investors significant upside when energy markets strengthen.',
        neighborhoods: 'Northeast Hobbs, Sunridge, North Hobbs, Lovington, Eunice',
        nearby: 'Lovington, Carlsbad, Eunice, Jal, Seminole TX',
        seller_hook: 'Hobbs\' Permian Basin energy economy drives strong buyer demand when oil markets are active — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Hobbs\' energy sector and affordable prices create active listing conditions for motivated buyers — connect with sellers through RealtorFinder.',
    },
];
