// cities/nv.js — Nevada city data for SEO landing pages

module.exports = [
    {
        slug: 'las-vegas',
        name: 'Las Vegas',
        county: 'Clark',
        state: 'NV',
        zip: '89101',
        population: '641000',
        median_price: '$430,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'Las Vegas is the most dynamic real estate market in the American Southwest — a city of relentless reinvention where the Strip\'s luxury resort corridor is backed by diverse residential neighborhoods ranging from the Arts District\'s urban lofts to Summerlin\'s master-planned suburbs. No state income tax, a booming service and technology economy, and a constant stream of retirees and remote workers relocating from California and the Midwest have made Las Vegas one of the fastest-appreciating major metro markets in the country.',
        neighborhoods: 'Downtown Las Vegas, Arts District, Charleston, John S. Park, Rancho Charleston, Mountain\'s Edge',
        nearby: 'Henderson, North Las Vegas, Summerlin, Enterprise, Boulder City',
        seller_hook: 'Las Vegas\'s no-income-tax appeal and California migration wave drive consistent buyer demand — let top Las Vegas realtors compete on RealtorFinder to earn the right to list your home.',
        realtor_hook: 'Las Vegas\'s relentless population growth and no-income-tax appeal create one of the most active listing markets in the West — RealtorFinder connects you with motivated sellers across the valley.',
    },
    {
        slug: 'henderson',
        name: 'Henderson',
        county: 'Clark',
        state: 'NV',
        zip: '89002',
        population: '320000',
        median_price: '$530,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Henderson is the most desirable residential city in the Las Vegas Valley — a master-planned community consistently ranked among the safest cities in the US that combines luxury resort-style living in Anthem, Lake Las Vegas\'s waterfront estates, and family-friendly neighborhoods with top-rated Clark County schools. Henderson\'s planned community character, proximity to Lake Mead National Recreation Area, and Village of Cadence development attract buyers from California and other high-tax states seeking quality suburban life with no state income tax.',
        neighborhoods: 'Anthem, Green Valley Ranch, Lake Las Vegas, Seven Hills, Cadence, MacDonald Ranch',
        nearby: 'Las Vegas, Boulder City, Enterprise, Paradise, Whitney Ranch',
        seller_hook: 'Henderson\'s top safety rankings and master-planned prestige attract premium buyers from across the Southwest — let competing agents battle on RealtorFinder to earn your listing.',
        realtor_hook: 'Henderson\'s consistent ranking as one of America\'s safest cities and its master-planned amenities drive premium buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'north-las-vegas',
        name: 'North Las Vegas',
        county: 'Clark',
        state: 'NV',
        zip: '89030',
        population: '265000',
        median_price: '$390,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'North Las Vegas is the Las Vegas Valley\'s fastest-growing and most affordable incorporated city — a diverse, working-class community experiencing rapid investment driven by Apex Industrial Park\'s massive logistics and technology development, including Amazon, Switch, and Tesla operations that are creating thousands of high-wage jobs. Newer master-planned neighborhoods in the North Valley offer first-time buyers spacious homes at prices well below Henderson and Summerlin.',
        neighborhoods: 'Aliante, Eldorado, Craig Ranch, North Cheyenne, Carey Rancho',
        nearby: 'Las Vegas, Nellis Air Force Base, Summerlin, Enterprise, Clark County',
        seller_hook: 'North Las Vegas\'s Apex Industrial growth and affordability are driving the fastest appreciation in the valley — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'North Las Vegas\'s logistics boom and affordability attract first-time buyers and investors from across the Southwest — RealtorFinder connects you with motivated sellers in the valley\'s growth corridor.',
    },
    {
        slug: 'summerlin',
        name: 'Summerlin',
        county: 'Clark',
        state: 'NV',
        zip: '89135',
        population: '110000',
        median_price: '$650,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Summerlin is the Las Vegas Valley\'s most prestigious master-planned community — a 22,500-acre development along the Spring Mountains foothills where The Summit Club, TPC Summerlin, Red Rock Country Club, and Downtown Summerlin\'s luxury retail and dining create a resort-caliber suburban lifestyle. Guard-gated villages like The Ridges, Summerlin Centre, and Paseos attract high-income buyers from California and other states who want Las Vegas proximity without the density, noise, or heat of the valley floor.',
        neighborhoods: 'The Ridges, The Hills, The Paseos, Summerlin Centre, Summerlin South, Reverence',
        nearby: 'Las Vegas, Enterprise, Spring Valley, Red Rock Canyon, Henderson',
        seller_hook: 'Summerlin\'s master-planned prestige and Red Rock views attract the highest-income buyers in Las Vegas — let the valley\'s top agents compete on RealtorFinder to earn your listing.',
        realtor_hook: 'Summerlin\'s resort-caliber master-planned communities and California buyer migration create a premium listing market — RealtorFinder connects you with motivated sellers in the valley\'s most prestigious address.',
    },
    {
        slug: 'enterprise',
        name: 'Enterprise',
        county: 'Clark',
        state: 'NV',
        zip: '89141',
        population: '230000',
        median_price: '$480,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Enterprise is an unincorporated Clark County community in the southwestern Las Vegas Valley — one of the fastest-growing residential areas in Nevada, where master-planned communities like Rhodes Ranch, Inspirada, and Southern Highlands offer suburban family living near the 215 Beltway with easy access to Henderson\'s retail and entertainment corridors. Enterprise\'s newer construction stock, competitive pricing relative to Henderson, and strong Clark County school options attract buyers from across the valley and from California.',
        neighborhoods: 'Rhodes Ranch, Southern Highlands, Inspirada, Mountain\'s Edge, Enterprise Hills',
        nearby: 'Henderson, Las Vegas, Spring Valley, Summerlin South, Boulder City',
        seller_hook: 'Enterprise\'s master-planned communities and Southwest Las Vegas location attract buyers from Henderson and California — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Enterprise\'s newer construction and Southwest Valley positioning create strong first-time and move-up buyer demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'spring-valley',
        name: 'Spring Valley',
        county: 'Clark',
        state: 'NV',
        zip: '89117',
        population: '210000',
        median_price: '$440,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Spring Valley is an unincorporated community in the western Las Vegas Valley — a large, diverse suburban area between the Strip and Summerlin that offers Las Vegas convenience and variety at prices below Summerlin. The Peccole Ranch and Canyon Gate planned communities provide gated amenities, while the proximity to Summerlin Parkway and the 215 Beltway makes Spring Valley an attractive compromise between affordability and access to the valley\'s best retail and employment centers.',
        neighborhoods: 'Peccole Ranch, Canyon Gate, Spanish Oaks, Spring Valley Estates, Westcliff',
        nearby: 'Summerlin, Las Vegas, Enterprise, Winchester, Paradise',
        seller_hook: 'Spring Valley\'s location between Summerlin and the Strip attracts buyers seeking Las Vegas convenience at competitive prices — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Spring Valley\'s central western valley location and relative affordability draw buyers from across Clark County — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'paradise',
        name: 'Paradise',
        county: 'Clark',
        state: 'NV',
        zip: '89109',
        population: '223000',
        median_price: '$390,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Paradise is the unincorporated community that is home to the Las Vegas Strip — the world\'s most famous entertainment corridor, Harry Reid International Airport, UNLV\'s main campus, and the T-Mobile Arena anchor a community of hotels, luxury high-rise condominiums, and residential neighborhoods stretching from the Strip\'s east edge to Green Valley\'s western border. For buyers seeking walkability to the Strip, university proximity, and the heart of the Las Vegas entertainment economy, Paradise offers a unique and high-demand urban residential market.',
        neighborhoods: 'University District, Winchester, Paradise Valley, Naked City, East of Strip',
        nearby: 'Las Vegas, Henderson, Winchester, Whitney, Enterprise',
        seller_hook: 'Paradise\'s Strip proximity and UNLV demand create a unique buyer market for urban Las Vegas living — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Paradise\'s Strip location and UNLV campus create a consistent buyer pipeline of students, investors, and urban lifestyle seekers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'sunrise-manor',
        name: 'Sunrise Manor',
        county: 'Clark',
        state: 'NV',
        zip: '89110',
        population: '189000',
        median_price: '$360,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Sunrise Manor is an unincorporated Clark County community in the eastern Las Vegas Valley — one of the most affordable residential areas in the metro, where first-time buyers and investors find single-family homes and condominiums at prices well below the valley median. The Frenchman Mountain backdrop, proximity to Nellis Air Force Base\'s employment, and the Boulder Highway corridor\'s improving commercial landscape make Sunrise Manor an entry-level market with strong appreciation potential.',
        neighborhoods: 'Sunrise Acres, Sunrise Manor Proper, East Las Vegas, Hollywood Hills, Whitney',
        nearby: 'Las Vegas, Henderson, Boulder City, North Las Vegas, Paradise',
        seller_hook: 'Sunrise Manor\'s affordability and Nellis Air Force Base proximity drive consistent first-time buyer demand — let competing agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Sunrise Manor\'s entry-level prices and military buyer base create strong first-time buyer activity — RealtorFinder connects you with motivated sellers in this eastern valley community.',
    },
    {
        slug: 'reno',
        name: 'Reno',
        county: 'Washoe',
        state: 'NV',
        zip: '89501',
        population: '264000',
        median_price: '$520,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Reno is the Biggest Little City in the World and one of the fastest-growing technology hubs in the American West — a city transformed by Tesla\'s Gigafactory, Apple\'s data center, and Google\'s Nevada operations that have created a tech-driven economy alongside the traditional gaming and tourism industries. The University of Nevada Reno, Midtown\'s vibrant arts and dining district, and proximity to Lake Tahoe ski resorts attract buyers from the Bay Area seeking Nevada tax advantages with a genuine urban lifestyle.',
        neighborhoods: 'Midtown, Old Southwest, University of Nevada area, Northwest Reno, South Meadows, Caughlin Ranch',
        nearby: 'Sparks, Carson City, Sun Valley, Fernley, Truckee CA',
        seller_hook: 'Reno\'s Tesla economy and Bay Area migration wave drive strong buyer demand — let top Northern Nevada agents compete on RealtorFinder to earn your listing.',
        realtor_hook: 'Reno\'s tech economy transformation and California tax refugee buyer base create one of the West\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'sparks',
        name: 'Sparks',
        county: 'Washoe',
        state: 'NV',
        zip: '89431',
        population: '108000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Sparks is Reno\'s eastern sister city — a growing community with its own Victorian Square entertainment district, the Legends at Sparks Marina outdoor mall, and master-planned communities along the Truckee River corridor that offer Reno-area living at slightly more affordable prices. The Northern Nevada Industrial Center and Tahoe-Reno Industrial Center nearby house major employers including Tesla, Google, and Switch, creating a strong blue-collar and tech worker buyer base.',
        neighborhoods: 'Spanish Springs, Wingfield Springs, Sun Valley, Golden Eagle, Heritage Trails',
        nearby: 'Reno, Fernley, Carson City, Pyramid Lake, Truckee CA',
        seller_hook: 'Sparks\'s industrial park employment and Reno metro growth drive consistent buyer demand — let competing Northern Nevada agents on RealtorFinder earn your listing.',
        realtor_hook: 'Sparks\'s Tesla and tech-adjacent employment create a strong working-professional buyer base — RealtorFinder connects you with motivated sellers in Reno\'s eastern growth corridor.',
    },
    {
        slug: 'carson-city',
        name: 'Carson City',
        county: 'Carson City',
        state: 'NV',
        zip: '89701',
        population: '58000',
        median_price: '$480,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Carson City is Nevada\'s state capital and one of its most livable small cities — an independent city at the base of the Carson Range with easy access to Lake Tahoe, the Sierra Nevada, and Reno\'s growing tech economy 30 miles north. State government provides a stable employment base, and the historic downtown\'s Nevada State Museum, Carson City Mint, and thriving brewery scene attract buyers seeking authentic Nevada history and outdoor recreation within a small-city footprint at prices below Reno.',
        neighborhoods: 'Southwest Carson City, North Carson City, Lakeview, Ormsby, Old Town Carson City',
        nearby: 'Reno, Sparks, Gardnerville, Dayton, Minden',
        seller_hook: 'Carson City\'s capital city stability and Tahoe proximity attract buyers from across Northern Nevada — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Carson City\'s government employment base and Tahoe proximity create steady buyer demand from both state workers and lifestyle seekers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'fernley',
        name: 'Fernley',
        county: 'Lyon',
        state: 'NV',
        zip: '89408',
        population: '23000',
        median_price: '$370,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Fernley is the fastest-growing small city in Nevada — a logistics and distribution hub on I-80 east of Reno that has attracted major warehouse operations from Amazon, FedEx, and dozens of manufacturers seeking affordable industrial land and Nevada tax advantages. Home prices remain among the lowest in the Northern Nevada market, attracting first-time buyers, logistics workers, and Reno commuters who cannot afford Sparks or Reno proper but still want access to the Reno metro economy and Lake Tahoe recreation.',
        neighborhoods: 'East Fernley, Silverland, Churchill, Fernley Village, Lazy Z',
        nearby: 'Sparks, Reno, Fallon, Lovelock, Dayton',
        seller_hook: 'Fernley\'s logistics boom and affordability are driving some of Nevada\'s fastest appreciation — let competing agents on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Fernley\'s Amazon and FedEx employment base and first-time buyer pricing create active listing demand at the entry level of the Northern Nevada market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'mesquite',
        name: 'Mesquite',
        county: 'Clark',
        state: 'NV',
        zip: '89027',
        population: '20000',
        median_price: '$380,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Mesquite is Nevada\'s premier golf and retirement community at the Arizona border — a small city in the Virgin River Valley where CasaBlanca, Eureka, and Virgin River resort casinos anchor an economy built around retirees, golfers, and weekend visitors from Las Vegas and southern Utah. The Wolf Creek Golf Club, Falcon Ridge Golf Course, and Oasis Golf Club draw buyers from across the country seeking desert golf lifestyle, low Nevada taxes, and lower prices than St. George and Palm Springs.',
        neighborhoods: 'Sun City Mesquite, Anthem at Mesquite, Bunkerville, Riverside, Desert Crest',
        nearby: 'St. George UT, Las Vegas, Laughlin NV, Overton, Bunkerville',
        seller_hook: 'Mesquite\'s retirement golf community appeal attracts buyers from across the US seeking Nevada tax advantages and desert lifestyle — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Mesquite\'s Sun City and golf resort communities draw active adult buyers from Las Vegas, Utah, and beyond — RealtorFinder connects you with motivated sellers in this growing retirement market.',
    },
    {
        slug: 'boulder-city',
        name: 'Boulder City',
        county: 'Clark',
        state: 'NV',
        zip: '89005',
        population: '16000',
        median_price: '$430,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Boulder City is Nevada\'s most unique small city — the only Nevada city that prohibits gambling, a historic planned community built by the federal government to house Hoover Dam workers in the 1930s whose downtown retains its original Art Deco character and small-town charm. Wedged between Lake Mead National Recreation Area and the Las Vegas Valley, Boulder City attracts buyers seeking a quiet, authentic Nevada community with world-class boating, hiking, and outdoor recreation access at prices similar to the broader Las Vegas metro.',
        neighborhoods: 'Downtown Boulder City, Buchanan, Historic District, Mountain View, Lakeview',
        nearby: 'Henderson, Las Vegas, Laughlin NV, Hoover Dam, Lake Mead',
        seller_hook: 'Boulder City\'s unique no-gambling charter and Lake Mead access attract buyers seeking authentic small-town Nevada life — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Boulder City\'s distinct no-gambling character and Lake Mead adjacency attract a dedicated buyer base that appreciates its unique identity within Clark County — RealtorFinder connects you with motivated sellers.',
    },
];
