// cities/ny-extra.js — Additional New York city data for SEO landing pages
// Base ny.js already covers: NYC boroughs, Yonkers, White Plains, New Rochelle, Mount Vernon,
// Scarsdale, Rye, Harrison, Port Chester, Ossining, Tarrytown, Dobbs Ferry, Bronxville,
// Larchmont, Mamaroneck, Great Neck, Garden City, Hempstead, Babylon, Islip, Smithtown,
// Huntington, Syosset, Manhasset, Buffalo, Amherst, Cheektowaga, Rochester, Syracuse,
// Albany, Troy, Saratoga Springs, Ithaca

module.exports = [
    {
        slug: 'binghamton',
        name: 'Binghamton',
        county: 'Broome',
        state: 'NY',
        zip: '13901',
        population: '45,000',
        median_price: '$145,000',
        price_trend: 'up 8%',
        avg_dom: 18,
        description: 'Binghamton is the Southern Tier\'s Triple Cities hub and one of New York\'s most undervalued real estate markets — a Susquehanna River city where Binghamton University\'s rapid research rise, United Health Services hospitals, and some of the most affordable brick homes in the entire Northeast create intense investor and first-time buyer activity in a market where appreciation now rivals far more expensive upstate cities.',
        neighborhoods: 'Johnson City, Endicott, Vestal, Endwell, Conklin',
        nearby: 'Johnson City, Endicott, Vestal, Owego, Cortland',
        seller_hook: 'Binghamton\'s BU enrollment surge and New York State affordability create fast-moving buyer competition — let top agents compete on RealtorFinder.',
        realtor_hook: 'Binghamton\'s value-gap market and university growth generate some of New York\'s strongest appreciation for listings — find sellers through RealtorFinder.',
    },
    {
        slug: 'utica-ny',
        name: 'Utica',
        county: 'Oneida',
        state: 'NY',
        zip: '13501',
        population: '60,000',
        median_price: '$130,000',
        price_trend: 'up 8%',
        avg_dom: 16,
        description: 'Utica is the Mohawk Valley\'s most diverse city and a Bosnian and Burmese refugee community that has reversed its population decline — a Mohawk River city where SUNY Polytechnic, Mohawk Valley Health System\'s downtown hospital, and some of the most affordable Victorian and Craftsman homes in New York State attract first-generation homeowners, investors, and urban pioneers who see what Buffalo looked like a decade ago.',
        neighborhoods: 'New Hartford, Whitesboro, Yorkville, Ilion, Herkimer',
        nearby: 'Rome NY, New Hartford, Whitesboro, Herkimer, Little Falls',
        seller_hook: 'Utica\'s affordability and Mohawk Valley revival create fast-moving listing conditions — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Utica\'s investment-grade prices and SUNY Poly growth generate some of central New York\'s most active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'poughkeepsie',
        name: 'Poughkeepsie',
        county: 'Dutchess',
        state: 'NY',
        zip: '12601',
        population: '32,000',
        median_price: '$295,000',
        price_trend: 'up 8%',
        avg_dom: 18,
        description: 'Poughkeepsie is the Hudson Valley\'s midpoint and the Mid-Hudson region\'s cultural hub — a Metro-North commuter rail city 75 minutes from Grand Central where Vassar College, Marist College, and Dutchess Community College create a college-town energy alongside a booming arts scene in the Walkway Over the Hudson corridor, attracting NYC buyers who want genuine Hudson Valley character at prices well below Westchester.',
        neighborhoods: 'Arlington, Hyde Park, Pleasant Valley, Wappingers Falls, Fishkill',
        nearby: 'Hyde Park, Wappingers Falls, Fishkill, Beacon, Rhinebeck',
        seller_hook: 'Poughkeepsie\'s Hudson Valley prestige and NYC commuter rail create strong buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Poughkeepsie\'s Mid-Hudson value and NYC spillover generate active listing conditions — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'kingston-ny',
        name: 'Kingston',
        county: 'Ulster',
        state: 'NY',
        zip: '12401',
        population: '24,000',
        median_price: '$375,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'Kingston is New York\'s first state capital and the Hudson Valley\'s hottest real estate story — a Rondout Creek city where Brooklyn and Manhattan artists, remote workers, and weekend buyers have transformed Stockade District brownstones and Uptown Victorian neighborhoods into some of the Hudson Valley\'s most coveted addresses, with appreciation running near double digits as national media coverage amplifies what insiders discovered years ago.',
        neighborhoods: 'Uptown Stockade, Midtown, Rondout, Hurley, Woodstock',
        nearby: 'Woodstock, Rhinebeck, Saugerties, New Paltz, Catskill',
        seller_hook: 'Kingston\'s NYC remote worker discovery and Hudson Valley prestige create exceptional seller conditions — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Kingston\'s double-digit appreciation and Brooklyn buyer pool generate some of the Hudson Valley\'s most competitive listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'newburgh-ny',
        name: 'Newburgh',
        county: 'Orange',
        state: 'NY',
        zip: '12550',
        population: '28,000',
        median_price: '$295,000',
        price_trend: 'up 9%',
        avg_dom: 16,
        description: 'Newburgh is the Hudson Valley\'s comeback city and one of New York\'s most-watched emerging real estate markets — a Hudson River city where a vibrant Arts District in a grid of Renaissance Revival and Federal row houses, Metro-North access to Grand Central from nearby Beacon, and prices still far below where fundamentals suggest they should be attract Brooklyn buyers, developers, and first-generation homeowners ahead of the gentrification curve.',
        neighborhoods: 'East Newburgh, New Windsor, Beacon, Cornwall-on-Hudson, Vails Gate',
        nearby: 'Beacon, Cornwall-on-Hudson, Middletown, Goshen, Montgomery',
        seller_hook: 'Newburgh\'s rapid appreciation and NYC discovery create exceptional listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Newburgh\'s value-gap market and NYC buyer influx generate some of the Hudson Valley\'s fastest-moving listings — find sellers through RealtorFinder.',
    },
    {
        slug: 'plattsburgh-ny',
        name: 'Plattsburgh',
        county: 'Clinton',
        state: 'NY',
        zip: '12901',
        population: '19,000',
        median_price: '$215,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Plattsburgh is northern New York\'s Lake Champlain city and the gateway to Montreal — a SUNY Plattsburgh and Clinton Community College community where a rebuilt downtown, proximity to the Canadian border and Vermont\'s Green Mountains, and affordable Adirondack-region home prices attract students, remote workers, and buyers who want New York homeownership with a truly international flair just 60 miles south of Montreal.',
        neighborhoods: 'West Plattsburgh, Beekmantown, Peru, Saranac, Keeseville',
        nearby: 'Saranac Lake, Ticonderoga, Burlington VT, Rouses Point, Champlain',
        seller_hook: 'Plattsburgh\'s SUNY enrollment and Canadian border appeal create consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Plattsburgh\'s university market and Lake Champlain lifestyle generate active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'watertown-ny',
        name: 'Watertown',
        county: 'Jefferson',
        state: 'NY',
        zip: '13601',
        population: '25,000',
        median_price: '$175,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Watertown is Jefferson County\'s Fort Drum gateway city — a North Country community where the 10th Mountain Division\'s massive Army installation creates one of upstate New York\'s most stable military housing markets, with VA loans and frequent soldier rotation driving year-round purchase activity for soldiers and families seeking affordable Adirondack-region homeownership close to the St. Lawrence River and Thousand Islands.',
        neighborhoods: 'Fort Drum, Evans Mills, Sackets Harbor, Henderson, Mannsville',
        nearby: 'Fort Drum, Adams, Sackets Harbor, Carthage, Clayton',
        seller_hook: 'Watertown\'s Fort Drum military community drives year-round buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Watertown\'s 10th Mountain Division buyer pool and North Country market create consistent listing activity — connect with sellers through RealtorFinder.',
    },
];
