// cities/ny-extra.js — Additional New York city data for SEO landing pages

module.exports = [
    {
        slug: 'albany-ny',
        name: 'Albany',
        county: 'Albany',
        state: 'NY',
        zip: '12207',
        population: '99,000',
        median_price: '$235,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'Albany is New York\'s state capital and Capital Region\'s anchor — a Hudson River government hub where the state bureaucracy, University at Albany, Albany Medical Center, and Global Foundries semiconductor plant in Malta create a stable professional market, with buyers finding stately Victorian and Dutch Colonial homes at some of the state\'s most affordable prices for a city of its cultural and political weight.',
        neighborhoods: 'Center Square, Pine Hills, Washington Park, Guilderland, Colonie',
        nearby: 'Schenectady, Troy, Cohoes, Watervliet, Guilderland',
        seller_hook: 'Albany\'s state capital stability and Capital Region growth drive consistent buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Albany\'s government and university market create active listing conditions at some of New York\'s most affordable upstate prices — find sellers through RealtorFinder.',
    },
    {
        slug: 'rochester-ny',
        name: 'Rochester',
        county: 'Monroe',
        state: 'NY',
        zip: '14604',
        population: '211,000',
        median_price: '$200,000',
        price_trend: 'up 8%',
        avg_dom: 16,
        description: 'Rochester is the Flower City and New York\'s most affordable major metro — a Genesee River city where Kodak\'s legacy spawned a deep technology and optics ecosystem, the University of Rochester and RIT drive innovation, and home prices that rank among the Northeast\'s best values have made it a national media darling for affordability, creating intense competition for limited inventory in a perpetual seller\'s market.',
        neighborhoods: 'Park Avenue, Corn Hill, South Wedge, Pittsford, Brighton, Fairport',
        nearby: 'Pittsford, Brighton, Penfield, Webster, Fairport',
        seller_hook: 'Rochester\'s nationally recognized affordability and limited inventory create exceptional seller conditions — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Rochester\'s tech ecosystem and fast-moving market make every listing a multiple-offer opportunity — find sellers through RealtorFinder.',
    },
    {
        slug: 'buffalo-ny',
        name: 'Buffalo',
        county: 'Erie',
        state: 'NY',
        zip: '14202',
        population: '278,000',
        median_price: '$215,000',
        price_trend: 'up 8%',
        avg_dom: 16,
        description: 'Buffalo is Western New York\'s resurgent city and America\'s greatest comeback story in real estate — a Lake Erie city where a billion-dollar medical corridor, Tesla Gigafactory, University at Buffalo, and Canada border shopping create a surging housing market with nationally reported bidding wars, while Elmwood Village arts culture and a passionate Bills fanbase keep the community tightly knit.',
        neighborhoods: 'Elmwood Village, Allentown, North Buffalo, Cheektowaga, Amherst',
        nearby: 'Cheektowaga, Amherst, Tonawanda, Niagara Falls, Lackawanna',
        seller_hook: 'Buffalo\'s nationally covered seller\'s market and medical corridor create exceptional listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Buffalo\'s fastest-appreciating upstate market and low inventory make every listing a competitive opportunity — find sellers through RealtorFinder.',
    },
    {
        slug: 'white-plains',
        name: 'White Plains',
        county: 'Westchester',
        state: 'NY',
        zip: '10601',
        population: '58,000',
        median_price: '$560,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'White Plains is Westchester County\'s urban hub and the New York metropolitan area\'s most accessible northern suburb — a Metro-North railroad city 25 minutes from Grand Central where IBM, Heineken USA, and dozens of corporate headquarters create a professional class that drives demand for condominiums, cooperative apartments, and single-family homes in a market that defines the NYC outer-ring suburban premium.',
        neighborhoods: 'Battle Hill, Gedney Farms, Fisher Hill, Greenburgh, Harrison',
        nearby: 'Yonkers, Scarsdale, Rye, Mamaroneck, Port Chester',
        seller_hook: 'White Plains\' Westchester corporate campus and NYC rail access create strong professional buyer demand — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'White Plains\' Westchester County location and Manhattan commuter market generate active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'new-rochelle',
        name: 'New Rochelle',
        county: 'Westchester',
        state: 'NY',
        zip: '10801',
        population: '79,000',
        median_price: '$610,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'New Rochelle is Westchester County\'s waterfront city and one of the New York metro\'s most rapidly transforming suburban downtowns — a Long Island Sound community where a massive $4 billion downtown revitalization, Iona University, and 30-minute Metro-North access to Grand Central attract young professionals seeking urban density in a suburban setting with waterfront parks at prices below Manhattan boroughs.',
        neighborhoods: 'Larchmont, Pelham, Pelham Manor, Eastchester, Mount Vernon',
        nearby: 'Larchmont, Yonkers, Mount Vernon, Eastchester, Pelham',
        seller_hook: 'New Rochelle\'s downtown revitalization and NYC rail access drive strong buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'New Rochelle\'s Westchester renewal and commuter appeal create active listing conditions — connect with sellers through RealtorFinder.',
    },
];
