// cities/ny.js — New York state city data (upstate and Westchester) for SEO landing pages

module.exports = [
    {
        slug: 'albany-ny',
        name: 'Albany',
        county: 'Albany',
        state: 'NY',
        zip: '12201',
        population: '99,000',
        median_price: '$229,000',
        price_trend: 'up 9%',
        avg_dom: 24,
        description: 'The capital of New York State, Albany anchors a growing Capital Region economy fueled by state government, higher education, and an emerging tech sector — with home prices that remain remarkably affordable for a northeastern state capital.',
        neighborhoods: 'Center Square, Pine Hills, Arbor Hill, Delaware Avenue, Washington Park, North Albany, Helderberg',
        nearby: 'Schenectady, Troy, Cohoes, Colonie, Guilderland',
        seller_hook: 'Albany\'s government and university buyer pool keeps demand steady year-round — let competitive realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Albany\'s affordable price points and steady state-government buyer demand create consistent listing volume — RealtorFinder connects you with motivated sellers in the Capital Region.',
    },
    {
        slug: 'buffalo',
        name: 'Buffalo',
        county: 'Erie',
        state: 'NY',
        zip: '14201',
        population: '276,000',
        median_price: '$189,000',
        price_trend: 'up 12%',
        avg_dom: 19,
        description: 'Buffalo is one of the most dramatically improving real estate markets in the Northeast — a revitalized lakefront city with stunning architecture, a booming food scene, and home prices that make it one of the most affordable major cities in the eastern US.',
        neighborhoods: 'Elmwood Village, Allentown, Delaware Avenue, Hertel Avenue, South Buffalo, Black Rock, North Park, Kenmore border',
        nearby: 'Cheektowaga, Amherst, Tonawanda, Lackawanna, West Seneca',
        seller_hook: 'Buffalo\'s renaissance is driving 12% annual appreciation — let top Western New York realtors compete on RealtorFinder to maximize your sale price.',
        realtor_hook: 'Buffalo\'s rapid appreciation and affordable entry points are pulling buyers from across the region — RealtorFinder connects you with sellers in one of the Northeast\'s hottest turnaround markets.',
    },
    {
        slug: 'yonkers',
        name: 'Yonkers',
        county: 'Westchester',
        state: 'NY',
        zip: '10701',
        population: '211,000',
        median_price: '$469,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Yonkers is Westchester County\'s largest city and its most affordable gateway — a dense, transit-connected city on the Hudson River with Metro-North access to Grand Central in under 30 minutes, attracting NYC buyers priced out of the boroughs.',
        neighborhoods: 'Southwest Yonkers, Park Hill, Nodine Hill, Dunwoodie, Wakefield, Nepperhan, Riverdale border',
        nearby: 'Bronxville, Hastings-on-Hudson, Mount Vernon, White Plains, Eastchester',
        seller_hook: 'Yonkers\' Metro-North access draws NYC buyer overflow that competes fiercely for every listing — put realtors in a bidding war on RealtorFinder to earn your business.',
        realtor_hook: 'Yonkers\' affordability relative to NYC and 30-minute commute generates strong, consistent buyer demand — RealtorFinder gives you first access to sellers in Westchester\'s largest city.',
    },
    {
        slug: 'rochester-ny',
        name: 'Rochester',
        county: 'Monroe',
        state: 'NY',
        zip: '14601',
        population: '211,000',
        median_price: '$169,000',
        price_trend: 'up 11%',
        avg_dom: 20,
        description: 'Rochester is western New York\'s cultural and educational hub — home to the University of Rochester, RIT, and a thriving medical sector — with home prices among the lowest of any major northeastern city and an appreciation rate that signals a market the rest of the country is starting to notice.',
        neighborhoods: 'Park Avenue, South Wedge, Corn Hill, East End, Beechwood, Swillburg, Monroe Avenue corridor',
        nearby: 'Brighton, Pittsford, Webster, Irondequoit, Greece',
        seller_hook: 'Rochester\'s 11% appreciation and university-driven buyer demand make now a strong time to sell — let competing realtors on RealtorFinder bring you the best offer.',
        realtor_hook: 'Rochester\'s sub-$170K entry point and university-driven demand create high listing volume and fast-moving buyers — RealtorFinder keeps your pipeline full in Monroe County.',
    },
    {
        slug: 'syracuse',
        name: 'Syracuse',
        county: 'Onondaga',
        state: 'NY',
        zip: '13201',
        population: '148,000',
        median_price: '$149,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'Syracuse is a central New York city in the midst of a genuine economic revival, anchored by Syracuse University, a growing healthcare sector, and proximity to chip-manufacturing investment that is transforming the region into a tech hub with dramatically rising real estate values.',
        neighborhoods: 'Armory Square, Strathmore, Westcott, Sedgwick, Hawley-Green, Near Westside, University Hill',
        nearby: 'Fayetteville, Manlius, Clay, Liverpool, Camillus',
        seller_hook: 'Syracuse\'s semiconductor boom and university demand are driving 10% appreciation — RealtorFinder puts motivated local agents in competition to maximize your sale.',
        realtor_hook: 'Syracuse is one of the most undervalued appreciation stories in the Northeast — RealtorFinder connects you with sellers before the broader market catches on.',
    },
    {
        slug: 'white-plains',
        name: 'White Plains',
        county: 'Westchester',
        state: 'NY',
        zip: '10601',
        population: '59,000',
        median_price: '$549,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'White Plains is Westchester County\'s downtown hub — a walkable, transit-rich city with a thriving restaurant and shopping scene, express Metro-North service to Grand Central in 33 minutes, and condominium and townhome inventory that draws NYC buyers seeking suburban convenience without suburban isolation.',
        neighborhoods: 'Downtown White Plains, Gedney Farms, Battle Hill, North White Plains, Fisher Hill',
        nearby: 'Scarsdale, Harrison, Greenburgh, Tarrytown, Yonkers',
        seller_hook: 'White Plains\' express train access and walkable downtown command strong buyer attention — let top Westchester agents compete on RealtorFinder to represent your home.',
        realtor_hook: 'White Plains\' urban amenities and Metro-North express service make it the most in-demand transit hub in Westchester — RealtorFinder connects you with sellers in this active market.',
    },
    {
        slug: 'new-rochelle',
        name: 'New Rochelle',
        county: 'Westchester',
        state: 'NY',
        zip: '10801',
        population: '84,000',
        median_price: '$599,000',
        price_trend: 'up 8%',
        avg_dom: 23,
        description: 'New Rochelle is experiencing a dramatic downtown renaissance, with a wave of new mixed-use development, Metro-North access to Grand Central in 26 minutes, and a diverse, established residential community that draws buyers seeking Sound Shore lifestyle within easy commuting range of Manhattan.',
        neighborhoods: 'Downtown New Rochelle, Wykagyl, Beechmont, Sutton Manor, Huguenot Park, Pelham border',
        nearby: 'Pelham, Mamaroneck, Larchmont, Mount Vernon, Scarsdale',
        seller_hook: 'New Rochelle\'s downtown revival and fast train access are generating serious buyer competition — RealtorFinder puts top Sound Shore agents in a race to win your listing.',
        realtor_hook: 'New Rochelle\'s renaissance and 26-minute Manhattan commute are attracting buyers with significant budgets — RealtorFinder gives you early access to sellers in this revitalized market.',
    },
    {
        slug: 'mount-vernon',
        name: 'Mount Vernon',
        county: 'Westchester',
        state: 'NY',
        zip: '10550',
        population: '68,000',
        median_price: '$419,000',
        price_trend: 'up 9%',
        avg_dom: 26,
        description: 'Mount Vernon is Westchester\'s most affordable entry point — a densely populated city that borders the Bronx with Metro-North service and a wide range of housing from historic Victorians to modern condominiums, drawing first-time buyers and NYC residents seeking more space on a realistic budget.',
        neighborhoods: 'Fleetwood, Eastchester Road corridor, South Side, Midland Avenue, Mount Vernon Heights',
        nearby: 'Yonkers, Bronxville, Pelham, New Rochelle, Eastchester',
        seller_hook: 'Mount Vernon\'s affordability draws serious first-time buyers from NYC in force — let competing Westchester agents on RealtorFinder bring the best buyers to your home.',
        realtor_hook: 'Mount Vernon\'s position as Westchester\'s most affordable market keeps buyer demand high and listing volume strong — RealtorFinder connects you with motivated sellers here.',
    },
    {
        slug: 'schenectady',
        name: 'Schenectady',
        county: 'Schenectady',
        state: 'NY',
        zip: '12301',
        population: '67,000',
        median_price: '$179,000',
        price_trend: 'up 10%',
        avg_dom: 23,
        description: 'Schenectady is the Capital Region\'s most affordable and rapidly improving city — a former GE manufacturing hub that has reinvented itself around Proctors Theatre, a revitalized downtown, and the SUNY Schenectady campus, with home prices that make it one of the best-value real estate markets in New York State.',
        neighborhoods: 'Stockade Historic District, Mont Pleasant, Hamilton Hill, Bellevue, GE Realty Plot, Union Street',
        nearby: 'Albany, Rotterdam, Niskayuna, Glenville, Scotia',
        seller_hook: 'Schenectady\'s 10% appreciation and revitalized downtown are drawing buyers across the Capital Region — let competing agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Schenectady\'s affordability and rapid improvement make it a high-opportunity market for focused agents — RealtorFinder connects you with motivated sellers in the Capital Region.',
    },
    {
        slug: 'utica',
        name: 'Utica',
        county: 'Oneida',
        state: 'NY',
        zip: '13501',
        population: '60,000',
        median_price: '$129,000',
        price_trend: 'up 11%',
        avg_dom: 25,
        description: 'Utica is central New York\'s most affordable market and a compelling story of revitalization — a city with a rich immigrant heritage, a growing refugee resettlement community, and home prices so low that investors and first-time buyers are arriving from across the state to capture appreciating assets before prices fully recover.',
        neighborhoods: 'Cornhill, Roscoe Conkling Park area, East Utica, South Utica, New Hartford border, Proctor Park',
        nearby: 'Rome, New Hartford, Marcy, Whitesboro, Herkimer',
        seller_hook: 'Utica\'s 11% appreciation and rising investor and first-time buyer interest make now an excellent time to sell — RealtorFinder puts competitive local agents in a bidding war to represent your home.',
        realtor_hook: 'Utica\'s sub-$130K entry point and strong appreciation signal one of upstate New York\'s best-value opportunity markets — RealtorFinder connects you with sellers before the market peaks.',
    },
];
