// cities/ny.js — New York state city data for SEO landing pages

module.exports = [
    {
        slug: 'new-york-city',
        name: 'New York City',
        county: 'New York (Manhattan)',
        state: 'NY',
        zip: '10001',
        population: '8,336,000',
        median_price: '$795,000',
        price_trend: 'up 6%',
        avg_dom: 62,
        description: 'New York City is the world\'s preeminent real estate market — a 302-square-mile metropolis of 8.3 million anchored by Manhattan\'s global finance, media, and tech economy, with five boroughs offering wildly different price points, neighborhood characters, and lifestyles from Wall Street to Flushing to Jamaica Bay.',
        neighborhoods: 'Upper West Side, Tribeca, Harlem, Astoria, Park Slope, Williamsburg, Riverdale, Stapleton',
        nearby: 'Yonkers, Fort Lee NJ, Newark NJ, Jersey City NJ, White Plains',
        seller_hook: 'New York City\'s global buyer pool is unlike any other market — let the most competitive agents on RealtorFinder fight to earn the commission on your biggest asset.',
        realtor_hook: 'New York City listings command some of the highest commissions in the country — RealtorFinder connects you with motivated sellers across all five boroughs.',
    },
    {
        slug: 'brooklyn',
        name: 'Brooklyn',
        county: 'Kings',
        state: 'NY',
        zip: '11201',
        population: '2,736,000',
        median_price: '$875,000',
        price_trend: 'up 7%',
        avg_dom: 55,
        description: 'Brooklyn is New York City\'s most populous and culturally vibrant borough — a patchwork of distinct neighborhoods from the brownstone streets of Park Slope and Brooklyn Heights to the waterfront reinvention of DUMBO and Red Hook, with strong appreciation driven by Manhattan overflow buyers and a fiercely loyal local buyer culture.',
        neighborhoods: 'Park Slope, DUMBO, Williamsburg, Bushwick, Brooklyn Heights, Bay Ridge, Crown Heights, Flatbush',
        nearby: 'Manhattan, Queens, Staten Island, Hoboken NJ, Jersey City NJ',
        seller_hook: 'Brooklyn\'s global reputation and consistent buyer demand ensure fierce competition for every listing — put that competition to work for you with RealtorFinder.',
        realtor_hook: 'Brooklyn\'s mix of luxury brownstones and emerging neighborhoods creates listing opportunities at every price point — RealtorFinder connects you with sellers across Kings County.',
    },
    {
        slug: 'queens',
        name: 'Queens',
        county: 'Queens',
        state: 'NY',
        zip: '11354',
        population: '2,405,000',
        median_price: '$749,000',
        price_trend: 'up 7%',
        avg_dom: 52,
        description: 'Queens is New York City\'s most ethnically diverse borough and one of its most active real estate markets — a vast borough stretching from the Long Island City waterfront to the attached-home streetscapes of Bayside and the detached single-family neighborhoods of Forest Hills and Jamaica, offering Manhattan access at meaningfully lower prices.',
        neighborhoods: 'Astoria, Long Island City, Forest Hills, Flushing, Jamaica, Bayside, Jackson Heights, Ridgewood',
        nearby: 'Brooklyn, Manhattan, Nassau County, Bronx, Newark NJ',
        seller_hook: 'Queens\' diversity of buyers — from first-timers to investors to Manhattan relocators — means strong competition for your home; let RealtorFinder agents compete to deliver it.',
        realtor_hook: 'Queens\' sheer size and buyer diversity generate one of New York\'s highest volumes of residential transactions — RealtorFinder connects you with motivated sellers borough-wide.',
    },
    {
        slug: 'staten-island',
        name: 'Staten Island',
        county: 'Richmond',
        state: 'NY',
        zip: '10301',
        population: '495,000',
        median_price: '$635,000',
        price_trend: 'up 8%',
        avg_dom: 35,
        description: 'Staten Island is New York City\'s most suburban borough — a largely single-family landscape of tree-lined streets, generous lot sizes, and strong community identity, favored by city workers and families seeking detached homes with yards at prices well below comparable Brooklyn and Queens properties, with Goethals Bridge access to New Jersey and ferry service to lower Manhattan.',
        neighborhoods: 'St. George, Tottenville, Annadale, Great Kills, New Dorp, Willowbrook, Stapleton, Sunnyside',
        nearby: 'Bayonne NJ, Perth Amboy NJ, Brooklyn, Elizabeth NJ',
        seller_hook: 'Staten Island\'s family buyer demand and NYC boroughs context keep competition strong — let top Richmond County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Staten Island\'s steady family market and sub-$650K median for NYC homes create a consistent flow of listings — RealtorFinder connects you with sellers here.',
    },
    {
        slug: 'yonkers',
        name: 'Yonkers',
        county: 'Westchester',
        state: 'NY',
        zip: '10701',
        population: '211,000',
        median_price: '$479,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Yonkers is Westchester County\'s largest city and most affordable gateway — a dense, transit-connected Hudson River city with Metro-North service to Grand Central in under 30 minutes, attracting NYC buyers priced out of the boroughs and offering a wide range of housing from historic multi-families to new waterfront condominiums.',
        neighborhoods: 'Southwest Yonkers, Park Hill, Nodine Hill, Dunwoodie, Wakefield, Nepperhan, Riverdale border',
        nearby: 'Bronxville, Hastings-on-Hudson, Mount Vernon, White Plains, Eastchester',
        seller_hook: 'Yonkers\' Metro-North access draws NYC buyer overflow that competes fiercely for every listing — put realtors in a bidding war on RealtorFinder to earn your business.',
        realtor_hook: 'Yonkers\' affordability relative to NYC and 30-minute commute generate strong, consistent buyer demand — RealtorFinder gives you first access to sellers in Westchester\'s largest city.',
    },
    {
        slug: 'white-plains',
        name: 'White Plains',
        county: 'Westchester',
        state: 'NY',
        zip: '10601',
        population: '59,000',
        median_price: '$569,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'White Plains is Westchester County\'s downtown hub — a walkable, transit-rich city with a thriving restaurant and retail scene, express Metro-North service to Grand Central in 33 minutes, and a condominium and townhome market that draws NYC buyers seeking suburban convenience without suburban isolation.',
        neighborhoods: 'Downtown White Plains, Gedney Farms, Battle Hill, North White Plains, Fisher Hill',
        nearby: 'Scarsdale, Harrison, Greenburgh, Tarrytown, Yonkers',
        seller_hook: 'White Plains\' express train access and walkable downtown command strong buyer attention — let top Westchester agents compete on RealtorFinder to represent your home.',
        realtor_hook: 'White Plains\' urban amenities and Metro-North express service make it the most in-demand transit hub in Westchester — RealtorFinder connects you with sellers in this active market.',
    },
    {
        slug: 'new-rochelle',
        name: 'New Rochelle',
        county: 'Westchester',
        state: 'NY',
        zip: '10801',
        population: '84,000',
        median_price: '$609,000',
        price_trend: 'up 8%',
        avg_dom: 23,
        description: 'New Rochelle is experiencing a dramatic downtown renaissance, with a wave of new mixed-use development, Metro-North access to Grand Central in 26 minutes, and a diverse, established residential community that draws buyers seeking Sound Shore lifestyle within easy commuting range of Manhattan.',
        neighborhoods: 'Downtown New Rochelle, Wykagyl, Beechmont, Sutton Manor, Huguenot Park, Pelham border',
        nearby: 'Pelham, Mamaroneck, Larchmont, Mount Vernon, Scarsdale',
        seller_hook: 'New Rochelle\'s downtown revival and fast train access are generating serious buyer competition — RealtorFinder puts top Sound Shore agents in a race to win your listing.',
        realtor_hook: 'New Rochelle\'s renaissance and 26-minute Manhattan commute attract buyers with significant budgets — RealtorFinder gives you early access to sellers in this revitalized market.',
    },
    {
        slug: 'mount-vernon',
        name: 'Mount Vernon',
        county: 'Westchester',
        state: 'NY',
        zip: '10550',
        population: '68,000',
        median_price: '$429,000',
        price_trend: 'up 9%',
        avg_dom: 26,
        description: 'Mount Vernon is Westchester\'s most affordable entry point — a densely populated city bordering the Bronx with Metro-North service and a wide range of housing from historic Victorians to modern condominiums, drawing first-time buyers and NYC residents seeking more space on a realistic budget.',
        neighborhoods: 'Fleetwood, Eastchester Road corridor, South Side, Midland Avenue, Mount Vernon Heights',
        nearby: 'Yonkers, Bronxville, Pelham, New Rochelle, Eastchester',
        seller_hook: 'Mount Vernon\'s affordability draws serious first-time buyers from NYC in force — let competing Westchester agents on RealtorFinder bring the best buyers to your home.',
        realtor_hook: 'Mount Vernon\'s position as Westchester\'s most affordable market keeps buyer demand high and listing volume strong — RealtorFinder connects you with motivated sellers here.',
    },
    {
        slug: 'scarsdale',
        name: 'Scarsdale',
        county: 'Westchester',
        state: 'NY',
        zip: '10583',
        population: '18,000',
        median_price: '$1,350,000',
        price_trend: 'up 6%',
        avg_dom: 38,
        description: 'Scarsdale is Westchester County\'s most prestigious residential address — a village of gracious Tudor and colonial estates on wooded lots, nationally ranked public schools, and an express Metro-North commute to Grand Central in 31 minutes, consistently attracting high-earning Manhattan professionals seeking the definitive New York suburb.',
        neighborhoods: 'Scarsdale Village, Edgewood, Greenacres, Fox Meadow, Murray Hill, Quaker Ridge',
        nearby: 'White Plains, Hartsdale, Eastchester, New Rochelle, Larchmont',
        seller_hook: 'Scarsdale\'s elite reputation and top schools attract the most qualified buyers in Westchester — let RealtorFinder\'s competitive agents maximize the premium your home commands.',
        realtor_hook: 'Scarsdale listings represent some of the highest commissions in New York State — RealtorFinder connects you with motivated sellers in this trophy-home market.',
    },
    {
        slug: 'rye',
        name: 'Rye',
        county: 'Westchester',
        state: 'NY',
        zip: '10580',
        population: '16,000',
        median_price: '$1,250,000',
        price_trend: 'up 6%',
        avg_dom: 40,
        description: 'Rye is a charming waterfront city on Long Island Sound — a community of stunning colonials and Tudors with a vibrant downtown, award-winning public schools, direct Metro-North access to Grand Central in 46 minutes, and a Sound Shore lifestyle that commands a significant premium over inland Westchester communities.',
        neighborhoods: 'Rye City, Rye Neck, Port Chester border, Milton Harbor, Rye Playland area',
        nearby: 'Port Chester, Harrison, Mamaroneck, Greenwich CT, Larchmont',
        seller_hook: 'Rye\'s waterfront character and top schools attract motivated buyers from across the NYC metro — put competing Sound Shore agents on RealtorFinder to work for your sale.',
        realtor_hook: 'Rye\'s desirable waterfront location and high median price make it one of Westchester\'s most lucrative markets for focused agents — RealtorFinder connects you with sellers here.',
    },
    {
        slug: 'harrison-ny',
        name: 'Harrison',
        county: 'Westchester',
        state: 'NY',
        zip: '10528',
        population: '28,000',
        median_price: '$979,000',
        price_trend: 'up 7%',
        avg_dom: 32,
        description: 'Harrison is a dual-community Westchester town — the incorporated Village of Harrison offers large-lot estates and top public schools, while the hamlet of Purchase is home to corporate headquarters including PepsiCo and MasterCard, creating a unique market of executive buyers drawn by proximity to both Manhattan and Fortune 500 employers.',
        neighborhoods: 'Harrison Village, Purchase, West Harrison, Harrison Hills, Blind Brook area',
        nearby: 'Rye, Port Chester, White Plains, Mamaroneck, Greenwich CT',
        seller_hook: 'Harrison\'s corporate campus neighbors and executive buyer pool create premium demand — let RealtorFinder\'s competing agents earn the right to represent your home.',
        realtor_hook: 'Harrison\'s corporate headquarters proximity and strong school ratings attract high-budget executive buyers — RealtorFinder connects you with motivated sellers in this premium market.',
    },
    {
        slug: 'port-chester',
        name: 'Port Chester',
        county: 'Westchester',
        state: 'NY',
        zip: '10573',
        population: '29,000',
        median_price: '$549,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Port Chester is one of Westchester\'s most vibrant and affordable villages — a culturally diverse community with a nationally recognized restaurant row, Metro-North access to Grand Central in 46 minutes, and a mix of condominiums, co-ops, and single-family homes that draw buyers priced out of neighboring Greenwich and Rye.',
        neighborhoods: 'Downtown Port Chester, Lyon Farm, King Street corridor, Bowman Avenue, Byram border',
        nearby: 'Rye, Harrison, Greenwich CT, Mamaroneck, Larchmont',
        seller_hook: 'Port Chester\'s restaurant scene and relative affordability draw hungry buyers from across Westchester — RealtorFinder puts motivated agents in competition to maximize your sale.',
        realtor_hook: 'Port Chester\'s revitalized downtown and Greenwich CT adjacency are attracting buyers with significant budgets — RealtorFinder connects you with motivated sellers in this emerging market.',
    },
    {
        slug: 'ossining',
        name: 'Ossining',
        county: 'Westchester',
        state: 'NY',
        zip: '10562',
        population: '26,000',
        median_price: '$619,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Ossining is a Hudson River village with genuine character — a diverse, hillside community with dramatic river views, a historic downtown, Metro-North express service to Grand Central in 49 minutes, and home values that remain accessible compared to neighboring Briarcliff Manor and Pleasantville.',
        neighborhoods: 'Downtown Ossining, Sparta, Cedar Lane Park, Teatown Lake area, Briarcliff Manor border',
        nearby: 'Briarcliff Manor, Pleasantville, Tarrytown, Croton-on-Hudson, Peekskill',
        seller_hook: 'Ossining\'s river views and Metro-North access attract buyers seeking Westchester value — let competitive agents on RealtorFinder earn your listing in this desirable community.',
        realtor_hook: 'Ossining\'s relative affordability among Metro-North towns keeps buyer demand strong and consistent — RealtorFinder connects you with sellers in this active Hudson River market.',
    },
    {
        slug: 'tarrytown',
        name: 'Tarrytown',
        county: 'Westchester',
        state: 'NY',
        zip: '10591',
        population: '11,000',
        median_price: '$769,000',
        price_trend: 'up 7%',
        avg_dom: 33,
        description: 'Tarrytown is one of the Hudson Valley\'s most storied and picturesque villages — a Washington Irving country of Victorian architecture, dramatic river views, a walkable main street, and Metro-North express service to Grand Central in 38 minutes, drawing buyers who want genuine Hudson River character without sacrificing Manhattan access.',
        neighborhoods: 'Tarrytown Village, Sleepy Hollow border, Warner Library area, Tappan Hill, Patriot\'s Park',
        nearby: 'Sleepy Hollow, Irvington, Dobbs Ferry, White Plains, Ardsley',
        seller_hook: 'Tarrytown\'s storied character and Hudson River views command strong buyer premiums — let competing Westchester agents on RealtorFinder fight to represent your home.',
        realtor_hook: 'Tarrytown\'s historical cachet and express train access draw discerning buyers with substantial budgets — RealtorFinder connects you with motivated sellers in this Hudson Valley gem.',
    },
    {
        slug: 'dobbs-ferry',
        name: 'Dobbs Ferry',
        county: 'Westchester',
        state: 'NY',
        zip: '10522',
        population: '11,000',
        median_price: '$729,000',
        price_trend: 'up 7%',
        avg_dom: 31,
        description: 'Dobbs Ferry is a quintessential Hudson River village — a walkable, architecturally rich community with a beloved main street, panoramic river views, Metro-North express to Grand Central in 40 minutes, and a loyal buyer base of Manhattan professionals seeking a genuine small-town feel without compromising on commute.',
        neighborhoods: 'Downtown Dobbs Ferry, Cedar Street area, Palisade Street, Riverview Manor, Ardsley border',
        nearby: 'Ardsley, Hastings-on-Hudson, Tarrytown, Irvington, Yonkers',
        seller_hook: 'Dobbs Ferry\'s charming downtown and river views create intense buyer competition — RealtorFinder puts top Westchester agents in a bidding war to earn your listing.',
        realtor_hook: 'Dobbs Ferry\'s combination of walkability, river character, and express train access draws buyers willing to pay a premium — RealtorFinder connects you with sellers here.',
    },
    {
        slug: 'bronxville',
        name: 'Bronxville',
        county: 'Westchester',
        state: 'NY',
        zip: '10708',
        population: '6,400',
        median_price: '$1,195,000',
        price_trend: 'up 6%',
        avg_dom: 42,
        description: 'Bronxville is one of New York\'s most exclusive and walkable villages — a beautifully preserved English Tudor streetscape with a nationally ranked school district, a 30-minute Metro-North express to Grand Central, and a Midtown Manhattan proximity that justifies prices rivaling the best Westchester addresses at a fraction of the acreage.',
        neighborhoods: 'Bronxville Village, Lawrence Park West, Sagamore, Cedar Knolls, Tuckahoe border',
        nearby: 'Tuckahoe, Eastchester, Yonkers, Mount Vernon, Scarsdale',
        seller_hook: 'Bronxville\'s elite village status and top schools drive fiercely competitive buyer demand — let RealtorFinder\'s competing agents maximize the full premium your home commands.',
        realtor_hook: 'Bronxville listings represent the highest per-square-foot values in lower Westchester — RealtorFinder connects you with motivated sellers in this ultra-premium market.',
    },
    {
        slug: 'larchmont',
        name: 'Larchmont',
        county: 'Westchester',
        state: 'NY',
        zip: '10538',
        population: '6,500',
        median_price: '$1,050,000',
        price_trend: 'up 6%',
        avg_dom: 36,
        description: 'Larchmont is a jewel of the Sound Shore — a tight-knit, walkable village with a yacht club, beautiful Long Island Sound beaches, an acclaimed Mamaroneck school district, and a Metro-North express to Grand Central in 34 minutes that makes it one of the most desirable and competitive commuter markets in all of Westchester.',
        neighborhoods: 'Larchmont Village, Manor Park, Murray Avenue corridor, Horseshoe Harbor, Mamaroneck border',
        nearby: 'Mamaroneck, New Rochelle, Rye, Scarsdale, Port Chester',
        seller_hook: 'Larchmont\'s waterfront access and village prestige generate among the most competitive buyer pools in Westchester — RealtorFinder puts top agents in competition for your listing.',
        realtor_hook: 'Larchmont\'s Sound Shore lifestyle and seven-figure median attract buyers who move quickly when the right home appears — RealtorFinder connects you with motivated sellers in this premium village.',
    },
    {
        slug: 'mamaroneck',
        name: 'Mamaroneck',
        county: 'Westchester',
        state: 'NY',
        zip: '10543',
        population: '19,000',
        median_price: '$869,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Mamaroneck is a diverse, waterfront community encompassing both the Town and Village — a Sound Shore community with two Metro-North stations, celebrated harbor access, strong public schools, and a mix of historic colonials and condominiums that draw buyers seeking Larchmont-caliber amenities at slightly more accessible prices.',
        neighborhoods: 'Mamaroneck Village, Harbor Island Park area, Orienta Point, Fenimore Road, Larchmont border',
        nearby: 'Larchmont, Rye, New Rochelle, Port Chester, Scarsdale',
        seller_hook: 'Mamaroneck\'s harbor and school reputation attract buyers from across the Sound Shore — let competing local agents on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Mamaroneck\'s waterfront character and strong schools drive consistent high-value buyer demand — RealtorFinder connects you with sellers in one of Westchester\'s most active markets.',
    },
    {
        slug: 'great-neck',
        name: 'Great Neck',
        county: 'Nassau',
        state: 'NY',
        zip: '11021',
        population: '10,000',
        median_price: '$849,000',
        price_trend: 'up 7%',
        avg_dom: 34,
        description: 'Great Neck is one of Long Island\'s most prestigious and internationally recognized addresses — a North Shore peninsula community with acclaimed public schools, diverse cultural amenities, LIRR service to Penn Station in 35 minutes, and a vibrant downtown that makes it the premier destination for buyers seeking Gold Coast character with Manhattan commuter access.',
        neighborhoods: 'Great Neck Plaza, Great Neck Estates, Kings Point, Saddle Rock, Kensington, Russell Gardens',
        nearby: 'Manhasset, Roslyn, Port Washington, Mineola, Garden City',
        seller_hook: 'Great Neck\'s global reputation and top schools create buyer competition from across the NYC metro — let RealtorFinder\'s competing agents maximize what your home is truly worth.',
        realtor_hook: 'Great Neck\'s international buyer pool and strong school ratings generate intense competition for every listing — RealtorFinder connects you with motivated sellers on the North Shore.',
    },
    {
        slug: 'garden-city',
        name: 'Garden City',
        county: 'Nassau',
        state: 'NY',
        zip: '11530',
        population: '22,000',
        median_price: '$899,000',
        price_trend: 'up 7%',
        avg_dom: 32,
        description: 'Garden City is one of Long Island\'s most elegant planned communities — a village of wide boulevards, brick colonials, and Tudor architecture, with nationally ranked schools, the Roosevelt Field retail corridor, and LIRR service to Penn Station in 40 minutes, consistently ranking among the most sought-after suburban addresses in Nassau County.',
        neighborhoods: 'Garden City South, Cathedral Avenue corridor, Clinton Road area, Adelphi University vicinity, Stewart Manor border',
        nearby: 'Mineola, Hempstead, Westbury, Uniondale, Carle Place',
        seller_hook: 'Garden City\'s historic character and top schools drive fierce competition for every listing — put the best Nassau County agents in a bidding war on RealtorFinder to represent your home.',
        realtor_hook: 'Garden City\'s elite reputation and consistent buyer demand make it one of Nassau County\'s most lucrative markets — RealtorFinder connects you with motivated sellers in this sought-after village.',
    },
    {
        slug: 'hempstead',
        name: 'Hempstead',
        county: 'Nassau',
        state: 'NY',
        zip: '11550',
        population: '58,000',
        median_price: '$519,000',
        price_trend: 'up 9%',
        avg_dom: 26,
        description: 'Hempstead is Nassau County\'s most populous village — a diverse, affordable community with LIRR service to Penn Station in 45 minutes, Hofstra University, a large municipal infrastructure, and home values that draw buyers priced out of more expensive Nassau suburbs while still offering full Long Island commuter access.',
        neighborhoods: 'Hempstead Village, Roosevelt, West Hempstead border, Lakeview, Uniondale adjacent',
        nearby: 'Garden City, Uniondale, Valley Stream, Elmont, Franklin Square',
        seller_hook: 'Hempstead\'s affordability and LIRR access attract strong first-time and move-up buyer demand — let competitive Nassau County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Hempstead\'s volume market and steady 9% appreciation create strong listing opportunities for active agents — RealtorFinder connects you with motivated sellers across Nassau County.',
    },
    {
        slug: 'babylon',
        name: 'Babylon',
        county: 'Suffolk',
        state: 'NY',
        zip: '11702',
        population: '12,500',
        median_price: '$629,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Babylon Village is one of the South Shore\'s most desirable addresses — a walkable village on the Great South Bay with a charming main street, Fire Island ferry access, boating culture, and LIRR service to Penn Station in 55 minutes, drawing buyers who want authentic South Shore character with year-round lifestyle appeal.',
        neighborhoods: 'Babylon Village, West Babylon, North Babylon, Wyandanch, Lindenhurst border',
        nearby: 'Bay Shore, Lindenhurst, Islip, West Islip, Amityville',
        seller_hook: 'Babylon\'s bay access and village character command buyer premiums across the South Shore — let competing realtors on RealtorFinder fight to earn the right to sell your home.',
        realtor_hook: 'Babylon\'s desirable waterfront lifestyle and consistent buyer demand create a strong, active listing market — RealtorFinder connects you with motivated sellers on the South Shore.',
    },
    {
        slug: 'islip',
        name: 'Islip',
        county: 'Suffolk',
        state: 'NY',
        zip: '11751',
        population: '18,000',
        median_price: '$619,000',
        price_trend: 'up 8%',
        avg_dom: 29,
        description: 'Islip is a classic South Shore community anchored by Great South Bay waterfront, Fire Island ferry service, MacArthur Airport, and a range of neighborhoods from bayfront estates to modest ranch homes, offering buyers authentic Long Island South Shore lifestyle at prices well below those of the North Shore and Nassau County Gold Coast.',
        neighborhoods: 'Islip Village, East Islip, Bay Shore, West Islip, Central Islip, Brightwaters',
        nearby: 'Babylon, Bohemia, Brentwood, Oakdale, Sayville',
        seller_hook: 'Islip\'s South Shore waterfront draws motivated buyers from across Long Island — RealtorFinder puts competitive local agents in a bidding war to maximize your sale.',
        realtor_hook: 'Islip Town\'s large geographic footprint and diverse submarkets generate consistent listing volume — RealtorFinder connects you with motivated sellers across this active South Shore territory.',
    },
    {
        slug: 'smithtown',
        name: 'Smithtown',
        county: 'Suffolk',
        state: 'NY',
        zip: '11787',
        population: '26,000',
        median_price: '$649,000',
        price_trend: 'up 7%',
        avg_dom: 27,
        description: 'Smithtown is one of Suffolk County\'s most family-oriented communities — a well-established North Shore town with highly rated public schools, quiet residential neighborhoods of colonials and split-levels, and LIRR service to Penn Station in about an hour, making it a perennial favorite for families seeking Long Island quality at a realistic price.',
        neighborhoods: 'Smithtown Center, Kings Park, Commack, Hauppauge, Nesconset, St. James',
        nearby: 'Huntington, Hauppauge, Brentwood, Lake Grove, Setauket',
        seller_hook: 'Smithtown\'s top schools and family reputation create strong, consistent buyer competition — let the best Suffolk County agents on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Smithtown\'s school reputation and steady family demand generate reliable listing volume for active agents — RealtorFinder connects you with motivated sellers across this North Shore community.',
    },
    {
        slug: 'huntington',
        name: 'Huntington',
        county: 'Suffolk',
        state: 'NY',
        zip: '11743',
        population: '33,000',
        median_price: '$699,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Huntington Village is Suffolk County\'s most vibrant downtown — a lively main street of restaurants, music venues, and boutiques on the North Shore, paired with strong public schools, Cold Spring Harbor waterfront access, and LIRR service to Penn Station in about an hour, making it one of Long Island\'s most attractive and complete communities.',
        neighborhoods: 'Huntington Village, Cold Spring Harbor border, Centerport, Greenlawn, Halesite, Dix Hills',
        nearby: 'Melville, Syosset, Smithtown, Northport, Lloyd Harbor',
        seller_hook: 'Huntington\'s lively village and North Shore character attract buyers who compete hard for every listing — RealtorFinder puts top Suffolk County agents in competition to earn your business.',
        realtor_hook: 'Huntington\'s combination of vibrant downtown, top schools, and waterfront access drives one of Suffolk County\'s strongest luxury markets — RealtorFinder connects you with sellers here.',
    },
    {
        slug: 'syosset',
        name: 'Syosset',
        county: 'Nassau',
        state: 'NY',
        zip: '11791',
        population: '19,000',
        median_price: '$839,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Syosset is one of Nassau County\'s top school districts and most consistently sought-after communities — a suburban gem of colonials and expanded ranches anchored by one of Long Island\'s highest-performing high schools, with LIRR service to Penn Station in 50 minutes and a dedicated buyer base of families who pursue Syosset school addresses specifically.',
        neighborhoods: 'Syosset Center, Woodbury border, Cold Spring Harbor border, South Syosset, Berry Hill',
        nearby: 'Woodbury, Jericho, Oyster Bay, Plainview, Huntington',
        seller_hook: 'Syosset\'s top-ranked schools drive fiercely competitive demand — let RealtorFinder put the most motivated Nassau County agents in competition for the right to list your home.',
        realtor_hook: 'Syosset\'s school reputation creates a self-selecting, highly motivated buyer pool that pays a premium — RealtorFinder connects you with sellers in one of Long Island\'s most desirable addresses.',
    },
    {
        slug: 'manhasset',
        name: 'Manhasset',
        county: 'Nassau',
        state: 'NY',
        zip: '11030',
        population: '8,000',
        median_price: '$1,195,000',
        price_trend: 'up 6%',
        avg_dom: 38,
        description: 'Manhasset is a prestigious North Shore hamlet anchored by the Miracle Mile luxury shopping district, one of New York\'s most celebrated school systems, and a community of grand colonials and Tudors with LIRR service to Penn Station in 35 minutes — a perennial destination for high-earning Manhattan professionals seeking a world-class suburban address.',
        neighborhoods: 'Manhasset Hills, Munsey Park, Strathmore, Plandome, Flower Hill, Searingtown',
        nearby: 'Great Neck, Roslyn, Port Washington, Williston Park, Mineola',
        seller_hook: 'Manhasset\'s elite schools and Miracle Mile cachet command seven-figure prices with motivated buyers — let competing top-tier agents on RealtorFinder maximize your sale.',
        realtor_hook: 'Manhasset\'s prestige address and international buyer interest generate some of Nassau County\'s highest commissions — RealtorFinder connects you with motivated sellers in this trophy market.',
    },
    {
        slug: 'buffalo',
        name: 'Buffalo',
        county: 'Erie',
        state: 'NY',
        zip: '14201',
        population: '276,000',
        median_price: '$229,000',
        price_trend: 'up 12%',
        avg_dom: 19,
        description: 'Buffalo is one of the most dramatically improving real estate markets in the Northeast — a revitalized lakefront city with stunning architecture, a booming food and arts scene, and home prices that make it one of the most affordable major cities in the eastern US, drawing investors and first-time buyers who recognize a market in sustained transformation.',
        neighborhoods: 'Elmwood Village, Allentown, Delaware Avenue, Hertel Avenue, South Buffalo, Black Rock, North Park, Kenmore border',
        nearby: 'Cheektowaga, Amherst, Tonawanda, Lackawanna, West Seneca',
        seller_hook: 'Buffalo\'s renaissance is driving 12% annual appreciation — let top Western New York realtors compete on RealtorFinder to maximize your sale price.',
        realtor_hook: 'Buffalo\'s rapid appreciation and affordable entry points are pulling buyers from across the region — RealtorFinder connects you with sellers in one of the Northeast\'s hottest turnaround markets.',
    },
    {
        slug: 'amherst',
        name: 'Amherst',
        county: 'Erie',
        state: 'NY',
        zip: '14226',
        population: '122,000',
        median_price: '$289,000',
        price_trend: 'up 9%',
        avg_dom: 21,
        description: 'Amherst is Western New York\'s most sought-after suburb — a large, well-managed town with top-ranked schools, the University at Buffalo\'s North Campus, the Williamsville East School District, and a wide range of housing from affordable starter homes to executive estates that draws families from across the Buffalo metro.',
        neighborhoods: 'Williamsville, Snyder, Eggertsville, Getzville, Clarence border, University District',
        nearby: 'Buffalo, Cheektowaga, Clarence, Tonawanda, Lockport',
        seller_hook: 'Amherst\'s top schools and suburban reputation drive fierce buyer competition throughout Erie County — let RealtorFinder\'s competing agents earn the right to represent your home.',
        realtor_hook: 'Amherst is the Buffalo metro\'s most active suburban market with consistent demand across all price points — RealtorFinder connects you with motivated sellers throughout this large town.',
    },
    {
        slug: 'cheektowaga',
        name: 'Cheektowaga',
        county: 'Erie',
        state: 'NY',
        zip: '14225',
        population: '75,000',
        median_price: '$199,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'Cheektowaga is Erie County\'s most affordable first-mover suburb — a dense, blue-collar community directly adjacent to Buffalo with Buffalo Niagara International Airport, strong city services, modest but well-maintained housing stock, and some of the lowest entry prices of any western New York suburb within easy reach of downtown Buffalo.',
        neighborhoods: 'Depew border, Sloan, Maryvale, Cheektowaga Center, Allentown adjacent, Cayuga Road corridor',
        nearby: 'Buffalo, Amherst, Depew, Lancaster, West Seneca',
        seller_hook: 'Cheektowaga\'s affordability and airport proximity draw buyers from across the Buffalo metro — let competitive Erie County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Cheektowaga\'s high transaction volume and consistent first-time buyer demand make it a reliable listing source in Western New York — RealtorFinder connects you with sellers here.',
    },
    {
        slug: 'rochester-ny',
        name: 'Rochester',
        county: 'Monroe',
        state: 'NY',
        zip: '14601',
        population: '211,000',
        median_price: '$199,000',
        price_trend: 'up 11%',
        avg_dom: 20,
        description: 'Rochester is western New York\'s cultural and educational hub — home to the University of Rochester, RIT, and a thriving medical sector — with home prices among the lowest of any major northeastern city and an appreciation rate that signals a market the rest of the country is starting to notice.',
        neighborhoods: 'Park Avenue, South Wedge, Corn Hill, East End, Beechwood, Swillburg, Monroe Avenue corridor',
        nearby: 'Brighton, Pittsford, Webster, Irondequoit, Greece',
        seller_hook: 'Rochester\'s 11% appreciation and university-driven buyer demand make now a strong time to sell — let competing realtors on RealtorFinder bring you the best offer.',
        realtor_hook: 'Rochester\'s sub-$200K entry point and university-driven demand create high listing volume and fast-moving buyers — RealtorFinder keeps your pipeline full in Monroe County.',
    },
    {
        slug: 'syracuse',
        name: 'Syracuse',
        county: 'Onondaga',
        state: 'NY',
        zip: '13201',
        population: '148,000',
        median_price: '$149,000',
        price_trend: 'up 10%',
        avg_dom: 22,
        description: 'Syracuse is a central New York city in the midst of a genuine economic revival, anchored by Syracuse University, a growing healthcare sector, and proximity to semiconductor manufacturing investment that is transforming the region into a tech hub with dramatically rising real estate values.',
        neighborhoods: 'Armory Square, Strathmore, Westcott, Sedgwick, Hawley-Green, Near Westside, University Hill',
        nearby: 'Fayetteville, Manlius, Clay, Liverpool, Camillus',
        seller_hook: 'Syracuse\'s semiconductor boom and university demand are driving 10% appreciation — RealtorFinder puts motivated local agents in competition to maximize your sale.',
        realtor_hook: 'Syracuse is one of the most undervalued appreciation stories in the Northeast — RealtorFinder connects you with sellers before the broader market catches on.',
    },
    {
        slug: 'albany-ny',
        name: 'Albany',
        county: 'Albany',
        state: 'NY',
        zip: '12201',
        population: '99,000',
        median_price: '$279,000',
        price_trend: 'up 9%',
        avg_dom: 24,
        description: 'The capital of New York State, Albany anchors a growing Capital Region economy fueled by state government, higher education, and an emerging tech sector — with home prices that remain remarkably affordable for a northeastern state capital, and an appreciation rate that reflects increasing recognition from buyers across the Hudson Valley.',
        neighborhoods: 'Center Square, Pine Hills, Arbor Hill, Delaware Avenue, Washington Park, North Albany, Helderberg',
        nearby: 'Schenectady, Troy, Cohoes, Colonie, Guilderland',
        seller_hook: 'Albany\'s government and university buyer pool keeps demand steady year-round — let competitive realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Albany\'s affordable price points and steady state-government buyer demand create consistent listing volume — RealtorFinder connects you with motivated sellers in the Capital Region.',
    },
    {
        slug: 'troy',
        name: 'Troy',
        county: 'Rensselaer',
        state: 'NY',
        zip: '12180',
        population: '50,000',
        median_price: '$239,000',
        price_trend: 'up 10%',
        avg_dom: 25,
        description: 'Troy is one of upstate New York\'s most exciting revitalization stories — a Hudson River city with a spectacular stock of 19th-century brownstones and commercial architecture, a booming craft brewery and arts scene centered on River Street, RPI and Russell Sage College, and home prices that make it one of the Capital Region\'s best-value markets.',
        neighborhoods: 'Downtown Troy, Lansingburgh, South Troy, North Central, Brunswick border, Collar City',
        nearby: 'Albany, Cohoes, Watervliet, Rensselaer, Schenectady',
        seller_hook: 'Troy\'s revitalization and brownstone character draw buyers from across the Capital Region — let competing local agents on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Troy\'s rapid appreciation and architectural renaissance attract a growing buyer base — RealtorFinder connects you with motivated sellers in one of upstate New York\'s most improved markets.',
    },
    {
        slug: 'saratoga-springs',
        name: 'Saratoga Springs',
        county: 'Saratoga',
        state: 'NY',
        zip: '12866',
        population: '29,000',
        median_price: '$479,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'Saratoga Springs is the crown jewel of the Capital Region — a world-famous thoroughbred racing destination with a vibrant year-round downtown on Broadway, nationally celebrated restaurants and arts institutions, Skidmore College, and a real estate market that draws wealthy buyers from NYC and Boston seeking a premier upstate lifestyle.',
        neighborhoods: 'Downtown Saratoga Springs, Geyser Crest, Circular Street, East Side Historic District, Loughberry Lake area',
        nearby: 'Ballston Spa, Malta, Clifton Park, Glens Falls, Albany',
        seller_hook: 'Saratoga Springs\' national profile and affluent buyer pool create premium demand — let the most competitive Capital Region agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Saratoga Springs attracts the Capital Region\'s wealthiest buyers and highest per-transaction commissions — RealtorFinder connects you with motivated sellers in this premier upstate market.',
    },
    {
        slug: 'ithaca',
        name: 'Ithaca',
        county: 'Tompkins',
        state: 'NY',
        zip: '14850',
        population: '32,000',
        median_price: '$339,000',
        price_trend: 'up 8%',
        avg_dom: 27,
        description: 'Ithaca is one of America\'s most distinctive small cities — a steeply gorged, intellectually vibrant college town anchored by Cornell University and Ithaca College, with a fiercely progressive culture, renowned waterfalls and natural beauty, a celebrated food and farm-to-table scene, and a tight real estate market driven by university demand year-round.',
        neighborhoods: 'Collegetown, Belle Sherman, Fall Creek, South Hill, West End, Cayuga Heights, Downtown Ithaca',
        nearby: 'Dryden, Lansing, Trumansburg, Cortland, Watkins Glen',
        seller_hook: 'Ithaca\'s Cornell-driven demand and limited housing supply keep competition strong even in slow seasons — let RealtorFinder\'s competing agents maximize what your home is worth.',
        realtor_hook: 'Ithaca\'s university-anchored demand and constrained inventory create a reliably competitive listing market — RealtorFinder connects you with motivated sellers in this unique upstate gem.',
    },
];
