// cities/oh-extra.js — Additional Ohio city data for SEO landing pages

module.exports = [
    {
        slug: 'akron',
        name: 'Akron',
        county: 'Summit',
        state: 'OH',
        zip: '44308',
        population: '190,000',
        median_price: '$165,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'Akron is the Rubber City reimagined as a polymer and healthcare innovation hub — a Summit County city where the University of Akron, Summa Health System, and a nationally recognized polymer science cluster create housing demand from students and researchers who find some of the Midwest\'s most affordable Craftsman bungalows and mid-century homes in a market with some of Ohio\'s strongest per-square-foot appreciation rates.',
        neighborhoods: 'Highland Square, Fairlawn, Copley, Stow, Bath Township',
        nearby: 'Cuyahoga Falls, Stow, Green, Barberton, Fairlawn',
        seller_hook: 'Akron\'s polymer tech revival and UA enrollment drive fast-moving buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Akron\'s innovation economy and affordable price points create one of Ohio\'s most active listing markets — find sellers through RealtorFinder.',
    },
    {
        slug: 'toledo-oh',
        name: 'Toledo',
        county: 'Lucas',
        state: 'OH',
        zip: '43604',
        population: '270,000',
        median_price: '$145,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Toledo is the Glass City and Northwest Ohio\'s industrial anchor — a Maumee River manufacturing hub where Jeep assembly, Owens Corning, and the University of Toledo create housing demand from auto workers, medical professionals, and students who find some of Ohio\'s and the nation\'s most affordable single-family homes, making Toledo a perennial favorite among investors seeking strong cap rates in the Rust Belt.',
        neighborhoods: 'Ottawa Hills, Sylvania, Perrysburg, Maumee, Waterville',
        nearby: 'Perrysburg, Maumee, Sylvania, Rossford, Monroe MI',
        seller_hook: 'Toledo\'s Jeep manufacturing and UT enrollment drive consistent buyer demand at Ohio\'s most affordable prices — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Toledo\'s industrial economy and cap-rate-friendly prices attract investors and first-time buyers alike — find sellers through RealtorFinder.',
    },
    {
        slug: 'dayton-oh',
        name: 'Dayton',
        county: 'Montgomery',
        state: 'OH',
        zip: '45402',
        population: '137,000',
        median_price: '$150,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'Dayton is Ohio\'s Gem City and the birthplace of aviation — a Wright Brothers legacy city where Wright-Patterson Air Force Base, one of the largest USAF installations in the world, the University of Dayton, and a booming Dayton Children\'s Hospital campus create housing demand from military families, researchers, and students who find stately Craftsman and colonial homes at some of the Midwest\'s most remarkable price-to-quality ratios.',
        neighborhoods: 'Oregon District, Oakwood, Beavercreek, Kettering, Centerville',
        nearby: 'Kettering, Beavercreek, Centerville, Huber Heights, Miamisburg',
        seller_hook: 'Dayton\'s WPAFB community and UD enrollment create consistent buyer demand at remarkable prices — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Dayton\'s military and university market generate strong listing activity at Ohio\'s most undervalued prices — find sellers through RealtorFinder.',
    },
    {
        slug: 'canton-oh',
        name: 'Canton',
        county: 'Stark',
        state: 'OH',
        zip: '44702',
        population: '70,000',
        median_price: '$145,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Canton is the Pro Football Hall of Fame city and Stark County\'s historic manufacturing hub — a community where Timken steel bearing manufacturing, Aultman and Mercy Medical hospitals, and an adjacent suburban corridor in North Canton create affordable housing demand from manufacturing workers, medical professionals, and investors seeking Ohio investment properties with cap rates rarely found in major metro markets.',
        neighborhoods: 'Plain Township, North Canton, Massillon, Louisville, Alliance',
        nearby: 'Massillon, North Canton, Alliance, Louisville, Akron',
        seller_hook: 'Canton\'s manufacturing economy and Hall of Fame prestige attract consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Canton\'s industrial market and Stark County affordability create consistent listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'youngstown-oh',
        name: 'Youngstown',
        county: 'Mahoning',
        state: 'OH',
        zip: '44503',
        population: '60,000',
        median_price: '$95,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Youngstown is the Mahoning Valley\'s steel legacy city and a Youngstown State University community undergoing an arts-driven rebirth — where YSU\'s Penguins culture, Youngstown Business Incubator\'s national reputation, and home prices that are among the lowest of any US city with a university create extraordinary investment opportunities for buyers who see the value in historically underpriced Craftsman and brick colonial neighborhoods.',
        neighborhoods: 'Boardman, Canfield, Poland, Austintown, Niles',
        nearby: 'Boardman, Struthers, Campbell, Warren, Niles',
        seller_hook: 'Youngstown\'s YSU enrollment and arts revival attract value-seeking buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Youngstown\'s investment-grade prices and university market create unique listing opportunities in the Mahoning Valley — find sellers through RealtorFinder.',
    },
];
