// cities/oh-extra.js — Additional Ohio city data for SEO landing pages
// Base oh.js already covers: Columbus metro, Cleveland metro, Cincinnati metro,
// Akron, Fairlawn, Hudson, Fairborn, Beavercreek, Dayton

module.exports = [
    {
        slug: 'toledo-oh',
        name: 'Toledo',
        county: 'Lucas',
        state: 'OH',
        zip: '43604',
        population: '270,000',
        median_price: '$145,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Toledo is the Glass City and Northwest Ohio\'s industrial anchor — a Maumee River manufacturing hub where Jeep assembly, Owens Corning, and the University of Toledo create housing demand from auto workers, medical professionals, and students who find some of Ohio\'s and the nation\'s most affordable single-family homes, making Toledo a perennial favorite among investors seeking strong cap rates in the Rust Belt.',
        neighborhoods: 'Ottawa Hills, Sylvania, Perrysburg, Maumee, Waterville',
        nearby: 'Perrysburg, Maumee, Sylvania, Rossford, Monroe MI',
        seller_hook: 'Toledo\'s Jeep manufacturing and UT enrollment drive consistent buyer demand at Ohio\'s most affordable prices — let top agents compete on RealtorFinder.',
        realtor_hook: 'Toledo\'s industrial economy and cap-rate-friendly prices attract investors and first-time buyers alike — find sellers through RealtorFinder.',
    },
    {
        slug: 'canton-oh',
        name: 'Canton',
        county: 'Stark',
        state: 'OH',
        zip: '44702',
        population: '70,000',
        median_price: '$145,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Canton is the Pro Football Hall of Fame city and Stark County\'s historic manufacturing hub — a community where Timken steel bearing manufacturing, Aultman and Mercy Medical hospitals, and an adjacent suburban corridor in North Canton create affordable housing demand from manufacturing workers, medical professionals, and investors seeking Ohio investment properties with cap rates rarely found in major metro markets.',
        neighborhoods: 'Plain Township, North Canton, Massillon, Louisville, Alliance',
        nearby: 'Massillon, North Canton, Alliance, Louisville, Akron',
        seller_hook: 'Canton\'s manufacturing economy and Hall of Fame prestige attract consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Canton\'s industrial market and Stark County affordability create consistent listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'youngstown-oh',
        name: 'Youngstown',
        county: 'Mahoning',
        state: 'OH',
        zip: '44503',
        population: '60,000',
        median_price: '$95,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Youngstown is the Mahoning Valley\'s steel legacy city undergoing an arts-driven rebirth — where Youngstown State University\'s Penguins culture, Youngstown Business Incubator\'s national reputation, and home prices among the lowest of any US city with a university create extraordinary investment opportunities for buyers who see the value in historically underpriced Craftsman and brick colonial neighborhoods.',
        neighborhoods: 'Boardman, Canfield, Poland, Austintown, Niles',
        nearby: 'Boardman, Struthers, Campbell, Warren, Niles',
        seller_hook: 'Youngstown\'s YSU enrollment and arts revival attract value-seeking buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Youngstown\'s investment-grade prices and university market create unique listing opportunities in the Mahoning Valley — find sellers through RealtorFinder.',
    },
    {
        slug: 'zanesville-oh',
        name: 'Zanesville',
        county: 'Muskingum',
        state: 'OH',
        zip: '43701',
        population: '25,000',
        median_price: '$130,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Zanesville is southeastern Ohio\'s Y-Bridge city and Muskingum County\'s arts and manufacturing hub — a Muskingum River community where Ohio University Zanesville, Genesis Healthcare System, and Ohio\'s famous Y-shaped bridge create demand for some of the most affordable Victorian and folk-Victorian homes in the Midwest, with investors and first-time buyers finding exceptional value in a stabilizing Appalachian Ohio market.',
        neighborhoods: 'South Zanesville, Roseville, Nashport, Duncan Falls, Philo',
        nearby: 'Cambridge, Coshocton, McConnelsville, Dresden, Caldwell',
        seller_hook: 'Zanesville\'s Y-Bridge heritage and Ohio University branch campus attract value-seeking buyers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Zanesville\'s Appalachian Ohio affordability and healthcare employment generate consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'mansfield-oh',
        name: 'Mansfield',
        county: 'Richland',
        state: 'OH',
        zip: '44902',
        population: '46,000',
        median_price: '$120,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Mansfield is Richland County\'s north-central Ohio hub and the Shawshank Redemption filming location — a manufacturing city where Ohio State Mansfield, OhioHealth Mansfield Hospital, and Ohio\'s fastest-growing ski resort at Snow Trails create housing demand from first-time buyers, medical workers, and outdoor enthusiasts who find brick four-square and colonial homes at prices that rank among the Midwest\'s most compelling values.',
        neighborhoods: 'Ontario, Lexington, Bellville, Ashland, Shelby',
        nearby: 'Ontario, Lexington, Ashland, Shelby, Galion',
        seller_hook: 'Mansfield\'s Shawshank filming fame and Richland County affordability attract buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Mansfield\'s north-central Ohio market and ultra-affordable prices create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'lima-oh',
        name: 'Lima',
        county: 'Allen',
        state: 'OH',
        zip: '45801',
        population: '37,000',
        median_price: '$115,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Lima is northwestern Ohio\'s industrial city and the Abrams tank production capital of America — a General Dynamics Land Systems and OhioHealth Lima community where military vehicle manufacturing wages, Rhodes State College enrollment, and some of Ohio\'s lowest home prices create a reliable first-time buyer market and strong investor cap rates in a city where federal defense contracts provide unusual employment stability.',
        neighborhoods: 'Elida, Delphos, Spencerville, Shawnee Township, American Township',
        nearby: 'Findlay, Van Wert, Wapakoneta, Celina, Kenton',
        seller_hook: 'Lima\'s General Dynamics defense employment and Ohio affordability attract consistent buyers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Lima\'s defense sector and northwestern Ohio market create listing opportunities at some of Ohio\'s most accessible prices — connect with sellers through RealtorFinder.',
    },
];
