// cities/ok.js — Oklahoma city data for SEO landing pages

module.exports = [
    {
        slug: 'oklahoma-city',
        name: 'Oklahoma City',
        county: 'Oklahoma',
        state: 'OK',
        zip: '73102',
        population: '695,000',
        median_price: '$230,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Oklahoma City is a sprawling Sun Belt metropolis reinvented by oil wealth and an NBA franchise — a city of affordable neighborhoods, a booming Bricktown entertainment district, and energy-sector employment that offers some of the nation\'s best housing value for first-time buyers, growing families, and investors seeking strong cap rates in the south-central United States.',
        neighborhoods: 'Bricktown, Midtown, Paseo, Mesta Park, Nichols Hills, The Village, Edmond, Moore',
        nearby: 'Edmond, Norman, Moore, Midwest City, Del City',
        seller_hook: 'Oklahoma City\'s affordable market and growing economy attract consistent buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Oklahoma City\'s energy economy and first-time buyer volume create high listing activity — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'tulsa',
        name: 'Tulsa',
        county: 'Tulsa',
        state: 'OK',
        zip: '74103',
        population: '415,000',
        median_price: '$210,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Tulsa is Oklahoma\'s second city and an Art Deco gem on the Arkansas River — a revitalized urban core with a thriving aerospace and energy industry, an acclaimed arts district anchored by Philbrook Museum, and neighborhoods like Brookside and Cherry Street offering walkable bungalow living at prices that attract both local buyers and out-of-state investors.',
        neighborhoods: 'Brookside, Cherry Street, Midtown, Pearl District, South Tulsa, Owasso, Broken Arrow',
        nearby: 'Broken Arrow, Owasso, Jenks, Bixby, Sand Springs',
        seller_hook: 'Tulsa\'s affordable prices and revitalized urban core attract a growing buyer pool — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Tulsa\'s arts-district revival and aerospace employment create active listing conditions across a broad price range — find sellers through RealtorFinder.',
    },
    {
        slug: 'norman',
        name: 'Norman',
        county: 'Cleveland',
        state: 'OK',
        zip: '73069',
        population: '128,000',
        median_price: '$240,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Norman is the home of the University of Oklahoma and Oklahoma\'s most vibrant college city — a community where Big 12 football culture, a walkable campus district, the National Weather Center, and steady state government employment anchor an affordable and active real estate market drawing students, faculty, and young families from across the region.',
        neighborhoods: 'Campus Corner, West Main, University North Park, Tudor Hills, Brookhaven',
        nearby: 'Oklahoma City, Moore, Midwest City, Edmond, Lexington',
        seller_hook: 'Norman\'s OU enrollment and university employer base drive consistent buyer demand — let RealtorFinder agents compete for your listing.',
        realtor_hook: 'Norman\'s university market and affordable price points create a steady flow of listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'broken-arrow',
        name: 'Broken Arrow',
        county: 'Tulsa / Wagoner',
        state: 'OK',
        zip: '74012',
        population: '113,000',
        median_price: '$245,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Broken Arrow is Tulsa\'s most populous suburb and one of Oklahoma\'s fastest-growing cities — a family-friendly community with top-ranked schools, an active Rose District entertainment area, strong aerospace and manufacturing employment, and a housing market that consistently outperforms Tulsa County averages in appreciation and days-on-market velocity.',
        neighborhoods: 'Rose District, South Broken Arrow, Lynn Lane, Garnett, Battle Creek',
        nearby: 'Tulsa, Bixby, Owasso, Jenks, Coweta',
        seller_hook: 'Broken Arrow\'s top schools and family buyer demand create competitive listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Broken Arrow\'s consistent appreciation and family buyer volume make it one of eastern Oklahoma\'s best listing markets — find sellers through RealtorFinder.',
    },
    {
        slug: 'edmond',
        name: 'Edmond',
        county: 'Oklahoma',
        state: 'OK',
        zip: '73003',
        population: '96,000',
        median_price: '$315,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Edmond is Oklahoma City\'s most affluent suburb and the preferred address of Oklahoma\'s professional class — a community of tree-lined streets, University of Central Oklahoma, consistently top-ranked public schools, and a tight housing inventory that keeps appreciation strong and multiple-offer situations common among buyers competing for the best homes.',
        neighborhoods: 'Coffee Creek, Waterford, Spring Creek, Sorghum Mill, Deer Creek',
        nearby: 'Oklahoma City, Guthrie, Yukon, Bethany, The Village',
        seller_hook: 'Edmond\'s elite school district and limited inventory create exceptional seller conditions — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Edmond\'s high-income buyer pool and low days-on-market make it OKC\'s most lucrative listing suburb — find sellers through RealtorFinder.',
    },
    {
        slug: 'lawton',
        name: 'Lawton',
        county: 'Comanche',
        state: 'OK',
        zip: '73501',
        population: '92,000',
        median_price: '$155,000',
        price_trend: 'up 3%',
        avg_dom: 40,
        description: 'Lawton is home to Fort Sill, one of the Army\'s largest installations, and is anchored by Cameron University — a military city where VA loans dominate the purchase market, constant soldier rotation creates strong rental demand, and prices among the nation\'s most affordable give investors and first-time buyers exceptional entry-point opportunities.',
        neighborhoods: 'Golf Course Road, Cache Road, Central Lawton, Elgin, Fletcher',
        nearby: 'Duncan, Altus, Chickasha, Anadarko',
        seller_hook: 'Lawton\'s Fort Sill military community creates steady buyer demand year-round — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Lawton\'s military buyer pool and VA loan market create consistent listing and purchase activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'moore-ok',
        name: 'Moore',
        county: 'Cleveland',
        state: 'OK',
        zip: '73160',
        population: '63,000',
        median_price: '$210,000',
        price_trend: 'up 4%',
        avg_dom: 30,
        description: 'Moore is a family-oriented Oklahoma City suburb that rebuilt stronger after devastating tornadoes and emerged with modern housing stock, strong schools, Tinker Air Force Base proximity, and a tight-knit community spirit that makes it consistently popular among military families and OKC-area buyers seeking value south of the interstate.',
        neighborhoods: 'Westmoore, Legacy, Eastern Hills, Indian Hills, Broadmoor',
        nearby: 'Oklahoma City, Norman, Midwest City, Del City, Mustang',
        seller_hook: 'Moore\'s rebuilt housing stock and family buyer base create solid listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Moore\'s Tinker AFB proximity and affordable market drive consistent buyer activity — find listing clients through RealtorFinder.',
    },
    {
        slug: 'owasso',
        name: 'Owasso',
        county: 'Tulsa / Rogers',
        state: 'OK',
        zip: '74055',
        population: '37,000',
        median_price: '$270,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Owasso is Tulsa\'s most sought-after northern suburb — a master-planned community where consistently top-ranked schools, new retail and commercial development along 96th Street, and a safe, family-focused environment attract professionals and young families willing to commute for access to the best public schools in the Tulsa metro.',
        neighborhoods: 'Bailey Ranch, Smith Farm, Camelot Estates, Nottingham, Copper Trails',
        nearby: 'Tulsa, Collinsville, Skiatook, Claremore, Catoosa',
        seller_hook: 'Owasso\'s top-ranked schools and family buyer demand create consistently competitive listing conditions — let agents compete on RealtorFinder.',
        realtor_hook: 'Owasso\'s premium school district and growing family buyer pool make it Tulsa\'s top listing suburb — find sellers through RealtorFinder.',
    },
    {
        slug: 'yukon-ok',
        name: 'Yukon',
        county: 'Canadian',
        state: 'OK',
        zip: '73099',
        population: '28,000',
        median_price: '$235,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Yukon is Oklahoma City\'s fast-growing western suburb — best known as the birthplace of Garth Brooks, it is a family community with strong Mustang and Yukon school districts, proximity to Will Rogers World Airport, and affordable new construction that draws first-time buyers and growing families from across the OKC metro.',
        neighborhoods: 'Mustang, Yukon Hills, Canyon Trails, Chisholm Trail',
        nearby: 'Oklahoma City, Mustang, El Reno, Chickasha',
        seller_hook: 'Yukon\'s western OKC growth and affordable market attract strong buyer demand — let RealtorFinder agents compete for your listing.',
        realtor_hook: 'Yukon\'s growing family market and new construction pipeline create active listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'jenks',
        name: 'Jenks',
        county: 'Tulsa',
        state: 'OK',
        zip: '74037',
        population: '24,000',
        median_price: '$285,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'Jenks is Tulsa\'s premier southern suburb — a "City of Character" on the Arkansas River where the Oklahoma Aquarium, River Spirit Casino, and consistently A-rated public schools create one of the Tulsa metro\'s most desirable residential addresses, with buyers paying a meaningful premium for Jenks school district addresses over neighboring zip codes.',
        neighborhoods: 'Riverside, East Jenks, West Jenks, Riverwalk, Stone Gate',
        nearby: 'Tulsa, Bixby, Glenpool, Sapulpa',
        seller_hook: 'Jenks\' top schools and riverside amenities command premium prices — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Jenks\' school district premium and strong buyer demand make it Tulsa\'s most consistent listing market — find sellers through RealtorFinder.',
    },
];
