// cities/or.js — Oregon city data for SEO landing pages

module.exports = [
    {
        slug: 'portland',
        name: 'Portland',
        county: 'Multnomah',
        state: 'OR',
        zip: '97201',
        population: '652503',
        median_price: '$520,000',
        price_trend: 'up 3%',
        avg_dom: 22,
        description: 'Portland straddles the Willamette River with distinct neighborhoods from the Pearl District\'s converted warehouses and galleries to the bungalow-lined streets of Sellwood and the indie shops of Alberta Arts District. The city\'s economy is anchored by Nike, Intel, and Adidas alongside a thriving food and craft beverage scene. Inner Southeast and North Mississippi Avenue remain perennial draws for buyers seeking walkable urban living.',
        neighborhoods: 'Pearl District, Alberta Arts District, Sellwood, Division Street, Mississippi Avenue',
        nearby: 'Lake Oswego, Beaverton, Gresham',
        seller_hook: 'Portland\'s diverse neighborhood appeal attracts buyers from across the country, and competing realtors drive harder marketing strategies that consistently push final sale prices above list.',
        realtor_hook: 'Portland\'s high transaction volume and consistent buyer demand make it one of the most productive listing markets in the Pacific Northwest.',
    },
    {
        slug: 'lake-oswego',
        name: 'Lake Oswego',
        county: 'Clackamas',
        state: 'OR',
        zip: '97034',
        population: '40850',
        median_price: '$950,000',
        price_trend: 'up 4%',
        avg_dom: 18,
        description: 'Lake Oswego is Portland\'s premier lakefront suburb, built around the private Oswego Lake and a charming village-style downtown with upscale dining and boutiques along A Avenue. Top-rated schools in the Lake Oswego School District and proximity to the South Waterfront corridor make it a magnet for executives and medical professionals. Neighborhoods like First Addition and Westlake feature mid-century modern and craftsman homes on manicured lots.',
        neighborhoods: 'First Addition, Westlake, Lake Grove, Palisades, Iron Mountain',
        nearby: 'Portland, Tualatin, Tigard',
        seller_hook: 'Lake Oswego\'s prestige zip code and lake access rights command premium valuations, and realtor competition here means sellers receive aggressive pricing strategies backed by high-net-worth buyer networks.',
        realtor_hook: 'With median prices near $950K and affluent repeat buyers, Lake Oswego delivers some of the highest per-transaction commissions in the Oregon metro.',
    },
    {
        slug: 'tualatin',
        name: 'Tualatin',
        county: 'Washington',
        state: 'OR',
        zip: '97062',
        population: '27200',
        median_price: '$540,000',
        price_trend: 'up 3%',
        avg_dom: 20,
        description: 'Tualatin sits at the southern edge of the Portland metro where the Tualatin River curves through community parks and the Tualatin Commons waterfront plaza anchors a revitalized town center. Major employers along Nyberg Road and easy I-5 access draw families priced out of Lake Oswego who still want strong schools and suburban amenities. Neighborhoods like Sherwood Hills and Durham offer newer construction at relative value.',
        neighborhoods: 'Tualatin Commons, Sherwood Hills, Durham, Nyberg Woods, Martinazzi',
        nearby: 'Lake Oswego, Tigard, Sherwood',
        seller_hook: 'Tualatin\'s position between two high-demand corridors keeps buyer interest consistently strong, and competing agents bring cross-market buyers from both the Portland core and South Metro.',
        realtor_hook: 'Tualatin\'s rapid turnover and family buyer pool make it an efficient market for realtors looking to build volume without the luxury-market entry barriers of Lake Oswego.',
    },
    {
        slug: 'tigard',
        name: 'Tigard',
        county: 'Washington',
        state: 'OR',
        zip: '97223',
        population: '55767',
        median_price: '$540,000',
        price_trend: 'up 3%',
        avg_dom: 21,
        description: 'Tigard is a densely connected suburb at the junction of Highway 217 and I-5, with Bridgeport Village offering upscale retail and the Fanno Creek Trail system threading through neighborhoods like Bull Mountain and Metzger. The city draws tech workers from the Beaverton-Hillsboro corridor who want more living space and a slightly more established neighborhood feel. Washington Square Mall and easy MAX light rail connections add to Tigard\'s commuter appeal.',
        neighborhoods: 'Bull Mountain, Metzger, Summerfield, Bridgeport, Walnut Grove',
        nearby: 'Beaverton, Lake Oswego, Tualatin',
        seller_hook: 'Tigard\'s location between two of Oregon\'s busiest employment zones means your home reaches buyers from multiple markets, and realtor competition drives creative marketing that fills open houses fast.',
        realtor_hook: 'Tigard\'s broad buyer demographic — from first-timers to downsizing empty nesters — gives realtors consistent pipeline opportunities across multiple price points.',
    },
    {
        slug: 'beaverton',
        name: 'Beaverton',
        county: 'Washington',
        state: 'OR',
        zip: '97005',
        population: '98962',
        median_price: '$560,000',
        price_trend: 'up 4%',
        avg_dom: 19,
        description: 'Beaverton is home to Nike\'s global headquarters and a booming tech corridor along the Sunset Highway that includes Intel, Tektronix, and dozens of semiconductor suppliers. The Beaverton Town Square and Cedar Hills Crossing retail centers serve a diverse, internationally-oriented community with one of the highest concentrations of Asian-American residents in the state. Neighborhoods like Sexton Mountain and Cooper Mountain offer newer construction with valley views.',
        neighborhoods: 'Sexton Mountain, Cooper Mountain, Cedar Hills, Raleigh Hills, Vose',
        nearby: 'Hillsboro, Portland, Tigard',
        seller_hook: 'Beaverton\'s tech-sector buyer pool is deep and well-qualified, and competing realtors leverage corporate relocation networks that regularly produce above-list offers.',
        realtor_hook: 'Beaverton\'s combination of Nike and Intel employment demand, strong school ratings, and high buyer volume makes it one of Washington County\'s most reliable listing markets.',
    },
    {
        slug: 'hillsboro',
        name: 'Hillsboro',
        county: 'Washington',
        state: 'OR',
        zip: '97123',
        population: '106447',
        median_price: '$560,000',
        price_trend: 'up 4%',
        avg_dom: 20,
        description: 'Hillsboro anchors Oregon\'s Silicon Forest with Intel\'s largest campus complex and a growing cluster of semiconductor and clean-tech manufacturers along Cornell Road and the Sunset Corridor. The Historic Downtown Hillsboro district and Jackson Bottom Wetlands Preserve provide community character alongside the rapid growth of neighborhoods like Tanasbourne and Reed\'s Crossing. MAX Blue Line service links Hillsboro directly to Portland in under an hour.',
        neighborhoods: 'Tanasbourne, AmberGlen, Reed\'s Crossing, Reedville, Orenco Station',
        nearby: 'Beaverton, Forest Grove, Cornelius',
        seller_hook: 'Intel\'s continuous hiring cycles bring a steady stream of relocating buyers with strong offers, and realtors competing for Hillsboro listings keep your home in front of corporate relocation programs.',
        realtor_hook: 'Hillsboro\'s Intel-driven relocation demand and rapid new-construction absorption give realtors access to a buyer pipeline that is largely recession-resistant.',
    },
    {
        slug: 'gresham',
        name: 'Gresham',
        county: 'Multnomah',
        state: 'OR',
        zip: '97030',
        population: '113100',
        median_price: '$430,000',
        price_trend: 'up 3%',
        avg_dom: 24,
        description: 'Gresham is Portland\'s largest eastern suburb and Oregon\'s fourth-largest city, with a revitalized downtown Main City Park district, the Springwater Corridor trail, and access to Columbia River Gorge recreation within 20 minutes. The city\'s affordability relative to inner Portland has drawn first-time buyers steadily eastward, supporting strong demand in neighborhoods like Powell Valley and Centennial. Mount Hood Community College and light industrial employment provide economic stability.',
        neighborhoods: 'Powell Valley, Centennial, Pleasant Valley, Rockwood, Historic Downtown',
        nearby: 'Troutdale, Portland, Fairview',
        seller_hook: 'Gresham\'s price point draws the largest pool of pre-approved first-time buyers in the east metro, and competing agents bring buyers who\'ve been outbid in Portland and are highly motivated to close.',
        realtor_hook: 'Gresham\'s volume-friendly price range and high buyer demand from eastward migration make it an excellent market for realtors building a high-transaction-count business.',
    },
    {
        slug: 'troutdale',
        name: 'Troutdale',
        county: 'Multnomah',
        state: 'OR',
        zip: '97060',
        population: '17200',
        median_price: '$440,000',
        price_trend: 'up 2%',
        avg_dom: 26,
        description: 'Troutdale sits at the western gateway to the Columbia River Gorge National Scenic Area, giving residents immediate access to hiking, windsurfing, and waterfall trails while remaining within the Portland metro commute zone. The historic downtown along Historic Columbia River Highway features antique shops and the Harlow House Museum, while newer subdivisions off Buxton Road offer modern construction at approachable prices. Reynolds School District serves the community alongside several charter options.',
        neighborhoods: 'Historic Downtown, Buxton Road, Glenn Otto Park area, Sweetbriar, Arata Creek',
        nearby: 'Gresham, Fairview, Corbett',
        seller_hook: 'Troutdale\'s gorge-gateway lifestyle appeal attracts outdoor-focused buyers who prioritize location over price, making well-presented homes move quickly even in slower markets.',
        realtor_hook: 'Troutdale\'s lifestyle-driven buyer niche and limited inventory create motivated purchase decisions that reward realtors with efficient, low-negotiation closings.',
    },
    {
        slug: 'salem',
        name: 'Salem',
        county: 'Marion',
        state: 'OR',
        zip: '97301',
        population: '174365',
        median_price: '$380,000',
        price_trend: 'up 3%',
        avg_dom: 25,
        description: 'Salem is Oregon\'s state capital and Willamette Valley\'s second-largest city, driven by government employment, healthcare through Salem Health, and a thriving agricultural economy in the surrounding Eola-Amity Hills wine country. The downtown core along Commercial Street has seen significant investment with new restaurants, breweries, and the restored Historic Elsinore Theatre. Neighborhoods like South Salem\'s Morningside and West Salem\'s Orchard Heights offer family-oriented living with valley views.',
        neighborhoods: 'South Salem, West Salem, Morningside, Orchard Heights, Lancaster',
        nearby: 'Keizer, Albany, Corvallis',
        seller_hook: 'Salem\'s large, stable government workforce creates consistent buyer demand, and competing realtors bring buyers from the Portland metro seeking affordability without sacrificing amenities.',
        realtor_hook: 'Salem\'s growing population, affordable price point, and proximity to Portland make it a high-volume market where realtors can build strong referral networks across diverse buyer demographics.',
    },
    {
        slug: 'eugene',
        name: 'Eugene',
        county: 'Lane',
        state: 'OR',
        zip: '97401',
        population: '176654',
        median_price: '$450,000',
        price_trend: 'up 4%',
        avg_dom: 22,
        description: 'Eugene is home to the University of Oregon and a deeply rooted outdoor culture centered on the Willamette River path, Pre\'s Trail, and Spencer Butte Park. The city\'s economy blends university employment, healthcare through PeaceHealth, and a creative sector supported by venues like the Hult Center for the Performing Arts. South Eugene\'s historic neighborhoods and the eclectic Whiteaker district attract buyers seeking character and walkability.',
        neighborhoods: 'South Eugene, Whiteaker, Friendly Area, Amazon, Cal Young',
        nearby: 'Springfield, Corvallis, Roseburg',
        seller_hook: 'Eugene\'s UO-affiliated relocation traffic and strong in-migration from California create a buyer pool that competes aggressively for well-located properties, especially near campus and bike infrastructure.',
        realtor_hook: 'Eugene\'s mix of student housing investors, relocating faculty, and lifestyle buyers provides realtors with a uniquely diverse client base and year-round market activity.',
    },
    {
        slug: 'bend',
        name: 'Bend',
        county: 'Deschutes',
        state: 'OR',
        zip: '97701',
        population: '102059',
        median_price: '$730,000',
        price_trend: 'up 5%',
        avg_dom: 20,
        description: 'Bend has emerged as one of the Pacific Northwest\'s most sought-after destinations, anchored by Mt. Bachelor ski resort, the Deschutes River trail system, and a craft brewery scene along the Old Mill District that draws year-round visitors and remote workers. The city\'s booming economy includes healthcare through St. Charles Medical Center, a tech satellite sector, and outdoor recreation industry employers like Hydro Flask and Deschutes Brewery. Neighborhoods like NorthWest Crossing and the Old Bend historic district command strong premiums.',
        neighborhoods: 'NorthWest Crossing, Old Bend, Broken Top, Awbrey Butte, Southeast Bend',
        nearby: 'Redmond, Sisters, Sunriver',
        seller_hook: 'Bend\'s national profile and remote-work migration wave bring cash and above-list offers from California and Pacific Northwest metros, giving competitive realtors exceptional leverage to maximize your sale.',
        realtor_hook: 'Bend\'s premium price point, high buyer urgency, and second-home investor demand create a high-commission market where top realtors build their most valuable listings.',
    },
    {
        slug: 'medford',
        name: 'Medford',
        county: 'Jackson',
        state: 'OR',
        zip: '97501',
        population: '86680',
        median_price: '$350,000',
        price_trend: 'up 3%',
        avg_dom: 27,
        description: 'Medford anchors the Rogue Valley between the Cascades and Siskiyous, serving as the commercial hub for Southern Oregon with Asante Rogue Regional Medical Center as the region\'s largest employer alongside Harry & David and a wine and pear agriculture industry. The city\'s Bear Creek Greenway and proximity to Crater Lake National Park and Rogue River fly-fishing attract lifestyle buyers from Northern California. West Medford\'s established neighborhoods and East Medford\'s newer subdivisions serve a broad buyer spectrum.',
        neighborhoods: 'West Medford, East Medford, North Medford, Jacksonville adjacent, Bear Creek',
        nearby: 'Ashland, Jacksonville, Central Point',
        seller_hook: 'Medford\'s affordability relative to California\'s Bay Area drives steady southward in-migration, and competing realtors tap Northern California buyer networks that bring motivated, pre-qualified offers.',
        realtor_hook: 'Medford\'s role as the Southern Oregon service hub and its California in-migration pipeline give realtors a steady deal flow that isn\'t dependent on any single employer or industry.',
    },
    {
        slug: 'ashland',
        name: 'Ashland',
        county: 'Jackson',
        state: 'OR',
        zip: '97520',
        population: '21600',
        median_price: '$650,000',
        price_trend: 'up 4%',
        avg_dom: 23,
        description: 'Ashland is Oregon\'s cultural jewel, home to the Tony Award-winning Oregon Shakespeare Festival and Southern Oregon University, with a walkable downtown of independent restaurants, bookshops, and galleries along East Main Street. The city\'s Lithia Park winds through a creek canyon at the foot of the Siskiyou Mountains, and nearby Mount Ashland offers winter skiing minutes from town. Buyers from California and the Bay Area consistently drive demand in Ashland\'s Westwood Hills and historic Railroad District neighborhoods.',
        neighborhoods: 'Railroad District, Westwood Hills, Lithia Park vicinity, SOU campus area, East Main',
        nearby: 'Medford, Jacksonville, Talent',
        seller_hook: 'Ashland\'s arts-and-culture identity attracts a national buyer pool willing to pay a premium for lifestyle, and realtors who market to California buyers consistently achieve the strongest Ashland sale prices.',
        realtor_hook: 'Ashland\'s prestige market, limited inventory, and affluent lifestyle-buyer pool make every listing a high-value opportunity for realtors with out-of-state buyer connections.',
    },
    {
        slug: 'corvallis',
        name: 'Corvallis',
        county: 'Benton',
        state: 'OR',
        zip: '97330',
        population: '59864',
        median_price: '$430,000',
        price_trend: 'up 3%',
        avg_dom: 24,
        description: 'Corvallis is defined by Oregon State University, whose campus and related research institutions employ the majority of the city\'s professional class alongside Hewlett-Packard\'s ink and printer supply division. The city consistently ranks among Oregon\'s most bikeable, with the Willamette River trail, McDonald-Dunn Research Forest, and a compact downtown of locally-owned businesses along 2nd Street. South Corvallis hillside neighborhoods and the established Northwest side offer contrasting options for buyers.',
        neighborhoods: 'Northwest Corvallis, South Corvallis, Timberhill, Crystal Lake, Witham Hill',
        nearby: 'Albany, Salem, Eugene',
        seller_hook: 'OSU faculty and HP relocation transfers provide a reliable stream of financially stable buyers, and competing realtors leverage the university\'s relocation services to bring offers fast.',
        realtor_hook: 'Corvallis\'s university-driven buyer turnover and consistent faculty relocation demand give realtors a predictable, relationship-based business with strong repeat and referral potential.',
    },
    {
        slug: 'albany',
        name: 'Albany',
        county: 'Linn',
        state: 'OR',
        zip: '97321',
        population: '57190',
        median_price: '$350,000',
        price_trend: 'up 3%',
        avg_dom: 26,
        description: 'Albany sits at the confluence of the Calapooia and Willamette Rivers in the central Willamette Valley, preserving one of Oregon\'s finest collections of Victorian and historic architecture in its Hackleman and Monteith historic districts. The city\'s economy relies on rare earth metals processing through Teledyne FLIR and Albany International, alongside healthcare and retail serving the broader mid-valley region. Albany\'s affordability compared to Corvallis and Salem draws commuters from both cities.',
        neighborhoods: 'Hackleman Historic District, Monteith Historic District, North Albany, Periwinkle, Sunrise',
        nearby: 'Corvallis, Salem, Lebanon',
        seller_hook: 'Albany\'s historic home inventory appeals to a passionate niche buyer who researches actively and moves quickly, and competitive realtors know how to market architectural character to that motivated audience.',
        realtor_hook: 'Albany\'s low price point, mid-valley location, and commuter buyer demand from Corvallis and Salem give realtors strong volume potential in an underserved market.',
    },
];
