// cities/pa.js — Pennsylvania city data for SEO landing pages

module.exports = [
    {
        slug: 'philadelphia',
        name: 'Philadelphia',
        county: 'Philadelphia',
        state: 'PA',
        zip: '19103',
        population: '1,576,000',
        median_price: '$249,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Philadelphia is the birthplace of American democracy and one of the East Coast\'s most dynamic real estate markets — a city where Fishtown\'s converted industrial lofts, Society Hill\'s Federal-period townhomes, and Chestnut Hill\'s Victorian estates coexist with rapidly gentrifying corridors in Point Breeze and East Kensington. Penn, Drexel, Jefferson Health, and a growing life sciences corridor anchor one of the country\'s strongest major-city economies.',
        neighborhoods: 'Fishtown, Northern Liberties, Rittenhouse Square, Society Hill, Graduate Hospital, Chestnut Hill, Manayunk, East Passyunk',
        nearby: 'Camden NJ, Chester, King of Prussia, Bensalem, Norristown',
        seller_hook: 'Philadelphia\'s booming life sciences and university economy keeps buyer demand strong across nearly every neighborhood — let RealtorFinder connect you with top city agents competing to list your home.',
        realtor_hook: 'Philadelphia\'s sheer size, rapidly gentrifying corridors, and diverse price points offer listing agents more opportunity per zip code than almost any major American city — join RealtorFinder to reach motivated sellers.',
    },
    {
        slug: 'pittsburgh',
        name: 'Pittsburgh',
        county: 'Allegheny',
        state: 'PA',
        zip: '15222',
        population: '303,000',
        median_price: '$239,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Pittsburgh has reinvented itself spectacularly — the Steel City is now a world-leading tech and healthcare hub, where Carnegie Mellon\'s AI research, Google\'s largest engineering office outside California, and UPMC\'s $26 billion health system have transformed the economy. Lawrenceville\'s brewery-and-boutique corridor, Squirrel Hill\'s Jewish cultural heritage, and Shadyside\'s Victorian architecture make Pittsburgh one of America\'s most livable and undervalued cities.',
        neighborhoods: 'Lawrenceville, Squirrel Hill, Shadyside, Highland Park, Regent Square, Mount Washington, Fox Chapel border, Bloomfield',
        nearby: 'Mount Lebanon, Upper St. Clair, Bethel Park, Wexford, Robinson Township',
        seller_hook: 'Pittsburgh\'s tech and healthcare boom has created a buyer class of CMU graduates and Google engineers competing for well-located homes — RealtorFinder helps you find an agent who understands this new Pittsburgh.',
        realtor_hook: 'Pittsburgh\'s transformation into a tech hub has brought high-earning buyers who are reshaping valuations across city neighborhoods — RealtorFinder connects you with motivated sellers in this dynamic market.',
    },
    {
        slug: 'allentown',
        name: 'Allentown',
        county: 'Lehigh',
        state: 'PA',
        zip: '18101',
        population: '126,000',
        median_price: '$259,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'Allentown is the Lehigh Valley\'s largest city and one of Pennsylvania\'s fastest-growing metros — the Neighborhood Improvement Zone downtown revitalization, PPL Center\'s arena entertainment district, and a surging distribution and e-commerce logistics sector have fueled strong population growth. Its location two hours from both New York City and Philadelphia makes it a compelling relocation destination for buyers seeking affordability without sacrificing access.',
        neighborhoods: 'West End, West Park, Old Fairgrounds, Midway Manor, Jordan Heights, Fountain Hill border, East Side, South Allentown',
        nearby: 'Bethlehem, Easton, Emmaus, Whitehall, Northampton',
        seller_hook: 'Allentown\'s proximity to New York City and booming logistics economy keep buyer competition healthy — RealtorFinder connects you with Lehigh Valley agents who know how to price and position your home.',
        realtor_hook: 'Allentown\'s rapid growth and NY/Philly transplant buyer pool make the Lehigh Valley one of Pennsylvania\'s most active listing markets — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'erie',
        name: 'Erie',
        county: 'Erie',
        state: 'PA',
        zip: '16501',
        population: '94,000',
        median_price: '$149,000',
        price_trend: 'up 4%',
        avg_dom: 44,
        description: 'Erie is Pennsylvania\'s only Great Lakes port city — a mid-size industrial city undergoing a creative renaissance anchored by the Presque Isle State Park peninsula, Gannon University, and a downtown being revitalized with arts venues and tech startups. Erie Insurance\'s regional headquarters, a growing manufacturing base, and one of Pennsylvania\'s lowest costs of living attract first-time buyers and remote workers seeking Great Lakes lifestyle.',
        neighborhoods: 'Frontier, West Bayfront, Millcreek border, Harborcreek border, Lawrence Park, Lawrence Parkway, East Side, Glenwood',
        nearby: 'Millcreek, Harborcreek, Fairview, Girard, North East',
        seller_hook: 'Erie\'s affordability and Great Lakes lifestyle appeal are drawing new buyer demographics — RealtorFinder helps you find a local agent who understands this evolving market to get the best result for your home.',
        realtor_hook: 'Erie\'s improving economy, affordable price points, and Presque Isle appeal generate consistent buyer activity for agents who work this market deeply — join RealtorFinder to reach motivated sellers.',
    },
    {
        slug: 'reading',
        name: 'Reading',
        county: 'Berks',
        state: 'PA',
        zip: '19601',
        population: '95,000',
        median_price: '$179,000',
        price_trend: 'up 5%',
        avg_dom: 36,
        description: 'Reading is the commercial hub of Berks County — a city with a deep Pennsylvania Dutch heritage and a rapidly growing Latino community that has reshaped its cultural character. Reading\'s outlet retail legacy, expanding healthcare sector, and affordability have attracted investors and first-time buyers, while the surrounding Berks County townships offer newer construction at prices well below the Philadelphia suburbs.',
        neighborhoods: 'Centre Park, Hampden Heights, GoggleWorks District, Northeast Reading, Northwest Reading, Berkshire Heights, Kenhorst border, Wyomissing border',
        nearby: 'Wyomissing, Exeter, Spring Township, Muhlenberg, Shillington',
        seller_hook: 'Reading\'s affordability and investor activity make it a competitive market for well-priced homes — RealtorFinder connects you with Berks County agents who know how to reach the right buyers.',
        realtor_hook: 'Reading\'s first-time buyer and investor demand, combined with strong Berks County suburbs, offer agents a steady volume listing market — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'scranton',
        name: 'Scranton',
        county: 'Lackawanna',
        state: 'PA',
        zip: '18503',
        population: '77,000',
        median_price: '$169,000',
        price_trend: 'up 5%',
        avg_dom: 38,
        description: 'Scranton is Northeastern Pennsylvania\'s Electric City — named for its pioneering electric trolley system, today it\'s known for its affordability, University of Scranton campus, and as the fictional setting of The Office television series that has driven a quirky but genuine tourism economy. The city\'s proximity to New York City (two hours) and Philadelphia (two and a half hours) is fueling a steady influx of remote workers seeking sub-$200k homes.',
        neighborhoods: 'Hill Section, Green Ridge, Hyde Park, West Side, Minooka, Pine Brook, Keyser Valley, South Side',
        nearby: 'Dunmore, Moosic, Old Forge, Wilkes-Barre, Stroudsburg',
        seller_hook: 'Scranton\'s remote-work migration from New York City is creating new buyer demand that is pushing prices upward — RealtorFinder helps you find an agent who can target that motivated buyer pool.',
        realtor_hook: 'Scranton\'s dramatic affordability advantage over New York City is driving unprecedented buyer interest from remote workers — join RealtorFinder to connect with motivated sellers in this emerging market.',
    },
    {
        slug: 'bethlehem',
        name: 'Bethlehem',
        county: 'Northampton',
        state: 'PA',
        zip: '18015',
        population: '77,000',
        median_price: '$279,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Bethlehem has transformed its Bethlehem Steel industrial legacy into one of Pennsylvania\'s most celebrated revitalization stories — the SteelStacks arts and cultural campus rises from the former blast furnaces, while Musikfest\'s annual 500,000-person festival and Wind Creek Bethlehem casino anchor a vibrant local economy. Lehigh University\'s presence, proximity to New York City via Route 78, and a thriving restaurant scene in the South Side district make it the Lehigh Valley\'s most desirable address.',
        neighborhoods: 'South Side, Historic District, West Bethlehem, Fountain Hill, Illick\'s Mill, Saucon Valley border, College Heights, East Side',
        nearby: 'Allentown, Easton, Hellertown, Northampton, Nazareth',
        seller_hook: 'Bethlehem\'s SteelStacks transformation and Lehigh University prestige have created strong buyer demand from NYC commuters and Lehigh alumni — let RealtorFinder connect you with agents who know this premium Lehigh Valley market.',
        realtor_hook: 'Bethlehem\'s revitalized economy and commuter appeal to New York City generate highly motivated buyers — RealtorFinder connects you with sellers in the Lehigh Valley\'s most competitive market.',
    },
    {
        slug: 'lancaster',
        name: 'Lancaster',
        county: 'Lancaster',
        state: 'PA',
        zip: '17601',
        population: '59,000',
        median_price: '$249,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Lancaster City is the nation\'s oldest inland city and one of Pennsylvania\'s most surprising food and arts destinations — Central Market\'s 300-year-old farmer\'s market, a James Beard-recognized restaurant scene, and gallery-lined Prince Street have made it a magnet for Philadelphia and New York transplants seeking authenticity and affordability. The surrounding Lancaster County countryside\'s Amish farms and covered bridges add a cultural richness unmatched in the region.',
        neighborhoods: 'Northwest Lancaster, Southeast Lancaster, Cabbage Hill, Chestnut Hill, Musser Park, Reservoir District, Fulton, East Lancaster',
        nearby: 'Manheim Township, East Lampeter, Lititz, Ephrata, Columbia',
        seller_hook: 'Lancaster\'s nationally recognized food and arts scene is drawing buyers from Philadelphia and New York who are willing to pay for the lifestyle — RealtorFinder connects you with agents who can reach this motivated audience.',
        realtor_hook: 'Lancaster City\'s cultural renaissance and strong demand from Philadelphia-area transplants make it one of South-Central Pennsylvania\'s most dynamic listing markets — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'harrisburg',
        name: 'Harrisburg',
        county: 'Dauphin',
        state: 'PA',
        zip: '17101',
        population: '50,000',
        median_price: '$189,000',
        price_trend: 'up 5%',
        avg_dom: 33,
        description: 'Harrisburg is Pennsylvania\'s capital city — a Susquehanna River city where the gold-domed State Capitol, Pennsylvania National Guard headquarters, and a growing state government administrative workforce anchor an economy that has remained stable through national recessions. The Midtown Harrisburg arts district, Broad Street Market, and Shipoke\'s riverside Victorian row houses serve a young professional and government worker buyer class.',
        neighborhoods: 'Midtown, Uptown, Shipoke, Allison Hill, Olde Uptown, City Island area, Penbrook border, Swatara border',
        nearby: 'Camp Hill, Mechanicsburg, Hershey, Carlisle, Enola',
        seller_hook: 'Harrisburg\'s stable government economy and growing Midtown arts scene attract buyers who value walkability and river access — RealtorFinder helps you find an agent who knows the capital region market.',
        realtor_hook: 'Harrisburg\'s government employment stability and affordability relative to Philadelphia make it a steady listing market with broad buyer appeal — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'york',
        name: 'York',
        county: 'York',
        state: 'PA',
        zip: '17401',
        population: '44,000',
        median_price: '$179,000',
        price_trend: 'up 5%',
        avg_dom: 34,
        description: 'York is South-Central Pennsylvania\'s industrial heartland — a city of manufacturing heritage, colorful Victorian architecture, and a Continental Square downtown that has been revitalized through York\'s creative arts movement. Harley-Davidson\'s Vehicle Operations factory, York College of Pennsylvania, and a manufacturing and food processing economy provide diverse employment, while affordability drives consistent first-time buyer demand.',
        neighborhoods: 'Elmwood, Colonial Complex, Northwest Triangle, Olde Towne, York Suburban border, Springettsbury border, Spring Garden, Penn Park',
        nearby: 'Hanover, Red Lion, Spring Garden Township, York Township, Dallastown',
        seller_hook: 'York\'s affordability and proximity to Harrisburg, Baltimore, and Lancaster attract value-conscious buyers in large numbers — let RealtorFinder connect you with an agent who can position your home to this active market.',
        realtor_hook: 'York\'s first-time buyer activity and investor demand for affordable inventory make it one of South-Central Pennsylvania\'s most consistent listing volume markets — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'west-chester',
        name: 'West Chester',
        county: 'Chester',
        state: 'PA',
        zip: '19380',
        population: '20,000',
        median_price: '$529,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'West Chester is Chester County\'s crown jewel — a historic borough of federal and Victorian architecture, walkable Gay Street restaurants, West Chester University\'s campus energy, and proximity to Pennsylvania\'s most desirable school districts. Its position at the heart of the Main Line\'s western extension, combined with access to Route 202\'s tech corridor and Amtrak to Philadelphia, makes it consistently one of the region\'s most competitive residential markets.',
        neighborhoods: 'Historic District, College Hill, Hoopes Park, Brandywine Heights, North Ward, South Ward, Exton border, Westtown border',
        nearby: 'Exton, Downingtown, Malvern, Kennett Square, Coatesville',
        seller_hook: 'West Chester\'s historic borough character and top-rated Chester County schools create fierce buyer competition — RealtorFinder helps you find a local expert to capitalize on that demand for your listing.',
        realtor_hook: 'West Chester\'s consistently low days-on-market and educated, high-income buyer pool make it one of Chester County\'s most rewarding listing markets — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'wayne',
        name: 'Wayne',
        county: 'Delaware',
        state: 'PA',
        zip: '19087',
        population: '54,000',
        median_price: '$619,000',
        price_trend: 'up 4%',
        avg_dom: 26,
        description: 'Wayne is the Main Line\'s most desirable address — an old-money Philadelphia suburb where the SEPTA Paoli/Thorndale line delivers commuters to Center City in 25 minutes, and where the Wayne Business District\'s independent restaurants and Radnor Township\'s nationally ranked schools command some of the highest residential premiums in Pennsylvania. Corporate campuses along Route 202 and the Route 30 corridor provide local employment that reduces commuting dependency.',
        neighborhoods: 'Wayne Village, Strafford, Berwyn border, Devon border, Radnor Township residential, Wallingford Hills, Chesterbrook, Valley Forge border',
        nearby: 'Berwyn, Paoli, Malvern, Villanova, Radnor',
        seller_hook: 'Wayne\'s Main Line pedigree and Radnor Township schools drive intense buyer competition among Philadelphia\'s professional class — RealtorFinder lets you find the specialist who commands the best price in this market.',
        realtor_hook: 'Wayne and the Main Line corridor represent Pennsylvania\'s most consistent high-value listing market, with motivated buyers competing year-round — join RealtorFinder to reach sellers in this prestigious area.',
    },
    {
        slug: 'king-of-prussia',
        name: 'King of Prussia',
        county: 'Montgomery',
        state: 'PA',
        zip: '19406',
        population: '24,000',
        median_price: '$469,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'King of Prussia is the Philadelphia region\'s premier commercial and residential crossroads — home to the nation\'s second-largest shopping complex, dozens of Fortune 500 regional headquarters, and a residential market that blends apartment communities, townhome developments, and single-family neighborhoods attracting young professionals and corporate transferees. Its position at the Route 202 and I-76 interchange makes it the region\'s most accessible suburb.',
        neighborhoods: 'Town Center, Gulph Mills, Croton, Draper, Village of Four Seasons, Upper Merion residential, Allendale, King Manor',
        nearby: 'Wayne, Norristown, Conshohocken, Trooper, Blue Bell',
        seller_hook: 'King of Prussia\'s major corporate presence and Route 202 tech corridor attract relocating professionals competing for homes — RealtorFinder connects you with Montgomery County agents who know this market.',
        realtor_hook: 'King of Prussia\'s corporate headquarters density and easy regional access generate a steady stream of corporate transferee buyers — RealtorFinder helps you reach motivated sellers in this active market.',
    },
    {
        slug: 'doylestown',
        name: 'Doylestown',
        county: 'Bucks',
        state: 'PA',
        zip: '18901',
        population: '8,000',
        median_price: '$549,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Doylestown is the historic heart of Bucks County — a small borough that punches far above its size with the Fonthill Castle, Mercer Museum, nationally recognized Doylestown Hospital, and a Main Street of acclaimed independent restaurants and boutiques. Central Bucks School District\'s exceptional reputation drives extraordinary buyer demand from Philadelphia families, making this one of the most competitive small-town markets in the Mid-Atlantic.',
        neighborhoods: 'Historic Borough, New Britain Township border, Doylestown Township border, Montgomery Township border, Warrington border, Solebury border, New Hope border, Upper Gwynedd border',
        nearby: 'New Hope, Chalfont, Warrington, Hatfield, Montgomeryville',
        seller_hook: 'Doylestown\'s Central Bucks schools and historic borough character create a bidding war environment for well-priced homes — RealtorFinder connects you with Bucks County specialists who can maximize your outcome.',
        realtor_hook: 'Doylestown\'s Central Bucks School District and charming borough lifestyle generate intense buyer competition with short days on market — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'newtown',
        name: 'Newtown',
        county: 'Bucks',
        state: 'PA',
        zip: '18940',
        population: '20,000',
        median_price: '$519,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Newtown Township and Borough sit in lower Bucks County\'s most sought-after corridor — a community where Council Rock School District\'s outstanding academic reputation, Tyler State Park\'s 1,700 acres of trails, and a historic State Street restaurant scene combine with convenient access to I-95 and the Trenton Transit Center for New York City commuters. New residential developments along the Route 332 corridor continue to attract families priced out of the Main Line.',
        neighborhoods: 'Newtown Borough, Newtown Grant, Newtown Crossing, Newtown Square border, Buck Road area, Upper Makefield border, Wrightstown border, Richboro border',
        nearby: 'Langhorne, Yardley, Richboro, Jamison, Doylestown',
        seller_hook: 'Newtown\'s Council Rock schools and New York commuter access create one of Bucks County\'s most active buyer markets — let RealtorFinder match you with agents who know how to capture that demand.',
        realtor_hook: 'Newtown\'s Council Rock School District reputation and lower Bucks County location generate consistent buyer demand from New York commuters and Philadelphia families — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'media',
        name: 'Media',
        county: 'Delaware',
        state: 'PA',
        zip: '19063',
        population: '6,000',
        median_price: '$489,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'Media is Delaware County\'s "Everybody\'s Hometown" — a small, walkable borough where State Street\'s independent restaurants and the annual Dining Under the Stars street festival reflect a community character that has made it one of the Philadelphia region\'s most beloved small towns. Rose Tree Media School District, the SEPTA Media trolley line to Philadelphia, and borough parks make it a fierce seller\'s market for any home that becomes available.',
        neighborhoods: 'Media Borough, Rose Valley border, Middletown Township border, Upper Providence border, Nether Providence border, Edgmont border, Swarthmore border, Lima border',
        nearby: 'Swarthmore, Moylan-Rose Valley, Springfield, Broomall, Glen Mills',
        seller_hook: 'Media\'s "Everybody\'s Hometown" reputation and constrained borough inventory mean motivated buyers frequently outnumber available homes — RealtorFinder connects you with Delaware County experts to capitalize on that demand.',
        realtor_hook: 'Media Borough\'s tight inventory and fierce buyer competition make every listing a genuine opportunity — RealtorFinder connects you with motivated sellers in this beloved Delaware County community.',
    },
    {
        slug: 'conshohocken',
        name: 'Conshohocken',
        county: 'Montgomery',
        state: 'PA',
        zip: '19428',
        population: '8,000',
        median_price: '$399,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Conshohocken has transformed from a steel town into one of the Philadelphia region\'s hottest young professional markets — Fayette Street\'s restaurant row, a SEPTA Manayunk/Norristown Line station to Center City, and a concentration of corporate campuses along the Schuylkill River have made "Conshohocken" synonymous with upward mobility for Millennial and Gen Z buyers. New townhome developments along the riverfront continue to meet surging demand.',
        neighborhoods: 'East Conshohocken, West Conshohocken border, Spring Mill, Fayette Street Corridor, Riverfront, Plymouth Township border, Whitpain Township border, Barren Hill border',
        nearby: 'Plymouth Meeting, King of Prussia, Norristown, Ambler, Blue Bell',
        seller_hook: 'Conshohocken\'s booming young professional demand and new construction competition make proper pricing and presentation critical — let RealtorFinder find you a Montgomery County agent who knows this fast-moving market.',
        realtor_hook: 'Conshohocken\'s exceptional appreciation rate and young professional buyer demand make it one of Montgomery County\'s most exciting listing markets — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'norristown',
        name: 'Norristown',
        county: 'Montgomery',
        state: 'PA',
        zip: '19401',
        population: '34,000',
        median_price: '$259,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Norristown is Montgomery County\'s seat and one of the Philadelphia region\'s most compelling affordable markets — its Victorian row houses and detached homes are drawing first-time buyers and investors priced out of Conshohocken and King of Prussia, while the SEPTA Manayunk/Norristown Line provides a direct Center City link. The Montgomery County courthouse complex, Norristown State Hospital redevelopment, and expanding retail base are driving renewed investment.',
        neighborhoods: 'West End, East End, Stony Creek, Elmwood Park, Tremont, Hartranft, Roosevelt, Burnside',
        nearby: 'Conshohocken, King of Prussia, Plymouth Meeting, Bridgeport, West Norriton',
        seller_hook: 'Norristown\'s rapid appreciation and first-time buyer demand are driving competition for well-maintained homes — RealtorFinder connects you with Montgomery County agents positioned to reach this growing buyer pool.',
        realtor_hook: 'Norristown\'s value pricing and SEPTA access to Center City are fueling some of Montgomery County\'s strongest appreciation — join RealtorFinder to connect with motivated sellers in this rising market.',
    },
    {
        slug: 'bensalem',
        name: 'Bensalem',
        county: 'Bucks',
        state: 'PA',
        zip: '19020',
        population: '61,000',
        median_price: '$349,000',
        price_trend: 'up 5%',
        avg_dom: 29,
        description: 'Bensalem is lower Bucks County\'s most populated municipality — a diverse township where Parx Casino\'s hospitality employment, Oxford Valley Mall, and extensive single-family developments attract working-class and middle-income buyers seeking affordability on I-95 between Philadelphia and Trenton. Its proximity to Northeast Philadelphia and Neshaminy School District makes it a first-time buyer stronghold in the Philadelphia metro.',
        neighborhoods: 'Cornwells Heights, Trevose, Nottingham, Holmes, Penndel border, Bristol border, Fairless Hills border, Hulmeville border',
        nearby: 'Levittown, Bristol, Langhorne, Feasterville, Horsham',
        seller_hook: 'Bensalem\'s first-time buyer activity and I-95 corridor location keep demand consistent — RealtorFinder connects you with Bucks County agents who can reach the motivated buyers competing for homes here.',
        realtor_hook: 'Bensalem\'s large population and steady first-time buyer market make it one of lower Bucks County\'s most reliable listing volume markets — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'lower-merion',
        name: 'Lower Merion',
        county: 'Montgomery',
        state: 'PA',
        zip: '19003',
        population: '60,000',
        median_price: '$699,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Lower Merion Township is the epicenter of the Main Line\'s prestige — an affluent Montgomery County municipality encompassing Ardmore, Haverford, Wynnewood, Bala Cynwyd, and Penn Wynne, where Lower Merion School District\'s Nationally ranked high schools, SEPTA Regional Rail access, and stately stone colonial homes on mature tree-lined streets create one of the most competitive residential markets in the Mid-Atlantic.',
        neighborhoods: 'Ardmore, Bala Cynwyd, Wynnewood, Penn Wynne, Merion Station, Haverford, Gladwyne, Narberth border',
        nearby: 'Narberth, Wayne, Villanova, Bryn Mawr, Havertown',
        seller_hook: 'Lower Merion\'s nationally ranked schools and Main Line prestige create intense year-round buyer competition — let RealtorFinder connect you with Main Line specialists who consistently achieve top dollar for their sellers.',
        realtor_hook: 'Lower Merion Township combines Pennsylvania\'s strongest school reputation with the region\'s most motivated buyer base — RealtorFinder connects you with sellers in this premier Main Line market.',
    },
    {
        slug: 'state-college',
        name: 'State College',
        county: 'Centre',
        state: 'PA',
        zip: '16801',
        population: '43,000',
        median_price: '$299,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'State College is Central Pennsylvania\'s university hub — a vibrant college town built around Penn State University\'s 47,000-student main campus, where Beaver Stadium\'s 107,000-seat game day energy, Beaver Avenue\'s restaurants and bars, and a robust startup ecosystem incubated by the university\'s research programs define a community unlike any other in the state. The faculty, Penn State Health, and university staff buyer market provides a reliable professional demand base.',
        neighborhoods: 'Highlands, Park Forest Village, Nittany, College Heights, Downtown State College, Whitehall Road Corridor, Holmes-Foster, Lemont border',
        nearby: 'Bellefonte, Boalsburg, Milesburg, Port Matilda, Philipsburg',
        seller_hook: 'State College\'s Penn State buyer base of faculty, healthcare professionals, and university staff creates consistent demand regardless of season — RealtorFinder connects you with Centre County agents who understand this specialized market.',
        realtor_hook: 'State College\'s university economy and Penn State\'s continuous faculty and staff hiring create a steady, recession-resistant buyer pool — join RealtorFinder to connect with motivated sellers here.',
    },
    {
        slug: 'malvern',
        name: 'Malvern',
        county: 'Chester',
        state: 'PA',
        zip: '19355',
        population: '3,000',
        median_price: '$589,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Malvern Borough and surrounding Great Valley area represent the western Main Line\'s tech and pharmaceutical hub — home to Siemens Healthineers, Saint-Gobain North America, and a concentration of biotech firms along Route 202 that has made it one of Chester County\'s most desirable employer-adjacent markets. Great Valley School District, SEPTA Regional Rail to Center City, and charming Main Street character make Malvern one of the fastest-selling markets in Pennsylvania.',
        neighborhoods: 'Malvern Borough, Great Valley, East Whiteland Township residential, Frazer, Paoli border, Berwyn border, Exton border, Lionville border',
        nearby: 'Paoli, Exton, Berwyn, Wayne, Phoenixville',
        seller_hook: 'Malvern\'s Route 202 corporate corridor and Great Valley School District combine to create one of Chester County\'s most motivated buyer bases — RealtorFinder finds you the specialist to maximize your result.',
        realtor_hook: 'Malvern\'s pharmaceutical and tech employer base generates a constant stream of corporate transferee and local move-up buyers — RealtorFinder connects you with motivated sellers in this high-demand Chester County market.',
    },
    {
        slug: 'phoenixville',
        name: 'Phoenixville',
        county: 'Chester',
        state: 'PA',
        zip: '19460',
        population: '17,000',
        median_price: '$389,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Phoenixville is Chester County\'s hottest emerging market — a former steel town that has undergone one of Pennsylvania\'s most celebrated downtown revivals, transforming Bridge Street into a nationally recognized strip of craft breweries (Victory Brewing, Root Down Brewing), restaurants, and arts venues. Its affordability relative to the Main Line, Schuylkill River trail access, and a downtown character that attracts young professionals from Philadelphia and the Route 202 corridor are driving some of the state\'s fastest appreciation.',
        neighborhoods: 'Downtown, Gay Street, Friendship Ridge, Spring Ford area, Kimberton border, East Pikeland border, Schuylkill River Trail corridor, Valley Forge border',
        nearby: 'Pottstown, Malvern, Spring City, Collegeville, Royersford',
        seller_hook: 'Phoenixville\'s bridge street revival and affordability advantage are driving bidding wars and record appreciation — RealtorFinder connects you with Chester County agents who know how to maximize your proceeds in this red-hot market.',
        realtor_hook: 'Phoenixville\'s fastest-in-Pennsylvania appreciation rate and young professional buyer surge make it Chester County\'s most exciting listing market right now — reach motivated sellers through RealtorFinder.',
    },
    {
        slug: 'lansdale',
        name: 'Lansdale',
        county: 'Montgomery',
        state: 'PA',
        zip: '19446',
        population: '16,000',
        median_price: '$359,000',
        price_trend: 'up 6%',
        avg_dom: 23,
        description: 'Lansdale is North Penn\'s hub borough — a diverse, rapidly appreciating community where North Penn School District\'s strong academics, SEPTA Lansdale/Doylestown Line rail access to Philadelphia, and affordable pricing relative to Doylestown and the Main Line are drawing first-time buyers and young families in large numbers. A revitalized Main Street corridor and proximity to Route 309 and the Pennsylvania Turnpike provide commuter convenience.',
        neighborhoods: 'Historic Borough, West Ward, East Ward, North Ward, Montgomeryville border, Hatfield border, North Wales border, Upper Gwynedd border',
        nearby: 'North Wales, Hatfield, Montgomeryville, Souderton, Colmar',
        seller_hook: 'Lansdale\'s SEPTA access and affordability relative to neighboring suburbs are driving intense first-time buyer competition — let RealtorFinder find you a North Penn area agent to capture that demand for your listing.',
        realtor_hook: 'Lansdale\'s consistently low days-on-market and strong first-time buyer pipeline make it one of Montgomery County\'s most active listing markets — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'easton',
        name: 'Easton',
        county: 'Northampton',
        state: 'PA',
        zip: '18042',
        population: '28,000',
        median_price: '$249,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Easton is the Lehigh Valley\'s most authentic Delaware River city — a place where the Crayola Experience children\'s museum, Lafayette College\'s Easton campus, and one of Pennsylvania\'s best farmers\' markets anchor a downtown revival that has attracted a growing community of artists, entrepreneurs, and remote workers from New York City. Its position at the PA/NJ border, affordability relative to the broader Lehigh Valley, and direct Route 78 access to New York are fueling rapid price appreciation.',
        neighborhoods: 'Downtown, College Hill, West Ward, South Side, Forks Township border, Palmer Township border, Wilson Borough border, Glendon border',
        nearby: 'Phillipsburg NJ, Bethlehem, Allentown, Nazareth, Bangor',
        seller_hook: 'Easton\'s New York City proximity and downtown revival are creating a buyer demand surge among remote workers and Lehigh Valley professionals — RealtorFinder connects you with agents positioned to reach this expanding buyer pool.',
        realtor_hook: 'Easton\'s fastest-rising appreciation in the Lehigh Valley and NYC commuter appeal make it one of Northampton County\'s most compelling listing markets right now — find motivated sellers through RealtorFinder.',
    },
];
