module.exports = [
    // ── Greater Providence ────────────────────────────────────────────────────
    {
        slug: 'providence',
        name: 'Providence',
        county: 'Providence County',
        state: 'RI',
        zip: '02901',
        population: '190,000',
        median_price: '$319,000',
        price_trend: 'up 15%',
        avg_dom: 18,
        description: 'Providence is Rhode Island\'s beating heart — a compact, walkable capital city energized by Brown University, RISD, a world-famous restaurant scene, and a waterfront that has been completely reimagined over the past two decades. Its 15% annual appreciation is the strongest in the state, reflecting explosive buyer demand from Boston spillover and local urban renaissance.',
        neighborhoods: 'College Hill, Federal Hill, Fox Point, Elmwood, Smith Hill, South Providence, Wayland Square',
        nearby: 'Cranston, Pawtucket, East Providence, Johnston',
        seller_hook: 'Providence\'s 15% appreciation — the highest in Rhode Island — reflects a tidal wave of Boston buyers discovering that a 50-minute commute buys them a city home at half the price. With homes selling in just 18 days and inventory at record lows, sellers are commanding prices that would have seemed impossible three years ago.',
        realtor_hook: 'Providence\'s explosive growth, Boston commuter spillover, and thriving university ecosystem create the most diverse and active buyer pool in Rhode Island — giving agents access to first-time buyers, investors, and relocation clients simultaneously. The city\'s trajectory means your client list today becomes your referral engine tomorrow.',
    },
    {
        slug: 'warwick',
        name: 'Warwick',
        county: 'Kent County',
        state: 'RI',
        zip: '02886',
        population: '82,000',
        median_price: '$309,000',
        price_trend: 'up 11%',
        avg_dom: 20,
        description: 'Warwick is Rhode Island\'s second-largest city, offering 39 miles of Narragansett Bay coastline, T.F. Green Airport, and some of the state\'s most affordable single-family homes. Its bayside neighborhoods and marina communities attract buyers who want waterfront access without Newport or South County price tags.',
        neighborhoods: 'Apponaug, Cowesett, Conimicut, Oakland Beach, Buttonwoods',
        nearby: 'Cranston, East Greenwich, West Warwick, North Kingstown',
        seller_hook: 'Warwick\'s 11% appreciation and 39 miles of Narragansett Bay coastline are drawing buyers from across the state and from Boston who want water access at an accessible price point. Tight inventory means your listing will attract serious, pre-qualified buyers ready to act quickly.',
        realtor_hook: 'Warwick\'s combination of airport proximity, bay access, and mid-market price range makes it Rhode Island\'s most consistently active market for transaction volume. Agents here build high-velocity pipelines serving a steady flow of buyers at every stage of life.',
    },
    {
        slug: 'cranston',
        name: 'Cranston',
        county: 'Providence County',
        state: 'RI',
        zip: '02910',
        population: '82,000',
        median_price: '$329,000',
        price_trend: 'up 12%',
        avg_dom: 19,
        description: 'Cranston is a densely woven mix of tight-knit neighborhoods just minutes from downtown Providence, offering well-maintained single-family homes, excellent parks, and a strong community identity that keeps buyers and residents fiercely loyal. Its 12% appreciation reflects surging demand from Providence buyers seeking more space at a slight value premium.',
        neighborhoods: 'Edgewood, Knightsville, Garden City, Auburn, Oaklawn',
        nearby: 'Providence, Warwick, Johnston, North Providence',
        seller_hook: 'Cranston is experiencing 12% appreciation as Providence buyers overflow into its well-kept neighborhoods in search of space and value — and with homes selling in 19 days, you won\'t be waiting long for the right offer. Rhode Island\'s tight inventory means motivated buyers are watching Cranston listings the moment they go live.',
        realtor_hook: 'Cranston\'s proximity to Providence and strong neighborhood identity create a buyer pool that is both local and spillover-driven, giving agents consistent volume at price points that generate meaningful commissions. Its diverse housing stock — from Arts and Crafts bungalows to new construction — supports a full range of client needs.',
    },
    {
        slug: 'pawtucket',
        name: 'Pawtucket',
        county: 'Providence County',
        state: 'RI',
        zip: '02860',
        population: '75,000',
        median_price: '$279,000',
        price_trend: 'up 15%',
        avg_dom: 22,
        description: 'Pawtucket is Rhode Island\'s most dynamic value market, with a vibrant arts scene anchored by AS220 and the Gamm Theatre, a revitalized downtown, and the historic Slater Mill — the birthplace of the American Industrial Revolution. Its 15% appreciation matches Providence\'s headline number, driven by artists, entrepreneurs, and buyers who see the trajectory clearly.',
        neighborhoods: 'Downtown Pawtucket, Quality Hill, Woodlawn, Darlington, Slater Mill district',
        nearby: 'Providence, Central Falls, North Providence, Cumberland',
        seller_hook: 'Pawtucket\'s 15% appreciation is the joint-highest in Rhode Island, fueled by a creative class and Boston-area buyers who are redefining what this city represents — and sellers who list now are the ones who benefit from peak momentum. The city\'s transformation is accelerating, not slowing.',
        realtor_hook: 'Pawtucket\'s artist-driven revitalization and Boston commuter appeal create a buyer demographic that is educated, decisive, and actively seeking the next neighborhood to break out. Agents who understand the city\'s cultural assets and trajectory can convert that enthusiasm into consistent transactions.',
    },
    {
        slug: 'east-providence',
        name: 'East Providence',
        county: 'Providence County',
        state: 'RI',
        zip: '02914',
        population: '48,000',
        median_price: '$319,000',
        price_trend: 'up 11%',
        avg_dom: 19,
        description: 'East Providence sits directly across the Providence River from the capital city, offering waterfront neighborhoods, a charming historic district, and easy access to downtown Providence amenities without downtown prices. Its underrated Riverside and Rumford neighborhoods are increasingly on buyers\' radar.',
        neighborhoods: 'Riverside, Rumford, Watchemoket, Crescent Park',
        nearby: 'Providence, Barrington, Seekonk MA, Attleboro MA',
        seller_hook: 'East Providence\'s waterfront access and Providence River views are finally getting the market recognition they deserve — 11% appreciation and 19-day average days on market confirm that buyers are serious and competing. Sellers in Riverside and Rumford especially are seeing demand that consistently exceeds their expectations.',
        realtor_hook: 'East Providence\'s Narragansett Bay and river frontage create a lifestyle story that sells itself, while its value position relative to Providence generates consistent buyer interest from across the metro. Agents who specialize here benefit from a market that is still in the early stages of its full appreciation potential.',
    },
    {
        slug: 'north-providence',
        name: 'North Providence',
        county: 'Providence County',
        state: 'RI',
        zip: '02904',
        population: '33,000',
        median_price: '$309,000',
        price_trend: 'up 10%',
        avg_dom: 20,
        description: 'North Providence is a compact, predominantly residential community offering well-maintained neighborhoods, excellent value relative to Providence proper, and easy access to Route 146 and I-95. Its 10% appreciation reflects buyers who know they\'re getting quality community character at a meaningful discount.',
        neighborhoods: 'Centredale, Fruit Hill, Woodbury, Lymansville',
        nearby: 'Providence, Pawtucket, Johnston, Smithfield',
        seller_hook: 'North Providence\'s tight inventory and 10% appreciation mean buyers are competing for the limited listings that come to market — giving sellers pricing power they haven\'t seen in years. The town\'s convenience to Providence and highway access keeps demand from a wide geographic buyer pool flowing.',
        realtor_hook: 'North Providence\'s value position in the Providence metro means buyers who can\'t afford or find what they want in the capital turn here first, creating a reliable secondary market with strong transaction velocity. Agents who cover both markets double their exposure to one of Rhode Island\'s most active buyer pools.',
    },
    {
        slug: 'johnston',
        name: 'Johnston',
        county: 'Providence County',
        state: 'RI',
        zip: '02919',
        population: '29,000',
        median_price: '$329,000',
        price_trend: 'up 9%',
        avg_dom: 21,
        description: 'Johnston is a solid, family-oriented suburb west of Providence known for its reasonable home sizes, community pride, and proximity to major employment corridors. Its gradual but consistent appreciation reflects a market where fundamentals — location, affordability, schools — are recognized and rewarded.',
        neighborhoods: 'Johnston Center, Simmonsville, Graniteville, Thornton',
        nearby: 'Providence, Cranston, North Providence, Scituate',
        seller_hook: 'Johnston\'s steady 9% appreciation and 21-day average on market confirm what local homeowners have always known — this is a community where people want to be, and new buyers are arriving to prove it. Sellers benefit from consistent demand and a buyer pool that prioritizes stability and value.',
        realtor_hook: 'Johnston\'s family-focused buyer base and value-to-Providence relationship create dependable year-round demand, making it a productive market for agents building consistent volume. Its position at the intersection of major commuter routes draws buyers from a broad geographic area.',
    },
    {
        slug: 'lincoln',
        name: 'Lincoln',
        county: 'Providence County',
        state: 'RI',
        zip: '02865',
        population: '23,000',
        median_price: '$389,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'Lincoln is one of Rhode Island\'s most desirable northern suburbs, offering excellent schools, scenic Blackstone Valley river views, and a strong community identity built around outdoor recreation and historic mill village character. Its low days-on-market reflects a buyer pool that moves decisively when a Lincoln listing appears.',
        neighborhoods: 'Lincoln Center, Manville, Lonsdale, Quinnville, Albion',
        nearby: 'North Smithfield, Cumberland, North Providence, Woonsocket',
        seller_hook: 'Lincoln\'s 18-day average on market is the fastest in its price range in the state — buyers are watching Lincoln listings closely and acting immediately when quality homes hit the market. Strong schools and Blackstone Valley recreation combine with 9% appreciation to make this an exceptional moment to sell.',
        realtor_hook: 'Lincoln\'s fast-moving, school-driven market rewards agents who can move efficiently and present listings compellingly to highly motivated buyers. Its strong appreciation trajectory and northern Rhode Island positioning make it a market where well-connected agents consistently win repeat and referral business.',
    },
    {
        slug: 'cumberland',
        name: 'Cumberland',
        county: 'Providence County',
        state: 'RI',
        zip: '02864',
        population: '36,000',
        median_price: '$379,000',
        price_trend: 'up 9%',
        avg_dom: 18,
        description: 'Cumberland is a wooded, spacious community in northern Rhode Island, anchored by the scenic Diamond Hill State Park and strong schools, offering a suburban lifestyle that feels more private and expansive than most Rhode Island towns. Its rapid 18-day sales pace reflects buyer enthusiasm for the town\'s quality of life at a reasonable price.',
        neighborhoods: 'Cumberland Hill, Valley Falls, Ashton, Arnold Mills, Diamond Hill',
        nearby: 'Lincoln, North Smithfield, Pawtucket, Attleboro MA',
        seller_hook: 'Cumberland\'s wooded character, Diamond Hill State Park access, and excellent schools are generating intense buyer interest — homes here sell in just 18 days as buyers fight for limited inventory. Sellers are seeing 9% appreciation on top of the value they\'ve already built in one of northern Rhode Island\'s most sought-after communities.',
        realtor_hook: 'Cumberland\'s appeal to Massachusetts border buyers and Rhode Island families seeking space and quality creates a uniquely broad buyer pool for agents to work with. Its combination of natural assets and strong fundamentals makes listings easy to market to both local and cross-state prospects.',
    },
    {
        slug: 'north-smithfield',
        name: 'North Smithfield',
        county: 'Providence County',
        state: 'RI',
        zip: '02896',
        population: '12,500',
        median_price: '$369,000',
        price_trend: 'up 9%',
        avg_dom: 19,
        description: 'North Smithfield is a quiet, rural-feeling community in the Blackstone Valley that offers generous lot sizes, a genuine small-town atmosphere, and access to historic mill village architecture in Slatersville. Buyers seeking space, privacy, and natural beauty at a competitive price are discovering it in growing numbers.',
        neighborhoods: 'Slatersville, Forestdale, Union Village, North Smithfield Center',
        nearby: 'Woonsocket, Lincoln, Cumberland, Uxbridge MA',
        seller_hook: 'North Smithfield\'s 9% appreciation reflects a growing buyer audience discovering that space, privacy, and Blackstone Valley character come at a significant value compared to more crowded Rhode Island communities. With homes selling in under 20 days, demand is strong and seller leverage is real.',
        realtor_hook: 'North Smithfield\'s rural character and Massachusetts border location attract buyers from both states seeking a genuine lifestyle upgrade at a sensible price — giving agents a cross-market prospect base to cultivate. Its low listing volume means each new property gets significant attention from buyers who have been waiting.',
    },
    {
        slug: 'coventry',
        name: 'Coventry',
        county: 'Kent County',
        state: 'RI',
        zip: '02816',
        population: '35,000',
        median_price: '$319,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Coventry is Rhode Island\'s largest town by area, a sprawling, lake-dotted community in Kent County that offers suburban comfort with genuine access to outdoor recreation, from Tiogue Lake to the Flat River Reservoir. Its affordable price point and steady appreciation make it a strong choice for value-oriented buyers.',
        neighborhoods: 'Anthony, Greene, Washington, Western Coventry, Tiogue Lake area',
        nearby: 'West Warwick, East Greenwich, Exeter, Foster',
        seller_hook: 'Coventry\'s lake access, large lots, and 8% appreciation are drawing buyers who want outdoor recreation and space built into their everyday life — not just as a vacation destination. Rhode Island\'s inventory crunch is pushing buyers toward Coventry in growing numbers, benefiting sellers across all neighborhoods.',
        realtor_hook: 'Coventry\'s geographic size and diverse neighborhoods — from lakefront to wooded rural — give agents a wide product range to match buyers with, reducing the risk of inventory limitations. Its value position in the Kent County market makes it a consistent source of first-time buyer and move-up transactions.',
    },
    {
        slug: 'west-warwick',
        name: 'West Warwick',
        county: 'Kent County',
        state: 'RI',
        zip: '02893',
        population: '29,000',
        median_price: '$279,000',
        price_trend: 'up 11%',
        avg_dom: 21,
        description: 'West Warwick is a former mill town in the heart of Kent County that is experiencing strong appreciation as affordability-conscious buyers seek alternatives to pricier Providence-area communities. Its historic mill villages and improving amenity base are attracting a new generation of residents who see long-term value.',
        neighborhoods: 'Crompton, Arctic, Phenix, Centreville',
        nearby: 'Coventry, Warwick, East Greenwich, Providence',
        seller_hook: 'West Warwick\'s 11% appreciation is driven by buyers who are priced out of nearby communities and discovering real value in its historic neighborhoods — and that momentum is only building as inventory stays tight across the state. Sellers here are getting more than they ever expected from a market that has clearly turned.',
        realtor_hook: 'West Warwick\'s affordability and rapid appreciation create a highly motivated buyer pool — predominantly first-time buyers and value investors who are ready to act. Agents who establish expertise in this market early will benefit as appreciation drives move-up buying and growing client equity.',
    },
    {
        slug: 'woonsocket',
        name: 'Woonsocket',
        county: 'Providence County',
        state: 'RI',
        zip: '02895',
        population: '44,000',
        median_price: '$229,000',
        price_trend: 'up 14%',
        avg_dom: 24,
        description: 'Woonsocket is Rhode Island\'s most affordable urban market, a Blackstone Valley mill city with authentic French-Canadian heritage, a revitalizing downtown, and the distinction of being the lowest-priced entry point for homeownership in the state. Its 14% appreciation signals that buyers are discovering what investors have known for years.',
        neighborhoods: 'Downtown Woonsocket, Globe Village, Social District, Hamlet',
        nearby: 'North Smithfield, Cumberland, Lincoln, Millville MA',
        seller_hook: 'Woonsocket\'s 14% appreciation is attracting buyers who recognize that Rhode Island\'s most affordable market is also its fastest-growing — and sellers who list now are capturing returns that would have been unthinkable just a few years ago. The city\'s Blackstone Valley heritage and revitalizing downtown are rewriting the narrative.',
        realtor_hook: 'Woonsocket\'s combination of lowest-in-state pricing and top-tier appreciation creates an investment buyer market unlike anything else in Rhode Island, generating consistent leads from out-of-state landlords and first-time buyers simultaneously. Agents who own this market early will ride its appreciation curve for years.',
    },

    // ── Newport County & Bay ──────────────────────────────────────────────────
    {
        slug: 'newport',
        name: 'Newport',
        county: 'Newport County',
        state: 'RI',
        zip: '02840',
        population: '24,000',
        median_price: '$579,000',
        price_trend: 'up 9%',
        avg_dom: 26,
        description: 'Newport is one of America\'s most iconic waterfront cities, a Gilded Age destination of legendary mansions, world-class sailing, and a Thames Street restaurant scene that draws visitors and buyers from around the globe. Its waterfront premiums and limited buildable land make it Rhode Island\'s most aspirational real estate market.',
        neighborhoods: 'Bellevue Avenue, Thames Street, The Point, Fifth Ward, Kay-Catherine',
        nearby: 'Middletown, Portsmouth, Jamestown, Bristol',
        seller_hook: 'Newport\'s global reputation and extreme scarcity of available properties mean your listing reaches an international buyer audience — and with prices up 9% and Ocean State inventory at historic lows, sellers are achieving waterfront and mansion-district premiums that reflect genuine rarity. There is simply no substitute for a Newport address.',
        realtor_hook: 'Newport\'s national and international buyer pool — driven by sailing culture, Gilded Age heritage, and coastal tourism — gives local agents access to the most geographically diverse and high-net-worth prospects in Rhode Island. Mastering this market opens doors to a clientele that will follow you throughout their real estate lives.',
    },
    {
        slug: 'bristol',
        name: 'Bristol',
        county: 'Bristol County',
        state: 'RI',
        zip: '02809',
        population: '22,000',
        median_price: '$389,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Bristol is a beautifully preserved colonial town on a peninsula between Narragansett Bay and the Mount Hope Bay, home of Roger Williams University and the nation\'s oldest Fourth of July celebration. Its walkable harbor, historic architecture, and maritime character attract buyers seeking authentic Rhode Island coastal living.',
        neighborhoods: 'Bristol Common, Poppasquash, Constitution Street, Ferry Road',
        nearby: 'Barrington, Warren, Portsmouth, Providence',
        seller_hook: 'Bristol\'s Narragansett Bay peninsula setting, stunning harbor, and historic character create a buyer demand that exceeds what this small market can supply — prices are up 8% as buyers compete for properties that rarely come to market. Selling a Bristol home means offering one of New England\'s most coveted addresses.',
        realtor_hook: 'Bristol\'s unique peninsular geography, Roger Williams University connection, and national heritage tourism draw a buyer pool that includes waterfront seekers, history lovers, and academic community members — giving agents multiple audiences to serve in a single market. Properties here generate genuine enthusiasm and word-of-mouth referrals.',
    },
    {
        slug: 'barrington',
        name: 'Barrington',
        county: 'Bristol County',
        state: 'RI',
        zip: '02806',
        population: '16,500',
        median_price: '$519,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'Barrington is consistently ranked as one of Rhode Island\'s best places to live, combining top-ranked public schools, a tight-knit community on Narragansett Bay, and a tree-lined residential character that appeals to families seeking the best of New England suburban living. Its Rumstick and Nayatt Point waterfront areas command significant premiums.',
        neighborhoods: 'Barrington Center, Rumstick Point, Nayatt Point, Hampden Meadows',
        nearby: 'East Providence, Bristol, Warren, Seekonk MA',
        seller_hook: 'Barrington\'s status as Rhode Island\'s premier family suburb means your home competes for buyers who have specifically chosen this town for its schools and community — a highly motivated, pre-qualified pool that drives 20-day average sales. With waterfront premiums on top of the state\'s tightest inventory, sellers hold exceptional leverage.',
        realtor_hook: 'Barrington\'s top school rankings and Narragansett Bay waterfront generate a perpetual pipeline of family buyers from Providence, Boston, and beyond who will not consider other towns. Agents who own this market command a premium clientele and benefit from one of Rhode Island\'s strongest referral networks.',
    },
    {
        slug: 'middletown',
        name: 'Middletown',
        county: 'Newport County',
        state: 'RI',
        zip: '02842',
        population: '16,000',
        median_price: '$419,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Middletown sits at the heart of Aquidneck Island between Newport and Portsmouth, offering Atlantic Ocean beaches, Second Beach and Third Beach access, and a more residential character than its famous neighbor at a more accessible price point. Its Naval Station Newport proximity and beach lifestyle drive consistent buyer demand.',
        neighborhoods: 'Miantonomi Park, Easton\'s Beach area, Green End, Paradise',
        nearby: 'Newport, Portsmouth, Bristol, Jamestown',
        seller_hook: 'Middletown offers Newport\'s beaches and Aquidneck Island lifestyle at a meaningful price advantage — and buyers know it, which is why 8% appreciation and 22-day sales confirm demand that far outpaces available homes. Ocean State inventory constraints and waterfront premiums make this an outstanding moment for Middletown sellers.',
        realtor_hook: 'Middletown\'s position as Newport\'s more affordable neighbor creates a natural buyer flow from the island\'s more expensive south end, giving agents a ready audience of price-adjusted Newport seekers. Military relocation demand from Naval Station Newport adds a reliable, time-sensitive buyer segment to any agent\'s pipeline.',
    },

    // ── Washington County (South County) ─────────────────────────────────────
    {
        slug: 'narragansett',
        name: 'Narragansett',
        county: 'Washington County',
        state: 'RI',
        zip: '02882',
        population: '15,500',
        median_price: '$489,000',
        price_trend: 'up 10%',
        avg_dom: 26,
        description: 'Narragansett is Rhode Island\'s quintessential seaside resort community, offering iconic Scarborough Beach, a vibrant Narragansett Pier village, and some of the finest surfing and sailing on the East Coast. Its blend of year-round residents, seasonal cottages, and luxury waterfront properties creates a diverse and dynamic market.',
        neighborhoods: 'Narragansett Pier, Bonnet Shores, Canonchet, Point Judith, Scarborough Beach area',
        nearby: 'South Kingstown, North Kingstown, Wakefield, Jamestown',
        seller_hook: 'Narragansett\'s beachfront and water-view properties are capturing waterfront premiums that are climbing sharply, with overall prices up 10% as buyers from Boston, Providence, and New York chase a shrinking supply of Ocean State coastal homes. Your Narragansett property is competing in a national vacation and relocation market — and winning.',
        realtor_hook: 'Narragansett\'s seasonal and year-round market duality gives agents two active buyer seasons and a client base that includes second-home buyers, vacation rental investors, and primary residence seekers all simultaneously. Boston and New York buyer spillover has made coastal Washington County one of the most reliably active markets in the state.',
    },
    {
        slug: 'north-kingstown',
        name: 'North Kingstown',
        county: 'Washington County',
        state: 'RI',
        zip: '02852',
        population: '26,000',
        median_price: '$419,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'North Kingstown anchors the upper end of South County, home to the charming historic Wickford Village on the shores of Narragansett Bay and a strong community of families who prize excellent schools and bay access. Its balance of residential quality, waterfront character, and highway access to Providence makes it one of Washington County\'s most well-rounded markets.',
        neighborhoods: 'Wickford Village, Saunderstown, Quidnessett, Hamilton',
        nearby: 'South Kingstown, Warwick, Narragansett, East Greenwich',
        seller_hook: 'North Kingstown\'s Wickford Village charm and Narragansett Bay waterfront are driving 8% appreciation as buyers discover a community that balances coastal beauty with practical Providence access. With inventory extremely tight across South County, motivated buyers are watching for every new listing in North Kingstown.',
        realtor_hook: 'North Kingstown\'s Wickford Village is one of Rhode Island\'s most photographable and marketable neighborhoods, giving agents a powerful visual story to tell across every platform. Boston commuter interest and Providence overflow create a broad buyer geographic that keeps leads flowing year-round.',
    },
    {
        slug: 'south-kingstown',
        name: 'South Kingstown',
        county: 'Washington County',
        state: 'RI',
        zip: '02879',
        population: '30,000',
        median_price: '$449,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'South Kingstown is the academic and cultural hub of Washington County, home to the University of Rhode Island\'s main campus, the charming village centers of Wakefield and Peace Dale, and a diverse range of properties from coastal beach communities to wooded equestrian estates. Its broad appeal generates consistent demand across buyer types.',
        neighborhoods: 'Peace Dale, Wakefield, Kingston, Matunuck, Green Hill',
        nearby: 'Narragansett, North Kingstown, Westerly, Charlestown',
        seller_hook: 'South Kingstown\'s University of Rhode Island anchor, beach village lifestyle, and 7% appreciation create year-round buyer demand from academics, families, and coastal lifestyle seekers — all competing for limited South County inventory. Sellers benefit from a market where multiple buyer types are always in the pipeline.',
        realtor_hook: 'South Kingstown\'s URI connection generates a built-in audience of faculty, staff, and alumni buyers who want to stay in the community long-term, supplemented by coastal lifestyle buyers from Boston and Providence. Agents who understand both the campus and coastal micro-markets can serve an exceptionally diverse client base.',
    },
    {
        slug: 'westerly',
        name: 'Westerly',
        county: 'Washington County',
        state: 'RI',
        zip: '02891',
        population: '23,000',
        median_price: '$379,000',
        price_trend: 'up 9%',
        avg_dom: 24,
        description: 'Westerly is Rhode Island\'s southwest coastal gem, bookended by the nationally renowned Watch Hill resort area and the mile-long Misquamicut Beach, with a vibrant downtown anchored by Amtrak access to Boston and New York. Its combination of beach, resort prestige, and transit connectivity makes it one of the state\'s most well-rounded coastal markets.',
        neighborhoods: 'Westerly Center, Watch Hill, Misquamicut Beach, Shelter Harbor',
        nearby: 'Charlestown, Stonington CT, Mystic CT, North Stonington CT',
        seller_hook: 'Westerly\'s Watch Hill cachet and Misquamicut Beach access are drawing buyers from New York and Boston who want a serious coastal address at prices that haven\'t yet reached the Hamptons or Cape Cod levels — and 9% appreciation confirms they are moving fast. Sellers with waterfront or village proximity hold exceptional cards in this market.',
        realtor_hook: 'Westerly\'s position at the Connecticut border and Amtrak connectivity mean its buyer pool extends from New York to Boston, giving local agents access to out-of-state buyers who are motivated, time-sensitive, and often pre-approved. Watch Hill\'s elite status and Misquamicut\'s family beach appeal create two distinct luxury and mass-market client segments in one town.',
    },
    {
        slug: 'charlestown',
        name: 'Charlestown',
        county: 'Washington County',
        state: 'RI',
        zip: '02813',
        population: '8,000',
        median_price: '$419,000',
        price_trend: 'up 8%',
        avg_dom: 27,
        description: 'Charlestown is Rhode Island\'s quietest and most naturally preserved coastal community, anchored by the pristine Ninigret Pond, miles of undeveloped barrier beach, and the Narragansett Indian tribal lands that give it a unique cultural character. Its low density and exceptional natural beauty attract buyers seeking a genuine coastal escape away from the crowds.',
        neighborhoods: 'Charlestown Beach, Quonochontaug, Ninigret Park area',
        nearby: 'Westerly, South Kingstown, Hopkinton, Richmond',
        seller_hook: 'Charlestown\'s undeveloped barrier beach and Ninigret Pond waterfront represent a rare and irreplaceable coastal asset — and 8% appreciation confirms that buyers who understand what can never be recreated here are acting decisively. With the lowest population density on Rhode Island\'s coast, your property is in a category all its own.',
        realtor_hook: 'Charlestown\'s natural scarcity — barrier beach, tidal pond access, state-protected open space — creates a buyer conviction that is unlike anywhere else on the Rhode Island coast, making properties here exceptionally easy to market to discerning outdoor enthusiasts and coastal lifestyle buyers. Boston and New York buyers especially prize Charlestown\'s unspoiled character.',
    },
];
