// cities/sc.js — South Carolina city data for SEO landing pages

module.exports = [
    {
        slug: 'charleston',
        name: 'Charleston',
        county: 'Charleston',
        state: 'SC',
        zip: '29401',
        population: '150000',
        median_price: '$850,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Charleston is one of America\'s most beloved cities — a stunningly preserved colonial port where antebellum architecture on the Historic Peninsula, world-class dining on King Street, and beach access on Sullivan\'s Island and Folly Beach combine with a booming aerospace and tech economy anchored by Boeing and Volvo to create one of the Southeast\'s most coveted real estate markets.',
        neighborhoods: 'Historic Peninsula, Harleston Village, Wagener Terrace, Cannonborough-Elliotborough, Radcliffeborough, Midtown Charleston',
        nearby: 'Mount Pleasant, West Ashley, James Island, North Charleston, Summerville',
        seller_hook: 'Charleston\'s global recognition and strict historic preservation keep supply constrained and prices rising — let top Charleston County realtors compete on RealtorFinder to earn your listing.',
        realtor_hook: 'Charleston\'s Historic Peninsula and national brand attract premium buyers from across the country — RealtorFinder connects you with motivated sellers in this iconic coastal market.',
    },
    {
        slug: 'mount-pleasant-sc',
        name: 'Mount Pleasant',
        county: 'Charleston',
        state: 'SC',
        zip: '29464',
        population: '94000',
        median_price: '$750,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Mount Pleasant is Charleston\'s most desirable suburb — an affluent East Cooper community across the Ravenel Bridge where Seaside Farms, Old Village, and I\'On neighborhoods attract buyers seeking top-ranked schools, easy downtown Charleston access, and proximity to Sullivan\'s Island and Isle of Palms beaches without the historic district\'s density.',
        neighborhoods: 'Old Village, I\'On, Seaside Farms, Park West, Belle Hall, Carolina Park, Dunes West',
        nearby: 'Charleston, Isle of Palms, Sullivan\'s Island, Awendaw, Georgetown SC',
        seller_hook: 'Mount Pleasant\'s top schools and East Cooper lifestyle drive some of Charleston\'s highest price-per-square-foot — let competing realtors on RealtorFinder maximize your sale.',
        realtor_hook: 'Mount Pleasant\'s affluent buyer base and proximity to Sullivan\'s Island create premium listing opportunities — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'west-ashley',
        name: 'West Ashley',
        county: 'Charleston',
        state: 'SC',
        zip: '29407',
        population: '78000',
        median_price: '$425,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'West Ashley is Charleston\'s largest and most established suburban corridor — a sprawling community along the Ashley River where neighborhoods like Byrnes Downs, Avondale, and Shadowmoss provide affordable entry points to the Charleston school district and quick downtown access that attract young professionals and families priced out of the Peninsula and Mount Pleasant.',
        neighborhoods: 'Byrnes Downs, Avondale, Shadowmoss, Seagate, Bees Ferry Road corridor, Lawton Bluff',
        nearby: 'Charleston, James Island, North Charleston, Summerville, Johns Island',
        seller_hook: 'West Ashley\'s affordable access to the Charleston school district and downtown keeps buyer demand consistent — let top Charleston County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'West Ashley\'s affordability relative to Mount Pleasant draws motivated first-time and move-up buyers — RealtorFinder connects you with sellers in this active Charleston corridor.',
    },
    {
        slug: 'johns-island',
        name: 'Johns Island',
        county: 'Charleston',
        state: 'SC',
        zip: '29455',
        population: '17000',
        median_price: '$520,000',
        price_trend: 'up 8%',
        avg_dom: 33,
        description: 'Johns Island is Charleston\'s last rural frontier — a sprawling Sea Island where ancient live oak corridors, Kiawah Island Resort proximity, working farmland, and master-planned communities like Stonoview and The Preserve attract buyers seeking land, privacy, and Lowcountry character at prices well below the Peninsula and Mount Pleasant.',
        neighborhoods: 'Stonoview, The Preserve at Fenwick Plantation, Brownswood, Stono Ferry, Maybank Highway corridor',
        nearby: 'Charleston, James Island, Kiawah Island, Edisto Island, West Ashley',
        seller_hook: 'Johns Island\'s Kiawah Island proximity and Lowcountry land appeal create strong appreciation — let competing Charleston County realtors on RealtorFinder fight for your listing.',
        realtor_hook: 'Johns Island\'s rapid development and Kiawah Island spillover demand make it one of Charleston\'s fastest-appreciating markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'james-island',
        name: 'James Island',
        county: 'Charleston',
        state: 'SC',
        zip: '29412',
        population: '25000',
        median_price: '$500,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'James Island is Charleston\'s laid-back coastal suburb — a tidal creek-laced community offering direct Folly Beach access and a five-minute bridge ride to downtown Charleston, where Camp Road and Folly Road corridors and neighborhoods like Riverland Terrace and Clearview attract buyers seeking beach lifestyle and urban proximity at still-reasonable Lowcountry prices.',
        neighborhoods: 'Riverland Terrace, Clearview, Westchester, Stiles Point, Ellis Oaks, McLeod Plantation vicinity',
        nearby: 'Charleston, West Ashley, Folly Beach, Johns Island, Kiawah Island',
        seller_hook: 'James Island\'s Folly Beach access and downtown proximity create consistent buyer demand — let top Charleston County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'James Island\'s beach lifestyle and quick downtown access attract motivated buyers seeking Lowcountry living at value — RealtorFinder connects you with sellers.',
    },
    {
        slug: 'north-charleston',
        name: 'North Charleston',
        county: 'Charleston',
        state: 'SC',
        zip: '29405',
        population: '115000',
        median_price: '$320,000',
        price_trend: 'up 6%',
        avg_dom: 32,
        description: 'North Charleston is the Charleston metro\'s industrial and logistics anchor — South Carolina\'s third-largest city where Boeing South Carolina\'s 787 Dreamliner facility and a massive Port of Charleston inland logistics cluster provide stable employment that keeps buyer demand for affordable Charleston County properties strong across neighborhoods from Park Circle to Dorchester Road.',
        neighborhoods: 'Park Circle, Waylyn, Wando, North Rhett corridor, Shipwatch Pointe, Pepperhill',
        nearby: 'Charleston, Summerville, Hanahan, Goose Creek, Ladson',
        seller_hook: 'North Charleston\'s Boeing and port employment keep affordable-market buyer demand active year-round — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'North Charleston\'s Boeing manufacturing and port logistics create a large, stable buyer pool — RealtorFinder connects you with motivated sellers in this affordable Charleston market.',
    },
    {
        slug: 'summerville-sc',
        name: 'Summerville',
        county: 'Dorchester',
        state: 'SC',
        zip: '29483',
        population: '54000',
        median_price: '$360,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Summerville is the Charleston metro\'s fastest-growing inland suburb — the Flower Town in the Pines where Nexton, Cane Bay Plantation, and Del Webb communities attract buyers seeking new construction, top Dorchester District 2 schools, and affordable Charleston metro access, supported by major employers including Volvo Cars USA\'s South Carolina headquarters.',
        neighborhoods: 'Nexton, Cane Bay Plantation, Del Webb Nexton, Pine Forest Country Club, Old Summerville, Scotch Hall',
        nearby: 'Charleston, Goose Creek, North Charleston, Ladson, Moncks Corner',
        seller_hook: 'Summerville\'s Volvo and new-construction boom drive strong appreciation across Dorchester County — let top local realtors on RealtorFinder compete to represent your home.',
        realtor_hook: 'Summerville\'s Nexton community and Volvo campus attract motivated buyers from across the Southeast — RealtorFinder connects you with sellers in one of South Carolina\'s hottest suburbs.',
    },
    {
        slug: 'goose-creek',
        name: 'Goose Creek',
        county: 'Berkeley',
        state: 'SC',
        zip: '29445',
        population: '44000',
        median_price: '$310,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'Goose Creek is Berkeley County\'s largest city and one of the Charleston metro\'s most affordable entry points — a military-influenced community near Naval Weapons Station Charleston where neighborhoods like Crowfield Plantation and Crowfield provide solid suburban value for military families, first-time buyers, and logistics workers seeking Charleston access.',
        neighborhoods: 'Crowfield Plantation, Crowfield, Medley Park, Devon Forest, Cypress Preserve, Hunters Bend',
        nearby: 'Summerville, North Charleston, Hanahan, Ladson, Moncks Corner',
        seller_hook: 'Goose Creek\'s military base proximity and affordability attract steady buyer demand — let competitive Berkeley County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Goose Creek\'s Naval Weapons Station and affordable price point attract a large, motivated military and first-time buyer pool — RealtorFinder connects you with sellers.',
    },
    {
        slug: 'hanahan',
        name: 'Hanahan',
        county: 'Berkeley',
        state: 'SC',
        zip: '29410',
        population: '25000',
        median_price: '$330,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'Hanahan is Berkeley County\'s most strategically located city — a compact, well-maintained community directly adjacent to North Charleston where Tanner Plantation and Otranto Club neighborhoods offer affordable homeownership with immediate access to Boeing, the Charleston airport, and I-26, making it a practical choice for aviation and aerospace professionals.',
        neighborhoods: 'Tanner Plantation, Otranto Club, Hanahan Village, Bear Swamp, Otranto Road corridor',
        nearby: 'North Charleston, Goose Creek, Ladson, Summerville, Charleston',
        seller_hook: 'Hanahan\'s Boeing and airport proximity keep buyer demand active — let competing Berkeley County realtors on RealtorFinder fight to earn the right to represent your home.',
        realtor_hook: 'Hanahan\'s aerospace corridor and affordable prices attract practical, motivated buyers — RealtorFinder connects you with sellers in this Charleston-adjacent market.',
    },
    {
        slug: 'ladson',
        name: 'Ladson',
        county: 'Berkeley',
        state: 'SC',
        zip: '29456',
        population: '14000',
        median_price: '$300,000',
        price_trend: 'up 6%',
        avg_dom: 31,
        description: 'Ladson is the Charleston metro\'s most affordable entry point — an unincorporated Berkeley County community at the crossroads of I-26 and Highway 78 where College Park and Gainsborough communities offer affordable single-family homes attractive to first-time buyers, logistics workers, and Summerville commuters seeking value in a market just minutes from major employment centers.',
        neighborhoods: 'College Park, Gainsborough, Summer Glen, Indigo Fields, Brentwood East',
        nearby: 'Summerville, Goose Creek, North Charleston, Hanahan, Moncks Corner',
        seller_hook: 'Ladson\'s lowest-cost-of-entry position in the Charleston metro drives consistent first-time buyer activity — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Ladson\'s affordability relative to the broader Charleston market creates a reliable pipeline of motivated first-time buyers — RealtorFinder connects you with sellers.',
    },
    {
        slug: 'columbia-sc',
        name: 'Columbia',
        county: 'Richland',
        state: 'SC',
        zip: '29201',
        population: '136000',
        median_price: '$245,000',
        price_trend: 'up 5%',
        avg_dom: 33,
        description: 'Columbia is South Carolina\'s state capital and home to the University of South Carolina — a government, military, and university city where Fort Jackson, one of the nation\'s largest Army training installations, and USC\'s 35,000-student campus anchor a diverse buyer market spanning established neighborhoods like Forest Acres and Five Points to the Cayce and West Columbia corridor.',
        neighborhoods: 'Forest Acres, Five Points, Shandon, Elmwood Park, Cayce, North Main, Vista',
        nearby: 'Lexington, Irmo, Chapin, West Columbia, Cayce',
        seller_hook: 'Columbia\'s USC and Fort Jackson demand create year-round buyer activity — let top Richland County realtors on RealtorFinder compete to maximize your sale.',
        realtor_hook: 'Columbia\'s state government, USC enrollment, and Fort Jackson training cycles create a diverse, consistent buyer pipeline — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'lexington-sc',
        name: 'Lexington',
        county: 'Lexington',
        state: 'SC',
        zip: '29072',
        population: '24000',
        median_price: '$320,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'Lexington is the Columbia metro\'s premier suburban destination — a rapidly growing Lexington County town on Lake Murray known for top-ranked schools in Lexington School District One, a thriving Main Street and Icehouse Amphitheatre venue, and master-planned communities like Lake Murray Estates and Saluda River Club attracting Columbia commuters and retirees alike.',
        neighborhoods: 'Lake Murray Estates, Saluda River Club, Barr Road corridor, Old Chapin Road area, Main Street vicinity',
        nearby: 'Columbia, Irmo, Chapin, West Columbia, Batesburg-Leesville',
        seller_hook: 'Lexington\'s District One schools and Lake Murray access drive premium demand in the Columbia metro — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Lexington\'s top-ranked schools and Lake Murray waterfront lifestyle attract motivated buyers from across the Midlands — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'irmo',
        name: 'Irmo',
        county: 'Richland',
        state: 'SC',
        zip: '29063',
        population: '12000',
        median_price: '$295,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Irmo is the Columbia metro\'s lakeside suburb — a well-established Richland County community on the eastern shores of Lake Murray where St. Andrews Road and Bush River Road corridors and neighborhoods like Harbison and Dutch Square offer affordable family living with Lexington District Five schools and easy I-26 access to downtown Columbia.',
        neighborhoods: 'Harbison, Dutch Square, Lake Murray Boulevard corridor, Shull Island, Ballentine',
        nearby: 'Columbia, Lexington, Chapin, Dentsville, Dutch Fork',
        seller_hook: 'Irmo\'s Lake Murray access and Columbia commutability attract steady buyer demand — let competitive Richland County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Irmo\'s Harbison commercial corridor and Lake Murray proximity keep buyers active in this affordable Columbia suburb — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'greenville-sc',
        name: 'Greenville',
        county: 'Greenville',
        state: 'SC',
        zip: '29601',
        population: '72000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Greenville is one of America\'s top urban revival success stories — a former textile hub reinvented around a world-class Main Street, a BMW and Michelin manufacturing corridor, and a nationally recognized Falls Park waterfall in the heart of downtown, creating a market where Augusta Road\'s historic bungalows and North Main\'s Craftsmans command premium prices from in-migrants nationwide.',
        neighborhoods: 'North Main, Augusta Road, Sans Souci, West Greenville, East Park, Overbrook, Haywood Road',
        nearby: 'Simpsonville, Mauldin, Taylors, Greer, Spartanburg',
        seller_hook: 'Greenville\'s nationally recognized Main Street and BMW-Michelin economy drive strong appreciation — let top Greenville County realtors on RealtorFinder compete for your listing.',
        realtor_hook: 'Greenville\'s national recognition and manufacturing economy create a steady flow of well-qualified buyers — RealtorFinder connects you with motivated sellers in this Upstate gem.',
    },
    {
        slug: 'spartanburg',
        name: 'Spartanburg',
        county: 'Spartanburg',
        state: 'SC',
        zip: '29301',
        population: '38000',
        median_price: '$295,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'Spartanburg is the Upstate\'s industrial and college hub — a city of seven colleges anchored by Wofford and Converse, a thriving Morgan Square downtown, and an unmatched manufacturing base including BMW\'s North American headquarters at nearby Greer that creates strong buyer demand from international executives and assembly workers alike.',
        neighborhoods: 'Morgan Square area, Converse Heights, Duncan Park, Hillbrook, Drayton Mills Marketplace, North Spartanburg',
        nearby: 'Greenville, Greer, Boiling Springs, Gaffney, Chesnee',
        seller_hook: 'Spartanburg\'s seven colleges and BMW proximity keep buyer demand active year-round — let competing Spartanburg County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Spartanburg\'s BMW and Michelin employment base and Wofford enrollment create a diverse, motivated buyer pool — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'mauldin',
        name: 'Mauldin',
        county: 'Greenville',
        state: 'SC',
        zip: '29662',
        population: '26000',
        median_price: '$350,000',
        price_trend: 'up 7%',
        avg_dom: 27,
        description: 'Mauldin is Greenville\'s fastest-growing southern suburb — a vibrant Greenville County city where Woodruff Road\'s retail corridor, Heritage Park Amphitheater, and communities like Butler Springs and Westchester offer Greenville school access and I-385 convenience at prices well below Greenville\'s North Main neighborhood, drawing young families and BMW-corridor commuters.',
        neighborhoods: 'Butler Springs, Westchester, Mauldin Road corridor, Hunters Chase, Wycombe',
        nearby: 'Greenville, Simpsonville, Fountain Inn, Woodruff, Greer',
        seller_hook: 'Mauldin\'s Woodruff Road amenities and Greenville school proximity drive strong buyer competition — let competing Greenville County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Mauldin\'s affordability relative to downtown Greenville and its BMW-corridor access create a motivated buyer pipeline — RealtorFinder connects you with sellers.',
    },
    {
        slug: 'simpsonville',
        name: 'Simpsonville',
        county: 'Greenville',
        state: 'SC',
        zip: '29680',
        population: '25000',
        median_price: '$360,000',
        price_trend: 'up 7%',
        avg_dom: 27,
        description: 'Simpsonville is Greenville County\'s booming southeastern suburb — a rapidly growing city where Harrison Bridge Road and Fairview Road corridors anchor new-construction communities like Gilder Creek Farm and Durbin Crossing, drawing buyers who prize Greenville District 5 schools, Pelham Medical Center access, and below-Greenville prices in a market with strong appreciation momentum.',
        neighborhoods: 'Gilder Creek Farm, Durbin Crossing, Neely Farm, Five Forks area, Fairview Road corridor',
        nearby: 'Greenville, Mauldin, Fountain Inn, Woodruff, Greer',
        seller_hook: 'Simpsonville\'s Greenville District 5 schools and new-construction boom drive strong consistent appreciation — let top local realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Simpsonville\'s new-community development and Five Forks growth corridor attract buyers throughout the year — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'myrtle-beach',
        name: 'Myrtle Beach',
        county: 'Horry',
        state: 'SC',
        zip: '29577',
        population: '35000',
        median_price: '$350,000',
        price_trend: 'up 6%',
        avg_dom: 35,
        description: 'Myrtle Beach is South Carolina\'s coastal tourism capital — the Grand Strand\'s urban core where 60 miles of beaches, over 100 golf courses, Broadway at the Beach entertainment, and a massive year-round tourism economy draw retirees, second-home buyers, and investment property buyers from across the East Coast into one of the Southeast\'s most active real estate markets.',
        neighborhoods: 'Market Common, Grande Dunes, Carolina Forest, Pine Lakes, Socastee, Conway vicinity',
        nearby: 'North Myrtle Beach, Conway, Pawleys Island, Surfside Beach, Murrell\'s Inlet',
        seller_hook: 'Myrtle Beach\'s resort-market demand and year-round tourism keep buyer interest strong — let competitive Grand Strand realtors on RealtorFinder maximize your sale.',
        realtor_hook: 'Myrtle Beach\'s massive retiree and second-home buyer market creates consistent listing opportunities — RealtorFinder connects you with motivated sellers along the Grand Strand.',
    },
    {
        slug: 'pawleys-island',
        name: 'Pawleys Island',
        county: 'Georgetown',
        state: 'SC',
        zip: '29585',
        population: '200',
        median_price: '$550,000',
        price_trend: 'up 5%',
        avg_dom: 40,
        description: 'Pawleys Island is the Grand Strand\'s most exclusive coastal enclave — one of America\'s oldest summer resort destinations where historic hammock shops, antique strand architecture, and a laid-back barrier island character attract affluent buyers seeking a more understated Lowcountry beach lifestyle compared to Myrtle Beach, supported by nearby Litchfield Beach and Caledonia golf communities.',
        neighborhoods: 'Litchfield Beach, Tradition, Heritage Plantation, Caledonia Golf community, Hagley Estates',
        nearby: 'Myrtle Beach, Murrells Inlet, Georgetown SC, Surfside Beach, Conway',
        seller_hook: 'Pawleys Island\'s historic barrier island character and scarcity of new inventory command Grand Strand premiums — let top Georgetown County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Pawleys Island\'s affluent second-home buyer market and exclusive coastal identity create high-value listing opportunities — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'conway-sc',
        name: 'Conway',
        county: 'Horry',
        state: 'SC',
        zip: '29526',
        population: '24000',
        median_price: '$285,000',
        price_trend: 'up 6%',
        avg_dom: 32,
        description: 'Conway is Horry County\'s charming inland seat and Coastal Carolina University\'s home — a historic riverfront city on the Waccamaw River where a beautifully preserved Riverwalk district, CCU\'s 10,000-student campus, and the most affordable price points in the Grand Strand market attract buyers seeking beach access at inland prices.',
        neighborhoods: 'Riverwalk area, Carolina Forest vicinity, Coastal Carolina University area, Kingston, Aynor Road corridor',
        nearby: 'Myrtle Beach, North Myrtle Beach, Loris, Aynor, Longs',
        seller_hook: 'Conway\'s CCU economy and Grand Strand proximity keep buyer activity consistent — let competing Horry County realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Conway\'s CCU enrollment and Myrtle Beach proximity create motivated buyers at the Grand Strand\'s most affordable price points — RealtorFinder connects you with sellers.',
    },
    {
        slug: 'hilton-head-island',
        name: 'Hilton Head Island',
        county: 'Beaufort',
        state: 'SC',
        zip: '29928',
        population: '40000',
        median_price: '$650,000',
        price_trend: 'up 4%',
        avg_dom: 42,
        description: 'Hilton Head Island is South Carolina\'s premier resort destination — a world-renowned barrier island where Sea Pines Resort, Harbour Town Golf Links, and 12 miles of pristine beaches anchor a real estate market dominated by luxury second homes, resort villas, and retirement properties bought by buyers from across the eastern United States and Europe seeking the ultimate Lowcountry lifestyle.',
        neighborhoods: 'Sea Pines, Shipyard Plantation, Palmetto Dunes, Port Royal Plantation, Indigo Run, Long Cove Club',
        nearby: 'Bluffton, Savannah GA, Daufuskie Island, Beaufort SC, Okatie',
        seller_hook: 'Hilton Head\'s global resort reputation and scarce beachfront inventory consistently command South Carolina\'s highest prices — let specialized Beaufort County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Hilton Head\'s affluent second-home buyer market and resort plantation demand create South Carolina\'s most lucrative listing opportunities — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'bluffton',
        name: 'Bluffton',
        county: 'Beaufort',
        state: 'SC',
        zip: '29910',
        population: '27000',
        median_price: '$480,000',
        price_trend: 'up 6%',
        avg_dom: 30,
        description: 'Bluffton is the Lowcountry\'s fastest-growing community — a vibrant Beaufort County town on the May River where the eclectic Old Town village, Palmetto Bluff\'s ultra-luxury resort community, and master-planned Sun City Hilton Head retirement enclave attract buyers seeking Hilton Head and Savannah access with new-construction pricing and a thriving local character all its own.',
        neighborhoods: 'Old Town Bluffton, Palmetto Bluff, Sun City Hilton Head, Hampton Lake, Belfair, Berkeley Hall',
        nearby: 'Hilton Head Island, Savannah GA, Hardeeville, Okatie, Beaufort SC',
        seller_hook: 'Bluffton\'s Palmetto Bluff cachet and Sun City retirement demand drive strong Beaufort County appreciation — let top local realtors on RealtorFinder compete for your listing.',
        realtor_hook: 'Bluffton\'s Sun City retiree pipeline and Palmetto Bluff luxury demand create premium listing opportunities — RealtorFinder connects you with motivated sellers in this Lowcountry boom town.',
    },
];
