// cities/sd.js — South Dakota city data for SEO landing pages

module.exports = [
    {
        slug: 'sioux-falls',
        name: 'Sioux Falls',
        county: 'Minnehaha',
        state: 'SD',
        zip: '57104',
        population: '196,000',
        median_price: '$295,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'Sioux Falls is South Dakota\'s largest city and one of the Midwest\'s best-kept economic secrets — a financial services powerhouse where Citibank, Wells Fargo, and dozens of credit card companies chose South Dakota\'s zero income and corporate tax environment, creating a professional class that drives housing demand in a metro consistently ranked among the nation\'s best for job growth, affordability, and quality of life.',
        neighborhoods: 'Downtown, Falls Park, McKennan Park, Tea, Brandon, Harrisburg',
        nearby: 'Brandon, Tea, Harrisburg, Dell Rapids, Baltic',
        seller_hook: 'Sioux Falls\' financial sector growth and zero income tax attract buyers from across the Midwest — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Sioux Falls\' consistent appreciation and corporate relocation market create high-volume listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'rapid-city',
        name: 'Rapid City',
        county: 'Pennington',
        state: 'SD',
        zip: '57701',
        population: '77,000',
        median_price: '$310,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Rapid City is the Gateway to the Black Hills and Mount Rushmore\'s nearest urban hub — a tourism, military, and healthcare city where Ellsworth Air Force Base, Rapid City Regional Hospital, and South Dakota School of Mines create housing demand from military families, medical workers, and buyers drawn by ponderosa pine scenery, Badlands access, and one of the West\'s most affordable outdoor lifestyle markets.',
        neighborhoods: 'West Rapid City, North Rapid City, Box Elder, Summerset, Piedmont',
        nearby: 'Box Elder, Summerset, Piedmont, Hill City, Spearfish',
        seller_hook: 'Rapid City\'s Black Hills lifestyle and Ellsworth AFB drive consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Rapid City\'s military and tourism market create active listing conditions at the foot of the Black Hills — find sellers through RealtorFinder.',
    },
    {
        slug: 'aberdeen-sd',
        name: 'Aberdeen',
        county: 'Brown',
        state: 'SD',
        zip: '57401',
        population: '28,000',
        median_price: '$195,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Aberdeen is northeastern South Dakota\'s Hub City — a regional commercial and medical center where Northern State University, Avera St. Luke\'s Hospital, and an agricultural services economy create demand for affordable ranch homes among first-time buyers, students, and farm families who appreciate South Dakota\'s zero income tax and some of the Great Plains\' lowest home prices.',
        neighborhoods: 'East Aberdeen, West Aberdeen, Columbia, Groton, Redfield',
        nearby: 'Watertown, Huron, Mitchell, Brookings, Ipswich',
        seller_hook: 'Aberdeen\'s NSU enrollment and medical hub drive steady buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Aberdeen\'s agricultural and medical economy create consistent listing activity at Great Plains prices — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'brookings-sd',
        name: 'Brookings',
        county: 'Brookings',
        state: 'SD',
        zip: '57006',
        population: '25,000',
        median_price: '$235,000',
        price_trend: 'up 6%',
        avg_dom: 25,
        description: 'Brookings is home to South Dakota State University and the academic heart of South Dakota — a Jackrabbits college town on the eastern prairie where SDSU\'s engineering and agricultural research programs, the South Dakota Art Museum, and a growing biotech sector create housing demand from students, faculty, and young professionals who find an unusually vibrant college community on the Minnesota border.',
        neighborhoods: 'University, Brookings North, Aurora, Volga, Sinai',
        nearby: 'Volga, Aurora, De Smet, Flandreau, Madison SD',
        seller_hook: 'Brookings\' SDSU enrollment and tech sector create strong buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Brookings\' university market and eastern South Dakota growth create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'watertown-sd',
        name: 'Watertown',
        county: 'Codington',
        state: 'SD',
        zip: '57201',
        population: '22,000',
        median_price: '$190,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Watertown is northeast South Dakota\'s largest city and a manufacturing hub on Lake Kampeska — a community where 3M, Raven Industries, and agricultural processing create stable blue-collar employment, while affordable single-family homes, excellent lake recreation, and South Dakota\'s zero income tax attract first-time buyers and retirees seeking the most accessible homeownership in the upper Midwest.',
        neighborhoods: 'East Watertown, North Watertown, Castlewood, Henry, Estelline',
        nearby: 'Brookings, Aberdeen, Clear Lake, Milbank, Florence',
        seller_hook: 'Watertown\'s manufacturing economy and lake lifestyle attract value-seeking buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Watertown\'s industrial market and Great Plains affordability create consistent listing activity — find sellers through RealtorFinder.',
    },
];
