// cities/tn.js — Tennessee city data for SEO landing pages

module.exports = [
    {
        slug: 'nashville',
        name: 'Nashville',
        county: 'Davidson',
        state: 'TN',
        zip: '37201',
        population: '689000',
        median_price: '$550,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Nashville is the Music City and one of America\'s fastest-growing metros — a booming entertainment, healthcare, and tech economy anchored by Vanderbilt University Medical Center, Amazon\'s Operations HQ, and a vibrant downtown with neighborhoods like 12South, East Nashville, and The Gulch drawing buyers from across the country.',
        neighborhoods: '12South, East Nashville, The Gulch, Germantown, Green Hills, Sylvan Park, Belmont-Hillsboro',
        nearby: 'Brentwood, Franklin, Hendersonville, Mount Juliet, Nolensville',
        seller_hook: 'Nashville\'s relentless in-migration and corporate expansions keep buyer demand fierce — let top Davidson County realtors compete on RealtorFinder to earn your listing.',
        realtor_hook: 'Nashville\'s Music City economy and nationally ranked growth make it one of the Southeast\'s strongest listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'brentwood',
        name: 'Brentwood',
        county: 'Williamson',
        state: 'TN',
        zip: '37027',
        population: '45000',
        median_price: '$875,000',
        price_trend: 'up 4%',
        avg_dom: 24,
        description: 'Brentwood is Nashville\'s most prestigious suburb — an affluent community in Williamson County featuring top-ranked public schools, country club estates in Governors Club and Otter Creek, and a corporate corridor hosting Dell Technologies, Deloitte, and Tractor Supply Company headquarters that draws executive-level buyers from across the country.',
        neighborhoods: 'Governors Club, Otter Creek, Concord Road corridor, Maryland Farms, Brentwood Hills',
        nearby: 'Franklin, Nashville, Nolensville, Spring Hill, Oak Hill',
        seller_hook: 'Brentwood\'s elite schools and Fortune 500 corporate campus demand consistently command premium prices — let top Williamson County realtors on RealtorFinder compete for your listing.',
        realtor_hook: 'Brentwood\'s affluent buyer pool and top-tier school reputation create some of Tennessee\'s strongest listing opportunities — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'franklin-tn',
        name: 'Franklin',
        county: 'Williamson',
        state: 'TN',
        zip: '37064',
        population: '83000',
        median_price: '$850,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'Franklin is Williamson County\'s crown jewel — a beautifully preserved Civil War-era downtown anchoring a booming suburb where Cool Springs corporate park hosts dozens of major employers, master-planned communities like Westhaven and Berry Farms attract premium buyers, and top-ranked schools make it a perennial relocation destination.',
        neighborhoods: 'Westhaven, Berry Farms, Historic Downtown Franklin, Cool Springs, McKay\'s Mill, Fieldstone Farms',
        nearby: 'Brentwood, Nashville, Spring Hill, Nolensville, Columbia',
        seller_hook: 'Franklin\'s beloved downtown and Williamson County school system drive premium buyer demand — let competing Franklin realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Franklin\'s Cool Springs corporate corridor and master-planned communities deliver a steady flow of well-qualified buyers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'murfreesboro',
        name: 'Murfreesboro',
        county: 'Rutherford',
        state: 'TN',
        zip: '37130',
        population: '152000',
        median_price: '$420,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'Murfreesboro is one of America\'s fastest-growing mid-sized cities — a dynamic Rutherford County hub anchored by Middle Tennessee State University, a booming healthcare sector at Saint Thomas Rutherford Hospital, and sprawling new-construction communities in Blackman and Barfield that attract young families priced out of Williamson County.',
        neighborhoods: 'Blackman, Barfield, Downtown Murfreesboro, Broad Street corridor, Cason Lane, Indian Hills',
        nearby: 'Smyrna, La Vergne, Nashville, Franklin, Shelbyville',
        seller_hook: 'Murfreesboro\'s explosive population growth and MTSU economy drive relentless buyer demand — let competitive Rutherford County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Murfreesboro\'s MTSU enrollment and healthcare sector keep buyers active year-round — RealtorFinder connects you with motivated sellers in one of Tennessee\'s fastest-growing markets.',
    },
    {
        slug: 'columbia-tn',
        name: 'Columbia',
        county: 'Maury',
        state: 'TN',
        zip: '38401',
        population: '42000',
        median_price: '$420,000',
        price_trend: 'up 7%',
        avg_dom: 31,
        description: 'Columbia is Maury County\'s fast-rising seat — a charming small city with a revitalizing historic downtown that has attracted major industrial investment including a massive GM battery plant and multiple automotive suppliers, creating a new wave of buyer demand from manufacturing professionals and Nashville commuters seeking more affordable homeownership.',
        neighborhoods: 'Historic Downtown Columbia, Woodland Hills, Riverview, Hampton Hills, Camelot',
        nearby: 'Franklin, Spring Hill, Nashville, Lewisburg, Mount Pleasant',
        seller_hook: 'Columbia\'s GM battery plant and manufacturing boom are driving rapid appreciation — let competitive Maury County realtors on RealtorFinder maximize your sale.',
        realtor_hook: 'Columbia\'s surging industrial economy and proximity to Franklin create a motivated buyer pipeline — RealtorFinder connects you with sellers in this high-growth market.',
    },
    {
        slug: 'nolensville',
        name: 'Nolensville',
        county: 'Williamson',
        state: 'TN',
        zip: '37135',
        population: '14000',
        median_price: '$520,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Nolensville is Williamson County\'s most sought-after small town — a charming, rapidly growing community just south of Nashville where Bent Creek and Scales Farmstead master-planned neighborhoods attract buyers seeking top-ranked schools, tight-knit community character, and reasonable prices compared to Brentwood and Franklin.',
        neighborhoods: 'Bent Creek, Scales Farmstead, Brittain Downs, Rocky Fork, Nolensville Town Center',
        nearby: 'Brentwood, Franklin, Nashville, Spring Hill, Smyrna',
        seller_hook: 'Nolensville\'s small-town appeal combined with Williamson County schools creates intense buyer competition — let top local realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Nolensville\'s booming new construction and Williamson County school access make it one of Tennessee\'s hottest small-town listing markets — RealtorFinder connects you with sellers.',
    },
    {
        slug: 'spring-hill-tn',
        name: 'Spring Hill',
        county: 'Williamson',
        state: 'TN',
        zip: '37174',
        population: '50000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Spring Hill straddles Williamson and Maury counties and has transformed from a General Motors factory town into one of Middle Tennessee\'s most desirable family suburbs — extensive new-construction communities like Autumn Ridge and Bridgemore Village offering Williamson County schools at prices well below Brentwood and Franklin.',
        neighborhoods: 'Autumn Ridge, Bridgemore Village, Reserve at Spring Hill, Port Royal Estates, Hidden Valley',
        nearby: 'Franklin, Columbia, Brentwood, Nolensville, Nashville',
        seller_hook: 'Spring Hill\'s GM heritage and booming suburb status drive strong buyer demand — let competing Williamson-Maury County realtors on RealtorFinder fight for your listing.',
        realtor_hook: 'Spring Hill\'s rapid growth and GM Corvette plant keep buyer traffic strong — RealtorFinder connects you with motivated sellers in one of Middle Tennessee\'s fastest-growing suburbs.',
    },
    {
        slug: 'hendersonville',
        name: 'Hendersonville',
        county: 'Sumner',
        state: 'TN',
        zip: '37075',
        population: '64000',
        median_price: '$450,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Hendersonville is Nashville\'s premier lakeside suburb — a beautiful Sumner County community on Old Hickory Lake where waterfront estates and established neighborhoods like Indian Lake and Drakes Creek attract buyers seeking Nashville commutability with a slower, lakeside pace that remains more affordable than Davidson County options.',
        neighborhoods: 'Indian Lake, Drakes Creek, Sanders Ferry, Walton Ferry, Durham Farms, Long Hollow',
        nearby: 'Nashville, Gallatin, Mount Juliet, Goodlettsville, Millersville',
        seller_hook: 'Hendersonville\'s Old Hickory Lake setting and Nashville proximity drive consistent premium demand — let competitive Sumner County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Hendersonville\'s lakeside lifestyle and Nashville commuters create strong buyer activity — RealtorFinder connects you with motivated sellers across Sumner County.',
    },
    {
        slug: 'mount-juliet',
        name: 'Mount Juliet',
        county: 'Wilson',
        state: 'TN',
        zip: '37122',
        population: '40000',
        median_price: '$470,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Mount Juliet is Wilson County\'s booming Nashville suburb — one of Tennessee\'s fastest-growing cities where Providence Marketplace has anchored a retail and residential corridor and neighborhoods like Beckwith Farms and Providence Point attract Nashville commuters seeking newer homes with good schools at prices still below Davidson County.',
        neighborhoods: 'Beckwith Farms, Providence Point, Green Hill, Curd Road corridor, Bel Aire',
        nearby: 'Nashville, Lebanon, Hermitage, Hendersonville, Smyrna',
        seller_hook: 'Mount Juliet\'s explosive growth and Nashville access keep buyer competition strong — let top Wilson County realtors on RealtorFinder maximize your home\'s value.',
        realtor_hook: 'Mount Juliet\'s consistent in-migration and new-construction demand create a vibrant listing pipeline — RealtorFinder connects you with motivated sellers in this growing suburb.',
    },
    {
        slug: 'smyrna-tn',
        name: 'Smyrna',
        county: 'Rutherford',
        state: 'TN',
        zip: '37167',
        population: '57000',
        median_price: '$420,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Smyrna is Rutherford County\'s industrial and residential powerhouse — home to the massive Nissan North America manufacturing plant, a growing aerospace sector at Smyrna Airport, and established neighborhoods like Elam Farms and Rocky River that attract buyers seeking affordable homeownership with strong employer access and interstate convenience.',
        neighborhoods: 'Elam Farms, Rocky River, Sam Ridley Parkway corridor, Hazelwood Farms, Beesley Road area',
        nearby: 'Murfreesboro, La Vergne, Nashville, Nolensville, Lavergne',
        seller_hook: 'Smyrna\'s Nissan plant and industrial economy drive steady buyer demand — let competing Rutherford County realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Smyrna\'s manufacturing economy and affordable price point attract first-time and move-up buyers alike — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'memphis',
        name: 'Memphis',
        county: 'Shelby',
        state: 'TN',
        zip: '38101',
        population: '633000',
        median_price: '$195,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Memphis is Tennessee\'s Blues City and logistics capital of North America — home to FedEx World Headquarters, the busiest cargo airport on the planet, and a deeply rooted cultural identity built around Beale Street, the Stax Museum, and iconic neighborhoods like Cooper-Young, Midtown, and Germantown Road corridors.',
        neighborhoods: 'Cooper-Young, Midtown, East Memphis, Downtown, Cordova, Bartlett border, Harbor Town',
        nearby: 'Germantown, Collierville, Bartlett, Olive Branch MS, Southaven MS',
        seller_hook: 'Memphis\'s FedEx-driven logistics economy and low prices attract investors and first-time buyers — let competitive Shelby County realtors on RealtorFinder fight for your listing.',
        realtor_hook: 'Memphis\'s logistics economy and strong rental demand create a consistent buyer pipeline — RealtorFinder connects you with motivated sellers across Shelby County.',
    },
    {
        slug: 'germantown-tn',
        name: 'Germantown',
        county: 'Shelby',
        state: 'TN',
        zip: '38138',
        population: '40000',
        median_price: '$510,000',
        price_trend: 'up 4%',
        avg_dom: 28,
        description: 'Germantown is the Memphis metro\'s most prestigious suburb — a carefully planned East Memphis community known for the Village Shops at Saddle Creek, perennially top-ranked schools, equestrian-estate neighborhoods along Poplar Avenue, and a civic character that has consistently earned it recognition as one of Tennessee\'s best places to raise a family.',
        neighborhoods: 'Thornwood, Forest Hill Irene, South Germantown, Farmington, Kimbrough Cove',
        nearby: 'Collierville, Memphis, Bartlett, Cordova, Collierville',
        seller_hook: 'Germantown\'s elite school reputation and Saddle Creek amenities command Memphis metro premiums — let top Shelby County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Germantown\'s affluent buyer base and top-ranked schools make it the Memphis metro\'s most dependable listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'collierville',
        name: 'Collierville',
        county: 'Shelby',
        state: 'TN',
        zip: '38017',
        population: '52000',
        median_price: '$480,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Collierville is Shelby County\'s southeastern gem — a thriving town with a historic, walkable Town Square surrounded by master-planned communities like Byhalia Road estates and Schilling Farms, anchored by FedEx campus proximity and consistently high school rankings that draw Memphis professionals seeking suburban character with urban amenities.',
        neighborhoods: 'Schilling Farms, Town Square area, Byhalia Road corridor, Houston Levee East, Forest Hill',
        nearby: 'Germantown, Memphis, Olive Branch MS, Hernando MS, Bartlett',
        seller_hook: 'Collierville\'s beloved Town Square and elite schools drive buyer demand — let competing Shelby County realtors on RealtorFinder maximize your sale price.',
        realtor_hook: 'Collierville\'s FedEx proximity and top school ratings keep buyers motivated — RealtorFinder connects you with sellers in one of the Memphis metro\'s best-performing markets.',
    },
    {
        slug: 'bartlett',
        name: 'Bartlett',
        county: 'Shelby',
        state: 'TN',
        zip: '38135',
        population: '58000',
        median_price: '$320,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Bartlett is the Memphis metro\'s most affordable family suburb — a well-established Shelby County community with decades of residential development, solid public schools, easy access to the I-40 and I-240 corridors, and established neighborhoods like Stage Road and Appling Farms providing family-friendly value for buyers priced out of Germantown and Collierville.',
        neighborhoods: 'Appling Farms, Elmore Park, Stage Road corridor, Bartlett Station, Sycamore View',
        nearby: 'Memphis, Germantown, Cordova, Lakeland, Arlington TN',
        seller_hook: 'Bartlett\'s family-friendly affordability and established neighborhoods attract a consistent buyer pool — let competing Shelby County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Bartlett\'s affordability and family appeal keep first-time and move-up buyers active year-round — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'chattanooga',
        name: 'Chattanooga',
        county: 'Hamilton',
        state: 'TN',
        zip: '37401',
        population: '181000',
        median_price: '$380,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Chattanooga is one of America\'s great urban revival stories — a former industrial city that reinvented itself with the world\'s first gigabit municipal fiber network, a booming outdoor recreation economy anchored by Rock City and Lookout Mountain, and revitalized urban neighborhoods like Northshore and Southside attracting tech workers and creatives nationwide.',
        neighborhoods: 'Northshore, Southside, Highland Park, East Brainerd, St. Elmo, Missionary Ridge, Hixson',
        nearby: 'Lookout Mountain, Ooltewah, Cleveland TN, Red Bank, Signal Mountain',
        seller_hook: 'Chattanooga\'s national tech and outdoor-recreation reputation draws buyers from across the country — let top Hamilton County realtors on RealtorFinder compete for your listing.',
        realtor_hook: 'Chattanooga\'s gigabit fiber, Volkswagen plant, and mountain lifestyle attract motivated buyers from major metros — RealtorFinder connects you with sellers in this surging market.',
    },
    {
        slug: 'lookout-mountain',
        name: 'Lookout Mountain',
        county: 'Hamilton',
        state: 'TN',
        zip: '37350',
        population: '2000',
        median_price: '$625,000',
        price_trend: 'up 5%',
        avg_dom: 42,
        description: 'Lookout Mountain is Chattanooga\'s most exclusive address — a small, elevated community straddling the Tennessee-Georgia border atop the iconic Civil War battlefield plateau where historic estate homes, sweeping Tennessee Valley views, and proximity to Rock City and Point Park attract buyers seeking a once-in-a-generation mountain lifestyle property.',
        neighborhoods: 'Scenic Highway corridor, Covenant College vicinity, Tennessee-Georgia state line area, Lula Lake Road area',
        nearby: 'Chattanooga, Fort Oglethorpe GA, Chickamauga GA, Signal Mountain, Ringgold GA',
        seller_hook: 'Lookout Mountain\'s rare inventory and iconic views consistently command Chattanooga\'s highest premiums — let specialized Hamilton County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Lookout Mountain\'s limited inventory and trophy-property demand create some of the Chattanooga metro\'s best commission opportunities — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'ooltewah',
        name: 'Ooltewah',
        county: 'Hamilton',
        state: 'TN',
        zip: '37363',
        population: '7000',
        median_price: '$440,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Ooltewah is Hamilton County\'s fastest-growing bedroom community — a suburban unincorporated area along the I-75 corridor southeast of Chattanooga where Cambridge Square, Windstone, and Heritage Landing communities attract buyers seeking newer construction, top-performing schools, and easy Volkswagen and Amazon campus commutes.',
        neighborhoods: 'Cambridge Square, Windstone, Heritage Landing, Snow Hill Road corridor, Apison Pike area',
        nearby: 'Chattanooga, Cleveland TN, East Ridge, Collegedale, Ringgold GA',
        seller_hook: 'Ooltewah\'s new-construction boom and top Hamilton County school access drive strong appreciation — let competitive local realtors on RealtorFinder fight for your listing.',
        realtor_hook: 'Ooltewah\'s I-75 corporate corridor and family-friendly new communities create a strong buyer pipeline — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'knoxville',
        name: 'Knoxville',
        county: 'Knox',
        state: 'TN',
        zip: '37901',
        population: '190000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 27,
        description: 'Knoxville is East Tennessee\'s commercial and cultural capital — a vibrant University of Tennessee city on the Tennessee River where the revitalized Market Square, Old City arts district, and Sequoyah Hills waterfront neighborhood anchor a market attracting remote workers, retirees, and UT families who prize the city\'s mountain access and below-average living costs.',
        neighborhoods: 'Sequoyah Hills, Old City, Fourth and Gill, Holston Hills, Bearden, West Hills, Downtown',
        nearby: 'Farragut, Maryville, Oak Ridge, Lenoir City, Powell',
        seller_hook: 'Knoxville\'s UT economy and mountain-access appeal draw buyers from across the Southeast — let top Knox County realtors on RealtorFinder compete to represent your home.',
        realtor_hook: 'Knoxville\'s UT enrollment and growing remote-work migration create strong year-round buyer demand — RealtorFinder connects you with motivated sellers in this East Tennessee hub.',
    },
    {
        slug: 'farragut',
        name: 'Farragut',
        county: 'Knox',
        state: 'TN',
        zip: '37934',
        population: '24000',
        median_price: '$530,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Farragut is Knoxville\'s most coveted western suburb — a prosperous Knox County town consistently ranked among Tennessee\'s best places to live, where communities like Timberlake, Queensbury, and McFee Park are anchored by the area\'s top public schools, easy I-40 access, and proximity to Fort Loudoun Lake\'s waterfront lifestyle.',
        neighborhoods: 'Timberlake, Queensbury, McFee Park, Turkey Creek corridor, Concord Hills, Fox Den',
        nearby: 'Knoxville, Lenoir City, Oak Ridge, Louisville TN, Kingston',
        seller_hook: 'Farragut\'s Tennessee\'s best-schools reputation and Turkey Creek amenities command Knox County\'s highest prices — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Farragut\'s elite schools and Turkey Creek retail corridor attract the Knoxville area\'s most qualified buyers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'maryville-tn',
        name: 'Maryville',
        county: 'Blount',
        state: 'TN',
        zip: '37801',
        population: '31000',
        median_price: '$380,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Maryville is the gateway to Great Smoky Mountains National Park and Blount County\'s thriving county seat — an outdoor-recreation and manufacturing hub anchored by DENSO Manufacturing and Maryville College, where buyers seeking Smoky Mountain access, strong local schools, and Knoxville commutability find a competitive but still-affordable market.',
        neighborhoods: 'Walland Road area, Montvale Road corridor, Downtown Maryville, Sevierville Road, Marietta area',
        nearby: 'Knoxville, Alcoa, Sevierville, Townsend, Lenoir City',
        seller_hook: 'Maryville\'s Smoky Mountain gateway location and Blount County growth drive consistent appreciation — let competitive local realtors on RealtorFinder maximize your sale.',
        realtor_hook: 'Maryville\'s DENSO employment base and Smoky Mountain proximity attract buyers from across Tennessee — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'alcoa-tn',
        name: 'Alcoa',
        county: 'Blount',
        state: 'TN',
        zip: '37701',
        population: '10000',
        median_price: '$320,000',
        price_trend: 'up 6%',
        avg_dom: 29,
        description: 'Alcoa is Blount County\'s industrial anchor — a small but strategically positioned city home to McGhee Tyson Airport, Alcoa Inc. aluminum operations, and a growing cluster of logistics and manufacturing employers that attract buyers seeking affordable homeownership near Knoxville with stable employment anchors and easy access to Maryville and the Smokies.',
        neighborhoods: 'Wright Road area, Hunter Street corridor, Airport Road vicinity, Springbrook, Topside Road area',
        nearby: 'Maryville, Knoxville, Louisville TN, Friendsville, Rockford',
        seller_hook: 'Alcoa\'s airport and industrial employment base keep buyer demand steady — let competitive Blount County realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Alcoa\'s McGhee Tyson Airport and industrial economy attract practical buyers seeking affordability with job access — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'johnson-city-tn',
        name: 'Johnson City',
        county: 'Washington',
        state: 'TN',
        zip: '37601',
        population: '71000',
        median_price: '$295,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Johnson City is the Tri-Cities region\'s largest market and home to East Tennessee State University and a major VA medical complex — an emerging remote-work destination where Appalachian Trail access, a revitalized Downtown District, and nationally recognized affordability attract buyers from coastal metros and retiring professionals seeking mountain quality of life at a fraction of national costs.',
        neighborhoods: 'Downtown Johnson City, Boones Creek, Knob Creek Road corridor, Cherokee Country Club area, Forest Hills',
        nearby: 'Kingsport, Bristol TN, Elizabethton, Greeneville, Gray',
        seller_hook: 'Johnson City\'s ETSU economy and Appalachian Trail draw create growing appreciation in an undervalued market — let top Washington County realtors on RealtorFinder compete for your listing.',
        realtor_hook: 'Johnson City\'s remote-work migration and ETSU enrollment create motivated buyers in Tennessee\'s most affordable metro — RealtorFinder connects you with sellers.',
    },
];
