// cities/tx-extra.js — Additional Texas city data for SEO landing pages

module.exports = [
    {
        slug: 'mcallen',
        name: 'McAllen',
        county: 'Hidalgo',
        state: 'TX',
        zip: '78501',
        population: '143,000',
        median_price: '$215,000',
        price_trend: 'up 5%',
        avg_dom: 38,
        description: 'McAllen is the Rio Grande Valley\'s largest city and one of America\'s most bilingual communities — a booming international trade hub on the US-Mexico border where cross-border commerce, a massive regional medical complex, UT Rio Grande Valley, and a booming master-planned suburb boom attract Mexican nationals, medical professionals, and families seeking affordable South Texas homeownership in a vibrant bicultural metro.',
        neighborhoods: 'Sharyland, Edinburg, Mission, Pharr, Hidalgo',
        nearby: 'Edinburg, Mission, Pharr, Hidalgo, Reynosa Mexico',
        seller_hook: 'McAllen\'s Rio Grande Valley growth and cross-border buyer demand create active listing conditions — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'McAllen\'s international trade market and medical sector generate consistent listing activity in the Valley — find sellers through RealtorFinder.',
    },
    {
        slug: 'killeen',
        name: 'Killeen',
        county: 'Bell',
        state: 'TX',
        zip: '76541',
        population: '153,000',
        median_price: '$215,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Killeen is home to Fort Cavazos, the largest active-duty military installation in the United States — a central Texas military city where Army combat divisions, VA healthcare, Central Texas College, and a massive rotation of soldiers and their families create one of the nation\'s most active VA loan markets, with investors finding some of Texas\'s strongest rental yields among military-community single-family homes.',
        neighborhoods: 'Fort Cavazos, Copperas Cove, Harker Heights, Temple, Belton',
        nearby: 'Copperas Cove, Harker Heights, Temple, Belton, Waco',
        seller_hook: 'Killeen\'s Fort Cavazos military community creates year-round buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Killeen\'s massive Army installation and VA buyer pool generate consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'waco',
        name: 'Waco',
        county: 'McLennan',
        state: 'TX',
        zip: '76701',
        population: '139,000',
        median_price: '$235,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Waco is the home of Baylor University and America\'s Fixer Upper capital — a Brazos River city forever transformed by Chip and Joanna Gaines\'s Magnolia brand, drawing hundreds of thousands of home-design pilgrims annually and a new wave of buyers who want to live where the farmhouse aesthetic was invented, alongside Baylor\'s 20,000 students and a booming medical corridor on I-35.',
        neighborhoods: 'Sanger Heights, Woodway, Hewitt, Lorena, China Spring',
        nearby: 'Woodway, Hewitt, Lorena, China Spring, Hillsboro',
        seller_hook: 'Waco\'s Magnolia fame and Baylor enrollment create nationwide buyer interest — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Waco\'s Fixer Upper culture and I-35 corridor growth generate active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'tyler-tx',
        name: 'Tyler',
        county: 'Smith',
        state: 'TX',
        zip: '75701',
        population: '107,000',
        median_price: '$265,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Tyler is the Rose Capital of America and East Texas\'s largest city — a Piney Woods medical hub where UT Health Tyler, Christus Trinity Mother Frances, and UT Tyler create a robust healthcare economy that draws medical professionals from Dallas who seek a quieter lifestyle, larger homes, and significantly lower prices while maintaining urban amenities in one of East Texas\'s most charming cities.',
        neighborhoods: 'Whitehouse, Lindale, Flint, Bullard, Chandler',
        nearby: 'Longview, Lindale, Whitehouse, Flint, Canton',
        seller_hook: 'Tyler\'s East Texas medical hub and rose country charm attract buyers seeking Dallas alternatives — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Tyler\'s healthcare economy and Piney Woods lifestyle create consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'beaumont-tx',
        name: 'Beaumont',
        county: 'Jefferson',
        state: 'TX',
        zip: '77701',
        population: '114,000',
        median_price: '$180,000',
        price_trend: 'up 4%',
        avg_dom: 40,
        description: 'Beaumont is Southeast Texas\'s largest city and a Gulf Coast petrochemical powerhouse — a Neches River refining hub where ExxonMobil, Chevron Phillips, and Lamar University create housing demand from refinery workers, medical professionals, and buyers seeking some of Texas\'s most affordable home prices in a city with a revitalized downtown and strong investment fundamentals tied to the energy corridor.',
        neighborhoods: 'Vidor, Nederland, Port Arthur, Groves, Orange',
        nearby: 'Port Arthur, Nederland, Orange, Groves, Vidor',
        seller_hook: 'Beaumont\'s petrochemical sector and affordable prices attract investors and first-time buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Beaumont\'s refinery economy and Southeast Texas market create consistent listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'midland-tx',
        name: 'Midland',
        county: 'Midland',
        state: 'TX',
        zip: '79701',
        population: '132,000',
        median_price: '$330,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Midland is the executive capital of the Permian Basin and birthplace of two US presidents — an oil and gas city on the West Texas plains where Pioneer Natural Resources, Chevron, and dozens of energy companies have made it one of America\'s highest-income per-capita cities, creating a boom-cycle housing market where energy workers and executives compete for homes in a city that punches far above its size weight.',
        neighborhoods: 'Greenwood, Westover Hills, Tall City, Gardendale, Midland County',
        nearby: 'Odessa, Big Spring, Andrews, Stanton, Lamesa',
        seller_hook: 'Midland\'s Permian Basin energy wealth creates one of Texas\'s most active seller\'s markets — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Midland\'s oil executive buyer pool and energy boom cycles create high-value listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'abilene-tx',
        name: 'Abilene',
        county: 'Taylor',
        state: 'TX',
        zip: '79601',
        population: '125,000',
        median_price: '$195,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Abilene is West Texas\'s hub of faith and education — a city of three Christian universities (Abilene Christian, Hardin-Simmons, McMurry), Dyess Air Force Base, and a strong regional medical corridor that creates a diverse and stable housing market serving military families, university students, and West Texas professionals seeking affordable homeownership in a community known for its friendly character.',
        neighborhoods: 'Wylie, Tye, Potosi, Tuscola, Buffalo Gap',
        nearby: 'Wylie, Tye, Potosi, Tuscola, Sweetwater',
        seller_hook: 'Abilene\'s three universities and Dyess AFB create diverse and reliable buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Abilene\'s military and faith-based university market generate consistent listing activity at West Texas prices — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'odessa-tx',
        name: 'Odessa',
        county: 'Ector',
        state: 'TX',
        zip: '79761',
        population: '113,000',
        median_price: '$275,000',
        price_trend: 'up 4%',
        avg_dom: 32,
        description: 'Odessa is Midland\'s Permian Basin twin city and the working heart of West Texas oil country — home of Friday Night Lights and one of the most energy-boom-driven housing markets in the nation, where roughneck wages, UT Permian Basin, and Medical Center Hospital create demand for affordable oilfield-worker housing and investment properties that swing dramatically with crude oil prices.',
        neighborhoods: 'Gardendale, Goldsmith, Andrews Highway, North Odessa, Midland County',
        nearby: 'Midland, Andrews, Kermit, Monahans, Big Spring',
        seller_hook: 'Odessa\'s Permian Basin energy wages and oil patch lifestyle attract motivated buyers — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Odessa\'s energy sector and Friday Night Lights culture create distinctive listing opportunities in West Texas — find sellers through RealtorFinder.',
    },
    {
        slug: 'wichita-falls-tx',
        name: 'Wichita Falls',
        county: 'Wichita',
        state: 'TX',
        zip: '76301',
        population: '102,000',
        median_price: '$165,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Wichita Falls is North Texas\'s Red River border city and home to Sheppard Air Force Base — a NATO pilot training hub where the largest international military pilot training program in the world, Midwestern State University, and United Regional Health System create consistent housing demand from multinational military families and medical professionals who find some of Texas\'s most affordable home prices.',
        neighborhoods: 'Burkburnett, Iowa Park, Holliday, Electra, Bowie',
        nearby: 'Burkburnett, Iowa Park, Lawton OK, Holliday, Electra',
        seller_hook: 'Wichita Falls\' Sheppard AFB training community drives year-round military buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Wichita Falls\' international military buyer pool and affordable prices create consistent listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'san-marcos-tx',
        name: 'San Marcos',
        county: 'Hays',
        state: 'TX',
        zip: '78666',
        population: '68,000',
        median_price: '$350,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'San Marcos is one of Texas\'s fastest-growing cities and home to Texas State University — a Colorado River college city perfectly positioned between Austin and San Antonio on the I-35 corridor where 38,000 Bobcats, a thriving tech and outdoor recreation economy, and Austin commuter demand have created intense housing competition and some of Texas\'s strongest appreciation rates for a mid-size city.',
        neighborhoods: 'Kyle, Wimberley, Buda, Martindale, Lockhart',
        nearby: 'Kyle, Buda, New Braunfels, Lockhart, Wimberley',
        seller_hook: 'San Marcos\' Texas State enrollment and Austin proximity create fast-moving listing conditions — let RealtorFinder agents compete for your home.',
        realtor_hook: 'San Marcos\' I-35 corridor growth and university market generate some of Texas\'s strongest appreciation — find sellers through RealtorFinder.',
    },
];
