// cities/tx.js — Texas city data for SEO landing pages

module.exports = [
    {
        slug: 'houston',
        name: 'Houston',
        county: 'Harris',
        state: 'TX',
        zip: '77001',
        population: '2300000',
        median_price: '$299,000',
        price_trend: 'up 4%',
        avg_dom: 32,
        description: 'Houston is the energy capital of the world and the most diverse large city in America — a sprawling metropolis with an extraordinarily broad real estate market, no zoning restrictions, and neighborhoods from the Museum District\'s cultural corridors to Montrose\'s eclectic bungalows that accommodate every buyer profile at every price point.',
        neighborhoods: 'Montrose, Heights, Museum District, Midtown, River Oaks border, Midtown, Upper Kirby, EaDo',
        nearby: 'Sugar Land, The Woodlands, Katy, Pearland, Pasadena',
        seller_hook: 'Houston\'s massive buyer pool and diverse housing demand mean the right realtor can make a significant difference — let competing agents on RealtorFinder earn your listing.',
        realtor_hook: 'Houston\'s enormous population and diverse real estate landscape create unmatched listing volume — RealtorFinder connects you with motivated sellers across America\'s most diverse city.',
    },
    {
        slug: 'san-antonio',
        name: 'San Antonio',
        county: 'Bexar',
        state: 'TX',
        zip: '78201',
        population: '1450000',
        median_price: '$269,000',
        price_trend: 'up 5%',
        avg_dom: 34,
        description: 'San Antonio is Texas\' second-largest city and one of the nation\'s fastest-growing — a military and tourism hub anchored by Fort Sam Houston, the River Walk, and a diverse economy that has attracted corporate relocations and remote workers seeking Texas affordability with genuine cultural identity.',
        neighborhoods: 'Alamo Heights, King William Historic District, Monte Vista, Stone Oak, Olmos Park, Southtown',
        nearby: 'New Braunfels, Boerne, Schertz, Converse, Live Oak',
        seller_hook: 'San Antonio\'s booming population growth drives strong buyer demand — let competitive Bexar County realtors on RealtorFinder fight for the right to represent your home.',
        realtor_hook: 'San Antonio\'s rapid growth and diverse buyer demographics make it one of Texas\'s most active listing markets — RealtorFinder keeps your pipeline full.',
    },
    {
        slug: 'dallas',
        name: 'Dallas',
        county: 'Dallas',
        state: 'TX',
        zip: '75201',
        population: '1300000',
        median_price: '$349,000',
        price_trend: 'up 4%',
        avg_dom: 30,
        description: 'Dallas is the economic powerhouse of the Dallas-Fort Worth metroplex — a corporate relocation magnet and financial hub where neighborhoods from Deep Ellum\'s arts district to Uptown\'s luxury high-rises and Oak Cliff\'s eclectic bungalows attract buyers from across the country seeking Texas opportunity without Austin\'s price tag.',
        neighborhoods: 'Uptown, Deep Ellum, Bishop Arts, Oak Cliff, Lakewood, M Streets, Preston Hollow, Lake Highlands',
        nearby: 'Plano, Irving, Garland, Mesquite, Richardson',
        seller_hook: 'Dallas\'s corporate relocation wave and diverse buyer pool create consistent demand — RealtorFinder puts top DFW agents in a bidding war to represent your home.',
        realtor_hook: 'Dallas\'s corporate migration and diverse neighborhoods create one of Texas\'s highest-volume listing markets — RealtorFinder connects you with motivated sellers across the metroplex.',
    },
    {
        slug: 'austin',
        name: 'Austin',
        county: 'Travis',
        state: 'TX',
        zip: '78701',
        population: '978,000',
        median_price: '$549,000',
        price_trend: 'up 3%',
        avg_dom: 38,
        description: 'Austin is America\'s tech boomtown — a live-music capital turned Silicon Hills that has attracted Apple, Tesla, Dell, and hundreds of tech startups, creating a real estate market that has seen massive price appreciation while beginning to normalize after a pandemic-era surge, offering opportunities for both buyers and sellers.',
        neighborhoods: 'East Austin, South Congress, Hyde Park, Barton Hills, Mueller, Domain area, Bouldin Creek',
        nearby: 'Cedar Park, Round Rock, Georgetown, Kyle, Pflugerville',
        seller_hook: 'Austin\'s tech industry buyer base and strong fundamentals support competitive sales — let top Austin-area agents compete on RealtorFinder to earn your listing.',
        realtor_hook: 'Austin\'s tech economy and national profile attract highly qualified buyers — RealtorFinder connects you with motivated sellers in one of America\'s most-watched markets.',
    },
    {
        slug: 'fort-worth',
        name: 'Fort Worth',
        county: 'Tarrant',
        state: 'TX',
        zip: '76101',
        population: '935,000',
        median_price: '$299,000',
        price_trend: 'up 5%',
        avg_dom: 31,
        description: 'Fort Worth is the "City Where the West Begins" — a DFW metroplex anchor that has grown into a sophisticated city in its own right, with a world-class Cultural District, the revitalized Sundance Square, and diverse neighborhoods that offer real value compared to Dallas proper while sharing the same booming regional economy.',
        neighborhoods: 'Cultural District, Near Southside, Fairmount, Mistletoe Heights, TCU area, Wedgwood, Ridglea',
        nearby: 'Arlington, Euless, North Richland Hills, Keller, Burleson',
        seller_hook: 'Fort Worth\'s growth and value proposition drive strong buyer demand from across DFW — RealtorFinder puts competitive Tarrant County agents in a race to represent your home.',
        realtor_hook: 'Fort Worth\'s rapid growth and affordability relative to Dallas attract buyers from across the metroplex — RealtorFinder connects you with motivated sellers in Tarrant County.',
    },
    {
        slug: 'el-paso',
        name: 'El Paso',
        county: 'El Paso',
        state: 'TX',
        zip: '79901',
        population: '678,000',
        median_price: '$219,000',
        price_trend: 'up 8%',
        avg_dom: 28,
        description: 'El Paso is the gateway to the American Southwest — a binational city at the junction of Texas, New Mexico, and Chihuahua with Fort Bliss military base, a growing tech sector, and home prices that remain among the most affordable of any large Texas city, attracting military families, first-time buyers, and investors.',
        neighborhoods: 'Kern Place, Sunset Heights, Central El Paso, West Side, East El Paso, Mission Valley',
        nearby: 'Anthony, Horizon City, Socorro, Santa Teresa NM, Ciudad Juárez',
        seller_hook: 'El Paso\'s military presence and growing civilian economy drive consistent buyer demand — let competing local realtors on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'El Paso\'s Fort Bliss-driven buyer base and affordable price points create consistent listing volume — RealtorFinder connects you with motivated sellers in this growing market.',
    },
    {
        slug: 'arlington-tx',
        name: 'Arlington',
        county: 'Tarrant',
        state: 'TX',
        zip: '76010',
        population: '400,000',
        median_price: '$289,000',
        price_trend: 'up 5%',
        avg_dom: 29,
        description: 'Arlington sits at the heart of the DFW metroplex — home to AT&T Stadium, Globe Life Field, and UT Arlington, with a diverse residential community that benefits from the region\'s economic boom and excellent highway access to both Dallas and Fort Worth, making it a practical choice for cost-conscious buyers.',
        neighborhoods: 'Downtown Arlington, Pantego border, South Arlington, Dalworthington Gardens, Interlochen',
        nearby: 'Fort Worth, Grand Prairie, Mansfield, Irving, Dallas',
        seller_hook: 'Arlington\'s central DFW location and sports venue profile drive broad buyer interest — let competitive realtors on RealtorFinder compete to represent your home.',
        realtor_hook: 'Arlington\'s central position in the DFW metroplex creates a diverse buyer pool and consistent listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'corpus-christi',
        name: 'Corpus Christi',
        county: 'Nueces',
        state: 'TX',
        zip: '78401',
        population: '317,000',
        median_price: '$229,000',
        price_trend: 'up 6%',
        avg_dom: 33,
        description: 'Corpus Christi is the Texas Gulf Coast\'s largest city — a naval air station town with access to Padre Island National Seashore, a growing petrochemical sector, and one of the most affordable coastal real estate markets in the country, drawing buyers seeking beachside living without Florida or California price tags.',
        neighborhoods: 'Flour Bluff, South Side, Calallen, Portland border, Padre Island, Bay Area',
        nearby: 'Rockport, Portland, Ingleside, Port Aransas, Victoria',
        seller_hook: 'Corpus Christi\'s coastal access and affordability attract buyers from across Texas and beyond — RealtorFinder puts competitive local agents in a race to represent your home.',
        realtor_hook: 'Corpus Christi\'s Gulf Coast lifestyle and affordable prices attract a broad buyer base — RealtorFinder connects you with motivated sellers in this coastal market.',
    },
    {
        slug: 'plano',
        name: 'Plano',
        county: 'Collin',
        state: 'TX',
        zip: '75023',
        population: '285,000',
        median_price: '$459,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Plano is the corporate headquarters capital of North Texas — home to Toyota, JPMorgan Chase, and dozens of Fortune 500 North American operations — with top-ranked schools, affluent subdivisions, and a real estate market that attracts corporate relocatees and wealthy families from across the country.',
        neighborhoods: 'Legacy West, West Plano, East Plano, Downtown Plano, Haggard Park area, Jack Carter Park',
        nearby: 'Allen, Frisco, McKinney, Richardson, Garland',
        seller_hook: 'Plano\'s corporate headquarters cluster and top schools drive premium buyer demand — let the best Collin County agents compete on RealtorFinder to sell your home.',
        realtor_hook: 'Plano\'s Fortune 500 relocation traffic and top-school demand create a premium listing market — RealtorFinder connects you with motivated sellers in North Texas\'s most corporate suburb.',
    },
    {
        slug: 'lubbock',
        name: 'Lubbock',
        county: 'Lubbock',
        state: 'TX',
        zip: '79401',
        population: '257,000',
        median_price: '$199,000',
        price_trend: 'up 7%',
        avg_dom: 30,
        description: 'Lubbock is West Texas\'s largest city and home to Texas Tech University — an agricultural and educational hub with some of the most affordable home prices of any Texas city its size, attracting first-time buyers, investors, and university-driven buyers seeking entry-level assets with strong long-term appreciation.',
        neighborhoods: 'Tech Terrace, University Avenue corridor, Overton, South Lubbock, North Lubbock',
        nearby: 'Wolfforth, Shallowater, Slaton, Levelland, Lamesa',
        seller_hook: 'Lubbock\'s university-driven demand and rising prices make now a great time to sell — let competing realtors on RealtorFinder bring you the best possible offer.',
        realtor_hook: 'Lubbock\'s Texas Tech buyer base and affordable entry points create consistent listing demand — RealtorFinder connects you with motivated sellers in West Texas.',
    },
    {
        slug: 'laredo',
        name: 'Laredo',
        county: 'Webb',
        state: 'TX',
        zip: '78040',
        population: '255,000',
        median_price: '$179,000',
        price_trend: 'up 6%',
        avg_dom: 35,
        description: 'Laredo is the busiest inland port on the US-Mexico border — a trade gateway city with a strong binational economy, a growing professional class, and home prices that offer exceptional value for buyers seeking entry into the Texas real estate market or investment properties in a strategically important border city.',
        neighborhoods: 'Del Mar, North Laredo, South Laredo, Downtown Laredo, El Pico area',
        nearby: 'Nuevo Laredo Mx, Cotulla, Zapata, Encinal',
        seller_hook: 'Laredo\'s trade economy and growing professional sector drive consistent buyer demand — let competitive local agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Laredo\'s strategic border economy creates a steady buyer base across professional and investment segments — RealtorFinder connects you with motivated sellers in this border market.',
    },
    {
        slug: 'irving',
        name: 'Irving',
        county: 'Dallas',
        state: 'TX',
        zip: '75061',
        population: '240,000',
        median_price: '$329,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Irving is the corporate gateway to DFW — home to the Las Colinas business district, DFW International Airport, and a diverse, transit-connected city where DART light rail, a multinational corporate presence, and more affordable home prices than neighboring Plano and Dallas attract buyers seeking value in a prime location.',
        neighborhoods: 'Las Colinas, Valley Ranch, Irving Heights, North Irving, South Irving, MacArthur Park',
        nearby: 'Dallas, Grand Prairie, Coppell, Grapevine, Carrollton',
        seller_hook: 'Irving\'s DFW Airport access and Las Colinas corporate presence draw buyers from across the metroplex — let top local realtors compete on RealtorFinder to represent your home.',
        realtor_hook: 'Irving\'s airport proximity and corporate district create diverse buyer demand — RealtorFinder connects you with motivated sellers in the heart of the DFW metroplex.',
    },
];
