// cities/ut.js — Utah city data for SEO landing pages

module.exports = [
    {
        slug: 'salt-lake-city',
        name: 'Salt Lake City',
        county: 'Salt Lake',
        state: 'UT',
        zip: '84101',
        population: '200,000',
        median_price: '$520,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Salt Lake City is Utah\'s capital and the economic heart of the Wasatch Front — a rapidly growing tech hub where Silicon Slopes companies, world-class ski access, and a young, educated workforce drive intense housing demand across neighborhoods like Sugar House, The Avenues, Liberty Wells, and the 9th & 9th district.',
        neighborhoods: 'Sugar House, The Avenues, Liberty Wells, East Bench, Marmalade, Rose Park, Glendale, 9th & 9th',
        nearby: 'West Valley City, Millcreek, Sandy, Murray, Taylorsville',
        seller_hook: 'Salt Lake City\'s booming tech economy and population growth keep demand strong year-round — let top SLC agents on RealtorFinder compete to list your home.',
        realtor_hook: 'Salt Lake City\'s Silicon Slopes migration and limited housing supply make it one of the West\'s most competitive listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'provo',
        name: 'Provo',
        county: 'Utah',
        state: 'UT',
        zip: '84601',
        population: '116,000',
        median_price: '$460,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Provo anchors Utah County\'s Silicon Slopes tech corridor and home to Brigham Young University — a family-friendly city where a young demographic, strong job growth from tech giants like Qualtrics and Adobe, and proximity to world-class skiing in the Wasatch Range fuel consistent housing demand.',
        neighborhoods: 'Riverbottoms, Maeser, Carterville, Franklin, Timp, Rock Canyon, East Bay',
        nearby: 'Orem, Springville, Spanish Fork, Mapleton, Lindon',
        seller_hook: 'Provo\'s BYU enrollment and Silicon Slopes job growth generate year-round buyer demand — connect with top agents on RealtorFinder to sell faster.',
        realtor_hook: 'Provo\'s tech economy and young population create a fast-moving market with motivated buyers — win listings through RealtorFinder.',
    },
    {
        slug: 'ogden',
        name: 'Ogden',
        county: 'Weber',
        state: 'UT',
        zip: '84401',
        population: '87,000',
        median_price: '$370,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Ogden is a gateway city to world-class skiing at Snowbasin and Powder Mountain — a revitalized downtown with a thriving arts scene, Weber State University, and Hill Air Force Base creating a diverse buyer pool seeking affordable Wasatch Front living compared to Salt Lake City.',
        neighborhoods: 'Historic 25th Street, East Bench, South Ogden, Lorin Farr, Bonneville Hills, Ogden Valley',
        nearby: 'Roy, Layton, Syracuse, Clearfield, Riverdale',
        seller_hook: 'Ogden\'s affordability relative to Salt Lake City draws steady buyer demand from outdoor enthusiasts and young families — RealtorFinder agents compete to list your home.',
        realtor_hook: 'Ogden\'s growing arts district and outdoor recreation appeal attract buyers priced out of SLC — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'sandy-ut',
        name: 'Sandy',
        county: 'Salt Lake',
        state: 'UT',
        zip: '84070',
        population: '96,000',
        median_price: '$550,000',
        price_trend: 'up 6%',
        avg_dom: 21,
        description: 'Sandy is one of Salt Lake Valley\'s most desirable suburbs — a polished master-planned community at the base of Little Cottonwood Canyon where top-rated schools, the TRAX light rail connection to downtown, and proximity to Alta and Snowbird ski resorts make it a perennial favorite among families and outdoor professionals.',
        neighborhoods: 'Dimple Dell, Granite, South Sandy, Copperview, Bell Canyon, Alta Canyon',
        nearby: 'Draper, South Jordan, Midvale, Cottonwood Heights, Murray',
        seller_hook: 'Sandy\'s excellent schools and ski access create strong year-round demand — let top agents on RealtorFinder compete for your listing.',
        realtor_hook: 'Sandy\'s family-oriented buyer pool and consistent appreciation make it one of the valley\'s most reliable listing markets — connect with sellers on RealtorFinder.',
    },
    {
        slug: 'west-jordan',
        name: 'West Jordan',
        county: 'Salt Lake',
        state: 'UT',
        zip: '84084',
        population: '114,000',
        median_price: '$470,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'West Jordan is Salt Lake County\'s largest suburb and one of Utah\'s fastest-growing cities — an affordable family destination with expanding commercial development, easy freeway access to both downtown Salt Lake and Silicon Slopes, and a diverse housing mix from starter homes to large new-construction properties.',
        neighborhoods: 'Bingham Creek, Mountain View Corridor, West Jordan Hills, Welby, Old Farm',
        nearby: 'South Jordan, Riverton, Taylorsville, Kearns, Magna',
        seller_hook: 'West Jordan\'s affordability and growth attract strong buyer demand — list through RealtorFinder and let agents compete for your property.',
        realtor_hook: 'West Jordan\'s expanding population and new construction pipeline create consistent listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'orem',
        name: 'Orem',
        county: 'Utah',
        state: 'UT',
        zip: '84057',
        population: '98,000',
        median_price: '$450,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Orem is Utah Valley\'s commercial hub and neighbor to Provo — home to Utah Valley University and positioned at the center of the Silicon Slopes tech corridor, it offers slightly more affordable housing than Provo with easy access to I-15, the FrontRunner commuter rail, and abundant retail and dining along State Street.',
        neighborhoods: 'Northeast Orem, Cascade, Scera Park, Geneva Road, Vineyard',
        nearby: 'Provo, Lindon, Pleasant Grove, American Fork, Vineyard',
        seller_hook: 'Orem\'s central Utah Valley location and UVU enrollment drive consistent buyer demand — RealtorFinder agents compete for your listing.',
        realtor_hook: 'Orem\'s growing tech workforce and university population create a motivated buyer pool — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'south-jordan',
        name: 'South Jordan',
        county: 'Salt Lake',
        state: 'UT',
        zip: '84095',
        population: '76,000',
        median_price: '$580,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'South Jordan is one of Salt Lake Valley\'s premier family suburbs — a master-planned community where top-tier schools, the Daybreak master-planned neighborhood, and rapid population growth from Silicon Slopes professionals have created one of Utah\'s most competitive housing markets with low days-on-market and frequent multiple-offer situations.',
        neighborhoods: 'Daybreak, Bingham Creek, South Jordan Hills, SoDa Row, Daybreak Town Center',
        nearby: 'West Jordan, Riverton, Herriman, Sandy, Bluffdale',
        seller_hook: 'South Jordan\'s Daybreak community and excellent schools drive fierce buyer competition — maximize your sale with top agents competing on RealtorFinder.',
        realtor_hook: 'South Jordan\'s fast-moving market and high price points make it one of the valley\'s most lucrative listing territories — find sellers on RealtorFinder.',
    },
    {
        slug: 'layton',
        name: 'Layton',
        county: 'Davis',
        state: 'UT',
        zip: '84041',
        population: '82,000',
        median_price: '$430,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Layton is Davis County\'s largest city and home to Hill Air Force Base — a thriving military and civilian community where affordable prices relative to Salt Lake County, strong I-15 access, and the FrontRunner commuter rail attract first-time buyers, military families, and young professionals commuting south to Salt Lake.',
        neighborhoods: 'East Layton, Layton Hills, Kays Creek, Sunset, West Layton',
        nearby: 'Clearfield, Syracuse, Kaysville, Farmington, Clinton',
        seller_hook: 'Layton\'s military community and commuter appeal drive steady buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Layton\'s Hill AFB presence and first-time buyer market create consistent listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'st-george',
        name: 'St. George',
        county: 'Washington',
        state: 'UT',
        zip: '84770',
        population: '97,000',
        median_price: '$480,000',
        price_trend: 'up 8%',
        avg_dom: 30,
        description: 'St. George is Utah\'s fastest-growing city and the gateway to Zion National Park — a warm desert resort community where retirees from California and Nevada, remote workers seeking sun and outdoor recreation, and a booming tourism economy have fueled some of Utah\'s strongest home price appreciation over the past decade.',
        neighborhoods: 'Bloomington Hills, Sunbrook, Foremaster Ridge, Entrada, Little Valley, Stone Cliff',
        nearby: 'Washington City, Santa Clara, Ivins, Hurricane, Cedar City',
        seller_hook: 'St. George\'s retirement influx and Zion tourism economy drive strong year-round demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'St. George\'s explosive growth and out-of-state buyer influx create exceptional listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'draper',
        name: 'Draper',
        county: 'Salt Lake / Utah',
        state: 'UT',
        zip: '84020',
        population: '50,000',
        median_price: '$650,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Draper sits at the crossroads of Salt Lake and Utah counties at the mouth of Traverse Mountain — a prestigious suburb where Silicon Slopes tech employers like Adobe, Vivint, and eBay have headquarters, excellent schools, mountain trail access, and one of Utah\'s strongest median household incomes make it the state\'s most affluent bedroom community.',
        neighborhoods: 'Corner Canyon, Draper Peaks, Suncrest, The Traverse, South Mountain',
        nearby: 'Sandy, Riverton, South Jordan, Bluffdale, Lehi',
        seller_hook: 'Draper\'s Silicon Slopes proximity and top schools create high demand and strong sale prices — let premium agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Draper\'s high-income tech workforce and competitive market make it one of Utah\'s most lucrative listing areas — find sellers through RealtorFinder.',
    },
    {
        slug: 'lehi',
        name: 'Lehi',
        county: 'Utah',
        state: 'UT',
        zip: '84043',
        population: '75,000',
        median_price: '$510,000',
        price_trend: 'up 8%',
        avg_dom: 22,
        description: 'Lehi is the epicenter of Utah\'s Silicon Slopes — a boomtown where tech giants including Adobe, Ancestry, IM Flash, and dozens of high-growth startups have established campuses, driving explosive population growth and one of the nation\'s most rapid housing market expansions among mid-size American cities.',
        neighborhoods: 'Traverse Mountain, North Point, Dry Creek, Thanksgiving Point, Wines Park',
        nearby: 'American Fork, Highland, Eagle Mountain, Saratoga Springs, Draper',
        seller_hook: 'Lehi\'s Silicon Slopes boom and explosive population growth create exceptional seller conditions — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Lehi\'s tech employment concentration and relentless new household formation make it Utah\'s hottest listing market — find sellers through RealtorFinder.',
    },
    {
        slug: 'park-city',
        name: 'Park City',
        county: 'Summit',
        state: 'UT',
        zip: '84060',
        population: '8,500',
        median_price: '$1,850,000',
        price_trend: 'up 9%',
        avg_dom: 45,
        description: 'Park City is Utah\'s premier mountain resort community — home to Park City Mountain and Deer Valley ski resorts, the Sundance Film Festival, and a globally recognized luxury real estate market where California and tech-sector second-home buyers compete intensely for limited inventory of ski-in/ski-out properties, historic Old Town Victorian homes, and contemporary mountain estates.',
        neighborhoods: 'Old Town, Deer Valley, Park Meadows, Prospector, Snyderville Basin, Kimball Junction',
        nearby: 'Heber City, Midway, Salt Lake City, Kamas, Coalville',
        seller_hook: 'Park City\'s luxury buyer demand and limited inventory drive exceptional sale prices — let elite mountain market agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Park City\'s luxury ski market and out-of-state buyer demand create high-value listing opportunities — connect with motivated sellers through RealtorFinder.',
    },
    {
        slug: 'herriman',
        name: 'Herriman',
        county: 'Salt Lake',
        state: 'UT',
        zip: '84096',
        population: '56,000',
        median_price: '$520,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Herriman is one of Utah\'s fastest-growing cities — a new-construction haven in Salt Lake County\'s southwestern corner where young families are drawn by affordable new builds, highly-rated schools, quiet neighborhoods far from urban congestion, and the growing Mountain View Corridor commercial corridor.',
        neighborhoods: 'Herriman Towne Center, Juniper Park, Eagle Landing, South Mountain, Bluffdale',
        nearby: 'Riverton, South Jordan, Bluffdale, West Jordan, Copperton',
        seller_hook: 'Herriman\'s new construction boom and family buyer demand create active listing conditions — let agents compete for your home on RealtorFinder.',
        realtor_hook: 'Herriman\'s rapid growth and first-time buyer market offer consistent new listing opportunities — find sellers through RealtorFinder.',
    },
    {
        slug: 'taylorsville',
        name: 'Taylorsville',
        county: 'Salt Lake',
        state: 'UT',
        zip: '84129',
        population: '60,000',
        median_price: '$430,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Taylorsville is a centrally located Salt Lake Valley city offering some of the region\'s best value — a diverse community with established neighborhoods, easy TRAX and freeway access to downtown Salt Lake and the University of Utah, and a strong mix of entry-level and move-up housing that attracts a wide range of buyers.',
        neighborhoods: 'Meadows, Kearns, Millcreek adjacent, Taylorsville Bennion',
        nearby: 'West Valley City, Murray, Kearns, Magna, Midvale',
        seller_hook: 'Taylorsville\'s central location and affordability keep buyer demand strong — list with a top agent through RealtorFinder.',
        realtor_hook: 'Taylorsville\'s value-oriented market and central SL County location attract motivated buyers — find listing clients through RealtorFinder.',
    },
    {
        slug: 'murray',
        name: 'Murray',
        county: 'Salt Lake',
        state: 'UT',
        zip: '84107',
        population: '50,000',
        median_price: '$440,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Murray is a centrally-situated Salt Lake County city revitalized by the TRAX light rail\'s Murray Central station and the state\'s largest Intermountain Health campus — an increasingly popular choice for healthcare professionals, young buyers, and urban commuters seeking walkable access to shopping along State Street and convenient connections to the entire Salt Lake Valley.',
        neighborhoods: 'Murray Park, Vine Street, Fashion Place, Cottonwood, Murray Central',
        nearby: 'Midvale, Millcreek, Sandy, Taylorsville, Holladay',
        seller_hook: 'Murray\'s TRAX access and IHC employment draw consistent buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Murray\'s transit connectivity and healthcare-sector buyer pool create reliable listing opportunities — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'logan-ut',
        name: 'Logan',
        county: 'Cache',
        state: 'UT',
        zip: '84321',
        population: '52,000',
        median_price: '$350,000',
        price_trend: 'up 4%',
        avg_dom: 32,
        description: 'Logan is Cache County\'s university town and the commercial hub of the fertile Cache Valley — home to Utah State University, a charming historic downtown, and affordable housing well below the Wasatch Front average that attracts students, faculty, and young families seeking mountain living without the high prices of the greater Salt Lake metro.',
        neighborhoods: 'Millville, Providence, North Logan, Hyde Park, River Heights',
        nearby: 'Providence, North Logan, Hyde Park, Smithfield, Hyrum',
        seller_hook: 'Logan\'s USU enrollment and Cache Valley employer base generate steady buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Logan\'s university market and growing Cache Valley economy offer consistent listing opportunities — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'riverton',
        name: 'Riverton',
        county: 'Salt Lake',
        state: 'UT',
        zip: '84065',
        population: '44,000',
        median_price: '$540,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Riverton is a premier family suburb in Salt Lake County\'s southwest corridor — a community of large single-family homes, top-rated Canyons School District schools, and proximity to both Silicon Slopes employers in Lehi and the Jordan River Parkway trail system that consistently draws competitive buyer offers from young families.',
        neighborhoods: 'South Bench, Riverton Ranches, Oquirrh Mountain, Bingham Creek',
        nearby: 'South Jordan, Herriman, Bluffdale, West Jordan, Draper',
        seller_hook: 'Riverton\'s family-friendly reputation and excellent schools drive multiple-offer competition — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Riverton\'s growing family buyer pool and strong school district make it one of the valley\'s most active listing markets — find sellers through RealtorFinder.',
    },
    {
        slug: 'american-fork',
        name: 'American Fork',
        county: 'Utah',
        state: 'UT',
        zip: '84003',
        population: '33,000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'American Fork sits at the foot of American Fork Canyon and borders Utah Lake — a rapidly growing Silicon Slopes bedroom community with a charming main street, proximity to Thanksgiving Point and the ICON Health & Fitness campus, and affordable pricing relative to neighboring Lehi and Draper that attracts tech employees seeking more space for their dollar.',
        neighborhoods: 'North American Fork, East Bench, Vista, Meadow, Canyon Road',
        nearby: 'Highland, Lehi, Pleasant Grove, Lindon, Orem',
        seller_hook: 'American Fork\'s canyon access and Silicon Slopes proximity drive strong buyer interest — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'American Fork\'s growing tech-worker buyer base and canyon lifestyle appeal create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'cedar-city',
        name: 'Cedar City',
        county: 'Iron',
        state: 'UT',
        zip: '84720',
        population: '36,000',
        median_price: '$320,000',
        price_trend: 'up 5%',
        avg_dom: 35,
        description: 'Cedar City is southern Utah\'s university hub and cultural capital — home to Southern Utah University, Shakespearean festival, and outdoor access to Brian Head ski resort, Zion and Bryce Canyon National Parks; it attracts retirees, outdoor recreationists, and remote workers seeking affordable mountain living and a tight-knit college-town community.',
        neighborhoods: 'Fort Harmony, Thunderbird Heights, Vintage Hills, Canyon View',
        nearby: 'Enoch, Parowan, Hurricane, St. George',
        seller_hook: 'Cedar City\'s SUU enrollment and tourism economy generate steady buyer demand — let RealtorFinder agents compete for your listing.',
        realtor_hook: 'Cedar City\'s growing remote-worker and retiree market offers consistent listing opportunities — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'eagle-mountain',
        name: 'Eagle Mountain',
        county: 'Utah',
        state: 'UT',
        zip: '84005',
        population: '45,000',
        median_price: '$440,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Eagle Mountain is one of Utah\'s fastest-growing master-planned communities — a new-construction city west of Utah Lake where young families are drawn by large affordable lots, brand-new schools, and significant tax savings from Utah County\'s lower property rates while remaining within commuting distance of Silicon Slopes employers along I-15.',
        neighborhoods: 'Ranches, Overland, Meadows, Pony Express, Cedar Valley',
        nearby: 'Saratoga Springs, Lehi, Fairfield, Bluffdale',
        seller_hook: 'Eagle Mountain\'s rapid growth and family buyer demand create strong listing conditions — let top agents compete for your home on RealtorFinder.',
        realtor_hook: 'Eagle Mountain\'s explosive new household formation offers exceptional listing volume — find motivated sellers through RealtorFinder.',
    },
];
