// cities/va.js — Virginia city data for SEO landing pages

module.exports = [
    {
        slug: 'arlington',
        name: 'Arlington',
        county: 'Arlington',
        state: 'VA',
        zip: '22201',
        population: '238000',
        median_price: '$850,000',
        price_trend: 'up 5%',
        avg_dom: 18,
        description: 'Arlington is a dense, walkable urban county directly across the Potomac from Washington DC, anchored by the Rosslyn-Ballston corridor\'s high-rises, the thriving Clarendon restaurant scene, and the Pentagon\'s massive federal workforce. Amazon HQ2\'s arrival in National Landing has further accelerated demand, pushing prices toward the region\'s upper tier while keeping the market highly liquid.',
        neighborhoods: 'Clarendon, Ballston, Rosslyn, Lyon Village, Westover, Aurora Highlands, National Landing, Pentagon City',
        nearby: 'Alexandria, McLean, Falls Church, Washington DC',
        seller_hook: 'Arlington\'s Amazon HQ2 growth and Metro-connected demand mean sellers consistently attract multiple offers — let top Arlington agents compete on RealtorFinder to maximize your sale.',
        realtor_hook: 'Arlington\'s perpetual shortage of inventory and tech-sector buyers relocating for Amazon HQ2 create premium listing opportunities — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'alexandria',
        name: 'Alexandria',
        county: 'Alexandria City',
        state: 'VA',
        zip: '22301',
        population: '160000',
        median_price: '$850,000',
        price_trend: 'up 4%',
        avg_dom: 20,
        description: 'Alexandria blends 18th-century cobblestone charm in Old Town with modern waterfront development along the Potomac and the revitalized Del Ray arts district. The city\'s proximity to DC, Reagan National Airport, and the growing National Landing tech hub makes it one of the most sought-after addresses in Northern Virginia, drawing federal workers, consultants, and young professionals alike.',
        neighborhoods: 'Old Town, Del Ray, Eisenhower Valley, Seminary Hill, Rosemont, Parker-Gray, National Landing',
        nearby: 'Arlington, Mount Vernon, Springfield, Hybla Valley',
        seller_hook: 'Alexandria\'s Old Town cachet and proximity to DC attract a deep pool of motivated buyers — let top Alexandria realtors compete on RealtorFinder to capture premium value.',
        realtor_hook: 'Alexandria\'s historic appeal and National Landing spillover create consistent high-value listing demand — RealtorFinder connects you with sellers ready to move.',
    },
    {
        slug: 'mclean',
        name: 'McLean',
        county: 'Fairfax',
        state: 'VA',
        zip: '22101',
        population: '48000',
        median_price: '$1,400,000',
        price_trend: 'up 4%',
        avg_dom: 28,
        description: 'McLean is Northern Virginia\'s most prestigious address, home to diplomatic estates, CIA headquarters, and the grand colonial and contemporary homes that line its wooded cul-de-sacs near the Potomac Palisades. The combination of top-ranked Langley High School, easy Beltway access, and a well-established luxury market makes McLean the benchmark for high-end real estate in the DC metro area.',
        neighborhoods: 'Langley Farms, Chesterbrook, Potomac Hills, McLean Hamlet, Salona Village, Dolley Madison',
        nearby: 'Arlington, Vienna, Great Falls, Falls Church, Tysons',
        seller_hook: 'McLean\'s prestige and limited luxury inventory mean qualified buyers compete aggressively — let top McLean agents compete on RealtorFinder to achieve top-dollar results.',
        realtor_hook: 'McLean\'s ultra-high median price and affluent buyer pool produce the highest-value commissions in Northern Virginia — RealtorFinder connects you with serious sellers.',
    },
    {
        slug: 'vienna',
        name: 'Vienna',
        county: 'Fairfax',
        state: 'VA',
        zip: '22180',
        population: '16500',
        median_price: '$900,000',
        price_trend: 'up 5%',
        avg_dom: 17,
        description: 'Vienna is a beloved small-town enclave at the center of Fairfax County, offering tree-lined streets, a walkable Church Street downtown, and access to the W&OD Trail. Its highly ranked schools, Silver and Orange Line Metro access from nearby Dunn Loring, and proximity to Tysons Corner\'s employment hub make it one of the fastest-moving markets in Northern Virginia.',
        neighborhoods: 'Town of Vienna, Westwood Hills, Windover Heights, Vienna Manor, Beulah Road Corridor',
        nearby: 'Fairfax, McLean, Reston, Falls Church, Tysons',
        seller_hook: 'Vienna\'s top schools and walkable downtown generate intense buyer competition — let top Vienna realtors compete on RealtorFinder to get your home sold at maximum value.',
        realtor_hook: 'Vienna\'s perpetually low days-on-market and school-driven buyer demand create reliable listing opportunities — RealtorFinder connects you with motivated local sellers.',
    },
    {
        slug: 'fairfax',
        name: 'Fairfax',
        county: 'Fairfax City',
        state: 'VA',
        zip: '22030',
        population: '24000',
        median_price: '$700,000',
        price_trend: 'up 4%',
        avg_dom: 22,
        description: 'Fairfax City sits at the heart of Fairfax County, offering a historic Old Town district, George Mason University\'s innovation campus, and a mix of colonial-era homes and modern townhouse developments. Its central location on the Beltway and I-66 corridors, paired with strong Northern Virginia employment, keeps demand consistently ahead of supply.',
        neighborhoods: 'Old Town Fairfax, Brentwood, Layton Hall, Mantua, Mosby Woods',
        nearby: 'Vienna, Centreville, Reston, Chantilly, Burke',
        seller_hook: 'Fairfax\'s central location and George Mason University growth attract diverse buyers year-round — let top Fairfax agents compete on RealtorFinder to sell your home quickly and profitably.',
        realtor_hook: 'Fairfax City\'s active turnover and broad price range create steady listing volume — RealtorFinder connects you with sellers looking for experienced local representation.',
    },
    {
        slug: 'reston',
        name: 'Reston',
        county: 'Fairfax',
        state: 'VA',
        zip: '20190',
        population: '62000',
        median_price: '$700,000',
        price_trend: 'up 5%',
        avg_dom: 19,
        description: 'Reston is a planned community that has evolved into one of Northern Virginia\'s top technology hubs, anchored by the Silver Line Metro and a cluster of cybersecurity and defense contractors along the Dulles Corridor. Reston Town Center\'s walkable urban core, extensive trail system, and diverse housing stock from condos to single-family homes make it attractive to a wide spectrum of buyers.',
        neighborhoods: 'Reston Town Center, Lake Newport, South Lakes, North Point, Hunters Woods',
        nearby: 'Herndon, Chantilly, Vienna, Sterling, Dulles',
        seller_hook: 'Reston\'s Silver Line Metro access and tech-sector buyer base drive strong demand at every price point — let top Reston agents compete on RealtorFinder to maximize your sale.',
        realtor_hook: 'Reston\'s booming Dulles Corridor tech economy and Metro connectivity create a consistent flow of relocation buyers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'herndon',
        name: 'Herndon',
        county: 'Fairfax',
        state: 'VA',
        zip: '20170',
        population: '25000',
        median_price: '$650,000',
        price_trend: 'up 5%',
        avg_dom: 20,
        description: 'Herndon offers some of the best value in the Dulles Corridor, with a charming historic downtown, Silver Line Metro access at Innovation Center station, and a large international tech workforce drawn to nearby Dulles Airport and corridor employers like DXC Technology and Leidos. The town\'s relatively affordable entry points compared to Reston and Ashburn attract first-time buyers and upsizers alike.',
        neighborhoods: 'Downtown Herndon, McNair Farms, Worldgate, Spring Lake, Sugarland Run',
        nearby: 'Reston, Sterling, Chantilly, Dulles, Ashburn',
        seller_hook: 'Herndon\'s Metro access and value pricing attract a broad buyer pool in a competitive corridor — let top Herndon agents compete on RealtorFinder to get you the best offer.',
        realtor_hook: 'Herndon\'s diverse international buyer base and Dulles tech corridor growth create strong listing demand — RealtorFinder connects you with sellers ready to capitalize on rising prices.',
    },
    {
        slug: 'chantilly',
        name: 'Chantilly',
        county: 'Fairfax',
        state: 'VA',
        zip: '20151',
        population: '23000',
        median_price: '$680,000',
        price_trend: 'up 4%',
        avg_dom: 22,
        description: 'Chantilly is a fast-growing suburban community in western Fairfax County, known for its excellent Westfield and Chantilly High School pyramid, proximity to Dulles Airport, and the mix of newer planned communities and established neighborhoods near Route 50. The Steven F. Udvar-Hazy Center anchors local pride while major data center and defense employers fuel economic stability.',
        neighborhoods: 'South Riding, Westfield, Centreville adjacent, Pleasant Valley, Stone\'s Throw',
        nearby: 'Herndon, Centreville, Ashburn, Sterling, Fairfax',
        seller_hook: 'Chantilly\'s top school ratings and Dulles Corridor employment base drive consistent family buyer demand — let top Chantilly agents compete on RealtorFinder to sell faster at higher prices.',
        realtor_hook: 'Chantilly\'s growing data center economy and strong family buyer demand create excellent listing opportunities — RealtorFinder connects you with motivated sellers in western Fairfax.',
    },
    {
        slug: 'ashburn',
        name: 'Ashburn',
        county: 'Loudoun',
        state: 'VA',
        zip: '20147',
        population: '55000',
        median_price: '$700,000',
        price_trend: 'up 6%',
        avg_dom: 17,
        description: 'Ashburn is the undisputed data center capital of the world and one of the fastest-growing communities in Virginia, with the Silver Line\'s Loudoun Gateway and Ashburn stations opening new commuter routes to DC. Planned communities like One Loudoun\'s urban village, Broadlands, and Brambleton offer resort-style amenities, top-ranked schools, and newly built homes that attract families and tech professionals in equal measure.',
        neighborhoods: 'One Loudoun, Broadlands, Brambleton, Belmont Greene, Farmwell Hunt, Ashburn Farm',
        nearby: 'Leesburg, Sterling, Herndon, Dulles, Lansdowne',
        seller_hook: 'Ashburn\'s explosive Silver Line growth and top Loudoun County schools create fierce buyer competition — let top Ashburn agents compete on RealtorFinder to maximize your return.',
        realtor_hook: 'Ashburn\'s data center economy and new Silver Line ridership create the highest-velocity buyer market in Loudoun County — RealtorFinder connects you with serious sellers.',
    },
    {
        slug: 'leesburg',
        name: 'Leesburg',
        county: 'Loudoun',
        state: 'VA',
        zip: '20175',
        population: '53000',
        median_price: '$650,000',
        price_trend: 'up 5%',
        avg_dom: 21,
        description: 'Leesburg combines a beautifully preserved colonial downtown with rapid suburban growth on its edges, serving as Loudoun County\'s seat and a growing destination for families priced out of closer-in Northern Virginia. The Leesburg Premium Outlets, a thriving wine country corridor along Route 7, and strong community character make it a popular lifestyle choice for commuters willing to trade proximity for space.',
        neighborhoods: 'Downtown Leesburg, Lansdowne, River Creek, Tuscarora, Woodlea Manor, Stratford',
        nearby: 'Ashburn, Purcellville, Hamilton, Round Hill, Dulles',
        seller_hook: 'Leesburg\'s charming downtown and Loudoun wine country lifestyle appeal attract buyers from across the region — let top Leesburg agents compete on RealtorFinder to get you top dollar.',
        realtor_hook: 'Leesburg\'s steady population growth and lifestyle appeal create a reliable stream of motivated buyers and sellers — RealtorFinder connects you with listings across Loudoun County\'s seat.',
    },
    {
        slug: 'woodbridge',
        name: 'Woodbridge',
        county: 'Prince William',
        state: 'VA',
        zip: '22191',
        population: '93000',
        median_price: '$450,000',
        price_trend: 'up 5%',
        avg_dom: 23,
        description: 'Woodbridge anchors the rapidly growing Prince William County corridor along I-95, offering one of the most affordable entry points to the DC metro area with VRE commuter rail access and a booming Potomac Mills retail district. The Dale City area\'s established neighborhoods and newer Lake Ridge communities attract federal workers and military families seeking space and value within commuting distance of the Pentagon and Fort Belvoir.',
        neighborhoods: 'Lake Ridge, Dale City, Occoquan, Potomac Mills, Marumsco, Rippon Landing',
        nearby: 'Manassas, Dumfries, Lorton, Occoquan, Stafford',
        seller_hook: 'Woodbridge\'s affordability in the DC metro corridor creates strong buyer demand from value-seeking families — let top Woodbridge agents compete on RealtorFinder to capture the best offer.',
        realtor_hook: 'Woodbridge\'s high volume of federal worker and military family buyers creates one of the most active listing markets in Prince William County — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'manassas',
        name: 'Manassas',
        county: 'Manassas City',
        state: 'VA',
        zip: '20110',
        population: '44000',
        median_price: '$420,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'Manassas balances Civil War battlefield history with modern suburban growth, featuring a revitalized Old Town district, VRE commuter rail service to DC, and one of Prince William County\'s most affordable housing markets. The city\'s growing Latino business community adds cultural vibrancy to its commercial corridors while its price points draw first-time buyers and investors from across the region.',
        neighborhoods: 'Old Town Manassas, Sudley, Bull Run, Yorkshire, Signal Hill, Blooms',
        nearby: 'Woodbridge, Centreville, Gainesville, Haymarket, Bristow',
        seller_hook: 'Manassas\'s affordability relative to the broader DC metro area drives consistent first-time buyer demand — let top Manassas agents compete on RealtorFinder to sell your home at market peak.',
        realtor_hook: 'Manassas\'s active first-time buyer market and steady price appreciation make it an excellent market for agents building listing volume — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'richmond',
        name: 'Richmond',
        county: 'Richmond City',
        state: 'VA',
        zip: '23220',
        population: '230000',
        median_price: '$380,000',
        price_trend: 'up 6%',
        avg_dom: 20,
        description: 'Richmond has emerged as one of the South\'s most exciting mid-size cities, with a world-class craft beer scene in Scott\'s Addition, a revitalized Canal Walk and Shockoe Bottom, and one of the country\'s best urban outdoor recreation corridors along the James River. Virginia Commonwealth University anchors a creative economy that draws young professionals, while the Fan District and Church Hill\'s preserved Victorian architecture give the city authentic historic character.',
        neighborhoods: 'The Fan, Carytown, Scott\'s Addition, Church Hill, Jackson Ward, Shockoe Bottom, Museum District, Ginter Park',
        nearby: 'Glen Allen, Henrico, Chesterfield, Midlothian, Short Pump',
        seller_hook: 'Richmond\'s rapid gentrification and growing remote-worker in-migration are pushing prices higher across all neighborhoods — let top Richmond agents compete on RealtorFinder to capture peak value.',
        realtor_hook: 'Richmond\'s booming urban neighborhoods and steady in-migration from DC and the Northeast create outstanding listing opportunities — RealtorFinder connects you with motivated city sellers.',
    },
    {
        slug: 'glen-allen',
        name: 'Glen Allen',
        county: 'Henrico',
        state: 'VA',
        zip: '23060',
        population: '47000',
        median_price: '$450,000',
        price_trend: 'up 5%',
        avg_dom: 21,
        description: 'Glen Allen is one of Henrico County\'s premier suburban destinations, stretching along the I-295 and I-64 corridor north of Richmond with master-planned communities, Innsbrook Corporate Center\'s dense office campus, and top-rated Henrico County schools. Its mix of established golf course communities and newer townhouse developments attracts corporate relocations and move-up buyers seeking Richmond\'s best suburbs.',
        neighborhoods: 'Innsbrook, Wyndham, Henrico Crossing, Twin Hickory, Hungary Creek, Staples Mill',
        nearby: 'Richmond, Short Pump, Mechanicsville, Ashland, Chesterfield',
        seller_hook: 'Glen Allen\'s top Henrico schools and Innsbrook corporate corridor drive strong relocation and move-up buyer demand — let top Glen Allen agents compete on RealtorFinder for best results.',
        realtor_hook: 'Glen Allen\'s corporate relocation pipeline and active move-up market create consistent high-value listing opportunities — RealtorFinder connects you with motivated sellers in Henrico\'s north corridor.',
    },
    {
        slug: 'chesterfield',
        name: 'Chesterfield',
        county: 'Chesterfield',
        state: 'VA',
        zip: '23832',
        population: '370000',
        median_price: '$420,000',
        price_trend: 'up 5%',
        avg_dom: 23,
        description: 'Chesterfield County encompasses one of Virginia\'s fastest-growing suburban jurisdictions south of Richmond, with a mix of established Midlothian communities, newer developments along Hull Street and Rt. 288, and a strong school system that consistently ranks among the state\'s best. The county\'s lower taxes and larger lot sizes compared to Henrico attract families seeking more space at accessible Richmond-area prices.',
        neighborhoods: 'Midlothian, Swift Creek, Brandermill, Woodlake, Ettrick, Chester',
        nearby: 'Richmond, Midlothian, Colonial Heights, Petersburg, Hopewell',
        seller_hook: 'Chesterfield\'s combination of top schools and value pricing generates intense family buyer competition — let top Chesterfield agents compete on RealtorFinder to achieve your best sale price.',
        realtor_hook: 'Chesterfield County\'s rapid growth and high transaction volume make it one of the Richmond metro\'s most productive listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'henrico',
        name: 'Henrico',
        county: 'Henrico',
        state: 'VA',
        zip: '23228',
        population: '330000',
        median_price: '$400,000',
        price_trend: 'up 5%',
        avg_dom: 22,
        description: 'Henrico County wraps around Richmond\'s north, east, and west borders, offering suburban communities at every price point alongside major retail in the Short Pump area, Virginia\'s largest airport, and the Richmond International Raceway. Its Libbie Mill mixed-use district and revitalized Staples Mill corridor reflect Henrico\'s commitment to walkable development while maintaining the affordable family housing the county has long been known for.',
        neighborhoods: 'Short Pump, Varina, Sandston, Highland Springs, Lakeside, Three Chopt',
        nearby: 'Richmond, Glen Allen, Short Pump, Mechanicsville',
        seller_hook: 'Henrico County\'s broad buyer base and proximity to Richmond ensure strong demand across all price points — let top Henrico agents compete on RealtorFinder for your best offer.',
        realtor_hook: 'Henrico County\'s high transaction volume and diverse housing stock create consistent listing opportunities for agents — RealtorFinder connects you with motivated sellers across the county.',
    },
    {
        slug: 'short-pump',
        name: 'Short Pump',
        county: 'Henrico',
        state: 'VA',
        zip: '23233',
        population: '28000',
        median_price: '$550,000',
        price_trend: 'up 6%',
        avg_dom: 18,
        description: 'Short Pump has transformed from a crossroads into Richmond\'s premier suburban destination, anchored by the Short Pump Town Center lifestyle mall, top-ranked Deep Run and Godwin High Schools, and a dense concentration of upscale new construction and established golf communities. The area\'s rapid commercial development along I-64 and West Broad Street continues to attract corporate relocations and affluent families seeking the best of Richmond\'s western suburbs.',
        neighborhoods: 'Wellesley, Charter Colony, Bacova, Gayton Crossing, Twin Hickory, Lauderdale',
        nearby: 'Glen Allen, Richmond, Manakin-Sabot, Goochland, Henrico',
        seller_hook: 'Short Pump\'s top schools and upscale retail corridor create fierce buyer competition for quality listings — let top Short Pump agents compete on RealtorFinder to maximize your sale.',
        realtor_hook: 'Short Pump\'s affluent buyer pool and rapid commercial growth produce some of the Richmond area\'s highest price points and strongest listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'midlothian',
        name: 'Midlothian',
        county: 'Chesterfield',
        state: 'VA',
        zip: '23113',
        population: '62000',
        median_price: '$480,000',
        price_trend: 'up 5%',
        avg_dom: 20,
        description: 'Midlothian is the jewel of Chesterfield County\'s western corridor, with the Brandermill and Woodlake lake communities, Swift Creek Reservoir waterfront properties, and top-ranked Midlothian and Clover Hill High Schools drawing families from across the Richmond region. Its blend of wooded, established neighborhoods and newer planned communities makes Midlothian one of Virginia\'s most consistently desirable suburban addresses.',
        neighborhoods: 'Brandermill, Woodlake, Waterford, Coalfield, Midlothian Village, Foxcroft',
        nearby: 'Chesterfield, Richmond, Colonial Heights, Powhatan, Goochland',
        seller_hook: 'Midlothian\'s lake communities and top schools create intense demand with limited inventory — let top Midlothian agents compete on RealtorFinder to sell faster and for more.',
        realtor_hook: 'Midlothian\'s desirable lake communities and top-school reputation drive strong buyer demand year-round — RealtorFinder connects you with motivated sellers in Chesterfield\'s best zip codes.',
    },
    {
        slug: 'virginia-beach',
        name: 'Virginia Beach',
        county: 'Virginia Beach City',
        state: 'VA',
        zip: '23451',
        population: '460000',
        median_price: '$380,000',
        price_trend: 'up 5%',
        avg_dom: 25,
        description: 'Virginia Beach is the largest city in Virginia by population and the anchor of the Hampton Roads metro area, combining 35 miles of Atlantic coastline, the booming Town Center urban district, and one of the largest concentrations of military personnel in the nation at Naval Air Station Oceana and Joint Expeditionary Base Little Creek. The Oceanfront resort strip and Princess Anne\'s rural southern reaches offer a range of lifestyles within the same city boundaries.',
        neighborhoods: 'Oceanfront, Town Center, Great Neck, Kempsville, Red Mill, Pungo, Sandbridge',
        nearby: 'Norfolk, Chesapeake, Hampton, Portsmouth, Suffolk',
        seller_hook: 'Virginia Beach\'s large military buyer pool and vacation home demand create year-round sales opportunities — let top Virginia Beach agents compete on RealtorFinder for your best outcome.',
        realtor_hook: 'Virginia Beach\'s military relocation volume and diverse neighborhood demand make it one of Virginia\'s highest-transaction markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'norfolk',
        name: 'Norfolk',
        county: 'Norfolk City',
        state: 'VA',
        zip: '23510',
        population: '238000',
        median_price: '$310,000',
        price_trend: 'up 5%',
        avg_dom: 27,
        description: 'Norfolk is the cultural and economic heart of Hampton Roads, home to Naval Station Norfolk — the world\'s largest naval base — as well as Old Dominion University, a revitalized Granby Street arts corridor, and the historic Ghent and Freemason districts. The city\'s ongoing Tide light rail expansion and waterfront development projects continue to draw investment, while its affordability relative to the broader mid-Atlantic metro area attracts buyers priced out of larger markets.',
        neighborhoods: 'Ghent, Freemason, Larchmont, Park Place, Ocean View, Wards Corner, Lamberts Point',
        nearby: 'Virginia Beach, Portsmouth, Chesapeake, Hampton, Suffolk',
        seller_hook: 'Norfolk\'s military relocation demand and ongoing urban renewal attract buyers across all price ranges — let top Norfolk agents compete on RealtorFinder to get your home sold.',
        realtor_hook: 'Norfolk\'s high military relocation volume and affordable price points create consistent listing demand — RealtorFinder connects you with motivated sellers in the heart of Hampton Roads.',
    },
    {
        slug: 'chesapeake',
        name: 'Chesapeake',
        county: 'Chesapeake City',
        state: 'VA',
        zip: '23320',
        population: '250000',
        median_price: '$380,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Chesapeake offers some of the most spacious suburban living in Hampton Roads, with large lots, top-ranked schools, and master-planned communities like Great Bridge and Grassfield drawing families seeking value and space. The city\'s southern agricultural heartland in the Deep Creek and Chesapeake Landing areas contrasts with the denser northern corridor near the Military Highway, giving buyers a range of lifestyle options within one of Virginia\'s fastest-growing independent cities.',
        neighborhoods: 'Great Bridge, Greenbrier, Deep Creek, Hickory, Western Branch, Grassfield',
        nearby: 'Norfolk, Virginia Beach, Suffolk, Portsmouth',
        seller_hook: 'Chesapeake\'s top-ranked schools and large-lot suburban appeal attract motivated family buyers — let top Chesapeake agents compete on RealtorFinder to maximize your home\'s value.',
        realtor_hook: 'Chesapeake\'s rapid growth and strong school reputation create steady listing demand across its diverse neighborhoods — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'suffolk',
        name: 'Suffolk',
        county: 'Suffolk City',
        state: 'VA',
        zip: '23434',
        population: '95000',
        median_price: '$350,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Suffolk is the largest city by land area in Virginia and one of Hampton Roads\' most affordable and fastest-growing communities, with the River\'s Bend and Harbour View master-planned communities driving population growth along the James River corridor. Its peanut-processing heritage gives way to a modern economy driven by Amazon fulfillment, military contracting, and healthcare, while lower prices relative to neighboring Chesapeake and Virginia Beach attract value-conscious buyers.',
        neighborhoods: 'Harbour View, Driver, Westhaven, Nansemond Village, Bennett\'s Creek, Lake Prince',
        nearby: 'Chesapeake, Norfolk, Portsmouth, Isle of Wight, Smithfield',
        seller_hook: 'Suffolk\'s affordability and rapid growth create strong buyer competition at accessible price points — let top Suffolk agents compete on RealtorFinder to get you the best possible offer.',
        realtor_hook: 'Suffolk\'s rapid population growth and affordable entry prices create strong listing volume and motivated buyers — RealtorFinder connects you with sellers ready to capitalize on rising demand.',
    },
    {
        slug: 'hampton',
        name: 'Hampton',
        county: 'Hampton City',
        state: 'VA',
        zip: '23661',
        population: '135000',
        median_price: '$290,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Hampton is the oldest continuously English-speaking settlement in the United States, home to Langley Air Force Base, NASA Langley Research Center, and Hampton University, creating one of Virginia\'s most diverse economic bases. The Phoebus arts district and the new Hampton Coliseum area redevelopment are driving urban renewal, while the city\'s waterfront and affordable prices make it attractive to first-time buyers and military families.',
        neighborhoods: 'Phoebus, Buckroe Beach, Fox Hill, Hampton Roads Center, Wythe, Coliseum',
        nearby: 'Newport News, Norfolk, Virginia Beach, Poquoson',
        seller_hook: 'Hampton\'s military and NASA buyer base provides consistent demand at affordable price points — let top Hampton agents compete on RealtorFinder to achieve the best outcome for your home.',
        realtor_hook: 'Hampton\'s Langley AFB and NASA Langley Research Center create a steady stream of relocating buyers — RealtorFinder connects you with motivated sellers in this historic waterfront city.',
    },
    {
        slug: 'newport-news',
        name: 'Newport News',
        county: 'Newport News City',
        state: 'VA',
        zip: '23601',
        population: '186000',
        median_price: '$300,000',
        price_trend: 'up 5%',
        avg_dom: 26,
        description: 'Newport News is home to Newport News Shipbuilding — the largest private employer in Virginia — as well as Jefferson Laboratory and a major Fort Eustis Army installation, anchoring the city\'s defense-heavy economy. The Denbigh and Kiln Creek corridors offer suburban family neighborhoods, while the revitalized Hilton Village — one of the nation\'s oldest planned communities — adds historic character to an otherwise industrial waterfront city.',
        neighborhoods: 'Hilton Village, Denbigh, Kiln Creek, Port Warwick, Oyster Point, Deer Park',
        nearby: 'Hampton, Yorktown, Williamsburg, Poquoson',
        seller_hook: 'Newport News\'s shipbuilding and military workforce creates reliable buyer demand across all price points — let top Newport News agents compete on RealtorFinder to sell your home successfully.',
        realtor_hook: 'Newport News\'s defense-industry employment base generates a constant stream of relocating buyers — RealtorFinder connects you with motivated sellers in this active Hampton Roads market.',
    },
    {
        slug: 'williamsburg',
        name: 'Williamsburg',
        county: 'James City',
        state: 'VA',
        zip: '23185',
        population: '15000',
        median_price: '$420,000',
        price_trend: 'up 4%',
        avg_dom: 30,
        description: 'Williamsburg is one of Virginia\'s most distinctive real estate markets, blending Colonial Williamsburg\'s globally recognized historic district with the resort amenities of Kingsmill on the James, Ford\'s Colony, and Governor\'s Land. College of William & Mary anchors a vibrant academic community while the area\'s growing retiree population, attracted by the Golden Horseshoe golf courses and Busch Gardens entertainment, creates diverse buyer demand across the Historic Triangle.',
        neighborhoods: 'Colonial Williamsburg, Kingsmill, Ford\'s Colony, Governor\'s Land, New Town, Powhatan Crossing',
        nearby: 'Newport News, Hampton, Yorktown, Jamestown, Charles City',
        seller_hook: 'Williamsburg\'s unique historic appeal and resort amenities attract buyers from across the country — let top Williamsburg agents compete on RealtorFinder to find your ideal buyer.',
        realtor_hook: 'Williamsburg\'s blend of historic prestige and resort living attracts out-of-state and retiree buyers seeking distinctive properties — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'charlottesville',
        name: 'Charlottesville',
        county: 'Albemarle',
        state: 'VA',
        zip: '22901',
        population: '47000',
        median_price: '$500,000',
        price_trend: 'up 5%',
        avg_dom: 24,
        description: 'Charlottesville combines the intellectual energy of the University of Virginia with the culinary and cultural cachet of a destination city that regularly appears on "best places to live" rankings. The Downtown Mall pedestrian corridor, Crozet\'s growing community, and the nearby Blue Ridge mountain wineries create a lifestyle that draws remote workers, retirees, and young professionals from the East Coast\'s largest metros, driving sustained price appreciation.',
        neighborhoods: 'Downtown, Belmont, Fifeville, North Downtown, Woolen Mills, Crozet, Pantops',
        nearby: 'Waynesboro, Staunton, Culpeper, Harrisonburg',
        seller_hook: 'Charlottesville\'s UVA prestige and lifestyle appeal attract buyers from across the country — let top Charlottesville agents compete on RealtorFinder to capture maximum value for your home.',
        realtor_hook: 'Charlottesville\'s remote-worker in-migration and university-driven demand create a robust seller\'s market — RealtorFinder connects you with motivated sellers in one of Virginia\'s most desirable cities.',
    },
    {
        slug: 'roanoke',
        name: 'Roanoke',
        county: 'Roanoke City',
        state: 'VA',
        zip: '24011',
        population: '100000',
        median_price: '$280,000',
        price_trend: 'up 5%',
        avg_dom: 28,
        description: 'Roanoke is Western Virginia\'s largest city and an outdoor recreation hub, with the Blue Ridge Parkway and Appalachian Trail accessible within minutes of its revitalized downtown Market District. The Roanoke Star overlooks a city undergoing significant downtown investment, with Carilion Clinic\'s biomedical research campus and Virginia Tech Carilion School of Medicine anchoring an emerging healthcare innovation economy that is drawing talent and investment from across the country.',
        neighborhoods: 'Downtown, Grandin Village, South Roanoke, Norwich, Wasena, Williamson Road, Hollins',
        nearby: 'Salem, Vinton, Hollins, Blacksburg, Lynchburg',
        seller_hook: 'Roanoke\'s outdoor recreation appeal and affordable prices are attracting remote workers from high-cost metros — let top Roanoke agents compete on RealtorFinder to get your best offer.',
        realtor_hook: 'Roanoke\'s emerging biomedical economy and remote-worker in-migration are driving appreciation in a historically affordable market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'lynchburg',
        name: 'Lynchburg',
        county: 'Lynchburg City',
        state: 'VA',
        zip: '24501',
        population: '82000',
        median_price: '$260,000',
        price_trend: 'up 5%',
        avg_dom: 30,
        description: 'Lynchburg is Virginia\'s Hill City, built across seven hills above the James River and home to Liberty University — one of the world\'s largest Christian universities — as well as Randolph College, University of Lynchburg, and a growing advanced manufacturing sector. The Historic Garland Hill and Diamond Hill districts offer beautifully preserved Victorian architecture at prices that remain among the most accessible in the entire mid-Atlantic region.',
        neighborhoods: 'Garland Hill, Diamond Hill, Boonsboro, Forest, Timberlake, Amherst Avenue',
        nearby: 'Bedford, Amherst, Campbell, Appomattox, Roanoke',
        seller_hook: 'Lynchburg\'s affordability and Liberty University growth attract buyers from across Virginia — let top Lynchburg agents compete on RealtorFinder to get your home sold at the best price.',
        realtor_hook: 'Lynchburg\'s active university community and affordable price points create consistent buyer activity — RealtorFinder connects you with motivated sellers looking for strong local representation.',
    },
    {
        slug: 'blacksburg',
        name: 'Blacksburg',
        county: 'Montgomery',
        state: 'VA',
        zip: '24060',
        population: '45000',
        median_price: '$320,000',
        price_trend: 'up 4%',
        avg_dom: 25,
        description: 'Blacksburg is home to Virginia Tech — one of the nation\'s leading engineering and research universities — and has grown into a nationally recognized technology hub through the Virginia Tech Corporate Research Center\'s cluster of startups and established tech firms. The town\'s vibrant Main Street, access to the New River Trail and Jefferson National Forest, and a college-town energy driven by 37,000 students make it a distinctive and increasingly competitive real estate market.',
        neighborhoods: 'Warm Hearth Village, Tom\'s Creek, Prices Fork, Progress Street, Harding Avenue, Ellett Valley',
        nearby: 'Christiansburg, Radford, Roanoke, Salem, Pulaski',
        seller_hook: 'Blacksburg\'s Virginia Tech economy and growing tech sector attract faculty, researchers, and startup buyers — let top Blacksburg agents compete on RealtorFinder to maximize your sale.',
        realtor_hook: 'Blacksburg\'s Virginia Tech Research Center creates steady faculty and tech-sector buyer demand — RealtorFinder connects you with motivated sellers in this growing university town.',
    },
];
