module.exports = [
    // ── Chittenden County (Burlington metro) ──────────────────────────────
    {
        slug: 'burlington',
        name: 'Burlington',
        county: 'Chittenden',
        state: 'VT',
        zip: '05401',
        population: '45,000',
        median_price: '$419,000',
        price_trend: 'up 10%',
        avg_dom: 16,
        description: 'Burlington is Vermont\'s largest city and cultural hub, with a thriving waterfront on Lake Champlain, a nationally recognized Church Street Marketplace, and the University of Vermont driving steady housing demand year-round. The diverse mix of students, young professionals, and long-time residents creates a dynamic market where well-priced homes attract multiple offers within days.',
        neighborhoods: 'Hill Section, New North End, Old North End, South End Arts District, downtown waterfront, University of Vermont area',
        nearby: 'South Burlington, Winooski, Colchester, Shelburne, Essex Junction',
        seller_hook: 'Burlington\'s chronic housing shortage and UVM-driven demand mean well-prepared sellers routinely see bidding wars — list now to capitalize on the city\'s tightest inventory in years.',
        realtor_hook: 'Burlington\'s blend of urban amenities, lakefront lifestyle, and a 16-day average market time makes it one of Vermont\'s most rewarding markets for agents who know how to price aggressively and move fast.',
    },
    {
        slug: 'south-burlington',
        name: 'South Burlington',
        county: 'Chittenden',
        state: 'VT',
        zip: '05403',
        population: '20,000',
        median_price: '$479,000',
        price_trend: 'up 8%',
        avg_dom: 18,
        description: 'South Burlington offers suburban convenience directly adjacent to Burlington, with top-rated schools, major retail corridors, and newer residential developments that attract families and remote workers priced out of the city. Its proximity to Burlington International Airport and I-89 makes it one of Chittenden County\'s most practical — and consistently appreciating — addresses.',
        neighborhoods: 'Dorset Street corridor, Shelburne Road area, Red Rocks, Williston Road, South Village',
        nearby: 'Burlington, Shelburne, Williston, Hinesburg',
        seller_hook: 'South Burlington\'s combination of top schools, airport proximity, and robust appreciation gives sellers a strong story that resonates with every buyer demographic in Chittenden County.',
        realtor_hook: 'With newer construction, diverse price points, and families actively competing for limited listings, South Burlington delivers consistent transaction volume that rewards well-connected agents.',
    },
    {
        slug: 'essex-junction',
        name: 'Essex Junction',
        county: 'Chittenden',
        state: 'VT',
        zip: '05452',
        population: '11,000',
        median_price: '$389,000',
        price_trend: 'up 9%',
        avg_dom: 17,
        description: 'Essex Junction combines small-town charm at the historic Five Corners with easy access to Burlington and IBM\'s Vermont campus, making it a perennial favorite for tech workers and young families seeking affordability without sacrificing convenience. Strong school systems and a tight-knit community keep demand elevated and days-on-market consistently low.',
        neighborhoods: 'Essex Junction Village, Five Corners, Maple Street, Towers neighborhood',
        nearby: 'Essex, Burlington, Williston, Colchester',
        seller_hook: 'Essex Junction\'s IBM employment anchor and sub-17-day average market time signal that now is an ideal moment for sellers to act before competing listings appear.',
        realtor_hook: 'Tech-sector demand and a loyal move-up buyer pool make Essex Junction a reliable source of repeat business for agents who build relationships in this tight-knit community.',
    },
    {
        slug: 'colchester',
        name: 'Colchester',
        county: 'Chittenden',
        state: 'VT',
        zip: '05446',
        population: '17,000',
        median_price: '$379,000',
        price_trend: 'up 8%',
        avg_dom: 19,
        description: 'Colchester stretches from lakefront communities on Malletts Bay to suburban neighborhoods near I-89, offering one of Chittenden County\'s most varied housing landscapes at prices still accessible to first-time buyers. The combination of waterfront appeal, National Guard employment, and Burlington commuter convenience keeps this market steadily active.',
        neighborhoods: 'Malletts Bay, Colchester Center, Blakely Road area, Airport Park',
        nearby: 'Burlington, Winooski, Essex, Milton',
        seller_hook: 'Malletts Bay waterfront and suburban lots alike are moving quickly in Colchester — sellers benefit from a wide buyer pool drawn by affordability and lake access.',
        realtor_hook: 'Colchester\'s diverse inventory — from entry-level condos to lakefront estates — gives agents the flexibility to serve buyers at every stage of the housing ladder.',
    },
    {
        slug: 'shelburne',
        name: 'Shelburne',
        county: 'Chittenden',
        state: 'VT',
        zip: '05482',
        population: '7,600',
        median_price: '$579,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Shelburne is one of Vermont\'s most coveted addresses, blending preserved farmland, Lake Champlain waterfront, and the landmark Shelburne Museum with upscale residential neighborhoods that attract affluent buyers from across the Northeast. Large lots, equestrian properties, and architecturally distinctive homes give the market a luxury character rarely found this close to Burlington.',
        neighborhoods: 'Shelburne Village, Shelburne Farms area, Church Street, Bay Road',
        nearby: 'Burlington, South Burlington, Charlotte, Hinesburg',
        seller_hook: 'Shelburne\'s prestige address and limited inventory create strong seller leverage — luxury properties here command premiums that few other Vermont communities can match.',
        realtor_hook: 'Shelburne\'s affluent, discerning buyer pool rewards agents with deep local knowledge and the ability to market high-end properties to out-of-state relocators and second-home seekers.',
    },
    {
        slug: 'williston',
        name: 'Williston',
        county: 'Chittenden',
        state: 'VT',
        zip: '05495',
        population: '9,600',
        median_price: '$519,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Williston has evolved from a quiet farming community into one of Chittenden County\'s fastest-growing suburbs, anchored by the Taft Corners retail hub and new residential subdivisions that appeal to families seeking more space than Burlington offers. Excellent schools, easy highway access, and a growing local amenity base keep buyers competing for the limited homes that come to market.',
        neighborhoods: 'Williston Village, Taft Corners, Oak Hill, Marshall Avenue',
        nearby: 'Essex, South Burlington, Richmond, Hinesburg',
        seller_hook: 'Williston\'s rapid growth and family-driven demand ensure sellers face a motivated, pre-qualified buyer pool ready to act quickly on well-priced homes.',
        realtor_hook: 'New construction activity and a constant stream of corporate relocations to Chittenden County make Williston a high-velocity market where proactive agents thrive.',
    },
    {
        slug: 'winooski',
        name: 'Winooski',
        county: 'Chittenden',
        state: 'VT',
        zip: '05404',
        population: '7,300',
        median_price: '$339,000',
        price_trend: 'up 11%',
        avg_dom: 18,
        description: 'Winooski — Vermont\'s smallest city — has undergone a remarkable urban renaissance, with the redeveloped Champlain Mill district, a vibrant restaurant scene, and some of the state\'s most diverse and walkable neighborhoods drawing young buyers priced out of Burlington. Its exceptional price-to-location ratio and strong community investment signal continued above-average appreciation.',
        neighborhoods: 'Downtown Winooski, Champlain Mill area, Alder Street, Weaver Street',
        nearby: 'Burlington, Colchester, Essex Junction',
        seller_hook: 'Winooski\'s 11% price growth and walkability buzz are pulling in a new generation of buyers — sellers who act now are ideally positioned to capture peak demand.',
        realtor_hook: 'Winooski\'s renaissance story sells itself to millennial and Gen Z buyers, giving savvy agents a compelling narrative that drives urgency and strong offers.',
    },

    // ── Central Vermont ───────────────────────────────────────────────────
    {
        slug: 'montpelier',
        name: 'Montpelier',
        county: 'Washington',
        state: 'VT',
        zip: '05602',
        population: '7,500',
        median_price: '$319,000',
        price_trend: 'up 9%',
        avg_dom: 22,
        description: 'Montpelier, the nation\'s smallest state capital, offers a remarkably walkable downtown with independent bookshops, farm-to-table restaurants, and a civic energy that attracts remote workers, state employees, and sustainability-minded buyers seeking authentic Vermont character. Victorian and Craftsman homes near Hubbard Park command growing premiums as buyers discover how much community this small city delivers.',
        neighborhoods: 'Downtown Montpelier, Berlin Street, Barre Street corridor, Hubbard Park area',
        nearby: 'Barre, Northfield, Berlin, Middlesex',
        seller_hook: 'Remote workers are discovering Montpelier\'s unmatched walkability and community fabric — sellers are meeting buyers from across the country who are willing to pay a premium for genuine Vermont living.',
        realtor_hook: 'Montpelier\'s national profile as a desirable remote-work destination brings well-qualified out-of-state buyers to market, rewarding agents who understand how to serve relocating clients.',
    },
    {
        slug: 'barre',
        name: 'Barre',
        county: 'Washington',
        state: 'VT',
        zip: '05641',
        population: '8,500',
        median_price: '$189,000',
        price_trend: 'up 12%',
        avg_dom: 28,
        description: 'Barre — the self-proclaimed Granite Capital of the World — offers some of Vermont\'s most affordable homeownership opportunities, with a working-class heritage, striking granite architecture, and a tight-knit community that is attracting first-time buyers and investors seeking strong rental yields. Rising prices reflect growing recognition of this undervalued market\'s potential.',
        neighborhoods: 'Barre City, Granite Street, Old Labor Hall area, South Barre',
        nearby: 'Montpelier, Berlin, Northfield, Orange',
        seller_hook: 'Barre\'s 12% appreciation is the highest in Washington County — sellers who have waited for the right moment will find a motivated first-time buyer pool ready to compete.',
        realtor_hook: 'Barre\'s affordability and rising investor interest create a high-volume transaction environment that rewards agents who know how to work with first-time buyers and rental property clients.',
    },
    {
        slug: 'northfield',
        name: 'Northfield',
        county: 'Washington',
        state: 'VT',
        zip: '05663',
        population: '5,900',
        median_price: '$259,000',
        price_trend: 'up 10%',
        avg_dom: 26,
        description: 'Northfield blends small-town Vermont charm with the institutional anchor of Norwich University, New England\'s oldest private military college, creating a stable housing market with steady rental demand and a growing population of faculty, staff, and alumni buyers. The scenic Winooski River corridor and classic village streetscapes add significant appeal for buyers seeking authenticity at accessible prices.',
        neighborhoods: 'Northfield Village, Norwich University area, Northfield Falls',
        nearby: 'Montpelier, Barre, Roxbury, Warren',
        seller_hook: 'Norwich University\'s steady enrollment and faculty housing needs mean Northfield sellers have access to a reliable, pre-qualified buyer pool that few similarly sized Vermont towns can match.',
        realtor_hook: 'The university-anchored market and growing remote-work appeal give Northfield agents a diverse client base of academics, first-time buyers, and investors seeking strong Vermont value.',
    },

    // ── Southern Vermont ──────────────────────────────────────────────────
    {
        slug: 'rutland',
        name: 'Rutland',
        county: 'Rutland',
        state: 'VT',
        zip: '05701',
        population: '15,000',
        median_price: '$189,000',
        price_trend: 'up 11%',
        avg_dom: 30,
        description: 'Rutland is Vermont\'s second-largest city and its most affordable urban market, undergoing a notable downtown revitalization driven by arts investment, new dining, and remote workers drawn by sub-$200K prices and easy access to Killington and Pico ski areas. The combination of healthcare employment at Rutland Regional Medical Center and recreational proximity makes this a compelling value proposition.',
        neighborhoods: 'Downtown Rutland, West Rutland, Rutland Town, Center Street',
        nearby: 'Killington, Castleton, Brandon, Proctor',
        seller_hook: 'Rutland\'s downtown revival and ski-proximity buzz are attracting buyers who once overlooked the city — sellers are finding demand they haven\'t seen in a generation.',
        realtor_hook: 'Rutland\'s revitalization story, affordable entry points, and ski-country appeal make it one of Vermont\'s most compelling pitches to remote workers and lifestyle buyers looking to stretch their dollar.',
    },
    {
        slug: 'brattleboro',
        name: 'Brattleboro',
        county: 'Windham',
        state: 'VT',
        zip: '05301',
        population: '11,500',
        median_price: '$259,000',
        price_trend: 'up 11%',
        avg_dom: 25,
        description: 'Brattleboro is southern Vermont\'s cultural epicenter — a progressive arts community with a legendary downtown, thriving music and food scene, and a Connecticut River setting that draws buyers from Boston and New York seeking an affordable creative lifestyle. Its position at the Vermont-Massachusetts border makes it one of the state\'s most accessible entry points for out-of-state buyers.',
        neighborhoods: 'Downtown Brattleboro, West Brattleboro, Putney Road, Whetstone Brook area',
        nearby: 'Putney, Dummerston, Hinsdale NH, Northfield MA',
        seller_hook: 'Brattleboro\'s arts-community cachet and strategic I-91 corridor location are pulling motivated buyers up from Massachusetts and Connecticut — sellers here benefit from a larger geographic buyer pool than almost anywhere else in Vermont.',
        realtor_hook: 'Brattleboro\'s appeal to creative-class buyers from major metros gives agents the opportunity to serve high-motivation out-of-state clients who close quickly and value local expertise.',
    },
    {
        slug: 'springfield-vt',
        name: 'Springfield',
        county: 'Windsor',
        state: 'VT',
        zip: '05156',
        population: '9,000',
        median_price: '$195,000',
        price_trend: 'up 10%',
        avg_dom: 28,
        description: 'Springfield sits at the confluence of the Connecticut and Black rivers in the Upper Connecticut River Valley, offering some of Windsor County\'s most affordable single-family homes alongside a proud industrial heritage and growing outdoor recreation draw along the North Springfield Lake corridor. First-time buyers and investors are taking notice of per-square-foot values that are hard to find anywhere else in the region.',
        neighborhoods: 'Springfield Village, Crown Point Road, Valley Street, North Springfield',
        nearby: 'Bellows Falls, Ludlow, Chester, Claremont NH',
        seller_hook: 'Springfield\'s affordability and rising regional interest make this an opportune moment to list — buyers priced out of Woodstock and Ludlow are actively looking here.',
        realtor_hook: 'Springfield\'s value positioning relative to pricier Windsor County towns gives agents a compelling pitch for buyers who want Vermont quality at accessible prices.',
    },
    {
        slug: 'bellows-falls',
        name: 'Bellows Falls',
        county: 'Windham',
        state: 'VT',
        zip: '05101',
        population: '3,000',
        median_price: '$189,000',
        price_trend: 'up 11%',
        avg_dom: 30,
        description: 'Bellows Falls is a compact Connecticut River mill village undergoing genuine revitalization, with murals, independent businesses, and an artisan community transforming its compact downtown into one of southern Vermont\'s most distinctive destinations. Extremely affordable by regional standards, it attracts buyers seeking character properties and investors anticipating continued gentrification.',
        neighborhoods: 'Downtown Bellows Falls, Rockingham, Walpole NH side',
        nearby: 'Springfield, Saxtons River, Brattleboro, Claremont NH',
        seller_hook: 'Bellows Falls\' revitalization momentum and rock-bottom entry prices are attracting a new wave of buyers — sellers with character properties are finding competitive offers from buyers who recognize untapped value.',
        realtor_hook: 'The Bellows Falls renaissance creates real opportunity for agents who can tell its revitalization story compellingly to buyers seeking affordable character and upside appreciation.',
    },
    {
        slug: 'bennington',
        name: 'Bennington',
        county: 'Bennington',
        state: 'VT',
        zip: '05201',
        population: '15,700',
        median_price: '$189,000',
        price_trend: 'up 9%',
        avg_dom: 33,
        description: 'Bennington anchors southwestern Vermont with a rich Revolutionary War history, the landmark Bennington Battle Monument, and Bennington College\'s arts community, offering buyers substantial historic homes at prices well below comparable properties in neighboring New York and Massachusetts. Proximity to the Taconic and Green Mountains adds outdoor recreation appeal that continues to draw new residents.',
        neighborhoods: 'Old Bennington, Downtown Bennington, North Bennington, Walloomsac area',
        nearby: 'Manchester, Arlington, Shaftsbury, Williamstown MA',
        seller_hook: 'Bennington\'s location at the crossroads of Vermont, New York, and Massachusetts puts your home in front of a tri-state buyer pool hungry for affordable New England character.',
        realtor_hook: 'Bennington\'s tri-state location and Bennington College arts community attract a diverse buyer base that rewards agents comfortable working with both local move-ups and out-of-state relocators.',
    },

    // ── Ski & Resort Towns ────────────────────────────────────────────────
    {
        slug: 'stowe',
        name: 'Stowe',
        county: 'Lamoille',
        state: 'VT',
        zip: '05672',
        population: '4,300',
        median_price: '$789,000',
        price_trend: 'up 16%',
        avg_dom: 20,
        description: 'Stowe is Vermont\'s premier four-season resort destination, anchored by Mount Mansfield — the state\'s highest peak — and the legendary Stowe Mountain Resort, with a Mountain Road corridor lined with luxury lodges, fine dining, and high-end retail that draws buyers from Boston, New York, and international markets. At 16% annual appreciation, it leads the state in price growth and shows no signs of slowing.',
        neighborhoods: 'Stowe Village, Mountain Road corridor, Smugglers Notch area, Moscow',
        nearby: 'Morrisville, Hyde Park, Waterbury, Johnson',
        seller_hook: 'Stowe\'s 16% appreciation — the highest in Vermont — and its unmatched four-season resort profile mean sellers are commanding prices that would have seemed extraordinary just three years ago.',
        realtor_hook: 'Stowe\'s national and international buyer profile, combined with Vermont\'s fastest appreciation rate, makes it the state\'s most lucrative market for agents who can navigate high-end transactions and second-home buyers.',
    },
    {
        slug: 'manchester-vt',
        name: 'Manchester',
        county: 'Bennington',
        state: 'VT',
        zip: '05254',
        population: '4,500',
        median_price: '$479,000',
        price_trend: 'up 12%',
        avg_dom: 23,
        description: 'Manchester is southern Vermont\'s most refined resort town, offering designer outlet shopping, world-class fly fishing on the Battenkill, and proximity to Bromley and Stratton ski areas — all set against the dramatic backdrop of Mount Equinox. Its elegant Village Historic District and growing population of remote workers and retirees from the New York metro area continue to push prices upward.',
        neighborhoods: 'Manchester Center, Manchester Village, Equinox area, Battenkill Valley',
        nearby: 'Dorset, Arlington, Stratton Mountain, Bromley',
        seller_hook: 'Manchester\'s combination of resort prestige, outlet retail, and remote-work migration from New York and Connecticut is driving 12% annual appreciation — an exceptional moment to sell.',
        realtor_hook: 'Manchester\'s affluent buyer base from the New York metro and its four-season resort lifestyle give agents the opportunity to work high-value transactions with well-qualified, motivated clients.',
    },
    {
        slug: 'woodstock',
        name: 'Woodstock',
        county: 'Windsor',
        state: 'VT',
        zip: '05091',
        population: '3,200',
        median_price: '$519,000',
        price_trend: 'up 10%',
        avg_dom: 29,
        description: 'Woodstock is frequently cited as one of America\'s most beautiful small towns, with a meticulously preserved Green, covered bridges, and the Rockefeller-endowed Marsh-Billings-Rockefeller National Historical Park creating an aesthetic standard that sustains premium property values throughout the Upper Valley. Its mix of historic estates, classic Colonials, and refined village condos appeals to buyers seeking quintessential Vermont with upper-crust character.',
        neighborhoods: 'Woodstock Green, South Woodstock, Taftsville, Woodstock Village Historic District',
        nearby: 'Quechee, Bridgewater, Barnard, Hanover NH',
        seller_hook: 'Woodstock\'s "most beautiful village in America" reputation brings motivated out-of-state buyers who are willing to pay a premium — well-presented homes here rarely stay on market long.',
        realtor_hook: 'Woodstock\'s national prestige attracts buyers with significant purchasing power who prioritize quality and character, rewarding agents who can present properties with sophistication and local insight.',
    },
    {
        slug: 'middlebury',
        name: 'Middlebury',
        county: 'Addison',
        state: 'VT',
        zip: '05753',
        population: '8,500',
        median_price: '$289,000',
        price_trend: 'up 8%',
        avg_dom: 24,
        description: 'Middlebury is the cultural and commercial heart of Vermont\'s Champlain Valley, centered on one of New England\'s finest liberal arts colleges and a vibrant downtown with independent shops, galleries, and restaurants that give the town an outsized cultural footprint. The college\'s faculty housing demand and growing remote-work appeal create a steady, balanced market with consistent appreciation.',
        neighborhoods: 'Middlebury College area, Downtown Middlebury, Weybridge Street, Chipman Hill',
        nearby: 'Vergennes, Bristol, Weybridge, Ripton',
        seller_hook: 'Middlebury College faculty housing demand and the town\'s reputation as Addison County\'s premier address give sellers a built-in audience of educated, motivated buyers.',
        realtor_hook: 'Middlebury\'s college-town stability and growing appeal to Burlington-area buyers seeking more space make it a reliable, low-volatility market ideal for agents building a long-term practice.',
    },
    {
        slug: 'morrisville',
        name: 'Morrisville',
        county: 'Lamoille',
        state: 'VT',
        zip: '05661',
        population: '5,200',
        median_price: '$289,000',
        price_trend: 'up 9%',
        avg_dom: 25,
        description: 'Morrisville serves as the year-round service hub for the Stowe ski corridor, offering significantly more affordable prices than its famous neighbor while providing easy access to Stowe Mountain Resort and the growing recreational amenities of the Lamoille Valley Rail Trail. Its mix of working families, ski industry employees, and value-conscious second-home buyers creates a dynamic and diversifying market.',
        neighborhoods: 'Morrisville Village, Craftsbury Road area, Cadys Falls, Hyde Park',
        nearby: 'Stowe, Hyde Park, Johnson, Cambridge',
        seller_hook: 'As Stowe prices push buyers into neighboring communities, Morrisville sellers are benefiting from overflow demand — your home will be seen by buyers who missed out in Stowe.',
        realtor_hook: 'Morrisville\'s position as Stowe\'s affordable alternative gives agents a compelling value story for ski-lifestyle buyers who want proximity without resort-town price tags.',
    },

    // ── Northern Vermont ──────────────────────────────────────────────────
    {
        slug: 'st-albans',
        name: 'St. Albans',
        county: 'Franklin',
        state: 'VT',
        zip: '05478',
        population: '7,600',
        median_price: '$279,000',
        price_trend: 'up 10%',
        avg_dom: 24,
        description: 'St. Albans anchors Franklin County with a revitalized Victorian downtown, a scenic Taylor Park, and increasing appeal to Burlington commuters who can access the city via I-89 in under 30 minutes while enjoying significantly lower home prices. The nearby Lake Champlain waterfront access and a growing downtown restaurant scene are adding new dimensions to a market that has historically been defined by affordability.',
        neighborhoods: 'St. Albans City, St. Albans Town, Taylor Park, Lake Champlain waterfront',
        nearby: 'Swanton, Fairfax, Georgia, Burlington',
        seller_hook: 'Burlington commuters are discovering St. Albans in greater numbers each year — sellers offering well-maintained homes near the city center are meeting buyers eager to escape Burlington prices.',
        realtor_hook: 'St. Albans\' Burlington commuter appeal and Victorian housing stock give agents a strong value narrative for buyers priced out of Chittenden County.',
    },
    {
        slug: 'white-river-junction',
        name: 'White River Junction',
        county: 'Windsor',
        state: 'VT',
        zip: '05001',
        population: '2,500',
        median_price: '$259,000',
        price_trend: 'up 9%',
        avg_dom: 26,
        description: 'White River Junction is the unlikely arts capital of the Upper Valley, home to the Center for Cartoon Studies, a thriving gallery district, and a beautifully restored downtown that belies its small size — all at prices that remain well below comparable Upper Valley communities across the river in New Hampshire. Its I-91/I-89 interchange location makes it one of Vermont\'s best-connected communities for remote workers and commuters.',
        neighborhoods: 'White River Junction Village, Upper Valley area, Wilder, Hanover NH nearby',
        nearby: 'Hartford, Wilder, Quechee, Hanover NH, Lebanon NH',
        seller_hook: 'White River Junction\'s arts-district cachet and strategic interstate location attract Upper Valley buyers from both Vermont and New Hampshire — a wider buyer pool that benefits sellers.',
        realtor_hook: 'The Upper Valley\'s bi-state buyer pool and White River Junction\'s growing arts community create cross-market opportunities that reward agents comfortable working the Vermont-New Hampshire border.',
    },
];
