// cities/wa.js — Washington city data for SEO landing pages

module.exports = [
    {
        slug: 'seattle',
        name: 'Seattle',
        county: 'King',
        state: 'WA',
        zip: '98101',
        population: '749,000',
        median_price: '$950,000',
        price_trend: 'up 5%',
        avg_dom: 18,
        description: 'Seattle is the Pacific Northwest\'s dominant tech metropolis — home to Amazon, Microsoft, Boeing, and a constellation of high-growth startups where neighborhoods from Capitol Hill and Fremont to Queen Anne and Ballard deliver walkable urban living backed by the highest median household incomes of any major American city.',
        neighborhoods: 'Capitol Hill, Fremont, Queen Anne, Ballard, Beacon Hill, Rainier Valley, Madison Park, Magnolia',
        nearby: 'Bellevue, Redmond, Kirkland, Shoreline, Renton',
        seller_hook: 'Seattle\'s tech economy and land-constrained geography keep buyer demand ferocious year-round — let top Seattle agents compete on RealtorFinder to achieve your maximum sale.',
        realtor_hook: 'Seattle\'s Amazon and tech employee buyer pool delivers the Pacific Northwest\'s highest residential commissions — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'bellevue',
        name: 'Bellevue',
        county: 'King',
        state: 'WA',
        zip: '98004',
        population: '153,000',
        median_price: '$1,500,000',
        price_trend: 'up 6%',
        avg_dom: 20,
        description: 'Bellevue is the Eastside\'s premier city and one of America\'s wealthiest tech suburbs — a gleaming skyline of Amazon and Microsoft satellite campuses, luxury high-rises, and elite shopping at Bellevue Square where top-ranked schools and a large international tech workforce sustain one of the nation\'s most competitive housing markets.',
        neighborhoods: 'Downtown Bellevue, Meydenbauer, Medina border, Bridle Trails, Somerset, Newport Hills, Crossroads',
        nearby: 'Mercer Island, Kirkland, Redmond, Issaquah, Sammamish',
        seller_hook: 'Bellevue\'s tech workforce and luxury market demand mean your home attracts the most competitive buyers in the region — let top Eastside agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Bellevue\'s Amazon and Microsoft employee buyer pool delivers Washington\'s highest residential commissions — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'redmond-wa',
        name: 'Redmond',
        county: 'King',
        state: 'WA',
        zip: '98052',
        population: '73,000',
        median_price: '$1,200,000',
        price_trend: 'up 6%',
        avg_dom: 18,
        description: 'Redmond is Microsoft\'s hometown and a global technology hub where the sprawling Microsoft campus anchors a tech ecosystem of thousands of engineers and program managers — creating persistent buyer demand in neighborhoods like Education Hill, Sammamish Valley, and Overlake that rarely sits unsatisfied for long.',
        neighborhoods: 'Education Hill, Overlake, Idylwood, Sammamish Valley, Bear Creek, Grass Lawn',
        nearby: 'Kirkland, Bellevue, Sammamish, Bothell, Woodinville',
        seller_hook: 'Redmond\'s Microsoft campus creates one of the nation\'s most reliable high-income buyer pools — let competing Eastside realtors on RealtorFinder earn the right to sell your home.',
        realtor_hook: 'Redmond\'s Microsoft workforce and limited inventory keep this one of Washington\'s tightest markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'kirkland-wa',
        name: 'Kirkland',
        county: 'King',
        state: 'WA',
        zip: '98033',
        population: '92,000',
        median_price: '$1,200,000',
        price_trend: 'up 6%',
        avg_dom: 19,
        description: 'Kirkland is the Eastside\'s most coveted waterfront community — a charming city on the eastern shore of Lake Washington where Google\'s Kirkland campus, a vibrant Marina district, top schools, and the Burke-Gilman Trail combine to attract tech professionals and families seeking Puget Sound lifestyle at prices slightly south of Bellevue.',
        neighborhoods: 'Downtown Kirkland, Juanita, Totem Lake, Finn Hill, Rose Hill, Bridle Trails border, Houghton',
        nearby: 'Redmond, Bellevue, Bothell, Woodinville, Sammamish',
        seller_hook: 'Kirkland\'s waterfront character and Google campus drive fierce Eastside buyer competition — let top agents on RealtorFinder compete to achieve your maximum sale price.',
        realtor_hook: 'Kirkland\'s Lake Washington waterfront and tech employer proximity create a premium listing market with highly motivated buyers — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'mercer-island',
        name: 'Mercer Island',
        county: 'King',
        state: 'WA',
        zip: '98040',
        population: '25,000',
        median_price: '$2,200,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Mercer Island is Washington\'s most exclusive residential enclave — a forested island in Lake Washington connected by I-90 to both Seattle and Bellevue where extraordinary waterfront estates, top-ranked schools, and rare inventory make every listing a significant event for the region\'s wealthiest tech executives and professional athletes.',
        neighborhoods: 'North End, South End, West Mercer, East Mercer, Town Center area, Clarke Beach',
        nearby: 'Bellevue, Seattle, Issaquah, Kirkland, Newcastle',
        seller_hook: 'Mercer Island\'s trophy market status means serious high-net-worth buyers compete for every listing — let Washington\'s top luxury agents on RealtorFinder fight to represent your home.',
        realtor_hook: 'Mercer Island\'s ultra-luxury market delivers Washington\'s most exceptional residential commissions — RealtorFinder connects you with motivated sellers on this exclusive island.',
    },
    {
        slug: 'sammamish',
        name: 'Sammamish',
        county: 'King',
        state: 'WA',
        zip: '98074',
        population: '69,000',
        median_price: '$1,100,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Sammamish is the Eastside\'s premier family suburb — a planned plateau community with top-ranked Issaquah and Lake Washington school districts, scenic Beaver Lake and Lake Sammamish parks, and a highly educated Microsoft and Amazon tech workforce that has driven sustained appreciation and strong buyer demand.',
        neighborhoods: 'Plateau area, Beaver Lake, Pine Lake, Trossachs, Inglewood Hill, Sahalee',
        nearby: 'Issaquah, Redmond, Bellevue, Kirkland, North Bend',
        seller_hook: 'Sammamish\'s top schools and tech professional buyer pool mean your listing will attract qualified, motivated buyers — let top Eastside agents on RealtorFinder compete for it.',
        realtor_hook: 'Sammamish\'s affluent tech workforce and family-focused market create consistent premium listing demand — RealtorFinder connects you with motivated sellers on the plateau.',
    },
    {
        slug: 'issaquah',
        name: 'Issaquah',
        county: 'King',
        state: 'WA',
        zip: '98027',
        population: '38,000',
        median_price: '$980,000',
        price_trend: 'up 6%',
        avg_dom: 23,
        description: 'Issaquah is a scenic foothills city at the foot of the Cascades — a rapidly growing Eastside community with Costco headquarters, top-ranked Issaquah School District, outstanding hiking access to Tiger Mountain and Squak Mountain, and a thriving Gilman Village district that makes it one of the most livable communities in greater Seattle.',
        neighborhoods: 'Gilman Village, Issaquah Highlands, Central Issaquah, Talus, Cougar Mountain, Grand Ridge',
        nearby: 'Sammamish, Bellevue, North Bend, Snoqualmie, Renton',
        seller_hook: 'Issaquah\'s Costco-anchored employment base and top schools drive consistent Eastside buyer demand — let competing agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Issaquah\'s tech employee overflow and outdoor lifestyle appeal create a strong premium listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'renton',
        name: 'Renton',
        county: 'King',
        state: 'WA',
        zip: '98055',
        population: '106,000',
        median_price: '$700,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Renton is the most affordable major city on Lake Washington\'s southern shore — the birthplace of Boeing aircraft manufacturing and home to a growing tech presence as Amazon and other employers expand into its rapidly developing downtown, with access to both Seattle and Bellevue via I-405 that keeps buyer demand consistently strong.',
        neighborhoods: 'The Highlands, Kennydale, Cascade, South Renton, Landing district, Talbot Hill',
        nearby: 'Kent, Auburn, Bellevue, Tukwila, Newcastle',
        seller_hook: 'Renton\'s affordability and central location between Seattle and Bellevue attract buyers priced out of both cities — let competing agents on RealtorFinder drive your sale.',
        realtor_hook: 'Renton\'s Boeing and tech employee buyer base and rapidly appreciating market create consistent listing opportunities — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'kent-wa',
        name: 'Kent',
        county: 'King',
        state: 'WA',
        zip: '98030',
        population: '133,000',
        median_price: '$600,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Kent is one of King County\'s largest cities and a major logistics and manufacturing hub in the Green River Valley — a diverse, affordable community with strong industrial employment, excellent commuter access to Seattle and Tacoma via I-5 and SR-167, and a housing market that delivers ownership opportunity at prices well below the Seattle metro median.',
        neighborhoods: 'Downtown Kent, East Hill, Meridian, West Hill, Panther Lake, Covington border',
        nearby: 'Renton, Auburn, Federal Way, Tukwila, Covington',
        seller_hook: 'Kent\'s affordability and logistics employment base attract a large, motivated buyer pool — let competing South King County agents on RealtorFinder earn your listing.',
        realtor_hook: 'Kent\'s large workforce population and affordable price point generate high listing volume and motivated buyer traffic — RealtorFinder connects you with sellers.',
    },
    {
        slug: 'auburn-wa',
        name: 'Auburn',
        county: 'King',
        state: 'WA',
        zip: '98001',
        population: '85,000',
        median_price: '$560,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Auburn straddles King and Pierce counties in the Green River Valley — a growing city with Emerald Downs horse racing, Green River Community College, and strong manufacturing and distribution employment that delivers affordable family housing with convenient I-5 access to both Seattle and Tacoma for buyers who want space without the metro price.',
        neighborhoods: 'Downtown Auburn, Lakeland Hills, West Auburn, Lea Hill, Terminal Park, East Auburn',
        nearby: 'Kent, Federal Way, Puyallup, Sumner, Pacific',
        seller_hook: 'Auburn\'s affordability and cross-county location attract a wide buyer pool from both metro areas — let competing agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Auburn\'s affordable price point and large buyer pool create consistent listing opportunities on the King-Pierce border — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'federal-way',
        name: 'Federal Way',
        county: 'King',
        state: 'WA',
        zip: '98003',
        population: '97,000',
        median_price: '$540,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Federal Way is South King County\'s largest city — a diverse community midway between Seattle and Tacoma on I-5 where Dash Point State Park and the developing City Center district offer buyers an affordable Pacific Northwest lifestyle with excellent commute access to two major employment centers.',
        neighborhoods: 'City Center, Twin Lakes, Dash Point, Steel Lake, West Campus, Redondo Beach',
        nearby: 'Auburn, Kent, Tacoma, Milton, Edgewood',
        seller_hook: 'Federal Way\'s location between two major cities and affordable pricing attract buyers from a wide geographic area — let competing agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Federal Way\'s large and diverse buyer pool creates reliable listing volume in South King County — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'tacoma',
        name: 'Tacoma',
        county: 'Pierce',
        state: 'WA',
        zip: '98401',
        population: '219,000',
        median_price: '$520,000',
        price_trend: 'up 7%',
        avg_dom: 23,
        description: 'Tacoma is the Puget Sound\'s most undervalued major city — a rapidly gentrifying port city with world-class museums along the Museum Mile, a thriving arts scene in the Stadium District, and direct Sounder train access to Seattle that has made it the top choice for buyers priced out of King County seeking Pacific Northwest character at accessible prices.',
        neighborhoods: 'Stadium District, North End, Proctor District, Hilltop, Eastside, South End, Old Town',
        nearby: 'Gig Harbor, Puyallup, Federal Way, Lakewood, Steilacoom',
        seller_hook: 'Tacoma\'s rapid gentrification and Seattle commuter demand mean your listing will attract buyers from across the region — let top Pierce County agents on RealtorFinder compete.',
        realtor_hook: 'Tacoma\'s fast appreciation and Seattle-overflow buyer demand create one of Pierce County\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'gig-harbor',
        name: 'Gig Harbor',
        county: 'Pierce',
        state: 'WA',
        zip: '98332',
        population: '13,000',
        median_price: '$750,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Gig Harbor is the Puget Sound\'s premier waterfront community — a picturesque harbor city connected to Tacoma by the Tacoma Narrows Bridge where boating culture, charming waterfront dining, and exceptional Puget Sound views combine with strong Tacoma and remote-worker buyer demand to sustain a premium market well above the Pierce County average.',
        neighborhoods: 'Downtown Gig Harbor, Uptown, Artondale, Rosedale, Kopachuck, Henderson Bay',
        nearby: 'Tacoma, Port Orchard, Bremerton, Purdy, Key Peninsula',
        seller_hook: 'Gig Harbor\'s waterfront lifestyle and scarcity of premium inventory attract motivated buyers from Seattle to Portland — let top agents on RealtorFinder compete for your listing.',
        realtor_hook: 'Gig Harbor\'s luxury waterfront market and remote-worker appeal deliver Pierce County\'s most rewarding residential commissions — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'puyallup',
        name: 'Puyallup',
        county: 'Pierce',
        state: 'WA',
        zip: '98371',
        population: '44,000',
        median_price: '$560,000',
        price_trend: 'up 7%',
        avg_dom: 24,
        description: 'Puyallup is Pierce County\'s most beloved family community — a city famous for the Washington State Fair, beautiful daffodil valley scenery, and a thriving downtown that has grown into one of the South Sound\'s most desirable addresses for families seeking top-rated schools, charming neighborhoods, and Cascade Mountain views.',
        neighborhoods: 'Downtown Puyallup, South Hill, Meeker, Bradley Lake, Shaw Road corridor, Firgrove',
        nearby: 'Tacoma, Auburn, Sumner, Orting, Buckley',
        seller_hook: 'Puyallup\'s family-friendly character and strong school reputation drive consistent buyer demand — let competing Pierce County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Puyallup\'s top schools and community character attract motivated family buyers — RealtorFinder connects you with sellers in this sought-after South Sound market.',
    },
    {
        slug: 'olympia-wa',
        name: 'Olympia',
        county: 'Thurston',
        state: 'WA',
        zip: '98501',
        population: '55,000',
        median_price: '$490,000',
        price_trend: 'up 6%',
        avg_dom: 27,
        description: 'Olympia is Washington\'s state capital and the South Puget Sound\'s cultural anchor — a vibrant progressive city with a thriving farmers market, the Evergreen State College, and a state government employment base that provides economic stability and consistent buyer demand from public-sector professionals and Olympia\'s large arts community.',
        neighborhoods: 'Capitol Campus area, Westside, Eastside, South Capitol, Downtown Olympia, Isthmus',
        nearby: 'Lacey, Tumwater, Yelm, Tenino, Rainier',
        seller_hook: 'Olympia\'s stable government employment base and progressive community attract motivated buyers — let competing Thurston County agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Olympia\'s government and college employment base creates a stable, reliable listing market — RealtorFinder connects you with motivated sellers in the state capital.',
    },
    {
        slug: 'lacey-wa',
        name: 'Lacey',
        county: 'Thurston',
        state: 'WA',
        zip: '98503',
        population: '65,000',
        median_price: '$480,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Lacey is Thurston County\'s fastest-growing city — a sprawling suburb east of Olympia anchored by Joint Base Lewis-McChord overflow demand, Saint Martin\'s University, and major retail corridors that make it the South Sound\'s most active new-construction market with strong military and government buyer demand driving consistent appreciation.',
        neighborhoods: 'Hawks Prairie, Lacey Downtown, Woodland Creek, Meridian Campus area, Pacific Avenue corridor',
        nearby: 'Olympia, Tumwater, Yelm, Rainier, Joint Base Lewis-McChord',
        seller_hook: 'Lacey\'s JBLM and government buyer pool create year-round demand — let competing Thurston County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Lacey\'s military and government buyer base provides consistent listing volume — RealtorFinder connects you with motivated sellers in this growing South Sound market.',
    },
    {
        slug: 'everett-wa',
        name: 'Everett',
        county: 'Snohomish',
        state: 'WA',
        zip: '98201',
        population: '116,000',
        median_price: '$580,000',
        price_trend: 'up 7%',
        avg_dom: 23,
        description: 'Everett is Snohomish County\'s largest city and a major industrial hub where Boeing\'s largest manufacturing facility, Naval Station Everett, and a growing tech presence anchor the employment base — delivering a waterfront downtown revival, Sounder train service to Seattle, and housing prices that attract buyers priced out of King County.',
        neighborhoods: 'Downtown Everett, Bayside, Eastmont, Silver Lake, Holly, Pinehurst, North Broadway',
        nearby: 'Marysville, Mukilteo, Lynnwood, Shoreline, Bothell',
        seller_hook: 'Everett\'s Boeing workforce and Seattle commuter appeal drive strong buyer demand — let competing Snohomish County agents on RealtorFinder compete for your listing.',
        realtor_hook: 'Everett\'s large employment base and King County overflow demand create one of Snohomish County\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'shoreline-wa',
        name: 'Shoreline',
        county: 'King',
        state: 'WA',
        zip: '98133',
        population: '55,000',
        median_price: '$750,000',
        price_trend: 'up 6%',
        avg_dom: 20,
        description: 'Shoreline is Seattle\'s immediate northern neighbor and one of its most rapidly transforming suburbs — a dense, transit-oriented city undergoing a light rail-driven building boom where Shoreline Community College, excellent North King County schools, and two new Link Light Rail stations are attracting buyers seeking Seattle access at a slight discount.',
        neighborhoods: 'Aurora Corridor, Richmond Beach, Ridgecrest, Hillwood, Parkwood, Echo Lake',
        nearby: 'Seattle, Lynnwood, Kenmore, Lake Forest Park, Bothell',
        seller_hook: 'Shoreline\'s new light rail stations and Seattle proximity are driving rapid appreciation — let top King County agents on RealtorFinder compete to maximize your sale.',
        realtor_hook: 'Shoreline\'s light rail transformation and Seattle overflow demand create an exceptional listing opportunity — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'bothell',
        name: 'Bothell',
        county: 'King',
        state: 'WA',
        zip: '98011',
        population: '52,000',
        median_price: '$850,000',
        price_trend: 'up 6%',
        avg_dom: 21,
        description: 'Bothell straddles King and Snohomish counties and has emerged as one of the Eastside\'s most desirable family communities — a city with top-ranked Northshore School District, a revitalized downtown main street, and proximity to Amazon, Microsoft, and Canyon Park tech employment that sustains exceptional buyer demand from tech professionals.',
        neighborhoods: 'Downtown Bothell, Kenmore border, Canyon Park, North Creek, Woodinville border, Maltby area',
        nearby: 'Kirkland, Kenmore, Woodinville, Redmond, Everett',
        seller_hook: 'Bothell\'s top Northshore schools and tech corridor proximity attract one of Washington\'s most competitive buyer pools — let top agents on RealtorFinder fight for your listing.',
        realtor_hook: 'Bothell\'s Northshore School District reputation and tech employee buyer base create consistent premium listing demand — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'lynnwood',
        name: 'Lynnwood',
        county: 'Snohomish',
        state: 'WA',
        zip: '98036',
        population: '45,000',
        median_price: '$680,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Lynnwood is Snohomish County\'s most transit-connected city — a rapidly transforming community receiving major investment around its Lynnwood City Center Link Light Rail station where Alderwood Mall, Edmonds College, and a growing urban core are attracting buyers seeking Seattle access and a dynamic evolving neighborhood at prices below the King County median.',
        neighborhoods: 'Lynnwood City Center, Alderwood, Meadowdale, Scriber Lake, Mountlake Terrace border',
        nearby: 'Edmonds, Mountlake Terrace, Shoreline, Everett, Bothell',
        seller_hook: 'Lynnwood\'s light rail investment and Seattle access are driving rapid buyer demand — let competing agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Lynnwood\'s light rail transformation and Snohomish affordability create a fast-appreciating listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'edmonds-wa',
        name: 'Edmonds',
        county: 'Snohomish',
        state: 'WA',
        zip: '98020',
        population: '42,000',
        median_price: '$790,000',
        price_trend: 'up 6%',
        avg_dom: 23,
        description: 'Edmonds is one of Puget Sound\'s most charming waterfront cities — a quaint community with a beloved ferry terminal, thriving arts scene, walkable downtown with boutiques and seafood restaurants, and stunning views of the Olympic Mountains that make it one of Snohomish County\'s most desirable addresses for buyers seeking coastal Pacific Northwest living.',
        neighborhoods: 'Downtown Edmonds, Seaview, Westgate, Perrinville, Woodway border, Five Corners',
        nearby: 'Lynnwood, Mountlake Terrace, Shoreline, Mukilteo, Kenmore',
        seller_hook: 'Edmonds\' waterfront character and artistic community command a strong premium — let top Snohomish County agents on RealtorFinder compete to achieve your maximum sale.',
        realtor_hook: 'Edmonds\' waterfront lifestyle and loyal buyer community create a premium listing market — RealtorFinder connects you with motivated sellers in this coastal gem.',
    },
    {
        slug: 'mukilteo',
        name: 'Mukilteo',
        county: 'Snohomish',
        state: 'WA',
        zip: '98275',
        population: '22,000',
        median_price: '$730,000',
        price_trend: 'up 6%',
        avg_dom: 24,
        description: 'Mukilteo is a scenic ferry and lighthouse community on Possession Sound — home to a major Boeing Everett factory workforce and Whidbey Island ferry access where premium water views, excellent Mukilteo School District ratings, and a tight-knit community character attract tech and Boeing professionals seeking a peaceful Puget Sound lifestyle.',
        neighborhoods: 'Old Town Mukilteo, Harbour Pointe, Picnic Point, Boeing campus area, Mukilteo Speedway corridor',
        nearby: 'Everett, Lynnwood, Edmonds, Marysville, Bothell',
        seller_hook: 'Mukilteo\'s Boeing workforce and waterfront views attract motivated buyers — let competing Snohomish County agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Mukilteo\'s Boeing employee buyer base and water-view premium create strong listing demand — RealtorFinder connects you with motivated sellers in this Puget Sound community.',
    },
    {
        slug: 'spokane',
        name: 'Spokane',
        county: 'Spokane',
        state: 'WA',
        zip: '99201',
        population: '229,000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 26,
        description: 'Spokane is Eastern Washington\'s dominant city and the Inland Northwest\'s commercial and cultural hub — a vibrant riverfront city with Gonzaga University, Washington State University extension campuses, a strong healthcare sector anchored by Providence and MultiCare hospitals, and housing prices that make it one of the Pacific Northwest\'s best-value markets.',
        neighborhoods: 'South Hill, Browne\'s Addition, Manito, Indian Trail, Shadle, East Central, Perry District',
        nearby: 'Spokane Valley, Liberty Lake, Cheney, Medical Lake, Coeur d\'Alene ID',
        seller_hook: 'Spokane\'s rapid appreciation and growing in-migration from western Washington and California drive strong buyer demand — let competing agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Spokane\'s fast-appreciating market and west coast in-migration create one of Eastern Washington\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'liberty-lake',
        name: 'Liberty Lake',
        county: 'Spokane',
        state: 'WA',
        zip: '99019',
        population: '11,000',
        median_price: '$520,000',
        price_trend: 'up 7%',
        avg_dom: 25,
        description: 'Liberty Lake is the Spokane metro\'s most affluent suburb — a master-planned lakeside community on the Idaho border with technology employers, a beautiful namesake lake and park system, and the highest home values in the greater Spokane area attracting remote workers and executives relocating from pricier western Washington cities.',
        neighborhoods: 'Liberty Lake Community Center area, Meadowwood, Pavillion Park, Sundance, Greenacres border',
        nearby: 'Spokane Valley, Spokane, Coeur d\'Alene ID, Post Falls ID, Cheney',
        seller_hook: 'Liberty Lake\'s lakeside lifestyle and Spokane metro premium attract buyers from across the Inland Northwest — let competing agents on RealtorFinder compete to sell your home.',
        realtor_hook: 'Liberty Lake\'s lakeside prestige and Spokane metro premium create the region\'s highest-value listing market — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'kennewick',
        name: 'Kennewick',
        county: 'Benton',
        state: 'WA',
        zip: '99336',
        population: '84,000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 28,
        description: 'Kennewick is the largest of the Tri-Cities — a sun-drenched Columbia River city anchored by Hanford nuclear site employment, Pacific Northwest National Laboratory, and a thriving wine industry where affordable housing, strong job growth, and over 300 days of sunshine annually attract buyers seeking value and outdoor lifestyle on the Columbia River.',
        neighborhoods: 'Southridge, Canyon Lakes, Vista Field area, Kennewick Downtown, West Kennewick, Clearwater',
        nearby: 'Richland, Pasco, West Richland, Prosser, Burbank',
        seller_hook: 'Kennewick\'s Hanford and PNNL employment base create consistent buyer demand — let competing Tri-Cities agents on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Kennewick\'s government and energy employment base delivers reliable listing volume and consistent buyer traffic — RealtorFinder connects you with motivated sellers.',
    },
];
