// cities/wa.js — Washington state city data for SEO landing pages

module.exports = [
    {
        slug: 'seattle',
        name: 'Seattle',
        county: 'King',
        state: 'WA',
        zip: '98101',
        population: '749,000',
        median_price: '$849,000',
        price_trend: 'up 6%',
        avg_dom: 19,
        description: 'Seattle is the Pacific Northwest\'s economic engine and one of America\'s great tech cities — home to Amazon and a major Microsoft presence, with neighborhoods from Capitol Hill\'s vibrant density to Ballard\'s Nordic heritage and Beacon Hill\'s emerging food scene creating a real estate market that ranks among the most competitive on the West Coast.',
        neighborhoods: 'Capitol Hill, Ballard, Queen Anne, Fremont, Beacon Hill, West Seattle, Wallingford, Columbia City',
        nearby: 'Bellevue, Redmond, Kirkland, Renton, Shoreline',
        seller_hook: 'Seattle\'s tech-industry buyer pool and low days on market mean the right agent makes a real difference — let competing King County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Seattle\'s Amazon and tech economy create the highest-earning buyer pool in the Pacific Northwest — RealtorFinder connects you with motivated sellers in this premium market.',
    },
    {
        slug: 'spokane',
        name: 'Spokane',
        county: 'Spokane',
        state: 'WA',
        zip: '99201',
        population: '228,000',
        median_price: '$319,000',
        price_trend: 'up 8%',
        avg_dom: 24,
        description: 'Spokane is eastern Washington\'s largest city and one of the Pacific Northwest\'s most compelling value markets — a healthcare and education hub anchored by Providence Health and Washington State University\'s medical school that offers buyers a genuine city experience at prices 60% below Seattle, driving strong migration from the west side of the Cascades.',
        neighborhoods: 'South Hill, Browne\'s Addition, Kendall Yards, Logan, Garland District, North Spokane',
        nearby: 'Spokane Valley, Cheney, Post Falls ID, Coeur d\'Alene ID, Liberty Lake',
        seller_hook: 'Spokane\'s west-side migration and rising prices create strong buyer competition — RealtorFinder puts competitive Spokane County agents in a bidding war to represent your home.',
        realtor_hook: 'Spokane\'s Seattle price discount and growing medical sector draw buyers from across the Pacific Northwest — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'tacoma',
        name: 'Tacoma',
        county: 'Pierce',
        state: 'WA',
        zip: '98401',
        population: '222,000',
        median_price: '$459,000',
        price_trend: 'up 8%',
        avg_dom: 21,
        description: 'Tacoma is Puget Sound\'s most rapidly appreciating real estate market — a diverse, arts-forward city with stunning Mount Rainier views, a revitalized downtown anchored by the Museum of Glass and Tacoma Art Museum, and home prices that offer meaningful value compared to Seattle while sharing the Sound\'s lifestyle and easy Sounder train access.',
        neighborhoods: 'Proctor District, North End, Stadium District, South Tacoma, West End, Hilltop, Ruston border',
        nearby: 'Lakewood, University Place, Puyallup, Federal Way, Bonney Lake',
        seller_hook: 'Tacoma\'s arts scene and Seattle discount drive fast-moving buyer demand — let competing Pierce County realtors on RealtorFinder fight to earn your listing.',
        realtor_hook: 'Tacoma\'s consistent appreciation and Seattle price differential attract buyers from across the Sound — RealtorFinder connects you with motivated sellers in Pierce County.',
    },
    {
        slug: 'vancouver-wa',
        name: 'Vancouver',
        county: 'Clark',
        state: 'WA',
        zip: '98660',
        population: '195,000',
        median_price: '$469,000',
        price_trend: 'up 7%',
        avg_dom: 23,
        description: 'Vancouver, Washington is the most strategically positioned city in the Pacific Northwest for tax-conscious buyers — a rapidly growing city directly across the Columbia River from Portland, Oregon that offers access to Portland\'s employment and culture without Oregon\'s state income tax, driving a persistent and powerful buyer demand.',
        neighborhoods: 'Uptown Village, Esther Short Park area, Fisher\'s Landing, Downtown Vancouver, Hazel Dell',
        nearby: 'Camas, Washougal, Ridgefield, Battle Ground, Portland OR',
        seller_hook: 'Vancouver\'s no-income-tax advantage over Oregon keeps buyer demand consistently strong — let competitive Clark County agents on RealtorFinder earn the right to represent your home.',
        realtor_hook: 'Vancouver\'s no-state-income-tax advantage draws buyers from Portland in force — RealtorFinder connects you with motivated sellers in this strategically positioned market.',
    },
    {
        slug: 'bellevue',
        name: 'Bellevue',
        county: 'King',
        state: 'WA',
        zip: '98004',
        population: '151,000',
        median_price: '$1249000',
        price_trend: 'up 6%',
        avg_dom: 17,
        description: 'Bellevue is the premier suburb of the Seattle metro — a wealthy, corporate city that has transformed from a bedroom community to a thriving business hub where Microsoft, Amazon, and dozens of tech companies maintain East Side campuses, creating a buyer pool of highly compensated tech professionals who purchase at the top of the market.',
        neighborhoods: 'Downtown Bellevue, Crossroads, Factoria, West Bellevue, Bridle Trails, Somerset, Eastgate',
        nearby: 'Redmond, Kirkland, Mercer Island, Issaquah, Newcastle',
        seller_hook: 'Bellevue\'s tech wealth and 17-day average market time mean your listing needs the best possible representation — RealtorFinder puts elite East Side agents in competition to earn it.',
        realtor_hook: 'Bellevue\'s $1.25M median and tech-industry buyer pool create some of the highest-value listing opportunities in the Pacific Northwest — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'kent-wa',
        name: 'Kent',
        county: 'King',
        state: 'WA',
        zip: '98031',
        population: '136,000',
        median_price: '$559,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Kent is King County\'s most affordable major city — a manufacturing and logistics hub with significant Boeing and Amazon fulfillment presence, diverse neighborhoods, and home prices that offer first-time buyers and families genuine value within the Seattle metro\'s commuter shed, accessible by both Sounder commuter rail and Metrolink.',
        neighborhoods: 'Downtown Kent, East Hill, West Hill, North Kent, Kentridge, Lake Meridian area',
        nearby: 'Renton, Auburn, Federal Way, Covington, Tukwila',
        seller_hook: 'Kent\'s affordability and Sounder access draw buyers from across the South Sound — RealtorFinder puts competitive South King County realtors in a race to represent your home.',
        realtor_hook: 'Kent\'s affordability and strong logistics employment create consistent buyer demand — RealtorFinder connects you with motivated sellers in South King County.',
    },
    {
        slug: 'everett',
        name: 'Everett',
        county: 'Snohomish',
        state: 'WA',
        zip: '98201',
        population: '115,000',
        median_price: '$519,000',
        price_trend: 'up 7%',
        avg_dom: 22,
        description: 'Everett is Snohomish County\'s largest city and the Boeing Company\'s largest factory town — a growing Puget Sound city with Sounder commuter rail to Seattle, a revitalizing waterfront, and home prices that have made it the top destination for Seattle buyers seeking meaningful value north of the city without leaving King County\'s gravitational pull.',
        neighborhoods: 'Downtown Everett, Bayside, Pinehurst, Harbour Pointe area, South Everett',
        nearby: 'Mukilteo, Lynnwood, Marysville, Bothell, Lake Stevens',
        seller_hook: 'Everett\'s Boeing presence and Seattle commuter appeal drive consistent buyer demand — let competing Snohomish County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Everett\'s Boeing workforce and Seattle price differential create strong buyer demand — RealtorFinder connects you with motivated sellers in Snohomish County.',
    },
    {
        slug: 'renton',
        name: 'Renton',
        county: 'King',
        state: 'WA',
        zip: '98055',
        population: '107,000',
        median_price: '$619,000',
        price_trend: 'up 7%',
        avg_dom: 20,
        description: 'Renton is the geographic center of the Seattle metro — a Boeing assembly campus city with Lake Washington waterfront, a revitalized downtown, and access to both Seattle and Bellevue that makes it one of King County\'s most strategically located and rapidly appreciating cities for buyers seeking value between two of the Pacific Northwest\'s most expensive markets.',
        neighborhoods: 'Downtown Renton, Kennydale, Highlands, South Renton, Landing area, Liberty Ridge',
        nearby: 'Kent, Bellevue, Tukwila, Newcastle, Maple Valley',
        seller_hook: 'Renton\'s position between Seattle and Bellevue and fast market times create strong buyer competition — RealtorFinder puts competitive King County agents in a race to earn your listing.',
        realtor_hook: 'Renton\'s Boeing presence and central King County location create consistent buyer demand — RealtorFinder connects you with motivated sellers between Seattle and Bellevue.',
    },
];
