// cities/wi.js — Wisconsin city data for SEO landing pages

module.exports = [
    {
        slug: 'milwaukee',
        name: 'Milwaukee',
        county: 'Milwaukee',
        state: 'WI',
        zip: '53202',
        population: '577000',
        median_price: '$210,000',
        price_trend: 'up 9%',
        avg_dom: 20,
        description: 'Milwaukee is one of America\'s most overlooked urban gems — a city of 30 distinct neighborhoods from the Victorian mansions of Yankee Hill to the craft brewery revival of Walker\'s Point to the lakefront vitality of the Third Ward, anchored by Johnson Controls, Harley-Davidson, and Rockwell Automation, with home prices that offer first-time buyers an entry point that coastal migrants simply cannot believe.',
        neighborhoods: 'Third Ward, Walker\'s Point, Yankee Hill, Brady Street, Bay View, Riverwest, East Side',
        nearby: 'Wauwatosa, West Allis, Shorewood, Bay View, Cudahy',
        seller_hook: 'Milwaukee\'s rising national profile and fast-appreciating neighborhoods mean motivated sellers who choose the right agent see real results — let competing Milwaukee County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Milwaukee\'s diverse neighborhoods and rising investor attention create abundant listing opportunities for agents who know this market — RealtorFinder connects you with motivated sellers across Milwaukee County.',
    },
    {
        slug: 'wauwatosa',
        name: 'Wauwatosa',
        county: 'Milwaukee',
        state: 'WI',
        zip: '53213',
        population: '48000',
        median_price: '$380,000',
        price_trend: 'up 8%',
        avg_dom: 14,
        description: 'Wauwatosa is Milwaukee\'s most coveted inner suburb — the Milwaukee Regional Medical Center campus with Children\'s Wisconsin, Froedtert Hospital, and the Medical College of Wisconsin anchors a healthcare economy that drives exceptional demand for the Craftsman bungalows, Tudors, and Colonial Revivals lining Wauwatosa\'s tree-canopied streets in neighborhoods like Hart Park and the Village.',
        neighborhoods: 'Wauwatosa Village, Hart Park, Honey Creek Parkway area, North Avenue corridor, Underwood Avenue corridor',
        nearby: 'Milwaukee, Brookfield, West Allis, Menomonee Falls, Elm Grove',
        seller_hook: 'Wauwatosa\'s medical campus employment and gorgeous historic homes create buyers who compete fiercely for every listing — let realtors on RealtorFinder fight to earn the right to represent you.',
        realtor_hook: 'Wauwatosa\'s fast DOM and medical campus relocation market make it one of Wisconsin\'s most rewarding listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'shorewood-wi',
        name: 'Shorewood',
        county: 'Milwaukee',
        state: 'WI',
        zip: '53211',
        population: '14000',
        median_price: '$480,000',
        price_trend: 'up 7%',
        avg_dom: 15,
        description: 'Shorewood is one of Wisconsin\'s most architecturally distinguished inner suburbs — a dense, walkable village of Tudor Revivals, American Foursquares, and Craftsman bungalows directly north of Milwaukee along Lake Michigan, with Shorewood School District consistently ranked among Wisconsin\'s best, a vibrant North Oakland Avenue retail strip, and a community energy that draws UW-Milwaukee professors and young professionals alike.',
        neighborhoods: 'North Oakland corridor, Bartlett Avenue area, Capitol Drive corridor, Whitefish Bay border, Milwaukee border',
        nearby: 'Whitefish Bay, Milwaukee, Fox Point, Glendale, Bayside',
        seller_hook: 'Shorewood\'s architectural prestige and walkable village character create buyers who are passionate about living here — let competing realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Shorewood\'s limited inventory and fast DOM make every listing highly competitive — RealtorFinder connects you with motivated sellers in this premier Milwaukee County village.',
    },
    {
        slug: 'whitefish-bay',
        name: 'Whitefish Bay',
        county: 'Milwaukee',
        state: 'WI',
        zip: '53217',
        population: '14000',
        median_price: '$520,000',
        price_trend: 'up 6%',
        avg_dom: 17,
        description: 'Whitefish Bay is Milwaukee\'s lakeside prestige address — a tightly knit village community on Lake Michigan with larger lots than neighboring Shorewood, a beautiful lakefront park system, and Whitefish Bay School District ranked among Wisconsin\'s very finest, attracting Milwaukee\'s top attorneys, physicians, and executives who prize proximity to the city alongside suburban tranquility.',
        neighborhoods: 'Silver Spring Drive corridor, Lake Drive estates, Montrose Avenue area, Silver Spring area, Bayside border',
        nearby: 'Shorewood, Fox Point, Bayside, Glendale, Milwaukee',
        seller_hook: 'Whitefish Bay\'s lakeside prestige and elite school district command premium prices for sellers in the best neighborhoods — let competing realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Whitefish Bay\'s high price points and limited inventory create outstanding listing opportunities for qualified agents — RealtorFinder connects you with motivated sellers along Milwaukee\'s North Shore.',
    },
    {
        slug: 'mequon',
        name: 'Mequon',
        county: 'Ozaukee',
        state: 'WI',
        zip: '53092',
        population: '24000',
        median_price: '$620,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Mequon is Ozaukee County\'s most prestigious community and Metro Milwaukee\'s northern estate destination — a spacious city of wooded properties on generous lots along Lake Michigan and the Milwaukee River, anchored by Concordia University Wisconsin, with Mequon-Thiensville School District highly regarded across the region and an executive housing market that attracts Wisconsin\'s most affluent families.',
        neighborhoods: 'Mequon Road corridor, Lake Michigan estates, Milwaukee River corridor, Cedarburg border, Grafton border',
        nearby: 'Cedarburg, Thiensville, Grafton, Fox Point, Bayside',
        seller_hook: 'Mequon\'s estate properties and Ozaukee County prestige attract serious buyers willing to pay for the right home — let competing realtors on RealtorFinder earn the right to represent your listing.',
        realtor_hook: 'Mequon\'s high price points and estate lot market create significant earning opportunities for qualified agents — RealtorFinder connects you with motivated sellers in this premier Ozaukee County market.',
    },
    {
        slug: 'brookfield-wi',
        name: 'Brookfield',
        county: 'Waukesha',
        state: 'WI',
        zip: '53045',
        population: '40000',
        median_price: '$440,000',
        price_trend: 'up 7%',
        avg_dom: 18,
        description: 'Brookfield is Waukesha County\'s leading commercial and residential hub — a prosperous western Milwaukee suburb anchored by Brookfield Square Mall and a dense corridor of corporate offices along Bluemound Road, with Elmbrook School District consistently ranked among Wisconsin\'s best and an executive housing market of custom colonials and contemporary homes that draws Milwaukee\'s top professionals.',
        neighborhoods: 'Brookfield Square area, Bluemound Road corridor, Executive Drive area, Elm Grove border, Pewaukee border',
        nearby: 'Elm Grove, Pewaukee, Waukesha, New Berlin, Menomonee Falls',
        seller_hook: 'Brookfield\'s Elmbrook Schools and corporate employment base create buyers ready to compete for great listings — let competing Waukesha County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Brookfield\'s high price points and corporate relocation market produce strong listing demand for agents — RealtorFinder connects you with motivated sellers in this Waukesha County powerhouse.',
    },
    {
        slug: 'elm-grove',
        name: 'Elm Grove',
        county: 'Waukesha',
        state: 'WI',
        zip: '53122',
        population: '6000',
        median_price: '$620,000',
        price_trend: 'up 6%',
        avg_dom: 22,
        description: 'Elm Grove is one of Metro Milwaukee\'s most exclusive small villages — a wooded enclave of estate properties and architecturally significant homes along Elm Grove Road, served by the highly regarded Elmbrook School District, with an intimate community character and convenient Bluemound Road access to Milwaukee that has kept this one of Wisconsin\'s consistently most expensive and desirable residential addresses.',
        neighborhoods: 'Elm Grove Village, Elmbrook area, Watertown Plank Road corridor, Brookfield border, Wauwatosa border',
        nearby: 'Brookfield, Wauwatosa, Pewaukee, New Berlin, Menomonee Falls',
        seller_hook: 'Elm Grove\'s village prestige and limited inventory give sellers exceptional positioning — let competing realtors on RealtorFinder earn the right to represent your estate property.',
        realtor_hook: 'Elm Grove\'s high price points and small inventory create significant per-listing earnings for qualified agents — RealtorFinder connects you with motivated sellers in this premier Waukesha County village.',
    },
    {
        slug: 'waukesha-wi',
        name: 'Waukesha',
        county: 'Waukesha',
        state: 'WI',
        zip: '53186',
        population: '72000',
        median_price: '$310,000',
        price_trend: 'up 8%',
        avg_dom: 20,
        description: 'Waukesha is Waukesha County\'s county seat and largest city — a growing community with a revitalized downtown along the Fox River, strong manufacturing and healthcare employment anchored by ProHealth Care, and affordable neighborhoods that offer Milwaukee-area workers a quality suburban lifestyle at prices well below the North Shore and inner suburb premium.',
        neighborhoods: 'Downtown Waukesha, Fox River corridor, Brookfield border, New Berlin border, Pewaukee border',
        nearby: 'Brookfield, Pewaukee, New Berlin, Oconomowoc, Elm Grove',
        seller_hook: 'Waukesha\'s affordability and downtown revitalization attract buyers from across the metro — let competing Waukesha County realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Waukesha\'s large population and accessible prices create consistent listing activity for agents — RealtorFinder connects you with motivated sellers across Waukesha County.',
    },
    {
        slug: 'pewaukee',
        name: 'Pewaukee',
        county: 'Waukesha',
        state: 'WI',
        zip: '53072',
        population: '15000',
        median_price: '$380,000',
        price_trend: 'up 7%',
        avg_dom: 21,
        description: 'Pewaukee is one of Waukesha County\'s most livable lake communities — the shores of Pewaukee Lake anchor a recreational lifestyle of boating, fishing, and lakeside dining, while Pewaukee School District\'s strong academic reputation, convenient I-94 access connecting residents to Milwaukee, and a mix of lakefront estates and affordable neighborhoods inland give buyers a range of options unavailable elsewhere in the county.',
        neighborhoods: 'Pewaukee Lake shoreline, Village of Pewaukee, Pewaukee Road corridor, Delafield border, North Lake area',
        nearby: 'Waukesha, Brookfield, Oconomowoc, Delafield, Hartland',
        seller_hook: 'Pewaukee\'s lakefront lifestyle and school reputation create buyers motivated to act on good listings — let competing Waukesha County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Pewaukee\'s lakefront and non-lakefront market segments create diverse listing opportunities for agents — RealtorFinder connects you with motivated sellers in this growing Waukesha County community.',
    },
    {
        slug: 'new-berlin',
        name: 'New Berlin',
        county: 'Waukesha',
        state: 'WI',
        zip: '53151',
        population: '40000',
        median_price: '$360,000',
        price_trend: 'up 8%',
        avg_dom: 19,
        description: 'New Berlin is one of Waukesha County\'s most family-friendly southern suburbs — a rapidly growing community of newer subdivisions and established neighborhoods served by New Berlin School District and Elmbrook School District, extensive park and trail systems, and convenient I-894 and I-894 access connecting residents to Milwaukee while maintaining a suburban character that draws young families from across the metro.',
        neighborhoods: 'New Berlin Hills area, National Avenue corridor, Calhoun Road area, Greenfield border, Muskego border',
        nearby: 'Waukesha, Brookfield, Greenfield, Muskego, Hales Corners',
        seller_hook: 'New Berlin\'s family reputation and affordable prices create a deep pool of motivated buyers — let competing realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'New Berlin\'s growing population and family buyer demand create consistent listing volume for agents — RealtorFinder connects you with motivated sellers across southern Waukesha County.',
    },
    {
        slug: 'madison',
        name: 'Madison',
        county: 'Dane',
        state: 'WI',
        zip: '53703',
        population: '269000',
        median_price: '$380,000',
        price_trend: 'up 8%',
        avg_dom: 13,
        description: 'Madison is one of America\'s most livable college cities elevated to a full innovation economy — the University of Wisconsin anchors a research and biotech ecosystem alongside Epic Systems, American Family Insurance, and a thriving startup scene, while neighborhoods like Wingra, Dudgeon-Monroe, and Marquette offer architectural character and walkability on the isthmus between two beautiful glacial lakes.',
        neighborhoods: 'Isthmus, Wingra, Dudgeon-Monroe, Marquette, Willy Street, Near East Side',
        nearby: 'Middleton, Sun Prairie, Verona, Fitchburg, Monona',
        seller_hook: 'Madison\'s university economy and tech sector create year-round buyer demand at prices that reward sellers who choose the right agent — let competing Dane County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Madison\'s fast DOM and strong UW relocation market make it one of Wisconsin\'s most rewarding listing cities for motivated agents — RealtorFinder connects you with sellers ready to move.',
    },
    {
        slug: 'middleton-wi',
        name: 'Middleton',
        county: 'Dane',
        state: 'WI',
        zip: '53562',
        population: '22000',
        median_price: '$480,000',
        price_trend: 'up 7%',
        avg_dom: 15,
        description: 'Middleton is Madison\'s premier western suburb and home to some of Dane County\'s most sought-after neighborhoods — an independent city with its own vibrant downtown, Epic Systems\' massive campus serving as an economic anchor for highly educated tech workers, Middleton-Cross Plains Area School District consistently among Wisconsin\'s finest, and a community energy that consistently ranks among America\'s best places to live.',
        neighborhoods: 'Downtown Middleton, Pheasant Branch Creek corridor, Greenway Station area, Epic campus corridor, Waunakee border',
        nearby: 'Madison, Waunakee, Cross Plains, Verona, Fitchburg',
        seller_hook: 'Middleton\'s Epic employment and top-ranked schools create buyers who act quickly and pay competitively — let realtors on RealtorFinder fight to earn the right to represent your home.',
        realtor_hook: 'Middleton\'s Epic relocation pipeline and premium prices create outstanding listing opportunities for agents — RealtorFinder connects you with motivated sellers in this Dane County gem.',
    },
    {
        slug: 'sun-prairie',
        name: 'Sun Prairie',
        county: 'Dane',
        state: 'WI',
        zip: '53590',
        population: '36000',
        median_price: '$360,000',
        price_trend: 'up 9%',
        avg_dom: 17,
        description: 'Sun Prairie is Dane County\'s fastest-growing city and Madison\'s most affordable viable alternative — a rapidly developing community with a charming historic downtown, Sun Prairie Area School District with strong academics, and newer subdivisions of craftsman and contemporary homes that attract Epic Systems employees, UW-Madison staff, and young families who need Madison proximity without Madison prices.',
        neighborhoods: 'Historic Downtown, Grand Avenue corridor, Bird Street area, Burke Township border, Columbus Road corridor',
        nearby: 'Madison, Cottage Grove, De Forest, Marshall, Waterloo',
        seller_hook: 'Sun Prairie\'s rapid growth and Madison overflow demand create buyers eager to compete for good listings — let competing Dane County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Sun Prairie\'s explosive growth and Epic/UW spillover demand create one of Dane County\'s most active listing markets — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'verona-wi',
        name: 'Verona',
        county: 'Dane',
        state: 'WI',
        zip: '53593',
        population: '15000',
        median_price: '$440,000',
        price_trend: 'up 8%',
        avg_dom: 14,
        description: 'Verona is best known as home to Epic Systems\' extraordinary 1,000-acre campus — the world\'s largest private healthcare software company employs over 13,000 people and drives exceptional housing demand in Verona, a community that also offers charming Sugar River Trail access, Verona Area School District highly regarded across the state, and a neighborhood character that blends small-town charm with technology-sector energy.',
        neighborhoods: 'Downtown Verona, Epic campus corridor, Sugar River Trail area, Fitchburg border, Madison border',
        nearby: 'Fitchburg, Madison, Middleton, Mt. Horeb, Belleville',
        seller_hook: 'Verona\'s Epic Systems employment creates the most powerful local buyer pool in Wisconsin — let competing Dane County realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Verona\'s Epic relocation demand and fast DOM create one of Wisconsin\'s most rewarding listing markets for agents — RealtorFinder connects you with motivated sellers.',
    },
    {
        slug: 'fitchburg-wi',
        name: 'Fitchburg',
        county: 'Dane',
        state: 'WI',
        zip: '53711',
        population: '31000',
        median_price: '$390,000',
        price_trend: 'up 8%',
        avg_dom: 15,
        description: 'Fitchburg is Dane County\'s southern growth corridor — a rapidly developing city adjacent to Madison\'s south side and Verona\'s Epic campus, with newer subdivisions and townhome communities along Fish Hatchery Road attracting young professionals, a growing biotech and research employment presence, and excellent access to Madison\'s amenities at price points that consistently undercut Madison and Middleton.',
        neighborhoods: 'McKee Road corridor, Fish Hatchery Road area, Lacy Road corridor, Verona border, Madison border',
        nearby: 'Madison, Verona, Oregon WI, McFarland, Monona',
        seller_hook: 'Fitchburg\'s Epic and Madison proximity create motivated buyers priced out of Verona and Middleton — let competing realtors on RealtorFinder earn the right to list your home.',
        realtor_hook: 'Fitchburg\'s rapid growth and overflow demand from Verona and Madison create consistent listing activity — RealtorFinder connects you with motivated sellers in this Dane County growth community.',
    },
    {
        slug: 'green-bay',
        name: 'Green Bay',
        county: 'Brown',
        state: 'WI',
        zip: '54301',
        population: '109000',
        median_price: '$220,000',
        price_trend: 'up 9%',
        avg_dom: 19,
        description: 'Green Bay is Wisconsin\'s third-largest city and the world\'s smallest market supporting an NFL franchise — the Packers\' Lambeau Field anchors a community identity unlike any other American city, while the Port of Green Bay, a growing healthcare sector anchored by HSHS St. Vincent and Bellin Health, and neighborhoods of affordable bungalows and colonials make it one of the Midwest\'s most livable mid-size cities.',
        neighborhoods: 'Astor Park, Olde Main Street, Titletown District, De Pere border, Allouez border',
        nearby: 'De Pere, Ashwaubenon, Howard, Allouez, Pulaski',
        seller_hook: 'Green Bay\'s Packers culture and rising prices create buyers motivated to plant roots in this one-of-a-kind community — let competing Brown County realtors on RealtorFinder earn your listing.',
        realtor_hook: 'Green Bay\'s large population and growing economy create consistent listing opportunities for agents who understand this unique market — RealtorFinder connects you with motivated sellers across Brown County.',
    },
];
