// cities/wv.js — West Virginia city data for SEO landing pages

module.exports = [
    {
        slug: 'charleston-wv',
        name: 'Charleston',
        county: 'Kanawha',
        state: 'WV',
        zip: '25301',
        population: '48,000',
        median_price: '$155,000',
        price_trend: 'up 4%',
        avg_dom: 42,
        description: 'Charleston is West Virginia\'s state capital and largest city — a Kanawha River hub where state government, CAMC and Thomas Memorial hospitals, and a chemical manufacturing legacy create housing demand from government workers and medical professionals who find some of the Appalachian region\'s most affordable historic Victorian homes, colonials, and brick ranches on tree-lined streets above the river.',
        neighborhoods: 'South Hills, Kanawha City, Elk City, St. Albans, Cross Lanes',
        nearby: 'St. Albans, South Charleston, Nitro, Dunbar, Cross Lanes',
        seller_hook: 'Charleston\'s state capital stability and affordable prices attract a reliable buyer pool — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Charleston\'s government and medical sector create consistent listing activity at some of the region\'s most accessible prices — find sellers through RealtorFinder.',
    },
    {
        slug: 'huntington-wv',
        name: 'Huntington',
        county: 'Cabell',
        state: 'WV',
        zip: '25701',
        population: '44,000',
        median_price: '$130,000',
        price_trend: 'up 3%',
        avg_dom: 48,
        description: 'Huntington is West Virginia\'s second-largest city and home to Marshall University — a tri-state Ohio River community where Marshall\'s Thundering Herd athletics, Cabell Huntington Hospital, and AK Steel legacy create housing demand among students, medical workers, and buyers seeking Appalachian homeownership at some of the nation\'s lowest price points, with craftsman bungalows and Victorians available under $100K.',
        neighborhoods: 'Southside, Altizer, Guyandotte, Barboursville, Milton',
        nearby: 'Ashland KY, Ironton OH, Barboursville, Milton, Wayne',
        seller_hook: 'Huntington\'s Marshall enrollment and medical hub create steady buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Huntington\'s tri-state market and ultra-affordable prices generate consistent listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'morgantown-wv',
        name: 'Morgantown',
        county: 'Monongalia',
        state: 'WV',
        zip: '26505',
        population: '32,000',
        median_price: '$235,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Morgantown is home to West Virginia University and one of Appalachia\'s most vibrant college towns — a Big 12 university city on the Monongahela River where WVU\'s 28,000 students, a nationally recognized PRT transit system, and a growing biomedical research park create strong rental investment demand and steady appreciation in a market that benefits from consistent out-of-state student family buying.',
        neighborhoods: 'Suncrest, Evansdale, Westover, Star City, Cheat Lake',
        nearby: 'Westover, Star City, Granville, Fairmont, Clarksburg',
        seller_hook: 'Morgantown\'s WVU enrollment and Big 12 athletics drive competitive buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Morgantown\'s university market and investment property demand create active listing conditions — find sellers through RealtorFinder.',
    },
    {
        slug: 'parkersburg-wv',
        name: 'Parkersburg',
        county: 'Wood',
        state: 'WV',
        zip: '26101',
        population: '29,000',
        median_price: '$140,000',
        price_trend: 'up 3%',
        avg_dom: 45,
        description: 'Parkersburg is northwestern West Virginia\'s commercial hub on the Ohio River — a city with a DuPont chemical manufacturing legacy, West Virginia University at Parkersburg, and an emerging downtown arts district that offers investors and first-time buyers some of the most affordable brick homes in the entire Ohio Valley, with strong rental yields relative to purchase prices.',
        neighborhoods: 'Vienna, Williamstown, Belpre OH, Davisville, Waverly',
        nearby: 'Vienna, Williamstown, Belpre OH, Ravenswood, Spencer',
        seller_hook: 'Parkersburg\'s Ohio River economy and affordable prices attract value-seeking buyers — let RealtorFinder agents compete to list your property.',
        realtor_hook: 'Parkersburg\'s affordable market and Ohio River location create consistent listing volume — find sellers through RealtorFinder.',
    },
    {
        slug: 'wheeling-wv',
        name: 'Wheeling',
        county: 'Ohio',
        state: 'WV',
        zip: '26003',
        population: '26,000',
        median_price: '$130,000',
        price_trend: 'up 3%',
        avg_dom: 48,
        description: 'Wheeling is West Virginia\'s northern panhandle gateway — a historic Ohio River city where Wheeling University, a revitalized Centre Market arts district, and proximity to Pittsburgh attract buyers seeking the most affordable homeownership in the greater Pittsburgh commuter shed, with 19th-century Victorian mansions and brick row homes available at prices that are nearly impossible to find elsewhere in the mid-Atlantic region.',
        neighborhoods: 'Elm Grove, Warwood, Woodsdale, Triadelphia, Bethlehem',
        nearby: 'Weirton, Steubenville OH, Moundsville, St. Clairsville OH, Benwood',
        seller_hook: 'Wheeling\'s Pittsburgh proximity and affordable Victorian homes attract buyers from across the region — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Wheeling\'s Northern Panhandle market and investment-grade prices create consistent listing activity — connect with sellers through RealtorFinder.',
    },
];
