// cities/wy.js — Wyoming city data for SEO landing pages

module.exports = [
    {
        slug: 'cheyenne-wy',
        name: 'Cheyenne',
        county: 'Laramie',
        state: 'WY',
        zip: '82001',
        population: '65,000',
        median_price: '$330,000',
        price_trend: 'up 6%',
        avg_dom: 28,
        description: 'Cheyenne is Wyoming\'s state capital and Magic City of the Plains — a government and military hub where F.E. Warren Air Force Base, Wyoming\'s state agencies, and Wyoming\'s zero income tax attract Colorado Front Range commuters and remote workers seeking large lots and affordable homeownership just 90 minutes north of Denver, with Frontier Days rodeo culture adding a uniquely western character to the housing market.',
        neighborhoods: 'South Greeley Highway, Crow Creek, Prairie Wind, Fox Farm, Burns',
        nearby: 'Laramie, Fort Collins CO, Greeley CO, Pine Bluffs, Torrington',
        seller_hook: 'Cheyenne\'s Colorado commuter market and tax advantages drive strong buyer demand — let top agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Cheyenne\'s F.E. Warren AFB community and Denver proximity create active listing conditions — find motivated sellers through RealtorFinder.',
    },
    {
        slug: 'casper-wy',
        name: 'Casper',
        county: 'Natrona',
        state: 'WY',
        zip: '82601',
        population: '59,000',
        median_price: '$295,000',
        price_trend: 'up 5%',
        avg_dom: 32,
        description: 'Casper is Wyoming\'s second-largest city and oil country\'s commercial capital — a North Platte River energy hub where Wyoming\'s Permian and Powder River Basin oil and gas sector, Casper College, and access to world-class trout fishing and hunting create housing demand from energy workers, outdoor enthusiasts, and families seeking Wyoming ranch-style living at prices far below the Jackson Hole resort market.',
        neighborhoods: 'Mills, Evansville, Bar Nunn, Midwest, Alcova',
        nearby: 'Mills, Evansville, Bar Nunn, Douglas, Glenrock',
        seller_hook: 'Casper\'s energy sector and Wyoming lifestyle attract consistent buyer demand — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Casper\'s oil and gas economy and outdoor recreation appeal create steady listing activity — find sellers through RealtorFinder.',
    },
    {
        slug: 'laramie-wy',
        name: 'Laramie',
        county: 'Albany',
        state: 'WY',
        zip: '82070',
        population: '33,000',
        median_price: '$320,000',
        price_trend: 'up 6%',
        avg_dom: 26,
        description: 'Laramie is home to the University of Wyoming and sits at 7,200 feet on the Laramie Plains — a high plains college city where UW Cowboys athletics, a growing renewable energy research sector, Wyoming\'s only law and medical schools, and 300 sunny days per year create housing demand from students, faculty, and remote workers drawn by the combination of college-town culture and pristine mountain proximity.',
        neighborhoods: 'East Laramie, West Laramie, University, Boswell, Vedauwoo',
        nearby: 'Cheyenne, Rock River, Bosler, Wheatland, Centennial',
        seller_hook: 'Laramie\'s UW enrollment and high-altitude lifestyle attract consistent buyer demand — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Laramie\'s university market and Wyoming outdoor appeal create steady listing activity — connect with sellers through RealtorFinder.',
    },
    {
        slug: 'gillette-wy',
        name: 'Gillette',
        county: 'Campbell',
        state: 'WY',
        zip: '82716',
        population: '32,000',
        median_price: '$275,000',
        price_trend: 'up 4%',
        avg_dom: 35,
        description: 'Gillette is the Energy Capital of the Nation and the heart of Wyoming\'s Powder River Basin coal country — a boom-bust energy city where Arch Coal and Peabody mining operations, high energy sector wages, and a low cost of living create strong demand for affordable ranch-style homes and investment properties among mining families and oil field workers who earn well above Wyoming\'s already-strong state median.',
        neighborhoods: 'Antelope Valley, Rawhide, Rozet, Wright, Moorcroft',
        nearby: 'Wright, Moorcroft, Sundance, Buffalo, Newcastle',
        seller_hook: 'Gillette\'s energy sector wages and coal country employment create a reliable buyer pool — let RealtorFinder agents compete to list your home.',
        realtor_hook: 'Gillette\'s mining economy and affordable prices create consistent listing opportunities in Wyoming\'s energy heartland — find sellers through RealtorFinder.',
    },
    {
        slug: 'rock-springs-wy',
        name: 'Rock Springs',
        county: 'Sweetwater',
        state: 'WY',
        zip: '82901',
        population: '23,000',
        median_price: '$270,000',
        price_trend: 'up 4%',
        avg_dom: 38,
        description: 'Rock Springs is Wyoming\'s southwestern energy hub in Sweetwater County — a trona mining and natural gas city where Genesis Alkali and OCI Wyoming operations, Western Wyoming Community College, and access to Flaming Gorge National Recreation Area create housing demand from mining workers and outdoor recreationalists seeking affordable high-desert homeownership with Wyoming\'s zero income tax advantage.',
        neighborhoods: 'Green River, Superior, Eden, Farson, Reliance',
        nearby: 'Green River, Superior, Evanston, Lyman, Kemmerer',
        seller_hook: 'Rock Springs\' mining economy and zero-tax appeal attract motivated buyers — let agents compete for your listing on RealtorFinder.',
        realtor_hook: 'Rock Springs\' energy sector and Sweetwater County market create consistent listing activity — find sellers through RealtorFinder.',
    },
];
